// @ts-nocheck
/**
 * Batch 18: grade 5 reading — literature, informational and foundational.
 *
 * Completes the 2-5 block, so an upper-elementary teacher is served across
 * every grade they might be assigned.
 *
 * A difference from batches 9 to 17 worth recording: those were built from
 * the Unpacking Standards decks, so their misconceptions were observed in
 * real classrooms. There is no grade 5 deck, so these are authored from the
 * standards themselves. They are the errors grade 5 teachers report most —
 * summary standing in for theme, quotation marks around a paraphrase, point
 * of view named but its effect unexamined — but they are not drawn from the
 * same source, and should be replaced if a grade 5 deck appears.
 *
 * American spellings throughout.
 *
 *   bun run scripts/seed-standards-batch-18.ts
 */
import { seedStandardsBatch } from "./lib/seed-standards-batch";

const standardsData = [
  {
    code: "RL.5.2",
    name: "Theme from how characters respond",
    plain_reading:
      "Determine a theme of a story, drama, or poem from details in the text, including how characters respond to challenges or how the speaker reflects upon a topic; summarize the text.",
    learning_target: "I can find the theme in how a character responded, not just in what happened.",
    skills: ["Theme", "Character Response", "Summary"],
    science_tags: ["elaboration", "retrieval"],
    match_keys: ["determine a theme", "respond to challenges", "speaker reflects", "summarize", "fifth grade"],
  },
  {
    code: "RL.5.3",
    name: "Compare characters on one dimension",
    plain_reading:
      "Compare and contrast two or more characters, settings, or events in a story or drama, drawing on specific details in the text.",
    learning_target: "I can compare two characters on one thing at a time, with evidence for both.",
    skills: ["Compare and Contrast", "Specific Detail", "Character Analysis"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["compare and contrast characters", "settings events", "specific details", "drama"],
  },
  {
    code: "RL.5.4",
    name: "Metaphors and similes in context",
    plain_reading:
      "Determine the meaning of words and phrases as they are used in a text, including figurative language such as metaphors and similes.",
    learning_target: "I can say what a metaphor claims, not just that it is a metaphor.",
    skills: ["Figurative Language", "Metaphor and Simile", "Context"],
    science_tags: ["elaboration", "metacognition"],
    match_keys: ["figurative language", "metaphors and similes", "meaning of words and phrases", "context"],
  },
  {
    code: "RL.5.5",
    name: "How the chapters fit together",
    plain_reading:
      "Explain how a series of chapters, scenes, or stanzas fits together to provide the overall structure of a particular story, drama, or poem.",
    learning_target: "I can say what each chapter does for the shape of the whole book.",
    skills: ["Overall Structure", "Successive Parts", "Genre Structure"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["series of chapters scenes stanzas", "overall structure", "fits together", "story drama poem"],
  },
  {
    code: "RL.5.6",
    name: "What the narrator's position does",
    plain_reading:
      "Describe how a narrator's or speaker's point of view influences how events are described.",
    learning_target: "I can show how the telling would change with a different narrator.",
    skills: ["Point of View", "Narrative Influence", "Perspective"],
    science_tags: ["elaboration", "metacognition"],
    match_keys: ["narrator's point of view", "speaker", "influences how events are described", "perspective"],
  },
  {
    code: "RL.5.7",
    name: "What the visuals add to tone",
    plain_reading:
      "Analyze how visual and multimedia elements contribute to the meaning, tone, or beauty of a text, such as a graphic novel or multimedia presentation.",
    learning_target: "I can explain what the pictures do to the mood, not just what they show.",
    skills: ["Visual Elements", "Tone", "Multimedia"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["visual and multimedia elements", "meaning tone or beauty", "graphic novel", "multimedia presentation"],
  },
  {
    code: "RL.5.9",
    name: "Same genre, different approach",
    plain_reading:
      "Compare and contrast stories in the same genre on their approaches to similar themes and topics.",
    learning_target: "I can compare how two books in one genre handle the same idea differently.",
    skills: ["Genre Comparison", "Theme", "Approach"],
    science_tags: ["dual-coding", "interleaving"],
    match_keys: ["stories in the same genre", "approaches to similar themes", "compare and contrast", "topics"],
  },
  {
    code: "RL.5.10",
    name: "Grade-level literature, on your own",
    plain_reading:
      "By the end of the year, read and comprehend literature at the high end of the grades 4-5 text complexity band independently and proficiently.",
    learning_target: "I can read a demanding book alone and show that I understood it.",
    skills: ["Independent Reading", "Comprehension", "Stamina"],
    science_tags: ["metacognition", "spaced"],
    match_keys: ["high end of the grades 4-5 band", "independently and proficiently", "stamina", "complexity"],
  },
  {
    code: "RI.5.1",
    name: "Quote accurately, and mark the inference",
    plain_reading:
      "Quote accurately from a text when explaining what the text says explicitly and when drawing inferences from the text.",
    learning_target: "I can quote the exact words and say which part was my own inference.",
    skills: ["Accurate Quotation", "Inference", "Explicit Meaning"],
    science_tags: ["metacognition", "retrieval"],
    match_keys: ["quote accurately", "explicitly", "drawing inferences", "evidence", "fifth grade"],
  },
  {
    code: "RI.5.3",
    name: "How two ideas act on each other",
    plain_reading:
      "Explain the relationships or interactions between two or more individuals, events, ideas, or concepts in a historical, scientific, or technical text based on specific information in the text.",
    learning_target: "I can explain how two things in the text affected each other.",
    skills: ["Relationships", "Interactions", "Technical Text"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["relationships or interactions", "individuals events ideas concepts", "historical scientific technical"],
  },
  {
    code: "RI.5.4",
    name: "Subject vocabulary in grade 5 texts",
    plain_reading:
      "Determine the meaning of general academic and domain-specific words and phrases in a text relevant to a grade 5 topic or subject area.",
    learning_target: "I can work out a subject word and check the meaning fits.",
    skills: ["Domain Vocabulary", "Academic Language", "Verification"],
    science_tags: ["elaboration", "interleaving"],
    match_keys: ["general academic and domain-specific", "grade 5 topic", "context", "reference materials"],
  },
  {
    code: "RI.5.6",
    name: "Several accounts of one event",
    plain_reading:
      "Analyze multiple accounts of the same event or topic, noting important similarities and differences in the point of view they represent.",
    learning_target: "I can say what each account emphasizes and why that differs.",
    skills: ["Multiple Accounts", "Point of View", "Comparison"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["multiple accounts", "same event or topic", "similarities and differences", "point of view"],
  },
  {
    code: "RI.5.7",
    name: "Find the answer fast, across sources",
    plain_reading:
      "Draw on information from multiple print or digital sources, demonstrating the ability to locate an answer to a question quickly or to solve a problem efficiently.",
    learning_target: "I can search several sources and find the answer without reading everything.",
    skills: ["Multiple Sources", "Efficient Search", "Locating Information"],
    science_tags: ["metacognition", "interleaving"],
    match_keys: ["multiple print or digital sources", "locate an answer quickly", "solve a problem efficiently"],
  },
  {
    code: "RI.5.8",
    name: "Which reason supports which point",
    plain_reading:
      "Explain how an author uses reasons and evidence to support particular points in a text, identifying which reasons and evidence support which point(s).",
    learning_target: "I can match each piece of evidence to the point it actually supports.",
    skills: ["Reasons and Evidence", "Matching Support", "Author's Argument"],
    science_tags: ["dual-coding", "metacognition"],
    match_keys: ["reasons and evidence", "support particular points", "which evidence supports which point", "argument"],
  },
  {
    code: "RI.5.9",
    name: "Several texts, one account",
    plain_reading:
      "Integrate information from several texts on the same topic in order to write or speak about the subject knowledgeably.",
    learning_target: "I can write one account from three sources rather than three summaries.",
    skills: ["Integration", "Synthesis", "Multiple Sources"],
    science_tags: ["dual-coding", "interleaving"],
    match_keys: ["integrate information from several texts", "knowledgeably", "synthesize", "same topic"],
  },
  {
    code: "RI.5.10",
    name: "Grade-level nonfiction, on your own",
    plain_reading:
      "By the end of the year, read and comprehend informational texts at the high end of the grades 4-5 text complexity band independently and proficiently.",
    learning_target: "I can work through dense nonfiction without giving up on it.",
    skills: ["Nonfiction Comprehension", "Independence", "Stamina"],
    science_tags: ["metacognition", "spaced"],
    match_keys: ["informational texts", "high end of the grades 4-5 band", "independently and proficiently"],
  },
  {
    code: "RF.5.3.A",
    name: "Long words, in and out of context",
    plain_reading:
      "Use combined knowledge of all letter-sound correspondences, syllabication patterns, and morphology to read accurately unfamiliar multisyllabic words in context and out of context.",
    learning_target: "I can read an unfamiliar long word and say what its parts mean.",
    skills: ["Morphology", "Syllabication", "Meaning from Parts"],
    science_tags: ["elaboration", "interleaving"],
    match_keys: ["letter-sound correspondences", "syllabication patterns", "morphology", "multisyllabic", "in and out of context"],
  },
  {
    code: "RF.5.4.A",
    name: "Read for the reason you are reading",
    plain_reading: "Read grade-level text with purpose and understanding.",
    learning_target: "I can match how I read to why I am reading.",
    skills: ["Purpose", "Adjusting Approach", "Monitoring"],
    science_tags: ["metacognition", "interleaving"],
    match_keys: ["purpose and understanding", "adjust approach", "monitor comprehension", "fluency"],
  },
  {
    code: "RF.5.4.B",
    name: "Read aloud so the meaning carries",
    plain_reading:
      "Read grade-level prose and poetry orally with accuracy, appropriate rate, and expression on successive readings.",
    learning_target: "I can read a long sentence in phrases so a listener follows it.",
    skills: ["Accuracy", "Prosody", "Successive Readings"],
    science_tags: ["spaced", "collaborative"],
    match_keys: ["prose and poetry orally", "accuracy rate expression", "successive readings", "phrasing"],
  },
  {
    code: "RF.5.4.C",
    name: "Catch the breakdown, repair it",
    plain_reading:
      "Use context to confirm or self-correct word recognition and understanding, rereading as necessary.",
    learning_target: "I can notice a paragraph that made no sense and go back far enough.",
    skills: ["Self-Correction", "Monitoring", "Rereading"],
    science_tags: ["metacognition", "collaborative"],
    match_keys: ["use context to confirm", "self-correct", "reread as necessary", "monitor comprehension"],
  },
];

const unpacksData = [
  {
    standard_code: "RL.5.2",
    verbs: [
      { word: "Determine", gloss: "work out the theme" },
      { word: "Summarize", gloss: "report the text without judging it" },
    ],
    concepts: ["Theme from response", "Theme versus summary", "Objective summary"],
    vocabulary: [
      { term: "theme", definition: "what the story says about life" },
      { term: "respond", definition: "what a character does about a challenge" },
      { term: "speaker", definition: "the voice in a poem" },
      { term: "summarize", definition: "report the main events without opinion" },
    ],
    prior_skills: ["Determine a theme", "Describe character response", "Write a summary"],
    prior_standards: [{ code: "RL.4.2", text: "Determine a theme from details in the text and summarize" }],
    future_standards: [{ code: "RL.6.2", text: "Determine a theme and how it is conveyed through particular details" }],
    challenges: [
      { problem: "A summary is offered as the theme — what happened rather than what it means", fix: "Two boxes, filled separately. If the sentence names a character, it is a summary" },
      { problem: "Theme is looked for in events rather than in how characters responded", fix: "The standard says how characters respond. Start at the response, not the plot" },
    ],
    mastery_statement: "Student can state a theme drawn from character response and summarize the text separately.",
    ladder: [
      { name: "I can retell the story", descriptor: "Recounts events" },
      { name: "I can summarize it", descriptor: "Reports without judgment" },
      { name: "I can find how they responded", descriptor: "Identifies the response" },
      { name: "I can state the theme", descriptor: "Derives it from the response" },
    ],
  },
  {
    standard_code: "RL.5.3",
    verbs: [
      { word: "Compare", gloss: "find what is shared" },
      { word: "Contrast", gloss: "find what differs" },
      { word: "Draw on", gloss: "use specific details as proof" },
    ],
    concepts: ["Point of comparison", "Specific detail", "Characters, settings, events"],
    vocabulary: [
      { term: "compare", definition: "find what is the same" },
      { term: "contrast", definition: "find what is different" },
      { term: "specific detail", definition: "an exact thing the text says" },
      { term: "drama", definition: "a play, written to be performed" },
    ],
    prior_skills: ["Compare characters with evidence", "Identify traits", "Locate details"],
    prior_standards: [{ code: "RL.4.3", text: "Describe a character, setting or event drawing on specific details" }],
    future_standards: [{ code: "RL.6.3", text: "Describe how a story's plot unfolds and how characters respond or change" }],
    challenges: [
      { problem: "Two characters are described in turn rather than compared", fix: "One dimension per row, both characters in it. Two descriptions stacked is not a comparison" },
      { problem: "Evidence is given for one side only", fix: "Every row needs a detail from each. An empty cell is an unsupported claim" },
    ],
    mastery_statement: "Student can compare two characters on a named dimension with evidence for both.",
    ladder: [
      { name: "I can describe one", descriptor: "Uses details for one character" },
      { name: "I can describe both", descriptor: "Covers two" },
      { name: "I can name the dimension", descriptor: "States what is being compared" },
      { name: "I can evidence both sides", descriptor: "Supports each claim" },
    ],
  },
  {
    standard_code: "RL.5.4",
    verbs: [
      { word: "Determine", gloss: "the meaning here" },
      { word: "Interpret", gloss: "what the comparison claims" },
    ],
    concepts: ["Metaphor and simile", "What a comparison claims", "Context"],
    vocabulary: [
      { term: "metaphor", definition: "a comparison saying one thing is another" },
      { term: "simile", definition: "a comparison using like or as" },
      { term: "figurative", definition: "not meant literally" },
      { term: "context", definition: "the words around it" },
    ],
    prior_skills: ["Explain similes and metaphors", "Use context clues", "Distinguish literal from nonliteral"],
    prior_standards: [{ code: "L.4.5", text: "Explain the meaning of simple similes and metaphors in context" }],
    future_standards: [{ code: "RL.6.4", text: "Determine the meaning of words including figurative and connotative meanings" }],
    challenges: [
      { problem: "The device is labelled and the meaning never given", fix: "Naming it is not reading it. Say what the comparison claims — a heart of stone claims coldness, not geology" },
      { problem: "Figurative meaning is guessed without checking the sentence", fix: "Substitute the plain meaning back and read it" },
    ],
    mastery_statement: "Student can state what a metaphor or simile claims and check it against the text.",
    ladder: [
      { name: "I can spot the comparison", descriptor: "Identifies the device" },
      { name: "I can name it", descriptor: "Distinguishes metaphor from simile" },
      { name: "I can say what it claims", descriptor: "Interprets the meaning" },
      { name: "I can check it fits", descriptor: "Verifies against context" },
    ],
  },
  {
    standard_code: "RL.5.5",
    verbs: [
      { word: "Explain", gloss: "how the parts fit together" },
      { word: "Analyze", gloss: "what each part does for the whole" },
    ],
    concepts: ["Overall structure", "Function of a part", "Genre forms"],
    vocabulary: [
      { term: "structure", definition: "the shape the parts make together" },
      { term: "chapter", definition: "a division of a novel" },
      { term: "scene", definition: "a division of a play" },
      { term: "stanza", definition: "a group of lines in a poem" },
    ],
    prior_skills: ["Name structural parts", "Explain genre differences", "Summarize a chapter"],
    prior_standards: [{ code: "RL.4.5", text: "Explain major differences between poems, drama and prose" }],
    future_standards: [{ code: "RL.6.5", text: "Analyze how a particular sentence, chapter or scene fits into the overall structure" }],
    challenges: [
      { problem: "Chapters are summarized one by one instead of their function being named", fix: "Content words banned. Say what the chapter does — introduces, complicates, resolves" },
      { problem: "Structure is described only as beginning, middle and end", fix: "Ask what would break if two chapters swapped places" },
    ],
    mastery_statement: "Student can explain what each part contributes to the structure of the whole text.",
    ladder: [
      { name: "I can summarize a chapter", descriptor: "Understands the part" },
      { name: "I can put them in order", descriptor: "Sees the sequence" },
      { name: "I can name each one's job", descriptor: "Identifies function" },
      { name: "I can explain the shape", descriptor: "Describes overall structure" },
    ],
  },
  {
    standard_code: "RL.5.6",
    verbs: [
      { word: "Describe", gloss: "how the point of view shapes the telling" },
      { word: "Analyze", gloss: "what a different narrator would change" },
    ],
    concepts: ["Narrator influence", "What is withheld", "Speaker in poetry"],
    vocabulary: [
      { term: "point of view", definition: "whose eyes the story comes through" },
      { term: "narrator", definition: "the voice telling it" },
      { term: "speaker", definition: "the voice in a poem" },
      { term: "influence", definition: "shape or affect" },
    ],
    prior_skills: ["Distinguish first and third person", "Compare points of view", "Identify a narrator"],
    prior_standards: [{ code: "RL.4.6", text: "Compare and contrast the point of view from which stories are narrated" }],
    future_standards: [{ code: "RL.6.6", text: "Explain how an author develops the point of view of the narrator or speaker" }],
    challenges: [
      { problem: "The point of view is named and its effect left unexamined", fix: "Retell one paragraph from another character. What can no longer be said is the influence" },
      { problem: "The narrator is assumed to be neutral", fix: "Ask what they are not telling us, and why they might not" },
    ],
    mastery_statement: "Student can describe how the narrator's position shapes what the reader is told.",
    ladder: [
      { name: "I can find the narrator", descriptor: "Identifies the voice" },
      { name: "I can name the person", descriptor: "First or third" },
      { name: "I can say what they know", descriptor: "Identifies the limits" },
      { name: "I can say what it shapes", descriptor: "Analyzes the influence" },
    ],
  },
  {
    standard_code: "RL.5.7",
    verbs: [
      { word: "Analyze", gloss: "how visuals contribute" },
      { word: "Explain", gloss: "their effect on tone" },
    ],
    concepts: ["Tone from image", "Multimedia", "Meaning and beauty"],
    vocabulary: [
      { term: "tone", definition: "the attitude a text takes" },
      { term: "multimedia", definition: "sound, image and text together" },
      { term: "graphic novel", definition: "a story told in panels" },
      { term: "contribute", definition: "add to" },
    ],
    prior_skills: ["Explain what illustrations add", "Connect text and presentation", "Name mood"],
    prior_standards: [{ code: "RL.4.7", text: "Make connections between the text and a visual or oral presentation" }],
    future_standards: [{ code: "RL.6.7", text: "Compare and contrast reading a text to listening to or viewing a version of it" }],
    challenges: [
      { problem: "The image is described rather than its effect analyzed", fix: "Describing is the floor. What does it do to the tone — darker, funnier, more urgent?" },
      { problem: "Tone and mood are used interchangeably and neither is named", fix: "A tone word bank, used before the analysis is written" },
    ],
    mastery_statement: "Student can analyze how a visual element changes the meaning, tone or beauty of a text.",
    ladder: [
      { name: "I can describe the visual", descriptor: "Observes it" },
      { name: "I can link it to the text", descriptor: "Connects the two" },
      { name: "I can name the tone", descriptor: "Uses precise language" },
      { name: "I can say what it contributes", descriptor: "Analyzes the effect" },
    ],
  },
  {
    standard_code: "RL.5.9",
    verbs: [
      { word: "Compare", gloss: "the approaches taken" },
      { word: "Contrast", gloss: "where they diverge" },
    ],
    concepts: ["Genre conventions", "Approach to a theme", "Similar topics"],
    vocabulary: [
      { term: "genre", definition: "a kind of story with shared conventions" },
      { term: "approach", definition: "the way a writer handles something" },
      { term: "theme", definition: "what the story says about life" },
      { term: "convention", definition: "what readers expect of that genre" },
    ],
    prior_skills: ["Compare themes across cultures", "Identify genre", "Determine theme"],
    prior_standards: [{ code: "RL.4.9", text: "Compare and contrast the treatment of similar themes across cultures" }],
    future_standards: [{ code: "RL.6.9", text: "Compare and contrast texts in different forms or genres" }],
    challenges: [
      { problem: "The plots are compared rather than the approaches", fix: "Two mysteries can share a theme and treat it oppositely. Compare the handling, not the events" },
      { problem: "Genre is treated as a label rather than a set of expectations", fix: "Name what the genre led you to expect, then whether it delivered" },
    ],
    mastery_statement: "Student can compare how two texts in one genre approach a shared theme.",
    ladder: [
      { name: "I can name the genre", descriptor: "Identifies the form" },
      { name: "I can find the theme", descriptor: "Determines the claim" },
      { name: "I can compare the handling", descriptor: "Contrasts approach" },
      { name: "I can use genre expectations", descriptor: "Reads against convention" },
    ],
  },
  {
    standard_code: "RL.5.10",
    verbs: [
      { word: "Read", gloss: "at the top of the band" },
      { word: "Comprehend", gloss: "independently and proficiently" },
    ],
    concepts: ["Text complexity", "Independence", "Stamina"],
    vocabulary: [
      { term: "proficiently", definition: "reliably well" },
      { term: "independently", definition: "without an adult beside you" },
      { term: "complexity", definition: "how demanding the text is" },
    ],
    prior_skills: ["Read grades 4-5 literature with scaffolding", "Use fix-up strategies", "Self-monitor"],
    prior_standards: [{ code: "RL.4.10", text: "Read and comprehend literature in the grades 4-5 band with scaffolding" }],
    future_standards: [{ code: "RL.6.10", text: "Read and comprehend literature in the grades 6-8 text complexity band" }],
    challenges: [
      { problem: "Finishing is taken as evidence of understanding", fix: "A retell at the midpoint, not at the end. Pages turned proves nothing" },
      { problem: "Difficulty is met by reading faster", fix: "Slowing down is a strategy and it needs naming as one" },
    ],
    mastery_statement: "Student can read and comprehend grades 4-5 literature independently at the high end.",
    ladder: [
      { name: "I can read with support", descriptor: "Uses scaffolds" },
      { name: "I can read alone", descriptor: "Reads independently" },
      { name: "I can handle the high end", descriptor: "Manages complexity" },
      { name: "I can prove I understood", descriptor: "Demonstrates comprehension" },
    ],
  },
  {
    standard_code: "RI.5.1",
    verbs: [
      { word: "Quote", gloss: "accurately, word for word" },
      { word: "Explain", gloss: "what the text states" },
      { word: "Infer", gloss: "what it supports without stating" },
    ],
    concepts: ["Accurate quotation", "Explicit versus inferred", "Citation"],
    vocabulary: [
      { term: "quote", definition: "the author's exact words" },
      { term: "accurately", definition: "with nothing changed" },
      { term: "explicitly", definition: "stated outright" },
      { term: "inference", definition: "a conclusion the text supports" },
    ],
    prior_skills: ["Refer to details and examples", "Cite precisely", "Draw inferences"],
    prior_standards: [{ code: "RI.4.1", text: "Refer to details and examples when explaining and when drawing inferences" }],
    future_standards: [{ code: "RI.6.1", text: "Cite textual evidence to support analysis of what the text says explicitly and inferences" }],
    challenges: [
      { problem: "Quotation marks are put around a paraphrase", fix: "Accurately means every word. Read the quote back against the page before it counts" },
      { problem: "An inference is presented as something the text said", fix: "Two sentences — the text says, and so I conclude" },
    ],
    mastery_statement: "Student can quote a text word for word and separate quotation from inference.",
    ladder: [
      { name: "I can find the support", descriptor: "Locates evidence" },
      { name: "I can quote it exactly", descriptor: "Reproduces accurately" },
      { name: "I can punctuate the quotation", descriptor: "Marks it correctly" },
      { name: "I can label my inference", descriptor: "Distinguishes the two" },
    ],
  },
  {
    standard_code: "RI.5.3",
    verbs: [
      { word: "Explain", gloss: "the relationship" },
      { word: "Base", gloss: "it on specific information" },
    ],
    concepts: ["Interaction", "Relationship over sequence", "Technical text"],
    vocabulary: [
      { term: "relationship", definition: "how two things are connected" },
      { term: "interaction", definition: "how they act on each other" },
      { term: "concept", definition: "an idea a text is built on" },
      { term: "technical", definition: "explaining how something works" },
    ],
    prior_skills: ["Describe causal chains", "Use sequence language", "Read technical text"],
    prior_standards: [{ code: "RI.4.3", text: "Explain events, procedures, ideas or concepts including what happened and why" }],
    future_standards: [{ code: "RI.6.3", text: "Analyze how a key individual, event or idea is introduced and elaborated" }],
    challenges: [
      { problem: "Two things are described separately with the interaction left out", fix: "The connecting sentence is the answer. One acted on the other, and saying how is the standard" },
      { problem: "Any two things mentioned together are assumed to interact", fix: "Ask for the specific information that shows it" },
    ],
    mastery_statement: "Student can explain how two ideas or events interact, using specific information.",
    ladder: [
      { name: "I can describe each", descriptor: "Understands both" },
      { name: "I can see they connect", descriptor: "Notices a link" },
      { name: "I can name the interaction", descriptor: "Explains the relationship" },
      { name: "I can evidence it", descriptor: "Cites specific information" },
    ],
  },
  {
    standard_code: "RI.5.4",
    verbs: [
      { word: "Determine", gloss: "the meaning in this subject" },
      { word: "Verify", gloss: "that it fits" },
    ],
    concepts: ["Domain vocabulary", "Academic language", "Checking the fit"],
    vocabulary: [
      { term: "domain-specific", definition: "belonging to one subject" },
      { term: "general academic", definition: "used across subjects" },
      { term: "context", definition: "the surrounding words" },
      { term: "verify", definition: "check you were right" },
    ],
    prior_skills: ["Determine technical meanings", "Use references", "Substitute to check"],
    prior_standards: [{ code: "RI.4.4", text: "Determine the meaning of general academic and domain-specific words in a grade 4 topic" }],
    future_standards: [{ code: "RI.6.4", text: "Determine the meaning of words as used in a text, including figurative and technical meanings" }],
    challenges: [
      { problem: "The everyday sense is carried into a technical passage", fix: "A familiar word in a science text is a warning. Ask which meaning before reading on" },
      { problem: "The first definition found is accepted", fix: "Substitute it back into the sentence and read it aloud" },
    ],
    mastery_statement: "Student can determine a domain-specific meaning and verify it against the sentence.",
    ladder: [
      { name: "I can spot the term", descriptor: "Notices it" },
      { name: "I can use context", descriptor: "Infers from surroundings" },
      { name: "I can use references", descriptor: "Consults appropriately" },
      { name: "I can verify", descriptor: "Checks the fit" },
    ],
  },
  {
    standard_code: "RI.5.6",
    verbs: [
      { word: "Analyze", gloss: "multiple accounts" },
      { word: "Note", gloss: "similarities and differences in point of view" },
    ],
    concepts: ["Multiple accounts", "Emphasis", "Point of view"],
    vocabulary: [
      { term: "account", definition: "one telling of an event" },
      { term: "point of view", definition: "the position it is told from" },
      { term: "emphasis", definition: "what an account chooses to stress" },
    ],
    prior_skills: ["Compare firsthand and secondhand accounts", "Identify author stance", "Compare two texts"],
    prior_standards: [{ code: "RI.4.6", text: "Compare and contrast a firsthand and secondhand account of the same event" }],
    future_standards: [{ code: "RI.6.6", text: "Determine an author's point of view and explain how it is conveyed" }],
    challenges: [
      { problem: "Accounts are compared on facts alone, missing differences in emphasis", fix: "Two accounts can agree on every fact and differ entirely in what they stress. Compare what each chose to include" },
      { problem: "One account is picked as the true one", fix: "The task is to note the difference, not resolve it" },
    ],
    mastery_statement: "Student can analyze several accounts and describe how their points of view differ.",
    ladder: [
      { name: "I can read each account", descriptor: "Comprehends both" },
      { name: "I can compare the facts", descriptor: "Notes content" },
      { name: "I can compare the emphasis", descriptor: "Notices what each stresses" },
      { name: "I can name the point of view", descriptor: "Analyzes perspective" },
    ],
  },
  {
    standard_code: "RI.5.7",
    verbs: [
      { word: "Draw on", gloss: "several sources" },
      { word: "Locate", gloss: "an answer quickly" },
    ],
    concepts: ["Efficient search", "Print and digital", "Solving a problem"],
    vocabulary: [
      { term: "source", definition: "one place information comes from" },
      { term: "efficiently", definition: "without wasted effort" },
      { term: "locate", definition: "find where it is" },
    ],
    prior_skills: ["Use text features and search tools", "Use key words", "Read multiple sources"],
    prior_standards: [{ code: "RI.3.5", text: "Use text features and search tools to locate information efficiently" }],
    future_standards: [{ code: "RI.6.7", text: "Integrate information presented in different media or formats" }],
    challenges: [
      { problem: "Every source is read from the beginning rather than searched", fix: "Reading is not searching. Go to the index, the heading, the search box — the answer has a location" },
      { problem: "The first source found is treated as sufficient", fix: "Check a second. Speed is not the only criterion" },
    ],
    mastery_statement: "Student can locate an answer across several sources without reading them whole.",
    ladder: [
      { name: "I can read a source", descriptor: "Comprehends one" },
      { name: "I can find within it", descriptor: "Uses features" },
      { name: "I can search several", descriptor: "Works across sources" },
      { name: "I can do it quickly", descriptor: "Locates efficiently" },
    ],
  },
  {
    standard_code: "RI.5.8",
    verbs: [
      { word: "Explain", gloss: "how the author supports a point" },
      { word: "Identify", gloss: "which evidence supports which point" },
    ],
    concepts: ["Matching support to claim", "Multiple points", "Evidence"],
    vocabulary: [
      { term: "reason", definition: "why the author says you should agree" },
      { term: "evidence", definition: "the facts behind the reason" },
      { term: "point", definition: "one thing the author is arguing" },
      { term: "support", definition: "back up" },
    ],
    prior_skills: ["Distinguish claim from evidence", "Evaluate support", "Find an author's points"],
    prior_standards: [{ code: "RI.4.8", text: "Explain how an author uses reasons and evidence to support particular points" }],
    future_standards: [{ code: "RI.6.8", text: "Trace and evaluate the argument, distinguishing claims supported by reasons from those that are not" }],
    challenges: [
      { problem: "Evidence is collected in one pile with no point attached", fix: "A text usually makes several points. Draw the line from each piece of evidence to the point it serves" },
      { problem: "Evidence that supports nothing is counted anyway", fix: "An unattached fact is not support for anything" },
    ],
    mastery_statement: "Student can match each piece of evidence to the specific point it supports.",
    ladder: [
      { name: "I can find the points", descriptor: "Identifies the claims" },
      { name: "I can find the evidence", descriptor: "Locates support" },
      { name: "I can match them", descriptor: "Attaches evidence to point" },
      { name: "I can spot the unattached", descriptor: "Notices unsupported material" },
    ],
  },
  {
    standard_code: "RI.5.9",
    verbs: [
      { word: "Integrate", gloss: "weave several sources together" },
      { word: "Write", gloss: "knowledgeably about the subject" },
    ],
    concepts: ["Integration over summary", "Several sources", "Knowledgeable voice"],
    vocabulary: [
      { term: "integrate", definition: "combine into one account" },
      { term: "several", definition: "more than two" },
      { term: "knowledgeably", definition: "as someone who actually knows" },
    ],
    prior_skills: ["Integrate two texts", "Take notes in categories", "Name conflicts"],
    prior_standards: [{ code: "RI.4.9", text: "Integrate information from two texts on the same topic" }],
    future_standards: [{ code: "RI.6.9", text: "Compare and contrast one author's presentation of events with another's" }],
    challenges: [
      { problem: "Three sources become three paragraphs, one each", fix: "Organize by idea, not by source. If the paragraph headings are the book titles, it has not been integrated" },
      { problem: "Conflicts between sources are smoothed over", fix: "Name the disagreement rather than choosing quietly" },
    ],
    mastery_statement: "Student can write one account organized by idea, drawing on several sources.",
    ladder: [
      { name: "I can use one source", descriptor: "Reports from one" },
      { name: "I can use two", descriptor: "Combines a pair" },
      { name: "I can organize by idea", descriptor: "Integrates rather than stacks" },
      { name: "I can handle disagreement", descriptor: "Names conflicts" },
    ],
  },
  {
    standard_code: "RI.5.10",
    verbs: [
      { word: "Read", gloss: "dense informational text" },
      { word: "Comprehend", gloss: "independently and proficiently" },
    ],
    concepts: ["Text complexity", "Chunking", "Independence"],
    vocabulary: [
      { term: "proficiently", definition: "reliably well" },
      { term: "independently", definition: "without help" },
      { term: "complexity", definition: "how demanding the text is" },
    ],
    prior_skills: ["Chunk and summarize", "Use text features", "Monitor comprehension"],
    prior_standards: [{ code: "RI.4.10", text: "Read and comprehend informational texts in the grades 4-5 band with scaffolding" }],
    future_standards: [{ code: "RI.6.10", text: "Read and comprehend literary nonfiction in the grades 6-8 band" }],
    challenges: [
      { problem: "Dense sections are skimmed and the gap is not noticed until later", fix: "Summarize each section before moving on. A section you cannot summarize was not read" },
      { problem: "Nonfiction is avoided in independent reading", fix: "Require it in the book box, as capacity does not follow preference" },
    ],
    mastery_statement: "Student can read grades 4-5 informational text independently and demonstrate comprehension.",
    ladder: [
      { name: "I can read a section", descriptor: "Handles short pieces" },
      { name: "I can chunk a long text", descriptor: "Sections it" },
      { name: "I can summarize as I go", descriptor: "Checks understanding" },
      { name: "I can read it alone", descriptor: "Works independently" },
    ],
  },
  {
    standard_code: "RF.5.3.A",
    verbs: [
      { word: "Use", gloss: "sounds, syllables and morphology together" },
      { word: "Read", gloss: "unfamiliar long words accurately" },
    ],
    concepts: ["Combined knowledge", "In and out of context", "Meaning from parts"],
    vocabulary: [
      { term: "syllabication", definition: "splitting a word into syllables" },
      { term: "morphology", definition: "word parts and their meanings" },
      { term: "root", definition: "the part carrying the core meaning" },
      { term: "affix", definition: "a prefix or suffix" },
    ],
    prior_skills: ["Decode multisyllabic words", "Use Greek and Latin roots", "Blend syllables"],
    prior_standards: [{ code: "RF.4.3.A", text: "Use combined knowledge to read unfamiliar multisyllabic words" }],
    future_standards: [{ code: "L.6.4", text: "Determine or clarify the meaning of unknown words using context and word parts" }],
    challenges: [
      { problem: "The word is decoded and its meaning skipped, so comprehension does not move", fix: "Reading it is half the job. Say what the parts mean before going on" },
      { problem: "Out of context is never practiced, so the skill depends on surrounding clues", fix: "The standard names both. Word lists as well as running text" },
    ],
    mastery_statement: "Student can read an unfamiliar multisyllabic word and use its parts to state a meaning.",
    ladder: [
      { name: "I can split it", descriptor: "Applies syllabication" },
      { name: "I can read it", descriptor: "Decodes accurately" },
      { name: "I can find the root", descriptor: "Uses morphology" },
      { name: "I can say what it means", descriptor: "Connects decoding to meaning" },
    ],
  },
  {
    standard_code: "RF.5.4.A",
    verbs: [
      { word: "Read", gloss: "with a purpose" },
      { word: "Adjust", gloss: "the approach to match" },
    ],
    concepts: ["Purpose", "Approach", "Monitoring"],
    vocabulary: [
      { term: "purpose", definition: "why you are reading" },
      { term: "comprehension", definition: "understanding what you read" },
      { term: "monitor", definition: "keep checking" },
    ],
    prior_skills: ["Set a purpose", "Skim and read closely", "Check against the purpose"],
    prior_standards: [{ code: "RF.4.4.A", text: "Read grade-level text with purpose and understanding" }],
    future_standards: [{ code: "RI.6.10", text: "Read and comprehend literary nonfiction proficiently" }],
    challenges: [
      { problem: "One reading speed serves every purpose", fix: "Name the purpose and the approach as two separate decisions" },
      { problem: "The purpose is never checked afterwards", fix: "Close the text and answer it" },
    ],
    mastery_statement: "Student can set a purpose and match their reading approach to it.",
    ladder: [
      { name: "I can read it", descriptor: "Comprehends" },
      { name: "I can set a purpose", descriptor: "Names it first" },
      { name: "I can choose an approach", descriptor: "Adjusts to the purpose" },
      { name: "I can check I met it", descriptor: "Monitors the outcome" },
    ],
  },
  {
    standard_code: "RF.5.4.B",
    verbs: [
      { word: "Read", gloss: "prose and poetry aloud" },
      { word: "Phrase", gloss: "so the meaning carries" },
    ],
    concepts: ["Phrasing", "Prosody", "Successive readings"],
    vocabulary: [
      { term: "fluency", definition: "reading that carries meaning" },
      { term: "prosody", definition: "the music of reading aloud" },
      { term: "phrasing", definition: "grouping words that belong together" },
      { term: "rate", definition: "how fast you read" },
    ],
    prior_skills: ["Read aloud with expression", "Mark phrase groups", "Reread to improve"],
    prior_standards: [{ code: "RF.4.4.B", text: "Read grade-level prose and poetry orally with accuracy, rate and expression" }],
    future_standards: [{ code: "SL.6.4", text: "Present claims and findings with appropriate eye contact, volume and pronunciation" }],
    challenges: [
      { problem: "Long sentences fall apart into single words even when every word is known", fix: "Mark the phrase groups before reading. Length is the problem, not vocabulary" },
      { problem: "Expression is performed rather than led by meaning", fix: "Say what the sentence means first, then read it that way" },
    ],
    mastery_statement: "Student can read prose and poetry aloud in phrases that carry the meaning.",
    ladder: [
      { name: "I can read accurately", descriptor: "Few errors" },
      { name: "I can use punctuation", descriptor: "Basic phrasing" },
      { name: "I can group into phrases", descriptor: "Phrases within sentences" },
      { name: "I can carry the meaning", descriptor: "Uses prosody for sense" },
    ],
  },
  {
    standard_code: "RF.5.4.C",
    verbs: [
      { word: "Use", gloss: "context to confirm" },
      { word: "Self-correct", gloss: "at the level of meaning" },
      { word: "Reread", gloss: "from where the sense went" },
    ],
    concepts: ["Passage-level monitoring", "Repair", "Rereading"],
    vocabulary: [
      { term: "self-correct", definition: "fix your own error" },
      { term: "context", definition: "the surrounding meaning" },
      { term: "monitor", definition: "keep checking it makes sense" },
    ],
    prior_skills: ["Monitor at paragraph level", "Reread", "Notice a comprehension breakdown"],
    prior_standards: [{ code: "RF.4.4.C", text: "Use context to confirm or self-correct word recognition and understanding" }],
    future_standards: [{ code: "RI.6.1", text: "Cite textual evidence to support analysis of what a text says" }],
    challenges: [
      { problem: "A paragraph read perfectly and understood not at all goes unnoticed", fix: "Check at the paragraph, not the word. Accuracy and comprehension are different things" },
      { problem: "Rereading starts at the word rather than where the sense went", fix: "Go back to the last point it made sense, not to the last word" },
    ],
    mastery_statement: "Student can notice a passage-level breakdown and reread from the right point.",
    ladder: [
      { name: "I can fix a word", descriptor: "Corrects decoding" },
      { name: "I can reread a sentence", descriptor: "Repairs locally" },
      { name: "I can check a paragraph", descriptor: "Monitors at passage level" },
      { name: "I can find where it went", descriptor: "Rereads from the right point" },
    ],
  },
];

const blueprintsData = [
  {
    standard_code: "RL.5.2",
    title: "Start at the Response, Not the Plot",
    badge: "Grade 5",
    route_name: "Analytical Reading",
    route_line: "Find the challenge → Find the response → Read the theme off it",
    success_criteria: ["States a theme as a claim", "Draws it from character response", "Summarizes separately"],
    steps: [
      { name: "Retrieve Theme Versus Summary", minutes: 5, body: "Sorted quickly. The distinction the standard rests on.", science_tag: "retrieval" },
      { name: "Two Boxes", minutes: 10, body: "Summary in one, theme in the other. If the sentence names a character, it belongs in the summary box.", science_tag: "dual-coding" },
      { name: "Where Was the Challenge", minutes: 12, body: "Located before anything is interpreted.", science_tag: "elaboration" },
      { name: "What Did They Do About It", minutes: 12, body: "The response, in one sentence. This is where the standard says the theme lives.", science_tag: "elaboration" },
      { name: "So What Does That Say", minutes: 12, body: "About people, about life. The response generalized into a claim.", science_tag: "elaboration" },
      { name: "Write the Summary Too", minutes: 10, body: "Separately, with no judgment in it.", science_tag: "interleaving" },
      { name: "Two Themes, One Story", minutes: 4, body: "Both defended. A story rarely says only one thing.", science_tag: "collaborative" },
    ],
    ef_supports: ["Two-box organizer", "Challenge-and-response frame", "Theme sentence stem", "Character-name test"],
    tech: "Chapter books with clear turning points",
    tech_purpose: "The response has to be findable to be read from",
    ai_prompts: ["Write stories where the theme is carried by a character's response", "Generate summaries and themes for sorting"],
    assessment: ["Check themes name no characters", "Confirm the response was located first", "Read summaries for judgment"],
    why_it_works: ["The character-name test is a rule a student can apply to their own sentence", "Starting at the response follows what the standard actually says", "Two boxes keep summary and theme from collapsing into each other", "Defending two themes shows interpretation is evidenced, not guessed"],
  },
  {
    standard_code: "RL.5.3",
    title: "One Row, Both Characters",
    badge: "Grade 5",
    route_name: "Analytical Reading",
    route_line: "Name the dimension → Fill both cells → Say what the difference means",
    success_criteria: ["Names a point of comparison", "Evidences both sides", "Draws a conclusion"],
    steps: [
      { name: "Retrieve Trait Words", minutes: 5, body: "Available before the reading starts.", science_tag: "retrieval" },
      { name: "Two Descriptions Is Not a Comparison", minutes: 10, body: "Shown deliberately. Both characters described, nothing compared.", science_tag: "elaboration" },
      { name: "Choose the Dimension", minutes: 10, body: "How each handles being wrong. What each wants. Named before gathering.", science_tag: "metacognition" },
      { name: "Both Cells, Both Cited", minutes: 14, body: "An empty cell is an unsupported claim. Every row carries a page number from each.", science_tag: "dual-coding" },
      { name: "So What", minutes: 12, body: "What does the difference tell us about the story?", science_tag: "elaboration" },
      { name: "Settings and Events Too", minutes: 8, body: "The standard names all three.", science_tag: "interleaving" },
      { name: "Challenge a Cell", minutes: 4, body: "A partner asks whether that detail really shows it.", science_tag: "collaborative" },
    ],
    ef_supports: ["Shared-row grid", "Dimension menu", "Citation box per cell", "So-what stem"],
    tech: "Texts with page numbers",
    tech_purpose: "Every cell needs a findable reference",
    ai_prompts: ["Write character pairs differing on one clear dimension", "Generate comparison dimensions for a story"],
    assessment: ["Check every cell is filled and cited", "Confirm the dimension is named first", "Read so-what sentences"],
    why_it_works: ["A shared row makes comparison structural rather than intended", "Naming the dimension first turns vagueness into a question", "Requiring citation on both sides prevents one-sided claims", "The so-what step is what the standard means by drawing on details"],
  },
  {
    standard_code: "RL.5.4",
    title: "What Is It Claiming",
    badge: "Grade 5",
    route_name: "Strategy Instruction",
    route_line: "Spot the comparison → Say what it claims → Check it against the sentence",
    success_criteria: ["Identifies metaphor and simile", "States what the comparison claims", "Verifies in context"],
    steps: [
      { name: "Retrieve Literal and Nonliteral", minutes: 5, body: "From grade 4.", science_tag: "retrieval" },
      { name: "Naming Is Not Reading", minutes: 10, body: "That is a metaphor is a label, not a meaning. Named as the stopping point it is.", science_tag: "metacognition" },
      { name: "A Heart of Stone", minutes: 12, body: "Claims coldness, not geology. Say what is being claimed about the thing.", science_tag: "elaboration" },
      { name: "Two Halves of the Comparison", minutes: 12, body: "What is being compared to what, and which quality carries across?", science_tag: "dual-coding" },
      { name: "Substitute and Read", minutes: 10, body: "Plain meaning back into the sentence. If it breaks, the reading was wrong.", science_tag: "metacognition" },
      { name: "Find One in Your Book", minutes: 8, body: "From independent reading, with the claim named.", science_tag: "spaced" },
      { name: "Write One", minutes: 3, body: "Their own, and say what it claims.", science_tag: "elaboration" },
    ],
    ef_supports: ["Claim frame", "Two-halves organizer", "Substitution check", "Figure collection log"],
    tech: "Texts with natural figurative language",
    tech_purpose: "Figures have to be met in context, not on a list",
    ai_prompts: ["Generate metaphors with clear transferred qualities", "Write similes for claim analysis"],
    assessment: ["Reject labels offered as meanings", "Check the claim is named", "Confirm substitution"],
    why_it_works: ["Naming the label-as-answer habit clears the way for the real question", "Identifying which quality transfers is what interpreting a metaphor is", "Substitution catches an interpretation that does not fit", "Writing one tests whether the mechanism was understood"],
  },
  {
    standard_code: "RL.5.5",
    title: "What Does This Chapter Do",
    badge: "Grade 5",
    route_name: "Analytical Reading",
    route_line: "Name each part's job → Map the shape → Test by swapping",
    success_criteria: ["Names the function of a part", "Explains the overall structure", "Uses genre terms"],
    steps: [
      { name: "Retrieve Structural Terms", minutes: 5, body: "Chapter, scene, stanza — matched to their form.", science_tag: "retrieval" },
      { name: "Content Words Banned", minutes: 12, body: "Say what the chapter does, not what happens in it. Introduces, complicates, delays, resolves.", science_tag: "elaboration" },
      { name: "One Row Per Part", minutes: 12, body: "Function only. The map is of the shape, not the story.", science_tag: "dual-coding" },
      { name: "Swap Two Chapters", minutes: 12, body: "What breaks? The damage names the structure.", science_tag: "elaboration" },
      { name: "Delete One", minutes: 10, body: "What is lost? Some parts carry more than others.", science_tag: "elaboration" },
      { name: "Poems and Plays Too", minutes: 8, body: "Stanzas and scenes, same routine.", science_tag: "interleaving" },
      { name: "Write the Explanation", minutes: 3, body: "How the parts make the whole.", science_tag: "interleaving" },
    ],
    ef_supports: ["Function verb menu", "Content-word ban", "One-row-per-part map", "Swap-and-break test"],
    tech: "A novel, a play and a poem",
    tech_purpose: "The standard names all three forms",
    ai_prompts: ["Generate chapter function labels", "Write texts where reordering visibly breaks the structure"],
    assessment: ["Check rows name functions not content", "Test the swap reasoning", "Confirm genre terms match"],
    why_it_works: ["Banning content words is what forces function over summary", "Swapping two parts makes the structure something you can test", "Deleting one shows parts are not equally load-bearing", "Covering all three forms matches what the standard asks"],
  },
  {
    standard_code: "RL.5.6",
    title: "Retell It From Someone Else",
    badge: "Grade 5",
    route_name: "Analytical Reading",
    route_line: "Name the narrator → Retell from another → Say what changed",
    success_criteria: ["Identifies the point of view", "Describes its influence", "Names what is withheld"],
    steps: [
      { name: "Retrieve Point of View", minutes: 5, body: "First, third, limited, all-knowing.", science_tag: "retrieval" },
      { name: "Naming Is Not Analyzing", minutes: 8, body: "Third person is a label. The standard asks what it does.", science_tag: "metacognition" },
      { name: "Retell From Another Character", minutes: 16, body: "One scene. What can no longer be said? That absence is the influence.", science_tag: "elaboration" },
      { name: "What Are They Not Telling Us", minutes: 12, body: "A narrator selects. What did this one leave out, and why might they?", science_tag: "elaboration" },
      { name: "The Speaker in a Poem", minutes: 10, body: "The standard names speakers as well as narrators.", science_tag: "interleaving" },
      { name: "Write the Analysis", minutes: 10, body: "How the point of view shaped the description.", science_tag: "interleaving" },
      { name: "Compare Two Retellings", minutes: 3, body: "Two students, two characters, one scene.", science_tag: "collaborative" },
    ],
    ef_supports: ["Retelling frame", "What-was-lost prompt", "Narrator selection questions", "Poetry speaker set"],
    tech: "Texts with distinctive narrators",
    tech_purpose: "Influence needs a narrator with a clear position",
    ai_prompts: ["Write scenes narrated by different characters", "Generate passages where the narrator withholds"],
    assessment: ["Check the effect is described, not the label", "Read retellings for what was lost", "Ask what was withheld"],
    why_it_works: ["Retelling makes the influence something discovered rather than asserted", "Naming what can no longer be said measures the narrator's limits", "Asking what was withheld treats narration as selection", "Two retellings of one scene show perspective without arguing about truth"],
  },
  {
    standard_code: "RL.5.7",
    title: "What the Picture Does to the Tone",
    badge: "Grade 5",
    route_name: "Analytical Reading",
    route_line: "Read the words → Study the visual → Name the tone it creates",
    success_criteria: ["Analyzes a visual element", "Names the tone", "Explains the contribution"],
    steps: [
      { name: "Retrieve Tone Words", minutes: 5, body: "Urgent, wistful, comic, bleak. Precision needs vocabulary.", science_tag: "retrieval" },
      { name: "Describing Is Not Analyzing", minutes: 10, body: "The panel shows a boy running is description. The question is what it does.", science_tag: "metacognition" },
      { name: "Cover the Words", minutes: 12, body: "What does the image alone establish? Usually tone.", science_tag: "dual-coding" },
      { name: "Swap the Visual", minutes: 12, body: "The same text with a different image. The tone moves, which proves it was doing work.", science_tag: "elaboration" },
      { name: "Name the Tone", minutes: 10, body: "From the bank, precisely, and justified.", science_tag: "elaboration" },
      { name: "Multimedia Too", minutes: 8, body: "Sound and motion, which the standard names.", science_tag: "interleaving" },
      { name: "Write the Analysis", minutes: 3, body: "This element contributes ___ because ___.", science_tag: "interleaving" },
    ],
    ef_supports: ["Tone word bank", "Cover-the-words card", "Alternative visuals", "Contribution frame"],
    tech: "Graphic novels and multimedia texts",
    tech_purpose: "The standard names both explicitly",
    ai_prompts: ["Generate alternative images shifting the tone of one passage", "Write tone analysis prompts"],
    assessment: ["Reject description as analysis", "Check tone is named precisely", "Test the swap reasoning"],
    why_it_works: ["Covering the words isolates what the image contributes", "Swapping the visual proves the contribution rather than asserting it", "A tone bank gives language for something students can already feel", "Naming description as insufficient sets the bar where the standard does"],
  },
  {
    standard_code: "RL.5.9",
    title: "Two Mysteries, Two Answers",
    badge: "Grade 5",
    route_name: "Analytical Reading",
    route_line: "Name the genre expectations → Find the shared theme → Compare the handling",
    success_criteria: ["Identifies genre conventions", "Finds a shared theme", "Compares approaches"],
    steps: [
      { name: "Retrieve Genre", minutes: 5, body: "What a mystery, a fantasy, a survival story leads you to expect.", science_tag: "retrieval" },
      { name: "Comparing Plots Is Easy", minutes: 10, body: "And is not the standard. Approach is the word.", science_tag: "metacognition" },
      { name: "What Did the Genre Promise", minutes: 12, body: "Written down before reading. Expectations made explicit.", science_tag: "elaboration" },
      { name: "One Theme, Two Handlings", minutes: 14, body: "Both books treat courage. One says it is loud, one says it is quiet. That is approach.", science_tag: "dual-coding" },
      { name: "Where It Broke the Rules", minutes: 10, body: "A book that defied the expectation, and what that achieved.", science_tag: "elaboration" },
      { name: "Write the Comparison", minutes: 10, body: "On approach, with evidence from both.", science_tag: "interleaving" },
      { name: "A Third Book", minutes: 3, body: "Same genre, same theme, later in the week.", science_tag: "spaced" },
    ],
    ef_supports: ["Genre expectation sheet", "Shared-theme row", "Broke-the-rules prompt", "Approach comparison frame"],
    tech: "Paired texts in one genre",
    tech_purpose: "Genre comparison needs two books readers can hold at once",
    ai_prompts: ["Write two same-genre stories treating one theme differently", "Generate genre expectation lists"],
    assessment: ["Check the comparison is on approach", "Confirm expectations were written first", "Read for evidence from both"],
    why_it_works: ["Writing expectations before reading makes convention visible", "One theme handled two ways isolates approach as the variable", "A book that breaks the rules shows conventions are choices", "Naming plot comparison as the easy answer sets the bar higher"],
  },
  {
    standard_code: "RL.5.10",
    title: "Prove You Understood It",
    badge: "Grade 5",
    route_name: "Strategy Instruction",
    route_line: "Choose a stretch book → Retell at the midpoint → Repair before the end",
    success_criteria: ["Reads at the high end", "Demonstrates comprehension", "Applies fix-up strategies"],
    steps: [
      { name: "Retrieve the Story So Far", minutes: 6, body: "Before reading on. Recall rather than recap.", science_tag: "retrieval" },
      { name: "Finished Is Not Understood", minutes: 8, body: "Named plainly. Pages turned is not evidence of anything.", science_tag: "metacognition" },
      { name: "Retell at the Midpoint", minutes: 14, body: "Early enough to repair. Waiting for the end finds the gap too late.", science_tag: "retrieval" },
      { name: "Slowing Down Is a Strategy", minutes: 10, body: "Difficulty is usually met by speeding up. The alternative needs saying.", science_tag: "elaboration" },
      { name: "Read On", minutes: 16, body: "Independently, with the midpoint check marked in advance.", science_tag: "spaced" },
      { name: "Where I Lost It", minutes: 8, body: "Located, and reread from there rather than from the start.", science_tag: "metacognition" },
      { name: "Book Talk", minutes: 4, body: "Which requires having understood it.", science_tag: "collaborative" },
    ],
    ef_supports: ["Midpoint checkpoint", "Retell prompts", "Lost-it log", "Book talk frame"],
    tech: "A library spanning the 4-5 band",
    tech_purpose: "The high end has to be available to be reached",
    ai_prompts: ["Generate midpoint retelling prompts", "Write comprehension checks for longer texts"],
    assessment: ["Test retelling at the midpoint", "Read lost-it logs", "Listen to book talks"],
    why_it_works: ["A midpoint check catches the gap while it can still be repaired", "Naming finished-but-lost separates completion from comprehension", "Locating where it went wrong makes rereading targeted", "A book talk cannot be given about a book that was not understood"],
  },
  {
    standard_code: "RI.5.1",
    title: "Word for Word, or Not at All",
    badge: "Grade 5",
    route_name: "Strategy Instruction",
    route_line: "Find the support → Copy it exactly → Label what you inferred",
    success_criteria: ["Quotes accurately", "Punctuates the quotation", "Separates inference"],
    steps: [
      { name: "Retrieve Evidence", minutes: 5, body: "What counts as support.", science_tag: "retrieval" },
      { name: "Quotation Marks Around a Paraphrase", minutes: 12, body: "Shown, then checked against the page. Accurately means every word, and this is the commonest failure.", science_tag: "metacognition" },
      { name: "Read It Back", minutes: 12, body: "Against the original, word by word, before it counts as a quotation.", science_tag: "metacognition" },
      { name: "Says and I Conclude", minutes: 12, body: "Two columns. Inference labelled as inference.", science_tag: "dual-coding" },
      { name: "Punctuate It", minutes: 10, body: "The four-part check from grade 3, applied to quoted evidence.", science_tag: "interleaving" },
      { name: "Write With Quotations", minutes: 10, body: "Each set up, quoted, explained.", science_tag: "interleaving" },
      { name: "Partner Audit", minutes: 3, body: "Check the quote against the page.", science_tag: "collaborative" },
    ],
    ef_supports: ["Read-it-back routine", "Two-column says-and-conclude", "Quotation punctuation check", "Partner audit"],
    tech: "Printed text with line numbers",
    tech_purpose: "Accuracy needs something to check against",
    ai_prompts: ["Generate paraphrases presented as quotations for correction", "Write explicit and inferable questions"],
    assessment: ["Check quotes word for word", "Confirm inference is labelled", "Run the partner audit"],
    why_it_works: ["Reading the quote back is the only check that catches a paraphrase in quotation marks", "Two columns keep inference honest without discouraging it", "A partner checking against the page makes accuracy verifiable", "Applying the punctuation check to evidence connects two standards"],
  },
  {
    standard_code: "RI.5.3",
    title: "How Did One Act on the Other",
    badge: "Grade 5",
    route_name: "Strategy Instruction",
    route_line: "Name both → Draw the arrow → Evidence the interaction",
    success_criteria: ["Explains a relationship", "Uses specific information", "Handles technical text"],
    steps: [
      { name: "Retrieve Connectives", minutes: 5, body: "Because, so, which caused, in response to.", science_tag: "retrieval" },
      { name: "Two Descriptions, No Link", minutes: 10, body: "Both things explained and nothing connecting them. The missing sentence is the standard.", science_tag: "elaboration" },
      { name: "Draw the Arrow", minutes: 12, body: "Between the two, with a word on it.", science_tag: "dual-coding" },
      { name: "Which Way Round", minutes: 12, body: "Did A change B, or B change A, or both? Direction is part of the relationship.", science_tag: "elaboration" },
      { name: "Evidence It", minutes: 12, body: "Specific information, which the standard names. Not an impression.", science_tag: "metacognition" },
      { name: "A Scientific Text", minutes: 8, body: "Same routine on concepts rather than events.", science_tag: "interleaving" },
      { name: "Write the Explanation", minutes: 3, body: "The relationship, in one paragraph.", science_tag: "interleaving" },
    ],
    ef_supports: ["Arrow-labelling routine", "Direction prompt", "Evidence requirement", "Connective bank"],
    tech: "Historical, scientific and technical texts",
    tech_purpose: "The standard names all three",
    ai_prompts: ["Write texts with clear interactions between concepts", "Generate pairs that co-occur without interacting"],
    assessment: ["Check the arrow carries a word", "Confirm direction is stated", "Look for specific evidence"],
    why_it_works: ["A labelled arrow is a relationship you can point at", "Asking which way round stops interaction being assumed symmetrical", "Requiring specific information is what the standard says", "Covering all three text types matches the standard's range"],
  },
  {
    standard_code: "RI.5.4",
    title: "Which Meaning Is This",
    badge: "Grade 5",
    route_name: "Strategy Instruction",
    route_line: "Spot the term → Take the subject meaning → Substitute to check",
    success_criteria: ["Determines domain meanings", "Uses context and references", "Verifies the fit"],
    steps: [
      { name: "Retrieve Vocabulary Tools", minutes: 5, body: "Context, word parts, glossary, dictionary.", science_tag: "retrieval" },
      { name: "Familiar Is a Warning", minutes: 12, body: "A known word in a science text is a flag, not a relief.", science_tag: "metacognition" },
      { name: "Which Meaning Here", minutes: 12, body: "Asked before reading on, of every candidate.", science_tag: "metacognition" },
      { name: "Substitute and Read", minutes: 12, body: "The meaning back into the sentence. If it breaks, it was wrong.", science_tag: "metacognition" },
      { name: "Academic Words Too", minutes: 10, body: "Analyze, determine, evaluate — the words the task itself uses.", science_tag: "interleaving" },
      { name: "Use It in Writing", minutes: 8, body: "Before the lesson ends. Defined is not learned.", science_tag: "elaboration" },
      { name: "Word Log", minutes: 3, body: "Collected across subjects and revisited.", science_tag: "spaced" },
    ],
    ef_supports: ["Two-meanings log", "Substitution frame", "Academic word list", "Subject glossaries"],
    tech: "Science and social studies texts",
    tech_purpose: "Domain vocabulary needs a domain",
    ai_prompts: ["Generate words with everyday and technical senses", "Write passages using the technical meaning"],
    assessment: ["Check the subject meaning was chosen", "Confirm substitution", "Look for the word in their writing"],
    why_it_works: ["Treating familiarity as a warning inverts the instinct that causes the error", "Substitution catches an imported everyday meaning", "Academic words are the ones the task itself depends on", "Using the word is the difference between defined and learned"],
  },
  {
    standard_code: "RI.5.6",
    title: "What Did Each One Choose to Say",
    badge: "Grade 5",
    route_name: "Analytical Reading",
    route_line: "Read all the accounts → Compare the facts → Compare the emphasis",
    success_criteria: ["Analyzes multiple accounts", "Notes similarities and differences", "Identifies points of view"],
    steps: [
      { name: "Retrieve Point of View", minutes: 5, body: "The author has a position.", science_tag: "retrieval" },
      { name: "Same Facts, Different Story", minutes: 14, body: "Two accounts agreeing on every fact and differing entirely in emphasis. That is the lesson.", science_tag: "elaboration" },
      { name: "Facts Column First", minutes: 10, body: "The easy comparison, done and set aside.", science_tag: "dual-coding" },
      { name: "Emphasis Column", minutes: 12, body: "What did each choose to spend its words on? That is where they diverge.", science_tag: "dual-coding" },
      { name: "Which Is True", minutes: 10, body: "A trap. The task is to note the difference, not resolve it.", science_tag: "metacognition" },
      { name: "A Third Account", minutes: 10, body: "Added to the same columns.", science_tag: "interleaving" },
      { name: "Write the Analysis", minutes: 3, body: "How the points of view differ.", science_tag: "interleaving" },
    ],
    ef_supports: ["Facts and emphasis columns", "Same-facts pair", "Which-is-true discussion", "Third account"],
    tech: "Multiple accounts of one event",
    tech_purpose: "The standard says multiple, not two",
    ai_prompts: ["Write accounts agreeing on facts but differing in emphasis", "Generate multi-account event sets"],
    assessment: ["Check emphasis is compared, not only facts", "Watch for picking a true version", "Confirm all accounts are used"],
    why_it_works: ["Two accounts agreeing on facts isolates emphasis as the difference", "Doing facts first clears the easy comparison out of the way", "The which-is-true trap surfaces the instinct to resolve rather than analyze", "A third account stops it becoming a binary"],
  },
  {
    standard_code: "RI.5.7",
    title: "Search It, Do Not Read It",
    badge: "Grade 5",
    route_name: "Strategy Instruction",
    route_line: "Reduce the question → Choose where to look → Find it fast",
    success_criteria: ["Uses multiple sources", "Locates answers quickly", "Chooses the right tool"],
    steps: [
      { name: "Retrieve Search Tools", minutes: 5, body: "Index, contents, headings, search box.", science_tag: "retrieval" },
      { name: "Reading Is Not Searching", minutes: 10, body: "Starting at page one is reading. The answer has a location.", science_tag: "metacognition" },
      { name: "Two Words From the Question", minutes: 12, body: "Underlined. Those are the search.", science_tag: "metacognition" },
      { name: "Where Would It Live", minutes: 12, body: "Predicted before looking. Which source, which section.", science_tag: "elaboration" },
      { name: "Race It", minutes: 14, body: "Same question, timed, across several sources. Efficiently is in the standard.", science_tag: "collaborative" },
      { name: "Check a Second Source", minutes: 8, body: "Speed is not the only criterion.", science_tag: "interleaving" },
      { name: "Yesterday's Question", minutes: 3, body: "Re-searched from memory of the tools.", science_tag: "spaced" },
    ],
    ef_supports: ["Key word underlining", "Where-would-it-live prediction", "Search timer", "Two-source rule"],
    tech: "Print sources and a supervised search tool",
    tech_purpose: "The standard names print and digital",
    ai_prompts: ["Generate questions answerable from several sources", "Write source sets with overlapping coverage"],
    assessment: ["Time the searches", "Check key words were extracted", "Confirm a second source"],
    why_it_works: ["Underlining two words converts a question into a search", "Predicting the location makes searching deliberate", "Timing is what makes efficiently a real criterion", "Requiring a second source keeps speed from becoming carelessness"],
  },
  {
    standard_code: "RI.5.8",
    title: "Draw the Line to the Point",
    badge: "Grade 5",
    route_name: "Analytical Reading",
    route_line: "List the points → List the evidence → Connect each one",
    success_criteria: ["Identifies multiple points", "Matches evidence to point", "Notices unattached material"],
    steps: [
      { name: "Retrieve Claim and Evidence", minutes: 5, body: "The distinction, secure.", science_tag: "retrieval" },
      { name: "More Than One Point", minutes: 10, body: "A text usually argues several things. Listing them first is the step that gets skipped.", science_tag: "metacognition" },
      { name: "Two Lists", minutes: 12, body: "Points down one side, evidence down the other.", science_tag: "dual-coding" },
      { name: "Draw the Lines", minutes: 14, body: "Each piece of evidence to the point it serves. Some serve none.", science_tag: "dual-coding" },
      { name: "The Unattached", minutes: 10, body: "Evidence supporting nothing. Interesting, and not support.", science_tag: "elaboration" },
      { name: "Which Point Is Best Supported", minutes: 10, body: "Count the lines and weigh them.", science_tag: "metacognition" },
      { name: "Write the Explanation", minutes: 3, body: "Which evidence supports which point.", science_tag: "interleaving" },
    ],
    ef_supports: ["Two-list layout", "Line-drawing routine", "Unattached box", "Weighing prompt"],
    tech: "Persuasive texts making several points",
    tech_purpose: "Matching requires more than one point to match to",
    ai_prompts: ["Write texts making several points with mixed evidence", "Generate unattached supporting material"],
    assessment: ["Check lines are drawn to specific points", "Confirm unattached evidence is identified", "Read the weighing"],
    why_it_works: ["Drawing lines makes the matching physical rather than assumed", "Listing points first prevents evidence piling up unattached", "Naming unattached evidence teaches that relevance is a requirement", "Weighing rather than counting is where evaluation begins"],
  },
  {
    standard_code: "RI.5.9",
    title: "Organize by Idea, Not by Book",
    badge: "Grade 5",
    route_name: "Analytical Reading",
    route_line: "Read them all → Merge into idea headings → Write from those",
    success_criteria: ["Integrates several sources", "Organizes by idea", "Names disagreements"],
    steps: [
      { name: "Retrieve Note Categories", minutes: 5, body: "Sorting notes as they are taken.", science_tag: "retrieval" },
      { name: "Three Paragraphs, Three Books", minutes: 10, body: "Named as the failure it is. That is reporting on the reading.", science_tag: "metacognition" },
      { name: "Idea Headings First", minutes: 12, body: "Decided before writing. If the headings are book titles, start again.", science_tag: "dual-coding" },
      { name: "Merge the Notes", minutes: 14, body: "Every source contributing to every heading it can.", science_tag: "dual-coding" },
      { name: "Where They Disagree", minutes: 12, body: "Named in the writing rather than quietly resolved.", science_tag: "elaboration" },
      { name: "Write Knowledgeably", minutes: 10, body: "As someone who knows the subject, not someone reporting three books.", science_tag: "interleaving" },
      { name: "Could a Reader Tell", minutes: 3, body: "Which fact came from where? They should not need to.", science_tag: "metacognition" },
    ],
    ef_supports: ["Idea heading sheet", "Merged note grid", "Disagreement box", "Book-title test"],
    tech: "Three sources on one topic",
    tech_purpose: "The standard says several, which is more than two",
    ai_prompts: ["Write three sources with partial overlap and one conflict", "Generate idea-based heading schemes"],
    assessment: ["Check headings are ideas not titles", "Confirm disagreements are named", "Read for a knowledgeable voice"],
    why_it_works: ["Deciding idea headings first makes integration structural", "The book-title test is a check students can run on their own plan", "Naming disagreement is more honest than choosing silently", "Asking whether a reader could tell the sources apart is the test of integration"],
  },
  {
    standard_code: "RI.5.10",
    title: "A Section You Cannot Summarize Was Not Read",
    badge: "Grade 5",
    route_name: "Strategy Instruction",
    route_line: "Chunk it → Read one → Summarize before moving on",
    success_criteria: ["Reads dense nonfiction", "Summarizes each section", "Works independently"],
    steps: [
      { name: "Four Terms First", minutes: 8, body: "Pre-taught before the text opens.", science_tag: "retrieval" },
      { name: "The Skim", minutes: 8, body: "Named honestly. Eyes move, nothing lands, and the gap shows up pages later.", science_tag: "metacognition" },
      { name: "Mark the Chunks", minutes: 10, body: "Before reading. A long text becomes several short ones.", science_tag: "dual-coding" },
      { name: "Summarize or Reread", minutes: 16, body: "One sentence per section before moving on. If it will not come, the section was not read.", science_tag: "retrieval" },
      { name: "Where It Got Dense", minutes: 8, body: "Marked, and reread deliberately.", science_tag: "metacognition" },
      { name: "Read Independently", minutes: 14, body: "With the routine running unprompted.", science_tag: "spaced" },
      { name: "Say It Back Whole", minutes: 4, body: "From the section summaries.", science_tag: "retrieval" },
    ],
    ef_supports: ["Pre-taught terms", "Chunk marking", "One-sentence summary lines", "Density marks"],
    tech: "Dense nonfiction in the 4-5 band",
    tech_purpose: "Chunking only matters where the text is genuinely long",
    ai_prompts: ["Write multi-section informational texts", "Generate section summary prompts"],
    assessment: ["Check a summary exists per section", "Confirm chunks were marked first", "Test the whole-text retell"],
    why_it_works: ["A section that cannot be summarized is a gap found immediately rather than later", "Marking chunks first makes the end visible", "Pre-teaching terms removes the barrier that ends the attempt", "Retelling from summaries proves the sections connected"],
  },
  {
    standard_code: "RF.5.3.A",
    title: "Read It, Then Mean It",
    badge: "Grade 5",
    route_name: "Explicit Instruction",
    route_line: "Find the root → Read the whole → State the meaning",
    success_criteria: ["Decodes multisyllabic words", "Uses morphology", "Works in and out of context"],
    steps: [
      { name: "Retrieve Roots and Affixes", minutes: 5, body: "Greek and Latin, from grade 4.", science_tag: "retrieval" },
      { name: "Decoded and Skipped", minutes: 10, body: "The word read perfectly and passed over. Comprehension did not move.", science_tag: "metacognition" },
      { name: "Root First", minutes: 12, body: "Before the sounds. Morphology gives a way in phonics alone does not.", science_tag: "elaboration" },
      { name: "Then the Syllables", minutes: 12, body: "Split what remains, read through, blend.", science_tag: "dual-coding" },
      { name: "Say What It Means", minutes: 12, body: "From the parts. Required every time.", science_tag: "elaboration" },
      { name: "Out of Context", minutes: 8, body: "A word list, with no sentence to lean on. The standard names both.", science_tag: "interleaving" },
      { name: "Yesterday's Words", minutes: 3, body: "Read and defined again, cold.", science_tag: "spaced" },
    ],
    ef_supports: ["Root-first routine", "Meaning requirement", "In-and-out-of-context sets", "Word log"],
    tech: "Word lists and connected text",
    tech_purpose: "The standard names both explicitly",
    ai_prompts: ["Generate multisyllabic words with recognizable roots", "Write sentences containing target words"],
    assessment: ["Require the meaning as well as the reading", "Test in isolation and in text", "Check the root is found first"],
    why_it_works: ["Requiring the meaning closes the gap between decoding and comprehension", "Finding the root first uses knowledge phonics cannot reach", "Out-of-context practice removes the crutch of surrounding clues", "Cold recall the next day tests retention rather than exposure"],
  },
  {
    standard_code: "RF.5.4.A",
    title: "Two Decisions Before You Start",
    badge: "Grade 5",
    route_name: "Strategy Instruction",
    route_line: "Name the purpose → Name the approach → Check you met it",
    success_criteria: ["Sets a purpose", "Adjusts the approach", "Monitors against it"],
    steps: [
      { name: "Retrieve Purpose Types", minutes: 4, body: "Locate, follow, understand, enjoy.", science_tag: "retrieval" },
      { name: "One Speed for Everything", minutes: 10, body: "Named as the default. One speed cannot serve four purposes.", science_tag: "metacognition" },
      { name: "Purpose, Then Approach", minutes: 12, body: "Two decisions, written down. The second is the one skipped.", science_tag: "metacognition" },
      { name: "One Text, Four Purposes", minutes: 14, body: "The same page read four ways. If it looked identical, one was wrong.", science_tag: "interleaving" },
      { name: "Close and Answer", minutes: 10, body: "Against the purpose, text shut.", science_tag: "retrieval" },
      { name: "Deliberately Mismatched", minutes: 8, body: "Skim where close reading was needed. Feel it fail.", science_tag: "elaboration" },
      { name: "Choose Both Yourself", minutes: 4, body: "Unprompted, for a new text.", science_tag: "metacognition" },
    ],
    ef_supports: ["Two-decision card", "Four-purpose set", "Close-and-answer check", "Mismatch exercise"],
    tech: "One text reused across purposes",
    tech_purpose: "Holding the text constant isolates the approach",
    ai_prompts: ["Generate four purposes for one text", "Write purpose-matched question sets"],
    assessment: ["Check both decisions are recorded", "Watch whether behavior changes", "Confirm the check happens"],
    why_it_works: ["Naming the approach surfaces the decision usually left implicit", "One text and four purposes isolates approach as the variable", "A deliberate mismatch makes the cost felt rather than described", "Answering with the text closed tests reading, not searching"],
  },
  {
    standard_code: "RF.5.4.B",
    title: "Mark the Phrases First",
    badge: "Grade 5",
    route_name: "Routine and Practice",
    route_line: "Work out the meaning → Mark the groups → Read it aloud",
    success_criteria: ["Reads in phrases", "Uses accuracy, rate and expression", "Improves across readings"],
    steps: [
      { name: "Retrieve Punctuation Jobs", minutes: 4, body: "What each mark does to the voice.", science_tag: "retrieval" },
      { name: "Word by Word in Long Sentences", minutes: 10, body: "Every word known and the sentence still collapses. Length is the problem.", science_tag: "metacognition" },
      { name: "Meaning Before Expression", minutes: 12, body: "Say what the sentence means, then read it that way. Expression follows sense.", science_tag: "elaboration" },
      { name: "Mark the Groups", minutes: 12, body: "Slashes where the voice should join words.", science_tag: "dual-coding" },
      { name: "Three Reads", minutes: 12, body: "Successive, as the standard says. Scored on all three measures.", science_tag: "spaced" },
      { name: "Poetry", minutes: 10, body: "Line breaks are not stops.", science_tag: "interleaving" },
      { name: "Read to a Listener", minutes: 4, body: "Who says what they could follow.", science_tag: "collaborative" },
    ],
    ef_supports: ["Phrase-marking slashes", "Meaning-first rule", "Three-score rubric", "Poetry set"],
    tech: "Long-sentence prose and poetry",
    tech_purpose: "Phrasing matters where sentences are long",
    ai_prompts: ["Write passages with demanding sentence length", "Generate poetry with enjambment"],
    assessment: ["Listen for phrase groups", "Compare read one and read three", "Check meaning preceded expression"],
    why_it_works: ["Marking phrases makes an invisible grouping decision visible", "Establishing meaning first keeps expression from becoming performance", "Naming length rather than vocabulary targets the real cause", "Enjambment forces reading for sense over line"],
  },
  {
    standard_code: "RF.5.4.C",
    title: "Go Back to Where It Made Sense",
    badge: "Grade 5",
    route_name: "Strategy Instruction",
    route_line: "Check the paragraph → Find where it went → Reread from there",
    success_criteria: ["Monitors at passage level", "Locates the breakdown", "Rereads from the right point"],
    steps: [
      { name: "Retrieve the Check Question", minutes: 4, body: "Did that make sense — asked of a paragraph.", science_tag: "retrieval" },
      { name: "Perfect Reading, No Meaning", minutes: 12, body: "A passage read faultlessly that nobody can retell.", science_tag: "metacognition" },
      { name: "Check Every Paragraph", minutes: 12, body: "However smoothly it read. Monitoring does not stop when decoding is secure.", science_tag: "metacognition" },
      { name: "Where Did It Go", minutes: 12, body: "Located rather than felt. Usually earlier than expected.", science_tag: "elaboration" },
      { name: "Reread From There", minutes: 12, body: "Not the word, not the start. From the last point it held.", science_tag: "elaboration" },
      { name: "Partner Listening", minutes: 8, body: "One reads, one listens for sense rather than errors.", science_tag: "collaborative" },
      { name: "Yesterday's Passage", minutes: 3, body: "Reread with the paragraph check running.", science_tag: "spaced" },
    ],
    ef_supports: ["Paragraph check routine", "Where-did-it-go marking", "Reread-from-there prompt", "Meaning-focused listening"],
    tech: "Passages with built-in comprehension traps",
    tech_purpose: "A passage-level breakdown has to be constructed to be practiced",
    ai_prompts: ["Write passages that decode easily but confuse", "Generate paragraph monitoring prompts"],
    assessment: ["Check monitoring on smooth text", "Confirm rereading starts at the right point", "Ask for a retell"],
    why_it_works: ["A faultlessly read passage nobody can retell separates accuracy from comprehension", "Checking smooth paragraphs is where the habit actually matters", "Locating where the sense went makes rereading targeted", "Listening for meaning rather than errors trains the right attention"],
  },
];

seedStandardsBatch({
  label: "Batch 18 — grade 5 reading",
  standardsData,
  unpacksData,
  blueprintsData,
});
