// @ts-nocheck
/**
 * Batch 10: grade 2 writing, speaking and language.
 *
 * The other half of the "Unpacking Standards 2nd" deck. With batch 9 this
 * completes grade 2 — every ELA standard in the deck now has an unpack and a
 * blueprint, rather than the seven that were there before.
 *
 * As with batch 9, the challenges are the deck's own misconceptions. Several
 * are unusually specific and would not have been guessed: apostrophes landing
 * on every word ending in s, revision meaning recopying neatly, one student
 * doing the whole shared research project while the rest watch.
 *
 * American spellings throughout.
 *
 *   bun run scripts/seed-standards-batch-10.ts
 */
import { seedStandardsBatch } from "./lib/seed-standards-batch";

const standardsData = [
  // ─── Writing ─────────────────────────────────────────────────────────────
  {
    code: "W.2.2",
    name: "Teach a topic with facts and definitions",
    plain_reading:
      "Write informative/explanatory texts in which they introduce a topic, use facts and definitions to develop points, and provide a concluding statement.",
    learning_target: "I can write to teach someone, using facts rather than what I think.",
    skills: ["Informative Writing", "Facts and Definitions", "Conclusion"],
    science_tags: ["elaboration", "dual-coding"],
    match_keys: ["informative explanatory", "facts and definitions", "develop points", "concluding statement", "second grade writing"],
  },
  {
    code: "W.2.3",
    name: "Write a story someone can picture",
    plain_reading:
      "Write narratives in which they recount a well-elaborated event, include details, use temporal words, and provide a sense of closure.",
    learning_target: "I can write a story with feelings in it, in order, that ends properly.",
    skills: ["Narrative Writing", "Descriptive Detail", "Temporal Words"],
    science_tags: ["elaboration", "dual-coding"],
    match_keys: ["narrative", "well-elaborated event", "temporal words", "sense of closure", "thoughts and feelings"],
  },
  {
    code: "W.2.5",
    name: "Change the writing, not just the handwriting",
    plain_reading:
      "With guidance and support from adults and peers, focus on a topic and strengthen writing as needed by revising and editing.",
    learning_target: "I can make my writing better, not just neater.",
    skills: ["Revising", "Editing", "Focus"],
    science_tags: ["metacognition", "collaborative"],
    match_keys: ["revising and editing", "strengthen writing", "focus on a topic", "feedback", "draft"],
  },
  {
    code: "W.2.6",
    name: "Write and publish with a computer",
    plain_reading:
      "With guidance and support from adults, use a variety of digital tools to produce and publish writing.",
    learning_target: "I can type my writing and share it with a reader.",
    skills: ["Digital Tools", "Publishing", "Keyboarding"],
    science_tags: ["collaborative", "interleaving"],
    match_keys: ["digital tools", "produce and publish writing", "keyboarding", "collaborate", "second grade technology"],
  },
  {
    code: "W.2.7",
    name: "Research something together",
    plain_reading: "Participate in shared research and writing projects.",
    learning_target: "I can do my own part of a project the whole class is building.",
    skills: ["Shared Research", "Multiple Sources", "Collaboration"],
    science_tags: ["collaborative", "interleaving"],
    match_keys: ["shared research", "writing projects", "several books on one topic", "group roles"],
  },
  {
    code: "W.2.8",
    name: "Gather what you need to answer a question",
    plain_reading:
      "Recall information from experiences or gather information from provided sources to answer a question.",
    learning_target: "I can take notes in my own words instead of copying sentences.",
    skills: ["Note-Taking", "Recall", "Using Sources"],
    science_tags: ["retrieval", "metacognition"],
    match_keys: ["recall information", "gather from provided sources", "answer a question", "note-taking", "research"],
  },

  // ─── Speaking and listening ──────────────────────────────────────────────
  {
    code: "SL.2.1",
    name: "Answer the person, not just the topic",
    plain_reading:
      "Participate in collaborative conversations with diverse partners about grade 2 topics and texts with peers and adults.",
    learning_target: "I can add to what my partner just said instead of waiting to say my own thing.",
    skills: ["Collaborative Conversation", "Building on Ideas", "Asking for Clarification"],
    science_tags: ["collaborative", "metacognition"],
    match_keys: ["collaborative conversations", "agreed-upon rules", "build on others talk", "multiple exchanges", "clarification"],
  },
  {
    code: "SL.2.2",
    name: "Hold on to what you heard",
    plain_reading:
      "Recount or describe key ideas or details from a text read aloud or information presented orally or through other media.",
    learning_target: "I can tell the key ideas from something I listened to, including the middle.",
    skills: ["Active Listening", "Recounting", "Key Ideas"],
    science_tags: ["retrieval", "dual-coding"],
    match_keys: ["recount key ideas", "text read aloud", "presented orally", "media", "listening"],
  },
  {
    code: "SL.2.3",
    name: "Ask the question that would help",
    plain_reading:
      "Ask and answer questions about what a speaker says in order to clarify comprehension, gather information, or deepen understanding.",
    learning_target: "I can ask about the part I did not follow, not the part already answered.",
    skills: ["Clarifying Questions", "Listening", "Gathering Information"],
    science_tags: ["metacognition", "collaborative"],
    match_keys: ["ask and answer questions", "what a speaker says", "clarify comprehension", "deepen understanding"],
  },
  {
    code: "SL.2.4",
    name: "Tell it clearly and loudly enough",
    plain_reading:
      "Tell a story or recount an experience with appropriate facts and relevant, descriptive details, speaking audibly in coherent sentences.",
    learning_target: "I can tell a story so the person at the back can hear and follow it.",
    skills: ["Oral Storytelling", "Audibility", "Descriptive Detail"],
    science_tags: ["collaborative", "spaced"],
    match_keys: ["speaking audibly", "coherent sentences", "descriptive details", "recount an experience", "presentation"],
  },
  {
    code: "SL.2.5",
    name: "Add a picture that explains something",
    plain_reading:
      "Create audio recordings of stories or poems; add drawings or other visual displays to clarify ideas, thoughts, and feelings.",
    learning_target: "I can make a picture that shows something my words did not.",
    skills: ["Audio Recording", "Visual Displays", "Clarifying"],
    science_tags: ["dual-coding", "collaborative"],
    match_keys: ["audio recordings", "visual displays", "clarify ideas thoughts feelings", "drawings", "presentation"],
  },
  {
    code: "SL.2.6",
    name: "Answer in a whole sentence when it matters",
    plain_reading:
      "Produce complete sentences when appropriate to task and situation in order to provide requested detail or clarification.",
    learning_target: "I can give a full answer when one word is not enough.",
    skills: ["Complete Sentences", "Detail", "Adjusting to Situation"],
    science_tags: ["spaced", "collaborative"],
    match_keys: ["complete sentences", "task and situation", "requested detail", "clarification", "oral language"],
  },

  // ─── Language ────────────────────────────────────────────────────────────
  {
    code: "L.2.2",
    name: "Capitals, commas and apostrophes",
    plain_reading:
      "Demonstrate command of the conventions of standard English capitalization, punctuation, and spelling when writing, including apostrophes for contractions and possessives.",
    learning_target: "I can use an apostrophe only when something is missing or owned.",
    skills: ["Capitalization", "Commas", "Apostrophes"],
    science_tags: ["spaced", "metacognition"],
    match_keys: ["capitalize holidays product geographic", "commas in greetings", "apostrophes contractions possessives", "spelling patterns"],
  },
  {
    code: "L.2.3",
    name: "Talk one way to a friend, another to a principal",
    plain_reading:
      "Use knowledge of language and its conventions when writing, speaking, reading, or listening, comparing formal and informal uses of English.",
    learning_target: "I can choose my words to suit who I am talking to.",
    skills: ["Formal and Informal", "Audience", "Word Choice"],
    science_tags: ["elaboration", "collaborative"],
    match_keys: ["formal and informal English", "conventions of language", "audience", "choose words for the situation"],
  },
  {
    code: "L.2.5",
    name: "Words that nearly mean the same thing",
    plain_reading:
      "Demonstrate understanding of word relationships and nuances in word meanings, including shades of meaning among closely related verbs and adjectives.",
    learning_target: "I can put words in order from gentle to strong.",
    skills: ["Shades of Meaning", "Word Relationships", "Categories"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["shades of meaning", "closely related verbs", "word relationships", "synonyms", "real-life connections"],
  },
  {
    code: "L.2.6",
    name: "Use the new word, do not just know it",
    plain_reading:
      "Use words and phrases acquired through conversations, reading and being read to, and responding to texts, including adjectives and adverbs to describe.",
    learning_target: "I can put a new word into my own writing and talking.",
    skills: ["Vocabulary Use", "Adjectives and Adverbs", "Word Acquisition"],
    science_tags: ["retrieval", "spaced"],
    match_keys: ["words and phrases acquired", "adjectives and adverbs to describe", "vocabulary", "use new words"],
  },
];

const unpacksData = [
  {
    standard_code: "W.2.2",
    verbs: [
      { word: "Introduce", gloss: "open by naming the topic" },
      { word: "Develop", gloss: "build the point out with facts" },
      { word: "Define", gloss: "explain a word the reader may not know" },
    ],
    concepts: ["Fact versus opinion", "Definition", "Concluding statement"],
    vocabulary: [
      { term: "informative", definition: "writing that teaches, not writing that argues" },
      { term: "fact", definition: "something true whether or not you like it" },
      { term: "definition", definition: "what a word means, explained for your reader" },
      { term: "conclusion", definition: "the sentence that finishes the piece" },
    ],
    prior_skills: ["Name a topic and give facts", "Write several related sentences", "Provide closure"],
    prior_standards: [{ code: "W.1.2", text: "Name a topic, supply some facts and provide some sense of closure" }],
    future_standards: [{ code: "W.3.2", text: "Develop the topic with facts, definitions and details, grouping information" }],
    challenges: [
      { problem: "Opinion slips into an informative piece", fix: "Sort fact from opinion before drafting, not after — the deck is explicit that the sorting comes first" },
      { problem: "Technical words are used but never explained", fix: "Circle any word a friend might not know and define it in your own words" },
    ],
    mastery_statement: "Student can introduce a topic and develop it with facts and definitions, then conclude.",
    ladder: [
      { name: "I can name my topic", descriptor: "Introduces the subject" },
      { name: "I can give facts", descriptor: "Supplies true information" },
      { name: "I can explain a hard word", descriptor: "Defines for the reader" },
      { name: "I can finish it properly", descriptor: "Writes a concluding statement" },
    ],
  },
  {
    standard_code: "W.2.3",
    verbs: [
      { word: "Recount", gloss: "tell what happened" },
      { word: "Elaborate", gloss: "add the detail that makes it real" },
      { word: "Signal", gloss: "use words that mark the order" },
    ],
    concepts: ["Well-elaborated event", "Thoughts and feelings", "Temporal words", "Closure"],
    vocabulary: [
      { term: "narrative", definition: "a story about something that happened" },
      { term: "detail", definition: "the small thing that makes a reader picture it" },
      { term: "temporal word", definition: "a word that shows when — first, then, later" },
      { term: "closure", definition: "an ending that feels finished" },
    ],
    prior_skills: ["Write about one event in order", "Use a temporal word", "Write complete sentences"],
    prior_standards: [{ code: "W.1.3", text: "Write narratives recounting two or more sequenced events with some detail" }],
    future_standards: [{ code: "W.3.3", text: "Write narratives using dialogue and descriptions of actions, thoughts and feelings" }],
    challenges: [
      { problem: "A bare list of events with no feelings — a summary, not a story", fix: "One feeling sentence required after each event. Well-elaborated is in the standard" },
      { problem: "The story stops instead of ending", fix: "A menu of closing moves, one chosen deliberately" },
    ],
    mastery_statement: "Student can recount an event with details of thought and feeling, ordered and closed.",
    ladder: [
      { name: "I can tell what happened", descriptor: "Recounts an event" },
      { name: "I can put it in order", descriptor: "Uses temporal words" },
      { name: "I can add how it felt", descriptor: "Includes thoughts and feelings" },
      { name: "I can end it properly", descriptor: "Provides closure" },
    ],
  },
  {
    standard_code: "W.2.5",
    verbs: [
      { word: "Revise", gloss: "change what it says" },
      { word: "Edit", gloss: "fix how it is written" },
      { word: "Focus", gloss: "keep it about one thing" },
    ],
    concepts: ["Revising versus editing", "Focus", "Feedback"],
    vocabulary: [
      { term: "revise", definition: "change the writing itself — add, cut, move" },
      { term: "edit", definition: "fix spelling, capitals and punctuation" },
      { term: "draft", definition: "a version that is not finished yet" },
      { term: "feedback", definition: "what a reader tells you about your writing" },
    ],
    prior_skills: ["Write a draft", "Reread own writing", "Take a suggestion"],
    prior_standards: [{ code: "W.1.5", text: "With guidance and support, focus on a topic and respond to questions and suggestions" }],
    future_standards: [{ code: "W.3.5", text: "With guidance and support, develop and strengthen writing by planning, revising and editing" }],
    challenges: [
      { problem: "Recopying neatly is called revising", fix: "Revising changes content, editing fixes conventions. Two different colored pens, so which one happened is visible" },
      { problem: "Every suggestion is accepted or none are", fix: "Choose two changes to make and say why the others were left" },
    ],
    mastery_statement: "Student can revise content and edit conventions as two distinct acts, with support.",
    ladder: [
      { name: "I can reread my writing", descriptor: "Reviews the draft" },
      { name: "I can fix my spelling", descriptor: "Edits conventions" },
      { name: "I can add or cut", descriptor: "Revises content" },
      { name: "I can tell them apart", descriptor: "Distinguishes revising from editing" },
    ],
  },
  {
    standard_code: "W.2.6",
    verbs: [
      { word: "Produce", gloss: "write it on the computer" },
      { word: "Publish", gloss: "put it where a reader will find it" },
      { word: "Collaborate", gloss: "work on it with someone else" },
    ],
    concepts: ["Digital production", "Publishing for a reader", "Content before decoration"],
    vocabulary: [
      { term: "publish", definition: "share your writing so others can read it" },
      { term: "digital tool", definition: "a program you write or make with" },
      { term: "keyboard", definition: "how you type the letters" },
      { term: "collaborate", definition: "work together on the same thing" },
    ],
    prior_skills: ["Write a draft on paper", "Find letters on a keyboard", "Save a file with help"],
    prior_standards: [{ code: "W.1.6", text: "With guidance and support, use digital tools to produce and publish writing" }],
    future_standards: [{ code: "W.3.6", text: "With guidance and support, use technology to produce and publish writing" }],
    challenges: [
      { problem: "The time goes into fonts and colors rather than the writing", fix: "Content first, formatting last, and say so before the laptops open" },
      { problem: "Typing is so slow the thinking stops", fix: "Draft on paper, type to publish — the standard is about publishing, not composing at a keyboard" },
    ],
    mastery_statement: "Student can produce and publish a piece of writing using a digital tool, with support.",
    ladder: [
      { name: "I can find the letters", descriptor: "Uses basic keyboarding" },
      { name: "I can type my writing", descriptor: "Produces digitally" },
      { name: "I can work with a partner", descriptor: "Collaborates" },
      { name: "I can publish it", descriptor: "Shares for a reader" },
    ],
  },
  {
    standard_code: "W.2.7",
    verbs: [
      { word: "Participate", gloss: "do your part of it" },
      { word: "Research", gloss: "find out from more than one book" },
      { word: "Produce", gloss: "make something together" },
    ],
    concepts: ["Shared research", "Several sources", "Everyone has a job"],
    vocabulary: [
      { term: "research", definition: "finding out about something on purpose" },
      { term: "shared", definition: "done by the whole group together" },
      { term: "source", definition: "a place the information came from" },
    ],
    prior_skills: ["Read informational text", "Work in a group", "Record a fact"],
    prior_standards: [{ code: "W.1.7", text: "Participate in shared research and writing projects" }],
    future_standards: [{ code: "W.3.7", text: "Conduct short research projects that build knowledge about a topic" }],
    challenges: [
      { problem: "One student does the work while the others watch", fix: "Distinct named roles, assigned before the project starts — the deck names this as the fix" },
      { problem: "Facts are collected but never combined", fix: "A single shared page everyone must add to and read" },
    ],
    mastery_statement: "Student can carry a defined role in a shared research project and contribute to the product.",
    ladder: [
      { name: "I can find one fact", descriptor: "Locates information" },
      { name: "I can do my job", descriptor: "Fulfils a role" },
      { name: "I can use two books", descriptor: "Uses several sources" },
      { name: "I can help make the product", descriptor: "Contributes to shared writing" },
    ],
  },
  {
    standard_code: "W.2.8",
    verbs: [
      { word: "Recall", gloss: "get it from your own memory" },
      { word: "Gather", gloss: "get it from a source" },
      { word: "Answer", gloss: "use what you found" },
    ],
    concepts: ["Note-taking in words", "Recall versus research", "Answering the question"],
    vocabulary: [
      { term: "recall", definition: "remember something you already know" },
      { term: "gather", definition: "collect information from somewhere else" },
      { term: "source", definition: "the book or site it came from" },
      { term: "information", definition: "facts that help answer something" },
    ],
    prior_skills: ["Answer a question about a text", "Read informational text", "Write a phrase"],
    prior_standards: [{ code: "W.1.8", text: "With guidance and support, recall information or gather information to answer a question" }],
    future_standards: [{ code: "W.3.8", text: "Recall information and take brief notes on sources, sorting evidence into categories" }],
    challenges: [
      { problem: "Whole sentences get copied out of the source", fix: "Note-taking in words and phrases has to be taught directly — a box too small for a sentence does it faster than a rule" },
      { problem: "What they already knew is never used", fix: "Recall first, on paper, before any book opens" },
    ],
    mastery_statement: "Student can gather information in their own words and use it to answer a question.",
    ladder: [
      { name: "I can say what I know", descriptor: "Recalls from experience" },
      { name: "I can find it in a book", descriptor: "Gathers from a source" },
      { name: "I can write it in my words", descriptor: "Takes notes rather than copying" },
      { name: "I can answer the question", descriptor: "Uses what was gathered" },
    ],
  },
  {
    standard_code: "SL.2.1",
    verbs: [
      { word: "Participate", gloss: "join the conversation" },
      { word: "Build on", gloss: "add to what was just said" },
      { word: "Clarify", gloss: "ask when you did not follow" },
    ],
    concepts: ["Agreed-upon rules", "Multiple exchanges", "Responding versus reciting"],
    vocabulary: [
      { term: "discussion", definition: "a conversation that goes somewhere" },
      { term: "build on", definition: "add to what your partner said" },
      { term: "turn", definition: "when it is your time to talk" },
      { term: "clarify", definition: "ask so it makes sense" },
    ],
    prior_skills: ["Take turns", "Listen to a partner", "Ask a question"],
    prior_standards: [{ code: "SL.1.1", text: "Build on others' talk through multiple exchanges" }],
    future_standards: [{ code: "SL.3.1", text: "Engage effectively in collaborative discussions, coming prepared" }],
    challenges: [
      { problem: "Students wait for a turn to deliver a prepared idea rather than responding", fix: "Every turn must open by naming what the previous person said. A prepared idea cannot survive that opening" },
      { problem: "Confusion goes unvoiced", fix: "One clarifying question required per group per round" },
    ],
    mastery_statement: "Student can respond to what was just said and ask for clarification when needed.",
    ladder: [
      { name: "I can take a turn", descriptor: "Participates" },
      { name: "I can follow the rules", descriptor: "Observes agreed norms" },
      { name: "I can add to their idea", descriptor: "Builds on others' talk" },
      { name: "I can ask when I am lost", descriptor: "Seeks clarification" },
    ],
  },
  {
    standard_code: "SL.2.2",
    verbs: [
      { word: "Recount", gloss: "say back what you heard" },
      { word: "Describe", gloss: "give the details" },
      { word: "Listen", gloss: "attend on purpose" },
    ],
    concepts: ["Listening comprehension", "Key ideas", "Holding the middle"],
    vocabulary: [
      { term: "recount", definition: "tell it back" },
      { term: "key idea", definition: "the part that really mattered" },
      { term: "detail", definition: "a smaller piece of information" },
      { term: "media", definition: "a video or recording you learn from" },
    ],
    prior_skills: ["Listen to a read-aloud", "Retell a story", "Answer questions about listening"],
    prior_standards: [{ code: "SL.1.2", text: "Ask and answer questions about key details in a text read aloud" }],
    future_standards: [{ code: "SL.3.2", text: "Determine the main ideas and supporting details of a text read aloud" }],
    challenges: [
      { problem: "The first and last things heard are remembered and the middle is lost", fix: "A three-box picture sheet filled during listening — even pictorial notes hold the middle" },
      { problem: "Listening is passive until the question arrives", fix: "Say what you are listening for before it starts" },
    ],
    mastery_statement: "Student can recount key ideas and details from something heard, including the middle.",
    ladder: [
      { name: "I can listen quietly", descriptor: "Attends" },
      { name: "I can say one thing", descriptor: "Recalls a detail" },
      { name: "I can say the key ideas", descriptor: "Recounts main content" },
      { name: "I can get the middle too", descriptor: "Retains across the whole" },
    ],
  },
  {
    standard_code: "SL.2.3",
    verbs: [
      { word: "Ask", gloss: "put the question that helps" },
      { word: "Clarify", gloss: "make the unclear part clear" },
      { word: "Deepen", gloss: "find out more than you were told" },
    ],
    concepts: ["Clarifying question", "Listening for the answer", "Deepening"],
    vocabulary: [
      { term: "clarify", definition: "make something clearer" },
      { term: "speaker", definition: "the person talking" },
      { term: "understand", definition: "know what they meant" },
    ],
    prior_skills: ["Ask a question", "Listen to a speaker", "Notice confusion"],
    prior_standards: [{ code: "SL.1.3", text: "Ask and answer questions about what a speaker says to gather information" }],
    future_standards: [{ code: "SL.3.3", text: "Ask and answer questions about information from a speaker, offering elaboration" }],
    challenges: [
      { problem: "Questions are asked that the speaker already answered", fix: "Before asking, say what you did hear. Half the questions disappear" },
      { problem: "I do not get it is offered as the question", fix: "Name the part — which sentence lost you?" },
    ],
    mastery_statement: "Student can ask a question that clarifies or deepens what a speaker said.",
    ladder: [
      { name: "I can listen to the speaker", descriptor: "Attends" },
      { name: "I can answer a question", descriptor: "Responds about content" },
      { name: "I can ask about the muddy part", descriptor: "Clarifies precisely" },
      { name: "I can ask for more", descriptor: "Deepens understanding" },
    ],
  },
  {
    standard_code: "SL.2.4",
    verbs: [
      { word: "Tell", gloss: "deliver it to a listener" },
      { word: "Speak", gloss: "audibly, so it carries" },
      { word: "Describe", gloss: "with details that matter" },
    ],
    concepts: ["Audibility", "Relevant detail", "Coherent sentences"],
    vocabulary: [
      { term: "audibly", definition: "loudly enough to be heard" },
      { term: "descriptive", definition: "giving a picture" },
      { term: "coherent", definition: "making sense in order" },
      { term: "recount", definition: "tell about something that happened" },
    ],
    prior_skills: ["Speak to a group", "Retell an experience", "Use complete sentences"],
    prior_standards: [{ code: "SL.1.4", text: "Describe people, places, things and events with relevant details, speaking audibly" }],
    future_standards: [{ code: "SL.3.4", text: "Report on a topic or text with appropriate facts and relevant details, speaking clearly" }],
    challenges: [
      { problem: "Speech goes toward the floor at low volume", fix: "Audibility is part of the standard, so it gets practiced directly — a listener at the back who signals when they lose you" },
      { problem: "Every detail is included, relevant or not", fix: "Three details only, chosen before speaking" },
    ],
    mastery_statement: "Student can recount an experience audibly, in coherent sentences, with relevant details.",
    ladder: [
      { name: "I can tell what happened", descriptor: "Recounts" },
      { name: "I can be heard", descriptor: "Speaks audibly" },
      { name: "I can use full sentences", descriptor: "Speaks coherently" },
      { name: "I can pick the best details", descriptor: "Selects relevant detail" },
    ],
  },
  {
    standard_code: "SL.2.5",
    verbs: [
      { word: "Create", gloss: "make the recording or picture" },
      { word: "Add", gloss: "put it alongside the words" },
      { word: "Clarify", gloss: "make the idea clearer with it" },
    ],
    concepts: ["Visual that clarifies", "Audio recording", "Matching visual to idea"],
    vocabulary: [
      { term: "audio recording", definition: "your voice, saved to play back" },
      { term: "visual display", definition: "a picture or chart that helps explain" },
      { term: "clarify", definition: "make easier to understand" },
    ],
    prior_skills: ["Draw to show an idea", "Read aloud", "Use a recording device with help"],
    prior_standards: [{ code: "SL.1.5", text: "Add drawings or other visual displays to descriptions to clarify ideas" }],
    future_standards: [{ code: "SL.3.5", text: "Create engaging audio recordings that demonstrate fluid reading at an understandable pace" }],
    challenges: [
      { problem: "Visuals are decorative rather than clarifying", fix: "Ask what the picture explains that the words alone do not. If nothing, it is decoration" },
      { problem: "Recording is redone endlessly for perfection", fix: "Two takes, then move on" },
    ],
    mastery_statement: "Student can add a visual or recording that clarifies an idea rather than decorating it.",
    ladder: [
      { name: "I can draw a picture", descriptor: "Creates a visual" },
      { name: "I can record my voice", descriptor: "Produces audio" },
      { name: "I can match it to my idea", descriptor: "Connects visual to content" },
      { name: "I can say what it explains", descriptor: "Justifies the clarification" },
    ],
  },
  {
    standard_code: "SL.2.6",
    verbs: [
      { word: "Produce", gloss: "say a whole sentence" },
      { word: "Provide", gloss: "give the detail asked for" },
      { word: "Adjust", gloss: "match the situation" },
    ],
    concepts: ["Complete sentence in speech", "Task and situation", "Requested detail"],
    vocabulary: [
      { term: "complete sentence", definition: "a whole thought, said out loud" },
      { term: "detail", definition: "the extra information asked for" },
      { term: "clarification", definition: "saying it again more clearly" },
    ],
    prior_skills: ["Speak in sentences", "Answer a question", "Listen to a request"],
    prior_standards: [{ code: "SL.1.6", text: "Produce complete sentences when appropriate to task and situation" }],
    future_standards: [{ code: "SL.3.6", text: "Speak in complete sentences to provide requested detail or clarification" }],
    challenges: [
      { problem: "One-word answers where a full sentence is called for", fix: "Prompt for the full response every time — the habit is built by the asking, not by a rule" },
      { problem: "Full sentences are used everywhere, including where they are stilted", fix: "Name the situations that need one. Not every answer does" },
    ],
    mastery_statement: "Student can produce a complete sentence when the task or situation calls for one.",
    ladder: [
      { name: "I can answer", descriptor: "Responds" },
      { name: "I can use a whole sentence", descriptor: "Produces complete sentences" },
      { name: "I can add the detail asked for", descriptor: "Provides requested information" },
      { name: "I can tell when it matters", descriptor: "Adjusts to the situation" },
    ],
  },
  {
    standard_code: "L.2.2",
    verbs: [
      { word: "Capitalize", gloss: "on holidays, products and places" },
      { word: "Punctuate", gloss: "commas and apostrophes in their places" },
      { word: "Spell", gloss: "using patterns and references" },
    ],
    concepts: ["Apostrophe for contraction or possession", "Commas in letters", "Proper noun capitals"],
    vocabulary: [
      { term: "capitalize", definition: "start with a big letter" },
      { term: "comma", definition: "the mark that separates parts" },
      { term: "apostrophe", definition: "the mark for a missing letter or for owning" },
      { term: "contraction", definition: "two words squashed with a letter missing" },
      { term: "possessive", definition: "showing something belongs to someone" },
    ],
    prior_skills: ["Capitalize sentence starts and names", "Use end punctuation", "Spell common patterns"],
    prior_standards: [{ code: "L.1.2", text: "Capitalize dates and names, use end punctuation and spell untaught words phonetically" }],
    future_standards: [{ code: "L.3.2", text: "Use commas in addresses and dialogue, and form and use possessives" }],
    challenges: [
      { problem: "Apostrophes land on every word ending in s, plurals included", fix: "Two questions before any apostrophe: is a letter missing, or does someone own it? If neither, no apostrophe" },
      { problem: "Only sentence starts get capitals", fix: "Sort proper nouns from common nouns before writing" },
    ],
    mastery_statement: "Student can use apostrophes only for contractions and possessives, and capitalize proper nouns.",
    ladder: [
      { name: "I can capitalize a sentence", descriptor: "Sentence-initial capitals" },
      { name: "I can capitalize names and places", descriptor: "Proper nouns" },
      { name: "I can use a comma in a letter", descriptor: "Greetings and closings" },
      { name: "I can use an apostrophe correctly", descriptor: "Contractions and possessives only" },
    ],
  },
  {
    standard_code: "L.2.3",
    verbs: [
      { word: "Use", gloss: "apply the conventions of language" },
      { word: "Compare", gloss: "set formal against informal" },
      { word: "Choose", gloss: "pick words for the person" },
    ],
    concepts: ["Formal and informal", "Audience", "Register"],
    vocabulary: [
      { term: "formal", definition: "the careful way, for someone you do not know well" },
      { term: "informal", definition: "the everyday way, with friends" },
      { term: "convention", definition: "the agreed way of doing it" },
      { term: "audience", definition: "who you are talking or writing to" },
    ],
    prior_skills: ["Speak in complete sentences", "Write a sentence", "Notice who you are talking to"],
    prior_standards: [{ code: "L.1.1", text: "Demonstrate command of the conventions of standard English grammar" }],
    future_standards: [{ code: "L.3.3", text: "Choose words and phrases for effect and recognize differences between spoken and written English" }],
    challenges: [
      { problem: "Writing reads exactly like speech, fillers included", fix: "Name the audience out loud before writing. The register follows once the reader is real" },
      { problem: "Formal is treated as better", fix: "Both are correct in their place — compare rather than rank" },
    ],
    mastery_statement: "Student can compare formal and informal English and choose words to suit the audience.",
    ladder: [
      { name: "I can say it my way", descriptor: "Uses everyday language" },
      { name: "I can hear the difference", descriptor: "Compares formal and informal" },
      { name: "I can name my audience", descriptor: "Identifies the reader" },
      { name: "I can choose to match", descriptor: "Adjusts word choice" },
    ],
  },
  {
    standard_code: "L.2.5",
    verbs: [
      { word: "Distinguish", gloss: "tell close words apart" },
      { word: "Identify", gloss: "connect words to real life" },
      { word: "Sort", gloss: "group words by category" },
    ],
    concepts: ["Shades of meaning", "Word relationships", "Categories"],
    vocabulary: [
      { term: "shades of meaning", definition: "the small differences between close words" },
      { term: "related", definition: "words that belong together" },
      { term: "synonym", definition: "a word that means nearly the same" },
      { term: "category", definition: "a group words can belong to" },
    ],
    prior_skills: ["Know common synonyms", "Sort objects", "Use describing words"],
    prior_standards: [{ code: "L.1.5", text: "Demonstrate understanding of word relationships and nuances in word meanings" }],
    future_standards: [{ code: "L.3.5", text: "Distinguish shades of meaning among related words describing states of mind" }],
    challenges: [
      { problem: "All synonyms are treated as interchangeable — toss and hurl the same", fix: "Order them on a line from gentle to strong. A line forces a decision a list does not" },
      { problem: "Words are defined but never connected to life", fix: "Name a real time you would use this one and not that one" },
    ],
    mastery_statement: "Student can order closely related words by intensity and say why they differ.",
    ladder: [
      { name: "I can name a synonym", descriptor: "Identifies related words" },
      { name: "I can sort into groups", descriptor: "Categorizes" },
      { name: "I can put them in order", descriptor: "Distinguishes shades of meaning" },
      { name: "I can say when to use each", descriptor: "Connects to real use" },
    ],
  },
  {
    standard_code: "L.2.6",
    verbs: [
      { word: "Use", gloss: "put the word to work" },
      { word: "Acquire", gloss: "pick it up from reading and talk" },
      { word: "Describe", gloss: "with adjectives and adverbs" },
    ],
    concepts: ["Production over recognition", "Adjectives and adverbs", "Where words come from"],
    vocabulary: [
      { term: "acquire", definition: "pick up and keep" },
      { term: "describe", definition: "say what something is like" },
      { term: "vocabulary", definition: "the words you have" },
    ],
    prior_skills: ["Understand new words in context", "Use describing words", "Listen to read-alouds"],
    prior_standards: [{ code: "L.1.6", text: "Use words and phrases acquired through conversations and reading" }],
    future_standards: [{ code: "L.3.6", text: "Acquire and use grade-appropriate conversational and domain-specific words" }],
    challenges: [
      { problem: "A new word is recognized but never used", fix: "Production is the goal, not recognition. A word is not learned until it appears in their own sentence" },
      { problem: "New words appear once and vanish", fix: "A word wall that must be drawn from, and old words revisited" },
    ],
    mastery_statement: "Student can use newly acquired words and phrases in their own speaking and writing.",
    ladder: [
      { name: "I can hear a new word", descriptor: "Notices unfamiliar vocabulary" },
      { name: "I know what it means", descriptor: "Understands in context" },
      { name: "I can use it in a sentence", descriptor: "Produces the word" },
      { name: "I use it without being asked", descriptor: "Owns the vocabulary" },
    ],
  },
];

const blueprintsData = [
  {
    standard_code: "W.2.2",
    title: "Facts Only, and Explain the Hard Words",
    badge: "Grade 2",
    route_name: "Writing Workshop",
    route_line: "Sort fact from opinion → Draft with facts → Define and conclude",
    success_criteria: ["Introduces the topic", "Uses facts and definitions", "Writes a concluding statement"],
    steps: [
      { name: "Retrieve Fact or Opinion", minutes: 5, body: "Sorted before a word is drafted. The deck puts the sorting first, and that ordering is the whole intervention.", science_tag: "retrieval" },
      { name: "Spot the Opinion in the Middle", minutes: 10, body: "An informative piece with one opinion sentence hidden in it. Students hunt for the intruder.", science_tag: "elaboration" },
      { name: "Three Facts, Three Boxes", minutes: 10, body: "Planned before drafting, each checked against the fact test.", science_tag: "dual-coding" },
      { name: "Circle the Hard Words", minutes: 10, body: "In their own draft, anything a friend might not know. Audience awareness made concrete.", science_tag: "metacognition" },
      { name: "Define It Your Way", minutes: 10, body: "Not the dictionary — the version a friend would understand. Two frames: which means, and that is when.", science_tag: "elaboration" },
      { name: "Conclude With Why It Matters", minutes: 8, body: "Restating the title is not a conclusion. It has to add something.", science_tag: "elaboration" },
      { name: "Reader Marks the Unknowns", minutes: 5, body: "A partner marks any word they did not know. Direct evidence rather than a guess.", science_tag: "collaborative" },
    ],
    ef_supports: ["Fact-or-opinion sorting mat", "Three-box planner", "Definition frames", "Partner unknown-word marking"],
    tech: "Draft on alternate lines",
    tech_purpose: "Room to add definitions where they belong",
    ai_prompts: ["Write informative texts with one opinion sentence hidden inside", "Generate age-appropriate definitions for topic words"],
    assessment: ["Check no opinions survived", "Confirm definitions are in the writer's words", "Read conclusions for added meaning"],
    why_it_works: ["Sorting before drafting is what stops the opinion appearing at all", "A hidden opinion is easier to find in someone else's writing than your own", "Circling in their own draft makes audience awareness a habit", "A partner's marks are evidence, not a guess about what is hard"],
  },
  {
    standard_code: "W.2.3",
    title: "A Story, Not a List of What Happened",
    badge: "Grade 2",
    route_name: "Writing Workshop",
    route_line: "Pick one event → Add what you felt → Order it and close it",
    success_criteria: ["Recounts one elaborated event", "Includes thoughts and feelings", "Uses temporal words and closes"],
    steps: [
      { name: "Retrieve Temporal Words", minutes: 5, body: "First, then, after that, finally. Recalled and displayed.", science_tag: "retrieval" },
      { name: "The List Versus the Story", minutes: 10, body: "Two accounts of the same trip. One is events, one is a story. Students say what the second one has — feelings, and that is the answer.", science_tag: "elaboration" },
      { name: "One Event, Not Ten", minutes: 8, body: "Well-elaborated means one thing described properly. Narrow it before drafting.", science_tag: "metacognition" },
      { name: "A Feeling After Every Event", minutes: 14, body: "Required, one per event. This is the step that turns the summary into a story.", science_tag: "elaboration" },
      { name: "Order It With Words", minutes: 10, body: "Temporal words added on a second pass, so ordering is not competing with detail.", science_tag: "interleaving" },
      { name: "Three Ways to End", minutes: 8, body: "And that is why, I will never forget, we finally. Chosen deliberately.", science_tag: "elaboration" },
      { name: "Read It to Someone", minutes: 5, body: "The listener says what they could picture.", science_tag: "collaborative" },
    ],
    ef_supports: ["Temporal word bank", "One-event narrowing prompt", "Feeling-after-event checklist", "Closing move menu"],
    tech: "Planning sheet then lined paper",
    tech_purpose: "Planning and drafting are separate loads at this age",
    ai_prompts: ["Write the same event as a bare list and as a story", "Generate feeling prompts for narrative events"],
    assessment: ["Count feeling sentences", "Check one event was chosen, not many", "Confirm a closing move was used"],
    why_it_works: ["Comparing a list with a story defines elaboration without defining it", "One feeling per event is countable, so it actually happens", "Narrowing to one event is what well-elaborated means in practice", "Adding order words on a second pass keeps the cognitive load down"],
  },
  {
    standard_code: "W.2.5",
    title: "Two Different Jobs, Two Different Pens",
    badge: "Grade 2",
    route_name: "Writing Workshop",
    route_line: "Reread → Change what it says → Then fix how it is written",
    success_criteria: ["Revises content", "Edits conventions", "Tells the two apart"],
    steps: [
      { name: "Retrieve Revise or Edit", minutes: 5, body: "Sorted as actions: adding a sentence, fixing a capital, cutting a bit, spelling.", science_tag: "retrieval" },
      { name: "Neater Is Not Better", minutes: 10, body: "A piece recopied beautifully with nothing changed. Students judge whether it improved. It did not, and that lands.", science_tag: "elaboration" },
      { name: "Green Pen: Change What It Says", minutes: 14, body: "Add, cut, move. Revising only, and it happens first because it is the one that gets skipped.", science_tag: "dual-coding" },
      { name: "Red Pen: Fix How It Is Written", minutes: 10, body: "Capitals, spelling, punctuation. Editing only, and second.", science_tag: "dual-coding" },
      { name: "Which Pen Did More", minutes: 8, body: "Look at the page. Two colors make the balance visible at a glance.", science_tag: "metacognition" },
      { name: "Partner Suggests Two", minutes: 8, body: "Two possible changes, not a list. Manageable.", science_tag: "collaborative" },
      { name: "Say Why You Left One", minutes: 5, body: "A suggestion declined with a reason. Authorship, not compliance.", science_tag: "metacognition" },
    ],
    ef_supports: ["Green and red pens", "Revise-or-edit sorting cards", "Two-suggestions rule", "Declined-suggestion frame"],
    tech: "Drafts on paper with wide margins",
    tech_purpose: "Revising needs somewhere to add",
    ai_prompts: ["Generate drafts needing content revision rather than editing", "Write revise-or-edit action cards"],
    assessment: ["Look for green ink, not just red", "Check content actually changed", "Read declined-suggestion reasons"],
    why_it_works: ["Two pen colors make an invisible distinction visible on the page", "The beautifully recopied piece shows recopying is not revising", "Revising first protects it from being crowded out by editing", "Declining a suggestion with a reason makes them the author"],
  },
  {
    standard_code: "W.2.6",
    title: "Content First, Fonts Last",
    badge: "Grade 2",
    route_name: "Writing Workshop",
    route_line: "Draft on paper → Type it up → Publish for a reader",
    success_criteria: ["Produces writing with a digital tool", "Collaborates with a peer", "Publishes for a reader"],
    steps: [
      { name: "Retrieve Keyboard Landmarks", minutes: 5, body: "Space, enter, backspace, shift. The four that matter most.", science_tag: "retrieval" },
      { name: "Content First, Say It Out Loud", minutes: 6, body: "Formatting after the words exist. Said before the laptops open, because after is too late.", science_tag: "metacognition" },
      { name: "Draft on Paper", minutes: 12, body: "Composing and typing are different loads. Separating them protects the thinking.", science_tag: "dual-coding" },
      { name: "Type It Up", minutes: 14, body: "Transcription only, which is what makes it manageable.", science_tag: "spaced" },
      { name: "Now You May Format", minutes: 8, body: "Ten minutes, once the words are in. Permission with a boundary.", science_tag: "interleaving" },
      { name: "Two Writers, One Document", minutes: 10, body: "Collaboration, which the standard names explicitly.", science_tag: "collaborative" },
      { name: "Publish It", minutes: 5, body: "Printed, posted or shared. A reader has to actually exist.", science_tag: "collaborative" },
    ],
    ef_supports: ["Keyboard landmark cards", "Content-first rule", "Ten-minute formatting timer", "Shared document"],
    tech: "Laptops or tablets with a shared document tool",
    tech_purpose: "Publishing and collaborating are both in the standard",
    ai_prompts: ["Generate short pieces suitable for typing practice", "Write collaboration prompts for paired writing"],
    assessment: ["Check the words came before the formatting", "Confirm both partners contributed", "See that it reached a reader"],
    why_it_works: ["Naming content-first before the laptops open is the only moment it can be heard", "Drafting on paper stops typing speed from throttling the thinking", "A formatting window satisfies the urge without letting it take the lesson", "A real reader is what publishing means"],
  },
  {
    standard_code: "W.2.7",
    title: "Everybody Has a Job",
    badge: "Grade 2",
    route_name: "Writing Workshop",
    route_line: "Take a role → Find your part → Put it together",
    success_criteria: ["Fulfils a named role", "Uses more than one source", "Contributes to a shared product"],
    steps: [
      { name: "Retrieve the Topic", minutes: 5, body: "What do we already know together? Recall before research.", science_tag: "retrieval" },
      { name: "Name the Roles", minutes: 8, body: "Reader, recorder, checker, presenter. Assigned before anything starts — the deck names this as the fix for one child doing it all.", science_tag: "collaborative" },
      { name: "Your Book, Your Facts", minutes: 14, body: "Each child a different source. Nobody can watch, because nobody else has their book.", science_tag: "collaborative" },
      { name: "The Shared Page", minutes: 12, body: "One page everyone must add to and read. Combining is a step, not an assumption.", science_tag: "dual-coding" },
      { name: "What Did We All Find", minutes: 8, body: "Facts appearing in two books, marked. Corroboration, early.", science_tag: "elaboration" },
      { name: "Build the Product", minutes: 10, body: "A poster, a book, a page — made from the shared page.", science_tag: "interleaving" },
      { name: "Who Did What", minutes: 4, body: "Named aloud. Contribution made visible.", science_tag: "metacognition" },
    ],
    ef_supports: ["Role cards", "One-source-each rule", "Shared recording page", "Contribution round"],
    tech: "A text set — several books on one topic",
    tech_purpose: "One source each is what makes watching impossible",
    ai_prompts: ["Generate text sets on one topic at grade 2 level", "Write role descriptions for shared research"],
    assessment: ["Check every child added to the shared page", "Confirm roles were used", "Listen to the who-did-what round"],
    why_it_works: ["Giving each child a different source removes the option of watching", "Named roles assigned in advance are the deck's own fix", "A shared page makes combining a step rather than a hope", "Saying who did what makes freeloading visible without accusation"],
  },
  {
    standard_code: "W.2.8",
    title: "Notes in Your Words, Not Their Sentences",
    badge: "Grade 2",
    route_name: "Strategy Instruction",
    route_line: "Say what you know → Find the rest → Write it small",
    success_criteria: ["Recalls from experience", "Gathers from a source", "Notes in words, not sentences"],
    steps: [
      { name: "What I Already Know", minutes: 8, body: "On paper before any book opens. Recall is half the standard and it is the half that gets skipped.", science_tag: "retrieval" },
      { name: "The Copied Answer", minutes: 8, body: "A note that is just a sentence from the book. Ask what the child understood. Usually nothing.", science_tag: "elaboration" },
      { name: "Boxes Too Small for a Sentence", minutes: 12, body: "Note-taking taught by the paper. A box that fits three words cannot hold a copied sentence.", science_tag: "dual-coding" },
      { name: "Cover and Write", minutes: 10, body: "Read it, cover it, then write. Copying becomes impossible rather than forbidden.", science_tag: "retrieval" },
      { name: "Answer the Question", minutes: 10, body: "From the notes alone, book closed.", science_tag: "retrieval" },
      { name: "Did I Need That Note", minutes: 6, body: "Cross out notes that did not help. Relevance, judged after the fact.", science_tag: "metacognition" },
      { name: "New Question, Same Notes", minutes: 4, body: "Would these notes answer a different question?", science_tag: "interleaving" },
    ],
    ef_supports: ["Small note boxes", "Cover-and-write routine", "Already-know page", "Cross-out review"],
    tech: "Provided sources at reading level",
    tech_purpose: "The standard says provided sources, so the search is not the task",
    ai_prompts: ["Write short sources with answerable questions", "Generate note-taking prompts in phrases"],
    assessment: ["Check notes are phrases, not sentences", "Confirm the recall page was filled first", "Watch the cover step happen"],
    why_it_works: ["A box too small to copy into teaches note-taking faster than a rule against copying", "Covering the text makes copying physically impossible", "Recall before research uses what they already have", "Crossing out useless notes teaches relevance in hindsight, which is when it is learnable"],
  },
  {
    standard_code: "SL.2.1",
    title: "Say Their Name Before Your Idea",
    badge: "Grade 2",
    route_name: "Structured Discussion",
    route_line: "Listen → Name what they said → Then add yours",
    success_criteria: ["Responds to the previous speaker", "Follows the agreed rules", "Asks for clarification"],
    steps: [
      { name: "Retrieve Our Rules", minutes: 4, body: "Agreed-upon is in the standard, so they are recalled rather than announced.", science_tag: "retrieval" },
      { name: "Two Conversations", minutes: 10, body: "One where each turn ignores the last, one where they connect. Students name which was a conversation.", science_tag: "elaboration" },
      { name: "Open By Naming Theirs", minutes: 14, body: "Every turn starts with what the previous person said. A prepared idea cannot survive that opening — which is the point.", science_tag: "collaborative" },
      { name: "Count the Exchanges", minutes: 10, body: "Back and forth, counted aloud. Three is the target.", science_tag: "collaborative" },
      { name: "One Question Each", minutes: 10, body: "Every group member asks one clarifying question per round. Asking becomes normal rather than an admission.", science_tag: "metacognition" },
      { name: "Rescue a Stalled Talk", minutes: 8, body: "It has stopped. What could you say? Repair is teachable.", science_tag: "elaboration" },
      { name: "Beat Yesterday", minutes: 4, body: "One more exchange than last time.", science_tag: "spaced" },
    ],
    ef_supports: ["Name-theirs sentence stem", "Exchange counter", "One-question-each rule", "Repair phrase list"],
    tech: "None — deliberately unplugged",
    tech_purpose: "Nothing should compete with faces",
    ai_prompts: ["Write connected and disconnected conversations on one topic", "Generate grade 2 discussion prompts"],
    assessment: ["Listen for the previous speaker being named", "Count real exchanges", "Note who never asks"],
    why_it_works: ["Opening by naming the last speaker makes a prepared idea impossible to deliver", "Contrasting two conversations defines building on without a definition", "Counting turns an abstract quality into a number to beat", "Requiring a question each removes the stigma of not understanding"],
  },
  {
    standard_code: "SL.2.2",
    title: "Holding On to the Middle",
    badge: "Grade 2",
    route_name: "Structured Discussion",
    route_line: "Know what you are listening for → Catch it in three boxes → Say it back",
    success_criteria: ["Listens actively", "Recounts key ideas", "Retains the middle as well as the ends"],
    steps: [
      { name: "Retrieve Key Idea", minutes: 4, body: "What makes an idea key rather than merely interesting?", science_tag: "retrieval" },
      { name: "Say What You Are Listening For", minutes: 6, body: "Before it starts. Listening becomes purposeful rather than passive.", science_tag: "metacognition" },
      { name: "Three Boxes, Filled As You Go", minutes: 14, body: "Beginning, middle, end — drawn or written during. The middle box exists because the middle is what gets lost.", science_tag: "dual-coding" },
      { name: "Say It Back", minutes: 10, body: "From the boxes, not from memory alone.", science_tag: "retrieval" },
      { name: "What Was in the Middle", minutes: 8, body: "Asked directly. The deck names this as the gap, so it gets its own question.", science_tag: "retrieval" },
      { name: "Listen to Media", minutes: 10, body: "A video rather than a read-aloud. The standard names other media too.", science_tag: "interleaving" },
      { name: "Yesterday's Read-Aloud", minutes: 4, body: "Recalled cold, a day later.", science_tag: "spaced" },
    ],
    ef_supports: ["Three-box listening sheet", "Listening-for statement", "Pictorial note option", "Media listening set"],
    tech: "Read-alouds and short video",
    tech_purpose: "The standard covers oral and media both",
    ai_prompts: ["Write read-alouds with a substantial middle section", "Generate listening-for prompts"],
    assessment: ["Check the middle box is filled", "Confirm say-it-back covers all three", "Compare listening with and without the sheet"],
    why_it_works: ["A middle box makes the forgotten part a space that has to be filled", "Naming what to listen for turns listening into a task", "Pictorial notes work for children who cannot write fast enough", "Asking about the middle directly tests the thing that fails"],
  },
  {
    standard_code: "SL.2.3",
    title: "Ask About the Part You Missed",
    badge: "Grade 2",
    route_name: "Structured Discussion",
    route_line: "Say what you heard → Name the muddy part → Ask about that",
    success_criteria: ["Asks about what was not said", "Clarifies precisely", "Uses the answer"],
    steps: [
      { name: "Retrieve Question Stems", minutes: 4, body: "Can you say more about, what did you mean by, can you give an example.", science_tag: "retrieval" },
      { name: "The Question Already Answered", minutes: 10, body: "A speaker, then a question they just covered. Students spot why it was wasted.", science_tag: "elaboration" },
      { name: "Say What You Did Hear", minutes: 12, body: "Before asking anything. Half the questions disappear, which is the fix for asking what was already answered.", science_tag: "metacognition" },
      { name: "Name the Muddy Bit", minutes: 10, body: "Not I do not get it — which sentence lost you. Precision makes it answerable.", science_tag: "metacognition" },
      { name: "Ask and Restate", minutes: 10, body: "Ask, listen, say the answer back. Restating proves it landed.", science_tag: "collaborative" },
      { name: "Deepen, Not Just Clarify", minutes: 8, body: "A question that goes past understanding into wanting to know more.", science_tag: "elaboration" },
      { name: "Still Unsure Of", minutes: 4, body: "Written at the end and carried forward.", science_tag: "metacognition" },
    ],
    ef_supports: ["Question stem cards", "Say-what-you-heard routine", "Muddy-bit pointer", "Restating frame"],
    tech: "None — face to face",
    tech_purpose: "Reading uncertainty needs faces",
    ai_prompts: ["Write short talks with one deliberately unclear section", "Generate clarifying versus deepening questions"],
    assessment: ["Check questions are not already answered", "Confirm the muddy part is named", "Listen for accurate restating"],
    why_it_works: ["Saying what you heard first eliminates the already-answered question automatically", "Naming the sentence that lost you makes the question answerable", "Restating proves the clarification worked rather than assuming", "Separating deepening from clarifying shows questions do more than repair"],
  },
  {
    standard_code: "SL.2.4",
    title: "Loud Enough for the Back Row",
    badge: "Grade 2",
    route_name: "Structured Presentation",
    route_line: "Choose three details → Say it in order → Be heard",
    success_criteria: ["Speaks audibly", "Uses coherent sentences", "Includes relevant descriptive detail"],
    steps: [
      { name: "Retrieve Descriptive Words", minutes: 4, body: "Recalled before they are needed.", science_tag: "retrieval" },
      { name: "Three Details Only", minutes: 10, body: "Chosen before speaking. Relevance is a decision made in advance, not during.", science_tag: "metacognition" },
      { name: "The Listener at the Back", minutes: 12, body: "One child at the back raises a hand the moment they lose you. Audibility gets direct practice, because it is in the standard.", science_tag: "collaborative" },
      { name: "Practice Twice", minutes: 10, body: "To a partner first, then the group. The second telling is always better.", science_tag: "spaced" },
      { name: "Whole Sentences Out Loud", minutes: 8, body: "Coherent is in the standard. Fragments get asked again.", science_tag: "elaboration" },
      { name: "Tell It to the Group", minutes: 10, body: "The performance, with the back-row signal running.", science_tag: "collaborative" },
      { name: "What Could I Picture", minutes: 4, body: "The audience says what they saw. Direct feedback on detail.", science_tag: "collaborative" },
    ],
    ef_supports: ["Three-detail planner", "Back-row signal", "Practice-twice routine", "Picture-it feedback prompt"],
    tech: "None — voice only",
    tech_purpose: "Audibility cannot be practiced through a microphone",
    ai_prompts: ["Generate recount prompts for grade 2", "Write descriptive detail banks"],
    assessment: ["Watch the back-row signal", "Count relevant details", "Listen for complete sentences"],
    why_it_works: ["A hand at the back gives instant feedback with nobody being told off", "Choosing three details in advance makes relevance a decision", "The second telling is measurably better, so practice is built in", "Asking what the audience pictured tests detail from the listener's side"],
  },
  {
    standard_code: "SL.2.5",
    title: "A Picture That Explains, Not Decorates",
    badge: "Grade 2",
    route_name: "Structured Presentation",
    route_line: "Say the idea → Ask what a picture could add → Make that",
    success_criteria: ["Creates a visual or recording", "Matches it to the idea", "Says what it clarifies"],
    steps: [
      { name: "Retrieve Clarify", minutes: 4, body: "What does clarify mean? The word the whole standard turns on.", science_tag: "retrieval" },
      { name: "Decoration or Explanation", minutes: 10, body: "Two visuals for one idea. One is pretty, one explains. Students sort — this is the deck's own misconception.", science_tag: "elaboration" },
      { name: "What Do My Words Not Show", minutes: 12, body: "Asked before drawing. The answer is what the picture should be.", science_tag: "metacognition" },
      { name: "Make It", minutes: 12, body: "Drawing or chart, aimed at the gap named.", science_tag: "dual-coding" },
      { name: "Record Your Poem", minutes: 10, body: "Two takes, then move on. Recording is in the standard.", science_tag: "collaborative" },
      { name: "This Helps Because", minutes: 8, body: "Written or said. If the sentence cannot be finished, it was decoration.", science_tag: "metacognition" },
      { name: "Swap and Judge", minutes: 4, body: "A partner says what the visual explained to them.", science_tag: "collaborative" },
    ],
    ef_supports: ["Decoration-or-explanation sorting pair", "What-my-words-miss prompt", "Two-take rule", "Helps-because frame"],
    tech: "Drawing materials and a recording device",
    tech_purpose: "The standard names both visual and audio",
    ai_prompts: ["Generate decorative and explanatory visuals for one idea", "Write poems suitable for recording"],
    assessment: ["Check the visual fills a real gap", "Confirm the helps-because sentence completes", "Listen to recordings for clarity"],
    why_it_works: ["Sorting decoration from explanation names the difference the deck warns about", "Asking what the words miss produces the picture rather than guessing at one", "The helps-because sentence fails audibly when the visual is decoration", "Two takes prevents recording becoming the whole lesson"],
  },
  {
    standard_code: "SL.2.6",
    title: "A Whole Sentence When One Word Will Not Do",
    badge: "Grade 2",
    route_name: "Oral Practice",
    route_line: "Hear the question → Judge what it needs → Answer in full",
    success_criteria: ["Produces complete sentences", "Provides the detail requested", "Judges when a full answer is needed"],
    steps: [
      { name: "Retrieve Complete Sentence", minutes: 4, body: "What makes it whole? Recalled from the writing work.", science_tag: "retrieval" },
      { name: "One Word Is Not Enough", minutes: 10, body: "A one-word answer to a question needing more. The listener is left guessing, which is the point.", science_tag: "elaboration" },
      { name: "Ask Again, Fuller", minutes: 12, body: "Every short answer prompted for the full one. The habit is built by asking, not by a rule.", science_tag: "collaborative" },
      { name: "When Is Short Fine", minutes: 10, body: "Not every answer needs a sentence. Judging the situation is in the standard.", science_tag: "metacognition" },
      { name: "Give the Detail Asked For", minutes: 10, body: "Answer the question that was actually asked, with what it requested.", science_tag: "elaboration" },
      { name: "Partner Practice", minutes: 8, body: "One asks, one answers fully. Swap.", science_tag: "collaborative" },
      { name: "Across the Day", minutes: 4, body: "The same prompt used in maths, in line, at lunch.", science_tag: "spaced" },
    ],
    ef_supports: ["Ask-again prompt", "Situation sorting cards", "Sentence starter strip", "Partner question sets"],
    tech: "None",
    tech_purpose: "This one lives in ordinary classroom talk",
    ai_prompts: ["Generate questions requiring full-sentence answers", "Write situations where a short answer is appropriate"],
    assessment: ["Count full-sentence answers without prompting", "Check the requested detail is given", "Note who judges the situation"],
    why_it_works: ["Prompting for the fuller answer every time is what builds the habit", "A one-word answer that leaves the listener guessing shows why it matters", "Judging when short is fine stops it becoming a stilted rule", "Using it all day is what moves it out of the lesson"],
  },
  {
    standard_code: "L.2.2",
    title: "Missing or Owning — Otherwise No Apostrophe",
    badge: "Grade 2",
    route_name: "Explicit Instruction",
    route_line: "Ask the two questions → Place the mark → Check the plurals",
    success_criteria: ["Uses apostrophes only for contractions and possessives", "Capitalizes proper nouns", "Uses commas in letters"],
    steps: [
      { name: "Retrieve Sentence Capitals", minutes: 4, body: "Last year's rule, still holding.", science_tag: "retrieval" },
      { name: "Cats or Cat's", minutes: 12, body: "Plural against possessive. The deck's misconception is apostrophes on every s, so this is where the lesson starts.", science_tag: "elaboration" },
      { name: "The Two Questions", minutes: 12, body: "Is a letter missing? Does someone own it? If neither, no apostrophe. A rule small enough to use alone.", science_tag: "metacognition" },
      { name: "Build Contractions", minutes: 10, body: "Two words, one squashed, a mark where the letter went. The apostrophe has a location for a reason.", science_tag: "dual-coding" },
      { name: "Holidays and Places", minutes: 8, body: "Proper nouns beyond names — Thanksgiving, Ohio, Cheerios.", science_tag: "interleaving" },
      { name: "Commas in a Letter", minutes: 8, body: "Dear Grandma, and Love, me. A real letter, actually sent.", science_tag: "collaborative" },
      { name: "Yesterday's Sentences", minutes: 4, body: "Checked cold with the two questions.", science_tag: "spaced" },
    ],
    ef_supports: ["Two-questions card", "Plural-versus-possessive sorting", "Contraction building strips", "Letter template"],
    tech: "Whiteboards and real letters",
    tech_purpose: "A letter with a real recipient makes the commas matter",
    ai_prompts: ["Generate plural and possessive pairs for sorting", "Write sentences with apostrophe errors to correct"],
    assessment: ["Check plurals are apostrophe-free", "Confirm the two questions are used", "Look at proper noun capitals"],
    why_it_works: ["Two yes-or-no questions are small enough for a seven-year-old to apply unaided", "Plural against possessive attacks the error directly rather than around it", "Placing the mark where the letter went explains the position rather than memorizing it", "A real letter gives the comma rules a purpose"],
  },
  {
    standard_code: "L.2.3",
    title: "Who Are You Talking To",
    badge: "Grade 2",
    route_name: "Explicit Instruction",
    route_line: "Name the audience → Hear both versions → Choose to match",
    success_criteria: ["Compares formal and informal", "Names the audience", "Chooses words to suit"],
    steps: [
      { name: "Retrieve Audience", minutes: 4, body: "Who reads or hears this? The question the whole standard rests on.", science_tag: "retrieval" },
      { name: "Same News, Two Ways", minutes: 12, body: "Told to a friend and to the principal. Both correct, and that is the lesson — neither is better.", science_tag: "elaboration" },
      { name: "Say It Before You Write It", minutes: 10, body: "Naming the audience out loud before drafting. The register follows once the reader is real.", science_tag: "metacognition" },
      { name: "Spot the Fillers", minutes: 10, body: "Um, like, and stuff on the page. Speech written down, and why it reads oddly.", science_tag: "elaboration" },
      { name: "Rewrite for the Other One", minutes: 12, body: "The same message, other audience. Register becomes a dial rather than a fact.", science_tag: "interleaving" },
      { name: "Which Was Right Here", minutes: 6, body: "A situation given, a version chosen and justified.", science_tag: "metacognition" },
      { name: "Yesterday's Note", minutes: 4, body: "Reread and re-aimed at a different reader.", science_tag: "spaced" },
    ],
    ef_supports: ["Audience naming routine", "Two-version comparison", "Filler word list", "Situation cards"],
    tech: "Written and spoken examples side by side",
    tech_purpose: "Comparing needs both present at once",
    ai_prompts: ["Write the same message formally and informally", "Generate audience situations for grade 2"],
    assessment: ["Check the audience is named before writing", "Confirm both versions are treated as correct", "Read justifications"],
    why_it_works: ["Naming the reader out loud is the moment register becomes a choice", "Two correct versions stop formal being read as better", "Seeing fillers written down explains why speech and writing differ", "Rewriting for the other audience makes register adjustable"],
  },
  {
    standard_code: "L.2.5",
    title: "From Gentle to Strong",
    badge: "Grade 2",
    route_name: "Explicit Instruction",
    route_line: "Gather close words → Put them on a line → Say when you would use each",
    success_criteria: ["Sorts words into categories", "Orders words by intensity", "Connects words to real use"],
    steps: [
      { name: "Retrieve Synonyms", minutes: 4, body: "Words that mean nearly the same. Nearly is the operative word.", science_tag: "retrieval" },
      { name: "Toss and Hurl", minutes: 10, body: "Both mean throw. Act them out. The difference is felt before it is described — the deck's own example.", science_tag: "dual-coding" },
      { name: "Put Them on a Line", minutes: 14, body: "Gentle at one end, strong at the other. A line forces a decision that a list never does.", science_tag: "dual-coding" },
      { name: "Argue About the Order", minutes: 10, body: "Two children disagree on placement. The argument is the understanding.", science_tag: "collaborative" },
      { name: "When Would You Use It", minutes: 10, body: "A real moment for each word. Real-life connections are in the standard.", science_tag: "elaboration" },
      { name: "Sort Into Categories", minutes: 8, body: "Words grouped by what they belong to.", science_tag: "interleaving" },
      { name: "Yesterday's Line", minutes: 4, body: "A new word added to an existing line.", science_tag: "spaced" },
    ],
    ef_supports: ["Intensity line strips", "Act-it-out routine", "Category sorting mats", "When-would-you-use prompt"],
    tech: "Word cards that can be physically ordered",
    tech_purpose: "The line has to be movable for the argument to happen",
    ai_prompts: ["Generate sets of closely related verbs varying in intensity", "Write adjective sets for ordering"],
    assessment: ["Check words are ordered, not just grouped", "Listen to placement arguments", "Confirm real-use examples"],
    why_it_works: ["Acting out toss and hurl puts the difference in the body first", "A line forces a decision that a list of synonyms never requires", "Disagreement about placement is where the nuance gets articulated", "Naming a real moment ties the word to use rather than to a definition"],
  },
  {
    standard_code: "L.2.6",
    title: "A Word Is Not Yours Until You Use It",
    badge: "Grade 2",
    route_name: "Routine and Practice",
    route_line: "Meet the word → Understand it → Put it in your own sentence",
    success_criteria: ["Understands new words in context", "Uses them in speech and writing", "Uses adjectives and adverbs to describe"],
    steps: [
      { name: "Retrieve Last Week's Words", minutes: 5, body: "Recalled cold, before new ones arrive.", science_tag: "retrieval" },
      { name: "Where Words Come From", minutes: 6, body: "Books, conversations, being read to. The standard names all three.", science_tag: "elaboration" },
      { name: "Knowing Is Not Using", minutes: 10, body: "A word they can define but have never said. Production is the goal, and naming the gap makes it visible.", science_tag: "metacognition" },
      { name: "Your Own Sentence", minutes: 12, body: "Not the book's sentence. A word is not learned until it appears in their own.", science_tag: "elaboration" },
      { name: "Describe With It", minutes: 10, body: "Adjectives and adverbs, which the standard names specifically.", science_tag: "dual-coding" },
      { name: "Word Wall You Must Use", minutes: 8, body: "Two words from the wall required in today's writing.", science_tag: "spaced" },
      { name: "Catch a Classmate", minutes: 4, body: "Notice someone using a wall word in conversation.", science_tag: "collaborative" },
    ],
    ef_supports: ["Word wall with a use requirement", "Own-sentence rule", "Adjective and adverb prompts", "Catch-a-classmate tally"],
    tech: "A visible, drawn-from word wall",
    tech_purpose: "A wall nobody must use is decoration",
    ai_prompts: ["Generate grade 2 vocabulary with usable contexts", "Write sentence prompts requiring specific words"],
    assessment: ["Check sentences are their own, not copied", "Count wall words appearing unprompted", "Listen for new words in speech"],
    why_it_works: ["Requiring their own sentence is the difference between recognition and production", "A mandatory word wall is used; an optional one is wallpaper", "Catching a classmate makes vocabulary something noticed rather than tested", "Recalling last week's words cold prevents the quiet loss of earlier ones"],
  },
];

seedStandardsBatch({
  label: "Batch 10 — grade 2 writing, speaking and language",
  standardsData,
  unpacksData,
  blueprintsData,
});
