// @ts-nocheck
/**
 * Batch 8: high school, grades 9-12.
 *
 * Extends the library past grade 8 for the first time, which is what makes the
 * "K-12" claim on the home page true rather than aspirational.
 *
 * High school codes are shaped differently. ELA uses two-year bands —
 * RL.9-10.1, RI.11-12.6 — and maths abandons grades entirely for conceptual
 * categories: N for number, A for algebra, F for functions, G for geometry,
 * S for statistics. standardGrade() was taught to read both before this ran.
 *
 *   bun run scripts/seed-standards-batch-8.ts
 */
import { seedStandardsBatch } from "./lib/seed-standards-batch";

const standardsData = [
  // ─── ELA, grades 9-10 ───────────────────────────────────────────────────
  {
    code: "RL.9-10.1",
    name: "Cite strong and thorough evidence",
    plain_reading:
      "Cite strong and thorough textual evidence to support analysis of what the text says explicitly as well as inferences drawn from the text.",
    learning_target: "I can choose evidence that carries the weight of my whole argument, not just some of it.",
    skills: ["Textual Evidence", "Analysis", "Inference"],
    science_tags: ["elaboration", "interleaving"],
    match_keys: ["strong and thorough evidence", "cite textual evidence", "analysis", "inference", "high school"],
  },
  {
    code: "RL.9-10.2",
    name: "Trace a theme and summarize objectively",
    plain_reading:
      "Determine a theme or central idea of a text and analyze in detail its development over the course of the text, including how it emerges and is shaped and refined by specific details.",
    learning_target: "I can show where a theme first appears and how the text keeps reshaping it.",
    skills: ["Theme", "Development", "Objective Summary"],
    science_tags: ["elaboration", "dual-coding"],
    match_keys: ["theme", "central idea", "emerges", "shaped and refined", "objective summary"],
  },
  {
    code: "RI.9-10.5",
    name: "Analyze how ideas are built across a text",
    plain_reading:
      "Analyze in detail how an author's ideas or claims are developed and refined by particular sentences, paragraphs, or larger portions of a text.",
    learning_target: "I can explain what a particular passage does for the argument around it.",
    skills: ["Text Structure", "Analysis", "Authorial Craft"],
    science_tags: ["elaboration", "dual-coding"],
    match_keys: ["developed and refined", "structure", "paragraph function", "claims", "analysis"],
  },
  {
    code: "W.9-10.1",
    name: "Write an argument with valid reasoning",
    plain_reading:
      "Write arguments to support claims in an analysis of substantive topics, using valid reasoning and relevant and sufficient evidence, and developing claim and counterclaims fairly.",
    learning_target: "I can argue a position and give the other side a fair hearing.",
    skills: ["Argument Writing", "Counterclaim", "Valid Reasoning"],
    science_tags: ["elaboration", "interleaving"],
    match_keys: ["argument", "counterclaims", "valid reasoning", "sufficient evidence", "high school writing"],
  },
  {
    code: "W.9-10.2",
    name: "Write to explain a complex idea",
    plain_reading:
      "Write informative or explanatory texts to examine and convey complex ideas, concepts and information clearly and accurately through the effective selection, organization and analysis of content.",
    learning_target: "I can explain something complicated without either oversimplifying or losing the reader.",
    skills: ["Informative Writing", "Organization", "Analysis"],
    science_tags: ["elaboration", "spaced"],
    match_keys: ["informative writing", "explanatory", "complex ideas", "selection", "organization"],
  },
  {
    code: "SL.9-10.1",
    name: "Take part in a rigorous discussion",
    plain_reading:
      "Initiate and participate effectively in a range of collaborative discussions with diverse partners on grades 9-10 topics, texts and issues, building on others' ideas and expressing their own clearly and persuasively.",
    learning_target: "I can start a discussion, not just answer in one, and take it somewhere.",
    skills: ["Discussion", "Initiating", "Persuasion"],
    science_tags: ["collaborative", "elaboration"],
    match_keys: ["collaborative discussion", "initiate", "seminar", "persuasively", "high school speaking"],
  },
  {
    code: "L.9-10.4",
    name: "Work out demanding vocabulary",
    plain_reading:
      "Determine or clarify the meaning of unknown and multiple-meaning words and phrases based on grades 9-10 reading and content, choosing flexibly from a range of strategies and verifying the inferred meaning.",
    learning_target: "I can work out a difficult word from context and word parts, then check I was right.",
    skills: ["Vocabulary", "Morphology", "Verification"],
    science_tags: ["elaboration", "interleaving"],
    match_keys: ["context clues", "word parts", "etymology", "verify meaning", "high school vocabulary"],
  },

  // ─── ELA, grades 11-12 ──────────────────────────────────────────────────
  {
    code: "RL.11-12.3",
    name: "Analyze an author's choices about structure",
    plain_reading:
      "Analyze the impact of an author's choices regarding how to develop and relate elements of a story or drama, including where a story is set, how the action is ordered, and how the characters are introduced and developed.",
    learning_target: "I can explain why the author told it in this order rather than another.",
    skills: ["Authorial Craft", "Structure", "Characterization"],
    science_tags: ["elaboration", "dual-coding"],
    match_keys: ["author's choices", "how the action is ordered", "narrative structure", "characterization"],
  },
  {
    code: "RI.11-12.6",
    name: "Analyze rhetoric and point of view",
    plain_reading:
      "Determine an author's point of view or purpose in a text in which the rhetoric is particularly effective, analyzing how style and content contribute to the power, persuasiveness or beauty of the text.",
    learning_target: "I can explain how a piece of writing persuades, not just what it says.",
    skills: ["Rhetoric", "Point of View", "Style"],
    science_tags: ["elaboration", "interleaving"],
    match_keys: ["rhetoric", "point of view", "persuasiveness", "style", "ethos pathos logos"],
  },
  {
    code: "W.11-12.1",
    name: "Write an argument that anticipates objections",
    plain_reading:
      "Write arguments to support claims using valid reasoning and relevant, sufficient evidence, establishing the significance of the claim and anticipating the audience's knowledge level, concerns and possible biases.",
    learning_target: "I can argue to a particular audience and answer what they will object to.",
    skills: ["Argument Writing", "Audience Awareness", "Counterclaim"],
    science_tags: ["elaboration", "interleaving"],
    match_keys: ["argument", "significance of the claim", "audience", "biases", "counterclaims"],
  },

  // ─── Mathematics, high school ───────────────────────────────────────────
  {
    code: "N-RN.2",
    name: "Rewrite expressions with rational exponents",
    plain_reading:
      "Rewrite expressions involving radicals and rational exponents using the properties of exponents.",
    learning_target: "I can move between a root and a fractional exponent, whichever is easier to work with.",
    skills: ["Rational Exponents", "Radicals", "Exponent Properties"],
    science_tags: ["elaboration", "interleaving"],
    match_keys: ["rational exponents", "radicals", "square root", "fractional exponent", "properties of exponents"],
  },
  {
    code: "A-SSE.1",
    name: "Read the structure of an expression",
    plain_reading:
      "Interpret expressions that represent a quantity in terms of its context, identifying the parts of an expression and interpreting complicated expressions by viewing one or more of their parts as a single entity.",
    learning_target: "I can look at an expression and say what each part is doing.",
    skills: ["Expression Structure", "Interpretation", "Modeling"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["interpret expressions", "structure", "terms factors coefficients", "chunking", "in context"],
  },
  {
    code: "A-CED.1",
    name: "Create equations from a situation",
    plain_reading:
      "Create equations and inequalities in one variable and use them to solve problems, including equations arising from linear and quadratic functions and simple rational and exponential functions.",
    learning_target: "I can turn a real situation into an equation and solve it.",
    skills: ["Modeling", "Equations", "Inequalities"],
    science_tags: ["elaboration", "interleaving"],
    match_keys: ["create equations", "modeling", "inequalities", "one variable", "word problems"],
  },
  {
    code: "A-REI.4",
    name: "Solve quadratic equations",
    plain_reading:
      "Solve quadratic equations in one variable by inspection, taking square roots, completing the square, factoring and the quadratic formula, recognizing when a solution is not real.",
    learning_target: "I can pick the quickest way to solve a quadratic rather than always using the formula.",
    skills: ["Quadratics", "Factoring", "Completing the Square"],
    science_tags: ["interleaving", "elaboration"],
    match_keys: ["quadratic equations", "quadratic formula", "factoring", "completing the square", "discriminant"],
  },
  {
    code: "F-IF.4",
    name: "Read the key features of a graph",
    plain_reading:
      "For a function that models a relationship between two quantities, interpret key features of graphs and tables in terms of the quantities, including intercepts, intervals of increase and decrease, maxima and minima, and end behavior.",
    learning_target: "I can describe what a graph is telling me about the real situation behind it.",
    skills: ["Graph Interpretation", "Key Features", "Modeling"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["key features", "intercepts", "increasing decreasing", "maximum minimum", "end behavior"],
  },
  {
    code: "F-BF.1",
    name: "Build a function to model a situation",
    plain_reading:
      "Write a function that describes a relationship between two quantities, determining an explicit expression or a recursive process from a context.",
    learning_target: "I can build the rule for a situation, not just use one I was given.",
    skills: ["Function Building", "Modeling", "Recursion"],
    science_tags: ["elaboration", "interleaving"],
    match_keys: ["build a function", "explicit expression", "recursive", "model a relationship", "combine functions"],
  },
  {
    code: "F-LE.2",
    name: "Tell linear growth from exponential",
    plain_reading:
      "Construct linear and exponential functions, including arithmetic and geometric sequences, given a graph, a description of a relationship, or two input-output pairs.",
    learning_target: "I can tell whether something grows by adding or by multiplying, and write the rule.",
    skills: ["Linear Functions", "Exponential Functions", "Sequences"],
    science_tags: ["interleaving", "dual-coding"],
    match_keys: ["linear vs exponential", "geometric sequence", "arithmetic sequence", "growth", "construct functions"],
  },
  {
    code: "G-SRT.8",
    name: "Solve right triangles with trigonometry",
    plain_reading:
      "Use trigonometric ratios and the Pythagorean Theorem to solve right triangles in applied problems.",
    learning_target: "I can find a missing side or angle in a right triangle and know which ratio to use.",
    skills: ["Trigonometry", "Right Triangles", "Applied Problems"],
    science_tags: ["retrieval", "interleaving"],
    match_keys: ["sine cosine tangent", "SOHCAHTOA", "right triangles", "pythagorean theorem", "angle of elevation"],
  },
  {
    code: "S-ID.6",
    name: "Fit a function to data",
    plain_reading:
      "Represent data on two quantitative variables on a scatter plot, and describe how the variables are related, fitting a function to the data and using it to solve problems.",
    learning_target: "I can fit a line to real data and use it to make a prediction, knowing what it cannot tell me.",
    skills: ["Scatter Plots", "Line of Best Fit", "Residuals"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["scatter plot", "line of best fit", "regression", "correlation", "residuals", "prediction"],
  },
];

const unpacksData = [
  {
    standard_code: "RL.9-10.1",
    verbs: [
      { word: "Cite", gloss: "quote and locate the evidence" },
      { word: "Support", gloss: "make the evidence carry the analysis" },
      { word: "Infer", gloss: "reason to what the text implies" },
    ],
    concepts: ["Strength of evidence", "Sufficiency", "Explicit and inferential"],
    vocabulary: [
      { term: "thorough", definition: "covering the whole claim, not just part of it" },
      { term: "strong evidence", definition: "the quote that proves the point most directly" },
      { term: "explicitly", definition: "stated outright in the text" },
      { term: "inference", definition: "a conclusion the text supports without stating" },
    ],
    prior_skills: ["Cite textual evidence", "Draw inferences", "Distinguish claim from evidence"],
    prior_standards: [{ code: "RI.8.1", text: "Cite the evidence that most strongly supports an analysis" }],
    future_standards: [{ code: "RL.11-12.1", text: "Cite evidence, including where the text leaves matters uncertain" }],
    challenges: [
      { problem: "One quote is offered for a claim needing several", fix: "Ask which part of the claim is still unevidenced" },
      { problem: "Evidence is thorough but weak", fix: "Rank candidates by directness before choosing" },
    ],
    mastery_statement: "Student can select evidence that is both strong and sufficient for the whole claim being made.",
    ladder: [
      { name: "I can find relevant evidence", descriptor: "Locates supporting text" },
      { name: "I can pick the strongest", descriptor: "Compares candidates" },
      { name: "I can cover the whole claim", descriptor: "Judges sufficiency" },
      { name: "I can support an inference too", descriptor: "Handles implied meaning" },
    ],
  },
  {
    standard_code: "RL.9-10.2",
    verbs: [
      { word: "Determine", gloss: "identify the theme" },
      { word: "Analyze", gloss: "examine how it is built up" },
      { word: "Refine", gloss: "track how the text sharpens it" },
    ],
    concepts: ["Emergence", "Shaping and refining", "Objective summary"],
    vocabulary: [
      { term: "emerge", definition: "become visible for the first time" },
      { term: "refine", definition: "make more precise as the text goes on" },
      { term: "theme", definition: "a claim the work makes about life" },
      { term: "objective", definition: "reported without your own judgment" },
    ],
    prior_skills: ["State a theme as a claim", "Trace development", "Write an objective summary"],
    prior_standards: [{ code: "RL.7.2", text: "Determine a theme and analyze its development" }],
    future_standards: [{ code: "RL.11-12.2", text: "Analyze two or more themes and their interaction" }],
    challenges: [
      { problem: "Theme is treated as fixed from the first page", fix: "Compare its first and last appearance and name the difference" },
      { problem: "Development is described as repetition", fix: "Require what changed, not that it recurred" },
    ],
    mastery_statement: "Student can trace where a theme emerges and how the text shapes and refines it.",
    ladder: [
      { name: "I can state a theme", descriptor: "Writes it as a claim" },
      { name: "I can find where it emerges", descriptor: "Locates the first appearance" },
      { name: "I can show how it is refined", descriptor: "Cites shaping moments" },
      { name: "I can summarize objectively", descriptor: "Excludes judgment" },
    ],
  },
  {
    standard_code: "RI.9-10.5",
    verbs: [
      { word: "Analyze", gloss: "work out what a passage is doing" },
      { word: "Develop", gloss: "build a claim out" },
      { word: "Refine", gloss: "narrow or qualify a claim" },
    ],
    concepts: ["Passage function", "Development versus refinement", "Argument architecture"],
    vocabulary: [
      { term: "refine", definition: "make a claim more precise" },
      { term: "qualify", definition: "limit a claim so it holds up" },
      { term: "portion", definition: "a stretch of text larger than a paragraph" },
      { term: "architecture", definition: "how the parts of an argument are arranged" },
    ],
    prior_skills: ["Analyze paragraph structure", "Identify claims", "Trace an argument"],
    prior_standards: [{ code: "RI.8.5", text: "Analyze the structure of a specific paragraph" }],
    future_standards: [{ code: "RI.11-12.5", text: "Analyze and evaluate the effectiveness of a text's structure" }],
    challenges: [
      { problem: "The passage is summarized rather than analyzed", fix: "Ban content words — describe the job only" },
      { problem: "Develop and refine are used interchangeably", fix: "Sort passages by which they do" },
    ],
    mastery_statement: "Student can explain how a specific passage develops or refines the author's claim.",
    ladder: [
      { name: "I can find the claim", descriptor: "Identifies the position" },
      { name: "I can say what a passage does", descriptor: "Names its function" },
      { name: "I can tell develop from refine", descriptor: "Distinguishes the moves" },
      { name: "I can map the whole argument", descriptor: "Explains the architecture" },
    ],
  },
  {
    standard_code: "W.9-10.1",
    verbs: [
      { word: "Support", gloss: "back the claim with evidence" },
      { word: "Develop", gloss: "build claim and counterclaim out" },
      { word: "Reason", gloss: "connect evidence to claim validly" },
    ],
    concepts: ["Valid reasoning", "Sufficiency", "Fair counterclaim"],
    vocabulary: [
      { term: "valid reasoning", definition: "logic that actually gets you from evidence to claim" },
      { term: "sufficient", definition: "enough to carry the claim, not just some support" },
      { term: "counterclaim", definition: "the strongest case against your position" },
      { term: "substantive", definition: "about something that genuinely matters" },
    ],
    prior_skills: ["Write arguments with counterclaims", "Evaluate evidence", "Organize reasons"],
    prior_standards: [{ code: "W.8.1", text: "Write arguments acknowledging and answering counterclaims" }],
    future_standards: [{ code: "W.11-12.1", text: "Write arguments anticipating audience concerns and biases" }],
    challenges: [
      { problem: "Evidence piles up without reasoning between it", fix: "Require a sentence linking each piece to the claim" },
      { problem: "The counterclaim is the weakest version", fix: "Steelman it — write the version its holders would recognize" },
    ],
    mastery_statement: "Student can argue a claim with valid reasoning and sufficient evidence, developing both sides fairly.",
    ladder: [
      { name: "I can state an arguable claim", descriptor: "Writes a defensible position" },
      { name: "I can support it with evidence", descriptor: "Supplies relevant support" },
      { name: "I can reason from it", descriptor: "Links evidence to claim" },
      { name: "I can develop the other side fairly", descriptor: "Steelmans the counterclaim" },
    ],
  },
  {
    standard_code: "W.9-10.2",
    verbs: [
      { word: "Examine", gloss: "look closely at a complex idea" },
      { word: "Convey", gloss: "get it across clearly" },
      { word: "Select", gloss: "choose what is worth including" },
    ],
    concepts: ["Complexity", "Selection", "Accuracy"],
    vocabulary: [
      { term: "complex", definition: "having parts that interact, not merely difficult" },
      { term: "accurate", definition: "true to the source, not approximately right" },
      { term: "cohesion", definition: "the sense that the parts belong together" },
      { term: "concept", definition: "an idea the topic depends on" },
    ],
    prior_skills: ["Write informative texts", "Select relevant content", "Use transitions"],
    prior_standards: [{ code: "W.8.2", text: "Write informative texts through selection and analysis of content" }],
    future_standards: [{ code: "W.11-12.2", text: "Write informative texts examining complex ideas thoroughly" }],
    challenges: [
      { problem: "Complexity is flattened into a simple summary", fix: "Require the tension or trade-off to appear" },
      { problem: "Everything researched is included", fix: "Force a cut against the focus question" },
    ],
    mastery_statement: "Student can explain a complex idea accurately, selecting and organizing content that carries it.",
    ladder: [
      { name: "I can explain a simple topic", descriptor: "Conveys information clearly" },
      { name: "I can select what matters", descriptor: "Cuts the irrelevant" },
      { name: "I can keep the complexity", descriptor: "Preserves tensions" },
      { name: "I can organize it cohesively", descriptor: "Parts connect" },
    ],
  },
  {
    standard_code: "SL.9-10.1",
    verbs: [
      { word: "Initiate", gloss: "start a line of discussion" },
      { word: "Participate", gloss: "take a real part in it" },
      { word: "Express", gloss: "make your view clear and persuasive" },
    ],
    concepts: ["Initiating", "Persuasion", "Collaborative norms"],
    vocabulary: [
      { term: "initiate", definition: "open a line of thinking rather than answer one" },
      { term: "persuasive", definition: "likely to move someone's position" },
      { term: "diverse partners", definition: "people who do not already agree with you" },
      { term: "consensus", definition: "agreement the group can live with" },
    ],
    prior_skills: ["Pose questions that elicit elaboration", "Qualify a view", "Come prepared with evidence"],
    prior_standards: [{ code: "SL.8.1", text: "Pose questions that connect ideas and qualify views" }],
    future_standards: [{ code: "SL.11-12.1", text: "Initiate and participate in discussions, propelling conversations" }],
    challenges: [
      { problem: "Everyone answers and nobody starts", fix: "Assign initiating turns explicitly" },
      { problem: "Persuasive is read as forceful", fix: "Credit the contribution that changed somebody's mind" },
    ],
    mastery_statement: "Student can initiate a line of discussion and express a position persuasively with evidence.",
    ladder: [
      { name: "I can contribute", descriptor: "Participates with evidence" },
      { name: "I can build on others", descriptor: "Extends rather than restarts" },
      { name: "I can start a new line", descriptor: "Initiates" },
      { name: "I can move the group", descriptor: "Persuades or is persuaded" },
    ],
  },
  {
    standard_code: "L.9-10.4",
    verbs: [
      { word: "Determine", gloss: "work out the meaning" },
      { word: "Verify", gloss: "check it against a reference" },
    ],
    concepts: ["Context", "Etymology", "Verification"],
    vocabulary: [
      { term: "etymology", definition: "where a word came from and how it changed" },
      { term: "denotation", definition: "the plain dictionary meaning" },
      { term: "connotation", definition: "the feeling the word carries" },
      { term: "inferred", definition: "worked out from clues rather than told" },
    ],
    prior_skills: ["Use context and word parts", "Choose the fitting dictionary sense", "Recognize connotation"],
    prior_standards: [{ code: "L.7.4", text: "Determine meanings and verify the inferred meaning" }],
    future_standards: [{ code: "L.11-12.4", text: "Determine meanings using grades 11-12 strategies" }],
    challenges: [
      { problem: "The dictionary is the first move", fix: "Require a context guess before looking it up" },
      { problem: "Roughly right is accepted", fix: "Record the gap between guess and definition" },
    ],
    mastery_statement: "Student can infer a demanding word's meaning from context and word parts, then verify it.",
    ladder: [
      { name: "I can guess from context", descriptor: "Proposes a meaning" },
      { name: "I can use word parts", descriptor: "Breaks the word down" },
      { name: "I can verify it", descriptor: "Checks a reference" },
      { name: "I can sharpen my guess", descriptor: "Notes and closes the gap" },
    ],
  },
  {
    standard_code: "RL.11-12.3",
    verbs: [
      { word: "Analyze", gloss: "examine the effect of a choice" },
      { word: "Relate", gloss: "show how elements act on each other" },
    ],
    concepts: ["Authorial choice", "Ordering of action", "Character introduction"],
    vocabulary: [
      { term: "in medias res", definition: "beginning in the middle of the action" },
      { term: "pacing", definition: "how fast the story moves through time" },
      { term: "frame", definition: "a story told inside another story" },
      { term: "juxtaposition", definition: "placing two things together so each comments on the other" },
    ],
    prior_skills: ["Analyze how story elements interact", "Track character development", "Cite evidence"],
    prior_standards: [{ code: "RL.7.3", text: "Analyze how story elements interact" }],
    future_standards: [{ code: "RL.11-12.5", text: "Analyze how structural choices contribute to meaning" }],
    challenges: [
      { problem: "Choices are described but not evaluated", fix: "Ask what would be lost if it were told in order" },
      { problem: "Structure is treated as arbitrary", fix: "Reorder a scene and compare the effect" },
    ],
    mastery_statement: "Student can analyze how an author's structural choices shape the story's effect.",
    ladder: [
      { name: "I can describe the structure", descriptor: "Identifies the ordering" },
      { name: "I can name the choice", descriptor: "Sees it as deliberate" },
      { name: "I can explain its effect", descriptor: "Links choice to impact" },
      { name: "I can test it by changing it", descriptor: "Reasons counterfactually" },
    ],
  },
  {
    standard_code: "RI.11-12.6",
    verbs: [
      { word: "Determine", gloss: "identify the purpose" },
      { word: "Analyze", gloss: "examine how style creates effect" },
    ],
    concepts: ["Rhetoric", "Style and content", "Persuasive effect"],
    vocabulary: [
      { term: "rhetoric", definition: "the craft of persuasion" },
      { term: "ethos", definition: "persuading through credibility" },
      { term: "pathos", definition: "persuading through feeling" },
      { term: "logos", definition: "persuading through reasoning" },
    ],
    prior_skills: ["Determine author's point of view", "Evaluate an argument", "Analyze word choice"],
    prior_standards: [{ code: "RI.7.6", text: "Determine an author's point of view and how it is distinguished" }],
    future_standards: [{ code: "RI.11-12.9", text: "Analyze foundational documents for their themes and rhetoric" }],
    challenges: [
      { problem: "The text is summarized instead of analyzed", fix: "Ban content words — describe the technique" },
      { problem: "Effective is confused with agreeable", fix: "Analyze a persuasive text the class disagrees with" },
    ],
    mastery_statement: "Student can analyze how style and content combine to make a text persuasive.",
    ladder: [
      { name: "I can state the purpose", descriptor: "Identifies the aim" },
      { name: "I can spot a technique", descriptor: "Names a rhetorical move" },
      { name: "I can explain its effect", descriptor: "Links technique to impact" },
      { name: "I can judge effectiveness apart from agreement", descriptor: "Separates craft from opinion" },
    ],
  },
  {
    standard_code: "W.11-12.1",
    verbs: [
      { word: "Establish", gloss: "show why the claim matters" },
      { word: "Anticipate", gloss: "answer objections before they are raised" },
    ],
    concepts: ["Significance", "Audience", "Bias"],
    vocabulary: [
      { term: "significance", definition: "why this claim is worth making at all" },
      { term: "anticipate", definition: "answer an objection before it is voiced" },
      { term: "bias", definition: "a leaning that shapes how something is received" },
      { term: "concession", definition: "granting a point without giving up the argument" },
    ],
    prior_skills: ["Write arguments with counterclaims", "Assess evidence", "Organize logically"],
    prior_standards: [{ code: "W.9-10.1", text: "Write arguments with valid reasoning and sufficient evidence" }],
    future_standards: [{ code: "W.11-12.1e", text: "Provide a concluding statement that follows from the argument" }],
    challenges: [
      { problem: "The argument addresses nobody in particular", fix: "Name the audience before drafting" },
      { problem: "Objections are answered only after they land", fix: "List three likely objections first" },
    ],
    mastery_statement: "Student can argue to a specific audience, establishing significance and anticipating objections.",
    ladder: [
      { name: "I can argue a claim", descriptor: "Supports with evidence" },
      { name: "I can say why it matters", descriptor: "Establishes significance" },
      { name: "I can name my audience", descriptor: "Writes for someone specific" },
      { name: "I can answer them in advance", descriptor: "Anticipates objections" },
    ],
  },
  {
    standard_code: "N-RN.2",
    verbs: [
      { word: "Rewrite", gloss: "express it in the other form" },
      { word: "Apply", gloss: "use the exponent properties" },
    ],
    concepts: ["Rational exponents", "Radicals", "Equivalence"],
    vocabulary: [
      { term: "radical", definition: "a root, written with the root sign" },
      { term: "rational exponent", definition: "a fractional power, like the one-half that means square root" },
      { term: "index", definition: "which root is being taken" },
      { term: "equivalent", definition: "different in form, identical in value" },
    ],
    prior_skills: ["Apply integer exponent properties", "Simplify radicals", "Work with fractions"],
    prior_standards: [{ code: "8.EE.A.1", text: "Know and apply the properties of integer exponents" }],
    future_standards: [{ code: "A-SSE.3", text: "Produce equivalent forms to reveal properties" }],
    challenges: [
      { problem: "The fractional exponent is treated as multiplication", fix: "Check with a numerical case — 9 to the one-half is 3" },
      { problem: "Numerator and denominator roles are swapped", fix: "Say it aloud: the bottom is the root, the top is the power" },
    ],
    mastery_statement: "Student can convert between radicals and rational exponents and justify the equivalence.",
    ladder: [
      { name: "I can apply integer exponent rules", descriptor: "Uses the properties" },
      { name: "I can read a fractional exponent", descriptor: "Names root and power" },
      { name: "I can convert both ways", descriptor: "Radical to exponent and back" },
      { name: "I can simplify with them", descriptor: "Combines the properties" },
    ],
  },
  {
    standard_code: "A-SSE.1",
    verbs: [
      { word: "Interpret", gloss: "say what the expression means here" },
      { word: "Identify", gloss: "name the parts" },
      { word: "View", gloss: "treat a chunk as a single thing" },
    ],
    concepts: ["Terms and factors", "Chunking", "Interpretation in context"],
    vocabulary: [
      { term: "term", definition: "a piece separated by plus or minus" },
      { term: "factor", definition: "a piece being multiplied" },
      { term: "coefficient", definition: "the number multiplying a variable" },
      { term: "chunk", definition: "a group of symbols treated as one entity" },
    ],
    prior_skills: ["Write and evaluate expressions", "Expand and factor", "Model with equations"],
    prior_standards: [{ code: "7.EE.A.1", text: "Add, subtract, factor and expand linear expressions" }],
    future_standards: [{ code: "A-SSE.3", text: "Produce equivalent forms to reveal properties of a quantity" }],
    challenges: [
      { problem: "Expressions are computed rather than read", fix: "Ask what a part means before anything is simplified" },
      { problem: "Chunking is not attempted", fix: "Substitute a single letter for a repeated group" },
    ],
    mastery_statement: "Student can interpret the parts of an expression in context, including treating a group as one entity.",
    ladder: [
      { name: "I can name terms and factors", descriptor: "Identifies the parts" },
      { name: "I can say what a part means", descriptor: "Interprets in context" },
      { name: "I can treat a group as one", descriptor: "Chunks an expression" },
      { name: "I can read a complicated expression", descriptor: "Interprets the whole structure" },
    ],
  },
  {
    standard_code: "A-CED.1",
    verbs: [
      { word: "Create", gloss: "build the equation from the situation" },
      { word: "Use", gloss: "solve the problem with it" },
    ],
    concepts: ["Modeling", "Variables", "Inequalities"],
    vocabulary: [
      { term: "model", definition: "an equation standing in for a real situation" },
      { term: "constraint", definition: "a limit the situation puts on the answer" },
      { term: "inequality", definition: "a statement that one side is larger or smaller" },
      { term: "variable", definition: "a letter standing for a quantity" },
    ],
    prior_skills: ["Construct and solve equations", "Work with inequalities", "Interpret in context"],
    prior_standards: [{ code: "7.EE.B.4", text: "Construct simple equations and inequalities to solve problems" }],
    future_standards: [{ code: "A-REI.11", text: "Explain why the intersection of two graphs solves an equation" }],
    challenges: [
      { problem: "The variable is never defined", fix: "Write 'let x = ' with units before anything else" },
      { problem: "Constraints are dropped", fix: "List what the situation forbids before solving" },
    ],
    mastery_statement: "Student can create an equation or inequality modeling a situation and use it to solve the problem.",
    ladder: [
      { name: "I can define the variable", descriptor: "Names it with units" },
      { name: "I can write the equation", descriptor: "Matches structure to situation" },
      { name: "I can solve it", descriptor: "Finds the solution" },
      { name: "I can check it against the constraints", descriptor: "Interprets in context" },
    ],
  },
  {
    standard_code: "A-REI.4",
    verbs: [
      { word: "Solve", gloss: "find the values that satisfy it" },
      { word: "Recognize", gloss: "see when no real solution exists" },
    ],
    concepts: ["Multiple methods", "Completing the square", "Discriminant"],
    vocabulary: [
      { term: "quadratic", definition: "an equation with a squared term as its highest power" },
      { term: "discriminant", definition: "the part under the root that tells you how many solutions" },
      { term: "root", definition: "a value that makes the equation true" },
      { term: "complete the square", definition: "rewrite so one side is a perfect square" },
    ],
    prior_skills: ["Solve linear equations", "Factor expressions", "Work with radicals"],
    prior_standards: [{ code: "8.EE.C.7", text: "Solve linear equations in one variable" }],
    future_standards: [{ code: "F-IF.8", text: "Use the process of factoring and completing the square" }],
    challenges: [
      { problem: "The formula is used for everything", fix: "Time factoring against the formula on an easy case" },
      { problem: "A negative discriminant is read as an error", fix: "Name it as no real solution, and say what that means graphically" },
    ],
    mastery_statement: "Student can solve a quadratic by a method suited to it, and interpret a negative discriminant.",
    ladder: [
      { name: "I can solve by taking roots", descriptor: "Handles the simplest form" },
      { name: "I can factor", descriptor: "Solves factorable quadratics" },
      { name: "I can complete the square", descriptor: "Handles any quadratic" },
      { name: "I can choose the quickest method", descriptor: "Selects deliberately" },
    ],
  },
  {
    standard_code: "F-IF.4",
    verbs: [
      { word: "Interpret", gloss: "say what a graph feature means" },
      { word: "Sketch", gloss: "draw a graph showing the features" },
    ],
    concepts: ["Intercepts", "Intervals of increase", "End behavior"],
    vocabulary: [
      { term: "intercept", definition: "where a graph crosses an axis" },
      { term: "maximum", definition: "the highest value the function reaches" },
      { term: "end behavior", definition: "what the graph does far out to the left and right" },
      { term: "interval", definition: "a stretch of inputs" },
    ],
    prior_skills: ["Understand functions", "Graph linear relationships", "Read scatter plots"],
    prior_standards: [{ code: "8.F.B.4", text: "Construct a function to model a linear relationship" }],
    future_standards: [{ code: "F-IF.7", text: "Graph functions and show key features" }],
    challenges: [
      { problem: "Features are named without units or meaning", fix: "Require the sentence to mention the real quantity" },
      { problem: "The graph is read as a picture of the situation", fix: "Ask what the axes actually measure" },
    ],
    mastery_statement: "Student can interpret the key features of a graph in terms of the quantities it models.",
    ladder: [
      { name: "I can read values off a graph", descriptor: "Locates points" },
      { name: "I can find intercepts and extremes", descriptor: "Identifies features" },
      { name: "I can describe intervals", descriptor: "Says where it rises and falls" },
      { name: "I can say what it means in context", descriptor: "Interprets with units" },
    ],
  },
  {
    standard_code: "F-BF.1",
    verbs: [
      { word: "Write", gloss: "produce the function" },
      { word: "Determine", gloss: "work out the rule from the context" },
    ],
    concepts: ["Explicit rules", "Recursive rules", "Combining functions"],
    vocabulary: [
      { term: "explicit", definition: "a rule that gives any term directly" },
      { term: "recursive", definition: "a rule that builds each term from the one before" },
      { term: "parameter", definition: "a number in the rule that sets its behavior" },
      { term: "compose", definition: "feed one function's output into another" },
    ],
    prior_skills: ["Construct linear functions", "Understand function notation", "Model relationships"],
    prior_standards: [{ code: "8.F.B.4", text: "Construct a function to model a linear relationship" }],
    future_standards: [{ code: "F-BF.3", text: "Identify the effect of transformations on a graph" }],
    challenges: [
      { problem: "A recursive rule is given where an explicit one is needed", fix: "Ask for the hundredth term and watch the method break" },
      { problem: "The rule is fitted to two points and never checked", fix: "Test it against a third" },
    ],
    mastery_statement: "Student can build a function modeling a situation, explicitly or recursively as the context requires.",
    ladder: [
      { name: "I can extend a pattern", descriptor: "Finds the next term" },
      { name: "I can write a recursive rule", descriptor: "Builds from the previous term" },
      { name: "I can write an explicit rule", descriptor: "Gives any term directly" },
      { name: "I can check it against the context", descriptor: "Validates the model" },
    ],
  },
  {
    standard_code: "F-LE.2",
    verbs: [
      { word: "Construct", gloss: "build the function" },
      { word: "Distinguish", gloss: "tell the two growth types apart" },
    ],
    concepts: ["Constant difference", "Constant ratio", "Sequences"],
    vocabulary: [
      { term: "arithmetic sequence", definition: "one that grows by adding the same amount" },
      { term: "geometric sequence", definition: "one that grows by multiplying by the same amount" },
      { term: "common difference", definition: "what is added each step" },
      { term: "common ratio", definition: "what is multiplied each step" },
    ],
    prior_skills: ["Construct linear functions", "Apply exponent properties", "Read tables and graphs"],
    prior_standards: [{ code: "8.F.B.4", text: "Construct a function to model a linear relationship" }],
    future_standards: [{ code: "F-LE.3", text: "Observe that exponential growth eventually exceeds polynomial" }],
    challenges: [
      { problem: "Any increasing pattern is called exponential", fix: "Test both differences and ratios before deciding" },
      { problem: "Early terms mislead", fix: "Extend the table far enough for the two to separate" },
    ],
    mastery_statement: "Student can tell linear from exponential growth by testing differences and ratios, and write the rule.",
    ladder: [
      { name: "I can find a common difference", descriptor: "Tests for arithmetic" },
      { name: "I can find a common ratio", descriptor: "Tests for geometric" },
      { name: "I can decide which it is", descriptor: "Applies both tests" },
      { name: "I can write the function", descriptor: "Produces the rule" },
    ],
  },
  {
    standard_code: "G-SRT.8",
    verbs: [
      { word: "Use", gloss: "apply the ratio or the theorem" },
      { word: "Solve", gloss: "find the missing side or angle" },
    ],
    concepts: ["Trigonometric ratios", "Right triangles", "Applied problems"],
    vocabulary: [
      { term: "sine", definition: "opposite over hypotenuse" },
      { term: "cosine", definition: "adjacent over hypotenuse" },
      { term: "tangent", definition: "opposite over adjacent" },
      { term: "angle of elevation", definition: "the angle up from horizontal to a line of sight" },
    ],
    prior_skills: ["Apply the Pythagorean Theorem", "Work with similar triangles", "Solve equations"],
    prior_standards: [{ code: "8.G.B.7", text: "Apply the Pythagorean Theorem to find unknown side lengths" }],
    future_standards: [{ code: "G-SRT.11", text: "Use the Law of Sines and Cosines to solve any triangle" }],
    challenges: [
      { problem: "Opposite and adjacent are read from the triangle, not the angle", fix: "Mark the angle first, then label from it" },
      { problem: "The Pythagorean Theorem is used where an angle is needed", fix: "Ask what is known before choosing a tool" },
    ],
    mastery_statement: "Student can solve right triangles using trigonometric ratios and the Pythagorean Theorem in context.",
    ladder: [
      { name: "I can find a missing side with Pythagoras", descriptor: "Applies the theorem" },
      { name: "I can label opposite and adjacent", descriptor: "Labels relative to the angle" },
      { name: "I can choose the right ratio", descriptor: "Selects sine, cosine or tangent" },
      { name: "I can solve an applied problem", descriptor: "Models and solves" },
    ],
  },
  {
    standard_code: "S-ID.6",
    verbs: [
      { word: "Represent", gloss: "plot the two variables" },
      { word: "Fit", gloss: "find a function matching the trend" },
      { word: "Describe", gloss: "say how the variables relate" },
    ],
    concepts: ["Line of best fit", "Residuals", "Prediction and its limits"],
    vocabulary: [
      { term: "line of best fit", definition: "the line that comes closest to all the points" },
      { term: "residual", definition: "how far a point sits from the fitted line" },
      { term: "extrapolate", definition: "predict beyond the data you actually have" },
      { term: "correlation", definition: "how closely two variables move together" },
    ],
    prior_skills: ["Construct and read scatter plots", "Find slope", "Write linear functions"],
    prior_standards: [{ code: "8.SP.A.1", text: "Construct and interpret scatter plots for bivariate data" }],
    future_standards: [{ code: "S-ID.7", text: "Interpret the slope and intercept of a linear model in context" }],
    challenges: [
      { problem: "A line is fitted to data with no linear trend", fix: "Look at the residual plot before fitting anything" },
      { problem: "Predictions run far beyond the data", fix: "Ask what the model says about a value nobody measured" },
    ],
    mastery_statement: "Student can fit a function to bivariate data, use it to predict, and say where the prediction stops being trustworthy.",
    ladder: [
      { name: "I can plot the data", descriptor: "Constructs a scatter plot" },
      { name: "I can describe the relationship", descriptor: "Names direction and strength" },
      { name: "I can fit a line", descriptor: "Produces a model" },
      { name: "I can say what it cannot tell me", descriptor: "Recognizes the limits" },
    ],
  },
];

const blueprintsData = [
  {
    standard_code: "RL.9-10.1",
    title: "Evidence That Carries the Whole Claim",
    badge: "Grades 9-10",
    route_name: "Analytical Reading",
    route_line: "Make the claim → Test each quote → Check nothing is left unevidenced",
    success_criteria: ["Selects the most direct evidence available", "Covers every part of the claim", "Supports an inference as well as a stated point"],
    steps: [
      { name: "Retrieve Citing", minutes: 5, body: "One claim, one quote. The base skill before strength and sufficiency are added.", science_tag: "retrieval" },
      { name: "Strong Is Not Thorough", minutes: 10, body: "A claim with two parts and one excellent quote covering only the first. Students name what is missing. The two words in the standard mean different things.", science_tag: "elaboration" },
      { name: "Rank for Strength", minutes: 12, body: "Three candidate quotes for one claim. Rank them by directness and specificity, and justify the order.", science_tag: "elaboration" },
      { name: "Audit for Sufficiency", minutes: 12, body: "Underline each part of the claim, then tick the parts the evidence reaches. Untickable parts are the work still to do.", science_tag: "dual-coding" },
      { name: "Evidence for an Inference", minutes: 10, body: "The quote is the clue, not the conclusion. Model the reasoning that bridges the gap.", science_tag: "elaboration" },
      { name: "Write It Up", minutes: 8, body: "Claim, evidence, reasoning — with an explicit note on which part of the claim each quote covers.", science_tag: "interleaving" },
      { name: "Challenge a Selection", minutes: 3, body: "A partner names a part of the claim they think is unevidenced.", science_tag: "spaced" },
    ],
    ef_supports: ["Claim broken into parts before evidence is gathered", "Ranking sheet for candidate quotes", "Tick-the-parts audit", "Line-numbered text"],
    tech: "Printed text with line numbers",
    tech_purpose: "Precise citation and easy comparison",
    ai_prompts: ["Generate multi-part claims with quotes covering only some parts", "Create candidate quote sets of varying strength"],
    assessment: ["Check every part of the claim is evidenced", "Confirm rankings carry justifications", "Read inference reasoning"],
    why_it_works: ["Splitting the claim makes sufficiency countable rather than a feeling", "Ranking surfaces reasoning that selecting hides", "Strong and thorough are different failures, so separate them", "Peer challenge finds the unevidenced part faster than self-review"],
  },
  {
    standard_code: "RL.9-10.2",
    title: "Where a Theme Emerges and How It Changes",
    badge: "Grades 9-10",
    route_name: "Analytical Reading",
    route_line: "State the theme → Find its first appearance → Track what refines it",
    success_criteria: ["States a theme as a claim about life", "Identifies where it first emerges", "Shows how later moments refine it"],
    steps: [
      { name: "Retrieve Theme Versus Topic", minutes: 5, body: "Sort words and sentences. The distinction should be automatic by now.", science_tag: "retrieval" },
      { name: "Themes Are Not Static", minutes: 10, body: "A theme stated at the start and complicated by the end. Read both moments together and name the difference.", science_tag: "elaboration" },
      { name: "Find the Emergence", minutes: 12, body: "Where does this idea first become visible? Often earlier and quieter than students expect.", science_tag: "elaboration" },
      { name: "Track the Refining", minutes: 14, body: "Three moments across the text, each adding a qualification. Plot them on a timeline.", science_tag: "dual-coding" },
      { name: "Say What Changed", minutes: 10, body: "Compare the first and last statement of the theme in one sentence. If nothing changed, it was repetition.", science_tag: "elaboration" },
      { name: "Objective Summary", minutes: 6, body: "Both the theme and its development, with no evaluative language.", science_tag: "interleaving" },
      { name: "Compare Two Readings", minutes: 3, body: "Two students state the theme differently. Whose evidence holds?", science_tag: "spaced" },
    ],
    ef_supports: ["Timeline organiser", "First-and-last comparison frame", "Banned evaluative word list", "Theme claim sentence stem"],
    tech: "Printed text with wide margins",
    tech_purpose: "Marking where a theme surfaces",
    ai_prompts: ["Write a passage where a theme is complicated by the ending", "Generate theme statements at varying levels of precision"],
    assessment: ["Check the emergence point is evidenced", "Confirm development shows change", "Scan summaries for judgment"],
    why_it_works: ["Emergence is a specific moment, so it can be argued about", "Comparing first and last statements makes refinement concrete", "Repetition is the default misreading, so name it", "Competing readings show interpretation is evidenced, not felt"],
  },
  {
    standard_code: "RI.9-10.5",
    title: "What This Passage Is Doing for the Argument",
    badge: "Grades 9-10",
    route_name: "Analytical Reading",
    route_line: "Find the claim → Name each passage's job → Separate developing from refining",
    success_criteria: ["Identifies the author's claim", "Names what a passage does", "Distinguishes developing from refining"],
    steps: [
      { name: "Retrieve Paragraph Function", minutes: 5, body: "Recall the menu of jobs a paragraph can do.", science_tag: "retrieval" },
      { name: "Develop or Refine", minutes: 12, body: "Developing adds reach; refining narrows and qualifies. Sort passages into the two.", science_tag: "elaboration" },
      { name: "Map the Argument", minutes: 12, body: "One row per passage, function only. Content words banned, which forces analysis over summary.", science_tag: "dual-coding" },
      { name: "Delete a Passage", minutes: 10, body: "What is lost? The damage names the role better than description does.", science_tag: "elaboration" },
      { name: "The Qualifying Move", minutes: 10, body: "Find where the author limits their own claim. Students often read this as weakness rather than rigour.", science_tag: "elaboration" },
      { name: "Write the Analysis", minutes: 8, body: "One passage: what it does, and how it develops or refines the claim.", science_tag: "interleaving" },
      { name: "Compare Two Maps", minutes: 3, body: "Two students compare function maps and discuss disagreements.", science_tag: "spaced" },
    ],
    ef_supports: ["Function menu", "Develop-versus-refine sorting mat", "Content-word ban", "Numbered passages"],
    tech: "Printed article with numbered paragraphs",
    tech_purpose: "Mapping needs stable references",
    ai_prompts: ["Write an argument that qualifies its own claim midway", "Generate passages that develop versus refine the same claim"],
    assessment: ["Check maps name functions not content", "Confirm the qualifying passage is found", "Read analyses for the distinction"],
    why_it_works: ["Banning content words is what forces function over summary", "The deletion test makes an abstract role concrete", "Qualification read as rigour is a genuine shift in maturity", "Develop versus refine is precisely what the standard asks"],
  },
  {
    standard_code: "W.9-10.1",
    title: "Reasoning That Actually Connects",
    badge: "Grades 9-10",
    route_name: "Writing Workshop",
    route_line: "Claim and evidence → Write the reasoning → Steelman the other side",
    success_criteria: ["Reasoning links each piece of evidence to the claim", "Evidence is sufficient for the claim made", "The counterclaim is stated at its strongest"],
    steps: [
      { name: "Retrieve Claim and Evidence", minutes: 5, body: "One claim, one piece of support. The floor before raising it.", science_tag: "retrieval" },
      { name: "The Missing Middle", minutes: 12, body: "A paragraph with a claim and a quote and nothing between them. Students supply the reasoning and see how much work it does.", science_tag: "elaboration" },
      { name: "Valid or Just Adjacent", minutes: 12, body: "Reasoning that sounds right but does not follow. Naming the gap is harder than spotting a missing quote.", science_tag: "elaboration" },
      { name: "Steelman the Opposition", minutes: 12, body: "Write the other side as its holders would. A caricature is easy to beat and proves nothing.", science_tag: "elaboration" },
      { name: "Concede and Counter", minutes: 10, body: "Grant what is true, then show why the claim survives. Model the frame twice.", science_tag: "dual-coding" },
      { name: "Assemble", minutes: 8, body: "Claim, evidence, reasoning, counterclaim, response — one full pass.", science_tag: "collaborative" },
      { name: "Attack a Partner's", minutes: 3, body: "Find the weakest link in the reasoning, not the evidence.", science_tag: "spaced" },
    ],
    ef_supports: ["Reasoning sentence isolated for practice", "Steelman requirement in writing", "Concede-then-counter frame", "Peer attack focused on reasoning"],
    tech: "Printed organisers",
    tech_purpose: "Keeping the five moves distinct while drafting",
    ai_prompts: ["Write claim-and-quote pairs with the reasoning removed", "Generate plausible but invalid reasoning for critique"],
    assessment: ["Check reasoning follows, not merely sounds right", "Confirm counterclaims are genuine", "Peer review targets reasoning"],
    why_it_works: ["Removing the reasoning shows how much of the argument lived there", "Invalid-but-plausible reasoning is the hard case at this level", "Steelmanning is what separates argument from persuasion", "Attacking reasoning rather than evidence raises the level of critique"],
  },
  {
    standard_code: "W.9-10.2",
    title: "Explaining Without Flattening",
    badge: "Grades 9-10",
    route_name: "Writing Workshop",
    route_line: "Find the tension → Select against it → Organise so it holds",
    success_criteria: ["Preserves the complexity rather than simplifying it away", "Selects content that carries the idea", "Organises so the parts connect"],
    steps: [
      { name: "Retrieve Informative Structure", minutes: 5, body: "Sections, transitions, concrete detail. The base to build on.", science_tag: "retrieval" },
      { name: "Complex Is Not Complicated", minutes: 10, body: "Complicated means many parts; complex means the parts interact. Sort topics into the two.", science_tag: "elaboration" },
      { name: "Find the Tension", minutes: 12, body: "Every complex topic contains a trade-off. Name it before writing — it is what the piece is about.", science_tag: "elaboration" },
      { name: "Cut Against the Tension", minutes: 12, body: "Keep what serves it, cut the rest. Selection with a criterion rather than by taste.", science_tag: "elaboration" },
      { name: "Accuracy Check", minutes: 8, body: "Compare each claim against the source. Approximately right is wrong at this level.", science_tag: "interleaving" },
      { name: "Draft Two Sections", minutes: 10, body: "Two sections and the join between them.", science_tag: "collaborative" },
      { name: "Read the Tension Aloud", minutes: 3, body: "One student reads the sentence naming the trade-off.", science_tag: "spaced" },
    ],
    ef_supports: ["Complicated versus complex sort", "Name-the-tension step before drafting", "Source accuracy check", "Draft two sections, not the whole piece"],
    tech: "Note cards and source excerpts",
    tech_purpose: "Selection is physical before it is written",
    ai_prompts: ["Generate topics containing a genuine trade-off", "Write flattened explanations for students to restore complexity to"],
    assessment: ["Check the tension is named", "Confirm cuts follow the criterion", "Verify claims against sources"],
    why_it_works: ["Naming the tension gives selection a criterion instead of taste", "Complicated versus complex is the distinction this standard turns on", "Flattening is the default failure, so make it visible", "Accuracy checking against sources builds a habit that matters beyond school"],
  },
  {
    standard_code: "SL.9-10.1",
    title: "Starting a Discussion, Not Just Joining One",
    badge: "Grades 9-10",
    route_name: "Structured Discussion",
    route_line: "Prepare a position → Initiate a line → Move someone, or be moved",
    success_criteria: ["Opens a new line of discussion", "Supports a position persuasively with evidence", "Engages with someone who disagrees"],
    steps: [
      { name: "Retrieve Talk Moves", minutes: 5, body: "Recall the moves before the chart appears.", science_tag: "retrieval" },
      { name: "Answering Is Not Initiating", minutes: 10, body: "Play a recording where everybody responds and nobody opens anything. Name what is missing.", science_tag: "elaboration" },
      { name: "Prepare an Opening", minutes: 10, body: "Each student writes one question or claim they could open with, plus the evidence behind it.", science_tag: "elaboration" },
      { name: "Persuasive Is Not Loud", minutes: 10, body: "Compare a forceful contribution with one that actually changed a mind. Credit the second.", science_tag: "dual-coding" },
      { name: "Seminar", minutes: 15, body: "Teacher outside the circle and silent. Initiating turns assigned so it is not left to the confident.", science_tag: "collaborative" },
      { name: "Track Openings and Shifts", minutes: 5, body: "Outer circle counts lines opened and positions changed.", science_tag: "interleaving" },
      { name: "Reflect on a Shift", minutes: 5, body: "Write about a moment your thinking moved, and what moved it.", science_tag: "spaced" },
    ],
    ef_supports: ["Prepared opening with evidence", "Assigned initiating turns", "Inner and outer circle", "Tally of openings and shifts"],
    tech: "Preparation and tally sheets",
    tech_purpose: "Initiating made a countable expectation",
    ai_prompts: ["Generate seminar questions with genuinely competing positions", "Write a discussion transcript where nobody initiates"],
    assessment: ["Check preparation sheets", "Count openings, not just contributions", "Read reflections for genuine shifts"],
    why_it_works: ["Assigning initiating turns stops it defaulting to the confident", "Counting openings measures the specific skill in the standard", "Crediting the mind-changing contribution redefines persuasive", "Teacher silence is the precondition for student ownership"],
  },
  {
    standard_code: "L.9-10.4",
    title: "Guess, Break Apart, Verify",
    badge: "Grades 9-10",
    route_name: "Strategy Instruction",
    route_line: "Infer from context → Break the word down → Check and sharpen",
    success_criteria: ["Proposes a meaning before consulting a reference", "Uses roots and affixes", "Records the gap between guess and definition"],
    steps: [
      { name: "Retrieve Roots", minutes: 5, body: "Rapid recall of taught Greek and Latin roots.", science_tag: "retrieval" },
      { name: "Guess Before You Look", minutes: 8, body: "Establish the order. Looking up first skips the thinking that makes it stick.", science_tag: "elaboration" },
      { name: "Two Sources, One Word", minutes: 12, body: "Context and word parts applied to the same word. Compare what each suggests — they can disagree.", science_tag: "dual-coding" },
      { name: "Etymology Tells a Story", minutes: 10, body: "Where a word came from often explains its odd modern sense. A word with a history is a word that stays.", science_tag: "elaboration" },
      { name: "Verify and Record the Gap", minutes: 12, body: "Now the reference. How close was the guess? The gap is where precision is learned.", science_tag: "elaboration" },
      { name: "Mixed Practice", minutes: 8, body: "Words yielding to different strategies. Choosing is the skill.", science_tag: "interleaving" },
      { name: "One Word, Three Steps", minutes: 3, body: "Guess, verify, note the gap.", science_tag: "spaced" },
    ],
    ef_supports: ["Guess-verify-gap recording sheet", "Growing root chart", "Etymology reference", "Both clue sources on one word"],
    tech: "Dictionaries with etymologies",
    tech_purpose: "Verification and word histories need a real reference",
    ai_prompts: ["Generate words where context and etymology suggest different senses", "Create multi-sense entries for selection practice"],
    assessment: ["Check the guess precedes the lookup", "Confirm the chosen sense fits", "Review recorded gaps"],
    why_it_works: ["Guessing first is what makes the verified meaning stick", "Disagreement between clue sources is where real reasoning happens", "Etymology gives a word a hook that a definition alone lacks", "Recording the gap turns approximation into precision"],
  },
  {
    standard_code: "RL.11-12.3",
    title: "Why Told This Way",
    badge: "Grades 11-12",
    route_name: "Analytical Reading",
    route_line: "Describe the ordering → Name the choice → Reorder it and compare",
    success_criteria: ["Describes how the action is ordered", "Names the choice as deliberate", "Explains what a different ordering would cost"],
    steps: [
      { name: "Retrieve Story Elements", minutes: 5, body: "Setting, character, plot, conflict. The parts before their arrangement.", science_tag: "retrieval" },
      { name: "Chronology Is a Choice", minutes: 10, body: "Map the events in story order and in told order. The gap between the two is the author's decision.", science_tag: "dual-coding" },
      { name: "Where We Meet People", minutes: 10, body: "When a character is introduced shapes how we judge them. Find a late introduction and ask what it buys.", science_tag: "elaboration" },
      { name: "Reorder the Scene", minutes: 14, body: "Retell one sequence chronologically. Read both aloud. What is lost is what the choice was for.", science_tag: "elaboration" },
      { name: "Setting as Pressure", minutes: 10, body: "Not scenery — constraint. What does this place make possible or impossible?", science_tag: "elaboration" },
      { name: "Write the Analysis", minutes: 8, body: "One structural choice, its effect, and what the reordering test showed.", science_tag: "interleaving" },
      { name: "Share a Reordering", minutes: 3, body: "One student explains what broke when they straightened the timeline.", science_tag: "spaced" },
    ],
    ef_supports: ["Two-timeline map: story order and told order", "Reordering as a thought experiment", "Setting-as-constraint prompt", "Numbered scenes"],
    tech: "Printed excerpt with numbered scenes",
    tech_purpose: "Reordering needs stable references",
    ai_prompts: ["Write an excerpt that withholds a key event until late", "Generate reordering prompts for a given text"],
    assessment: ["Check both timelines are mapped", "Confirm the reordering test is run", "Read analyses for effect, not description"],
    why_it_works: ["Two timelines make the authorial choice visible as a gap", "Reordering is the only way to feel what an ordering achieved", "Late introductions are a concrete, arguable case", "Setting as constraint moves past scenery"],
  },
  {
    standard_code: "RI.11-12.6",
    title: "How This Text Persuades",
    badge: "Grades 11-12",
    route_name: "Analytical Reading",
    route_line: "Name the purpose → Find the technique → Judge it apart from agreeing",
    success_criteria: ["States a purpose specific enough to dispute", "Identifies rhetorical techniques", "Judges effectiveness separately from agreement"],
    steps: [
      { name: "Retrieve Author's Position", minutes: 5, body: "One text, one position stated in a sentence.", science_tag: "retrieval" },
      { name: "Three Appeals", minutes: 10, body: "Ethos, pathos, logos — introduced as tools rather than labels to spot.", science_tag: "dual-coding" },
      { name: "Highlight the Technique", minutes: 12, body: "Colour-code the appeals through a speech. A pattern emerges that single sentences do not show.", science_tag: "dual-coding" },
      { name: "Agree But Analyse", minutes: 12, body: "A text the class agrees with. Judging its craft while sharing its view is the harder discipline.", science_tag: "elaboration" },
      { name: "Disagree But Credit", minutes: 10, body: "Now a text they reject that is superbly made. Effective and agreeable are different judgments.", science_tag: "elaboration" },
      { name: "Write the Analysis", minutes: 8, body: "How style and content combine to persuade — with no statement of whether you agree.", science_tag: "interleaving" },
      { name: "Defend a Judgment", minutes: 3, body: "One student argues a text is effective while disagreeing with it.", science_tag: "spaced" },
    ],
    ef_supports: ["Three-colour highlighting for the appeals", "Agree-but-analyse and disagree-but-credit pairs", "Ban on stating agreement in the analysis", "Numbered paragraphs"],
    tech: "Printed speeches with numbered paragraphs",
    tech_purpose: "Tracking appeals across a whole text",
    ai_prompts: ["Generate persuasive passages leaning on different appeals", "Find well-made arguments students would likely reject"],
    assessment: ["Check purposes are disputable", "Confirm analysis avoids agreement", "Listen to the defence of effectiveness"],
    why_it_works: ["Separating effective from agreeable is the whole discipline here", "Colour-coding shows appeals as a pattern rather than isolated moments", "A well-made argument you reject is the sharpest test", "Banning agreement from the analysis forces attention onto craft"],
  },
  {
    standard_code: "W.11-12.1",
    title: "Writing to Someone in Particular",
    badge: "Grades 11-12",
    route_name: "Writing Workshop",
    route_line: "Name the audience → Establish significance → Answer them before they ask",
    success_criteria: ["Names a specific audience", "Establishes why the claim matters", "Anticipates and answers likely objections"],
    steps: [
      { name: "Retrieve Argument Structure", minutes: 5, body: "Claim, evidence, reasoning, counterclaim. The base to build on.", science_tag: "retrieval" },
      { name: "Written for Nobody", minutes: 10, body: "An argument addressed to no one in particular. Students notice it persuades no one either.", science_tag: "elaboration" },
      { name: "Name Your Reader", minutes: 10, body: "Who specifically? What do they already believe, and what will they resist?", science_tag: "elaboration" },
      { name: "So What?", minutes: 10, body: "Significance is not the same as truth. Why does this claim matter, to them?", science_tag: "elaboration" },
      { name: "List Three Objections", minutes: 12, body: "Before drafting. Then answer each in advance rather than after it lands.", science_tag: "dual-coding" },
      { name: "Draft the Opening", minutes: 10, body: "Claim, significance, and the first anticipated objection.", science_tag: "collaborative" },
      { name: "Read to the Audience", minutes: 3, body: "A partner reads as the named audience and says where they resisted.", science_tag: "spaced" },
    ],
    ef_supports: ["Audience profile before drafting", "Three-objection list", "So-what test for significance", "Partner reads in role"],
    tech: "Printed audience profile sheets",
    tech_purpose: "Making an abstract reader concrete",
    ai_prompts: ["Generate claims with clearly different likely audiences", "Write arguments addressed to nobody, for critique"],
    assessment: ["Check the audience is specific", "Confirm significance is established", "Verify objections are answered in advance"],
    why_it_works: ["An argument for nobody persuades nobody, and students feel it immediately", "Listing objections first changes the draft rather than patching it", "Significance is the move that separates an essay from an argument", "A partner reading in role gives real resistance"],
  },
  {
    standard_code: "N-RN.2",
    title: "Roots and Powers Are the Same Thing",
    badge: "High school",
    route_name: "Explicit Instruction",
    route_line: "Test with numbers → See the pattern → Convert either way",
    success_criteria: ["Converts between radicals and rational exponents", "Applies exponent properties to both forms", "Justifies the equivalence numerically"],
    steps: [
      { name: "Retrieve Exponent Rules", minutes: 5, body: "Integer properties, fast. Everything here extends them.", science_tag: "retrieval" },
      { name: "What Would One-Half Mean", minutes: 12, body: "If the rules hold, x to the half times x to the half is x. So it must be the square root. Derived, not decreed.", science_tag: "elaboration" },
      { name: "Check With Numbers", minutes: 10, body: "Nine to the one-half is three. Test several before trusting the rule.", science_tag: "elaboration" },
      { name: "Bottom Is the Root", minutes: 10, body: "Two-thirds means cube root, squared. Say it aloud every time until the roles stop swapping.", science_tag: "dual-coding" },
      { name: "Convert Both Ways", minutes: 12, body: "Radical to exponent and back, mixed so the direction must be read.", science_tag: "interleaving" },
      { name: "Simplify With Them", minutes: 8, body: "Problems easier in one form than the other. Choosing the form is the skill.", science_tag: "interleaving" },
      { name: "Justify One", minutes: 3, body: "Explain why the one-half power is a square root.", science_tag: "spaced" },
    ],
    ef_supports: ["Numerical checks before symbolic rules", "Bottom-is-the-root phrase", "Two-way conversion practice", "Choose-the-easier-form prompt"],
    tech: "Calculators for numerical checks",
    tech_purpose: "Testing a rule before trusting it",
    ai_prompts: ["Generate conversion pairs in both directions", "Create expressions easier in one form than the other"],
    assessment: ["Check numerator and denominator roles", "Confirm conversions both ways", "Ask for the justification"],
    why_it_works: ["Deriving the meaning from the existing rules beats asserting it", "Numerical checks make an abstract definition testable", "Root and power roles swap constantly, so drill the phrase", "Choosing the form is where fluency shows"],
  },
  {
    standard_code: "A-SSE.1",
    title: "Reading an Expression Before Solving It",
    badge: "High school",
    route_name: "Explicit Instruction",
    route_line: "Name the parts → Say what each means → Treat a group as one",
    success_criteria: ["Identifies terms, factors and coefficients", "Says what a part means in context", "Treats a group of symbols as a single entity"],
    steps: [
      { name: "Retrieve Expression Vocabulary", minutes: 5, body: "Term, factor, coefficient. Named quickly before use.", science_tag: "retrieval" },
      { name: "Do Not Simplify Yet", minutes: 10, body: "An expression from a real context. Ask what each part represents before touching it.", science_tag: "elaboration" },
      { name: "Interest and Growth", minutes: 12, body: "P(1+r) — the P is the money, the bracket is the growth factor. Interpretation before computation.", science_tag: "elaboration" },
      { name: "Chunk It", minutes: 12, body: "Substitute a single letter for a repeated group. A complicated expression becomes a simple one.", science_tag: "dual-coding" },
      { name: "Chunking Reveals Structure", minutes: 10, body: "A quartic that is really a quadratic in disguise, once the group is treated as one thing.", science_tag: "elaboration" },
      { name: "Interpret in Context", minutes: 8, body: "Mixed expressions from real situations. Say what a part means before any manipulation.", science_tag: "interleaving" },
      { name: "Explain a Part", minutes: 3, body: "Point at a factor and say what it does.", science_tag: "spaced" },
    ],
    ef_supports: ["Interpret-before-simplify routine", "Substitute-a-letter chunking", "Real contexts with units", "Vocabulary reference"],
    tech: "Printed expression cards",
    tech_purpose: "Annotating parts before manipulating",
    ai_prompts: ["Generate expressions from real contexts with meaningful parts", "Create expressions that simplify once chunked"],
    assessment: ["Check interpretation precedes simplification", "Confirm chunking is attempted", "Ask what a named part means"],
    why_it_works: ["Interpreting before simplifying is the habit the standard names", "Chunking turns intimidating expressions into familiar ones", "Real contexts give the parts something to mean", "Structure seen is structure that can be used"],
  },
  {
    standard_code: "A-CED.1",
    title: "From Situation to Equation",
    badge: "High school",
    route_name: "Mathematical Modeling",
    route_line: "Define the variable → Write the constraint → Solve and check it fits",
    success_criteria: ["Defines the variable with units", "Writes an equation or inequality matching the situation", "Checks the solution against the constraints"],
    steps: [
      { name: "Retrieve Solving", minutes: 5, body: "Linear and simple quadratic solving, quickly. Modeling needs this automatic.", science_tag: "retrieval" },
      { name: "Let x Equal What Exactly", minutes: 10, body: "With units, every time. Most modeling errors are born here.", science_tag: "elaboration" },
      { name: "Equation or Inequality", minutes: 12, body: "At most, at least, no more than. The words that decide which one, and which way it points.", science_tag: "dual-coding" },
      { name: "List the Constraints", minutes: 10, body: "What does the situation forbid? Negative lengths, fractional people. Written before solving.", science_tag: "elaboration" },
      { name: "Solve and Test", minutes: 12, body: "Solve, then check the answer against every constraint. A mathematically correct impossible answer is still wrong.", science_tag: "interleaving" },
      { name: "Mixed Contexts", minutes: 8, body: "Linear, quadratic and exponential situations shuffled, so the model must be judged.", science_tag: "interleaving" },
      { name: "Model One Situation", minutes: 3, body: "Define, write, solve, check.", science_tag: "spaced" },
    ],
    ef_supports: ["Let-x-equal frame with units", "Constraint list before solving", "Inequality word bank", "Check-against-constraints step"],
    tech: "Printed context cards",
    tech_purpose: "Real situations to model",
    ai_prompts: ["Generate situations with meaningful constraints", "Create problems where the mathematical answer violates the context"],
    assessment: ["Check variables carry units", "Confirm constraints are listed", "Verify answers are tested against them"],
    why_it_works: ["Defining the variable precisely prevents most modeling errors", "Constraints written first make checking possible", "An impossible-but-correct answer teaches what modeling means", "Mixed contexts stop pattern-matching to one model type"],
  },
  {
    standard_code: "A-REI.4",
    title: "Four Ways to Solve a Quadratic",
    badge: "High school",
    route_name: "Strategy Instruction",
    route_line: "Learn each method → Race them → Choose by inspection",
    success_criteria: ["Solves by roots, factoring, completing the square and the formula", "Chooses a method suited to the equation", "Interprets a negative discriminant"],
    steps: [
      { name: "Retrieve Factoring", minutes: 5, body: "Factor several quadratics quickly. The fastest method when it works.", science_tag: "retrieval" },
      { name: "Four Methods", minutes: 12, body: "Taking roots, factoring, completing the square, the formula. Same equation, all four, side by side.", science_tag: "dual-coding" },
      { name: "Race Them", minutes: 10, body: "One easy equation, timed by method. Factoring wins; the formula is the slow reliable one.", science_tag: "elaboration" },
      { name: "When Factoring Fails", minutes: 10, body: "An unfactorable quadratic. Completing the square always works, and the formula comes from it.", science_tag: "elaboration" },
      { name: "The Discriminant", minutes: 12, body: "What the part under the root tells you before you compute anything. Sort equations by number of real solutions.", science_tag: "interleaving" },
      { name: "Choose by Inspection", minutes: 8, body: "Mixed set. Name the method before solving. The choosing is the skill.", science_tag: "interleaving" },
      { name: "Explain a Choice", minutes: 3, body: "Why that method for this equation?", science_tag: "spaced" },
    ],
    ef_supports: ["Four-method comparison on one equation", "Timing to motivate selection", "Discriminant sorting mat", "Name-the-method-first routine"],
    tech: "Printed equation cards",
    tech_purpose: "Sorting by method before solving",
    ai_prompts: ["Generate quadratics best suited to each method", "Create sets with varying discriminants"],
    assessment: ["Check the method is named first", "Confirm the discriminant is interpreted", "Ask for justification of the choice"],
    why_it_works: ["Timing gives a reason to choose rather than defaulting to the formula", "Deriving the formula from completing the square makes it less arbitrary", "The discriminant predicts before computing, which is genuinely useful", "Naming the method first is where the strategy lives"],
  },
  {
    standard_code: "F-IF.4",
    title: "What the Graph Is Telling You",
    badge: "High school",
    route_name: "Explicit Instruction",
    route_line: "Name the features → Say what they mean → Sketch from a description",
    success_criteria: ["Identifies intercepts, extremes and intervals", "Interprets each in terms of the real quantities", "Sketches a graph from a verbal description"],
    steps: [
      { name: "Retrieve Function Basics", minutes: 5, body: "Input, output, one output per input. The ground beneath all of it.", science_tag: "retrieval" },
      { name: "The Feature Vocabulary", minutes: 10, body: "Intercepts, maxima, intervals of increase, end behaviour. Named on one graph.", science_tag: "dual-coding" },
      { name: "What Does That Mean Here", minutes: 12, body: "A y-intercept is not a number, it is the starting height, or the fixed fee. Require units and meaning.", science_tag: "elaboration" },
      { name: "The Graph Is Not a Picture", minutes: 12, body: "A distance-time graph that looks like a hill but describes no hill. The classic misreading, confronted.", science_tag: "elaboration" },
      { name: "Sketch From Words", minutes: 10, body: "Given a description, draw a graph showing the features. Harder than reading one.", science_tag: "interleaving" },
      { name: "Interpret a Real Graph", minutes: 8, body: "Real data. Describe the features in the quantities' own terms.", science_tag: "collaborative" },
      { name: "Explain One Feature", minutes: 3, body: "Say what a maximum means in context.", science_tag: "spaced" },
    ],
    ef_supports: ["Feature vocabulary chart", "Units required in every interpretation", "Graph-is-not-a-picture counterexample", "Sketch-from-description tasks"],
    tech: "Graph paper and printed graphs",
    tech_purpose: "Sketching is a different skill from reading",
    ai_prompts: ["Generate contexts whose graphs invite a picture misreading", "Write verbal descriptions for students to sketch"],
    assessment: ["Check interpretations carry units", "Confirm the picture misreading is avoided", "Review sketches for named features"],
    why_it_works: ["Interpreting with units turns graph reading into modelling", "The graph-as-picture misreading persists unless confronted directly", "Sketching from words tests understanding that reading can fake", "Real data makes the features worth naming"],
  },
  {
    standard_code: "F-BF.1",
    title: "Building the Rule Yourself",
    badge: "High school",
    route_name: "Mathematical Modeling",
    route_line: "Describe the pattern → Write it recursively → Write it explicitly",
    success_criteria: ["Writes a recursive rule from a context", "Writes an explicit rule", "Checks the model against the situation"],
    steps: [
      { name: "Retrieve Function Notation", minutes: 5, body: "Reading and evaluating f(x). The language before the building.", science_tag: "retrieval" },
      { name: "Describe Before Symbolising", minutes: 10, body: "Say the rule in words first. The sentence becomes the function.", science_tag: "elaboration" },
      { name: "Recursive Is Natural", minutes: 12, body: "Each term from the one before. It matches how situations actually unfold.", science_tag: "dual-coding" },
      { name: "Ask for the Hundredth Term", minutes: 10, body: "Recursion breaks down. The need for an explicit rule creates itself.", science_tag: "elaboration" },
      { name: "Write It Explicitly", minutes: 12, body: "Any term directly. Connect each parameter back to the situation.", science_tag: "elaboration" },
      { name: "Check Against a Third Point", minutes: 8, body: "A rule fitted to two points and never checked is a guess.", science_tag: "interleaving" },
      { name: "Model One Situation", minutes: 3, body: "Words, recursive, explicit, checked.", science_tag: "spaced" },
    ],
    ef_supports: ["Describe-in-words step before symbols", "Hundredth-term prompt", "Parameter-to-context mapping", "Third-point check"],
    tech: "Printed context cards",
    tech_purpose: "Situations worth modelling",
    ai_prompts: ["Generate contexts that unfold recursively", "Create situations where an explicit rule is clearly needed"],
    assessment: ["Check the words come before the symbols", "Confirm both rule forms", "Verify the third-point check"],
    why_it_works: ["Saying the rule in words first makes the symbols a translation", "Asking for a distant term creates the need for the explicit form", "Mapping parameters to context keeps it modelling rather than algebra", "Checking a third point catches an overfitted guess"],
  },
  {
    standard_code: "F-LE.2",
    title: "Adding or Multiplying?",
    badge: "High school",
    route_name: "Explicit Instruction",
    route_line: "Test differences → Test ratios → Write the rule",
    success_criteria: ["Tests a table for both a common difference and a common ratio", "Distinguishes linear from exponential", "Writes the corresponding function"],
    steps: [
      { name: "Retrieve Slope", minutes: 5, body: "Rate of change from a table. The linear test in miniature.", science_tag: "retrieval" },
      { name: "Both Tests, Always", minutes: 12, body: "Differences and ratios on the same table. Running only one is how exponentials get called linear.", science_tag: "dual-coding" },
      { name: "Early Terms Mislead", minutes: 12, body: "Two tables that look identical for four rows and diverge sharply after. Extend before deciding.", science_tag: "elaboration" },
      { name: "Sequences Are Functions", minutes: 10, body: "Arithmetic is linear, geometric is exponential. The same idea in different clothes.", science_tag: "elaboration" },
      { name: "Write Both Rules", minutes: 12, body: "From a table, a graph and two points. Three starting places, one rule.", science_tag: "interleaving" },
      { name: "Which Grows Faster", minutes: 8, body: "Exponential eventually overtakes any linear, however slow its start. Extend far enough to see it.", science_tag: "elaboration" },
      { name: "Classify and Write", minutes: 3, body: "One table classified with both tests, then written as a function.", science_tag: "spaced" },
    ],
    ef_supports: ["Both-tests-always routine", "Tables extended far enough to diverge", "Sequence-to-function mapping", "Three starting points for the same rule"],
    tech: "Printed tables and graph paper",
    tech_purpose: "Extending a table is what reveals the difference",
    ai_prompts: ["Generate table pairs that look alike early and diverge later", "Create linear and exponential contexts"],
    assessment: ["Check both tests are run", "Confirm tables are extended before deciding", "Verify the written rules"],
    why_it_works: ["Running only one test is the standard failure, so require both", "Early similarity is genuinely deceptive and worth experiencing", "Linking sequences to functions unifies two topics usually taught apart", "Seeing exponential overtake linear makes the distinction matter"],
  },
  {
    standard_code: "G-SRT.8",
    title: "Which Ratio, and Why",
    badge: "High school",
    route_name: "Strategy Instruction",
    route_line: "Mark the angle → Label from it → Choose the ratio that uses what you know",
    success_criteria: ["Labels opposite and adjacent relative to the angle", "Chooses the ratio using the known sides", "Solves applied problems including angles of elevation"],
    steps: [
      { name: "Retrieve Pythagoras", minutes: 5, body: "Find a missing side. The tool for when no angle is involved.", science_tag: "retrieval" },
      { name: "Labels Depend on the Angle", minutes: 12, body: "The same side is opposite one angle and adjacent to another. Mark the angle first, always.", science_tag: "dual-coding" },
      { name: "Three Ratios", minutes: 10, body: "Sine, cosine, tangent, defined from the labels rather than memorised as a word.", science_tag: "elaboration" },
      { name: "Choose by What You Know", minutes: 12, body: "List the known sides, then pick the ratio using them. Selection, not recall.", science_tag: "elaboration" },
      { name: "Angle or Side", minutes: 10, body: "Finding an angle needs the inverse. A different button and a different question.", science_tag: "interleaving" },
      { name: "Applied Problems", minutes: 8, body: "Ladders, elevation, shadows. Draw and label before touching a ratio.", science_tag: "collaborative" },
      { name: "One of Each", minutes: 3, body: "One missing side, one missing angle.", science_tag: "spaced" },
    ],
    ef_supports: ["Mark-the-angle-first routine", "Label-from-the-angle practice", "Known-sides checklist", "Draw and label before solving"],
    tech: "Printed diagrams and calculators",
    tech_purpose: "Labelling relative to the angle needs a markable diagram",
    ai_prompts: ["Generate right triangles where the same side changes role", "Create applied trigonometry problems with diagrams"],
    assessment: ["Check the angle is marked before labelling", "Confirm the ratio matches the known sides", "Watch for inverse operations when finding angles"],
    why_it_works: ["Labels depending on the angle is the misconception that defeats students", "Choosing by what you know turns recall into strategy", "Finding an angle is a different question, so separate it", "Diagrams drawn before ratios prevent blind substitution"],
  },
  {
    standard_code: "S-ID.6",
    title: "Fitting a Line, and Knowing Its Limits",
    badge: "High school",
    route_name: "Explicit Instruction",
    route_line: "Plot it → Fit a function → Say where the prediction stops being trustworthy",
    success_criteria: ["Fits a function to bivariate data", "Uses residuals to judge the fit", "Says where a prediction becomes unreliable"],
    steps: [
      { name: "Retrieve Scatter Plots", minutes: 5, body: "Direction, form, strength. The description before the model.", science_tag: "retrieval" },
      { name: "Fit by Eye First", minutes: 10, body: "Draw a line through the data by hand. Compare across the room — everybody's differs, which motivates a rule.", science_tag: "elaboration" },
      { name: "Residuals Judge the Fit", minutes: 14, body: "How far is each point from the line? A residual plot with a pattern means the wrong model.", science_tag: "dual-coding" },
      { name: "Fitting the Wrong Shape", minutes: 10, body: "A line through curved data. The correlation looks decent; the residuals give it away.", science_tag: "elaboration" },
      { name: "Predict Within Range", minutes: 12, body: "Interpolate, then extrapolate absurdly far. Where does the model stop meaning anything?", science_tag: "elaboration" },
      { name: "Real Data", minutes: 8, body: "Class-collected data, fitted and interpreted with units.", science_tag: "collaborative" },
      { name: "State a Limit", minutes: 3, body: "Say one prediction this model cannot support.", science_tag: "spaced" },
    ],
    ef_supports: ["Fit-by-eye before any formula", "Residual plots", "Absurd extrapolation prompt", "Class-collected data"],
    tech: "Graph paper and calculators",
    tech_purpose: "Residual plots need to be drawn to be believed",
    ai_prompts: ["Generate curved data that a line fits deceptively well", "Create prediction questions inside and far outside the data range"],
    assessment: ["Check residuals are examined", "Confirm the wrong-shape case is spotted", "Require a stated limit on prediction"],
    why_it_works: ["Everybody's hand-drawn line differing motivates a principled rule", "Residuals are the honest judge that correlation alone is not", "Absurd extrapolation makes the limits of a model concrete", "Stating what a model cannot do is the mark of statistical maturity"],
  },
];

await seedStandardsBatch({
  label: "Batch 8 — high school",
  standardsData,
  unpacksData,
  blueprintsData,
});
