// @ts-nocheck
/**
 * Batch 14: grade 3 mathematics.
 *
 * Finishes grade 3, and with it the whole 3rd grade deck.
 *
 * The misconceptions here are unusually sharp, and several are about rules
 * learned without meaning: five or more raise the score, add a zero, count the
 * tick marks. Each of those works until it does not, and the moment it stops
 * working is usually years later. The blueprints go after the meaning rather
 * than the rule.
 *
 * American spellings throughout.
 *
 *   bun run scripts/seed-standards-batch-14.ts
 */
import { seedStandardsBatch } from "./lib/seed-standards-batch";

const standardsData = [
  {
    code: "3.OA.A.2",
    name: "Division has two meanings",
    plain_reading:
      "Interpret whole-number quotients of whole numbers as the number of objects in each share or the number of shares.",
    learning_target: "I can tell whether a problem is asking how many groups or how many in each group.",
    skills: ["Partitive Division", "Measurement Division", "Representing Division"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["quotient", "share equally", "how many groups", "partitive measurement division", "third grade"],
  },
  {
    code: "3.OA.A.3",
    name: "Model the situation, not the keywords",
    plain_reading:
      "Use multiplication and division within 100 to solve word problems in situations involving equal groups, arrays, and measurement quantities.",
    learning_target: "I can draw what is happening instead of hunting for a keyword.",
    skills: ["Word Problems", "Modeling", "Equations with Unknowns"],
    science_tags: ["dual-coding", "metacognition"],
    match_keys: ["multiplication and division word problems", "equal groups arrays", "symbol for the unknown", "keywords", "within 100"],
  },
  {
    code: "3.OA.A.4",
    name: "The equal sign means balance",
    plain_reading:
      "Determine the unknown whole number in a multiplication or division equation relating three whole numbers.",
    learning_target: "I can solve 8 × ? = 48 because the equal sign means the two sides match.",
    skills: ["Missing Factor", "Inverse Operations", "Equation Balance"],
    science_tags: ["elaboration", "metacognition"],
    match_keys: ["unknown whole number", "missing factor", "inverse", "equal sign", "equation"],
  },
  {
    code: "3.OA.B.5",
    name: "Break a factor apart",
    plain_reading: "Apply properties of operations as strategies to multiply and divide.",
    learning_target: "I can turn 7 × 8 into 7 × 5 plus 7 × 3.",
    skills: ["Distributive Property", "Commutative Property", "Decomposing Factors"],
    science_tags: ["elaboration", "dual-coding"],
    match_keys: ["commutative associative distributive", "properties of operations", "break apart a factor", "strategies"],
  },
  {
    code: "3.OA.B.6",
    name: "Division is a missing factor",
    plain_reading: "Understand division as an unknown-factor problem.",
    learning_target: "I can use a multiplication fact I already know to divide.",
    skills: ["Unknown Factor", "Fact Families", "Inverse Relationship"],
    science_tags: ["retrieval", "elaboration"],
    match_keys: ["division as unknown factor", "fact family", "inverse", "multiplication facts", "divide"],
  },
  {
    code: "3.OA.C.7",
    name: "Facts from anchors, then from memory",
    plain_reading:
      "Fluently multiply and divide within 100. By the end of grade 3, know from memory all products of two one-digit numbers.",
    learning_target: "I can build the hard facts from the ones I already know.",
    skills: ["Fluency", "Derived Facts", "Recall"],
    science_tags: ["retrieval", "spaced"],
    match_keys: ["fluently multiply and divide", "know from memory", "products of one-digit numbers", "anchor facts", "strategies"],
  },
  {
    code: "3.OA.D.9",
    name: "Explain the pattern, not just spot it",
    plain_reading:
      "Identify arithmetic patterns, including patterns in the addition table or multiplication table, and explain them using properties of operations.",
    learning_target: "I can say why the pattern happens, not just that it does.",
    skills: ["Arithmetic Patterns", "Explanation", "Properties"],
    science_tags: ["elaboration", "metacognition"],
    match_keys: ["arithmetic patterns", "multiplication table", "explain using properties", "multiples", "even odd"],
  },
  {
    code: "3.NBT.A.1",
    name: "Round by asking which is closer",
    plain_reading:
      "Use place value understanding to round whole numbers to the nearest 10 or 100.",
    learning_target: "I can put the number on a line and see which benchmark is nearer.",
    skills: ["Rounding", "Number Line", "Place Value"],
    science_tags: ["dual-coding", "metacognition"],
    match_keys: ["round to the nearest 10 or 100", "halfway", "number line", "place value", "estimate"],
  },
  {
    code: "3.NBT.A.3",
    name: "Why the zero appears",
    plain_reading:
      "Multiply one-digit whole numbers by multiples of 10 in the range 10-90 using strategies based on place value.",
    learning_target: "I can explain why 4 × 30 is 120 instead of just adding a zero.",
    skills: ["Multiples of Ten", "Place Value Reasoning", "Pattern Explanation"],
    science_tags: ["elaboration", "dual-coding"],
    match_keys: ["multiply by multiples of 10", "place value strategies", "add a zero", "pattern in the zeros"],
  },
  {
    code: "3.NF.A.2",
    name: "A fraction is a number on the line",
    plain_reading:
      "Understand a fraction as a number on the number line; represent fractions on a number line diagram.",
    learning_target: "I can find where three quarters lives between zero and one.",
    skills: ["Fractions on a Number Line", "Partitioning Intervals", "Unit Fractions"],
    science_tags: ["dual-coding", "metacognition"],
    match_keys: ["fraction as a number", "number line diagram", "partition the interval", "unit fraction", "locate a/b"],
  },
  {
    code: "3.MD.A.2",
    name: "Mass is not size",
    plain_reading:
      "Measure and estimate liquid volumes and masses of objects using grams, kilograms, and liters; solve one-step problems involving these units.",
    learning_target: "I can choose the right unit and know a big thing can be light.",
    skills: ["Mass and Volume", "Metric Units", "Estimation"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["liquid volume", "mass", "grams kilograms liters", "estimate", "one-step problems"],
  },
  {
    code: "3.MD.B.3",
    name: "Scaled graphs, where a square is not one",
    plain_reading:
      "Draw a scaled picture graph and a scaled bar graph to represent a data set with several categories; solve problems using the graphs.",
    learning_target: "I can read the key before I read a bar.",
    skills: ["Scaled Graphs", "Keys", "Two-Step Problems"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["scaled picture graph", "scaled bar graph", "key", "scale greater than one", "two-step problems"],
  },
  {
    code: "3.MD.B.4",
    name: "Measure to the quarter inch",
    plain_reading:
      "Generate measurement data by measuring lengths using rulers marked with halves and fourths of an inch; show the data on a line plot.",
    learning_target: "I can measure to the nearest quarter inch instead of rounding to whole ones.",
    skills: ["Fractional Measurement", "Line Plots", "Precision"],
    science_tags: ["dual-coding", "metacognition"],
    match_keys: ["halves and fourths of an inch", "line plot", "measurement data", "precision", "scale in halves"],
  },
  {
    code: "3.MD.C.5",
    name: "Area is covering",
    plain_reading:
      "Recognize area as an attribute of plane figures and understand concepts of area measurement.",
    learning_target: "I can say whether a question is about covering or about going around.",
    skills: ["Concept of Area", "Unit Square", "Covering Without Gaps"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["area as an attribute", "unit square", "square units", "cover without gaps", "plane figure"],
  },
  {
    code: "3.MD.C.6",
    name: "Count the squares, all of them",
    plain_reading: "Measure areas by counting unit squares.",
    learning_target: "I can count area without skipping or double-counting.",
    skills: ["Counting Unit Squares", "Square Units", "Irregular Shapes"],
    science_tags: ["dual-coding", "metacognition"],
    match_keys: ["measure area", "counting unit squares", "square cm square in", "irregular shapes", "partial squares"],
  },
  {
    code: "3.MD.D.8",
    name: "Perimeter goes around",
    plain_reading:
      "Solve real world and mathematical problems involving perimeters of polygons, including finding an unknown side length.",
    learning_target: "I can find a missing side when I know the perimeter.",
    skills: ["Perimeter", "Unknown Side Length", "Area Versus Perimeter"],
    science_tags: ["dual-coding", "interleaving"],
    match_keys: ["perimeter of polygons", "unknown side length", "same perimeter different areas", "real world problems"],
  },
  {
    code: "3.G.A.2",
    name: "Equal areas, different shapes",
    plain_reading:
      "Partition shapes into parts with equal areas; express the area of each part as a unit fraction of the whole.",
    learning_target: "I can split a shape into equal areas that do not have to look the same.",
    skills: ["Partitioning", "Unit Fractions", "Equal Area"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["partition shapes equal areas", "unit fraction of the whole", "equal area not congruent", "geometry fractions"],
  },
];

const unpacksData = [
  {
    standard_code: "3.OA.A.2",
    verbs: [
      { word: "Interpret", gloss: "say what the division means here" },
      { word: "Represent", gloss: "show it with objects or a drawing" },
    ],
    concepts: ["Sharing division", "Grouping division", "Quotient"],
    vocabulary: [
      { term: "quotient", definition: "the answer to a division" },
      { term: "dividend", definition: "the number being divided" },
      { term: "divisor", definition: "the number you divide by" },
      { term: "share equally", definition: "give out so everyone gets the same" },
    ],
    prior_skills: ["Make equal groups", "Skip count", "Use arrays"],
    prior_standards: [{ code: "3.OA.A.1", text: "Interpret products of whole numbers as equal groups" }],
    future_standards: [{ code: "3.OA.B.6", text: "Understand division as an unknown-factor problem" }],
    challenges: [
      { problem: "Only the sharing meaning is learned, so how many groups of 6 are in 30 is confusing", fix: "Both meanings acted out with the same numbers. 30 divided by 6 is two different stories with one answer" },
      { problem: "Division is done without knowing what was found", fix: "Label the answer — six in each group, or five groups. The number alone is ambiguous" },
    ],
    mastery_statement: "Student can tell whether a division situation is sharing or grouping and represent it.",
    ladder: [
      { name: "I can share equally", descriptor: "Uses partitive division" },
      { name: "I can make groups of", descriptor: "Uses measurement division" },
      { name: "I can tell which is which", descriptor: "Distinguishes the two" },
      { name: "I can draw either one", descriptor: "Represents both meanings" },
    ],
  },
  {
    standard_code: "3.OA.A.3",
    verbs: [
      { word: "Solve", gloss: "the word problem" },
      { word: "Model", gloss: "the situation with a drawing" },
      { word: "Represent", gloss: "the unknown with a symbol" },
    ],
    concepts: ["Equal groups", "Arrays and area", "Unknown position"],
    vocabulary: [
      { term: "equal groups", definition: "groups that are all the same size" },
      { term: "array", definition: "rows and columns" },
      { term: "unknown", definition: "what you are trying to find" },
      { term: "equation", definition: "a number sentence with an equals sign" },
    ],
    prior_skills: ["Multiply within 100", "Interpret division", "Draw equal groups"],
    prior_standards: [{ code: "3.OA.A.2", text: "Interpret whole-number quotients as shares or number of shares" }],
    future_standards: [{ code: "4.OA.A.2", text: "Multiply or divide to solve word problems involving multiplicative comparison" }],
    challenges: [
      { problem: "Keywords are hunted instead of the situation being modeled — each does not always mean multiply", fix: "Two problems containing each, one multiplication and one division. The keyword strategy fails visibly" },
      { problem: "The unknown is always assumed to be at the end", fix: "Vary its position deliberately across problems" },
    ],
    mastery_statement: "Student can model a multiplication or division situation and write an equation for it.",
    ladder: [
      { name: "I can compute", descriptor: "Multiplies and divides" },
      { name: "I can draw the situation", descriptor: "Models the problem" },
      { name: "I can write the equation", descriptor: "Uses a symbol for the unknown" },
      { name: "I can choose the operation", descriptor: "Decides from the situation" },
    ],
  },
  {
    standard_code: "3.OA.A.4",
    verbs: [
      { word: "Determine", gloss: "the unknown number" },
      { word: "Use", gloss: "the inverse relationship" },
      { word: "Check", gloss: "by substituting back" },
    ],
    concepts: ["Equal sign as balance", "Missing factor", "Inverse operations"],
    vocabulary: [
      { term: "unknown", definition: "the number you are looking for" },
      { term: "missing factor", definition: "the number that was multiplied" },
      { term: "inverse", definition: "the operation that undoes it" },
      { term: "equation", definition: "two sides that are equal" },
    ],
    prior_skills: ["Multiply within 100", "Understand fact families", "Read an equation"],
    prior_standards: [{ code: "3.OA.A.3", text: "Use multiplication and division to solve word problems within 100" }],
    future_standards: [{ code: "4.OA.A.1", text: "Interpret a multiplication equation as a comparison" }],
    challenges: [
      { problem: "The equal sign is read as the answer comes next, so 8 x ? = 48 is confusing", fix: "Balance scales. Both sides weigh the same, and the sign says so — not that a result follows" },
      { problem: "The unknown is guessed rather than derived", fix: "Substitute the answer back and check both sides match" },
    ],
    mastery_statement: "Student can find an unknown in any position by treating the equal sign as balance.",
    ladder: [
      { name: "I can solve 6 x 7 = ?", descriptor: "Unknown at the end" },
      { name: "I can solve 8 x ? = 48", descriptor: "Unknown as a factor" },
      { name: "I can solve ? divided by 4 = 5", descriptor: "Unknown in any position" },
      { name: "I can check my answer", descriptor: "Substitutes back" },
    ],
  },
  {
    standard_code: "3.OA.B.5",
    verbs: [
      { word: "Apply", gloss: "the properties as strategies" },
      { word: "Decompose", gloss: "break a factor apart" },
      { word: "Explain", gloss: "why the property works" },
    ],
    concepts: ["Distributive property", "Commutative property", "Decomposing"],
    vocabulary: [
      { term: "commutative", definition: "order does not change the product" },
      { term: "associative", definition: "grouping does not change the product" },
      { term: "distributive", definition: "you can split a factor and add the parts" },
      { term: "decompose", definition: "break into smaller pieces" },
    ],
    prior_skills: ["Multiply within 100", "Know anchor facts", "Use arrays"],
    prior_standards: [{ code: "3.OA.A.4", text: "Determine the unknown whole number in a multiplication or division equation" }],
    future_standards: [{ code: "3.OA.C.7", text: "Fluently multiply and divide within 100" }],
    challenges: [
      { problem: "Commutativity is applied to subtraction and division, so 12 minus 5 is thought to equal 5 minus 12", fix: "Test the claim rather than stating the rule. It fails immediately, and failing is the lesson" },
      { problem: "The distributive property is used as a procedure with no picture behind it", fix: "Cut the array. Seven rows of eight becomes seven of five and seven of three, physically" },
    ],
    mastery_statement: "Student can decompose a factor to simplify a multiplication and explain why it works.",
    ladder: [
      { name: "I know order does not matter", descriptor: "Uses commutativity" },
      { name: "I can break a factor apart", descriptor: "Decomposes" },
      { name: "I can add the parts", descriptor: "Applies distribution" },
      { name: "I can say why it works", descriptor: "Explains the property" },
    ],
  },
  {
    standard_code: "3.OA.B.6",
    verbs: [
      { word: "Rewrite", gloss: "division as a missing factor" },
      { word: "Use", gloss: "the multiplication fact you know" },
    ],
    concepts: ["Unknown factor", "Fact families", "Inverse"],
    vocabulary: [
      { term: "unknown factor", definition: "the number that was multiplied to get there" },
      { term: "inverse", definition: "the operation that undoes another" },
      { term: "fact family", definition: "the facts built from one set of numbers" },
    ],
    prior_skills: ["Know multiplication facts", "Understand division meanings", "Find a missing factor"],
    prior_standards: [{ code: "3.OA.A.4", text: "Determine the unknown whole number in a multiplication or division equation" }],
    future_standards: [{ code: "3.OA.C.7", text: "Fluently multiply and divide within 100" }],
    challenges: [
      { problem: "Division facts are treated as a separate set to memorize", fix: "Every division fact is a multiplication fact already known, asked backwards. There is nothing new to learn" },
      { problem: "The connection is stated but not used under pressure", fix: "Say the multiplication aloud before answering the division" },
    ],
    mastery_statement: "Student can solve a division fact by recalling the related multiplication fact.",
    ladder: [
      { name: "I know my times tables", descriptor: "Recalls multiplication" },
      { name: "I can build a fact family", descriptor: "Relates the four facts" },
      { name: "I can rewrite the division", descriptor: "Expresses as missing factor" },
      { name: "I use it automatically", descriptor: "Applies without prompting" },
    ],
  },
  {
    standard_code: "3.OA.C.7",
    verbs: [
      { word: "Multiply", gloss: "fluently within 100" },
      { word: "Divide", gloss: "fluently within 100" },
      { word: "Know", gloss: "one-digit products from memory" },
    ],
    concepts: ["Anchor facts", "Derived facts", "Fluency versus speed"],
    vocabulary: [
      { term: "fluently", definition: "accurately, efficiently and flexibly" },
      { term: "product", definition: "the answer to a multiplication" },
      { term: "quotient", definition: "the answer to a division" },
      { term: "strategy", definition: "a way of working it out" },
    ],
    prior_skills: ["Use properties as strategies", "Understand division as unknown factor", "Skip count"],
    prior_standards: [{ code: "3.OA.B.5", text: "Apply properties of operations as strategies to multiply and divide" }],
    future_standards: [{ code: "4.NBT.B.5", text: "Multiply a whole number of up to four digits by a one-digit whole number" }],
    challenges: [
      { problem: "Timed drills before strategy work produce anxiety and guessing", fix: "Anchors first — 2s, 5s, 10s — then derive. Speed is the last thing added, not the first" },
      { problem: "Hard facts are practiced at random with no route in", fix: "Six times seven is five sevens plus two sevens. The anchor gives a way in" },
    ],
    mastery_statement: "Student can multiply and divide within 100 fluently, knowing one-digit products from memory.",
    ladder: [
      { name: "I know my anchors", descriptor: "2s, 5s and 10s secure" },
      { name: "I can derive the rest", descriptor: "Builds from anchors" },
      { name: "I can divide too", descriptor: "Uses the inverse" },
      { name: "I know them from memory", descriptor: "Recalls without strategy" },
    ],
  },
  {
    standard_code: "3.OA.D.9",
    verbs: [
      { word: "Identify", gloss: "the pattern" },
      { word: "Explain", gloss: "why it happens" },
      { word: "Predict", gloss: "the next term" },
    ],
    concepts: ["Arithmetic pattern", "Explanation with properties", "Multiples"],
    vocabulary: [
      { term: "pattern", definition: "something that repeats predictably" },
      { term: "multiple", definition: "a number in a times table" },
      { term: "rule", definition: "what the pattern does each time" },
    ],
    prior_skills: ["Skip count", "Know multiplication facts", "Read a table"],
    prior_standards: [{ code: "3.OA.C.7", text: "Fluently multiply and divide within 100" }],
    future_standards: [{ code: "4.OA.C.5", text: "Generate a number or shape pattern that follows a given rule" }],
    challenges: [
      { problem: "The pattern is described but never explained", fix: "They are all even is a description. Because every product has a factor of two is an explanation, and the standard asks for the second" },
      { problem: "Patterns are spotted only in rows, not columns or diagonals", fix: "Look deliberately in all three directions" },
    ],
    mastery_statement: "Student can identify a pattern in a table and explain it using properties of operations.",
    ladder: [
      { name: "I can see a pattern", descriptor: "Notices regularity" },
      { name: "I can describe it", descriptor: "States what happens" },
      { name: "I can predict the next", descriptor: "Extends the pattern" },
      { name: "I can say why", descriptor: "Explains with properties" },
    ],
  },
  {
    standard_code: "3.NBT.A.1",
    verbs: [
      { word: "Round", gloss: "to the nearest 10 or 100" },
      { word: "Locate", gloss: "the number on a line" },
      { word: "Decide", gloss: "which benchmark is closer" },
    ],
    concepts: ["Proximity", "Benchmarks", "The halfway point"],
    vocabulary: [
      { term: "round", definition: "replace with the nearest convenient number" },
      { term: "nearest", definition: "closest to" },
      { term: "halfway", definition: "the same distance from both" },
      { term: "estimate", definition: "a sensible approximate value" },
    ],
    prior_skills: ["Compare three-digit numbers", "Use a number line", "Know place value"],
    prior_standards: [{ code: "2.NBT.A.4", text: "Compare two three-digit numbers using place value" }],
    future_standards: [{ code: "4.NBT.A.3", text: "Use place value understanding to round multi-digit whole numbers" }],
    challenges: [
      { problem: "Five or more raise the score is memorized without any sense of proximity", fix: "A number line every time. Rounding is a question about which benchmark is closer, and the rule is the shortcut that follows" },
      { problem: "The halfway case is treated as arbitrary", fix: "It is genuinely equidistant, so a convention is needed. Say that plainly" },
    ],
    mastery_statement: "Student can round to the nearest 10 or 100 by deciding which benchmark is closer.",
    ladder: [
      { name: "I can find the benchmarks", descriptor: "Identifies the nearest tens" },
      { name: "I can place the number", descriptor: "Locates on the line" },
      { name: "I can see which is closer", descriptor: "Judges proximity" },
      { name: "I can round without the line", descriptor: "Applies with understanding" },
    ],
  },
  {
    standard_code: "3.NBT.A.3",
    verbs: [
      { word: "Multiply", gloss: "by a multiple of ten" },
      { word: "Explain", gloss: "the pattern in the zeros" },
    ],
    concepts: ["Place value scaling", "Multiples of ten", "Why the zero appears"],
    vocabulary: [
      { term: "multiple of ten", definition: "ten, twenty, thirty and so on" },
      { term: "place value", definition: "what each digit is worth" },
      { term: "product", definition: "the answer to a multiplication" },
    ],
    prior_skills: ["Multiply within 100", "Understand place value", "Skip count by tens"],
    prior_standards: [{ code: "3.OA.C.7", text: "Fluently multiply and divide within 100" }],
    future_standards: [{ code: "4.NBT.B.5", text: "Multiply a whole number of up to four digits by a one-digit whole number" }],
    challenges: [
      { problem: "Add a zero is used as a rule with no understanding, and misapplied to decimals later", fix: "Four thirties is four threes of ten — twelve tens, which is a hundred and twenty. The zero is a consequence, not a move" },
      { problem: "The pattern is memorized rather than derived", fix: "Base-ten blocks, so twelve tens can be seen becoming a hundred and twenty" },
    ],
    mastery_statement: "Student can multiply by a multiple of ten and explain the result using place value.",
    ladder: [
      { name: "I know the basic fact", descriptor: "Recalls 4 x 3" },
      { name: "I can find 4 x 30", descriptor: "Multiplies by a multiple of ten" },
      { name: "I can say it in tens", descriptor: "Uses place value language" },
      { name: "I can explain the zero", descriptor: "Justifies the pattern" },
    ],
  },
  {
    standard_code: "3.NF.A.2",
    verbs: [
      { word: "Understand", gloss: "a fraction as a number" },
      { word: "Partition", gloss: "the interval into equal parts" },
      { word: "Locate", gloss: "the fraction on the line" },
    ],
    concepts: ["Fraction as a number", "The whole is 0 to 1", "Intervals not marks"],
    vocabulary: [
      { term: "number line", definition: "a line where equal distances show equal amounts" },
      { term: "interval", definition: "the space between two marks" },
      { term: "unit fraction", definition: "one part of the whole, like one quarter" },
      { term: "point", definition: "the exact place a number sits" },
    ],
    prior_skills: ["Understand unit fractions", "Use a number line for whole numbers", "Partition shapes equally"],
    prior_standards: [{ code: "3.NF.A.1", text: "Understand a fraction 1/b as one part when a whole is partitioned into b equal parts" }],
    future_standards: [{ code: "3.NF.A.3", text: "Explain equivalence of fractions and compare fractions by reasoning about their size" }],
    challenges: [
      { problem: "Tick marks are counted rather than intervals, or the whole line is taken as the whole rather than the segment from 0 to 1", fix: "Mark 0 and 1 heavily first. That segment is the whole, and everything else is inside it" },
      { problem: "Fractions are treated as pieces of pizza rather than as numbers", fix: "Ask which is bigger, and where it sits. Only a number has a place on a line" },
    ],
    mastery_statement: "Student can partition 0 to 1 into equal intervals and locate a fraction as a number.",
    ladder: [
      { name: "I can find whole numbers", descriptor: "Uses a number line" },
      { name: "I can mark 0 and 1", descriptor: "Identifies the whole" },
      { name: "I can split it evenly", descriptor: "Partitions into b parts" },
      { name: "I can place a/b", descriptor: "Locates the fraction" },
    ],
  },
  {
    standard_code: "3.MD.A.2",
    verbs: [
      { word: "Measure", gloss: "mass and liquid volume" },
      { word: "Estimate", gloss: "before measuring" },
      { word: "Solve", gloss: "one-step problems in these units" },
    ],
    concepts: ["Mass versus size", "Metric units", "Estimation"],
    vocabulary: [
      { term: "mass", definition: "how much matter something contains" },
      { term: "liquid volume", definition: "how much liquid something holds" },
      { term: "gram", definition: "a small unit of mass" },
      { term: "kilogram", definition: "a thousand grams" },
      { term: "liter", definition: "a unit of liquid volume" },
    ],
    prior_skills: ["Measure length", "Use standard units", "Estimate with benchmarks"],
    prior_standards: [{ code: "2.MD.A.3", text: "Estimate lengths using standard units" }],
    future_standards: [{ code: "4.MD.A.1", text: "Know relative sizes of measurement units within one system" }],
    challenges: [
      { problem: "Mass is confused with size — a bigger object is assumed heavier", fix: "A large balloon and a small stone on a balance. Size loses, visibly" },
      { problem: "Units are chosen at random", fix: "Benchmarks — a paper clip is about a gram, a bag of sugar a kilogram" },
    ],
    mastery_statement: "Student can measure and estimate mass and volume in metric units and solve problems.",
    ladder: [
      { name: "I can use the tools", descriptor: "Measures with a balance and jug" },
      { name: "I can choose a unit", descriptor: "Selects appropriately" },
      { name: "I can estimate first", descriptor: "Uses benchmarks" },
      { name: "I can solve a problem", descriptor: "Applies to one-step problems" },
    ],
  },
  {
    standard_code: "3.MD.B.3",
    verbs: [
      { word: "Draw", gloss: "a scaled graph" },
      { word: "Use", gloss: "a key with a scale above one" },
      { word: "Solve", gloss: "one- and two-step problems" },
    ],
    concepts: ["Scale above one", "Key", "Two-step problems from data"],
    vocabulary: [
      { term: "scaled graph", definition: "a graph where one square stands for more than one" },
      { term: "key", definition: "what one symbol represents" },
      { term: "scale", definition: "what each step is worth" },
      { term: "category", definition: "one of the groups counted" },
    ],
    prior_skills: ["Draw a bar graph", "Use a simple key", "Add and subtract within 100"],
    prior_standards: [{ code: "2.MD.D.10", text: "Draw a picture graph and a bar graph with up to four categories" }],
    future_standards: [{ code: "4.MD.B.4", text: "Make a line plot to display a data set of measurements in fractions" }],
    challenges: [
      { problem: "Each square or symbol is read as one, ignoring the key", fix: "Ask what one symbol represents before any value is read. Aloud, every time" },
      { problem: "Two-step problems are answered after one step", fix: "Underline both things the question asks for" },
    ],
    mastery_statement: "Student can draw a scaled graph and solve two-step problems using the key.",
    ladder: [
      { name: "I can read a graph", descriptor: "Interprets simple graphs" },
      { name: "I can use the key", descriptor: "Applies a scale above one" },
      { name: "I can draw a scaled graph", descriptor: "Chooses and uses a scale" },
      { name: "I can solve two-step problems", descriptor: "Combines operations from data" },
    ],
  },
  {
    standard_code: "3.MD.B.4",
    verbs: [
      { word: "Measure", gloss: "to the half and quarter inch" },
      { word: "Generate", gloss: "the data yourself" },
      { word: "Show", gloss: "it on a line plot" },
    ],
    concepts: ["Fractional precision", "Line plot scale", "Data shape"],
    vocabulary: [
      { term: "line plot", definition: "a graph where each mark is one measurement" },
      { term: "half inch", definition: "the mark halfway between inches" },
      { term: "quarter inch", definition: "the mark a quarter of the way" },
      { term: "scale", definition: "the numbers along the line" },
    ],
    prior_skills: ["Measure to the whole inch", "Make a line plot", "Understand fractions"],
    prior_standards: [{ code: "2.MD.D.9", text: "Generate measurement data and show it on a line plot" }],
    future_standards: [{ code: "4.MD.B.4", text: "Make a line plot to display measurements in fractions of a unit" }],
    challenges: [
      { problem: "Measurements are rounded to whole inches out of habit, losing the precision the standard requires", fix: "Ban whole-inch answers. If every measurement is a whole number, the ruler was not really read" },
      { problem: "The line plot scale skips the fractional marks", fix: "The scale must show halves and fourths, whether or not data landed there" },
    ],
    mastery_statement: "Student can measure to the quarter inch and plot the data on a fractionally scaled line plot.",
    ladder: [
      { name: "I can measure whole inches", descriptor: "Reads a ruler" },
      { name: "I can find the half", descriptor: "Uses half-inch marks" },
      { name: "I can find the quarter", descriptor: "Uses quarter-inch marks" },
      { name: "I can plot it properly", descriptor: "Scales in halves and fourths" },
    ],
  },
  {
    standard_code: "3.MD.C.5",
    verbs: [
      { word: "Recognize", gloss: "area as an attribute" },
      { word: "Understand", gloss: "the unit square" },
      { word: "Cover", gloss: "without gaps or overlaps" },
    ],
    concepts: ["Area as covering", "Unit square", "Area versus perimeter"],
    vocabulary: [
      { term: "area", definition: "how much surface something covers" },
      { term: "unit square", definition: "a square one unit on each side" },
      { term: "square unit", definition: "the unit area is measured in" },
      { term: "plane figure", definition: "a flat shape" },
    ],
    prior_skills: ["Partition rectangles into squares", "Count by rows", "Use arrays"],
    prior_standards: [{ code: "2.G.A.2", text: "Partition a rectangle into rows and columns of same-size squares" }],
    future_standards: [{ code: "3.MD.C.6", text: "Measure areas by counting unit squares" }],
    challenges: [
      { problem: "Area and perimeter are confused and answers are labeled in the wrong units", fix: "Ask what is being measured — covering or surrounding. Then attach the unit, since square units only make sense for covering" },
      { problem: "Gaps and overlaps are allowed when covering", fix: "Physical tiles. A gap is visible in a way a drawing hides" },
    ],
    mastery_statement: "Student can explain area as covering and measure it in square units.",
    ladder: [
      { name: "I can cover a shape", descriptor: "Uses tiles" },
      { name: "I can cover with no gaps", descriptor: "Understands the requirement" },
      { name: "I can name the unit", descriptor: "Uses square units" },
      { name: "I can tell area from perimeter", descriptor: "Distinguishes the attributes" },
    ],
  },
  {
    standard_code: "3.MD.C.6",
    verbs: [
      { word: "Measure", gloss: "area by counting" },
      { word: "Count", gloss: "unit squares systematically" },
    ],
    concepts: ["Counting systematically", "Square units", "Irregular shapes"],
    vocabulary: [
      { term: "unit square", definition: "the square used to measure area" },
      { term: "square centimeter", definition: "a square one centimeter on each side" },
      { term: "irregular", definition: "not a neat rectangle" },
    ],
    prior_skills: ["Understand area", "Count by rows", "Use a grid"],
    prior_standards: [{ code: "3.MD.C.5", text: "Recognize area as an attribute and understand concepts of area measurement" }],
    future_standards: [{ code: "3.MD.C.7", text: "Relate area to the operations of multiplication and addition" }],
    challenges: [
      { problem: "Only border squares are counted, or squares are skipped and double-counted in irregular shapes", fix: "Cross off each square as it is counted. A system beats care" },
      { problem: "Partial squares are ignored or counted as whole", fix: "Pair them up — two halves make one" },
    ],
    mastery_statement: "Student can find area by counting unit squares systematically, including irregular shapes.",
    ladder: [
      { name: "I can count squares", descriptor: "Counts in a rectangle" },
      { name: "I can count by rows", descriptor: "Uses structure" },
      { name: "I can avoid double-counting", descriptor: "Counts systematically" },
      { name: "I can handle irregular shapes", descriptor: "Manages partial squares" },
    ],
  },
  {
    standard_code: "3.MD.D.8",
    verbs: [
      { word: "Find", gloss: "the perimeter" },
      { word: "Determine", gloss: "an unknown side length" },
      { word: "Compare", gloss: "shapes with equal perimeters" },
    ],
    concepts: ["Perimeter as distance around", "Unknown side", "Same perimeter, different area"],
    vocabulary: [
      { term: "perimeter", definition: "the distance all the way around" },
      { term: "polygon", definition: "a closed shape with straight sides" },
      { term: "side length", definition: "how long one side is" },
      { term: "dimension", definition: "a measurement of a shape" },
    ],
    prior_skills: ["Add within 100", "Measure sides", "Understand area"],
    prior_standards: [{ code: "3.MD.C.5", text: "Recognize area as an attribute of plane figures" }],
    future_standards: [{ code: "4.MD.A.3", text: "Apply the area and perimeter formulas for rectangles" }],
    challenges: [
      { problem: "Perimeter and area are used interchangeably", fix: "Side by side, repeatedly, with units attached. Walking the perimeter and tiling the area are different physical acts" },
      { problem: "The unknown side is guessed rather than derived from the total", fix: "Add the known sides and subtract from the perimeter" },
    ],
    mastery_statement: "Student can find a perimeter, find a missing side, and distinguish perimeter from area.",
    ladder: [
      { name: "I can add the sides", descriptor: "Finds perimeter" },
      { name: "I can measure then add", descriptor: "Works from a shape" },
      { name: "I can find a missing side", descriptor: "Works backwards" },
      { name: "I can compare with area", descriptor: "Distinguishes the two" },
    ],
  },
  {
    standard_code: "3.G.A.2",
    verbs: [
      { word: "Partition", gloss: "into equal areas" },
      { word: "Express", gloss: "each part as a unit fraction" },
    ],
    concepts: ["Equal area", "Unit fraction of a whole", "Equal is not identical"],
    vocabulary: [
      { term: "partition", definition: "split into parts" },
      { term: "equal area", definition: "parts covering the same amount" },
      { term: "unit fraction", definition: "one of the equal parts" },
      { term: "whole", definition: "the shape being divided" },
    ],
    prior_skills: ["Partition rectangles", "Understand unit fractions", "Measure area"],
    prior_standards: [{ code: "3.NF.A.1", text: "Understand a fraction 1/b as one part of a whole partitioned into b equal parts" }],
    future_standards: [{ code: "4.G.A.3", text: "Recognize a line of symmetry for a two-dimensional figure" }],
    challenges: [
      { problem: "Equal parts are assumed to be identical in shape, though the requirement is equal area", fix: "A square split into four equal areas that look nothing alike. Count the squares — they match" },
      { problem: "The whole is lost track of", fix: "Name the whole out loud before naming any fraction" },
    ],
    mastery_statement: "Student can partition a shape into equal areas and name each as a unit fraction.",
    ladder: [
      { name: "I can split a shape", descriptor: "Partitions" },
      { name: "I can make the parts equal", descriptor: "Achieves equal area" },
      { name: "I can name the fraction", descriptor: "Expresses as a unit fraction" },
      { name: "I know equal is not identical", descriptor: "Separates area from congruence" },
    ],
  },
];

const blueprintsData = [
  {
    standard_code: "3.OA.A.2",
    title: "How Many Groups, or How Many Each",
    badge: "Grade 3",
    route_name: "Concrete-Representational-Abstract",
    route_line: "Act out both stories → See one answer → Label what you found",
    success_criteria: ["Interprets sharing division", "Interprets grouping division", "Says which the situation is"],
    steps: [
      { name: "Retrieve Equal Groups", minutes: 5, body: "From the multiplication work. Division undoes it.", science_tag: "retrieval" },
      { name: "Two Stories, One Number Sentence", minutes: 14, body: "Thirty biscuits shared between six children, and thirty biscuits in bags of six. Both are 30 divided by 6, and they are not the same question.", science_tag: "dual-coding" },
      { name: "Act Them Out", minutes: 12, body: "Counters, physically. Sharing deals one at a time; grouping scoops six at a time. The hands are different.", science_tag: "dual-coding" },
      { name: "Label the Answer", minutes: 10, body: "Five each, or five bags. Five on its own does not say which was found.", science_tag: "metacognition" },
      { name: "Sort the Story Type", minutes: 12, body: "Problems sorted into sharing or grouping before any solving happens.", science_tag: "interleaving" },
      { name: "Draw Either One", minutes: 10, body: "Given a story, produce the matching picture.", science_tag: "dual-coding" },
      { name: "Write Your Own", minutes: 4, body: "One of each, using the same numbers.", science_tag: "elaboration" },
    ],
    ef_supports: ["Counters", "Two-story comparison sheet", "Labelling frame", "Sorting mat"],
    tech: "Counters and cups",
    tech_purpose: "Dealing and scooping are different actions, and that is the point",
    ai_prompts: ["Generate sharing and grouping problems with identical numbers", "Write division stories for sorting"],
    assessment: ["Ask which meaning the problem used", "Check answers are labeled", "Watch the acting out"],
    why_it_works: ["The same numbers in two stories isolates the meaning as the difference", "Dealing and scooping are physically distinct, so the distinction is felt", "Labelling the answer forces the meaning to be carried through", "Writing both from one set of numbers proves the distinction was understood"],
  },
  {
    standard_code: "3.OA.A.3",
    title: "Each Does Not Always Mean Multiply",
    badge: "Grade 3",
    route_name: "Strategy Instruction",
    route_line: "Draw the situation → Choose the operation → Write the equation",
    success_criteria: ["Models the situation", "Chooses the right operation", "Uses a symbol for the unknown"],
    steps: [
      { name: "Retrieve Both Operations", minutes: 5, body: "What multiplication does, what division does.", science_tag: "retrieval" },
      { name: "Two Problems With Each", minutes: 14, body: "One multiplies, one divides. The keyword strategy fails in front of them, which is more convincing than being told not to use it.", science_tag: "elaboration" },
      { name: "Draw Before Deciding", minutes: 12, body: "The picture comes before the operation. Modeling the situation is the strategy.", science_tag: "dual-coding" },
      { name: "Where Is the Unknown", minutes: 10, body: "Marked with a box on the drawing first.", science_tag: "metacognition" },
      { name: "Write the Equation", minutes: 10, body: "Matching the drawing, box included.", science_tag: "elaboration" },
      { name: "Move the Unknown", minutes: 10, body: "The same story with a different quantity missing.", science_tag: "interleaving" },
      { name: "Area Situations Too", minutes: 4, body: "Measurement quantities, which the standard names.", science_tag: "interleaving" },
    ],
    ef_supports: ["Draw-first rule", "Unknown box", "Keyword failure pair", "Varied unknown position"],
    tech: "Squared paper for arrays and area",
    tech_purpose: "Equal groups, arrays and area all need drawing",
    ai_prompts: ["Generate problem pairs sharing a keyword but needing different operations", "Write problems with the unknown in each position"],
    assessment: ["Check a drawing precedes the equation", "Vary the unknown position", "Watch for keyword hunting"],
    why_it_works: ["Two problems with the same keyword breaks the strategy visibly", "Drawing first makes the situation, not the wording, decide the operation", "Marking the unknown on the drawing links the picture to the equation", "Moving the unknown prevents a memorized equation shape"],
  },
  {
    standard_code: "3.OA.A.4",
    title: "Both Sides Weigh the Same",
    badge: "Grade 3",
    route_name: "Concrete-Representational-Abstract",
    route_line: "Balance the scale → Find what is missing → Check both sides",
    success_criteria: ["Treats the equal sign as balance", "Finds the unknown in any position", "Checks by substituting"],
    steps: [
      { name: "Retrieve Fact Families", minutes: 5, body: "Four facts from three numbers.", science_tag: "retrieval" },
      { name: "The Answer Comes Next", minutes: 10, body: "Named as the misreading it is. The equal sign is not an arrow.", science_tag: "metacognition" },
      { name: "Balance Scales", minutes: 14, body: "Both sides weigh the same. Physical before symbolic, because the symbol has been misread for two years.", science_tag: "dual-coding" },
      { name: "Cover a Number", minutes: 12, body: "In a true equation, cover one number. What must it be for the balance to hold?", science_tag: "elaboration" },
      { name: "Unknown Anywhere", minutes: 12, body: "Start, middle, end. All the same job.", science_tag: "interleaving" },
      { name: "Substitute and Check", minutes: 8, body: "Put the answer back and confirm both sides match.", science_tag: "metacognition" },
      { name: "True or False", minutes: 4, body: "Equations to judge rather than solve. 4 x 6 = 3 x 8 is true.", science_tag: "elaboration" },
    ],
    ef_supports: ["Balance scales", "Cover-a-number routine", "Varied unknown positions", "True-or-false equation set"],
    tech: "Pan balances and cubes",
    tech_purpose: "The equal sign has to be re-taught physically",
    ai_prompts: ["Generate equations with the unknown in each position", "Write true-or-false equations with operations on both sides"],
    assessment: ["Test the unknown in every position", "Check substitution", "Use true-or-false items"],
    why_it_works: ["A balance is the meaning of the equal sign, and the symbol has usually been taught as an arrow", "Covering a number in a true equation keeps the balance intact", "True-or-false items cannot be answered by computing left to right", "Substituting back is a check that uses the same understanding"],
  },
  {
    standard_code: "3.OA.B.5",
    title: "Cut the Array",
    badge: "Grade 3",
    route_name: "Concrete-Representational-Abstract",
    route_line: "Build the array → Cut it → Add the parts",
    success_criteria: ["Decomposes a factor", "Applies the distributive property", "Explains why it works"],
    steps: [
      { name: "Retrieve Anchor Facts", minutes: 5, body: "Fives and twos, fast.", science_tag: "retrieval" },
      { name: "Does It Work for Subtraction", minutes: 10, body: "Twelve minus five against five minus twelve. Tested, not asserted. It fails, and that is the answer.", science_tag: "elaboration" },
      { name: "Build Seven Eights", minutes: 12, body: "As an array, physically.", science_tag: "dual-coding" },
      { name: "Cut It", minutes: 14, body: "Seven fives and seven threes. The scissors are the distributive property.", science_tag: "dual-coding" },
      { name: "Add the Parts", minutes: 10, body: "Thirty-five and twenty-one. The same fifty-six.", science_tag: "elaboration" },
      { name: "Choose Your Cut", minutes: 10, body: "Where would you split it, and why there?", science_tag: "metacognition" },
      { name: "Explain to a Partner", minutes: 4, body: "Why cutting is allowed.", science_tag: "collaborative" },
    ],
    ef_supports: ["Array paper and scissors", "Anchor fact reference", "Cut-choice prompt", "Property test cards"],
    tech: "Squared paper arrays that can be cut",
    tech_purpose: "Cutting is the property made physical",
    ai_prompts: ["Generate arrays for decomposition", "Write property claims to test, true and false"],
    assessment: ["Check the cut is at a useful place", "Ask why it works", "Test commutativity claims"],
    why_it_works: ["Cutting an array is the distributive property rather than an illustration of it", "Testing commutativity on subtraction lets it fail rather than forbidding it", "Choosing where to cut makes it a strategy rather than a procedure", "Explaining to a partner requires the reason, not the steps"],
  },
  {
    standard_code: "3.OA.B.6",
    title: "You Already Know the Division Facts",
    badge: "Grade 3",
    route_name: "Strategy Instruction",
    route_line: "See the division → Say the multiplication → Read off the answer",
    success_criteria: ["Rewrites division as a missing factor", "Uses known multiplication facts", "Explains the connection"],
    steps: [
      { name: "Retrieve Times Tables", minutes: 5, body: "The facts already held.", science_tag: "retrieval" },
      { name: "Nothing New to Learn", minutes: 10, body: "Every division fact is a multiplication fact asked backwards. There is no second set.", science_tag: "elaboration" },
      { name: "Build Fact Families", minutes: 12, body: "Three numbers, four facts. Two multiplications, two divisions.", science_tag: "dual-coding" },
      { name: "Say the Multiplication First", minutes: 14, body: "Aloud, before answering the division. The route made habitual.", science_tag: "retrieval" },
      { name: "Missing Factor Notation", minutes: 10, body: "56 divided by 7 becomes 7 times what is 56.", science_tag: "elaboration" },
      { name: "Mixed Practice", minutes: 10, body: "Multiplication and division interleaved, unlabelled.", science_tag: "interleaving" },
      { name: "Yesterday's Facts", minutes: 4, body: "Recalled cold.", science_tag: "spaced" },
    ],
    ef_supports: ["Fact family triangles", "Say-it-first routine", "Missing factor frame", "Mixed practice sets"],
    tech: "Fact family triangle cards",
    tech_purpose: "One card holding four facts shows the relationship",
    ai_prompts: ["Generate fact families within 100", "Write mixed multiplication and division sets"],
    assessment: ["Listen for the multiplication being said", "Check speed on division matches multiplication", "Use mixed sets"],
    why_it_works: ["A triangle card holds all four facts, so the relationship is the card", "Saying the multiplication aloud makes the route automatic", "Naming that there is nothing new removes the sense of a second mountain", "Mixed practice stops the two being kept in separate boxes"],
  },
  {
    standard_code: "3.OA.C.7",
    title: "Anchors First, Speed Last",
    badge: "Grade 3",
    route_name: "Routine and Practice",
    route_line: "Secure the anchors → Derive the hard ones → Then go faster",
    success_criteria: ["Knows anchor facts", "Derives harder facts", "Recalls from memory by year end"],
    steps: [
      { name: "Retrieve the Anchors", minutes: 6, body: "Twos, fives, tens. These have to be automatic before anything is built on them.", science_tag: "retrieval" },
      { name: "Drills Before Strategy", minutes: 8, body: "Named as the mistake it is. Timing a fact nobody has a route to produces guessing and anxiety.", science_tag: "metacognition" },
      { name: "Six Sevens From Five Sevens", minutes: 14, body: "Thirty-five plus seven. The anchor gives a way in.", science_tag: "elaboration" },
      { name: "Which Anchor Helps", minutes: 12, body: "For each hard fact, name the route before answering.", science_tag: "metacognition" },
      { name: "Then Add Speed", minutes: 12, body: "Only once every fact has a route. Speed last.", science_tag: "spaced" },
      { name: "Division Alongside", minutes: 8, body: "Every fact practiced both ways.", science_tag: "interleaving" },
      { name: "Daily Short Round", minutes: 4, body: "Two minutes, mixed, every day.", science_tag: "spaced" },
    ],
    ef_supports: ["Anchor fact wall", "Route-naming prompt", "Daily short round", "Both-ways practice"],
    tech: "Fact cards and a timer, introduced late",
    tech_purpose: "The timer arrives after the routes, not before",
    ai_prompts: ["Generate derivation routes from anchor facts", "Write mixed fluency sets"],
    assessment: ["Check every hard fact has a route", "Introduce timing only after that", "Test division alongside"],
    why_it_works: ["Anchors give every hard fact a way in, so nothing is bare memorization", "Naming the route before answering makes the strategy visible and coachable", "Adding speed last means fluency is built on understanding rather than fear", "Daily short rounds beat weekly long ones for retention"],
  },
  {
    standard_code: "3.OA.D.9",
    title: "Because Every Product Has a Two",
    badge: "Grade 3",
    route_name: "Strategy Instruction",
    route_line: "Spot the pattern → Predict the next → Say why it happens",
    success_criteria: ["Identifies patterns in tables", "Predicts the next term", "Explains using properties"],
    steps: [
      { name: "Retrieve Multiples", minutes: 5, body: "What a multiple is, and how to spot one.", science_tag: "retrieval" },
      { name: "They Are All Even", minutes: 10, body: "A description, not an explanation. The standard asks for the second, and naming the difference is the lesson.", science_tag: "metacognition" },
      { name: "Because There Is a Two", minutes: 14, body: "Every product in the fours row has a factor of two, so every one is even. That is an explanation.", science_tag: "elaboration" },
      { name: "Rows, Columns, Diagonals", minutes: 12, body: "Patterns hide in all three directions, and only rows usually get looked at.", science_tag: "dual-coding" },
      { name: "Predict the Next", minutes: 10, body: "Then check. A pattern that predicts is a real one.", science_tag: "metacognition" },
      { name: "Find Your Own", minutes: 10, body: "In the multiplication table, with an explanation attached.", science_tag: "elaboration" },
      { name: "Yesterday's Pattern", minutes: 4, body: "Re-explained from memory.", science_tag: "spaced" },
    ],
    ef_supports: ["Multiplication table grids", "Describe-or-explain sorting", "Three-direction prompt", "Prediction check"],
    tech: "Printed multiplication tables to mark up",
    tech_purpose: "Patterns need a grid that can be colored",
    ai_prompts: ["Generate table patterns with property-based explanations", "Write descriptions and explanations for sorting"],
    assessment: ["Reject descriptions offered as explanations", "Check predictions", "Look for column and diagonal patterns"],
    why_it_works: ["Separating description from explanation names exactly what the standard asks for", "A factor of two is an explanation a child can give and check", "Looking in three directions finds patterns rows alone never show", "Prediction is the test of whether a pattern was understood"],
  },
  {
    standard_code: "3.NBT.A.1",
    title: "Which One Is Closer",
    badge: "Grade 3",
    route_name: "Multiple Representations",
    route_line: "Find the two benchmarks → Place the number → Pick the nearer",
    success_criteria: ["Rounds to 10 and 100", "Uses proximity reasoning", "Handles the halfway case"],
    steps: [
      { name: "Retrieve Place Value", minutes: 5, body: "Tens and hundreds, named.", science_tag: "retrieval" },
      { name: "Five or More Raise the Score", minutes: 10, body: "Said aloud, then set aside. It is a shortcut for something, and the something is what is being taught.", science_tag: "metacognition" },
      { name: "The Two Neighbors", minutes: 12, body: "Which tens does this number sit between? Both written down before anything else.", science_tag: "dual-coding" },
      { name: "Put It on the Line", minutes: 14, body: "And look. Closer to one end or the other — rounding is a question about distance.", science_tag: "dual-coding" },
      { name: "The Halfway Case", minutes: 10, body: "Genuinely equidistant, so a convention is needed. Say that rather than pretending it is obvious.", science_tag: "elaboration" },
      { name: "Round to Hundreds", minutes: 10, body: "Same routine, bigger benchmarks.", science_tag: "interleaving" },
      { name: "Without the Line", minutes: 4, body: "Once the reasoning holds, the shortcut is safe.", science_tag: "spaced" },
    ],
    ef_supports: ["Blank number lines", "Two-neighbors box", "Halfway discussion", "Hundreds and tens practice"],
    tech: "Printed and blank number lines",
    tech_purpose: "Proximity has to be seen before it is a rule",
    ai_prompts: ["Generate rounding items including halfway cases", "Write numbers requiring hundreds rounding"],
    assessment: ["Ask which benchmarks it sits between", "Check the halfway reasoning", "Test without the line last"],
    why_it_works: ["Writing both neighbors first turns rounding into a comparison", "A number line makes closeness visible rather than procedural", "Naming halfway as a convention is honest and stops it seeming arbitrary", "The rule is safe once it is a shortcut for reasoning that exists"],
  },
  {
    standard_code: "3.NBT.A.3",
    title: "Twelve Tens Is a Hundred and Twenty",
    badge: "Grade 3",
    route_name: "Concrete-Representational-Abstract",
    route_line: "Build it in tens → Count the tens → Say why the zero appears",
    success_criteria: ["Multiplies by multiples of ten", "Uses place value reasoning", "Explains the zero"],
    steps: [
      { name: "Retrieve the Basic Fact", minutes: 5, body: "Four threes, before four thirties.", science_tag: "retrieval" },
      { name: "Add a Zero", minutes: 10, body: "Said aloud, then examined. It works here and breaks later, and knowing why is the difference.", science_tag: "metacognition" },
      { name: "Build It in Tens", minutes: 14, body: "Four groups of three tens. Twelve tens, in blocks, on the desk.", science_tag: "dual-coding" },
      { name: "Twelve Tens Is What", minutes: 12, body: "A hundred and twenty. The regrouping is where the zero comes from.", science_tag: "elaboration" },
      { name: "Say It in Tens", minutes: 10, body: "Four thirties is twelve tens. The language carries the reasoning.", science_tag: "elaboration" },
      { name: "Explain the Zero", minutes: 8, body: "In writing. If it cannot be explained, it is still just a rule.", science_tag: "metacognition" },
      { name: "Mixed Practice", minutes: 4, body: "With and without multiples of ten.", science_tag: "interleaving" },
    ],
    ef_supports: ["Base-ten blocks", "Say-it-in-tens frame", "Written explanation", "Mixed practice"],
    tech: "Base-ten blocks",
    tech_purpose: "Twelve tens becoming a hundred and twenty has to be seen",
    ai_prompts: ["Generate one-digit by multiple-of-ten items", "Write explanation prompts for the zero pattern"],
    assessment: ["Ask for the explanation, not just the answer", "Check tens language", "Watch for the rule without reasoning"],
    why_it_works: ["Building twelve tens shows the regrouping the zero records", "Saying it in tens keeps place value in the language", "Examining the rule rather than banning it keeps a useful shortcut", "A written explanation is where the difference between rule and reasoning shows"],
  },
  {
    standard_code: "3.NF.A.2",
    title: "Zero to One Is the Whole",
    badge: "Grade 3",
    route_name: "Multiple Representations",
    route_line: "Mark 0 and 1 → Split the gap evenly → Land on the fraction",
    success_criteria: ["Identifies the whole as 0 to 1", "Partitions into equal intervals", "Locates a fraction"],
    steps: [
      { name: "Retrieve Unit Fractions", minutes: 5, body: "One part of a whole split into equal parts.", science_tag: "retrieval" },
      { name: "Where Is the Whole", minutes: 12, body: "Not the line — the segment from zero to one. The commonest error, addressed first.", science_tag: "metacognition" },
      { name: "Mark Zero and One Heavily", minutes: 10, body: "Before anything else. Everything happens inside that.", science_tag: "dual-coding" },
      { name: "Fold to Partition", minutes: 12, body: "A paper strip folded into four. Folding cannot produce unequal parts.", science_tag: "dual-coding" },
      { name: "Spaces, Not Marks", minutes: 12, body: "Three quarters is three intervals along, not the third tick.", science_tag: "metacognition" },
      { name: "Beyond One", minutes: 10, body: "Five quarters. The whole stays the same size and the number keeps going.", science_tag: "elaboration" },
      { name: "Which Is Bigger", minutes: 4, body: "Two fractions placed on one line. Only numbers can be compared this way.", science_tag: "elaboration" },
    ],
    ef_supports: ["Paper strips for folding", "Heavy 0 and 1 marking", "Interval counting prompt", "Beyond-one lines"],
    tech: "Paper strips and blank number lines",
    tech_purpose: "Folding guarantees equal intervals",
    ai_prompts: ["Generate number lines requiring fractional placement", "Write comparison items using one line"],
    assessment: ["Ask where the whole is", "Watch for tick-mark counting", "Check placement beyond one"],
    why_it_works: ["Naming the whole as the segment addresses the deeper error first", "Folding makes equal partitioning physical rather than careful", "Counting intervals rather than marks fixes the off-by-one directly", "Going beyond one proves a fraction is a number, not a piece of something"],
  },
  {
    standard_code: "3.MD.A.2",
    title: "Big Does Not Mean Heavy",
    badge: "Grade 3",
    route_name: "Concrete Practice",
    route_line: "Estimate → Measure → Explain the surprise",
    success_criteria: ["Measures mass and volume", "Chooses appropriate units", "Separates mass from size"],
    steps: [
      { name: "Retrieve the Units", minutes: 5, body: "Gram, kilogram, liter, and what each suits.", science_tag: "retrieval" },
      { name: "Balloon Against Stone", minutes: 12, body: "A large balloon and a small stone on a balance. Size loses, and the misconception dies visibly.", science_tag: "dual-coding" },
      { name: "Benchmarks", minutes: 10, body: "A paper clip is about a gram, a bag of sugar a kilogram, a bottle a liter.", science_tag: "retrieval" },
      { name: "Estimate First", minutes: 12, body: "Written down, then measured. Committing makes it an estimate.", science_tag: "metacognition" },
      { name: "Which Unit", minutes: 10, body: "Grams or kilograms? Chosen with a reason.", science_tag: "elaboration" },
      { name: "One-Step Problems", minutes: 10, body: "Using the measurements just taken.", science_tag: "interleaving" },
      { name: "Yesterday's Objects", minutes: 4, body: "Re-estimated from memory.", science_tag: "spaced" },
    ],
    ef_supports: ["Balance scales and measuring jugs", "Benchmark card", "Estimate-then-measure sheet", "Unit choice prompt"],
    tech: "Balances, jugs, and objects of misleading size",
    tech_purpose: "The balloon and stone are the whole argument",
    ai_prompts: ["Generate object sets where size misleads about mass", "Write one-step mass and volume problems"],
    assessment: ["Check estimates precede measuring", "Ask why a unit was chosen", "Watch for size-based reasoning"],
    why_it_works: ["A large light object and a small heavy one settles the misconception in one demonstration", "Benchmarks turn guessing into estimating", "Choosing a unit with a reason makes it a judgment", "Solving problems with their own measurements keeps it concrete"],
  },
  {
    standard_code: "3.MD.B.3",
    title: "What Does One Symbol Mean",
    badge: "Grade 3",
    route_name: "Multiple Representations",
    route_line: "Read the key aloud → Then read the graph → Then answer",
    success_criteria: ["Uses a key with a scale above one", "Draws a scaled graph", "Solves two-step problems"],
    steps: [
      { name: "Retrieve Graph Parts", minutes: 4, body: "Title, categories, key, scale.", science_tag: "retrieval" },
      { name: "The Same Graph, Two Keys", minutes: 12, body: "Identical bars, one symbol worth one, then worth five. Different answers, same picture.", science_tag: "elaboration" },
      { name: "Key Aloud, Every Time", minutes: 10, body: "Before a single value is read. Said, not assumed.", science_tag: "metacognition" },
      { name: "Choose Your Own Scale", minutes: 12, body: "Given data, pick a scale that fits the page. A decision with consequences.", science_tag: "dual-coding" },
      { name: "Draw It", minutes: 12, body: "Several categories, with a key that is genuinely needed.", science_tag: "dual-coding" },
      { name: "Two-Step Questions", minutes: 10, body: "How many more, then how many altogether. Both parts underlined first.", science_tag: "interleaving" },
      { name: "Yesterday's Graph", minutes: 4, body: "New questions on the same data.", science_tag: "spaced" },
    ],
    ef_supports: ["Two-key comparison pair", "Key-aloud routine", "Scale choice prompt", "Two-step underlining"],
    tech: "Squared paper and printed graphs",
    tech_purpose: "Drawing and reading are separate skills",
    ai_prompts: ["Generate identical graphs with different keys", "Write two-step questions from graph data"],
    assessment: ["Check the key is read first", "Confirm the scale suits the data", "Test two-step questions"],
    why_it_works: ["Identical bars with two keys makes assuming one-per-symbol visibly wrong", "Reading the key aloud is a habit that outlasts the lesson", "Choosing a scale makes it a decision rather than a given", "Underlining both parts is what catches the half-answered two-step question"],
  },
  {
    standard_code: "3.MD.B.4",
    title: "No Whole-Inch Answers",
    badge: "Grade 3",
    route_name: "Concrete Practice",
    route_line: "Find the quarter marks → Measure honestly → Plot in fourths",
    success_criteria: ["Measures to the quarter inch", "Plots on a fractional scale", "Reads the shape of the data"],
    steps: [
      { name: "Retrieve Fractions", minutes: 5, body: "Halves and quarters, from the fraction work.", science_tag: "retrieval" },
      { name: "Find the Marks", minutes: 10, body: "On the ruler itself. Which line is the half, which the quarter?", science_tag: "dual-coding" },
      { name: "Whole Inches Banned", minutes: 12, body: "If every measurement is a whole number, the ruler was not really read. Honesty about precision.", science_tag: "metacognition" },
      { name: "Measure Ten Things", minutes: 12, body: "To the nearest quarter, recorded as fractions.", science_tag: "dual-coding" },
      { name: "Scale in Fourths", minutes: 12, body: "Every quarter mark on the plot, whether or not data landed there.", science_tag: "elaboration" },
      { name: "What Does the Shape Say", minutes: 8, body: "Where do most sit? Reading the plot, not just making it.", science_tag: "elaboration" },
      { name: "New Objects, Same Plot", minutes: 4, body: "Added later in the week.", science_tag: "spaced" },
    ],
    ef_supports: ["Rulers with clear quarter marks", "No-whole-inches rule", "Fourths scale template", "Shape-reading questions"],
    tech: "Inch rulers marked in quarters",
    tech_purpose: "The precision the standard asks for needs the marks",
    ai_prompts: ["Generate objects with fractional lengths", "Write shape-reading questions for line plots"],
    assessment: ["Check for rounding to whole inches", "Confirm the scale shows fourths", "Ask what the shape shows"],
    why_it_works: ["Banning whole-inch answers exposes rounding out of habit", "Finding the marks on the ruler first makes the precision reachable", "A scale showing every fourth keeps the distribution honest", "Reading the shape is the reason for making the plot"],
  },
  {
    standard_code: "3.MD.C.5",
    title: "Covering or Going Around",
    badge: "Grade 3",
    route_name: "Concrete Practice",
    route_line: "Tile the shape → Name the unit → Say which question it answers",
    success_criteria: ["Explains area as covering", "Uses square units", "Distinguishes area from perimeter"],
    steps: [
      { name: "Retrieve Partitioning", minutes: 5, body: "Same-size squares, from grade 2.", science_tag: "retrieval" },
      { name: "Walk It or Tile It", minutes: 12, body: "Perimeter is walked around the edge, area is tiled across the middle. Two different physical acts.", science_tag: "dual-coding" },
      { name: "Tiles, No Gaps", minutes: 12, body: "Physical tiles. A gap is visible where a drawing hides it.", science_tag: "dual-coding" },
      { name: "Why Squares", minutes: 10, body: "Circles leave gaps, triangles are awkward. Squares tile perfectly, and that is why they are the unit.", science_tag: "elaboration" },
      { name: "Square Units", minutes: 10, body: "The unit says which question was answered. Centimeters or square centimeters.", science_tag: "metacognition" },
      { name: "Which Am I Being Asked", minutes: 10, body: "Problems sorted into covering or surrounding before solving.", science_tag: "interleaving" },
      { name: "Label Every Answer", minutes: 4, body: "An unlabelled area answer is incomplete.", science_tag: "elaboration" },
    ],
    ef_supports: ["Square tiles", "Walk-it-or-tile-it routine", "Unit labelling rule", "Covering-or-surrounding sorting"],
    tech: "Square tiles and shapes to cover",
    tech_purpose: "Gaps and overlaps have to be physically possible to be ruled out",
    ai_prompts: ["Generate problems mixing area and perimeter", "Write shapes for tiling"],
    assessment: ["Check units are square units", "Ask which question is being answered", "Watch for gaps when tiling"],
    why_it_works: ["Walking and tiling are different actions, so the concepts separate physically", "Asking why squares explains the unit rather than assuming it", "The unit label is where the confusion becomes visible", "Sorting before solving makes the distinction the first move"],
  },
  {
    standard_code: "3.MD.C.6",
    title: "Cross Off Every Square",
    badge: "Grade 3",
    route_name: "Concrete Practice",
    route_line: "Count systematically → Cross as you go → Pair the partials",
    success_criteria: ["Counts unit squares accurately", "Uses a system", "Handles irregular shapes"],
    steps: [
      { name: "Retrieve Square Units", minutes: 4, body: "What area is measured in.", science_tag: "retrieval" },
      { name: "Border Only", minutes: 10, body: "A common miscount, demonstrated. Counting the edge is perimeter, not area.", science_tag: "metacognition" },
      { name: "Cross Off As You Count", minutes: 14, body: "A system beats care. Double-counting becomes impossible rather than unlikely.", science_tag: "dual-coding" },
      { name: "Count by Rows", minutes: 10, body: "In a rectangle, the structure is faster and safer.", science_tag: "dual-coding" },
      { name: "Irregular Shapes", minutes: 12, body: "No neat rows. The crossing-off system carries it.", science_tag: "interleaving" },
      { name: "Pair the Halves", minutes: 10, body: "Two half squares make one. Partial squares handled rather than ignored.", science_tag: "elaboration" },
      { name: "Different Units", minutes: 4, body: "Square centimeters and square inches on the same shape.", science_tag: "interleaving" },
    ],
    ef_supports: ["Cross-off routine", "Grid overlays", "Irregular shape set", "Half-pairing prompt"],
    tech: "Transparent grid overlays",
    tech_purpose: "Irregular shapes need a grid laid over them",
    ai_prompts: ["Generate irregular shapes on grids", "Write area problems with partial squares"],
    assessment: ["Watch for border-only counting", "Check the system is used", "Confirm partials are paired"],
    why_it_works: ["Crossing off makes double-counting structurally impossible", "Demonstrating the border miscount names it before it happens", "Rows are faster where they exist, and the system covers where they do not", "Pairing halves gives partial squares a rule rather than a guess"],
  },
  {
    standard_code: "3.MD.D.8",
    title: "Same Perimeter, Different Area",
    badge: "Grade 3",
    route_name: "Concrete Practice",
    route_line: "Measure around → Find the missing side → Compare with area",
    success_criteria: ["Finds perimeter", "Finds an unknown side", "Distinguishes perimeter from area"],
    steps: [
      { name: "Retrieve Area", minutes: 5, body: "Covering, in square units.", science_tag: "retrieval" },
      { name: "Same Perimeter, Different Area", minutes: 14, body: "Rectangles all with perimeter twenty. Their areas differ wildly, which proves the two are independent.", science_tag: "dual-coding" },
      { name: "Walk the Perimeter", minutes: 10, body: "String around the edge, then measured. Perimeter is a length.", science_tag: "dual-coding" },
      { name: "Units Attached", minutes: 10, body: "Centimeters for perimeter, square centimeters for area. The units keep them apart.", science_tag: "metacognition" },
      { name: "Find the Missing Side", minutes: 12, body: "Add the known sides, subtract from the perimeter.", science_tag: "elaboration" },
      { name: "Mixed Problems", minutes: 10, body: "Area and perimeter interleaved, unlabelled.", science_tag: "interleaving" },
      { name: "Yesterday's Shapes", minutes: 4, body: "Both measures found again.", science_tag: "spaced" },
    ],
    ef_supports: ["String for perimeter", "Same-perimeter rectangle set", "Unit labelling rule", "Mixed unlabelled problems"],
    tech: "String, rulers and squared paper",
    tech_purpose: "String makes perimeter a length you can hold",
    ai_prompts: ["Generate rectangles with equal perimeters and different areas", "Write missing side problems"],
    assessment: ["Check units distinguish the two", "Test the missing side method", "Use unlabelled mixed problems"],
    why_it_works: ["Equal perimeters with different areas proves the two measure different things", "String turns perimeter into a length that can be handled", "Units are the fastest diagnostic for which was calculated", "Unlabelled mixed problems stop the topic cueing the method"],
  },
  {
    standard_code: "3.G.A.2",
    title: "Equal Area, Not Equal Shape",
    badge: "Grade 3",
    route_name: "Concrete-Representational-Abstract",
    route_line: "Split the shape → Check the areas match → Name the fraction",
    success_criteria: ["Partitions into equal areas", "Names each as a unit fraction", "Accepts unlike shapes"],
    steps: [
      { name: "Retrieve Unit Fractions", minutes: 5, body: "One part of a whole split equally.", science_tag: "retrieval" },
      { name: "Four Quarters That Look Different", minutes: 14, body: "A square split into four equal areas of unlike shape. Count the squares — they match. Equal area is the requirement, not congruence.", science_tag: "dual-coding" },
      { name: "Name the Whole First", minutes: 10, body: "Before naming any fraction. A quarter of what?", science_tag: "metacognition" },
      { name: "Count to Check", minutes: 12, body: "Equal area is verified by counting squares, not by looking.", science_tag: "elaboration" },
      { name: "Split It Yourself", minutes: 12, body: "Into equal areas, at least one of them an odd shape.", science_tag: "elaboration" },
      { name: "Name Each Part", minutes: 8, body: "One fourth of the whole, written as a fraction.", science_tag: "interleaving" },
      { name: "Is This Equal", minutes: 4, body: "Partitions to judge, some equal and some not.", science_tag: "metacognition" },
    ],
    ef_supports: ["Squared paper shapes", "Unlike-quarters example", "Name-the-whole prompt", "Judge-the-partition set"],
    tech: "Squared paper and scissors",
    tech_purpose: "Equal area is checked by counting, which needs a grid",
    ai_prompts: ["Generate equal-area partitions of unlike shape", "Write partitions to judge as equal or unequal"],
    assessment: ["Check equality is verified by counting", "Ask what the whole is", "Watch for congruence being demanded"],
    why_it_works: ["Four unlike quarters that count the same breaks the identical-shape assumption", "Naming the whole first stops fractions floating free of what they are of", "Counting squares makes equality checkable rather than judged by eye", "Judging given partitions tests the criterion rather than the drawing"],
  },
];

seedStandardsBatch({
  label: "Batch 14 — grade 3 mathematics",
  standardsData,
  unpacksData,
  blueprintsData,
});
