// @ts-nocheck
/**
 * Batch 7: 20 more drafted standards, reaching 144.
 *
 * Closes the writing progressions entirely — opinion and argument now run
 * unbroken from grade 1 to grade 8 — and adds the maths every teacher covers
 * but nobody lists as a favourite: telling time, long division, decimal
 * operations, percent, exponents and curved-solid volume.
 *
 *   bun run scripts/seed-standards-batch-7.ts
 */
import { seedStandardsBatch } from "./lib/seed-standards-batch";

const standardsData = [
  // ─── ELA ────────────────────────────────────────────────────────────────
  {
    code: "RL.K.3",
    name: "Name who is in the story and what happens",
    plain_reading:
      "With prompting and support, identify characters, settings, and major events in a story.",
    learning_target: "I can say who is in the story, where it happens, and what happens.",
    skills: ["Story Elements", "Listening Comprehension", "Retelling"],
    science_tags: ["dual-coding", "collaborative"],
    match_keys: ["characters", "setting", "major events", "story elements", "kindergarten"],
  },
  {
    code: "RI.1.5",
    name: "Use headings and contents to find things",
    plain_reading:
      "Know and use various text features, including headings, tables of contents, glossaries, electronic menus and icons, to locate key facts or information in a text.",
    learning_target: "I can use the contents page and headings to find what I need.",
    skills: ["Text Features", "Locating Information", "Nonfiction Navigation"],
    science_tags: ["dual-coding", "retrieval"],
    match_keys: ["text features", "table of contents", "headings", "glossary", "icons", "locate information"],
  },
  {
    code: "RF.2.4",
    name: "Read grade 2 text smoothly",
    plain_reading:
      "Read with sufficient accuracy and fluency to support comprehension, reading on-level text with purpose and understanding and with appropriate rate and expression.",
    learning_target: "I can read smoothly enough to still know what the story means.",
    skills: ["Fluency", "Accuracy", "Expression"],
    science_tags: ["retrieval", "spaced"],
    match_keys: ["fluency", "grade 2 fluency", "expression", "reading rate", "self-correction"],
  },
  {
    code: "L.3.1",
    name: "Explain what each kind of word does",
    plain_reading:
      "Demonstrate command of the conventions of standard English grammar and usage, including explaining the function of nouns, pronouns, verbs, adjectives and adverbs in particular sentences.",
    learning_target: "I can name the job a word is doing in a sentence.",
    skills: ["Grammar", "Parts of Speech", "Sentence Analysis"],
    science_tags: ["retrieval", "interleaving"],
    match_keys: ["parts of speech", "nouns verbs adjectives adverbs", "pronouns", "function", "grammar grade 3"],
  },
  {
    code: "RL.4.3",
    name: "Describe a character in depth",
    plain_reading:
      "Describe in depth a character, setting, or event in a story or drama, drawing on specific details in the text such as a character's thoughts, words, or actions.",
    learning_target: "I can describe a character properly using what they think, say and do.",
    skills: ["Characterisation", "Textual Evidence", "Inference"],
    science_tags: ["elaboration", "dual-coding"],
    match_keys: ["character traits", "in depth", "thoughts words actions", "describe character", "specific details"],
  },
  {
    code: "W.5.1",
    name: "Write an opinion with logically ordered reasons",
    plain_reading:
      "Write opinion pieces on topics or texts, supporting a point of view with reasons and information, with logically ordered reasons supported by facts and details.",
    learning_target: "I can order my reasons so each one builds on the last.",
    skills: ["Opinion Writing", "Logical Order", "Supporting Facts"],
    science_tags: ["elaboration", "interleaving"],
    match_keys: ["opinion writing", "logically ordered reasons", "point of view", "facts and details"],
  },
  {
    code: "W.6.1",
    name: "Write an argument with organised reasons",
    plain_reading:
      "Write arguments to support claims with clear reasons and relevant evidence, introducing claims and organising the reasons and evidence clearly.",
    learning_target: "I can introduce a claim and organise my evidence so it holds together.",
    skills: ["Argument Writing", "Claim", "Organisation"],
    science_tags: ["elaboration", "interleaving"],
    match_keys: ["argument writing", "claim", "relevant evidence", "organize reasons", "credible sources"],
  },
  {
    code: "RI.6.1",
    name: "Cite evidence in informational text",
    plain_reading:
      "Cite textual evidence to support analysis of what the text says explicitly as well as inferences drawn from the text.",
    learning_target: "I can back up my analysis of a nonfiction text with the author's own words.",
    skills: ["Textual Evidence", "Analysis", "Inference"],
    science_tags: ["elaboration", "interleaving"],
    match_keys: ["cite textual evidence", "informational text", "analysis", "inference", "explicitly"],
  },
  {
    code: "SL.7.1",
    name: "Discuss with questions that go deeper",
    plain_reading:
      "Engage effectively in a range of collaborative discussions on grade 7 topics, texts and issues, posing questions that elicit elaboration and responding with relevant observations and ideas.",
    learning_target: "I can ask a question that makes someone say more, not just answer.",
    skills: ["Discussion", "Questioning", "Elaboration"],
    science_tags: ["collaborative", "elaboration"],
    match_keys: ["collaborative discussion", "elicit elaboration", "pose questions", "grade 7 speaking", "respond"],
  },
  {
    code: "L.7.4",
    name: "Work out unfamiliar words in grade 7 texts",
    plain_reading:
      "Determine or clarify the meaning of unknown and multiple-meaning words and phrases based on grade 7 reading and content, using context, word parts and reference materials, and verifying the inferred meaning.",
    learning_target: "I can work out a word from clues and then check whether I was right.",
    skills: ["Vocabulary", "Morphology", "Verification"],
    science_tags: ["elaboration", "interleaving"],
    match_keys: ["context clues", "word parts", "reference materials", "verify meaning", "multiple meaning words"],
  },

  // ─── Mathematics ────────────────────────────────────────────────────────
  {
    code: "K.OA.A.3",
    name: "Break a number into two parts",
    plain_reading:
      "Decompose numbers less than or equal to 10 into pairs in more than one way, and record each decomposition by a drawing or equation.",
    learning_target: "I can split a number into two parts in more than one way.",
    skills: ["Decomposition", "Number Bonds", "Equations"],
    science_tags: ["dual-coding", "retrieval"],
    match_keys: ["decompose numbers", "number bonds", "pairs", "ways to make", "part part whole"],
  },
  {
    code: "1.MD.A.1",
    name: "Order objects by length",
    plain_reading:
      "Order three objects by length, and compare the lengths of two objects indirectly by using a third object.",
    learning_target: "I can put things in order by length, even when I cannot move them.",
    skills: ["Measurement", "Ordering", "Transitivity"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["order by length", "indirect comparison", "longer shorter", "transitivity", "third object"],
  },
  {
    code: "2.OA.A.1",
    name: "Solve one- and two-step problems within 100",
    plain_reading:
      "Use addition and subtraction within 100 to solve one- and two-step word problems involving situations of adding to, taking from, putting together, taking apart and comparing.",
    learning_target: "I can solve a word problem that needs one step or two.",
    skills: ["Word Problems", "Two-Step Problems", "Addition and Subtraction"],
    science_tags: ["interleaving", "dual-coding"],
    match_keys: ["word problems within 100", "two step", "adding to", "taking from", "comparing"],
  },
  {
    code: "3.MD.A.1",
    name: "Tell time to the minute",
    plain_reading:
      "Tell and write time to the nearest minute and measure time intervals in minutes, solving word problems involving addition and subtraction of time intervals.",
    learning_target: "I can read a clock to the minute and work out how long something took.",
    skills: ["Telling Time", "Time Intervals", "Elapsed Time"],
    science_tags: ["dual-coding", "retrieval"],
    match_keys: ["tell time", "nearest minute", "elapsed time", "time intervals", "analog clock"],
  },
  {
    code: "4.NBT.B.6",
    name: "Divide with remainders",
    plain_reading:
      "Find whole-number quotients and remainders with up to four-digit dividends and one-digit divisors, using strategies based on place value and the properties of operations.",
    learning_target: "I can divide a big number by a small one and explain each step.",
    skills: ["Division", "Place Value Strategies", "Remainders"],
    science_tags: ["dual-coding", "interleaving"],
    match_keys: ["long division", "quotients", "remainders", "divide by one digit", "partial quotients"],
  },
  {
    code: "5.NBT.B.7",
    name: "Compute with decimals to hundredths",
    plain_reading:
      "Add, subtract, multiply and divide decimals to hundredths, using concrete models or drawings and strategies based on place value, and relate the strategy to a written method.",
    learning_target: "I can add, subtract, multiply and divide decimals and explain why it works.",
    skills: ["Decimal Operations", "Place Value", "Estimation"],
    science_tags: ["dual-coding", "interleaving"],
    match_keys: ["decimal operations", "add decimals", "multiply decimals", "divide decimals", "hundredths"],
  },
  {
    code: "6.EE.B.7",
    name: "Solve one-step equations",
    plain_reading:
      "Solve real-world and mathematical problems by writing and solving equations of the form x + p = q and px = q for cases in which p, q and x are all non-negative rational numbers.",
    learning_target: "I can write an equation for a problem and solve it.",
    skills: ["Equations", "Inverse Operations", "Modelling"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["one step equations", "solve for x", "inverse operations", "x plus p equals q", "balance"],
  },
  {
    code: "7.RP.A.3",
    name: "Solve percent and ratio problems",
    plain_reading:
      "Use proportional relationships to solve multistep ratio and percent problems, including simple interest, tax, markups, discounts, tips, and percent increase and decrease.",
    learning_target: "I can work out discounts, tips and percent changes.",
    skills: ["Percent", "Proportional Reasoning", "Multistep Problems"],
    science_tags: ["interleaving", "elaboration"],
    match_keys: ["percent", "discount", "markup", "tax", "tip", "percent increase", "proportional"],
  },
  {
    code: "8.EE.A.1",
    name: "Apply the laws of exponents",
    plain_reading:
      "Know and apply the properties of integer exponents to generate equivalent numerical expressions, including products, quotients, powers of powers, and negative exponents.",
    learning_target: "I can simplify expressions with exponents and explain the rule I used.",
    skills: ["Exponents", "Equivalent Expressions", "Negative Exponents"],
    science_tags: ["elaboration", "interleaving"],
    match_keys: ["exponent rules", "properties of exponents", "negative exponents", "power of a power", "zero exponent"],
  },
  {
    code: "8.G.C.9",
    name: "Find the volume of curved solids",
    plain_reading:
      "Know the formulas for the volumes of cones, cylinders and spheres and use them to solve real-world and mathematical problems.",
    learning_target: "I can find the volume of a cylinder, cone or sphere and know which formula fits.",
    skills: ["Volume", "Cylinders and Cones", "Formula Selection"],
    science_tags: ["dual-coding", "interleaving"],
    match_keys: ["volume of cylinder", "cone", "sphere", "pi r squared h", "curved solids"],
  },
];

const unpacksData = [
  {
    standard_code: "RL.K.3",
    verbs: [
      { word: "Identify", gloss: "point out who, where and what" },
    ],
    concepts: ["Characters", "Setting", "Major events"],
    vocabulary: [
      { term: "character", definition: "a person or animal in the story" },
      { term: "setting", definition: "where the story happens" },
      { term: "event", definition: "something that happens" },
      { term: "story", definition: "a made-up telling with a beginning and an end" },
    ],
    prior_skills: ["Listen to a whole story", "Talk about pictures", "Answer a simple question"],
    prior_standards: [{ code: "PK.RL.3", text: "Respond to who and where questions about a story" }],
    future_standards: [{ code: "RL.1.3", text: "Describe characters, settings and major events using key details" }],
    challenges: [
      { problem: "Every small happening is called a major event", fix: "Ask whether the story would still work without it" },
      { problem: "Setting is named as the book, not the place", fix: "Ask where the characters actually are" },
    ],
    mastery_statement: "Student can identify characters, setting and major events in a read-aloud with prompting.",
    ladder: [
      { name: "I can name a character", descriptor: "Identifies who is in it" },
      { name: "I can say where it happens", descriptor: "Names the setting" },
      { name: "I can say what happens", descriptor: "Recalls events" },
      { name: "I can pick the big events", descriptor: "Distinguishes major from minor" },
    ],
  },
  {
    standard_code: "RI.1.5",
    verbs: [
      { word: "Know", gloss: "recognise each feature" },
      { word: "Use", gloss: "actually go to it to find something" },
    ],
    concepts: ["Text features", "Locating information", "Book navigation"],
    vocabulary: [
      { term: "heading", definition: "the title of a section" },
      { term: "table of contents", definition: "the list at the front showing what is where" },
      { term: "glossary", definition: "the word list at the back" },
      { term: "icon", definition: "a small picture that stands for something" },
    ],
    prior_skills: ["Identify a title", "Recognise a photograph", "Turn to a given page"],
    prior_standards: [{ code: "RI.K.5", text: "Identify the front cover, back cover and title page" }],
    future_standards: [{ code: "RI.2.5", text: "Know and use text features to locate key facts efficiently" }],
    challenges: [
      { problem: "Students read from the start rather than navigating", fix: "Pose questions and time the search" },
      { problem: "Contents and glossary are confused", fix: "Sort questions by which one answers them" },
    ],
    mastery_statement: "Student can use a table of contents, headings or a glossary to locate information in a text.",
    ladder: [
      { name: "I can find the contents page", descriptor: "Locates the feature" },
      { name: "I can say what it is for", descriptor: "Matches feature to purpose" },
      { name: "I can use it to find a page", descriptor: "Navigates successfully" },
      { name: "I can pick the right feature", descriptor: "Chooses for the question" },
    ],
  },
  {
    standard_code: "RF.2.4",
    verbs: [
      { word: "Read", gloss: "decode accurately and smoothly" },
      { word: "Self-correct", gloss: "notice and fix a slip" },
    ],
    concepts: ["Accuracy", "Rate", "Expression"],
    vocabulary: [
      { term: "fluency", definition: "reading smoothly, accurately and with expression" },
      { term: "expression", definition: "reading so it sounds like talking" },
      { term: "punctuation", definition: "the marks that tell you where to pause" },
      { term: "self-correct", definition: "fix your own mistake without being told" },
    ],
    prior_skills: ["Decode grade 2 words", "Read sight words automatically", "Read familiar text aloud"],
    prior_standards: [{ code: "RF.1.4", text: "Read grade 1 text with accuracy and fluency" }],
    future_standards: [{ code: "RF.3.4", text: "Read grade 3 text with accuracy, rate and expression" }],
    challenges: [
      { problem: "Punctuation is read straight through", fix: "Mark pauses and practise the same line both ways" },
      { problem: "Errors pass unnoticed", fix: "Stop at the sentence end and ask whether it made sense" },
    ],
    mastery_statement: "Student can read grade 2 text accurately at an appropriate rate, with expression that supports meaning.",
    ladder: [
      { name: "I can read the words correctly", descriptor: "Accurate decoding" },
      { name: "I can keep going without stopping", descriptor: "Reasonable rate" },
      { name: "I can use the punctuation", descriptor: "Pauses appropriately" },
      { name: "I can fix a mistake myself", descriptor: "Self-corrects for meaning" },
    ],
  },
  {
    standard_code: "L.3.1",
    verbs: [
      { word: "Explain", gloss: "say what job a word does" },
      { word: "Demonstrate", gloss: "show it in your own writing" },
    ],
    concepts: ["Parts of speech", "Word function", "Sentence structure"],
    vocabulary: [
      { term: "noun", definition: "a word for a person, place or thing" },
      { term: "verb", definition: "a word for an action or state" },
      { term: "adjective", definition: "a word that describes a noun" },
      { term: "adverb", definition: "a word that tells you how, when or where" },
    ],
    prior_skills: ["Identify nouns and verbs", "Write complete sentences", "Use adjectives"],
    prior_standards: [{ code: "L.2.1", text: "Demonstrate command of grade 2 grammar conventions" }],
    future_standards: [{ code: "L.4.1", text: "Use relative pronouns, progressive tenses and modal auxiliaries" }],
    challenges: [
      { problem: "Words are labelled from a list rather than by their job", fix: "Use a word that changes class between two sentences" },
      { problem: "Adverbs are assumed to end in -ly", fix: "Collect adverbs that do not — soon, here, very" },
    ],
    mastery_statement: "Student can explain the function a word performs in a particular sentence, not just its usual label.",
    ladder: [
      { name: "I can find the nouns and verbs", descriptor: "Identifies the basics" },
      { name: "I can find adjectives and adverbs", descriptor: "Extends the categories" },
      { name: "I can say what job a word does here", descriptor: "Reasons from function" },
      { name: "I can use them deliberately", descriptor: "Applies in own writing" },
    ],
  },
  {
    standard_code: "RL.4.3",
    verbs: [
      { word: "Describe", gloss: "give a full account" },
      { word: "Draw on", gloss: "use specific details as evidence" },
    ],
    concepts: ["Characterisation", "Thoughts, words and actions", "Depth versus label"],
    vocabulary: [
      { term: "trait", definition: "what a character is generally like" },
      { term: "motivation", definition: "why a character does something" },
      { term: "in depth", definition: "fully, with detail and evidence" },
      { term: "evidence", definition: "the detail from the text that shows it" },
    ],
    prior_skills: ["Describe characters and settings", "Cite details", "Make inferences"],
    prior_standards: [{ code: "RL.3.3", text: "Describe characters and explain how their actions contribute" }],
    future_standards: [{ code: "RL.5.3", text: "Compare and contrast characters drawing on specific details" }],
    challenges: [
      { problem: "A one-word label is offered as a description", fix: "Require a trait plus the moment that shows it" },
      { problem: "Only what the character says counts", fix: "Collect thoughts and actions in separate columns" },
    ],
    mastery_statement: "Student can describe a character in depth using their thoughts, words and actions as evidence.",
    ladder: [
      { name: "I can name a character trait", descriptor: "Gives a label" },
      { name: "I can find a moment showing it", descriptor: "Supplies evidence" },
      { name: "I can use thoughts, words and actions", descriptor: "Draws on all three" },
      { name: "I can explain why they act that way", descriptor: "Infers motivation" },
    ],
  },
  {
    standard_code: "W.5.1",
    verbs: [
      { word: "Support", gloss: "back the view with reasons and facts" },
      { word: "Order", gloss: "sequence reasons logically" },
    ],
    concepts: ["Logical order", "Facts as support", "Point of view"],
    vocabulary: [
      { term: "logically ordered", definition: "arranged so each reason sets up the next" },
      { term: "point of view", definition: "the position you are arguing for" },
      { term: "detail", definition: "a specific fact supporting a reason" },
      { term: "concluding statement", definition: "the ending that ties it together" },
    ],
    prior_skills: ["Write opinion pieces with grouped reasons", "Use linking words", "Find supporting facts"],
    prior_standards: [{ code: "W.4.1", text: "Write opinion pieces with grouped, supported reasons" }],
    future_standards: [{ code: "W.6.1", text: "Write arguments to support claims with clear reasons and evidence" }],
    challenges: [
      { problem: "Reasons appear in the order they were thought of", fix: "Swap two and ask whether anything is lost" },
      { problem: "Reasons have no facts beneath them", fix: "Require one specific detail per reason before drafting" },
    ],
    mastery_statement: "Student can write an opinion piece whose reasons are logically ordered and supported by facts.",
    ladder: [
      { name: "I can state an opinion", descriptor: "Writes a clear position" },
      { name: "I can give supported reasons", descriptor: "Adds facts beneath each" },
      { name: "I can order them logically", descriptor: "Sequences deliberately" },
      { name: "I can conclude properly", descriptor: "Ties the piece together" },
    ],
  },
  {
    standard_code: "W.6.1",
    verbs: [
      { word: "Introduce", gloss: "state the claim clearly" },
      { word: "Support", gloss: "back it with relevant evidence" },
      { word: "Organise", gloss: "arrange reasons so they build" },
    ],
    concepts: ["Claim", "Relevant evidence", "Credible sources"],
    vocabulary: [
      { term: "claim", definition: "the position you are arguing for" },
      { term: "credible", definition: "trustworthy enough to rely on" },
      { term: "relevant", definition: "actually supporting the claim made" },
      { term: "cohesion", definition: "the sense that parts belong together" },
    ],
    prior_skills: ["Write opinion pieces with ordered reasons", "Cite evidence", "Use transitions"],
    prior_standards: [{ code: "W.5.1", text: "Write opinion pieces with logically ordered reasons" }],
    future_standards: [{ code: "W.7.1", text: "Write arguments acknowledging alternate claims" }],
    challenges: [
      { problem: "Opinion and argument are treated as the same genre", fix: "Compare a piece grounded in preference with one grounded in evidence" },
      { problem: "Any source is treated as credible", fix: "Ask who wrote it and what they wanted" },
    ],
    mastery_statement: "Student can write an argument introducing a claim and organising relevant evidence to support it.",
    ladder: [
      { name: "I can state a claim", descriptor: "Writes an arguable position" },
      { name: "I can find evidence", descriptor: "Locates supporting material" },
      { name: "I can check it is relevant", descriptor: "Tests against the claim" },
      { name: "I can organise it clearly", descriptor: "Arranges for cohesion" },
    ],
  },
  {
    standard_code: "RI.6.1",
    verbs: [
      { word: "Cite", gloss: "quote and locate the evidence" },
      { word: "Support", gloss: "make the evidence carry the analysis" },
      { word: "Analyse", gloss: "explain how and why" },
    ],
    concepts: ["Citation", "Explicit and inferential", "Analysis"],
    vocabulary: [
      { term: "cite", definition: "quote and say where it came from" },
      { term: "explicitly", definition: "stated directly in the text" },
      { term: "inference", definition: "a conclusion drawn from clues" },
      { term: "analysis", definition: "explaining how and why, not just what" },
    ],
    prior_skills: ["Quote accurately", "Draw inferences", "Locate supporting text"],
    prior_standards: [{ code: "RI.5.1", text: "Quote accurately when explaining and inferring" }],
    future_standards: [{ code: "RI.7.1", text: "Cite several pieces of evidence to support analysis" }],
    challenges: [
      { problem: "Evidence is dropped in with no comment", fix: "Require a sentence of analysis after every quote" },
      { problem: "Quotes fit the topic but not the claim", fix: "Test each against the claim, not the subject" },
    ],
    mastery_statement: "Student can cite evidence for explicit statements and inferences in informational text, and explain the link.",
    ladder: [
      { name: "I can find relevant evidence", descriptor: "Locates supporting text" },
      { name: "I can cite it accurately", descriptor: "Quotes and attributes" },
      { name: "I can support an inference", descriptor: "Handles implied meaning" },
      { name: "I can explain the connection", descriptor: "Adds analysis" },
    ],
  },
  {
    standard_code: "SL.7.1",
    verbs: [
      { word: "Pose", gloss: "ask a question that opens something up" },
      { word: "Elicit", gloss: "draw more out of someone" },
      { word: "Respond", gloss: "reply with something relevant" },
    ],
    concepts: ["Questions that elicit", "Relevant response", "Discussion momentum"],
    vocabulary: [
      { term: "elicit", definition: "draw a fuller answer out of someone" },
      { term: "elaborate", definition: "say more about an idea" },
      { term: "probe", definition: "ask a question that digs deeper" },
      { term: "relevant", definition: "actually connected to what is being discussed" },
    ],
    prior_skills: ["Build on others' ideas", "Come prepared with evidence", "Follow discussion norms"],
    prior_standards: [{ code: "SL.6.1", text: "Come to discussions prepared and draw on evidence" }],
    future_standards: [{ code: "SL.8.1", text: "Pose questions that connect ideas and qualify views" }],
    challenges: [
      { problem: "Questions have yes or no answers", fix: "Ban questions answerable in one word" },
      { problem: "Responses restart rather than respond", fix: "Require a reference to the previous speaker" },
    ],
    mastery_statement: "Student can pose questions that draw fuller answers from others and respond with relevant ideas.",
    ladder: [
      { name: "I can contribute an idea", descriptor: "Participates" },
      { name: "I can ask a question", descriptor: "Poses a question at all" },
      { name: "I can ask one that opens things up", descriptor: "Elicits elaboration" },
      { name: "I can respond to what was said", descriptor: "Connects rather than restarts" },
    ],
  },
  {
    standard_code: "L.7.4",
    verbs: [
      { word: "Determine", gloss: "work out the meaning" },
      { word: "Verify", gloss: "check the inferred meaning is right" },
    ],
    concepts: ["Context", "Word parts", "Verification"],
    vocabulary: [
      { term: "infer", definition: "work out from clues rather than being told" },
      { term: "verify", definition: "check something is actually true" },
      { term: "root", definition: "the core part carrying a word's meaning" },
      { term: "precise", definition: "exactly right rather than roughly right" },
    ],
    prior_skills: ["Use context clues", "Break words into parts", "Use a dictionary"],
    prior_standards: [{ code: "L.6.4", text: "Determine the meaning of unknown words using grade 6 strategies" }],
    future_standards: [{ code: "L.8.4", text: "Determine meanings using grade 8 strategies and verify them" }],
    challenges: [
      { problem: "The inferred meaning is never checked", fix: "Require the dictionary as the last step, not the first" },
      { problem: "A roughly right meaning is accepted", fix: "Compare the guess with the definition and note the gap" },
    ],
    mastery_statement: "Student can infer a word's meaning from context and word parts, then verify it against a reference.",
    ladder: [
      { name: "I can guess from context", descriptor: "Proposes a meaning" },
      { name: "I can use word parts", descriptor: "Breaks the word down" },
      { name: "I can check it", descriptor: "Verifies against a reference" },
      { name: "I can sharpen my first guess", descriptor: "Notes the gap and refines" },
    ],
  },
  {
    standard_code: "K.OA.A.3",
    verbs: [
      { word: "Decompose", gloss: "break a number into two parts" },
      { word: "Record", gloss: "show it as a drawing or equation" },
    ],
    concepts: ["Number bonds", "Part-part-whole", "Multiple decompositions"],
    vocabulary: [
      { term: "part", definition: "one piece of a bigger number" },
      { term: "whole", definition: "the total number" },
      { term: "decompose", definition: "break into parts" },
      { term: "equation", definition: "a number sentence with an equals sign" },
    ],
    prior_skills: ["Count objects", "Compare small groups", "Represent addition"],
    prior_standards: [{ code: "K.OA.A.1", text: "Represent addition and subtraction" }],
    future_standards: [{ code: "1.OA.B.3", text: "Apply properties of operations as strategies to add" }],
    challenges: [
      { problem: "Only one decomposition is found", fix: "Ask for another way, then another, until the pattern appears" },
      { problem: "5 and 2 is treated as different from 2 and 5", fix: "Show both with the same counters, rearranged" },
    ],
    mastery_statement: "Student can break a number up to 10 into two parts in more than one way and record each.",
    ladder: [
      { name: "I can split a number into two", descriptor: "Finds one decomposition" },
      { name: "I can find another way", descriptor: "Finds a second" },
      { name: "I can find all the ways", descriptor: "Works systematically" },
      { name: "I can write them as equations", descriptor: "Records symbolically" },
    ],
  },
  {
    standard_code: "1.MD.A.1",
    verbs: [
      { word: "Order", gloss: "put three things in length order" },
      { word: "Compare", gloss: "use a third object to judge two" },
    ],
    concepts: ["Ordering", "Indirect comparison", "Transitivity"],
    vocabulary: [
      { term: "longest", definition: "more length than all the others" },
      { term: "shortest", definition: "less length than all the others" },
      { term: "order", definition: "arrange from least to most" },
      { term: "indirect", definition: "compared using something else in between" },
    ],
    prior_skills: ["Compare two objects directly", "Line objects up at a common start", "Use longer and shorter"],
    prior_standards: [{ code: "K.MD.A.2", text: "Directly compare two objects on a shared attribute" }],
    future_standards: [{ code: "2.MD.A.1", text: "Measure length with appropriate tools" }],
    challenges: [
      { problem: "Three objects are compared only in pairs", fix: "Line all three up at once" },
      { problem: "Indirect comparison is not trusted", fix: "Compare two fixed objects with a piece of string" },
    ],
    mastery_statement: "Student can order three objects by length and compare two indirectly using a third.",
    ladder: [
      { name: "I can compare two things", descriptor: "Direct comparison" },
      { name: "I can find the longest of three", descriptor: "Identifies an extreme" },
      { name: "I can order all three", descriptor: "Full ordering" },
      { name: "I can use string to compare", descriptor: "Indirect comparison" },
    ],
  },
  {
    standard_code: "2.OA.A.1",
    verbs: [
      { word: "Solve", gloss: "work out the answer" },
      { word: "Represent", gloss: "show the problem with a drawing or equation" },
    ],
    concepts: ["Problem types", "Two-step problems", "Unknowns in any position"],
    vocabulary: [
      { term: "altogether", definition: "the total when groups are combined" },
      { term: "difference", definition: "how much more one is than another" },
      { term: "two-step", definition: "needing two calculations" },
      { term: "unknown", definition: "the part you have to work out" },
    ],
    prior_skills: ["Solve one-step problems within 20", "Add and subtract within 100", "Draw a bar model"],
    prior_standards: [{ code: "1.OA.A.1", text: "Solve addition and subtraction word problems within 20" }],
    future_standards: [{ code: "3.OA.D.8", text: "Solve two-step word problems using the four operations" }],
    challenges: [
      { problem: "The second step is forgotten", fix: "Underline what the question actually asks before starting" },
      { problem: "Keywords drive the operation", fix: "Include compare problems where 'more' needs subtraction" },
    ],
    mastery_statement: "Student can solve one- and two-step problems within 100 and represent them with a model or equation.",
    ladder: [
      { name: "I can solve a one-step problem", descriptor: "Single operation" },
      { name: "I can draw the problem", descriptor: "Represents the structure" },
      { name: "I can find the hidden step", descriptor: "Identifies both steps" },
      { name: "I can check I answered the question", descriptor: "Returns to what was asked" },
    ],
  },
  {
    standard_code: "3.MD.A.1",
    verbs: [
      { word: "Tell", gloss: "read the time from a clock" },
      { word: "Measure", gloss: "work out how long something took" },
    ],
    concepts: ["Analog clock reading", "Minutes", "Elapsed time"],
    vocabulary: [
      { term: "hour hand", definition: "the short hand showing the hour" },
      { term: "minute hand", definition: "the long hand showing the minutes" },
      { term: "interval", definition: "the amount of time between two moments" },
      { term: "elapsed", definition: "how much time has passed" },
    ],
    prior_skills: ["Tell time to five minutes", "Skip count by fives", "Add and subtract within 100"],
    prior_standards: [{ code: "2.MD.C.7", text: "Tell and write time to the nearest five minutes" }],
    future_standards: [{ code: "4.MD.A.2", text: "Solve word problems involving time intervals" }],
    challenges: [
      { problem: "The hands are read the wrong way round", fix: "Colour the hands and label them" },
      { problem: "Elapsed time is subtracted like ordinary numbers", fix: "Count on around a number line marked in minutes" },
    ],
    mastery_statement: "Student can read a clock to the nearest minute and work out elapsed time in minutes.",
    ladder: [
      { name: "I can read the hour", descriptor: "Uses the hour hand" },
      { name: "I can read to five minutes", descriptor: "Skip counts around" },
      { name: "I can read to the minute", descriptor: "Counts individual minutes" },
      { name: "I can work out how long it took", descriptor: "Computes an interval" },
    ],
  },
  {
    standard_code: "4.NBT.B.6",
    verbs: [
      { word: "Find", gloss: "work out the quotient" },
      { word: "Explain", gloss: "justify the strategy used" },
    ],
    concepts: ["Division strategies", "Partial quotients", "Remainders"],
    vocabulary: [
      { term: "dividend", definition: "the number being divided" },
      { term: "divisor", definition: "the number you divide by" },
      { term: "quotient", definition: "the answer to a division" },
      { term: "partial quotient", definition: "one chunk of the answer, found at a time" },
    ],
    prior_skills: ["Multiply multi-digit numbers", "Divide within 100", "Estimate with rounding"],
    prior_standards: [{ code: "4.NBT.B.5", text: "Multiply multi-digit whole numbers" }],
    future_standards: [{ code: "5.NBT.B.6", text: "Find quotients with two-digit divisors" }],
    challenges: [
      { problem: "The algorithm is followed with no sense of size", fix: "Estimate the quotient first" },
      { problem: "A zero in the quotient is skipped", fix: "Use place value columns so every position is filled" },
    ],
    mastery_statement: "Student can divide up to four digits by one digit, interpret the remainder, and explain the strategy.",
    ladder: [
      { name: "I can divide within 100", descriptor: "Uses known facts" },
      { name: "I can estimate the quotient", descriptor: "Judges size first" },
      { name: "I can use partial quotients", descriptor: "Chunks the division" },
      { name: "I can explain each step", descriptor: "Justifies the method" },
    ],
  },
  {
    standard_code: "5.NBT.B.7",
    verbs: [
      { word: "Add", gloss: "combine decimals" },
      { word: "Multiply", gloss: "find a decimal product" },
      { word: "Relate", gloss: "connect the model to the written method" },
    ],
    concepts: ["Decimal place value", "Estimation", "Model to method"],
    vocabulary: [
      { term: "hundredth", definition: "one of a hundred equal parts" },
      { term: "decimal point", definition: "the dot separating whole from part" },
      { term: "align", definition: "line up by place value" },
      { term: "estimate", definition: "a rough answer used to check" },
    ],
    prior_skills: ["Understand decimal place value", "Multiply multi-digit numbers", "Add fractions"],
    prior_standards: [{ code: "5.NBT.A.1", text: "Understand place value across the decimal point" }],
    future_standards: [{ code: "6.NS.B.3", text: "Fluently add, subtract, multiply and divide decimals" }],
    challenges: [
      { problem: "Decimals are lined up by the last digit rather than the point", fix: "Add trailing zeros so both have the same places" },
      { problem: "The point is placed by rule with no check", fix: "Estimate first — 4.2 × 3 must be about 12" },
    ],
    mastery_statement: "Student can compute with decimals to hundredths and justify the placement of the decimal point.",
    ladder: [
      { name: "I can add and subtract decimals", descriptor: "Aligns by place value" },
      { name: "I can estimate the answer", descriptor: "Judges size first" },
      { name: "I can multiply decimals", descriptor: "Places the point correctly" },
      { name: "I can explain why the point goes there", descriptor: "Reasons rather than recalls" },
    ],
  },
  {
    standard_code: "6.EE.B.7",
    verbs: [
      { word: "Write", gloss: "turn the situation into an equation" },
      { word: "Solve", gloss: "find the value that makes it true" },
    ],
    concepts: ["Inverse operations", "Equation modelling", "Balance"],
    vocabulary: [
      { term: "equation", definition: "a statement that two things are equal" },
      { term: "inverse", definition: "the operation that undoes another" },
      { term: "solution", definition: "the value that makes the equation true" },
      { term: "isolate", definition: "get the variable alone on one side" },
    ],
    prior_skills: ["Write and evaluate expressions", "Understand the equal sign", "Operate with rational numbers"],
    prior_standards: [{ code: "6.EE.A.2", text: "Write, read and evaluate expressions with variables" }],
    future_standards: [{ code: "7.EE.B.4", text: "Construct and solve equations and inequalities" }],
    challenges: [
      { problem: "The same operation is done to only one side", fix: "Use a balance model so the imbalance is visible" },
      { problem: "The answer is found by guessing", fix: "Require the inverse operation to be shown" },
    ],
    mastery_statement: "Student can write an equation for a situation and solve it using inverse operations.",
    ladder: [
      { name: "I can check whether a value works", descriptor: "Substitutes and tests" },
      { name: "I can solve by inspection", descriptor: "Finds simple solutions" },
      { name: "I can use the inverse operation", descriptor: "Isolates the variable" },
      { name: "I can write the equation myself", descriptor: "Models a situation" },
    ],
  },
  {
    standard_code: "7.RP.A.3",
    verbs: [
      { word: "Use", gloss: "apply proportional reasoning" },
      { word: "Solve", gloss: "answer multistep percent problems" },
    ],
    concepts: ["Percent as a rate", "Increase and decrease", "Multistep problems"],
    vocabulary: [
      { term: "percent", definition: "out of a hundred" },
      { term: "markup", definition: "the amount added to a cost" },
      { term: "discount", definition: "the amount taken off a price" },
      { term: "percent increase", definition: "how much something grew, relative to where it started" },
    ],
    prior_skills: ["Find unit rates", "Convert between fractions, decimals and percents", "Solve proportions"],
    prior_standards: [{ code: "7.RP.A.2", text: "Recognise and represent proportional relationships" }],
    future_standards: [{ code: "8.EE.B.5", text: "Graph proportional relationships and interpret slope" }],
    challenges: [
      { problem: "Percent change is computed against the wrong base", fix: "Always ask 'percent of what?' before dividing" },
      { problem: "A 20% rise then a 20% fall is expected to return to the start", fix: "Work a concrete example and compare" },
    ],
    mastery_statement: "Student can solve multistep percent problems and identify the base each percentage refers to.",
    ladder: [
      { name: "I can find a percent of a number", descriptor: "Basic computation" },
      { name: "I can find a discount or markup", descriptor: "Applies to a price" },
      { name: "I can find percent change", descriptor: "Uses the original as the base" },
      { name: "I can handle two steps", descriptor: "Chains percent operations" },
    ],
  },
  {
    standard_code: "8.EE.A.1",
    verbs: [
      { word: "Know", gloss: "hold the exponent rules" },
      { word: "Apply", gloss: "use them to simplify" },
    ],
    concepts: ["Product and quotient rules", "Power of a power", "Negative and zero exponents"],
    vocabulary: [
      { term: "exponent", definition: "how many times the base is multiplied by itself" },
      { term: "base", definition: "the number being raised to a power" },
      { term: "negative exponent", definition: "a power meaning one over the positive power" },
      { term: "equivalent", definition: "different-looking but always equal" },
    ],
    prior_skills: ["Evaluate powers", "Multiply and divide fluently", "Work with fractions"],
    prior_standards: [{ code: "6.EE.A.1", text: "Write and evaluate numerical expressions involving exponents" }],
    future_standards: [{ code: "N-RN.1", text: "Extend the properties of exponents to rational exponents" }],
    challenges: [
      { problem: "Exponents are added when bases differ", fix: "Expand both and count — the rule only holds for a shared base" },
      { problem: "A negative exponent is read as a negative answer", fix: "Extend the pattern down through zero to see the reciprocal appear" },
    ],
    mastery_statement: "Student can apply the exponent properties to generate equivalent expressions and explain each rule.",
    ladder: [
      { name: "I can evaluate a power", descriptor: "Computes correctly" },
      { name: "I can multiply powers of the same base", descriptor: "Adds exponents" },
      { name: "I can handle a power of a power", descriptor: "Multiplies exponents" },
      { name: "I can explain a negative exponent", descriptor: "Reasons from the pattern" },
    ],
  },
  {
    standard_code: "8.G.C.9",
    verbs: [
      { word: "Know", gloss: "hold the three volume formulas" },
      { word: "Use", gloss: "apply the right one to a problem" },
    ],
    concepts: ["Cylinder, cone and sphere", "Formula selection", "Relationships between solids"],
    vocabulary: [
      { term: "cylinder", definition: "a solid with two circular ends and straight sides" },
      { term: "cone", definition: "a solid with a circular base narrowing to a point" },
      { term: "sphere", definition: "a perfectly round solid" },
      { term: "radius", definition: "the distance from the centre to the edge of a circle" },
    ],
    prior_skills: ["Find the area of a circle", "Compute volume of prisms", "Work with pi"],
    prior_standards: [{ code: "7.G.B.6", text: "Solve problems involving area, volume and surface area" }],
    future_standards: [{ code: "G-GMD.3", text: "Use volume formulas to solve problems" }],
    challenges: [
      { problem: "Diameter is used where radius is needed", fix: "Mark the radius on every diagram before substituting" },
      { problem: "The formulas are memorised without relationship", fix: "Pour a cone into a cylinder — three cones fill it exactly" },
    ],
    mastery_statement: "Student can select and apply the correct volume formula for a cylinder, cone or sphere.",
    ladder: [
      { name: "I can find the area of a circle", descriptor: "Uses pi r squared" },
      { name: "I can find a cylinder's volume", descriptor: "Area times height" },
      { name: "I can find a cone's volume", descriptor: "Applies the one-third" },
      { name: "I can choose the right formula", descriptor: "Identifies the solid" },
    ],
  },
];

const blueprintsData = [
  {
    standard_code: "RL.K.3",
    title: "Who, Where, What Happened",
    badge: "Kindergarten",
    route_name: "Interactive Read-Aloud",
    route_line: "Meet the characters → Find the place → Pick the big moments",
    success_criteria: ["Names a character", "Says where the story happens", "Picks out a major event"],
    steps: [
      { name: "Retrieve Yesterday's Story", minutes: 5, body: "Who was in it? Where were they? Oral recall builds the habit of holding a story.", science_tag: "retrieval" },
      { name: "Three Picture Cards", minutes: 8, body: "A person, a place, an action. Three icons for the three things we listen for.", science_tag: "dual-coding" },
      { name: "Listen for Characters", minutes: 10, body: "Read aloud, stopping when someone new appears. Students hold up the person card.", science_tag: "collaborative" },
      { name: "Where Are They?", minutes: 8, body: "Stop and ask. Point to the picture that shows the place. Setting as somewhere, not something.", science_tag: "dual-coding" },
      { name: "Big or Little", minutes: 12, body: "Six moments from the story. Which really mattered? Ask whether the story still works without it.", science_tag: "elaboration" },
      { name: "Act It Out", minutes: 10, body: "Small groups act the major events in order. Acting forces a decision about what mattered.", science_tag: "collaborative" },
      { name: "Tell a Partner", minutes: 4, body: "Who, where, what happened. Three things, said aloud.", science_tag: "spaced" },
    ],
    ef_supports: ["Three icon cards for the elements", "Stop points marked in the book", "Acting out instead of writing", "Turn-and-talk before whole group"],
    tech: "Big book and picture cards",
    tech_purpose: "Icons let non-readers hold the three categories",
    ai_prompts: ["Write a kindergarten story with clear characters, setting and events", "Generate major and minor events for sorting"],
    assessment: ["Watch card responses during the read-aloud", "Check the acted events are the major ones", "Partner retell covering all three"],
    why_it_works: ["Three icons keep the categories in mind without reading", "The remove-it test makes 'major' a decidable question", "Acting forces a judgement about importance", "Holding up a card lets every child answer every time"],
  },
  {
    standard_code: "RI.1.5",
    title: "Finding Your Way Around a Book",
    badge: "Grade 1",
    route_name: "Strategy Instruction",
    route_line: "Tour the features → Match to purpose → Race to find",
    success_criteria: ["Locates the contents page and glossary", "Says what each feature is for", "Uses one to find a page"],
    steps: [
      { name: "What Is Different Here?", minutes: 5, body: "Compare a storybook and an information book. Students notice the extra parts.", science_tag: "retrieval" },
      { name: "Feature Tour", minutes: 10, body: "Contents, headings, glossary, icons. Say the job first, then the name — the job is what sticks.", science_tag: "dual-coding" },
      { name: "Match Job to Feature", minutes: 10, body: "Cards matching purposes to features. Contents and glossary get swapped, which is the useful moment.", science_tag: "elaboration" },
      { name: "Which Would Help?", minutes: 10, body: "Questions posed; students name the feature that would answer each. No reading yet.", science_tag: "interleaving" },
      { name: "Fact Race", minutes: 12, body: "Timed. Five questions, real books. Speed makes navigating beat reading straight through.", science_tag: "collaborative" },
      { name: "Show Your Route", minutes: 8, body: "How did you find it? Comparing routes surfaces efficiency as a skill.", science_tag: "elaboration" },
      { name: "Find One Fact", minutes: 5, body: "One question, one feature named, one page found.", science_tag: "spaced" },
    ],
    ef_supports: ["Feature and purpose matching cards", "Timer for the race", "Books with all features present", "Anchor chart with icons"],
    tech: "Nonfiction books and matching cards",
    tech_purpose: "Real features to navigate",
    ai_prompts: ["Generate questions answerable by different text features", "Create feature-to-purpose matching cards"],
    assessment: ["Check the matching, especially contents versus glossary", "Time the race", "Confirm the feature named matches the route used"],
    why_it_works: ["Timing is what stops cover-to-cover reading", "Teaching the job before the name makes features useful rather than vocabulary", "Comparing routes makes efficiency visible", "The contents/glossary swap is predictable, so plan for it"],
  },
  {
    standard_code: "RF.2.4",
    title: "Reading So It Sounds Like Talking",
    badge: "Grade 2",
    route_name: "Routine and Practice",
    route_line: "Hear the difference → Reread → Read for meaning",
    success_criteria: ["Reads accurately", "Pauses at punctuation", "Notices and fixes a mistake"],
    steps: [
      { name: "Warm Up on Known Text", minutes: 5, body: "Reread yesterday's passage. Familiar text is where expression grows.", science_tag: "spaced" },
      { name: "Robot or Person", minutes: 8, body: "Read a passage flat, then naturally. Students name which they understood. Fluency serves meaning.", science_tag: "elaboration" },
      { name: "Punctuation Is Instructions", minutes: 10, body: "Full stops mean stop, commas mean pause, question marks lift the voice. Practise the same line three ways.", science_tag: "dual-coding" },
      { name: "Echo Reading", minutes: 10, body: "Teacher reads a line, students echo it. Expression is copied before it is produced.", science_tag: "collaborative" },
      { name: "Three Reads With a Partner", minutes: 12, body: "The same short passage, three times, partner listening for smoothness. Repetition is the mechanism.", science_tag: "retrieval" },
      { name: "Did That Make Sense?", minutes: 8, body: "Stop at each sentence end and ask. Self-correction starts with noticing.", science_tag: "interleaving" },
      { name: "Read and Answer", minutes: 5, body: "One new passage, one comprehension question.", science_tag: "spaced" },
    ],
    ef_supports: ["Familiar text for expression work", "Punctuation practice on one line", "Echo before independent", "Partner smoothness checklist"],
    tech: "Printed passages",
    tech_purpose: "Repeated reading needs the same text in hand",
    ai_prompts: ["Write grade 2 passages with varied punctuation", "Generate comprehension questions to follow a fluency read"],
    assessment: ["Listen to third reads", "Check punctuation is observed", "Comprehension question after every read"],
    why_it_works: ["Repeated reading of one passage is what builds fluency", "The robot contrast shows why prosody matters", "Punctuation as instructions gives a concrete rule", "Pairing every read with a question keeps meaning the point"],
  },
  {
    standard_code: "L.3.1",
    title: "What Job Is This Word Doing?",
    badge: "Grade 3",
    route_name: "Explicit Instruction",
    route_line: "Sort by job → Watch a word change class → Use them deliberately",
    success_criteria: ["Identifies nouns, verbs, adjectives and adverbs", "Explains a word's job in a particular sentence", "Uses each deliberately in writing"],
    steps: [
      { name: "Retrieve Nouns and Verbs", minutes: 5, body: "Sort words into things and actions. The foundation categories.", science_tag: "retrieval" },
      { name: "Adjectives and Adverbs", minutes: 10, body: "One describes a noun, the other tells how, when or where. Include adverbs without -ly.", science_tag: "dual-coding" },
      { name: "The Same Word, Two Jobs", minutes: 12, body: "'Run' in 'I run fast' and 'a long run'. Class depends on the sentence, not the word.", science_tag: "elaboration" },
      { name: "Sort by Function", minutes: 10, body: "Words in sentences, sorted by the job they do there. The sentence context is the decider.", science_tag: "interleaving" },
      { name: "Improve a Flat Sentence", minutes: 12, body: "Add an adjective, then an adverb. Grammar improving writing rather than labelling it.", science_tag: "elaboration" },
      { name: "Hunt in Your Own Writing", minutes: 8, body: "Find one of each in a recent draft. Transfer is the point.", science_tag: "collaborative" },
      { name: "Explain One Word", minutes: 3, body: "Given a word in a sentence, say what job it is doing.", science_tag: "spaced" },
    ],
    ef_supports: ["Non -ly adverb collection", "Same-word-two-jobs pairs", "Sentence improvement frames", "Own draft for the hunt"],
    tech: "Word and sentence cards",
    tech_purpose: "Sorting by function needs words in context",
    ai_prompts: ["Generate words that change class between sentences", "Create flat sentences for students to improve"],
    assessment: ["Check sorting is by function not by list", "Confirm improved sentences use both", "Individual explanation of a word's job"],
    why_it_works: ["A word changing class proves function beats memorised labels", "Non -ly adverbs break the rule students infer", "Improving a sentence makes grammar a tool", "Function sorting is exactly what the standard asks for"],
  },
  {
    standard_code: "RL.4.3",
    title: "More Than One Word About a Character",
    badge: "Grade 4",
    route_name: "Analytical Reading",
    route_line: "Collect thoughts, words, actions → Name a trait → Prove it",
    success_criteria: ["Names a character trait", "Supports it with a specific moment", "Draws on thoughts, words and actions"],
    steps: [
      { name: "Retrieve Character Description", minutes: 5, body: "Describe a character from a known book. Note how thin one-word answers feel.", science_tag: "retrieval" },
      { name: "Three Columns", minutes: 10, body: "Thoughts, words, actions. Three sources of evidence, collected separately as we read.", science_tag: "dual-coding" },
      { name: "Fill the Columns", minutes: 12, body: "Read a passage, collect entries in all three. Most students fill only the words column unprompted.", science_tag: "collaborative" },
      { name: "Trait Plus Evidence", minutes: 12, body: "'Brave' is a label. 'Brave, because she went back for the dog' is a description. Require both.", science_tag: "elaboration" },
      { name: "The Contradiction", minutes: 10, body: "A character who is brave in one scene and frightened in another. People are not one word.", science_tag: "elaboration" },
      { name: "Write the Description", minutes: 8, body: "One character, two traits, evidence from at least two of the three columns.", science_tag: "interleaving" },
      { name: "Share a Trait", minutes: 3, body: "One student gives a trait and the moment proving it.", science_tag: "spaced" },
    ],
    ef_supports: ["Three-column evidence organiser", "Trait-plus-because frame", "Contradiction discussion", "Numbered paragraphs"],
    tech: "Printed passage and organiser",
    tech_purpose: "Three columns make the three evidence sources visible",
    ai_prompts: ["Write passages revealing character through thought and action", "Generate contradictory character moments"],
    assessment: ["Check all three columns have entries", "Confirm traits carry evidence", "Look for more than one trait"],
    why_it_works: ["Three columns force evidence beyond dialogue", "Requiring 'because' turns a label into a description", "The contradiction prevents flat one-word characterisation", "In depth means more than one trait, so require two"],
  },
  {
    standard_code: "W.5.1",
    title: "Reasons That Build on Each Other",
    badge: "Grade 5",
    route_name: "Writing Workshop",
    route_line: "Gather reasons → Attach facts → Order for effect",
    success_criteria: ["Supports each reason with a fact", "Orders reasons logically", "Writes a conclusion that ties it together"],
    steps: [
      { name: "Retrieve Opinion Structure", minutes: 5, body: "Opinion, reasons, conclusion. Quick recall before deepening it.", science_tag: "retrieval" },
      { name: "A Reason Without a Fact", minutes: 8, body: "Show a reason with nothing beneath it. Students feel the thinness before being told.", science_tag: "elaboration" },
      { name: "One Fact Each", minutes: 12, body: "Every reason gets a specific fact, number or example. Reasons without one get cut.", science_tag: "elaboration" },
      { name: "Try Two Orders", minutes: 12, body: "Arrange the reasons two ways and read both aloud. Order changes how it lands.", science_tag: "interleaving" },
      { name: "Why Strongest Last", minutes: 10, body: "The final reason is what the reader leaves with. Discuss when that rule might not hold.", science_tag: "dual-coding" },
      { name: "Draft With Transitions", minutes: 10, body: "Connect reasons with phrases that show the build, not just 'also'.", science_tag: "collaborative" },
      { name: "Read the Last Reason", minutes: 3, body: "Two students read their final reason. Is it the strongest?", science_tag: "spaced" },
    ],
    ef_supports: ["Reason slips for reordering", "One-fact-per-reason rule", "Transition phrase bank", "Read both orders aloud"],
    tech: "Paper slips and organisers",
    tech_purpose: "Ordering is physical before it is written",
    ai_prompts: ["Generate grade 5 opinion prompts with researchable support", "Create reasons with and without supporting facts"],
    assessment: ["Check each reason has a fact", "Confirm the order was chosen deliberately", "Read conclusions for cohesion"],
    why_it_works: ["Feeling the thinness motivates supporting facts", "Reading two orders aloud shows sequence matters", "Cutting unsupported reasons teaches evidence comes first", "Discussing when the rule fails prevents formulaic writing"],
  },
  {
    standard_code: "W.6.1",
    title: "From Opinion to Argument",
    badge: "Grade 6",
    route_name: "Writing Workshop",
    route_line: "State the claim → Test the evidence → Organise for cohesion",
    success_criteria: ["States an arguable claim", "Uses evidence relevant to the claim", "Organises reasons so they cohere"],
    steps: [
      { name: "Retrieve Opinion Writing", minutes: 5, body: "Opinion, reasons, facts. The base this builds on.", science_tag: "retrieval" },
      { name: "Preference or Argument", minutes: 10, body: "'Pizza is best' versus 'school should start later'. One is taste, the other has evidence. Sort statements.", science_tag: "elaboration" },
      { name: "Relevant to the Claim", minutes: 12, body: "Evidence about the topic but not the claim. Students spot the gap — subtle and worth the time.", science_tag: "elaboration" },
      { name: "Who Wrote This?", minutes: 10, body: "Credibility. Who produced the source and what did they want? A quick habit, not a research unit.", science_tag: "dual-coding" },
      { name: "Group Evidence Under Reasons", minutes: 12, body: "Reasons are headings; evidence sits beneath. Structure before drafting.", science_tag: "dual-coding" },
      { name: "Draft With Cohesion", minutes: 10, body: "A sentence connecting each section to the last. Cohesion is written, not hoped for.", science_tag: "collaborative" },
      { name: "Swap and Test", minutes: 3, body: "Partners check every piece of evidence supports the claim, not just the topic.", science_tag: "spaced" },
    ],
    ef_supports: ["Preference versus argument sorting", "Claim relevance test", "Reasons as headings organiser", "Cohesion sentence frames"],
    tech: "Printed organisers and source excerpts",
    tech_purpose: "Grouping evidence under reasons physically",
    ai_prompts: ["Generate arguable and preference statements", "Write topic-relevant but claim-irrelevant evidence"],
    assessment: ["Check claims are arguable", "Confirm evidence supports the claim specifically", "Read cohesion sentences"],
    why_it_works: ["The preference-versus-argument sort marks the genre boundary", "Topic-relevant evidence is the subtle failure at this grade", "Reasons as headings makes structure visible before drafting", "Cohesion sentences are where an argument stops being a list"],
  },
  {
    standard_code: "RI.6.1",
    title: "Proving It From a Nonfiction Text",
    badge: "Grade 6",
    route_name: "Analytical Reading",
    route_line: "Make a claim → Find evidence → Explain the link",
    success_criteria: ["Cites evidence for a stated claim", "Cites evidence for an inference", "Explains how the evidence supports the claim"],
    steps: [
      { name: "Retrieve Quoting", minutes: 5, body: "One accurate quote from a familiar text.", science_tag: "retrieval" },
      { name: "Claim, Evidence, Link", minutes: 10, body: "Three parts colour-coded in a model. Students usually supply two and skip the third.", science_tag: "dual-coding" },
      { name: "Two Quotes, One Claim", minutes: 12, body: "Both fit. Which is stronger, and why? Directness and specificity separate them.", science_tag: "elaboration" },
      { name: "Evidence for an Inference", minutes: 12, body: "The quote is a clue, not the conclusion. Model the reasoning that bridges the gap.", science_tag: "elaboration" },
      { name: "Write Only the Link", minutes: 10, body: "Practise the third sentence alone. Isolating it stops it being dropped.", science_tag: "interleaving" },
      { name: "Full Paragraph", minutes: 8, body: "Claim, evidence, link, on a new question.", science_tag: "collaborative" },
      { name: "Check a Partner's", minutes: 3, body: "Are all three parts there, and does the link do work?", science_tag: "spaced" },
    ],
    ef_supports: ["Colour-coded model paragraph", "Two-quote comparison", "Link sentence practised alone", "Line-numbered text"],
    tech: "Printed article with line numbers",
    tech_purpose: "Precise citation needs stable references",
    ai_prompts: ["Generate claims with two quotes of differing strength", "Write inference questions with single-sentence clues"],
    assessment: ["Check all three parts appear", "Confirm the stronger quote is justified", "Read links for real reasoning"],
    why_it_works: ["The link is what students drop, so practise it alone", "Comparing two valid quotes teaches selection", "Inference evidence needs the gap modelled explicitly", "Colour coding makes paragraph structure visible"],
  },
  {
    standard_code: "SL.7.1",
    title: "Questions That Open Things Up",
    badge: "Grade 7",
    route_name: "Structured Discussion",
    route_line: "Ban yes-or-no → Practise probes → Respond, do not restart",
    success_criteria: ["Asks a question that cannot be answered in one word", "Responds to the previous speaker", "Contributes relevant observations"],
    steps: [
      { name: "Retrieve Discussion Moves", minutes: 5, body: "Recall the talk moves from memory before the chart appears.", science_tag: "retrieval" },
      { name: "Closed or Open", minutes: 10, body: "Sort questions by whether one word answers them. The sort defines the target.", science_tag: "dual-coding" },
      { name: "Turn Closed Into Open", minutes: 12, body: "Rewrite closed questions so they need elaboration. This is the specific grade 7 skill.", science_tag: "elaboration" },
      { name: "Probe Stems", minutes: 10, body: "'What makes you say that?' 'How does that fit with…?' Give the stems, then rehearse in pairs.", science_tag: "dual-coding" },
      { name: "Seminar With Probes", minutes: 15, body: "Full discussion. Every contribution must respond to the previous one. Teacher silent.", science_tag: "collaborative" },
      { name: "Tally the Probes", minutes: 5, body: "Outer circle counts open questions and the elaborations they produced.", science_tag: "interleaving" },
      { name: "Write One Probe", minutes: 3, body: "Given a statement, write a question that would draw more out.", science_tag: "spaced" },
    ],
    ef_supports: ["Closed versus open sorting", "Probe stem chart", "Inner and outer circle", "Tally sheets"],
    tech: "Printed question cards and tallies",
    tech_purpose: "Sorting questions physically before using them",
    ai_prompts: ["Generate closed questions for students to open up", "Write probe stems suited to grade 7 texts"],
    assessment: ["Check rewritten questions are genuinely open", "Count probes and the elaborations following", "Review written probes"],
    why_it_works: ["Sorting closed from open defines the target concretely", "Rewriting is harder than recognising, and proves more", "Stems give a starting point when nerves take over", "Counting the elaborations produced measures effect, not just effort"],
  },
  {
    standard_code: "L.7.4",
    title: "Guess, Then Check",
    badge: "Grade 7",
    route_name: "Strategy Instruction",
    route_line: "Infer from clues → Verify in a reference → Sharpen the meaning",
    success_criteria: ["Proposes a meaning before looking it up", "Verifies against a reference", "Notes the gap between guess and definition"],
    steps: [
      { name: "Retrieve Roots", minutes: 5, body: "Rapid recall of taught roots and affixes. These compound across a year.", science_tag: "retrieval" },
      { name: "Guess Before You Look", minutes: 10, body: "Establish the order. Looking up first skips the thinking that makes a word stick.", science_tag: "elaboration" },
      { name: "Two Sources of Clues", minutes: 12, body: "Context and word parts. Use both on the same word and compare what each suggests.", science_tag: "dual-coding" },
      { name: "Verify It", minutes: 10, body: "Now the dictionary. Choose the sense that fits the sentence, not the first listed.", science_tag: "elaboration" },
      { name: "Mind the Gap", minutes: 12, body: "How close was the guess? The gap is where precision gets learned, so record it.", science_tag: "elaboration" },
      { name: "Mixed Practice", minutes: 8, body: "Words yielding to different strategies. Choosing is the skill.", science_tag: "interleaving" },
      { name: "One Word, Three Steps", minutes: 3, body: "Guess, verify, note the gap.", science_tag: "spaced" },
    ],
    ef_supports: ["Guess-verify-gap recording sheet", "Root and affix chart", "Dictionary sense selection practice", "Both clue sources used on one word"],
    tech: "Dictionaries and passages",
    tech_purpose: "Verification needs a real reference",
    ai_prompts: ["Generate grade 7 words where context and word parts suggest different things", "Create multi-sense entries for selection practice"],
    assessment: ["Check a guess precedes the lookup", "Confirm the chosen sense fits", "Review recorded gaps"],
    why_it_works: ["Guessing first is what makes the verified meaning stick", "Comparing two clue sources shows they can disagree", "Recording the gap is where precision is actually learned", "Choosing among dictionary senses is the real reference skill"],
  },
  {
    standard_code: "K.OA.A.3",
    title: "How Many Ways to Make Five?",
    badge: "Kindergarten",
    route_name: "Concrete-Representational-Abstract",
    route_line: "Break it up → Find another way → Record it",
    success_criteria: ["Splits a number into two parts", "Finds more than one way", "Records a decomposition as a drawing or equation"],
    steps: [
      { name: "Count and Compare", minutes: 5, body: "Count small sets. Accurate counting underpins everything here.", science_tag: "retrieval" },
      { name: "Spill the Beans", minutes: 12, body: "Five two-colour counters shaken and spilled. However they land is a way to make five.", science_tag: "dual-coding" },
      { name: "Another Way", minutes: 10, body: "Spill again. A different split. Repeating shows there are several, not one.", science_tag: "elaboration" },
      { name: "Record Each One", minutes: 12, body: "Draw the split or write 3 + 2 = 5. Symbols attached to something that happened.", science_tag: "dual-coding" },
      { name: "Have We Found Them All?", minutes: 10, body: "Work systematically: 5 and 0, 4 and 1, 3 and 2. Order reveals completeness.", science_tag: "elaboration" },
      { name: "Same Two, Different Order", minutes: 8, body: "Is 2 and 3 the same as 3 and 2? Rearrange the same counters and discuss.", science_tag: "interleaving" },
      { name: "Show One Way", minutes: 3, body: "Split a number and record it.", science_tag: "spaced" },
    ],
    ef_supports: ["Two-colour counters", "Recording sheet with number bond frames", "Systematic ordering", "Small numbers before larger"],
    tech: "Two-colour counters and cups",
    tech_purpose: "Spilling generates decompositions without the teacher choosing them",
    ai_prompts: ["Generate decomposition recording sheets for numbers to 10", "Create systematic listing prompts"],
    assessment: ["Check more than one way is found", "Confirm recordings match the counters", "Watch the systematic search"],
    why_it_works: ["Spilling produces the decompositions rather than the teacher supplying them", "Repeating shows multiplicity, which is the standard's point", "Systematic ordering introduces completeness early", "Recording ties symbols to something that physically happened"],
  },
  {
    standard_code: "1.MD.A.1",
    title: "Longest to Shortest",
    badge: "Grade 1",
    route_name: "Concrete Practice",
    route_line: "Compare two → Order three → Use string for the rest",
    success_criteria: ["Orders three objects by length", "Lines objects up at a common start", "Compares two fixed objects using a third"],
    steps: [
      { name: "Retrieve Direct Comparison", minutes: 5, body: "Which of these two is longer? Line them up first.", science_tag: "retrieval" },
      { name: "Find the Longest of Three", minutes: 10, body: "Three objects. Longest first, then shortest, then the middle falls out.", science_tag: "dual-coding" },
      { name: "Order Them All", minutes: 12, body: "Arrange from shortest to longest. Comparing in pairs is not enough — all three at once.", science_tag: "elaboration" },
      { name: "Things You Cannot Move", minutes: 12, body: "Is the door longer than the bookshelf? They cannot be lined up. What now?", science_tag: "elaboration" },
      { name: "String Solves It", minutes: 10, body: "Cut string to one object, carry it to the other. The third object carries the length.", science_tag: "dual-coding" },
      { name: "Prove It", minutes: 8, body: "Pairs use string to compare two fixed things and report which is longer.", science_tag: "collaborative" },
      { name: "Order Three", minutes: 3, body: "Three objects ordered and described.", science_tag: "spaced" },
    ],
    ef_supports: ["Common start line", "String for indirect comparison", "Objects with clear differences first", "Order language frames"],
    tech: "String, scissors, classroom objects",
    tech_purpose: "String is the third object that makes indirect comparison possible",
    ai_prompts: ["List object trios with clear length differences", "Generate indirect comparison challenges"],
    assessment: ["Check all three are compared, not just pairs", "Watch the common start", "Confirm string is used correctly"],
    why_it_works: ["The immovable-objects problem creates the need for indirect comparison", "String makes transitivity physical rather than logical", "Ordering three at once is harder than two comparisons", "Finding the extremes first gives a strategy"],
  },
  {
    standard_code: "2.OA.A.1",
    title: "Problems That Hide a Second Step",
    badge: "Grade 2",
    route_name: "Strategy Instruction",
    route_line: "Draw the structure → Find the hidden step → Answer the actual question",
    success_criteria: ["Draws a model matching the problem", "Identifies both steps before calculating", "Answers what was actually asked"],
    steps: [
      { name: "Retrieve One-Step Problems", minutes: 5, body: "Two quick single-operation problems. The base before doubling it.", science_tag: "retrieval" },
      { name: "Draw Before Deciding", minutes: 10, body: "Bar models for the four problem types. The drawing decides the operation.", science_tag: "dual-coding" },
      { name: "The Keyword Trap", minutes: 10, body: "A compare problem containing 'more' that needs subtraction. Let the keyword strategy fail publicly.", science_tag: "elaboration" },
      { name: "The Hidden Question", minutes: 14, body: "Two-step problems contain a question nobody asked. Find it before calculating anything.", science_tag: "elaboration" },
      { name: "Underline the Ask", minutes: 10, body: "What does the question actually want? Stopping after step one is the commonest error.", science_tag: "interleaving" },
      { name: "Solve a Mixed Set", minutes: 10, body: "One- and two-step problems shuffled, so the number of steps must be judged.", science_tag: "interleaving" },
      { name: "One Problem Through", minutes: 3, body: "Draw, find the steps, solve, check the question was answered.", science_tag: "spaced" },
    ],
    ef_supports: ["Bar model templates", "Underline-the-question routine", "Mixed one- and two-step sets", "Draw before choosing an operation"],
    tech: "Printed problem cards and model templates",
    tech_purpose: "Drawing the structure is what decides the operation",
    ai_prompts: ["Generate two-step problems whose first answer is not the final one", "Write compare problems where the keyword misleads"],
    assessment: ["Check the model matches the situation", "Watch for first-step answers submitted", "Confirm mixed sets are judged not assumed"],
    why_it_works: ["Bar models make the structure decide the operation", "Letting keywords fail publicly is more convincing than banning them", "Naming the hidden question is the specific two-step skill", "Mixed sets stop students assuming every problem has two steps"],
  },
  {
    standard_code: "3.MD.A.1",
    title: "Reading the Clock to the Minute",
    badge: "Grade 3",
    route_name: "Concrete Practice",
    route_line: "Sort the hands → Count round → Work out how long",
    success_criteria: ["Reads a clock to the nearest minute", "Distinguishes the two hands reliably", "Calculates an elapsed time"],
    steps: [
      { name: "Retrieve Skip Counting", minutes: 5, body: "By fives to sixty. The clock face is a skip counting track.", science_tag: "retrieval" },
      { name: "Two Hands, Two Jobs", minutes: 10, body: "Colour the hands differently on a demonstration clock. Reading them backwards is the classic error.", science_tag: "dual-coding" },
      { name: "Count by Fives, Then Ones", minutes: 12, body: "Land on the nearest five, then count single minutes. A two-stage method that always works.", science_tag: "dual-coding" },
      { name: "Set the Clock", minutes: 10, body: "Given a time, students set their own geared clocks. Producing is harder than reading.", science_tag: "elaboration" },
      { name: "How Long Did It Take?", minutes: 12, body: "Elapsed time on a number line marked in minutes. Counting on, not subtracting.", science_tag: "elaboration" },
      { name: "Cross the Hour", minutes: 8, body: "10:50 to 11:20. Crossing the hour is where subtraction breaks and counting on holds.", science_tag: "interleaving" },
      { name: "Read and Calculate", minutes: 3, body: "One clock read, one interval calculated.", science_tag: "spaced" },
    ],
    ef_supports: ["Geared demonstration clocks", "Colour-coded hands", "Number line marked in minutes", "Two-stage counting method"],
    tech: "Individual geared clocks",
    tech_purpose: "Setting a time is a different skill from reading one",
    ai_prompts: ["Generate elapsed time problems crossing the hour", "Create clock reading sets at minute precision"],
    assessment: ["Watch for hands read backwards", "Check the two-stage count", "Confirm elapsed time uses counting on"],
    why_it_works: ["Colour-coding the hands addresses the dominant confusion", "Fives-then-ones is a method that always works", "Setting a clock proves understanding that reading can fake", "Counting on survives the hour boundary where subtraction fails"],
  },
  {
    standard_code: "4.NBT.B.6",
    title: "Dividing in Chunks",
    badge: "Grade 4",
    route_name: "Strategy Instruction",
    route_line: "Estimate → Take out chunks → Record the method",
    success_criteria: ["Estimates the quotient first", "Uses partial quotients accurately", "Interprets the remainder"],
    steps: [
      { name: "Retrieve Multiplication Facts", minutes: 5, body: "Facts within 100. Division leans entirely on these.", science_tag: "retrieval" },
      { name: "Estimate the Answer", minutes: 8, body: "Roughly how many times does it go? Estimating first makes a wrong answer visible.", science_tag: "elaboration" },
      { name: "Take Out Easy Chunks", minutes: 14, body: "How many tens of the divisor fit? Take them out, then more. Partial quotients before the algorithm.", science_tag: "dual-coding" },
      { name: "Record the Chunks", minutes: 10, body: "Each chunk written and totalled. The record is the method, not an afterthought.", science_tag: "dual-coding" },
      { name: "The Zero Problem", minutes: 12, body: "A quotient with a zero inside it. Place value columns keep every position accounted for.", science_tag: "elaboration" },
      { name: "What Is Left Over", minutes: 8, body: "Interpret the remainder in context — the same four options as in multistep problems.", science_tag: "interleaving" },
      { name: "One Division Through", minutes: 3, body: "Estimate, chunk, total, interpret.", science_tag: "spaced" },
    ],
    ef_supports: ["Partial quotient recording frame", "Estimate-first step", "Place value columns", "Multiplication facts posted"],
    tech: "Printed recording frames",
    tech_purpose: "Partial quotients need somewhere to be listed and totalled",
    ai_prompts: ["Generate divisions with clean partial quotients", "Create problems whose quotients contain a zero"],
    assessment: ["Check estimates precede answers", "Confirm chunks total correctly", "Watch the zero-in-quotient problems"],
    why_it_works: ["Partial quotients let students use chunks they are confident with", "Estimating first turns checking into comparison", "The zero-in-quotient case is where the standard algorithm silently fails", "Recording chunks makes the method inspectable"],
  },
  {
    standard_code: "5.NBT.B.7",
    title: "Where Does the Point Go?",
    badge: "Grade 5",
    route_name: "Concrete-Representational-Abstract",
    route_line: "Model on a grid → Estimate → Justify the point",
    success_criteria: ["Aligns decimals by place value", "Estimates before computing", "Explains where the decimal point belongs"],
    steps: [
      { name: "Retrieve Decimal Place Value", minutes: 5, body: "Name the places either side of the point. The ground for everything here.", science_tag: "retrieval" },
      { name: "Line Up the Point", minutes: 10, body: "Not the last digit — the point. Add trailing zeros so both numbers have the same places.", science_tag: "dual-coding" },
      { name: "Model on Hundred Grids", minutes: 12, body: "0.3 × 0.4 shaded across and down. The overlap is the product, and it is smaller.", science_tag: "dual-coding" },
      { name: "Estimate to Place the Point", minutes: 12, body: "4.2 × 3 must be about 12, so 126 is wrong and 12.6 is right. Estimation places the point.", science_tag: "elaboration" },
      { name: "Dividing by a Decimal", minutes: 10, body: "How many 0.2s in 1.6? Measurement division, modelled before any shifting rule.", science_tag: "elaboration" },
      { name: "Mixed Operations", minutes: 8, body: "All four shuffled. Mixing forces reading rather than repeating.", science_tag: "interleaving" },
      { name: "Justify a Point", minutes: 3, body: "One computation with the point placement explained.", science_tag: "spaced" },
    ],
    ef_supports: ["Hundred grids for products", "Trailing zeros for alignment", "Estimate-to-place-the-point routine", "Measurement division models"],
    tech: "Printed hundred grids",
    tech_purpose: "The shrinking product needs to be seen",
    ai_prompts: ["Generate decimal computations suited to grid models", "Create estimation checks for decimal placement"],
    assessment: ["Check alignment by point, not last digit", "Confirm estimates precede answers", "Ask for point placement justifications"],
    why_it_works: ["Estimation places the decimal point by reasoning rather than rule", "Grid models show why a product of decimals shrinks", "Aligning by the point addresses the dominant error", "Measurement division makes dividing by a decimal sensible"],
  },
  {
    standard_code: "6.EE.B.7",
    title: "Keeping the Equation Balanced",
    badge: "Grade 6",
    route_name: "Concrete-Representational-Abstract",
    route_line: "Balance it → Undo the operation → Write it from a story",
    success_criteria: ["Performs the same operation on both sides", "Uses the inverse to isolate the variable", "Writes an equation from a situation"],
    steps: [
      { name: "Retrieve the Equal Sign", minutes: 5, body: "What does equals mean? Both sides the same. The whole method rests on this.", science_tag: "retrieval" },
      { name: "A Balance With a Bag", minutes: 12, body: "A bag of unknown counters plus three, balancing eight. Remove three from both sides. Physical first.", science_tag: "dual-coding" },
      { name: "Record the Move", minutes: 10, body: "What you did to the balance, written down. The notation records a physical action.", science_tag: "dual-coding" },
      { name: "Inverse Operations", minutes: 12, body: "Addition is undone by subtraction, multiplication by division. Name the pattern.", science_tag: "elaboration" },
      { name: "Guessing Is Not Solving", minutes: 10, body: "An equation with an ugly answer. Guessing fails; the inverse works. The point makes itself.", science_tag: "elaboration" },
      { name: "From Story to Equation", minutes: 10, body: "Write the equation from a situation, then solve it. Modelling and solving as separate skills.", science_tag: "interleaving" },
      { name: "Solve and Check", minutes: 3, body: "One equation solved, with the answer substituted back.", science_tag: "spaced" },
    ],
    ef_supports: ["Balance scale with bags and counters", "Record-the-move routine", "Inverse operation pairs chart", "Substitution check"],
    tech: "Balance scale, bags, counters",
    tech_purpose: "Doing the same thing to both sides has to be seen to be believed",
    ai_prompts: ["Generate equations with non-obvious solutions", "Create situations modelled by one-step equations"],
    assessment: ["Check both sides are operated on", "Watch for guessing", "Confirm substitution checks"],
    why_it_works: ["A physical balance makes the both-sides rule obvious rather than arbitrary", "An ugly answer kills guessing as a strategy", "Recording the move connects notation to action", "Separating modelling from solving clarifies which is hard"],
  },
  {
    standard_code: "7.RP.A.3",
    title: "Percent of What?",
    badge: "Grade 7",
    route_name: "Strategy Instruction",
    route_line: "Find the base → Compute the change → Chain two steps",
    success_criteria: ["Identifies what the percentage is of", "Computes increases and decreases", "Handles two-step percent problems"],
    steps: [
      { name: "Retrieve Percent Basics", minutes: 5, body: "Find 10%, 25%, 50% of a number mentally. Benchmarks make everything else checkable.", science_tag: "retrieval" },
      { name: "Percent of What?", minutes: 12, body: "The base is what the percentage refers to, and it moves. Ask the question before every calculation.", science_tag: "elaboration" },
      { name: "Increase and Decrease", minutes: 12, body: "A 20% rise means 120% of the original. One multiplication, not two steps.", science_tag: "dual-coding" },
      { name: "Up 20, Down 20", minutes: 12, body: "Does it return to the start? Work a concrete example. It does not, and the reason is the base changed.", science_tag: "elaboration" },
      { name: "Tax, Tip and Discount", minutes: 10, body: "Real contexts. Which base does each apply to? Order matters when they chain.", science_tag: "interleaving" },
      { name: "Two-Step Problems", minutes: 10, body: "Discount then tax. Two bases, one after the other.", science_tag: "interleaving" },
      { name: "Name the Base", minutes: 3, body: "Given a problem, say what each percentage is of before solving.", science_tag: "spaced" },
    ],
    ef_supports: ["Percent-of-what routine", "Benchmark percents for checking", "Concrete up-then-down example", "Two-step chaining practice"],
    tech: "Printed real-world price problems",
    tech_purpose: "Contexts make the base concrete",
    ai_prompts: ["Generate two-step percent problems chaining discount and tax", "Create percent change problems with shifting bases"],
    assessment: ["Check the base is named before computing", "Confirm the up-then-down result is understood", "Review two-step ordering"],
    why_it_works: ["Naming the base prevents the dominant percent error", "The up-then-down surprise is memorable and explains why the base matters", "Single-multiplication increases are faster and less error-prone", "Real prices make the maths obviously useful"],
  },
  {
    standard_code: "8.EE.A.1",
    title: "Why the Exponent Rules Work",
    badge: "Grade 8",
    route_name: "Explicit Instruction",
    route_line: "Expand it out → Spot the rule → Extend to zero and negatives",
    success_criteria: ["Applies product and quotient rules", "Handles a power of a power", "Explains zero and negative exponents"],
    steps: [
      { name: "Retrieve Powers", minutes: 5, body: "Evaluate small powers. The meaning before the manipulation.", science_tag: "retrieval" },
      { name: "Write It Out Longhand", minutes: 12, body: "2³ × 2⁴ written as seven twos multiplied. Count them. The rule is a shortcut for counting.", science_tag: "elaboration" },
      { name: "Only With the Same Base", minutes: 10, body: "2³ × 3⁴ cannot be combined. Expand both to see why the rule fails.", science_tag: "elaboration" },
      { name: "Power of a Power", minutes: 10, body: "(2³)² expanded is six twos. Multiplying rather than adding the exponents, seen not asserted.", science_tag: "dual-coding" },
      { name: "Down Through Zero", minutes: 14, body: "2³, 2², 2¹, 2⁰, 2⁻¹. Halving each time. Zero gives one and negatives give fractions, by pattern.", science_tag: "dual-coding" },
      { name: "Mixed Simplification", minutes: 8, body: "All rules shuffled. Choosing which applies is the skill.", science_tag: "interleaving" },
      { name: "Explain One Rule", minutes: 3, body: "Explain why a negative exponent gives a fraction.", science_tag: "spaced" },
    ],
    ef_supports: ["Longhand expansion before rules", "Same-base requirement demonstrated", "Halving pattern table through zero", "Mixed practice for selection"],
    tech: "Printed expansion frames",
    tech_purpose: "Writing powers out longhand is what makes the rules obvious",
    ai_prompts: ["Generate expressions requiring different exponent rules", "Create halving pattern tables extending past zero"],
    assessment: ["Watch for exponents added across different bases", "Check negative exponents give fractions not negatives", "Ask for rule explanations"],
    why_it_works: ["Expanding longhand makes each rule a counting shortcut rather than a decree", "The different-base failure shows rules have conditions", "The halving pattern derives zero and negative exponents rather than asserting them", "Mixed practice teaches rule selection"],
  },
  {
    standard_code: "8.G.C.9",
    title: "Cones, Cylinders and Spheres",
    badge: "Grade 8",
    route_name: "Concrete Practice",
    route_line: "Pour to find the relationship → Learn the formulas → Choose the right one",
    success_criteria: ["Identifies the solid before computing", "Uses radius rather than diameter", "Applies the correct volume formula"],
    steps: [
      { name: "Retrieve Circle Area", minutes: 5, body: "Area of a circle. Every formula here contains it.", science_tag: "retrieval" },
      { name: "Cylinder Is Stacked Circles", minutes: 10, body: "Area of the circle times the height. Volume as repeated area, same as prisms.", science_tag: "elaboration" },
      { name: "Pour the Cone", minutes: 14, body: "Fill a cone with rice and empty it into a cylinder of the same base and height. Three times exactly. The one-third earns itself.", science_tag: "dual-coding" },
      { name: "The Sphere Formula", minutes: 10, body: "Four thirds pi r cubed. Relate it to the cylinder it sits inside rather than presenting it bare.", science_tag: "dual-coding" },
      { name: "Radius, Not Diameter", minutes: 10, body: "Problems giving diameter. Mark the radius on the diagram before substituting. The dominant error.", science_tag: "elaboration" },
      { name: "Which Solid Is It?", minutes: 10, body: "Mixed problems. Identify the solid, then choose the formula. Sorting before computing.", science_tag: "interleaving" },
      { name: "One of Each", minutes: 3, body: "One cylinder, one cone, correct formulas used.", science_tag: "spaced" },
    ],
    ef_supports: ["Cone and cylinder pair for pouring", "Mark-the-radius routine", "Formula reference sheet", "Identify-the-solid step"],
    tech: "Cone and cylinder models, rice",
    tech_purpose: "Pouring three cones into a cylinder proves the one-third",
    ai_prompts: ["Generate volume problems giving diameter rather than radius", "Create mixed solid identification sets"],
    assessment: ["Check radius is used", "Confirm the solid is identified first", "Watch formula selection"],
    why_it_works: ["Pouring makes the one-third a discovery instead of an arbitrary fraction", "Relating the sphere to its cylinder gives the formula a home", "The diameter trap catches most students, so target it", "Identifying the solid first prevents formula roulette"],
  },
];

await seedStandardsBatch({
  label: "Batch 7",
  standardsData,
  unpacksData,
  blueprintsData,
});
