// @ts-nocheck
/**
 * Batch 4: 20 more drafted standards.
 *
 * Depth rather than breadth this time — the strands and domains are all open,
 * so this fills the grades between what is already there and adds the
 * standards teachers search for most: two-step word problems, the equal sign,
 * the coordinate plane, citing evidence, and fluency at grade 4.
 *
 *   bun run scripts/seed-standards-batch-4.ts
 */
import { seedStandardsBatch } from "./lib/seed-standards-batch";

const standardsData = [
  // ─── ELA ────────────────────────────────────────────────────────────────
  {
    code: "RF.K.3",
    name: "Match letters to the sounds they make",
    plain_reading:
      "Know and apply grade-level phonics and word analysis skills in decoding words, including letter-sound correspondences for consonants and the five major vowels, and reading common high-frequency words by sight.",
    learning_target: "I know the sound each letter makes, and I can read some words straight away.",
    skills: ["Letter-Sound Correspondence", "Decoding", "Sight Words"],
    science_tags: ["retrieval", "spaced"],
    match_keys: ["letter sounds", "phonics kindergarten", "high frequency words", "sight words", "decoding"],
  },
  {
    code: "L.1.4",
    name: "Work out what a new word means",
    plain_reading:
      "Determine or clarify the meaning of unknown and multiple-meaning words and phrases based on grade 1 reading and content, choosing flexibly from an array of strategies including sentence-level context and common affixes.",
    learning_target: "I can use the rest of the sentence to work out a word I do not know.",
    skills: ["Vocabulary", "Context Clues", "Word Parts"],
    science_tags: ["elaboration", "dual-coding"],
    match_keys: ["context clues", "unknown words", "multiple meaning", "affixes", "grade 1 vocabulary"],
  },
  {
    code: "RI.2.1",
    name: "Ask and answer questions about a nonfiction text",
    plain_reading:
      "Ask and answer such questions as who, what, where, when, why, and how to demonstrate understanding of key details in a text.",
    learning_target: "I can ask and answer all six kinds of question about a true text.",
    skills: ["Comprehension", "Questioning", "Key Details"],
    science_tags: ["retrieval", "elaboration"],
    match_keys: ["who what where when why how", "informational text", "key details", "ask and answer"],
  },
  {
    code: "SL.3.1",
    name: "Take part in a discussion and build on others",
    plain_reading:
      "Engage effectively in a range of collaborative discussions with diverse partners on grade 3 topics and texts, building on others' ideas and expressing their own clearly, following agreed-upon rules for discussions.",
    learning_target: "I can listen, follow our talking rules, and add to what someone else said.",
    skills: ["Discussion", "Active Listening", "Turn Taking"],
    science_tags: ["collaborative", "elaboration"],
    match_keys: ["collaborative discussion", "discussion rules", "build on ideas", "turn taking", "grade 3 speaking"],
  },
  {
    code: "RF.4.4",
    name: "Read grade 4 text smoothly and accurately",
    plain_reading:
      "Read with sufficient accuracy and fluency to support comprehension, reading grade-level prose and poetry orally with accuracy, appropriate rate, and expression on successive readings.",
    learning_target: "I can read longer texts smoothly enough that the meaning still comes through.",
    skills: ["Fluency", "Accuracy", "Expression"],
    science_tags: ["retrieval", "spaced"],
    match_keys: ["fluency", "reading rate", "expression", "prosody", "grade 4 fluency", "oral reading"],
  },
  {
    code: "RL.5.1",
    name: "Quote accurately to explain and infer",
    plain_reading:
      "Quote accurately from a text when explaining what the text says explicitly and when drawing inferences from the text.",
    learning_target: "I can use the author's exact words to back up what I say about a story.",
    skills: ["Textual Evidence", "Quoting", "Inference"],
    science_tags: ["elaboration", "interleaving"],
    match_keys: ["quote accurately", "textual evidence", "inference", "explicitly", "cite the text"],
  },
  {
    code: "W.5.3",
    name: "Write a narrative with technique and detail",
    plain_reading:
      "Write narratives to develop real or imagined experiences or events using effective technique, descriptive details, and clear event sequences, including dialogue, pacing, and description.",
    learning_target: "I can tell a story that uses dialogue and pacing to pull a reader along.",
    skills: ["Narrative Writing", "Dialogue", "Pacing"],
    science_tags: ["elaboration", "spaced"],
    match_keys: ["narrative writing", "dialogue", "pacing", "descriptive details", "story writing grade 5"],
  },
  {
    code: "RL.6.1",
    name: "Cite evidence for what a text says and implies",
    plain_reading:
      "Cite textual evidence to support analysis of what the text says explicitly as well as inferences drawn from the text.",
    learning_target: "I can point to the words that support both what the text says and what it hints at.",
    skills: ["Textual Evidence", "Analysis", "Inference"],
    science_tags: ["elaboration", "interleaving"],
    match_keys: ["cite textual evidence", "analysis", "inference", "explicitly", "support with evidence"],
  },
  {
    code: "L.6.4",
    name: "Work out unfamiliar words in grade 6 texts",
    plain_reading:
      "Determine or clarify the meaning of unknown and multiple-meaning words and phrases based on grade 6 reading and content, choosing flexibly from a range of strategies including context, Greek and Latin affixes, and reference materials.",
    learning_target: "I can use context, word parts and a dictionary to pin down a word's meaning.",
    skills: ["Vocabulary", "Morphology", "Reference Skills"],
    science_tags: ["elaboration", "interleaving"],
    match_keys: ["context clues", "greek latin roots", "affixes", "dictionary", "multiple meaning words"],
  },
  {
    code: "RI.8.5",
    name: "Analyse the structure of a paragraph",
    plain_reading:
      "Analyze in detail the structure of a specific paragraph in a text, including the role of particular sentences in developing and refining a key concept.",
    learning_target: "I can explain what each sentence in a paragraph is doing for the idea.",
    skills: ["Text Structure", "Analysis", "Authorial Craft"],
    science_tags: ["elaboration", "dual-coding"],
    match_keys: ["paragraph structure", "role of sentences", "develop and refine", "key concept", "analyze structure"],
  },

  // ─── Mathematics ────────────────────────────────────────────────────────
  {
    code: "K.G.A.2",
    name: "Name shapes however they are turned",
    plain_reading:
      "Correctly name shapes regardless of their orientations or overall size.",
    learning_target: "I know a triangle is still a triangle even when it is turned or tiny.",
    skills: ["Shape Recognition", "Geometric Vocabulary", "Orientation"],
    science_tags: ["dual-coding", "interleaving"],
    match_keys: ["name shapes", "triangle", "rectangle", "orientation", "shape recognition"],
  },
  {
    code: "1.OA.D.7",
    name: "Understand what the equal sign means",
    plain_reading:
      "Understand the meaning of the equal sign, and determine if equations involving addition and subtraction are true or false.",
    learning_target: "I know the equal sign means both sides are worth the same.",
    skills: ["Equality", "Equations", "Number Sense"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["equal sign", "true or false equations", "balance", "same amount", "equality"],
  },
  {
    code: "2.G.A.3",
    name: "Split shapes into halves, thirds and fourths",
    plain_reading:
      "Partition circles and rectangles into two, three, or four equal shares, describe the shares using the words halves, thirds, half of, a third of, and recognize that equal shares of identical wholes need not have the same shape.",
    learning_target: "I can split a shape into equal parts and name them, even if they look different.",
    skills: ["Partitioning", "Equal Shares", "Fraction Language"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["halves thirds fourths", "equal shares", "partition", "same size different shape"],
  },
  {
    code: "3.OA.D.8",
    name: "Solve two-step word problems",
    plain_reading:
      "Solve two-step word problems using the four operations. Represent these problems using equations with a letter standing for the unknown quantity, and assess the reasonableness of answers.",
    learning_target: "I can solve a problem that needs two steps and check my answer makes sense.",
    skills: ["Multi-Step Problems", "Equations", "Reasonableness"],
    science_tags: ["interleaving", "elaboration"],
    match_keys: ["two step word problems", "four operations", "unknown quantity", "reasonableness", "estimation"],
  },
  {
    code: "4.NF.C.6",
    name: "Write fractions as decimals",
    plain_reading:
      "Use decimal notation for fractions with denominators 10 or 100, and locate these decimals on a number line.",
    learning_target: "I can write tenths and hundredths as decimals and find them on a number line.",
    skills: ["Decimals", "Fractions", "Number Line"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["decimal notation", "tenths", "hundredths", "fractions as decimals", "number line"],
  },
  {
    code: "5.G.A.1",
    name: "Plot points on the coordinate plane",
    plain_reading:
      "Use a pair of perpendicular number lines, called axes, to define a coordinate system, and understand that the first number indicates how far to travel from the origin along the first axis and the second number how far along the second.",
    learning_target: "I can plot a point using its two numbers, in the right order.",
    skills: ["Coordinate Plane", "Ordered Pairs", "Graphing"],
    science_tags: ["dual-coding", "retrieval"],
    match_keys: ["coordinate plane", "ordered pairs", "x axis", "y axis", "origin", "plot points"],
  },
  {
    code: "6.NS.C.6",
    name: "Place rational numbers on a number line",
    plain_reading:
      "Understand a rational number as a point on the number line, extending number line diagrams and coordinate axes to represent points with negative coordinates.",
    learning_target: "I can put positive and negative numbers in the right place on a number line.",
    skills: ["Rational Numbers", "Number Line", "Opposites"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["negative numbers", "number line", "opposites", "rational numbers", "four quadrants"],
  },
  {
    code: "6.SP.B.5",
    name: "Summarise a data set",
    plain_reading:
      "Summarize numerical data sets in relation to their context, reporting the number of observations, describing the attribute measured, and giving measures of centre and variability.",
    learning_target: "I can describe a set of data with a typical value and how spread out it is.",
    skills: ["Statistics", "Measures of Centre", "Variability"],
    science_tags: ["elaboration", "dual-coding"],
    match_keys: ["mean median mode", "range", "variability", "summarize data", "measures of center"],
  },
  {
    code: "7.NS.A.2",
    name: "Multiply and divide rational numbers",
    plain_reading:
      "Apply and extend previous understandings of multiplication and division and of fractions to multiply and divide rational numbers, including understanding the rules for signs.",
    learning_target: "I can multiply and divide positive and negative numbers and explain the sign.",
    skills: ["Rational Numbers", "Sign Rules", "Fraction Operations"],
    science_tags: ["interleaving", "elaboration"],
    match_keys: ["multiply negative numbers", "divide rational numbers", "sign rules", "integers"],
  },
  {
    code: "8.EE.B.5",
    name: "Graph proportional relationships and read slope",
    plain_reading:
      "Graph proportional relationships, interpreting the unit rate as the slope of the graph, and compare two different proportional relationships represented in different ways.",
    learning_target: "I can graph a proportional relationship and say what its steepness means.",
    skills: ["Slope", "Proportional Relationships", "Graph Interpretation"],
    science_tags: ["dual-coding", "interleaving"],
    match_keys: ["slope", "unit rate", "proportional relationships", "graph", "compare rates"],
  },
];

const unpacksData = [
  {
    standard_code: "RF.K.3",
    verbs: [
      { word: "Know", gloss: "hold the letter sounds in memory" },
      { word: "Apply", gloss: "use them to read a word" },
      { word: "Decode", gloss: "turn letters into a spoken word" },
    ],
    concepts: ["Letter-sound correspondence", "Vowels", "High-frequency words"],
    vocabulary: [
      { term: "letter", definition: "a symbol we use to write words" },
      { term: "sound", definition: "what a letter says" },
      { term: "vowel", definition: "the letters a, e, i, o, u" },
      { term: "sight word", definition: "a word you know straight away without sounding out" },
    ],
    prior_skills: ["Recognise letter shapes", "Hear the first sound in a word", "Sing the alphabet"],
    prior_standards: [{ code: "RF.K.1", text: "Understand the organisation and basic features of print" }],
    future_standards: [{ code: "RF.1.3", text: "Know and apply grade 1 phonics and word analysis skills" }],
    challenges: [
      { problem: "Letter names are given instead of sounds", fix: "Ask 'what does it say?' rather than 'what is it?'" },
      { problem: "Sight words are sounded out letter by letter", fix: "Flash them fast enough that sounding out is not possible" },
    ],
    mastery_statement: "Student can give the sound for each consonant and the five major vowels, and read common high-frequency words on sight.",
    ladder: [
      { name: "I can name the letters", descriptor: "Recognises letter shapes" },
      { name: "I can say what each letter says", descriptor: "Gives sounds for consonants" },
      { name: "I can say the vowel sounds", descriptor: "Knows the five short vowels" },
      { name: "I can read some words straight away", descriptor: "Recognises high-frequency words" },
    ],
  },
  {
    standard_code: "L.1.4",
    verbs: [
      { word: "Determine", gloss: "work out what a word means" },
      { word: "Clarify", gloss: "make a fuzzy meaning clearer" },
    ],
    concepts: ["Sentence context", "Common affixes", "Multiple meanings"],
    vocabulary: [
      { term: "clue", definition: "something that helps you work out an answer" },
      { term: "meaning", definition: "what a word tells you" },
      { term: "ending", definition: "a word part added to the back, like -ed or -s" },
      { term: "sentence", definition: "a group of words telling a whole idea" },
    ],
    prior_skills: ["Use pictures for meaning", "Ask about unknown words", "Read simple sentences"],
    prior_standards: [{ code: "L.K.4", text: "Determine the meaning of unknown words with prompting" }],
    future_standards: [{ code: "L.2.4", text: "Determine the meaning of unknown words using grade 2 strategies" }],
    challenges: [
      { problem: "Unknown words get skipped silently", fix: "Teach a hand signal for 'I do not know that one'" },
      { problem: "Guesses ignore the sentence", fix: "Read the whole sentence again before guessing" },
    ],
    mastery_statement: "Student can use sentence context and common word endings to work out an unfamiliar word.",
    ladder: [
      { name: "I can notice a word I do not know", descriptor: "Flags unfamiliar words" },
      { name: "I can reread the sentence", descriptor: "Uses context deliberately" },
      { name: "I can guess what it means", descriptor: "Proposes a plausible meaning" },
      { name: "I can check my guess fits", descriptor: "Tests it back in the sentence" },
    ],
  },
  {
    standard_code: "RI.2.1",
    verbs: [
      { word: "Ask", gloss: "pose a question about the text" },
      { word: "Answer", gloss: "respond using the text" },
      { word: "Demonstrate", gloss: "show you understood" },
    ],
    concepts: ["Question types", "Key details", "Nonfiction comprehension"],
    vocabulary: [
      { term: "question word", definition: "who, what, where, when, why or how" },
      { term: "key detail", definition: "an important piece of information" },
      { term: "fact", definition: "something true the text tells you" },
      { term: "evidence", definition: "the part of the text that proves your answer" },
    ],
    prior_skills: ["Ask questions about a text", "Locate a fact on a page", "Distinguish fiction from nonfiction"],
    prior_standards: [{ code: "RI.1.1", text: "Ask and answer questions about key details in a text" }],
    future_standards: [{ code: "RI.3.1", text: "Ask and answer questions, referring explicitly to the text" }],
    challenges: [
      { problem: "Only who and what questions are asked", fix: "Assign the harder question words deliberately" },
      { problem: "Why questions get answered from opinion", fix: "Require the sentence in the text that explains it" },
    ],
    mastery_statement: "Student can ask and answer all six question types about an informational text using its details.",
    ladder: [
      { name: "I can answer a who or what question", descriptor: "Handles literal questions" },
      { name: "I can answer where and when", descriptor: "Locates detail in the text" },
      { name: "I can answer why and how", descriptor: "Handles explanatory questions" },
      { name: "I can ask all six kinds myself", descriptor: "Generates varied questions" },
    ],
  },
  {
    standard_code: "SL.3.1",
    verbs: [
      { word: "Engage", gloss: "take an active part" },
      { word: "Build", gloss: "add to what someone else said" },
      { word: "Follow", gloss: "stick to the agreed rules" },
    ],
    concepts: ["Discussion norms", "Building on ideas", "Preparation"],
    vocabulary: [
      { term: "discussion", definition: "a talk where everyone shares ideas" },
      { term: "build on", definition: "add something to another person's idea" },
      { term: "norm", definition: "a rule the group agreed to follow" },
      { term: "turn", definition: "your moment to speak" },
    ],
    prior_skills: ["Take turns speaking", "Listen without interrupting", "Share an idea aloud"],
    prior_standards: [{ code: "SL.2.1", text: "Participate in collaborative conversations with peers" }],
    future_standards: [{ code: "SL.4.1", text: "Engage effectively in collaborative discussions" }],
    challenges: [
      { problem: "Children wait to speak rather than listen", fix: "Require the first sentence to reference the previous speaker" },
      { problem: "The same few dominate", fix: "Use talk tokens so airtime is visible" },
    ],
    mastery_statement: "Student can follow discussion norms, build explicitly on another's idea, and express their own clearly.",
    ladder: [
      { name: "I can take my turn", descriptor: "Waits and contributes" },
      { name: "I can listen to others", descriptor: "Can restate a peer's point" },
      { name: "I can build on an idea", descriptor: "Extends rather than restarts" },
      { name: "I can ask a question about it", descriptor: "Deepens the discussion" },
    ],
  },
  {
    standard_code: "RF.4.4",
    verbs: [
      { word: "Read", gloss: "decode accurately at a good pace" },
      { word: "Self-correct", gloss: "notice and fix a slip" },
    ],
    concepts: ["Accuracy", "Rate", "Prosody"],
    vocabulary: [
      { term: "fluency", definition: "reading smoothly, accurately and with expression" },
      { term: "phrasing", definition: "grouping words so they sound like talking" },
      { term: "rate", definition: "how fast you read" },
      { term: "prose", definition: "ordinary writing, not poetry" },
    ],
    prior_skills: ["Read grade 3 text fluently", "Decode multisyllable words", "Self-correct for meaning"],
    prior_standards: [{ code: "RF.3.4", text: "Read with sufficient accuracy and fluency at grade 3" }],
    future_standards: [{ code: "RF.5.4", text: "Read grade 5 text with accuracy, rate and expression" }],
    challenges: [
      { problem: "Speed rises and comprehension drops", fix: "Ask a question after every timed read" },
      { problem: "Poetry is read like prose", fix: "Mark line breaks and practise phrasing separately" },
    ],
    mastery_statement: "Student can read grade 4 prose and poetry aloud with accuracy, appropriate rate and expression.",
    ladder: [
      { name: "I can read the words correctly", descriptor: "Accurate decoding" },
      { name: "I can keep a steady pace", descriptor: "Appropriate rate" },
      { name: "I can read in phrases", descriptor: "Groups words meaningfully" },
      { name: "I can read poetry differently from prose", descriptor: "Adapts to the form" },
    ],
  },
  {
    standard_code: "RL.5.1",
    verbs: [
      { word: "Quote", gloss: "use the author's exact words" },
      { word: "Explain", gloss: "say what the text means" },
      { word: "Infer", gloss: "work out what it implies" },
    ],
    concepts: ["Accurate quoting", "Explicit and implicit meaning", "Evidence"],
    vocabulary: [
      { term: "quote", definition: "the author's exact words, copied correctly" },
      { term: "explicit", definition: "said directly in the text" },
      { term: "inference", definition: "a conclusion built from clues" },
      { term: "accurately", definition: "exactly right, word for word" },
    ],
    prior_skills: ["Refer to details in a text", "Draw an inference", "Locate supporting lines"],
    prior_standards: [{ code: "RL.4.1", text: "Refer to details and examples when explaining and inferring" }],
    future_standards: [{ code: "RL.6.1", text: "Cite textual evidence to support analysis" }],
    challenges: [
      { problem: "Quotes are paraphrased and called quotes", fix: "Check the copied words against the page, character by character" },
      { problem: "Whole paragraphs are quoted", fix: "Cap the quote at one sentence" },
    ],
    mastery_statement: "Student can quote a text accurately to support both stated meaning and inferences.",
    ladder: [
      { name: "I can find the supporting part", descriptor: "Locates relevant text" },
      { name: "I can copy it exactly", descriptor: "Quotes accurately" },
      { name: "I can use it to explain", descriptor: "Links quote to explicit meaning" },
      { name: "I can use it to support an inference", descriptor: "Links quote to implied meaning" },
    ],
  },
  {
    standard_code: "W.5.3",
    verbs: [
      { word: "Develop", gloss: "build the experience out" },
      { word: "Pace", gloss: "control how fast the story moves" },
      { word: "Describe", gloss: "show rather than tell" },
    ],
    concepts: ["Dialogue", "Pacing", "Descriptive detail"],
    vocabulary: [
      { term: "dialogue", definition: "the words characters say out loud" },
      { term: "pacing", definition: "how fast or slow the story moves" },
      { term: "narrator", definition: "the voice telling the story" },
      { term: "transitional phrase", definition: "words that move the reader through time" },
    ],
    prior_skills: ["Write a sequenced narrative", "Add sensory detail", "Punctuate dialogue"],
    prior_standards: [{ code: "W.4.3", text: "Write narratives using dialogue and description" }],
    future_standards: [{ code: "W.6.3", text: "Write narratives using relevant descriptive details and well-structured sequences" }],
    challenges: [
      { problem: "Dialogue is used for plot delivery only", fix: "Require one line that reveals character rather than events" },
      { problem: "Everything moves at the same speed", fix: "Slow the most important moment to three times its length" },
    ],
    mastery_statement: "Student can write a narrative using dialogue, pacing and description to develop the experience.",
    ladder: [
      { name: "I can write events in order", descriptor: "Clear sequence" },
      { name: "I can add description", descriptor: "Shows rather than tells" },
      { name: "I can write dialogue", descriptor: "Punctuates and uses speech" },
      { name: "I can slow down what matters", descriptor: "Controls pacing deliberately" },
    ],
  },
  {
    standard_code: "RL.6.1",
    verbs: [
      { word: "Cite", gloss: "quote and say where it came from" },
      { word: "Support", gloss: "make the evidence carry the claim" },
      { word: "Analyse", gloss: "explain how and why" },
    ],
    concepts: ["Citation", "Explicit and inferential claims", "Analysis"],
    vocabulary: [
      { term: "cite", definition: "quote and say where you found it" },
      { term: "analysis", definition: "explaining how and why, not just what" },
      { term: "inference", definition: "a conclusion drawn from clues" },
      { term: "support", definition: "back up a claim with evidence" },
    ],
    prior_skills: ["Quote accurately", "Draw inferences", "Distinguish claim from evidence"],
    prior_standards: [{ code: "RL.5.1", text: "Quote accurately when explaining and inferring" }],
    future_standards: [{ code: "RL.7.1", text: "Cite several pieces of evidence to support analysis" }],
    challenges: [
      { problem: "Quotes are dropped in without comment", fix: "Require a sentence of analysis after every quote" },
      { problem: "Evidence supports the topic but not the claim", fix: "Test each quote against the claim, not the subject" },
    ],
    mastery_statement: "Student can cite textual evidence supporting both explicit statements and inferences, and explain the link.",
    ladder: [
      { name: "I can find relevant evidence", descriptor: "Locates a supporting quote" },
      { name: "I can cite it properly", descriptor: "Quotes and attributes" },
      { name: "I can support an inference with it", descriptor: "Handles implied meaning" },
      { name: "I can explain how it supports my point", descriptor: "Adds analysis" },
    ],
  },
  {
    standard_code: "L.6.4",
    verbs: [
      { word: "Determine", gloss: "work out the meaning" },
      { word: "Clarify", gloss: "sharpen a fuzzy meaning" },
      { word: "Verify", gloss: "check it against a reference" },
    ],
    concepts: ["Context", "Greek and Latin roots", "Reference materials"],
    vocabulary: [
      { term: "root", definition: "the core part of a word carrying its meaning" },
      { term: "affix", definition: "a prefix or suffix added to a root" },
      { term: "etymology", definition: "where a word came from" },
      { term: "connotation", definition: "the feeling a word carries beyond its plain meaning" },
    ],
    prior_skills: ["Use context clues", "Recognise common affixes", "Use a dictionary"],
    prior_standards: [{ code: "L.5.4", text: "Determine the meaning of unknown words using grade 5 strategies" }],
    future_standards: [{ code: "L.7.4", text: "Determine meanings using grade 7 strategies including reference materials" }],
    challenges: [
      { problem: "The dictionary is the first move rather than the last", fix: "Require a context guess before looking it up" },
      { problem: "The first dictionary sense is taken regardless of fit", fix: "Read all senses and choose the one that fits the sentence" },
    ],
    mastery_statement: "Student can determine a word's meaning from context and word parts, then verify it against a reference.",
    ladder: [
      { name: "I can use context to guess", descriptor: "Proposes a meaning from the sentence" },
      { name: "I can break the word apart", descriptor: "Identifies root and affixes" },
      { name: "I can use a dictionary well", descriptor: "Chooses the sense that fits" },
      { name: "I can tell shades of meaning apart", descriptor: "Distinguishes connotation" },
    ],
  },
  {
    standard_code: "RI.8.5",
    verbs: [
      { word: "Analyse", gloss: "examine in detail how it is built" },
      { word: "Develop", gloss: "build an idea up" },
      { word: "Refine", gloss: "sharpen an idea already introduced" },
    ],
    concepts: ["Sentence function", "Development versus refinement", "Paragraph architecture"],
    vocabulary: [
      { term: "develop", definition: "build an idea out with more" },
      { term: "refine", definition: "make an idea more precise" },
      { term: "key concept", definition: "the main idea the paragraph is about" },
      { term: "function", definition: "the job a sentence does" },
    ],
    prior_skills: ["Analyse text structure", "Identify a central idea", "Name a paragraph's function"],
    prior_standards: [{ code: "RI.7.5", text: "Analyse the structure an author uses to organise a text" }],
    future_standards: [{ code: "RI.9-10.5", text: "Analyse how an author's ideas are developed by particular sentences and paragraphs" }],
    challenges: [
      { problem: "Sentences are summarised rather than analysed", fix: "Ban content words — describe the job only" },
      { problem: "Develop and refine are used interchangeably", fix: "Sort sentences into which they do" },
    ],
    mastery_statement: "Student can explain the role of individual sentences in developing and refining a paragraph's key concept.",
    ladder: [
      { name: "I can find the key concept", descriptor: "Names the paragraph's idea" },
      { name: "I can say what a sentence does", descriptor: "Identifies function" },
      { name: "I can tell develop from refine", descriptor: "Distinguishes the two moves" },
      { name: "I can map the whole paragraph", descriptor: "Explains the architecture" },
    ],
  },
  {
    standard_code: "K.G.A.2",
    verbs: [{ word: "Name", gloss: "say which shape it is" }],
    concepts: ["Shape attributes", "Orientation", "Size invariance"],
    vocabulary: [
      { term: "triangle", definition: "a shape with three straight sides" },
      { term: "rectangle", definition: "a shape with four sides and four square corners" },
      { term: "side", definition: "one straight edge of a shape" },
      { term: "corner", definition: "where two sides meet" },
    ],
    prior_skills: ["Match identical shapes", "Sort by shape", "Point out shapes in the room"],
    prior_standards: [{ code: "PK.G.1", text: "Identify basic shapes in the environment" }],
    future_standards: [{ code: "1.G.A.1", text: "Distinguish defining from non-defining attributes of shapes" }],
    challenges: [
      { problem: "A rotated triangle is not recognised", fix: "Turn the same shape repeatedly while naming it" },
      { problem: "Only equilateral triangles count as triangles", fix: "Show long thin and lopsided triangles too" },
    ],
    mastery_statement: "Student can name shapes correctly whatever their size or orientation.",
    ladder: [
      { name: "I can match shapes that look the same", descriptor: "Matches by appearance" },
      { name: "I can name a shape", descriptor: "Uses correct vocabulary" },
      { name: "I can name it when it is turned", descriptor: "Orientation independent" },
      { name: "I can name it at any size", descriptor: "Size independent" },
    ],
  },
  {
    standard_code: "1.OA.D.7",
    verbs: [
      { word: "Understand", gloss: "know what the equal sign means" },
      { word: "Determine", gloss: "decide if an equation is true" },
    ],
    concepts: ["Equality as balance", "True and false equations", "Equivalence"],
    vocabulary: [
      { term: "equal", definition: "worth exactly the same" },
      { term: "equation", definition: "a number sentence with an equals sign" },
      { term: "true", definition: "both sides really are the same" },
      { term: "false", definition: "the two sides are not the same" },
    ],
    prior_skills: ["Add within 10", "Compare two amounts", "Read a number sentence"],
    prior_standards: [{ code: "K.OA.A.1", text: "Represent addition and subtraction" }],
    future_standards: [{ code: "2.OA.B.2", text: "Fluently add and subtract within 20" }],
    challenges: [
      { problem: "Equals is read as 'the answer comes next'", fix: "Write equations backwards — 7 = 4 + 3 — until it stops looking wrong" },
      { problem: "5 + 3 = 8 + 2 is called true", fix: "Model with a balance so both sides are physically compared" },
    ],
    mastery_statement: "Student can judge whether an equation is true and explain that the equal sign means both sides match.",
    ladder: [
      { name: "I can read a number sentence", descriptor: "Reads equations aloud" },
      { name: "I can solve 4 + 3 = ?", descriptor: "Answer on the right" },
      { name: "I can solve ? = 4 + 3", descriptor: "Answer on the left" },
      { name: "I can say if an equation is true", descriptor: "Compares both sides" },
    ],
  },
  {
    standard_code: "2.G.A.3",
    verbs: [
      { word: "Partition", gloss: "split into equal parts" },
      { word: "Describe", gloss: "name the parts correctly" },
      { word: "Recognise", gloss: "see that equal parts can look different" },
    ],
    concepts: ["Equal shares", "Fraction language", "Same area, different shape"],
    vocabulary: [
      { term: "half", definition: "one of two equal parts" },
      { term: "third", definition: "one of three equal parts" },
      { term: "fourth", definition: "one of four equal parts" },
      { term: "whole", definition: "all the parts together" },
    ],
    prior_skills: ["Partition into halves and quarters", "Recognise equal parts", "Name basic shapes"],
    prior_standards: [{ code: "1.G.A.3", text: "Partition circles and rectangles into halves and quarters" }],
    future_standards: [{ code: "3.NF.A.1", text: "Understand a fraction as parts of a whole" }],
    challenges: [
      { problem: "Thirds are drawn unequal", fix: "Fold and compare rather than eyeball" },
      { problem: "Differently shaped halves are called unequal", fix: "Cut and overlay to show the areas match" },
    ],
    mastery_statement: "Student can partition shapes into halves, thirds and fourths and name the shares correctly.",
    ladder: [
      { name: "I can split into two equal parts", descriptor: "Makes halves" },
      { name: "I can split into four", descriptor: "Makes fourths" },
      { name: "I can split into three", descriptor: "Makes thirds" },
      { name: "I know equal parts can look different", descriptor: "Understands area equality" },
    ],
  },
  {
    standard_code: "3.OA.D.8",
    verbs: [
      { word: "Solve", gloss: "work out the answer" },
      { word: "Represent", gloss: "write it as an equation" },
      { word: "Assess", gloss: "judge whether the answer is sensible" },
    ],
    concepts: ["Multi-step problems", "Unknown quantities", "Reasonableness"],
    vocabulary: [
      { term: "two-step", definition: "needing two calculations, not one" },
      { term: "unknown", definition: "the amount you have to work out" },
      { term: "estimate", definition: "a close-enough answer to check against" },
      { term: "reasonable", definition: "sensible for the situation" },
    ],
    prior_skills: ["Solve one-step problems", "Multiply and divide within 100", "Round numbers"],
    prior_standards: [{ code: "3.OA.A.3", text: "Use multiplication and division within 100 to solve problems" }],
    future_standards: [{ code: "4.OA.A.3", text: "Solve multistep word problems with whole numbers" }],
    challenges: [
      { problem: "Only the first step is completed", fix: "Ask what the question actually asked for before writing an answer" },
      { problem: "Wild answers go unchallenged", fix: "Require an estimate before calculating" },
    ],
    mastery_statement: "Student can solve two-step problems, represent them with an equation, and judge the answer's reasonableness.",
    ladder: [
      { name: "I can solve a one-step problem", descriptor: "Single operation" },
      { name: "I can find the hidden first step", descriptor: "Identifies both steps" },
      { name: "I can write an equation with a letter", descriptor: "Represents the unknown" },
      { name: "I can check my answer is sensible", descriptor: "Estimates and compares" },
    ],
  },
  {
    standard_code: "4.NF.C.6",
    verbs: [
      { word: "Use", gloss: "write the fraction as a decimal" },
      { word: "Locate", gloss: "find it on a number line" },
    ],
    concepts: ["Tenths and hundredths", "Decimal notation", "Equivalence"],
    vocabulary: [
      { term: "decimal", definition: "a way of writing parts of a whole using a point" },
      { term: "tenth", definition: "one of ten equal parts" },
      { term: "hundredth", definition: "one of a hundred equal parts" },
      { term: "decimal point", definition: "the dot separating whole from part" },
    ],
    prior_skills: ["Understand fractions", "Find equivalent fractions", "Use a number line"],
    prior_standards: [{ code: "4.NF.C.5", text: "Add fractions with denominators 10 and 100" }],
    future_standards: [{ code: "5.NBT.A.3", text: "Read, write and compare decimals to thousandths" }],
    challenges: [
      { problem: "0.5 is read as 'point five' with no size attached", fix: "Say 'five tenths' every time until the meaning sticks" },
      { problem: "0.7 is thought smaller than 0.25 because 7 < 25", fix: "Place both on a number line" },
    ],
    mastery_statement: "Student can write tenths and hundredths as decimals and place them on a number line.",
    ladder: [
      { name: "I can name tenths as fractions", descriptor: "Reads 3/10" },
      { name: "I can write them as decimals", descriptor: "Writes 0.3" },
      { name: "I can do the same with hundredths", descriptor: "Writes 0.25" },
      { name: "I can place decimals on a number line", descriptor: "Orders by size" },
    ],
  },
  {
    standard_code: "5.G.A.1",
    verbs: [
      { word: "Use", gloss: "work with the two axes" },
      { word: "Plot", gloss: "mark a point in the right place" },
    ],
    concepts: ["Axes", "Origin", "Ordered pairs"],
    vocabulary: [
      { term: "axis", definition: "one of the two number lines on a grid" },
      { term: "origin", definition: "the point where the axes cross, (0, 0)" },
      { term: "ordered pair", definition: "two numbers naming a point, in order" },
      { term: "coordinate", definition: "one of the two numbers locating a point" },
    ],
    prior_skills: ["Read a number line", "Understand horizontal and vertical", "Read a grid reference"],
    prior_standards: [{ code: "4.MD.A.2", text: "Solve problems involving measurement and representation" }],
    future_standards: [{ code: "6.NS.C.6", text: "Represent points with negative coordinates" }],
    challenges: [
      { problem: "The pair is read in the wrong order", fix: "Say 'along the corridor, then up the stairs' every time" },
      { problem: "Counting starts at 1 rather than the origin", fix: "Always place a finger on (0, 0) first" },
    ],
    mastery_statement: "Student can plot and read ordered pairs on a coordinate plane, moving along the first axis before the second.",
    ladder: [
      { name: "I can find the origin", descriptor: "Locates (0, 0)" },
      { name: "I can move along one axis", descriptor: "Counts horizontally" },
      { name: "I can plot a point", descriptor: "Uses both coordinates in order" },
      { name: "I can read a point off the grid", descriptor: "Names an ordered pair" },
    ],
  },
  {
    standard_code: "6.NS.C.6",
    verbs: [
      { word: "Understand", gloss: "see a number as a place on the line" },
      { word: "Extend", gloss: "carry the number line past zero" },
    ],
    concepts: ["Negative numbers", "Opposites", "Quadrants"],
    vocabulary: [
      { term: "rational number", definition: "any number that can be written as a fraction" },
      { term: "opposite", definition: "the same distance from zero, other side" },
      { term: "quadrant", definition: "one of the four regions of a coordinate plane" },
      { term: "integer", definition: "a whole number, positive, negative or zero" },
    ],
    prior_skills: ["Plot on a coordinate plane", "Order whole numbers", "Work with fractions"],
    prior_standards: [{ code: "5.G.A.1", text: "Plot points on the coordinate plane" }],
    future_standards: [{ code: "7.NS.A.1", text: "Add and subtract rational numbers" }],
    challenges: [
      { problem: "-5 is thought bigger than -2", fix: "Place both on a line and read left to right" },
      { problem: "Negative coordinates are plotted positively", fix: "Trace the direction from the origin each time" },
    ],
    mastery_statement: "Student can place positive and negative rational numbers on a number line and plot points in all four quadrants.",
    ladder: [
      { name: "I can order positive numbers", descriptor: "Uses the number line" },
      { name: "I can place negatives", descriptor: "Extends past zero" },
      { name: "I can find opposites", descriptor: "Reflects across zero" },
      { name: "I can plot in all four quadrants", descriptor: "Handles negative coordinates" },
    ],
  },
  {
    standard_code: "6.SP.B.5",
    verbs: [
      { word: "Summarise", gloss: "describe the data set briefly" },
      { word: "Report", gloss: "state how many and what was measured" },
      { word: "Describe", gloss: "give centre and spread" },
    ],
    concepts: ["Measures of centre", "Variability", "Context"],
    vocabulary: [
      { term: "mean", definition: "the total shared out equally" },
      { term: "median", definition: "the middle value when they are in order" },
      { term: "range", definition: "the gap between largest and smallest" },
      { term: "outlier", definition: "a value far away from the rest" },
    ],
    prior_skills: ["Calculate a mean", "Order a data set", "Read a dot plot"],
    prior_standards: [{ code: "6.SP.A.2", text: "Understand that a data set has a distribution" }],
    future_standards: [{ code: "7.SP.B.4", text: "Use measures of centre and variability to compare populations" }],
    challenges: [
      { problem: "The mean is reported without noticing an outlier", fix: "Compute mean and median together and discuss the gap" },
      { problem: "Numbers are given with no units or context", fix: "Require a sentence naming what was measured" },
    ],
    mastery_statement: "Student can summarise a data set with a measure of centre and of spread, in context.",
    ladder: [
      { name: "I can find the mean", descriptor: "Computes the average" },
      { name: "I can find the median", descriptor: "Orders and locates the middle" },
      { name: "I can describe the spread", descriptor: "Reports range or variability" },
      { name: "I can say which centre fits better", descriptor: "Reasons about outliers" },
    ],
  },
  {
    standard_code: "7.NS.A.2",
    verbs: [
      { word: "Multiply", gloss: "find the product" },
      { word: "Divide", gloss: "find the quotient" },
      { word: "Apply", gloss: "extend what you know about fractions" },
    ],
    concepts: ["Sign rules", "Fraction operations", "Reciprocals"],
    vocabulary: [
      { term: "product", definition: "the answer to a multiplication" },
      { term: "quotient", definition: "the answer to a division" },
      { term: "reciprocal", definition: "a fraction flipped over" },
      { term: "rational number", definition: "any number writable as a fraction" },
    ],
    prior_skills: ["Add and subtract rational numbers", "Multiply fractions", "Divide fractions"],
    prior_standards: [{ code: "7.NS.A.1", text: "Add and subtract rational numbers" }],
    future_standards: [{ code: "8.NS.A.1", text: "Know that numbers that are not rational are irrational" }],
    challenges: [
      { problem: "Sign rules are memorised without meaning", fix: "Build from repeated addition of negatives" },
      { problem: "Two negatives are added rather than multiplied", fix: "Contrast -3 + -4 with -3 × -4 side by side" },
    ],
    mastery_statement: "Student can multiply and divide rational numbers and explain why the sign is what it is.",
    ladder: [
      { name: "I can multiply positives", descriptor: "Handles fractions and decimals" },
      { name: "I can multiply with one negative", descriptor: "Applies the sign rule" },
      { name: "I can multiply two negatives", descriptor: "Explains the positive result" },
      { name: "I can divide rational numbers", descriptor: "Uses reciprocals correctly" },
    ],
  },
  {
    standard_code: "8.EE.B.5",
    verbs: [
      { word: "Graph", gloss: "draw the relationship" },
      { word: "Interpret", gloss: "say what the slope means" },
      { word: "Compare", gloss: "judge two relationships against each other" },
    ],
    concepts: ["Slope as unit rate", "Proportional graphs", "Comparing representations"],
    vocabulary: [
      { term: "slope", definition: "how steep a line is" },
      { term: "unit rate", definition: "how much for exactly one" },
      { term: "proportional", definition: "always changing by the same multiple" },
      { term: "origin", definition: "the point (0, 0)" },
    ],
    prior_skills: ["Recognise proportional relationships", "Find unit rates", "Plot points"],
    prior_standards: [{ code: "7.RP.A.2", text: "Recognise and represent proportional relationships" }],
    future_standards: [{ code: "8.F.B.4", text: "Construct a function to model a linear relationship" }],
    challenges: [
      { problem: "Slope is computed without units, so it means nothing", fix: "Say it aloud as 'miles per hour' rather than a bare number" },
      { problem: "Relationships in different forms are compared by eye", fix: "Convert both to unit rates before judging" },
    ],
    mastery_statement: "Student can graph a proportional relationship, interpret its slope as a unit rate, and compare two such relationships.",
    ladder: [
      { name: "I can plot a proportional relationship", descriptor: "Graphs from a table" },
      { name: "I can find the slope", descriptor: "Computes rise over run" },
      { name: "I can say what the slope means", descriptor: "States it with units" },
      { name: "I can compare two relationships", descriptor: "Judges across representations" },
    ],
  },
];

const blueprintsData = [
  {
    standard_code: "RF.K.3",
    title: "Every Letter Has a Sound",
    badge: "Kindergarten",
    route_name: "Explicit Instruction",
    route_line: "Teach the sound → Practise it fast → Read it in a word",
    success_criteria: ["Gives the sound for a shown letter", "Reads a CVC word by sounding out", "Reads taught high-frequency words on sight"],
    steps: [
      { name: "Sound Drill", minutes: 5, body: "Flash previously taught letters. Students say sounds, not names. Fast, daily, no reteaching — this is retrieval.", science_tag: "retrieval" },
      { name: "Introduce the New Sound", minutes: 8, body: "Show the letter, say the sound, give a keyword picture. Students say it while tracing the shape in the air.", science_tag: "dual-coding" },
      { name: "Hear It in Words", minutes: 8, body: "Say words; students signal when they hear the target sound. Ear before eye keeps the sound primary.", science_tag: "elaboration" },
      { name: "Blend It Into a Word", minutes: 12, body: "Build CVC words using the new letter. Sound each letter, then sweep to blend. Model the sweep every time.", science_tag: "dual-coding" },
      { name: "Sight Word Flash", minutes: 8, body: "Two or three high-frequency words, flashed too fast to sound out. Speed is the point — these must be automatic.", science_tag: "retrieval" },
      { name: "Read a Sentence", minutes: 10, body: "One sentence using the new sound and today's sight words. Real reading, however short.", science_tag: "interleaving" },
      { name: "Sound Check", minutes: 5, body: "Individually: give the sound for three letters and read one word.", science_tag: "spaced" },
    ],
    ef_supports: ["Keyword picture per letter", "Air tracing for the shape", "Sound-first routine before letters", "Very short daily drill rather than long sessions"],
    tech: "Letter cards and keyword pictures",
    tech_purpose: "Pair each sound with a memorable image",
    ai_prompts: ["Generate CVC words for a given target letter", "Write kindergarten sentences using specific sight words"],
    assessment: ["Watch the daily drill for letters not yet secure", "Individual sound check", "Note who sounds out sight words"],
    why_it_works: ["Sounds before names avoids the commonest confusion", "Daily retrieval is what makes letter sounds automatic", "Flashing sight words too fast to decode forces recognition", "A real sentence proves the sound is usable, not just known"],
  },
  {
    standard_code: "L.1.4",
    title: "Clues in the Sentence",
    badge: "Grade 1",
    route_name: "Strategy Instruction",
    route_line: "Notice the word → Reread for clues → Check the guess",
    success_criteria: ["Flags a word they do not know", "Uses the sentence to propose a meaning", "Checks the meaning fits"],
    steps: [
      { name: "Retrieve Known Endings", minutes: 5, body: "What does -s mean? -ed? Quick recall of endings already taught.", science_tag: "retrieval" },
      { name: "Model Noticing", minutes: 8, body: "Read aloud, hit a hard word, stop visibly. Say 'I do not know that one'. Noticing has to be modelled before it is expected.", science_tag: "elaboration" },
      { name: "The Reread Move", minutes: 10, body: "Teach rereading the whole sentence rather than staring at the word. Practise on three sentences together.", science_tag: "dual-coding" },
      { name: "Guess Together", minutes: 12, body: "Sentences with strong context. Students propose meanings and point to the clue word that helped.", science_tag: "collaborative" },
      { name: "Does It Fit?", minutes: 10, body: "Put the guess back into the sentence. Does it still make sense? Practise on one guess that nearly works but does not.", science_tag: "elaboration" },
      { name: "Partner Practice", minutes: 10, body: "Partners take turns: one reads a sentence with a hard word, the other works it out and names the clue.", science_tag: "collaborative" },
      { name: "One Word Out", minutes: 5, body: "One sentence, one unknown word. Students draw or write what they think it means.", science_tag: "spaced" },
    ],
    ef_supports: ["Hand signal for unknown words", "Reread-the-sentence anchor chart", "Sentence frames for proposing a meaning", "Draw instead of write"],
    tech: "Slides showing one sentence at a time",
    tech_purpose: "Control the pace so nobody reads ahead",
    ai_prompts: ["Generate grade 1 sentences where context reveals a word", "Create near-miss meanings for students to test"],
    assessment: ["Do students flag unknown words at all?", "Check the clue word they name", "Exit sentence with meaning given"],
    why_it_works: ["Modelling the stop makes noticing visible", "Rereading gives a concrete first move instead of staring", "Testing the guess catches plausible-but-wrong meanings", "Naming the clue proves the strategy was used, not luck"],
  },
  {
    standard_code: "RI.2.1",
    title: "All Six Question Words",
    badge: "Grade 2",
    route_name: "Explicit Instruction",
    route_line: "Cover the easy ones → Push into why and how → Ask your own",
    success_criteria: ["Answers all six question types", "Finds the detail supporting each answer", "Writes a why or how question of their own"],
    steps: [
      { name: "Retrieve the Question Words", minutes: 5, body: "Six words, said together, with a gesture for each. Fast recall before use.", science_tag: "retrieval" },
      { name: "Easy Four First", minutes: 8, body: "Who, what, where, when on a short text. These are locate-and-report; get them fluent before the hard ones.", science_tag: "retrieval" },
      { name: "Why Is Different", minutes: 12, body: "Why questions need a reason from the text, not a personal one. Model finding the explaining sentence.", science_tag: "elaboration" },
      { name: "How Is Different Too", minutes: 10, body: "How questions ask for a process. Model tracking steps across several sentences.", science_tag: "elaboration" },
      { name: "Sort by Question Word", minutes: 10, body: "Given answers, students say which question word produced them. Working backwards clarifies the types.", science_tag: "interleaving" },
      { name: "Write Your Own", minutes: 10, body: "Each student writes one why or how question about the text and swaps with a partner to answer.", science_tag: "collaborative" },
      { name: "Share the Hardest", minutes: 5, body: "Two students share a why question and where the answer lived.", science_tag: "spaced" },
    ],
    ef_supports: ["Question word chart with gestures", "Colour coding for question type", "Sentence stems for why and how", "Text chunked into short sections"],
    tech: "Printed informational text",
    tech_purpose: "Markable copy for locating answers",
    ai_prompts: ["Write a grade 2 informational text supporting all six question types", "Generate answers for students to match to question words"],
    assessment: ["Check why answers come from the text", "Review student-written questions for type", "Note who avoids why and how"],
    why_it_works: ["Separating the easy four from why and how targets the real difficulty", "Working backwards from answers clarifies question types", "Writing a question is harder than answering one, and proves understanding", "Requiring the source sentence blocks opinion answers"],
  },
  {
    standard_code: "SL.3.1",
    title: "Talking So the Conversation Grows",
    badge: "Grade 3",
    route_name: "Structured Discussion",
    route_line: "Agree the rules → Practise building on → Run a real discussion",
    success_criteria: ["Follows the agreed discussion rules", "Builds on another student's idea", "Contributes at least twice"],
    steps: [
      { name: "Recall Our Rules", minutes: 5, body: "Students recall the discussion norms before the chart is shown. Retrieval, then confirm.", science_tag: "retrieval" },
      { name: "Prepare Something to Say", minutes: 8, body: "Everyone writes one idea about the text first. Unprepared discussion favours the quick-talking.", science_tag: "elaboration" },
      { name: "The Build-On Stem", minutes: 10, body: "Teach one move: 'I agree with ___ because…'. Model it twice, badly and then well.", science_tag: "dual-coding" },
      { name: "Practise in Threes", minutes: 12, body: "Triads. Every contribution must start with the stem. Awkward at first, which is the point of isolating it.", science_tag: "collaborative" },
      { name: "Whole Group Discussion", minutes: 12, body: "One question, whole class. Teacher stays quiet and lets silences sit.", science_tag: "collaborative" },
      { name: "Count the Builds", minutes: 5, body: "How many times did someone build on another idea? Count them together — it makes the target visible.", science_tag: "interleaving" },
      { name: "Set a Personal Goal", minutes: 3, body: "Each student names one thing to do next time.", science_tag: "spaced" },
    ],
    ef_supports: ["Discussion rules chart", "Build-on sentence stem", "Written idea before speaking", "Triads before whole group"],
    tech: "Printed idea slips",
    tech_purpose: "Everyone arrives with something to say",
    ai_prompts: ["Generate discussable questions for a grade 3 text", "Write a scripted discussion where nobody connects ideas"],
    assessment: ["Listen in triads for stem use", "Count build-ons in the whole group", "Read personal goals"],
    why_it_works: ["Writing an idea first means everyone has something to contribute", "Isolating one move prevents overload", "Counting build-ons makes an abstract goal concrete", "Teacher silence is what creates student talk"],
  },
  {
    standard_code: "RF.4.4",
    title: "Reading That Sounds Like Meaning",
    badge: "Grade 4",
    route_name: "Routine and Practice",
    route_line: "Model the phrasing → Reread for smoothness → Read for meaning",
    success_criteria: ["Reads grade 4 text accurately", "Groups words into meaningful phrases", "Reads poetry differently from prose"],
    steps: [
      { name: "Warm Up on Yesterday's Text", minutes: 5, body: "Reread a familiar passage. Familiar text is where expression can grow without decoding competing.", science_tag: "spaced" },
      { name: "Two Readings, Compared", minutes: 8, body: "Read a passage flat, then with phrasing. Students say which they understood and why.", science_tag: "elaboration" },
      { name: "Mark the Phrases", minutes: 10, body: "Slash marks between phrase groups. Students mark their own, then read it their way.", science_tag: "dual-coding" },
      { name: "Repeated Reading", minutes: 12, body: "Three reads of the same short passage with a partner listening. Repetition is the mechanism, not the practice.", science_tag: "retrieval" },
      { name: "Poetry Is Not Prose", minutes: 10, body: "Same fluency skills, different shape. Line breaks are not full stops. Practise a short poem aloud.", science_tag: "interleaving" },
      { name: "Read for Meaning", minutes: 10, body: "New passage, one read, then a comprehension question. Fluency that loses meaning does not count.", science_tag: "interleaving" },
      { name: "Self-Rate", minutes: 5, body: "Students rate their smoothness and name one thing to improve.", science_tag: "spaced" },
    ],
    ef_supports: ["Phrase-marked passages", "Partner smoothness checklist", "Familiar text for expression work", "Poems printed with clear line breaks"],
    tech: "Printed prose and poetry passages",
    tech_purpose: "Marking phrases needs a markable copy",
    ai_prompts: ["Write grade 4 passages at consistent difficulty", "Generate short poems suited to fluency practice"],
    assessment: ["Listen to third reads for phrasing", "Comprehension question after every fluency read", "Track accuracy across repeated reads"],
    why_it_works: ["Repeated reading of one text is what builds fluency", "The flat-versus-phrased contrast shows why prosody matters", "Poetry forces attention to phrasing rather than pace", "Pairing every read with a question keeps meaning the goal"],
  },
  {
    standard_code: "RL.5.1",
    title: "The Author's Exact Words",
    badge: "Grade 5",
    route_name: "Explicit Instruction",
    route_line: "Find it → Copy it exactly → Use it to prove a point",
    success_criteria: ["Copies a quote word for word", "Uses a quote to support a stated meaning", "Uses a quote to support an inference"],
    steps: [
      { name: "Retrieve Evidence Habits", minutes: 5, body: "One question, answered with a reference to the text. Re-establish the baseline.", science_tag: "retrieval" },
      { name: "Quote or Paraphrase", minutes: 10, body: "Show both for the same idea. Students name the difference. A paraphrase in quotation marks is the commonest error.", science_tag: "elaboration" },
      { name: "Copy It Exactly", minutes: 10, body: "Practise transcribing quotes and checking them word for word against the page. Accuracy is a habit, not an instinct.", science_tag: "dual-coding" },
      { name: "Quote for What It Says", minutes: 10, body: "Explicit questions, answered with a quote. Straightforward, and it builds the routine.", science_tag: "retrieval" },
      { name: "Quote for What It Implies", minutes: 12, body: "Inference questions. The quote is the clue, not the conclusion. Model the gap between them.", science_tag: "elaboration" },
      { name: "Trim the Quote", minutes: 8, body: "Cut a long quote down to the words doing the work. Selection is the skill.", science_tag: "interleaving" },
      { name: "Check a Partner's", minutes: 5, body: "Partners verify each other's quotes against the text, character by character.", science_tag: "spaced" },
    ],
    ef_supports: ["Quotation punctuation reference", "Highlighters for locating quotes", "Word-for-word checking routine", "Numbered paragraphs"],
    tech: "Printed text with numbered paragraphs",
    tech_purpose: "Precise citation needs stable references",
    ai_prompts: ["Generate quote-and-paraphrase pairs for the same idea", "Write inference questions whose clues are single sentences"],
    assessment: ["Check quotes match the text exactly", "Confirm inference quotes are clues not conclusions", "Partner verification"],
    why_it_works: ["The quote-versus-paraphrase contrast names the commonest error", "Character-by-character checking builds accuracy as a habit", "Separating explicit from inferential use makes the harder case visible", "Trimming teaches selection rather than transcription"],
  },
  {
    standard_code: "W.5.3",
    title: "Slow Down the Moment That Matters",
    badge: "Grade 5",
    route_name: "Writing Workshop",
    route_line: "Plan the sequence → Add dialogue → Control the pace",
    success_criteria: ["Writes dialogue that reveals character", "Slows the most important moment", "Uses transitions to manage time"],
    steps: [
      { name: "Retrieve Narrative Structure", minutes: 5, body: "Beginning, problem, turning point, resolution. Quick recall before building on it.", science_tag: "retrieval" },
      { name: "Dialogue That Does Work", minutes: 10, body: "Two versions: dialogue delivering plot, and dialogue revealing character. Students name the difference.", science_tag: "elaboration" },
      { name: "Punctuate It", minutes: 8, body: "Quick technical block on speech punctuation and new speaker, new line. Get it out of the way.", science_tag: "dual-coding" },
      { name: "Find the Moment", minutes: 10, body: "Which moment in your story matters most? Mark it. Everything else exists to reach it.", science_tag: "elaboration" },
      { name: "Stretch It", minutes: 12, body: "Rewrite that one moment at three times the length. Thoughts, senses, small actions. This is pacing made concrete.", science_tag: "interleaving" },
      { name: "Speed Up the Rest", minutes: 10, body: "Compress the less important parts with transitional phrases. Contrast is what makes pacing visible.", science_tag: "collaborative" },
      { name: "Read the Stretched Moment", minutes: 5, body: "Two students read theirs. Class names what they could picture.", science_tag: "spaced" },
    ],
    ef_supports: ["Speech punctuation reference card", "Mark-the-moment routine", "Transitional phrase bank", "Rewrite one moment rather than the whole draft"],
    tech: "Printed drafts to annotate",
    tech_purpose: "Marking the key moment needs a physical draft",
    ai_prompts: ["Generate dialogue pairs delivering plot versus revealing character", "List transitional phrases for compressing time"],
    assessment: ["Check dialogue reveals something", "Confirm one moment is genuinely stretched", "Listen for picturable writing"],
    why_it_works: ["Pacing is invisible until you contrast stretched with compressed", "Rewriting one moment beats revising a whole draft", "Dialogue that reveals character is a concrete, teachable distinction", "Punctuation taught separately stops it derailing the craft work"],
  },
  {
    standard_code: "RL.6.1",
    title: "Evidence That Carries the Claim",
    badge: "Grade 6",
    route_name: "Analytical Reading",
    route_line: "Make the claim → Find evidence for it → Explain the link",
    success_criteria: ["Cites evidence for an explicit statement", "Cites evidence for an inference", "Explains how the evidence supports the claim"],
    steps: [
      { name: "Retrieve Quoting", minutes: 5, body: "One accurate quote from a familiar text. The base skill before analysis is added.", science_tag: "retrieval" },
      { name: "Claim, Evidence, Link", minutes: 10, body: "Three parts, colour-coded in a model paragraph. Most students supply two and skip the third.", science_tag: "dual-coding" },
      { name: "Relevant to the Claim", minutes: 12, body: "Evidence relevant to the topic but not the claim. Students spot the gap. Subtle and worth the time.", science_tag: "elaboration" },
      { name: "Evidence for an Inference", minutes: 12, body: "The quote is a clue, not a statement of the conclusion. Model the reasoning that bridges them.", science_tag: "elaboration" },
      { name: "Write the Link", minutes: 10, body: "Practise only the third sentence — how the evidence supports the claim. Isolating it stops it being dropped.", science_tag: "interleaving" },
      { name: "Full Paragraph", minutes: 8, body: "Claim, evidence, link, on a new question.", science_tag: "collaborative" },
      { name: "Swap and Check", minutes: 3, body: "Partners check all three parts are present and the link does real work.", science_tag: "spaced" },
    ],
    ef_supports: ["Colour-coded model paragraph", "Claim/evidence/link frame", "Practise the link sentence alone", "Numbered paragraphs"],
    tech: "Printed text with line numbers",
    tech_purpose: "Precise citation",
    ai_prompts: ["Generate evidence relevant to a topic but not to a claim", "Write inference questions with single-sentence clues"],
    assessment: ["Check all three parts appear", "Confirm evidence matches the claim not the topic", "Read link sentences for real reasoning"],
    why_it_works: ["The link is the part students drop, so practise it alone", "Topic-relevant but claim-irrelevant evidence is the subtle failure", "Colour coding makes paragraph structure visible", "Inference evidence needs explicit modelling of the gap"],
  },
  {
    standard_code: "L.6.4",
    title: "Three Ways Into a Word",
    badge: "Grade 6",
    route_name: "Strategy Instruction",
    route_line: "Guess from context → Break it apart → Verify it",
    success_criteria: ["Proposes a meaning from context before looking it up", "Identifies root and affixes", "Chooses the dictionary sense that fits"],
    steps: [
      { name: "Retrieve Known Roots", minutes: 5, body: "Rapid recall of taught Greek and Latin roots. These compound over a year.", science_tag: "retrieval" },
      { name: "Context First, Always", minutes: 10, body: "Establish the order: guess, then check. Looking up first skips the thinking that makes it stick.", science_tag: "elaboration" },
      { name: "Break the Word Apart", minutes: 12, body: "Prefix, root, suffix. Build meaning from parts, then compare to the context guess.", science_tag: "dual-coding" },
      { name: "The Dictionary Trap", minutes: 10, body: "A word with five senses. Students pick the one fitting the sentence, not the first listed.", science_tag: "elaboration" },
      { name: "Mixed Practice", minutes: 12, body: "Some words yield to context, some to word parts, some need the dictionary. Choosing is the skill.", science_tag: "interleaving" },
      { name: "Shades of Meaning", minutes: 8, body: "Rank related words by strength. Connotation is the half of this standard usually skipped.", science_tag: "elaboration" },
      { name: "One Word, Three Ways", minutes: 3, body: "One word: context guess, word parts, verified meaning.", science_tag: "spaced" },
    ],
    ef_supports: ["Growing root and affix chart", "Guess-then-check routine", "Dictionary sense selection practice", "Intensity ranking lines"],
    tech: "Dictionaries and printed passages",
    tech_purpose: "Verification needs a real reference",
    ai_prompts: ["Generate grade 6 words built from common Greek and Latin roots", "Create multi-sense dictionary entries for selection practice"],
    assessment: ["Check a context guess precedes the lookup", "Review word part breakdowns", "Confirm the chosen sense fits"],
    why_it_works: ["Guessing before looking up is what makes the meaning stick", "Roots compound — every one learned helps with dozens of words", "Choosing among senses is the real dictionary skill", "Connotation work covers the neglected half of the standard"],
  },
  {
    standard_code: "RI.8.5",
    title: "What Each Sentence Is Doing",
    badge: "Grade 8",
    route_name: "Analytical Reading",
    route_line: "Find the key concept → Name each sentence's job → Separate develop from refine",
    success_criteria: ["States the paragraph's key concept", "Names the function of individual sentences", "Distinguishes developing from refining"],
    steps: [
      { name: "Retrieve Paragraph Function", minutes: 5, body: "What jobs can a paragraph do for a text? Recall the menu from earlier work.", science_tag: "retrieval" },
      { name: "Zoom In One Level", minutes: 8, body: "Same question, sentence level. Introduce the finer menu: introduces, illustrates, qualifies, counters, concludes.", science_tag: "dual-coding" },
      { name: "Develop or Refine", minutes: 12, body: "Developing adds; refining narrows. Sort sentences into the two. The distinction is the standard's actual demand.", science_tag: "elaboration" },
      { name: "Map a Paragraph", minutes: 12, body: "One sentence per row, function only. Content words banned, which forces the shift from summary to analysis.", science_tag: "dual-coding" },
      { name: "Delete a Sentence", minutes: 10, body: "What is lost if this sentence goes? The damage names its role better than description does.", science_tag: "elaboration" },
      { name: "Write the Analysis", minutes: 10, body: "One paragraph: name the key concept and explain how two specific sentences develop or refine it.", science_tag: "interleaving" },
      { name: "Compare Two Maps", minutes: 3, body: "Two students compare function maps and discuss the disagreements.", science_tag: "spaced" },
    ],
    ef_supports: ["Sentence function menu", "One-row-per-sentence map", "Content-word ban", "Develop versus refine sorting mat"],
    tech: "Printed article with numbered sentences",
    tech_purpose: "Sentence-level reference for mapping",
    ai_prompts: ["Write a dense grade 8 paragraph with varied sentence functions", "Generate sentences that develop versus refine the same concept"],
    assessment: ["Check maps name functions not content", "Confirm develop and refine are distinguished", "Read analyses for specific sentence references"],
    why_it_works: ["Banning content words forces analysis over summary", "The deletion test makes a sentence's role concrete", "Develop versus refine is precisely what the standard asks for", "Sentence-level work is a genuine step up from paragraph-level"],
  },
  {
    standard_code: "K.G.A.2",
    title: "Still a Triangle When You Turn It",
    badge: "Kindergarten",
    route_name: "Concrete Practice",
    route_line: "Name it → Turn it → Find it everywhere",
    success_criteria: ["Names common shapes", "Names a shape when it is rotated", "Names a shape at any size"],
    steps: [
      { name: "Shape Names", minutes: 5, body: "Flash shape cards in their usual orientation. Fast naming to establish the vocabulary.", science_tag: "retrieval" },
      { name: "Count the Sides", minutes: 8, body: "What makes a triangle a triangle? Three straight sides. Attributes, not appearance.", science_tag: "elaboration" },
      { name: "Turn It Around", minutes: 12, body: "Same shape, rotated slowly while students keep naming it. The point is that nothing changed.", science_tag: "dual-coding" },
      { name: "Big One, Tiny One", minutes: 10, body: "Same shape at wildly different sizes. Still the same name. Size invariance, made obvious.", science_tag: "dual-coding" },
      { name: "Odd Ones In", minutes: 10, body: "Long thin triangles, lopsided ones. Students often reject these. Include them deliberately.", science_tag: "interleaving" },
      { name: "Shape Hunt", minutes: 10, body: "Find shapes around the room, in any orientation. Real objects rarely sit square to the world.", science_tag: "collaborative" },
      { name: "Name Three", minutes: 5, body: "Three shapes, rotated, named individually.", science_tag: "spaced" },
    ],
    ef_supports: ["Shape cards that can be physically rotated", "Attribute language — count the sides", "Deliberately atypical examples", "Room hunt for real orientations"],
    tech: "Cut-out shapes",
    tech_purpose: "Rotating a shape by hand is what proves it does not change",
    ai_prompts: ["Generate atypical examples of common shapes", "List classroom objects matching each shape"],
    assessment: ["Watch for rejection of rotated shapes", "Check atypical examples are accepted", "Individual naming check"],
    why_it_works: ["Physically rotating a shape shows nothing changed", "Atypical examples are where the misconception lives", "Attribute language gives a test beyond appearance", "The room hunt shows shapes rarely sit square in the world"],
  },
  {
    standard_code: "1.OA.D.7",
    title: "Both Sides Are the Same",
    badge: "Grade 1",
    route_name: "Concrete-Representational-Abstract",
    route_line: "Balance it → Read it both ways → Judge true or false",
    success_criteria: ["Explains the equal sign as balance", "Solves equations with the answer on the left", "Judges an equation true or false"],
    steps: [
      { name: "Retrieve Facts Within 10", minutes: 5, body: "Quick sums. Fluency here frees attention for the structure.", science_tag: "retrieval" },
      { name: "Use a Balance", minutes: 12, body: "Physical balance with cubes. Equal means it balances. This is the whole idea, made concrete.", science_tag: "dual-coding" },
      { name: "Write What the Balance Shows", minutes: 10, body: "4 + 3 = 7, matching the pans. Symbols attached to a physical fact.", science_tag: "dual-coding" },
      { name: "Backwards Equations", minutes: 12, body: "7 = 4 + 3. Students will say it looks wrong. Keep writing them until it stops looking wrong.", science_tag: "elaboration" },
      { name: "True or False", minutes: 12, body: "Judge equations without solving where possible. 5 + 3 = 8 + 2 is false, and the balance shows why.", science_tag: "interleaving" },
      { name: "Both Sides Have Sums", minutes: 8, body: "4 + 3 = 5 + 2. Both sides need working out. This is where the operator reading finally breaks.", science_tag: "elaboration" },
      { name: "Judge Three", minutes: 3, body: "Three equations, true or false, with a reason.", science_tag: "spaced" },
    ],
    ef_supports: ["Physical balance scale", "Backwards equations written routinely", "True/false cards", "Cubes for building both sides"],
    tech: "Balance scale and cubes",
    tech_purpose: "Equality as a physical fact before a symbolic one",
    ai_prompts: ["Generate true and false equations with sums on both sides", "Create backwards-form equations for grade 1"],
    assessment: ["Watch for 'the answer comes next' reasoning", "Check both-sides equations are handled", "Individual true/false with reasons"],
    why_it_works: ["A balance makes equality physical rather than notational", "Backwards equations directly attack the operator misconception", "Judging without solving forces attention to structure", "This misconception blocks algebra years later if left alone"],
  },
  {
    standard_code: "2.G.A.3",
    title: "Halves, Thirds and Fourths",
    badge: "Grade 2",
    route_name: "Concrete-Representational-Abstract",
    route_line: "Fold and check → Name the shares → See that shape can differ",
    success_criteria: ["Partitions into halves, thirds and fourths", "Names shares with correct language", "Recognises equal shares of different shapes"],
    steps: [
      { name: "Retrieve Halves and Fourths", minutes: 5, body: "Fold paper in half, then fourths. Ground the lesson in what is already known.", science_tag: "retrieval" },
      { name: "Thirds Are Harder", minutes: 12, body: "Three equal parts cannot be made by folding in half. Students must measure or estimate and check.", science_tag: "elaboration" },
      { name: "Check by Stacking", minutes: 10, body: "Cut and stack the parts. If they match, they are equal. The proof students can run themselves.", science_tag: "dual-coding" },
      { name: "Name the Shares", minutes: 10, body: "A third of, two thirds. Precise language, said aloud every time.", science_tag: "dual-coding" },
      { name: "Different Shapes, Same Share", minutes: 12, body: "Two halves of a rectangle split diagonally versus straight. Both halves. Cut and overlay to prove it.", science_tag: "elaboration" },
      { name: "Sort Equal and Unequal", minutes: 8, body: "Cards including near-misses. Sorting forces the equal-parts test to be applied.", science_tag: "interleaving" },
      { name: "Fold and Name", minutes: 3, body: "One shape folded into thirds and named.", science_tag: "spaced" },
    ],
    ef_supports: ["Paper shapes and scissors", "Stacking to verify equality", "Near-miss sorting cards", "Precise share language modelled"],
    tech: "Paper shapes",
    tech_purpose: "Folding and stacking is a proof children can perform",
    ai_prompts: ["Generate partitioned shapes including unequal near-misses", "Create same-area different-shape examples"],
    assessment: ["Check thirds are genuinely equal", "Watch the sort for accepted unequal parts", "Individual fold and name"],
    why_it_works: ["Thirds resist folding, which forces genuine measurement", "Stacking is a proof students own rather than accept", "Same-area-different-shape is the subtle case in this standard", "Near-miss cards test whether equal really registered"],
  },
  {
    standard_code: "3.OA.D.8",
    title: "Problems That Need Two Steps",
    badge: "Grade 3",
    route_name: "Strategy Instruction",
    route_line: "Find the hidden question → Solve both steps → Check it makes sense",
    success_criteria: ["Identifies both steps before calculating", "Writes an equation with a letter for the unknown", "Estimates first and checks the answer against it"],
    steps: [
      { name: "Retrieve One-Step Problems", minutes: 5, body: "Two quick single-operation problems. Confirm the base before doubling it.", science_tag: "retrieval" },
      { name: "The Hidden Question", minutes: 12, body: "Two-step problems contain a question nobody asked. Model finding it before calculating anything.", science_tag: "elaboration" },
      { name: "Estimate First", minutes: 10, body: "Roughly what should the answer be? Estimating first is what makes a wild answer visible later.", science_tag: "elaboration" },
      { name: "Write It With a Letter", minutes: 12, body: "Represent the unknown. Two equations, or one with brackets. Structure before arithmetic.", science_tag: "dual-coding" },
      { name: "Solve and Compare", minutes: 12, body: "Calculate, then compare with the estimate. A large gap means checking, not shrugging.", science_tag: "interleaving" },
      { name: "Answer the Actual Question", minutes: 8, body: "Problems where the first step's answer is not what was asked. The commonest error, targeted directly.", science_tag: "elaboration" },
      { name: "One Problem Through", minutes: 3, body: "Estimate, equation, solve, check.", science_tag: "spaced" },
    ],
    ef_supports: ["Find-the-hidden-question routine", "Estimate-before-solve step", "Equation frame with a letter", "Underline what the question actually asks"],
    tech: "Printed problem cards",
    tech_purpose: "Annotating the question is part of the method",
    ai_prompts: ["Generate two-step problems where step one's answer is not the final answer", "Create problems suited to estimation checks"],
    assessment: ["Check both steps are identified first", "Confirm an estimate precedes the calculation", "Watch for first-step answers submitted as final"],
    why_it_works: ["Naming the hidden question is the specific skill two-step problems need", "Estimating first turns checking into comparison rather than repetition", "Stopping after step one is the dominant error, so target it", "Letters for unknowns prepare the ground for algebra"],
  },
  {
    standard_code: "4.NF.C.6",
    title: "Tenths and Hundredths as Decimals",
    badge: "Grade 4",
    route_name: "Concrete-Representational-Abstract",
    route_line: "Shade the grid → Write it two ways → Place it on the line",
    success_criteria: ["Writes tenths and hundredths as decimals", "Says the decimal as a fraction aloud", "Places decimals correctly on a number line"],
    steps: [
      { name: "Retrieve Tenths", minutes: 5, body: "Name fractions with denominator 10. The bridge into decimal notation.", science_tag: "retrieval" },
      { name: "Shade a Ten-Grid", minutes: 10, body: "Ten strips, shade three. Three tenths. Then write 0.3. The grid connects the two forms.", science_tag: "dual-coding" },
      { name: "Say It as a Fraction", minutes: 8, body: "Read 0.3 as 'three tenths', never 'point three'. Naming keeps the size attached.", science_tag: "elaboration" },
      { name: "Hundred-Grid", minutes: 12, body: "Hundred squares, shade twenty-five. 25/100 and 0.25. Notice 0.25 equals 0.2 and 5 hundredths.", science_tag: "dual-coding" },
      { name: "The Size Trap", minutes: 12, body: "Is 0.7 bigger than 0.25? Many say no because 7 < 25. Shade both grids and compare.", science_tag: "elaboration" },
      { name: "Place on a Number Line", minutes: 10, body: "Decimals between 0 and 1. Position makes size undeniable.", science_tag: "interleaving" },
      { name: "Write and Place", minutes: 3, body: "One fraction written as a decimal and placed on a line.", science_tag: "spaced" },
    ],
    ef_supports: ["Ten-strips and hundred-grids", "Say-it-as-a-fraction routine", "Number lines from 0 to 1", "Side-by-side grid comparison"],
    tech: "Printed decimal grids",
    tech_purpose: "Shading makes the size of a decimal visible",
    ai_prompts: ["Generate fraction and decimal pairs for tenths and hundredths", "Create comparison pairs that trigger the digit-count error"],
    assessment: ["Listen for 'point seven' rather than 'seven tenths'", "Check grid shading matches the notation", "Confirm number line placement"],
    why_it_works: ["Grids make decimal size visible rather than notational", "Saying the fraction name keeps magnitude attached to the symbol", "The 0.7 versus 0.25 comparison is the standard misconception", "Number lines force ordering by size, not by digits"],
  },
  {
    standard_code: "5.G.A.1",
    title: "Along, Then Up",
    badge: "Grade 5",
    route_name: "Explicit Instruction",
    route_line: "Start at the origin → Move along, then up → Read it back",
    success_criteria: ["Starts every plot at the origin", "Moves along the first axis before the second", "Reads a point's ordered pair correctly"],
    steps: [
      { name: "Retrieve Number Lines", minutes: 5, body: "Read values off a single number line. Two axes are just two of these.", science_tag: "retrieval" },
      { name: "Build the Grid", minutes: 10, body: "Two perpendicular number lines. Name the origin, the axes. Establish the vocabulary first.", science_tag: "dual-coding" },
      { name: "Along the Corridor, Up the Stairs", minutes: 10, body: "One memorable phrase for the order. Say it every single time until it is automatic.", science_tag: "elaboration" },
      { name: "Plot Together", minutes: 12, body: "Finger on the origin, count along, then up, mark. The finger-on-origin step prevents most errors.", science_tag: "dual-coding" },
      { name: "The Reversal Trap", minutes: 12, body: "Plot (2, 5) and (5, 2). Different points. Students who reverse see immediately why order matters.", science_tag: "elaboration" },
      { name: "Read It Back", minutes: 10, body: "Given a marked point, name the pair. The reverse operation, which catches shaky understanding.", science_tag: "interleaving" },
      { name: "Plot and Name", minutes: 3, body: "Plot one point, read another.", science_tag: "spaced" },
    ],
    ef_supports: ["Finger-on-origin routine", "Along-then-up phrase", "Grid paper with labelled axes", "Reversal pairs for comparison"],
    tech: "Grid paper",
    tech_purpose: "Plotting needs a grid to plot on",
    ai_prompts: ["Generate coordinate pairs including reversals", "Create plot-and-read exercises for grade 5"],
    assessment: ["Watch for plots not starting at the origin", "Check reversal pairs are distinguished", "Confirm reading back is accurate"],
    why_it_works: ["A memorable phrase for order beats a rule students forget", "Finger on origin removes the counting-start error", "Reversal pairs make the order requirement self-evident", "Reading back tests understanding that plotting alone can hide"],
  },
  {
    standard_code: "6.NS.C.6",
    title: "The Number Line Goes Both Ways",
    badge: "Grade 6",
    route_name: "Explicit Instruction",
    route_line: "Extend past zero → Find opposites → Plot in four quadrants",
    success_criteria: ["Orders positive and negative numbers", "Identifies a number's opposite", "Plots points with negative coordinates"],
    steps: [
      { name: "Retrieve Ordering", minutes: 5, body: "Order positive numbers on a line. The base before extending it.", science_tag: "retrieval" },
      { name: "Past Zero", minutes: 10, body: "Extend the line left. Temperature or debt gives it meaning. Negatives are positions, not just signs.", science_tag: "dual-coding" },
      { name: "The Ordering Trap", minutes: 12, body: "Is -5 bigger than -2? Many say yes. Place both on the line and read left to right.", science_tag: "elaboration" },
      { name: "Opposites", minutes: 10, body: "Same distance from zero, other side. Fold the line at zero to show the reflection.", science_tag: "dual-coding" },
      { name: "Two Axes, Four Quadrants", minutes: 12, body: "Extend the coordinate plane. Name the quadrants and their sign patterns.", science_tag: "dual-coding" },
      { name: "Plot With Negatives", minutes: 10, body: "Points in all four quadrants. Trace direction from the origin every time.", science_tag: "interleaving" },
      { name: "Order and Plot", minutes: 3, body: "Order four rational numbers, plot one negative point.", science_tag: "spaced" },
    ],
    ef_supports: ["Extended number line on the wall", "Fold-at-zero demonstration", "Quadrant sign chart", "Trace-from-origin routine"],
    tech: "Four-quadrant grid paper",
    tech_purpose: "Negative coordinates need the full plane",
    ai_prompts: ["Generate ordering sets mixing negative fractions and decimals", "Create plotting exercises across all four quadrants"],
    assessment: ["Check negative ordering", "Confirm opposites are found correctly", "Watch for negatives plotted positively"],
    why_it_works: ["Reading left to right on a line settles negative ordering", "Folding at zero makes opposites a reflection, not a rule", "Context like temperature gives negatives meaning", "Quadrant sign patterns come from the axes rather than memorisation"],
  },
  {
    standard_code: "6.SP.B.5",
    title: "One Number to Describe Many",
    badge: "Grade 6",
    route_name: "Explicit Instruction",
    route_line: "Find the centre → Describe the spread → Say it in context",
    success_criteria: ["Calculates mean and median", "Describes the spread of a data set", "Reports findings with units and context"],
    steps: [
      { name: "Retrieve Mean", minutes: 5, body: "Compute one mean. The calculation should be automatic before interpretation begins.", science_tag: "retrieval" },
      { name: "Mean Versus Median", minutes: 12, body: "Same data set, both computed. Usually close. Then add an outlier and watch only one move.", science_tag: "elaboration" },
      { name: "Which Centre Is Fairer", minutes: 10, body: "House prices, test scores with one zero. Students argue for one over the other. The reasoning is the point.", science_tag: "elaboration" },
      { name: "Spread Matters Too", minutes: 12, body: "Two sets with the same mean and wildly different spread. Centre alone hides the difference.", science_tag: "dual-coding" },
      { name: "Describe in Context", minutes: 10, body: "Number of observations, what was measured, centre, spread. A bare number is not a summary.", science_tag: "elaboration" },
      { name: "Summarise a Real Set", minutes: 10, body: "Class data — heights, reaction times. Students write a full summary paragraph.", science_tag: "collaborative" },
      { name: "Defend a Choice", minutes: 3, body: "One student explains why they chose mean or median.", science_tag: "spaced" },
    ],
    ef_supports: ["Dot plots for visualising spread", "Same-mean different-spread pairs", "Summary sentence frame", "Class-collected data"],
    tech: "Printed data sets and grid paper",
    tech_purpose: "Plotting makes spread visible",
    ai_prompts: ["Generate data sets where mean and median diverge", "Create pairs with equal means and different spreads"],
    assessment: ["Check both centres are computed", "Confirm spread is reported", "Read summaries for units and context"],
    why_it_works: ["Adding an outlier live shows why the two centres differ", "Same-mean different-spread proves centre alone is insufficient", "Requiring context stops statistics becoming bare arithmetic", "Arguing for a centre is where statistical reasoning starts"],
  },
  {
    standard_code: "7.NS.A.2",
    title: "Why Two Negatives Make a Positive",
    badge: "Grade 7",
    route_name: "Explicit Instruction",
    route_line: "Build from patterns → Name the rule → Apply to fractions",
    success_criteria: ["Multiplies and divides with negative numbers", "Explains why the sign rules hold", "Handles negative fractions and decimals"],
    steps: [
      { name: "Retrieve Adding Negatives", minutes: 5, body: "Quick sums with negatives. Addition must be secure before multiplication builds on it.", science_tag: "retrieval" },
      { name: "Repeated Addition", minutes: 10, body: "3 × -4 is -4 added three times. Negative times positive needs no rule, just meaning.", science_tag: "elaboration" },
      { name: "Find the Pattern", minutes: 12, body: "3 × -4, 2 × -4, 1 × -4, 0 × -4, then -1 × -4. Continue the pattern and the sign flips itself.", science_tag: "elaboration" },
      { name: "Name the Rule", minutes: 8, body: "Now state it — as a summary of what the pattern showed, not a decree.", science_tag: "dual-coding" },
      { name: "Add Not Multiply", minutes: 10, body: "-3 + -4 versus -3 × -4. Side by side. Confusing these is the commonest error.", science_tag: "interleaving" },
      { name: "Fractions and Decimals", minutes: 12, body: "Same rules, harder numbers. The standard says rational, not integer.", science_tag: "interleaving" },
      { name: "Explain the Rule", minutes: 3, body: "One student explains why two negatives multiply to a positive.", science_tag: "spaced" },
    ],
    ef_supports: ["Pattern table extending past zero", "Add-versus-multiply comparison", "Sign rule summary chart", "Negative fraction examples"],
    tech: "Printed pattern tables",
    tech_purpose: "The pattern does the explaining",
    ai_prompts: ["Generate sign-rule pattern sequences", "Create mixed add-and-multiply problems with negatives"],
    assessment: ["Check the pattern is continued correctly", "Watch for add/multiply confusion", "Confirm fractions are handled"],
    why_it_works: ["A pattern that flips the sign itself beats a rule handed down", "Repeated addition makes negative times positive meaningful", "Contrasting addition and multiplication targets the real confusion", "Extending to fractions covers the standard as written"],
  },
  {
    standard_code: "8.EE.B.5",
    title: "Steepness Means Something",
    badge: "Grade 8",
    route_name: "Multiple Representations",
    route_line: "Graph it → Read the slope → Compare across forms",
    success_criteria: ["Graphs a proportional relationship", "States the slope with its units", "Compares relationships given in different forms"],
    steps: [
      { name: "Retrieve Unit Rate", minutes: 5, body: "Find unit rates from two tables. Slope is this idea, graphed.", science_tag: "retrieval" },
      { name: "Table to Graph", minutes: 10, body: "Plot a proportional table. Straight line through the origin — both conditions named.", science_tag: "dual-coding" },
      { name: "Slope Is the Unit Rate", minutes: 12, body: "Rise over run equals the per-one value. Show they are the same number arriving two ways.", science_tag: "elaboration" },
      { name: "Say It With Units", minutes: 10, body: "Not 'the slope is 3' but 'three miles per hour'. A bare number means nothing.", science_tag: "elaboration" },
      { name: "Steeper Means Faster", minutes: 10, body: "Two lines on one grid. Which represents the better deal? Steepness given meaning.", science_tag: "dual-coding" },
      { name: "Compare Across Forms", minutes: 12, body: "One as a graph, one as a table, one as an equation. Convert to unit rates and judge.", science_tag: "interleaving" },
      { name: "Interpret a Slope", minutes: 3, body: "Given a graph, say what its slope means in context.", science_tag: "spaced" },
    ],
    ef_supports: ["Graph paper with labelled axes", "Units required at every step", "Two lines on one grid for comparison", "Conversion routine for mixed forms"],
    tech: "Graph paper and printed tables",
    tech_purpose: "Comparing steepness needs a shared grid",
    ai_prompts: ["Generate proportional relationships in table, graph and equation form", "Create comparison problems across representations"],
    assessment: ["Check slopes carry units", "Confirm both graph conditions are named", "Verify cross-form comparisons"],
    why_it_works: ["Slope and unit rate arriving as the same number connects two topics", "Units turn slope from arithmetic into meaning", "Two lines on one grid makes steepness comparative", "Cross-form comparison is what the standard actually asks for"],
  },
];

await seedStandardsBatch({
  label: "Batch 4",
  standardsData,
  unpacksData,
  blueprintsData,
});
