// @ts-nocheck
/**
 * Batch 3: 20 more drafted standards.
 *
 * Where batch 2 deepened existing strands, this one opens domains the library
 * had nothing in at all — measurement and data, geometry, statistics and
 * probability, and functions on the maths side; fluency, grammar conventions
 * and argument evaluation on the ELA side.
 *
 *   bun run scripts/seed-standards-batch-3.ts
 */
import { seedStandardsBatch } from "./lib/seed-standards-batch";

const standardsData = [
  // ─── ELA ────────────────────────────────────────────────────────────────
  {
    code: "RL.K.1",
    name: "Ask and answer questions about a story",
    plain_reading:
      "With prompting and support, ask and answer questions about key details in a text.",
    learning_target: "I can ask and answer questions about the story we read.",
    skills: ["Comprehension", "Questioning", "Key Details"],
    science_tags: ["retrieval", "collaborative"],
    match_keys: ["ask and answer questions", "key details", "kindergarten comprehension", "with prompting"],
  },
  {
    code: "RI.1.1",
    name: "Ask and answer questions about a true text",
    plain_reading: "Ask and answer questions about key details in a text.",
    learning_target: "I can ask and answer questions about a book that tells me true things.",
    skills: ["Comprehension", "Questioning", "Nonfiction"],
    science_tags: ["retrieval", "elaboration"],
    match_keys: ["informational text", "ask and answer", "key details", "nonfiction comprehension"],
  },
  {
    code: "W.2.1",
    name: "Write an opinion with reasons",
    plain_reading:
      "Write opinion pieces in which they introduce the topic or book, state an opinion, supply reasons that support the opinion, use linking words to connect opinion and reasons, and provide a concluding statement.",
    learning_target: "I can say what I think about a book and give reasons why.",
    skills: ["Opinion Writing", "Reasons", "Linking Words"],
    science_tags: ["elaboration", "spaced"],
    match_keys: ["opinion writing", "reasons", "linking words", "because", "concluding statement"],
  },
  {
    code: "L.2.1",
    name: "Use standard English grammar when writing and speaking",
    plain_reading:
      "Demonstrate command of the conventions of standard English grammar and usage when writing or speaking, including collective nouns, irregular plurals, and past tense of irregular verbs.",
    learning_target: "I can use the right words and word endings when I write and talk.",
    skills: ["Grammar", "Conventions", "Usage"],
    science_tags: ["retrieval", "interleaving"],
    match_keys: ["grammar", "conventions", "irregular plurals", "past tense", "collective nouns", "usage"],
  },
  {
    code: "RI.3.2",
    name: "Find the main idea and the details that support it",
    plain_reading:
      "Determine the main idea of a text; recount the key details and explain how they support the main idea.",
    learning_target: "I can name the big idea of a text and show which details hold it up.",
    skills: ["Main Idea", "Supporting Details", "Nonfiction"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["main idea", "key details", "support the main idea", "informational text", "recount"],
  },
  {
    code: "RF.3.4",
    name: "Read accurately and fluently to understand",
    plain_reading:
      "Read with sufficient accuracy and fluency to support comprehension, including reading on-level text with purpose, appropriate rate, expression, and self-correction.",
    learning_target: "I can read smoothly enough that I still understand what I read.",
    skills: ["Fluency", "Accuracy", "Expression"],
    science_tags: ["retrieval", "spaced"],
    match_keys: ["fluency", "reading rate", "expression", "prosody", "self-correction", "accuracy"],
  },
  {
    code: "RL.4.2",
    name: "Determine a theme from details in the text",
    plain_reading:
      "Determine a theme of a story, drama, or poem from details in the text; summarize the text.",
    learning_target: "I can work out the message of a story using details, and sum the story up.",
    skills: ["Theme", "Summarising", "Inference"],
    science_tags: ["elaboration", "dual-coding"],
    match_keys: ["theme", "message", "lesson", "summarize", "details in the text"],
  },
  {
    code: "RI.6.8",
    name: "Trace and evaluate an argument",
    plain_reading:
      "Trace and evaluate the argument and specific claims in a text, distinguishing claims that are supported by reasons and evidence from claims that are not.",
    learning_target: "I can follow an author's argument and tell which claims are actually backed up.",
    skills: ["Argument Analysis", "Evaluating Evidence", "Critical Reading"],
    science_tags: ["elaboration", "interleaving"],
    match_keys: ["trace an argument", "evaluate claims", "supported by evidence", "unsupported claims", "reasoning"],
  },
  {
    code: "RI.7.2",
    name: "Determine central ideas and how they develop",
    plain_reading:
      "Determine two or more central ideas in a text and analyze their development over the course of the text; provide an objective summary of the text.",
    learning_target: "I can find more than one central idea and trace how each is built up.",
    skills: ["Central Idea", "Development", "Objective Summary"],
    science_tags: ["elaboration", "dual-coding"],
    match_keys: ["central ideas", "development", "objective summary", "analyze", "informational"],
  },
  {
    code: "SL.8.1",
    name: "Lead and sustain a collaborative discussion",
    plain_reading:
      "Engage effectively in a range of collaborative discussions on grade 8 topics, texts, and issues, building on others' ideas, posing questions that connect ideas, and qualifying or justifying their own views.",
    learning_target: "I can push a discussion forward and change my mind when the evidence earns it.",
    skills: ["Discussion", "Questioning", "Justifying Views"],
    science_tags: ["collaborative", "elaboration"],
    match_keys: ["collaborative discussion", "qualify views", "pose questions", "socratic seminar", "justify"],
  },

  // ─── Mathematics ────────────────────────────────────────────────────────
  {
    code: "K.CC.B.4",
    name: "Connect counting to how many",
    plain_reading:
      "Understand the relationship between numbers and quantities; connect counting to cardinality, including that the last number said tells the number of objects counted.",
    learning_target: "I know the last number I say is how many there are.",
    skills: ["Cardinality", "One-to-One Correspondence", "Counting"],
    science_tags: ["dual-coding", "retrieval"],
    match_keys: ["cardinality", "one to one correspondence", "how many", "last number counted", "counting objects"],
  },
  {
    code: "1.G.A.3",
    name: "Partition shapes into halves and quarters",
    plain_reading:
      "Partition circles and rectangles into two and four equal shares, describe the shares using the words halves, fourths, and quarters, and understand that decomposing into more equal shares creates smaller shares.",
    learning_target: "I can split a shape into equal parts and name them halves or quarters.",
    skills: ["Partitioning", "Equal Shares", "Early Fractions"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["halves", "fourths", "quarters", "equal shares", "partition shapes"],
  },
  {
    code: "2.MD.A.1",
    name: "Measure length with the right tool",
    plain_reading:
      "Measure the length of an object by selecting and using appropriate tools such as rulers, yardsticks, meter sticks, and measuring tapes.",
    learning_target: "I can pick the right tool and measure how long something is.",
    skills: ["Measurement", "Tool Selection", "Length"],
    science_tags: ["dual-coding", "collaborative"],
    match_keys: ["measure length", "ruler", "measuring tape", "appropriate tool", "units"],
  },
  {
    code: "3.MD.C.7",
    name: "Relate area to multiplication",
    plain_reading:
      "Relate area to the operations of multiplication and addition, including finding area by tiling and by multiplying side lengths.",
    learning_target: "I can find area by covering a shape with squares or by multiplying its sides.",
    skills: ["Area", "Multiplication", "Tiling"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["area", "square units", "tiling", "multiply side lengths", "rectangles"],
  },
  {
    code: "4.G.A.1",
    name: "Draw and identify lines and angles",
    plain_reading:
      "Draw points, lines, line segments, rays, angles (right, acute, obtuse), and perpendicular and parallel lines. Identify these in two-dimensional figures.",
    learning_target: "I can draw and name the different kinds of lines and angles.",
    skills: ["Geometry Vocabulary", "Angles", "Lines"],
    science_tags: ["dual-coding", "retrieval"],
    match_keys: ["lines", "rays", "angles", "acute", "obtuse", "parallel", "perpendicular"],
  },
  {
    code: "5.MD.C.5",
    name: "Find the volume of a rectangular prism",
    plain_reading:
      "Relate volume to the operations of multiplication and addition and solve real world and mathematical problems involving volume of right rectangular prisms.",
    learning_target: "I can find how much space a box holds and explain why the formula works.",
    skills: ["Volume", "Multiplication", "Three-Dimensional Reasoning"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["volume", "cubic units", "rectangular prism", "length times width times height", "layers"],
  },
  {
    code: "6.EE.A.2",
    name: "Write, read and evaluate expressions with variables",
    plain_reading:
      "Write, read, and evaluate expressions in which letters stand for numbers, including translating between words and algebraic expressions and evaluating at specific values.",
    learning_target: "I can turn words into an expression with a letter and work out its value.",
    skills: ["Expressions", "Variables", "Evaluating"],
    science_tags: ["interleaving", "elaboration"],
    match_keys: ["algebraic expressions", "variables", "evaluate", "translate words", "substitute"],
  },
  {
    code: "7.G.B.6",
    name: "Solve area, volume and surface area problems",
    plain_reading:
      "Solve real-world and mathematical problems involving area, volume and surface area of two- and three-dimensional objects composed of triangles, quadrilaterals, polygons, cubes, and right prisms.",
    learning_target: "I can work out area, surface area or volume and know which one the question wants.",
    skills: ["Area", "Surface Area", "Volume"],
    science_tags: ["interleaving", "dual-coding"],
    match_keys: ["surface area", "volume", "composite figures", "prisms", "nets", "area of polygons"],
  },
  {
    code: "7.SP.C.5",
    name: "Understand the probability of a chance event",
    plain_reading:
      "Understand that the probability of a chance event is a number between 0 and 1 that expresses the likelihood of the event occurring, with larger numbers indicating greater likelihood.",
    learning_target: "I can put the chance of something happening on a scale from 0 to 1.",
    skills: ["Probability", "Likelihood", "Proportional Reasoning"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["probability", "likelihood", "chance event", "impossible certain", "between 0 and 1"],
  },
  {
    code: "8.F.A.1",
    name: "Understand what makes a relationship a function",
    plain_reading:
      "Understand that a function is a rule that assigns to each input exactly one output; the graph of a function is the set of ordered pairs consisting of an input and the corresponding output.",
    learning_target: "I can tell whether a relationship is a function and say why.",
    skills: ["Functions", "Input and Output", "Graph Interpretation"],
    science_tags: ["dual-coding", "interleaving"],
    match_keys: ["function", "input output", "vertical line test", "exactly one output", "ordered pairs"],
  },
];

const unpacksData = [
  {
    standard_code: "RL.K.1",
    verbs: [
      { word: "Ask", gloss: "wonder something out loud about the story" },
      { word: "Answer", gloss: "say what you think, using the story" },
    ],
    concepts: ["Key details", "Questioning", "Listening comprehension"],
    vocabulary: [
      { term: "question", definition: "something you ask when you want to know more" },
      { term: "answer", definition: "what you say back to a question" },
      { term: "story", definition: "a book that tells about made-up things happening" },
      { term: "detail", definition: "a small thing the story tells you" },
    ],
    prior_skills: ["Listen to a whole story", "Look at pictures for meaning", "Talk about a book"],
    prior_standards: [{ code: "PK.RL.1", text: "Engage with a story and respond to simple questions" }],
    future_standards: [{ code: "RL.1.1", text: "Ask and answer questions about key details in a text" }],
    challenges: [
      { problem: "Answers wander into personal stories", fix: "Redirect with 'what did the book say?'" },
      { problem: "Students echo the last thing said", fix: "Ask several children before confirming" },
    ],
    mastery_statement: "Student can ask and answer questions about key details in a read-aloud with prompting and support.",
    ladder: [
      { name: "I can listen to the whole story", descriptor: "Attends through a read-aloud" },
      { name: "I can answer a question about it", descriptor: "Responds using story content" },
      { name: "I can ask a question about it", descriptor: "Poses a relevant question" },
      { name: "I can point to the part that shows it", descriptor: "Connects answer to page" },
    ],
  },
  {
    standard_code: "RI.1.1",
    verbs: [
      { word: "Ask", gloss: "pose a question about the facts" },
      { word: "Answer", gloss: "respond using what the text said" },
    ],
    concepts: ["Key details", "Fact vs story", "Questioning"],
    vocabulary: [
      { term: "information", definition: "true things a book tells you" },
      { term: "fact", definition: "something true you can check" },
      { term: "detail", definition: "a small piece of information" },
      { term: "topic", definition: "what the book is about" },
    ],
    prior_skills: ["Ask questions about a story", "Recognize a nonfiction book", "Use pictures for information"],
    prior_standards: [{ code: "RI.K.1", text: "Ask and answer questions about key details with prompting" }],
    future_standards: [{ code: "RI.2.1", text: "Ask and answer who, what, where, when, why and how questions" }],
    challenges: [
      { problem: "Prior knowledge replaces the text", fix: "Ask 'did the book say that, or did you already know it?'" },
      { problem: "Questions are all about pictures", fix: "Cover the pictures for one reading" },
    ],
    mastery_statement: "Student can ask and answer questions about key details in an informational text using the text itself.",
    ladder: [
      { name: "I can tell a true book from a story", descriptor: "Distinguishes genres" },
      { name: "I can answer a question about the facts", descriptor: "Responds from the text" },
      { name: "I can ask my own question", descriptor: "Poses a relevant question" },
      { name: "I can show where the answer is", descriptor: "Locates supporting text" },
    ],
  },
  {
    standard_code: "W.2.1",
    verbs: [
      { word: "State", gloss: "say clearly what you think" },
      { word: "Supply", gloss: "give reasons that back it up" },
      { word: "Connect", gloss: "join opinion and reason with a linking word" },
    ],
    concepts: ["Opinion", "Reasons", "Structure"],
    vocabulary: [
      { term: "opinion", definition: "what you think about something" },
      { term: "reason", definition: "why you think it" },
      { term: "linking word", definition: "a word like because that joins ideas" },
      { term: "conclusion", definition: "the sentence that finishes your writing" },
    ],
    prior_skills: ["Say what you like and why", "Write complete sentences", "Use because in speech"],
    prior_standards: [{ code: "W.1.1", text: "Write opinion pieces introducing a topic and giving a reason" }],
    future_standards: [{ code: "W.3.1", text: "Write opinion pieces with organized reasons" }],
    challenges: [
      { problem: "Only one reason appears", fix: "Require two boxes filled before drafting" },
      { problem: "Reasons repeat the opinion", fix: "Read it back with because and check it adds something" },
    ],
    mastery_statement: "Student can write an opinion piece with a stated opinion, two reasons, linking words and a closing statement.",
    ladder: [
      { name: "I can say what I think", descriptor: "States an opinion" },
      { name: "I can give one reason", descriptor: "Supplies supporting reason" },
      { name: "I can give two reasons", descriptor: "Supplies multiple reasons" },
      { name: "I can join them and finish", descriptor: "Uses linking words and a conclusion" },
    ],
  },
  {
    standard_code: "L.2.1",
    verbs: [
      { word: "Demonstrate", gloss: "show it in your own writing and speech" },
      { word: "Use", gloss: "apply the convention correctly" },
    ],
    concepts: ["Grammar conventions", "Irregular forms", "Usage in context"],
    vocabulary: [
      { term: "noun", definition: "a word for a person, place or thing" },
      { term: "verb", definition: "a word for something you do" },
      { term: "plural", definition: "more than one" },
      { term: "past tense", definition: "the form of a verb for something already done" },
    ],
    prior_skills: ["Write complete sentences", "Use capital letters and full stops", "Identify nouns and verbs"],
    prior_standards: [{ code: "L.1.1", text: "Demonstrate command of grade 1 grammar conventions" }],
    future_standards: [{ code: "L.3.1", text: "Explain the function of parts of speech in sentences" }],
    challenges: [
      { problem: "Irregular forms get regularised — 'runned', 'mouses'", fix: "Collect irregulars on a class chart and revisit weekly" },
      { problem: "Grammar is correct in exercises but not in writing", fix: "Edit their own drafts, not worksheet sentences" },
    ],
    mastery_statement: "Student can use standard grammar conventions, including irregular plurals and past tense, in their own writing.",
    ladder: [
      { name: "I can write a complete sentence", descriptor: "Subject and verb present" },
      { name: "I can make regular plurals", descriptor: "Adds -s and -es correctly" },
      { name: "I can use irregular forms", descriptor: "Uses children, mice, ran, went" },
      { name: "I can fix my own writing", descriptor: "Self-edits for conventions" },
    ],
  },
  {
    standard_code: "RI.3.2",
    verbs: [
      { word: "Determine", gloss: "work out the main idea" },
      { word: "Recount", gloss: "tell the key details" },
      { word: "Explain", gloss: "show how details support the idea" },
    ],
    concepts: ["Main idea", "Supporting details", "Idea vs topic"],
    vocabulary: [
      { term: "main idea", definition: "the most important point of the text" },
      { term: "topic", definition: "what the text is about in a word or two" },
      { term: "key detail", definition: "an important fact that holds up the main idea" },
      { term: "support", definition: "to back up or hold up an idea" },
    ],
    prior_skills: ["Identify the topic", "Recall details", "Retell a text"],
    prior_standards: [{ code: "RI.2.2", text: "Identify the main topic of a multiparagraph text" }],
    future_standards: [{ code: "RI.4.2", text: "Determine the main idea and explain supporting details" }],
    challenges: [
      { problem: "Topic is given as the main idea", fix: "Require a full sentence, not a noun phrase" },
      { problem: "First sentence is assumed to be the main idea", fix: "Use texts where it is not" },
    ],
    mastery_statement: "Student can state a main idea as a sentence and explain how specific details support it.",
    ladder: [
      { name: "I can say what the text is about", descriptor: "Names the topic" },
      { name: "I can state the main idea in a sentence", descriptor: "Goes beyond topic" },
      { name: "I can list key details", descriptor: "Selects important facts" },
      { name: "I can explain how details support it", descriptor: "Links detail to idea" },
    ],
  },
  {
    standard_code: "RF.3.4",
    verbs: [
      { word: "Read", gloss: "decode the words on the page" },
      { word: "Self-correct", gloss: "notice and fix a mistake as you go" },
    ],
    concepts: ["Accuracy", "Rate", "Prosody"],
    vocabulary: [
      { term: "fluency", definition: "reading smoothly, accurately and with expression" },
      { term: "rate", definition: "how fast you read" },
      { term: "expression", definition: "reading so it sounds like talking" },
      { term: "self-correct", definition: "fix your own mistake without being told" },
    ],
    prior_skills: ["Decode grade-level words", "Read familiar text aloud", "Recognize common sight words"],
    prior_standards: [{ code: "RF.2.4", text: "Read with sufficient accuracy and fluency at grade 2" }],
    future_standards: [{ code: "RF.4.4", text: "Read grade 4 text with accuracy, appropriate rate and expression" }],
    challenges: [
      { problem: "Speed is chased at the cost of meaning", fix: "Ask a comprehension question after every timed read" },
      { problem: "Reading is accurate but flat", fix: "Model phrasing with a marked-up text" },
    ],
    mastery_statement: "Student can read grade-level text accurately, at an appropriate rate and with expression that supports comprehension.",
    ladder: [
      { name: "I can read the words correctly", descriptor: "Decodes accurately" },
      { name: "I can read at a steady pace", descriptor: "Appropriate rate" },
      { name: "I can read with expression", descriptor: "Phrasing and intonation" },
      { name: "I can fix my own mistakes", descriptor: "Self-corrects for meaning" },
    ],
  },
  {
    standard_code: "RL.4.2",
    verbs: [
      { word: "Determine", gloss: "work out the theme" },
      { word: "Summarize", gloss: "capture the story in short form" },
    ],
    concepts: ["Theme", "Details as evidence", "Summary"],
    vocabulary: [
      { term: "theme", definition: "the message or lesson a story teaches" },
      { term: "topic", definition: "what the story is about on the surface" },
      { term: "summary", definition: "a short version keeping only what matters" },
      { term: "evidence", definition: "the details that point to the theme" },
    ],
    prior_skills: ["Retell a story", "Describe characters", "Identify a lesson in a fable"],
    prior_standards: [{ code: "RL.3.2", text: "Recount stories and determine the central message" }],
    future_standards: [{ code: "RL.5.2", text: "Determine a theme from details including character response" }],
    challenges: [
      { problem: "Theme is given as one word", fix: "Require a sentence that states a message" },
      { problem: "Summary becomes a full retell", fix: "Impose a sentence limit" },
    ],
    mastery_statement: "Student can state a theme as a message supported by details, and summarize the story concisely.",
    ladder: [
      { name: "I can retell the story", descriptor: "Recounts events in order" },
      { name: "I can name what the story is about", descriptor: "Identifies the topic" },
      { name: "I can state the theme as a message", descriptor: "Writes a full claim" },
      { name: "I can point to details that show it", descriptor: "Supports theme with evidence" },
    ],
  },
  {
    standard_code: "RI.6.8",
    verbs: [
      { word: "Trace", gloss: "follow the argument through the text" },
      { word: "Evaluate", gloss: "judge how well it holds up" },
      { word: "Distinguish", gloss: "separate supported claims from bare assertions" },
    ],
    concepts: ["Claim", "Evidence quality", "Argument structure"],
    vocabulary: [
      { term: "claim", definition: "something the author says is true" },
      { term: "evidence", definition: "the facts offered to back a claim" },
      { term: "reasoning", definition: "the thinking that connects evidence to claim" },
      { term: "unsupported", definition: "stated but never backed up" },
    ],
    prior_skills: ["Identify a main idea", "Cite evidence", "Distinguish fact from opinion"],
    prior_standards: [{ code: "RI.5.8", text: "Explain how an author uses reasons and evidence to support points" }],
    future_standards: [{ code: "RI.7.8", text: "Assess whether reasoning is sound and evidence sufficient" }],
    challenges: [
      { problem: "Confident writing is mistaken for supported writing", fix: "Highlight claims and evidence in two colors and compare" },
      { problem: "Students evaluate whether they agree, not whether it is supported", fix: "Analyze an argument they agree with but that lacks evidence" },
    ],
    mastery_statement: "Student can map an author's argument and identify which claims are supported by evidence and which are not.",
    ladder: [
      { name: "I can find the author's main claim", descriptor: "Identifies the overall position" },
      { name: "I can list the supporting claims", descriptor: "Traces the argument" },
      { name: "I can find the evidence for each", descriptor: "Matches evidence to claim" },
      { name: "I can spot a claim with no support", descriptor: "Evaluates rather than agrees" },
    ],
  },
  {
    standard_code: "RI.7.2",
    verbs: [
      { word: "Determine", gloss: "identify the central ideas" },
      { word: "Analyze", gloss: "examine how each is developed" },
      { word: "Summarize", gloss: "restate without opinion" },
    ],
    concepts: ["Central idea", "Development", "Objectivity"],
    vocabulary: [
      { term: "central idea", definition: "a main point running through the text" },
      { term: "development", definition: "how an idea is built up across a text" },
      { term: "objective", definition: "sticking to the text without your own view" },
      { term: "trace", definition: "follow something through from start to finish" },
    ],
    prior_skills: ["Determine main ideas", "Summarize a text", "Identify supporting details"],
    prior_standards: [{ code: "RI.6.2", text: "Determine a central idea and analyze its development" }],
    future_standards: [{ code: "RI.8.2", text: "Analyze the development of a central idea over the course of a text" }],
    challenges: [
      { problem: "Only one central idea is found", fix: "Section the text and name an idea per section" },
      { problem: "Development is described as 'it talks about it more'", fix: "Require what changes between the first and last mention" },
    ],
    mastery_statement: "Student can identify two or more central ideas, trace how each develops, and summarize the text objectively.",
    ladder: [
      { name: "I can find one central idea", descriptor: "Names a main point" },
      { name: "I can find two or more", descriptor: "Handles a multi-idea text" },
      { name: "I can trace how one develops", descriptor: "Cites moments across the text" },
      { name: "I can write an objective summary", descriptor: "Excludes personal judgement" },
    ],
  },
  {
    standard_code: "SL.8.1",
    verbs: [
      { word: "Pose", gloss: "ask a question that connects ideas" },
      { word: "Qualify", gloss: "adjust your view in light of evidence" },
      { word: "Justify", gloss: "give the reasoning behind your position" },
    ],
    concepts: ["Discussion leadership", "Qualifying a view", "Evidence-based talk"],
    vocabulary: [
      { term: "qualify", definition: "adjust a claim to make it more accurate" },
      { term: "justify", definition: "give reasons for what you said" },
      { term: "connect", definition: "link two people's ideas together" },
      { term: "probe", definition: "ask a question that digs deeper" },
    ],
    prior_skills: ["Build on others' ideas", "Come to a discussion prepared", "Cite evidence in speech"],
    prior_standards: [{ code: "SL.7.1", text: "Engage in collaborative discussions, posing and responding to questions" }],
    future_standards: [{ code: "SL.9-10.1", text: "Initiate and participate in a range of collaborative discussions" }],
    challenges: [
      { problem: "Changing your mind is treated as losing", fix: "Credit qualification explicitly in the tally" },
      { problem: "Questions are asked of the teacher, not the group", fix: "Sit outside the circle and stay silent" },
    ],
    mastery_statement: "Student can pose questions that connect ideas and qualify or justify their own view in discussion.",
    ladder: [
      { name: "I can build on someone's idea", descriptor: "Extends rather than restarts" },
      { name: "I can back my view with evidence", descriptor: "Cites text in speech" },
      { name: "I can ask a question that connects ideas", descriptor: "Links two contributions" },
      { name: "I can change my view when evidence warrants", descriptor: "Qualifies a position" },
    ],
  },
  {
    standard_code: "K.CC.B.4",
    verbs: [
      { word: "Connect", gloss: "link counting to how many there are" },
      { word: "Count", gloss: "say one number for each object" },
    ],
    concepts: ["One-to-one correspondence", "Cardinality", "Conservation"],
    vocabulary: [
      { term: "count", definition: "say numbers in order, one for each thing" },
      { term: "how many", definition: "the total number of things" },
      { term: "last number", definition: "the number that tells you how many" },
      { term: "group", definition: "a set of things together" },
    ],
    prior_skills: ["Say number words in order", "Touch objects one at a time", "Recognize small quantities"],
    prior_standards: [{ code: "K.CC.A.1", text: "Count to 100 by ones and by tens" }],
    future_standards: [{ code: "1.NBT.A.1", text: "Count to 120 and read and write numerals" }],
    challenges: [
      { problem: "Recounting when asked how many", fix: "Ask again immediately — the answer should not need a recount" },
      { problem: "Counting outruns pointing", fix: "Move each object to a second pile as it is counted" },
    ],
    mastery_statement: "Student can count a set with one-to-one correspondence and state that the last number counted is the total.",
    ladder: [
      { name: "I can say numbers in order", descriptor: "Rote sequence secure" },
      { name: "I can touch one thing per number", descriptor: "One-to-one correspondence" },
      { name: "I can say how many without counting again", descriptor: "Cardinality understood" },
      { name: "I know the number stays the same if I move them", descriptor: "Conservation of number" },
    ],
  },
  {
    standard_code: "1.G.A.3",
    verbs: [
      { word: "Partition", gloss: "split a shape into equal parts" },
      { word: "Describe", gloss: "name the parts using fraction words" },
    ],
    concepts: ["Equal shares", "Halves and quarters", "More shares means smaller"],
    vocabulary: [
      { term: "half", definition: "one of two equal parts" },
      { term: "quarter", definition: "one of four equal parts" },
      { term: "equal", definition: "exactly the same size" },
      { term: "share", definition: "one of the equal parts of a whole" },
    ],
    prior_skills: ["Identify circles and rectangles", "Compare sizes", "Fold paper in half"],
    prior_standards: [{ code: "K.G.B.6", text: "Compose simple shapes to form larger shapes" }],
    future_standards: [{ code: "2.G.A.3", text: "Partition circles and rectangles into halves, thirds and fourths" }],
    challenges: [
      { problem: "Unequal parts are still called halves", fix: "Cut and stack the parts to check they match" },
      { problem: "More parts is assumed to mean bigger parts", fix: "Compare a half and a quarter of identical shapes" },
    ],
    mastery_statement: "Student can partition circles and rectangles into equal halves and quarters and name the shares.",
    ladder: [
      { name: "I can split a shape into two parts", descriptor: "Partitions into two" },
      { name: "I can make the parts equal", descriptor: "Checks parts match" },
      { name: "I can name halves and quarters", descriptor: "Uses fraction vocabulary" },
      { name: "I know quarters are smaller than halves", descriptor: "Understands inverse relationship" },
    ],
  },
  {
    standard_code: "2.MD.A.1",
    verbs: [
      { word: "Select", gloss: "choose the right measuring tool" },
      { word: "Measure", gloss: "find how long something is" },
    ],
    concepts: ["Units", "Tool selection", "Measuring from zero"],
    vocabulary: [
      { term: "length", definition: "how long something is" },
      { term: "unit", definition: "the size you measure with, like inches" },
      { term: "ruler", definition: "a tool for measuring shorter things" },
      { term: "measuring tape", definition: "a bendy tool for measuring longer or curved things" },
    ],
    prior_skills: ["Compare lengths directly", "Count units end to end", "Order objects by length"],
    prior_standards: [{ code: "1.MD.A.2", text: "Express the length of an object as whole units" }],
    future_standards: [{ code: "3.MD.B.4", text: "Measure lengths to the nearest half and quarter inch" }],
    challenges: [
      { problem: "Measuring starts at the end of the ruler, not zero", fix: "Mark the zero line and check alignment first" },
      { problem: "Any tool is used for any object", fix: "Pose objects that make a ruler obviously wrong" },
    ],
    mastery_statement: "Student can select an appropriate tool and measure an object's length accurately from zero.",
    ladder: [
      { name: "I can compare two lengths", descriptor: "Orders by length" },
      { name: "I can line up at zero", descriptor: "Aligns correctly" },
      { name: "I can measure with a ruler", descriptor: "Reads the measurement" },
      { name: "I can pick the right tool", descriptor: "Matches tool to object" },
    ],
  },
  {
    standard_code: "3.MD.C.7",
    verbs: [
      { word: "Relate", gloss: "connect area to multiplication" },
      { word: "Tile", gloss: "cover a shape with unit squares" },
    ],
    concepts: ["Area as covering", "Square units", "Area and multiplication"],
    vocabulary: [
      { term: "area", definition: "how much space a flat shape covers" },
      { term: "square unit", definition: "one square used to measure area" },
      { term: "tile", definition: "cover completely with no gaps or overlaps" },
      { term: "side length", definition: "how long one edge of a shape is" },
    ],
    prior_skills: ["Multiply within 100", "Understand arrays", "Count squares in a grid"],
    prior_standards: [{ code: "3.OA.A.1", text: "Interpret products of whole numbers" }],
    future_standards: [{ code: "4.MD.A.3", text: "Apply area and perimeter formulas for rectangles" }],
    challenges: [
      { problem: "Area and perimeter get confused", fix: "Do both on the same shape and label what each measures" },
      { problem: "Tiles are counted with gaps or overlaps", fix: "Use physical tiles before drawn grids" },
    ],
    mastery_statement: "Student can find area by tiling and by multiplying side lengths, and explain why the two agree.",
    ladder: [
      { name: "I can cover a shape with squares", descriptor: "Tiles without gaps" },
      { name: "I can count the squares", descriptor: "Finds area by counting" },
      { name: "I can multiply the sides instead", descriptor: "Applies the shortcut" },
      { name: "I can explain why they match", descriptor: "Connects rows to multiplication" },
    ],
  },
  {
    standard_code: "4.G.A.1",
    verbs: [
      { word: "Draw", gloss: "produce the figure accurately" },
      { word: "Identify", gloss: "spot it inside a larger shape" },
    ],
    concepts: ["Geometric vocabulary", "Angle classification", "Line relationships"],
    vocabulary: [
      { term: "ray", definition: "a line with one endpoint that goes on forever the other way" },
      { term: "acute angle", definition: "an angle smaller than a right angle" },
      { term: "obtuse angle", definition: "an angle bigger than a right angle" },
      { term: "parallel", definition: "lines that never meet, always the same distance apart" },
    ],
    prior_skills: ["Recognize 2D shapes", "Identify right angles", "Use a ruler to draw straight lines"],
    prior_standards: [{ code: "3.G.A.1", text: "Understand shapes in categories by shared attributes" }],
    future_standards: [{ code: "5.G.B.3", text: "Understand attributes of categories of two-dimensional figures" }],
    challenges: [
      { problem: "Line, segment and ray are used interchangeably", fix: "Draw all three side by side with arrows marked" },
      { problem: "Angle size is judged by the length of the arms", fix: "Show the same angle with long and short arms" },
    ],
    mastery_statement: "Student can draw and identify points, lines, segments, rays, angle types and parallel or perpendicular lines.",
    ladder: [
      { name: "I can draw a line and a segment", descriptor: "Distinguishes the two" },
      { name: "I can identify a right angle", descriptor: "Recognizes 90 degrees" },
      { name: "I can classify acute and obtuse", descriptor: "Compares to a right angle" },
      { name: "I can find them inside a shape", descriptor: "Identifies within figures" },
    ],
  },
  {
    standard_code: "5.MD.C.5",
    verbs: [
      { word: "Relate", gloss: "connect volume to multiplication" },
      { word: "Solve", gloss: "answer real volume problems" },
    ],
    concepts: ["Cubic units", "Layers", "Volume formula"],
    vocabulary: [
      { term: "volume", definition: "how much space a solid shape takes up" },
      { term: "cubic unit", definition: "one cube used to measure volume" },
      { term: "layer", definition: "one flat level of cubes" },
      { term: "prism", definition: "a solid with the same shape all the way through" },
    ],
    prior_skills: ["Find area of rectangles", "Multiply multi-digit numbers", "Build with unit cubes"],
    prior_standards: [{ code: "5.MD.C.4", text: "Measure volume by counting unit cubes" }],
    future_standards: [{ code: "6.G.A.2", text: "Find volume of prisms with fractional edge lengths" }],
    challenges: [
      { problem: "Volume and surface area get confused", fix: "Build one box and compute both, labelling the units" },
      { problem: "The formula is applied without meaning", fix: "Build the layers first and count them" },
    ],
    mastery_statement: "Student can find the volume of a rectangular prism and explain the formula as layers of area.",
    ladder: [
      { name: "I can count cubes in a solid", descriptor: "Finds volume by counting" },
      { name: "I can see the layers", descriptor: "Identifies repeated area" },
      { name: "I can multiply to find volume", descriptor: "Applies the formula" },
      { name: "I can explain why the formula works", descriptor: "Connects area to layers" },
    ],
  },
  {
    standard_code: "6.EE.A.2",
    verbs: [
      { word: "Write", gloss: "turn words into an expression" },
      { word: "Read", gloss: "say what an expression means" },
      { word: "Evaluate", gloss: "work out its value for a given number" },
    ],
    concepts: ["Variables", "Translation", "Order of operations"],
    vocabulary: [
      { term: "expression", definition: "a maths phrase with no equals sign" },
      { term: "variable", definition: "a letter standing for a number" },
      { term: "coefficient", definition: "the number multiplying a variable" },
      { term: "evaluate", definition: "work out the value by substituting" },
    ],
    prior_skills: ["Apply order of operations", "Write numeric expressions", "Substitute values"],
    prior_standards: [{ code: "5.OA.A.2", text: "Write simple expressions that record calculations" }],
    future_standards: [{ code: "7.EE.A.1", text: "Apply properties to add, factor and expand expressions" }],
    challenges: [
      { problem: "'Less than' is translated in the wrong order", fix: "Rewrite the phrase before translating: 5 less than x is x - 5" },
      { problem: "Order of operations is dropped when substituting", fix: "Substitute in brackets every time" },
    ],
    mastery_statement: "Student can translate between words and algebraic expressions and evaluate them at given values.",
    ladder: [
      { name: "I can evaluate a numeric expression", descriptor: "Applies order of operations" },
      { name: "I can substitute a value for a letter", descriptor: "Replaces and computes" },
      { name: "I can write an expression from words", descriptor: "Translates correctly" },
      { name: "I can read an expression back in words", descriptor: "Describes structure" },
    ],
  },
  {
    standard_code: "7.G.B.6",
    verbs: [
      { word: "Solve", gloss: "answer the problem asked" },
      { word: "Decompose", gloss: "break a composite figure into simple ones" },
    ],
    concepts: ["Area of composites", "Surface area via nets", "Volume of prisms"],
    vocabulary: [
      { term: "surface area", definition: "the total area of all the faces" },
      { term: "net", definition: "a flat pattern that folds into a solid" },
      { term: "composite figure", definition: "a shape made from simpler shapes" },
      { term: "prism", definition: "a solid with two identical parallel faces" },
    ],
    prior_skills: ["Find area of triangles and quadrilaterals", "Find volume of prisms", "Work with nets"],
    prior_standards: [{ code: "6.G.A.4", text: "Represent three-dimensional figures using nets" }],
    future_standards: [{ code: "8.G.C.9", text: "Know and use volume formulas for cones, cylinders and spheres" }],
    challenges: [
      { problem: "Surface area and volume are confused", fix: "Ask what units the answer needs before computing" },
      { problem: "Composite figures are treated as one shape", fix: "Draw the dividing line before any calculation" },
    ],
    mastery_statement: "Student can find area, surface area and volume of composite figures and choose the right measure for the question.",
    ladder: [
      { name: "I can find the area of a triangle", descriptor: "Applies the formula" },
      { name: "I can break a composite figure apart", descriptor: "Decomposes into simple shapes" },
      { name: "I can find surface area from a net", descriptor: "Sums the faces" },
      { name: "I can tell which measure the question wants", descriptor: "Selects area, surface area or volume" },
    ],
  },
  {
    standard_code: "7.SP.C.5",
    verbs: [
      { word: "Understand", gloss: "know what a probability number means" },
      { word: "Express", gloss: "state likelihood as a number" },
    ],
    concepts: ["Probability scale", "Likelihood language", "Impossible to certain"],
    vocabulary: [
      { term: "probability", definition: "a number from 0 to 1 telling how likely something is" },
      { term: "impossible", definition: "it can never happen, probability 0" },
      { term: "certain", definition: "it must happen, probability 1" },
      { term: "likely", definition: "more likely to happen than not" },
    ],
    prior_skills: ["Work with fractions and decimals", "Convert between fractions, decimals and percents", "Describe likelihood in words"],
    prior_standards: [{ code: "6.RP.A.3", text: "Use ratio reasoning to solve problems" }],
    future_standards: [{ code: "7.SP.C.7", text: "Develop a probability model and use it to find probabilities" }],
    challenges: [
      { problem: "Probabilities are given greater than 1 or as whole numbers", fix: "Place every answer on a 0 to 1 line before accepting it" },
      { problem: "Unlikely is treated as impossible", fix: "Distinguish 0 from a small probability explicitly" },
    ],
    mastery_statement: "Student can express the likelihood of an event as a number between 0 and 1 and interpret what it means.",
    ladder: [
      { name: "I can say if something is likely or unlikely", descriptor: "Uses likelihood language" },
      { name: "I can place events on a 0 to 1 line", descriptor: "Orders by likelihood" },
      { name: "I can give a probability as a fraction", descriptor: "Computes simple probabilities" },
      { name: "I can explain what the number means", descriptor: "Interprets in context" },
    ],
  },
  {
    standard_code: "8.F.A.1",
    verbs: [
      { word: "Understand", gloss: "know what makes a relation a function" },
      { word: "Determine", gloss: "decide whether something is a function" },
    ],
    concepts: ["Input and output", "Exactly one output", "Representations of functions"],
    vocabulary: [
      { term: "function", definition: "a rule giving exactly one output for each input" },
      { term: "input", definition: "the value you put in" },
      { term: "output", definition: "the value that comes out" },
      { term: "ordered pair", definition: "an input and its output written together" },
    ],
    prior_skills: ["Plot ordered pairs", "Read a table of values", "Recognize proportional relationships"],
    prior_standards: [{ code: "7.RP.A.2", text: "Recognize and represent proportional relationships" }],
    future_standards: [{ code: "F-IF.1", text: "Understand function notation and domain and range" }],
    challenges: [
      { problem: "Repeated outputs are assumed to break the rule", fix: "Show a valid function where two inputs share an output" },
      { problem: "The vertical line test is used without understanding", fix: "Connect the test back to the one-output rule" },
    ],
    mastery_statement: "Student can determine whether a relationship is a function and justify it by the one-output rule.",
    ladder: [
      { name: "I can read inputs and outputs from a table", descriptor: "Interprets representations" },
      { name: "I can state the function rule", descriptor: "Says exactly one output per input" },
      { name: "I can test a table or set of pairs", descriptor: "Checks for repeated inputs" },
      { name: "I can test a graph", descriptor: "Applies and explains the vertical line test" },
    ],
  },
];

const blueprintsData = [
  {
    standard_code: "RL.K.1",
    title: "Wondering About Stories",
    badge: "Kindergarten",
    route_name: "Interactive Read-Aloud",
    route_line: "Model wondering → Wonder together → Answer from the book",
    success_criteria: ["Asks a question about the story", "Answers using something from the story", "Points to the page that shows it"],
    steps: [
      { name: "Retrieve Yesterday's Story", minutes: 5, body: "Who was in it? What happened? Oral recall builds the habit of holding a story in mind.", science_tag: "retrieval" },
      { name: "Model Wondering Aloud", minutes: 8, body: "Read a page, stop, and say 'I wonder why she did that'. Wondering has to be heard before it can be done.", science_tag: "elaboration" },
      { name: "Question Words Chart", minutes: 8, body: "Who, what, where. Three only at this stage. Picture cue for each so non-readers can use the chart.", science_tag: "dual-coding" },
      { name: "Turn and Wonder", minutes: 10, body: "Stop three times during the read-aloud. Partners share a question each time. Everyone talks, every time.", science_tag: "collaborative" },
      { name: "Answer from the Book", minutes: 10, body: "Take student questions and answer them together, turning back to the page each time. The page-turn is the habit being built.", science_tag: "retrieval" },
      { name: "Draw Your Question", minutes: 10, body: "Students draw something they wondered about. Drawing lets them record a question they cannot yet write.", science_tag: "dual-coding" },
      { name: "Share Three", minutes: 4, body: "Three students share a question and where the answer was. Celebrate the page-turn.", science_tag: "spaced" },
    ],
    ef_supports: ["Question word chart with pictures", "Turn-and-talk before whole group", "Draw instead of write", "Stop points marked in the book"],
    tech: "Big book with marked stop points",
    tech_purpose: "Shared text so every child sees the page being referenced",
    ai_prompts: ["Write a kindergarten read-aloud with natural wondering points", "Generate who/what/where questions for a picture book"],
    assessment: ["Listen during turn-and-talk for real questions", "Check drawings represent a question", "Note who turns back to the page"],
    why_it_works: ["Wondering aloud makes an internal process audible", "Three question words is the right load for kindergarten", "Turning back to the page builds text-based answering from the start", "Drawing removes writing as a barrier to showing thinking"],
  },
  {
    standard_code: "RI.1.1",
    title: "Questions About True Books",
    badge: "Grade 1",
    route_name: "Interactive Read-Aloud",
    route_line: "Separate true from story → Ask about facts → Find the answer",
    success_criteria: ["Tells an informational book from a story", "Asks a question about the facts", "Finds the answer in the text, not from memory"],
    steps: [
      { name: "Retrieve Story Questions", minutes: 5, body: "Quick questions about a familiar story. The skill transfers; the text type changes.", science_tag: "retrieval" },
      { name: "True Book or Story", minutes: 8, body: "Sort six books. What tells you? Photographs, headings, facts. The sort defines the genre.", science_tag: "dual-coding" },
      { name: "Read and Stop", minutes: 10, body: "Read an informational text, stopping for questions. Model asking about a fact rather than a feeling.", science_tag: "elaboration" },
      { name: "Already Knew or Book Told Me", minutes: 12, body: "Sort answers into two piles. This is the lesson — prior knowledge is not the text.", science_tag: "interleaving" },
      { name: "Hunt the Answer", minutes: 10, body: "Give three questions. Students find the page with the answer. Cover the pictures for one of them.", science_tag: "collaborative" },
      { name: "Ask Your Own", minutes: 8, body: "Students write or draw a question about the topic, then find whether the book answers it. Some will not — that is worth naming.", science_tag: "elaboration" },
      { name: "Share and Check", minutes: 2, body: "Two students share a question and the page that answered it.", science_tag: "spaced" },
    ],
    ef_supports: ["Book sorting set", "Two-pile sorting mat for answer sources", "Cover-the-picture routine", "Draw-or-write option"],
    tech: "Informational books with photographs",
    tech_purpose: "Real nonfiction features to sort and search",
    ai_prompts: ["Write a grade 1 informational text on a familiar topic", "Generate questions, some answerable from the text and some not"],
    assessment: ["Check genre sorting accuracy", "Watch the already-knew sort for text-based answering", "Confirm students locate the answering page"],
    why_it_works: ["The two-pile sort makes the text-versus-memory distinction visible", "Covering pictures forces reliance on the words", "Questions the book cannot answer teach that texts have limits", "Genre sorting grounds the shift from story to information"],
  },
  {
    standard_code: "W.2.1",
    title: "What I Think and Why",
    badge: "Grade 2",
    route_name: "Writing Workshop",
    route_line: "State the opinion → Give two reasons → Link and close",
    success_criteria: ["States an opinion in one clear sentence", "Gives two reasons that add new information", "Uses a linking word and a closing sentence"],
    steps: [
      { name: "Retrieve Opinion Words", minutes: 5, body: "I think, I believe, the best. Quick recall of opening moves.", science_tag: "retrieval" },
      { name: "Opinion or Fact", minutes: 8, body: "Sort eight statements. The boundary cases are where the learning is.", science_tag: "dual-coding" },
      { name: "Model a Weak One", minutes: 8, body: "An opinion with one reason that repeats the opinion. Students say what is missing.", science_tag: "elaboration" },
      { name: "Two Reasons Minimum", minutes: 12, body: "Students pick a book they liked and fill two reason boxes. Two boxes, both filled, before any drafting.", science_tag: "collaborative" },
      { name: "The Because Check", minutes: 10, body: "Read the opinion, add because, read the reason. Does it add something new? Fix any that fail.", science_tag: "elaboration" },
      { name: "Link and Close", minutes: 12, body: "Add also, another reason, and a closing sentence. Model two closings and let students choose a style.", science_tag: "interleaving" },
      { name: "Read to a Partner", minutes: 5, body: "Partner listens for the opinion, two reasons and the ending. Three things to check.", science_tag: "spaced" },
    ],
    ef_supports: ["Opinion and two-reason organizer", "Linking word bank", "Because check as an anchor chart", "Partner checklist of three items"],
    tech: "Printed organizers",
    tech_purpose: "Two visible boxes make the two-reason requirement concrete",
    ai_prompts: ["Generate grade 2 opinion prompts about familiar books", "Write an opinion paragraph with circular reasoning for critique"],
    assessment: ["Check both reason boxes are filled", "Apply the because check to each reason", "Partner check covers all three elements"],
    why_it_works: ["Two physical boxes make the requirement impossible to skip", "The because check is a self-assessment students can run alone", "Critiquing a weak model is easier than producing a strong one", "A three-item partner checklist is short enough to actually be used"],
  },
  {
    standard_code: "L.2.1",
    title: "Words That Do Not Follow the Rules",
    badge: "Grade 2",
    route_name: "Explicit Instruction",
    route_line: "Notice the pattern → Collect the exceptions → Fix your own writing",
    success_criteria: ["Forms regular plurals and past tense correctly", "Uses common irregular forms", "Finds and fixes errors in their own writing"],
    steps: [
      { name: "Retrieve Nouns and Verbs", minutes: 5, body: "Sort words into things and actions. The categories have to be secure before their forms are.", science_tag: "retrieval" },
      { name: "The Regular Pattern", minutes: 8, body: "Add -s for more than one, -ed for the past. Establish the rule before breaking it.", science_tag: "dual-coding" },
      { name: "Rules That Break", minutes: 10, body: "Mouse becomes mice, run becomes ran. Students supply the wrong regular form first, then hear the real one. The contrast is memorable.", science_tag: "elaboration" },
      { name: "Build the Class Chart", minutes: 12, body: "Collect irregulars onto a chart students will keep adding to all year. Ownership makes it get used.", science_tag: "collaborative" },
      { name: "Mixed Practice", minutes: 12, body: "Sentences needing regular and irregular forms shuffled. Mixing prevents applying one rule blindly.", science_tag: "interleaving" },
      { name: "Edit Real Writing", minutes: 10, body: "Students hunt these forms in their own drafts. Grammar only matters where it actually appears.", science_tag: "elaboration" },
      { name: "Add to the Chart", minutes: 3, body: "Any new irregular found today goes up. The chart grows from their own writing.", science_tag: "spaced" },
    ],
    ef_supports: ["Growing irregular forms chart", "Color coding for regular vs irregular", "Edit own draft rather than worksheet", "Word sorting for nouns and verbs"],
    tech: "Class anchor chart",
    tech_purpose: "A reference students build and therefore consult",
    ai_prompts: ["Generate sentences mixing regular and irregular plurals and past tense", "List the most common grade 2 irregular forms"],
    assessment: ["Check mixed practice for over-regularisation", "Review self-edits on real drafts", "Track chart additions over time"],
    why_it_works: ["Predicting the wrong regular form first makes the exception stick", "A student-built chart gets consulted; a given one does not", "Mixed practice stops blind rule application", "Editing real writing is where conventions actually transfer"],
  },
  {
    standard_code: "RI.3.2",
    title: "The Big Idea and What Holds It Up",
    badge: "Grade 3",
    route_name: "Explicit Instruction",
    route_line: "Topic to idea → Collect the details → Show the support",
    success_criteria: ["States the main idea as a full sentence", "Lists key details from the text", "Explains how each detail supports the idea"],
    steps: [
      { name: "Retrieve Topic Finding", minutes: 5, body: "Three short paragraphs, name the topic of each. Fast — the topic is the starting point, not the destination.", science_tag: "retrieval" },
      { name: "Topic Is Not the Idea", minutes: 10, body: "Topic: penguins. Main idea: penguins have special ways to stay warm. Students upgrade three topics to ideas.", science_tag: "elaboration" },
      { name: "Table Legs Model", minutes: 10, body: "Main idea is the tabletop, details are the legs. Draw it. The image gives the abstract relationship a shape.", science_tag: "dual-coding" },
      { name: "Collect the Legs", minutes: 12, body: "Read a text, list the key details. Not every detail — the ones holding the idea up.", science_tag: "collaborative" },
      { name: "Test Each Detail", minutes: 10, body: "Does this detail hold up the idea, or is it just interesting? Removing weak legs is the selection skill.", science_tag: "elaboration" },
      { name: "Write It Out", minutes: 10, body: "Main idea sentence, three details, one sentence explaining how they support it.", science_tag: "interleaving" },
      { name: "Compare Two Ideas", minutes: 3, body: "Two students share main idea sentences for the same text. Discuss which the details support better.", science_tag: "spaced" },
    ],
    ef_supports: ["Table-and-legs graphic organizer", "Topic-to-idea upgrade frame", "Detail testing question", "Numbered paragraphs"],
    tech: "Printed text and organizers",
    tech_purpose: "The table image makes support structural, not verbal",
    ai_prompts: ["Write a grade 3 informational text with a clear main idea", "Generate topics for students to upgrade into main idea sentences"],
    assessment: ["Check main ideas are sentences, not topics", "Review which details were rejected and why", "Read explanations for genuine linking"],
    why_it_works: ["The table image makes an abstract relationship physical", "Upgrading topics to ideas targets the most common shortfall", "Rejecting merely interesting details teaches selection", "Comparing two candidate ideas shows the answer is a judgement"],
  },
  {
    standard_code: "RF.3.4",
    title: "Smooth Enough to Understand",
    badge: "Grade 3",
    route_name: "Routine and Practice",
    route_line: "Model phrasing → Repeated reading → Read for meaning",
    success_criteria: ["Reads grade-level text accurately", "Reads in phrases rather than word by word", "Self-corrects when meaning breaks down"],
    steps: [
      { name: "Warm Up on Known Text", minutes: 5, body: "Reread yesterday's passage. Familiar text is where expression can develop without decoding competing.", science_tag: "spaced" },
      { name: "Model Two Readings", minutes: 8, body: "Read a passage word by word, then with phrasing. Students say which they understood better. Fluency is for comprehension.", science_tag: "elaboration" },
      { name: "Mark the Phrases", minutes: 10, body: "Slash marks between phrase groups. Students mark a passage, then read it their way.", science_tag: "dual-coding" },
      { name: "Echo and Choral", minutes: 10, body: "You read a line, they echo it. Then read together. Phrasing is copied before it is produced.", science_tag: "collaborative" },
      { name: "Partner Repeated Reading", minutes: 12, body: "Three reads of the same short passage with a partner listening for smoothness. Repetition is the mechanism.", science_tag: "retrieval" },
      { name: "Read for Meaning", minutes: 10, body: "New passage, one read, then a comprehension question. Speed without understanding does not count.", science_tag: "interleaving" },
      { name: "Rate Yourself", minutes: 5, body: "Students rate their own smoothness and note one thing to work on.", science_tag: "spaced" },
    ],
    ef_supports: ["Phrase-marked passages", "Echo reading before independent", "Partner smoothness checklist", "Familiar text for expression work"],
    tech: "Printed passages with wide spacing",
    tech_purpose: "Room to mark phrase boundaries",
    ai_prompts: ["Write grade 3 passages at consistent difficulty for repeated reading", "Generate comprehension questions to follow a fluency read"],
    assessment: ["Listen to partner reads for phrasing", "Comprehension question after every fluency read", "Track accuracy across the three repeated reads"],
    why_it_works: ["Repeated reading of the same text is the mechanism that builds fluency", "Phrase marking makes prosody visible rather than intuitive", "Pairing every read with a question keeps comprehension the goal", "Familiar text lets expression develop without decoding load"],
  },
  {
    standard_code: "RL.4.2",
    title: "What the Story Is Really Saying",
    badge: "Grade 4",
    route_name: "Explicit Instruction",
    route_line: "Topic to message → Gather the evidence → Summarize tightly",
    success_criteria: ["States a theme as a message about life", "Points to details that led there", "Summarizes the story in a set number of sentences"],
    steps: [
      { name: "Retrieve Story Elements", minutes: 5, body: "Character, setting, problem, solution for a known story. The scaffolding theme sits on.", science_tag: "retrieval" },
      { name: "Fable First", minutes: 10, body: "Fables state their moral outright. Read two, name the lesson. Theme with the difficulty removed.", science_tag: "elaboration" },
      { name: "Topic Versus Message", minutes: 10, body: "Friendship is a topic. Real friends tell you hard truths is a message. Students upgrade four topics.", science_tag: "elaboration" },
      { name: "Find the Evidence", minutes: 12, body: "What did the character learn? What changed? Those moments point to the theme.", science_tag: "collaborative" },
      { name: "Test the Theme", minutes: 10, body: "Does the evidence support this theme, or a different one? Revise claims that do not survive.", science_tag: "interleaving" },
      { name: "Summarize in Four", minutes: 10, body: "Four sentences. The limit forces choosing what matters over retelling.", science_tag: "dual-coding" },
      { name: "Share Two Themes", minutes: 3, body: "Two defensible themes for the same story. Discuss why both can work.", science_tag: "spaced" },
    ],
    ef_supports: ["Theme sentence frame", "Fables as a low-difficulty entry", "Four-sentence summary limit", "Evidence collection organizer"],
    tech: "Printed stories and fables",
    tech_purpose: "Short texts so the whole arc is visible",
    ai_prompts: ["Write fables with clear morals for grade 4", "Generate topic words for students to upgrade into theme statements"],
    assessment: ["Check themes are messages, not topics", "Confirm evidence supports the stated theme", "Summaries must hold to the sentence limit"],
    why_it_works: ["Fables give theme practice with the inference difficulty stripped out", "Upgrading topics targets the standard shortfall directly", "The sentence limit is what converts retelling into summarising", "Two valid themes shows interpretation is reasoned, not guessed"],
  },
  {
    standard_code: "RI.6.8",
    title: "Is That Claim Actually Backed Up?",
    badge: "Grade 6",
    route_name: "Analytical Reading",
    route_line: "Map the claims → Hunt the evidence → Judge what holds",
    success_criteria: ["Identifies the author's main and supporting claims", "Matches evidence to each claim", "Names claims that have no support"],
    steps: [
      { name: "Retrieve Fact and Opinion", minutes: 5, body: "Sort five statements. The base distinction before evaluating support.", science_tag: "retrieval" },
      { name: "Claim, Evidence, Reasoning", minutes: 10, body: "Define the three parts and color-code them in a short model argument.", science_tag: "dual-coding" },
      { name: "Color the Text", minutes: 12, body: "Students highlight claims one color, evidence another. Unhighlighted text is worth discussing too.", science_tag: "dual-coding" },
      { name: "Find the Naked Claim", minutes: 12, body: "One claim in the text has no evidence. Students hunt for it. Confident writing is not supported writing.", science_tag: "elaboration" },
      { name: "Agree But Unsupported", minutes: 10, body: "An argument students agree with, poorly supported. Separating agreement from evaluation is the hard part.", science_tag: "interleaving" },
      { name: "Write the Evaluation", minutes: 10, body: "Which claims hold up and which do not, with reasons. Not whether they agree.", science_tag: "elaboration" },
      { name: "Defend a Judgement", minutes: 3, body: "One student names an unsupported claim. Class checks the text for evidence they missed.", science_tag: "spaced" },
    ],
    ef_supports: ["Two-color highlighting system", "Claim/evidence/reasoning anchor chart", "Argument map organizer", "Numbered paragraphs"],
    tech: "Printed articles with numbered paragraphs",
    tech_purpose: "Highlighting needs a markable copy",
    ai_prompts: ["Write a grade 6 argument with one deliberately unsupported claim", "Generate an argument students would agree with but that lacks evidence"],
    assessment: ["Check highlighting distinguishes claim from evidence", "Confirm the unsupported claim was found", "Read evaluations for reasoning rather than agreement"],
    why_it_works: ["Color-coding makes argument structure visible at a glance", "A planted unsupported claim gives the hunt a definite answer", "The agree-but-unsupported case separates evaluation from opinion", "Unhighlighted text reveals filler and rhetoric"],
  },
  {
    standard_code: "RI.7.2",
    title: "Two Ideas, Traced Across a Text",
    badge: "Grade 7",
    route_name: "Analytical Reading",
    route_line: "Section the text → Name the ideas → Trace their development",
    success_criteria: ["Identifies two or more central ideas", "Traces how each develops across the text", "Writes an objective summary"],
    steps: [
      { name: "Retrieve Main Idea", minutes: 5, body: "One paragraph, one idea. Confirm the base skill before scaling to multiple ideas.", science_tag: "retrieval" },
      { name: "Where the Idea Shifts", minutes: 10, body: "Model sectioning by where the focus changes. Students mark their own boundaries and compare.", science_tag: "dual-coding" },
      { name: "Name an Idea Per Section", minutes: 12, body: "One sentence per section. Then group sections that serve the same central idea.", science_tag: "elaboration" },
      { name: "Development Is Change", minutes: 12, body: "What is said about this idea at the start versus the end? If nothing changes, it is repetition, not development.", science_tag: "elaboration" },
      { name: "Track on a Timeline", minutes: 10, body: "Plot each idea's mentions across the text. Two lines, one per idea. Development becomes visible.", science_tag: "dual-coding" },
      { name: "Objective Summary", minutes: 8, body: "Both ideas, no opinion. Students circle any evaluative word and replace it.", science_tag: "interleaving" },
      { name: "Compare Boundaries", minutes: 3, body: "Two students compare where they sectioned the text. Discuss the disagreements.", science_tag: "spaced" },
    ],
    ef_supports: ["Timeline organizer with two tracks", "Section marking in the margin", "Evaluative word list", "Start-versus-end comparison frame"],
    tech: "Printed text with wide margins",
    tech_purpose: "Space to section and annotate",
    ai_prompts: ["Write a grade 7 text developing two distinct central ideas", "Generate evaluative words to exclude from objective summaries"],
    assessment: ["Check both ideas are identified", "Confirm development shows change, not repetition", "Scan summaries for evaluative language"],
    why_it_works: ["Sectioning gives a procedure for an otherwise vague task", "Defining development as change rules out mere repetition", "Two timeline tracks make parallel development visible", "Boundary disagreements are where the analysis gets interesting"],
  },
  {
    standard_code: "SL.8.1",
    title: "Discussion That Changes Minds",
    badge: "Grade 8",
    route_name: "Structured Discussion",
    route_line: "Prepare with evidence → Connect and probe → Qualify your view",
    success_criteria: ["Comes prepared with text evidence", "Poses a question connecting two contributions", "Qualifies or justifies a position when challenged"],
    steps: [
      { name: "Retrieve the Talk Moves", minutes: 5, body: "Recall the moves from memory before the chart goes up. Retrieval, then confirmation.", science_tag: "retrieval" },
      { name: "Prepared Positions", minutes: 10, body: "Students write their position with two pieces of evidence before any talking. Unprepared discussion goes nowhere.", science_tag: "elaboration" },
      { name: "Connecting Questions", minutes: 10, body: "Model a question that links two speakers rather than starting fresh. Give stems. This is the grade 8 upgrade.", science_tag: "dual-coding" },
      { name: "Qualifying Is Strength", minutes: 10, body: "Model changing your own position in response to evidence. Name it as intellectual honesty, not losing.", science_tag: "elaboration" },
      { name: "Seminar", minutes: 15, body: "Full discussion. Teacher outside the circle and silent. Silences belong to the students.", science_tag: "collaborative" },
      { name: "Track the Moves", minutes: 5, body: "Outer circle tallies connecting questions and qualifications. Data, not impressions.", science_tag: "interleaving" },
      { name: "Reflect on a Shift", minutes: 5, body: "Students write about one moment their thinking moved and what caused it.", science_tag: "spaced" },
    ],
    ef_supports: ["Prepared position sheet with evidence", "Connecting question stems", "Inner/outer circle with tally sheets", "Teacher outside the circle"],
    tech: "Printed tally and preparation sheets",
    tech_purpose: "Make discussion moves countable",
    ai_prompts: ["Generate seminar questions with genuine competing positions", "Write connecting question stems for grade 8 discussion"],
    assessment: ["Check preparation sheets before the seminar", "Collect outer circle tallies", "Read reflections for genuine shifts"],
    why_it_works: ["Preparation with evidence is what separates seminar from chat", "Connecting questions are the specific grade 8 escalation", "Crediting qualification removes the incentive to dig in", "Teacher silence is the precondition for student ownership"],
  },
  {
    standard_code: "K.CC.B.4",
    title: "The Last Number Tells How Many",
    badge: "Kindergarten",
    route_name: "Concrete Practice",
    route_line: "Touch and count → Say how many → Prove it stays the same",
    success_criteria: ["Touches one object per number said", "States the total without recounting", "Knows the total does not change when objects move"],
    steps: [
      { name: "Retrieve the Count Sequence", minutes: 5, body: "Count to 20 together. The sequence must be automatic before it can be attached to objects.", science_tag: "retrieval" },
      { name: "One Touch, One Number", minutes: 10, body: "Model counting while touching. Deliberately go too fast so the mismatch is obvious, then fix it.", science_tag: "dual-coding" },
      { name: "Move as You Count", minutes: 10, body: "Slide each object to a new pile as it is counted. The physical separation prevents double-counting.", science_tag: "dual-coding" },
      { name: "How Many?", minutes: 12, body: "After counting, ask how many. Anyone who recounts has not got cardinality yet. Ask again immediately.", science_tag: "elaboration" },
      { name: "Rearrange and Ask Again", minutes: 10, body: "Spread the same objects out. How many now? Conservation is tested, not assumed.", science_tag: "elaboration" },
      { name: "Count Partner's Set", minutes: 8, body: "Partners build a set and count each other's. Two roles, both useful.", science_tag: "collaborative" },
      { name: "Individual Check", minutes: 5, body: "One set each: count it, say how many, then answer again after you spread it out.", science_tag: "spaced" },
    ],
    ef_supports: ["Objects that can be physically moved", "Two-pile counting routine", "Counting mats with a start point", "Small sets before large"],
    tech: "Counters and counting mats",
    tech_purpose: "Moving objects prevents double counting",
    ai_prompts: ["Generate counting set sizes sequenced for kindergarten", "Create counting mats with a marked starting point"],
    assessment: ["Watch for one-to-one correspondence", "Note who recounts when asked how many", "Test conservation by rearranging"],
    why_it_works: ["Moving objects while counting removes the tracking demand", "Asking how many immediately after is the cardinality test", "Rearranging tests conservation rather than assuming it", "Deliberate teacher error makes the mismatch visible"],
  },
  {
    standard_code: "1.G.A.3",
    title: "Fair Shares: Halves and Quarters",
    badge: "Grade 1",
    route_name: "Concrete-Representational-Abstract",
    route_line: "Fold and check → Name the shares → Compare the sizes",
    success_criteria: ["Splits a shape into equal parts", "Names halves and quarters correctly", "Knows a quarter is smaller than a half"],
    steps: [
      { name: "Retrieve Shape Names", minutes: 5, body: "Circle, rectangle, square. The shapes being partitioned need naming first.", science_tag: "retrieval" },
      { name: "Fair or Not Fair", minutes: 10, body: "Show cookies split evenly and unevenly. Who is happy? Fairness is the entry point to equal.", science_tag: "elaboration" },
      { name: "Fold and Check", minutes: 12, body: "Fold paper shapes in half. Cut and stack the parts to check they match. Stacking is the proof.", science_tag: "dual-coding" },
      { name: "Fold Again for Quarters", minutes: 10, body: "Fold the half in half. Four equal parts. Students see quarters made from halves.", science_tag: "dual-coding" },
      { name: "Which Is Bigger", minutes: 10, body: "Compare a half and a quarter of identical shapes. More parts means smaller parts — counterintuitive and worth the time.", science_tag: "elaboration" },
      { name: "Sort Equal and Unequal", minutes: 8, body: "Cards showing partitioned shapes. Students sort. Include near-misses.", science_tag: "interleaving" },
      { name: "Show Me a Half", minutes: 5, body: "Each student folds a new shape into halves and names the parts.", science_tag: "spaced" },
    ],
    ef_supports: ["Paper shapes to fold and cut", "Stacking to verify equality", "Equal/unequal sorting cards", "Identical shapes for comparison"],
    tech: "Paper shapes and scissors",
    tech_purpose: "Folding and stacking proves equality physically",
    ai_prompts: ["Generate partitioned shape cards including unequal near-misses", "Create fair-share story problems for grade 1"],
    assessment: ["Check folds produce genuinely equal parts", "Watch the sort for unequal partitions accepted", "Individual fold-and-name check"],
    why_it_works: ["Stacking the parts is a proof children can perform themselves", "Fairness is an intuition children already hold strongly", "Making quarters from halves shows the relationship", "Near-miss cards test whether equal really registered"],
  },
  {
    standard_code: "2.MD.A.1",
    title: "Picking the Right Tool",
    badge: "Grade 2",
    route_name: "Concrete Practice",
    route_line: "Line up at zero → Read the number → Choose the tool that fits",
    success_criteria: ["Aligns the object with zero", "Reads the measurement accurately", "Chooses a sensible tool for the object"],
    steps: [
      { name: "Retrieve Comparing", minutes: 5, body: "Order three objects by length without measuring. Comparison before measurement.", science_tag: "retrieval" },
      { name: "The Zero Problem", minutes: 10, body: "Measure something starting from the ruler's edge instead of zero. Get it wrong deliberately. Students catch it.", science_tag: "elaboration" },
      { name: "Line Up and Read", minutes: 12, body: "Practice alignment and reading on several objects. Alignment is the skill; reading follows.", science_tag: "dual-coding" },
      { name: "Meet the Tools", minutes: 10, body: "Ruler, yardstick, measuring tape. What is each best for? Handle all three.", science_tag: "dual-coding" },
      { name: "Wrong Tool on Purpose", minutes: 10, body: "Measure the room with a 12-inch ruler. Let it be tedious. The frustration teaches tool selection.", science_tag: "elaboration" },
      { name: "Measurement Hunt", minutes: 12, body: "A list of objects. Students pick a tool, measure, record both. The choice is recorded, not just the number.", science_tag: "collaborative" },
      { name: "Justify a Choice", minutes: 3, body: "One student explains why they picked a particular tool.", science_tag: "spaced" },
    ],
    ef_supports: ["Rulers with a clearly marked zero", "Tool comparison station", "Recording sheet with a tool column", "Objects of varied size"],
    tech: "Rulers, yardsticks and measuring tapes",
    tech_purpose: "Tool selection requires having tools to select between",
    ai_prompts: ["Generate a measurement hunt list spanning tool types", "Create a recording sheet with tool and measurement columns"],
    assessment: ["Watch for zero alignment", "Check recorded tool choices are sensible", "Individual justification of a choice"],
    why_it_works: ["Deliberate teacher error makes the zero rule memorable", "Using the wrong tool is more persuasive than being told", "Recording the tool makes selection an explicit decision", "Handling all three tools grounds the comparison"],
  },
  {
    standard_code: "3.MD.C.7",
    title: "Covering Space: Area and Multiplication",
    badge: "Grade 3",
    route_name: "Concrete-Representational-Abstract",
    route_line: "Tile it → Count the rows → Multiply the sides",
    success_criteria: ["Tiles a rectangle with no gaps or overlaps", "Finds area by counting square units", "Multiplies side lengths and explains why it matches"],
    steps: [
      { name: "Retrieve Arrays", minutes: 5, body: "Rows and columns, find the total. Area is an array with the objects touching.", science_tag: "retrieval" },
      { name: "Cover It Completely", minutes: 10, body: "Tile a rectangle with square tiles. No gaps, no overlaps. Count them. Area is covering.", science_tag: "dual-coding" },
      { name: "Area or Perimeter", minutes: 10, body: "Do both on one shape. Label what each measures and its units. The confusion is predictable, so address it directly.", science_tag: "interleaving" },
      { name: "See the Rows", minutes: 12, body: "Four rows of six tiles. Students spot the multiplication hiding in the tiling.", science_tag: "elaboration" },
      { name: "Multiply Instead", minutes: 10, body: "Same rectangles, multiply the sides. Check against the tile count every time until trust is earned.", science_tag: "elaboration" },
      { name: "Irregular Shapes", minutes: 10, body: "L-shapes split into two rectangles. Decomposition extends the idea.", science_tag: "interleaving" },
      { name: "Explain the Shortcut", minutes: 3, body: "One student explains why multiplying the sides gives the same answer as counting.", science_tag: "spaced" },
    ],
    ef_supports: ["Square tiles", "Grid paper", "Area and perimeter labelled side by side", "L-shape decomposition examples"],
    tech: "Square tiles and grid paper",
    tech_purpose: "Tiling makes area a covering, not a formula",
    ai_prompts: ["Generate rectangles for tiling with clean dimensions", "Create L-shaped composite area problems"],
    assessment: ["Check tiling has no gaps or overlaps", "Confirm the multiply answer matches the count", "Individual explanation of the shortcut"],
    why_it_works: ["Tiling makes area concretely a covering", "Doing area and perimeter together addresses the confusion head on", "Checking multiplication against tiling earns trust in the formula", "Decomposition extends the idea without new machinery"],
  },
  {
    standard_code: "4.G.A.1",
    title: "The Language of Lines and Angles",
    badge: "Grade 4",
    route_name: "Explicit Instruction",
    route_line: "Draw each one → Compare to a right angle → Find them in shapes",
    success_criteria: ["Draws points, lines, segments and rays correctly", "Classifies angles as right, acute or obtuse", "Identifies these features inside two-dimensional figures"],
    steps: [
      { name: "Retrieve Shape Names", minutes: 5, body: "Name polygons quickly. The figures the vocabulary will be found in.", science_tag: "retrieval" },
      { name: "Line, Segment, Ray", minutes: 10, body: "Draw all three side by side with arrows marked. The arrows carry the meaning.", science_tag: "dual-coding" },
      { name: "The Right Angle Reference", minutes: 10, body: "Use a paper corner as a right-angle checker. Everything is classified against it.", science_tag: "dual-coding" },
      { name: "Bigger or Smaller", minutes: 12, body: "Compare angles to the paper corner. Acute or obtuse. The corner makes it a physical comparison, not a judgement.", science_tag: "elaboration" },
      { name: "Arm Length Trap", minutes: 10, body: "The same angle drawn with long and short arms. Students often say the long one is bigger. Confront it directly.", science_tag: "elaboration" },
      { name: "Find Them in Figures", minutes: 10, body: "Mark parallel sides, perpendicular sides and angle types on polygons. Vocabulary applied in context.", science_tag: "interleaving" },
      { name: "Draw to Order", minutes: 3, body: "Draw an obtuse angle, a ray, two parallel lines. Quick individual check.", science_tag: "spaced" },
    ],
    ef_supports: ["Paper corner as a right-angle checker", "Side-by-side line type reference", "Same-angle different-arms comparison", "Polygons to annotate"],
    tech: "Rulers and paper corners",
    tech_purpose: "A physical right angle to compare against",
    ai_prompts: ["Generate angles for classification including near-right cases", "Create polygons for marking parallel and perpendicular sides"],
    assessment: ["Check line, segment and ray are drawn distinctly", "Watch for arm-length reasoning about angle size", "Draw-to-order check"],
    why_it_works: ["The paper corner turns classification into physical comparison", "The arm-length misconception is near universal and needs confronting", "Side-by-side drawing makes line types distinguishable", "Annotating real polygons applies vocabulary in context"],
  },
  {
    standard_code: "5.MD.C.5",
    title: "Filling the Box: Volume",
    badge: "Grade 5",
    route_name: "Concrete-Representational-Abstract",
    route_line: "Build with cubes → Count the layers → Multiply three dimensions",
    success_criteria: ["Finds volume by counting unit cubes", "Sees volume as repeated layers of area", "Applies and explains the volume formula"],
    steps: [
      { name: "Retrieve Area", minutes: 5, body: "Area of rectangles. Volume is area with a third dimension, so start there.", science_tag: "retrieval" },
      { name: "Build and Count", minutes: 12, body: "Build a prism from unit cubes and count them. Slow and concrete. Volume is filling.", science_tag: "dual-coding" },
      { name: "See the Layers", minutes: 12, body: "One layer is the base area. How many layers? The formula lives here, not in the symbols.", science_tag: "elaboration" },
      { name: "Area Times Height", minutes: 10, body: "Base area times number of layers. Check against the cube count each time.", science_tag: "elaboration" },
      { name: "Volume or Surface Area", minutes: 10, body: "Same box, both measures. Units tell them apart — cubic versus square. The unit is the tell.", science_tag: "interleaving" },
      { name: "Real Problems", minutes: 12, body: "Storage boxes, aquariums, shipping. Students sketch and label before computing.", science_tag: "collaborative" },
      { name: "Explain the Formula", minutes: 3, body: "One student explains why length times width times height gives volume.", science_tag: "spaced" },
    ],
    ef_supports: ["Unit cubes for building", "Layer diagrams", "Unit labels required on every answer", "Sketch-before-compute routine"],
    tech: "Unit cubes",
    tech_purpose: "Volume as physically filling a space",
    ai_prompts: ["Generate real-world volume problems with clean dimensions", "Create layer diagrams for rectangular prisms"],
    assessment: ["Check builds match the stated dimensions", "Confirm units are cubic", "Individual explanation of the formula"],
    why_it_works: ["Building with cubes makes volume a filling, not a formula", "The layer view is where the formula becomes reasoning", "Units are the reliable discriminator between volume and surface area", "Sketching first catches misread dimensions"],
  },
  {
    standard_code: "6.EE.A.2",
    title: "Letters That Stand for Numbers",
    badge: "Grade 6",
    route_name: "Explicit Instruction",
    route_line: "Read expressions → Translate words → Evaluate at a value",
    success_criteria: ["Translates a phrase into an expression", "Reads an expression back in words", "Evaluates correctly using order of operations"],
    steps: [
      { name: "Retrieve Order of Operations", minutes: 5, body: "Evaluate four numeric expressions. Substitution will lean on this immediately.", science_tag: "retrieval" },
      { name: "What a Variable Does", minutes: 8, body: "A letter holds a place for a number that can change. Contrast with a fixed number.", science_tag: "dual-coding" },
      { name: "Translate Both Ways", minutes: 12, body: "Words to expression and expression to words. Reading back catches errors writing alone hides.", science_tag: "interleaving" },
      { name: "The Less Than Trap", minutes: 10, body: "Five less than x is x - 5, not 5 - x. Rewrite the phrase before translating. This error is near universal.", science_tag: "elaboration" },
      { name: "Substitute in Brackets", minutes: 12, body: "Always substitute inside brackets. It costs nothing and prevents order of operations errors with negatives.", science_tag: "elaboration" },
      { name: "Mixed Practice", minutes: 10, body: "Write, read and evaluate shuffled. Mixing forces reading the task.", science_tag: "interleaving" },
      { name: "Read One Back", minutes: 3, body: "One student reads an expression aloud in words and evaluates it.", science_tag: "spaced" },
    ],
    ef_supports: ["Translation phrase bank", "Rewrite-before-translate routine", "Substitute-in-brackets rule", "Two-way translation cards"],
    tech: "Printed translation cards",
    tech_purpose: "Two-way practice needs prompts in both directions",
    ai_prompts: ["Generate phrases including subtraction order traps", "Create expressions for students to read back in words"],
    assessment: ["Check subtraction order in translations", "Confirm substitution uses brackets", "Individual read-back and evaluation"],
    why_it_works: ["Reading expressions back catches misunderstandings writing hides", "The less-than trap is predictable so teach the rewrite", "Bracket substitution eliminates a whole error class cheaply", "Mixed task types prevent mechanical repetition"],
  },
  {
    standard_code: "7.G.B.6",
    title: "Which Measure Does the Question Want?",
    badge: "Grade 7",
    route_name: "Strategy Instruction",
    route_line: "Read for the measure → Decompose the figure → Compute and check units",
    success_criteria: ["Identifies whether a problem needs area, surface area or volume", "Decomposes composite figures before computing", "Reports the answer with correct units"],
    steps: [
      { name: "Retrieve Basic Formulas", minutes: 5, body: "Area of triangle, rectangle, volume of a prism. The building blocks.", science_tag: "retrieval" },
      { name: "Units Tell You Which", minutes: 10, body: "Square units means area, cubic means volume. Read the question for what it wants before computing anything.", science_tag: "dual-coding" },
      { name: "Sort by Measure", minutes: 12, body: "Problems sorted into area, surface area and volume before any calculation. Sorting is the skill being taught.", science_tag: "interleaving" },
      { name: "Decompose Composites", minutes: 12, body: "Draw the dividing line first, always. Then compute each piece and combine.", science_tag: "dual-coding" },
      { name: "Nets for Surface Area", minutes: 10, body: "Unfold a prism into its net. Every face has to be counted, including the hidden ones.", science_tag: "elaboration" },
      { name: "Mixed Problems", minutes: 10, body: "All three measures shuffled. Students name the measure before computing.", science_tag: "interleaving" },
      { name: "Check the Units", minutes: 3, body: "Every answer gets a unit check. Wrong units usually means the wrong measure.", science_tag: "spaced" },
    ],
    ef_supports: ["Measure sorting mats", "Draw-the-dividing-line routine", "Physical nets to unfold", "Unit check as a final step"],
    tech: "Printed nets and composite figure diagrams",
    tech_purpose: "Unfolding a net makes every face countable",
    ai_prompts: ["Generate mixed area, surface area and volume problems", "Create composite figures requiring decomposition"],
    assessment: ["Check the measure is named before computing", "Confirm composite figures are divided first", "Unit check on every answer"],
    why_it_works: ["Naming the measure first prevents computing the wrong thing", "Units are a reliable self-check students can always run", "Physical nets make hidden faces visible", "Sorting without computing isolates the identification skill"],
  },
  {
    standard_code: "7.SP.C.5",
    title: "From Impossible to Certain",
    badge: "Grade 7",
    route_name: "Explicit Instruction",
    route_line: "Order by likelihood → Attach numbers → Interpret the value",
    success_criteria: ["Places events on a 0 to 1 scale", "Expresses probability as a fraction or decimal", "Explains what a given probability means"],
    steps: [
      { name: "Retrieve Fraction and Decimal Links", minutes: 5, body: "Convert between fractions, decimals and percents. Probability lives in all three.", science_tag: "retrieval" },
      { name: "Order the Events", minutes: 10, body: "Everyday events ordered from impossible to certain, no numbers yet. Intuition first.", science_tag: "elaboration" },
      { name: "Anchor the Scale", minutes: 10, body: "Impossible is 0, certain is 1, even chance is 0.5. Three anchors to place everything else against.", science_tag: "dual-coding" },
      { name: "Place with Numbers", minutes: 12, body: "Students assign probabilities to the ordered events and place them on the line. Order constrains the numbers.", science_tag: "dual-coding" },
      { name: "Compute Simple Probabilities", minutes: 12, body: "Dice, spinners, cards. Favourable over total. Check each answer lands between 0 and 1.", science_tag: "elaboration" },
      { name: "Unlikely Is Not Impossible", minutes: 8, body: "A probability of 0.02 is not zero. This distinction matters and gets flattened.", science_tag: "interleaving" },
      { name: "Interpret a Value", minutes: 3, body: "What does a probability of 0.8 mean in plain words?", science_tag: "spaced" },
    ],
    ef_supports: ["0 to 1 probability line on the wall", "Three anchor points marked", "Event cards to order physically", "Range check on every answer"],
    tech: "Dice, spinners and a wall probability line",
    tech_purpose: "A shared scale everything gets placed on",
    ai_prompts: ["Generate everyday events spanning the likelihood scale", "Create simple probability problems with dice and spinners"],
    assessment: ["Check every answer falls between 0 and 1", "Confirm ordering matches assigned numbers", "Individual interpretation of a probability value"],
    why_it_works: ["Ordering before numbering builds on intuition students already have", "Three anchors give reference points for estimation", "The range check catches impossible answers immediately", "Separating unlikely from impossible prevents a common flattening"],
  },
  {
    standard_code: "8.F.A.1",
    title: "One Input, One Output",
    badge: "Grade 8",
    route_name: "Explicit Instruction",
    route_line: "State the rule → Test each representation → Justify the verdict",
    success_criteria: ["States the one-output rule", "Tests tables, pairs and graphs for function status", "Explains the vertical line test in terms of the rule"],
    steps: [
      { name: "Retrieve Ordered Pairs", minutes: 5, body: "Plot and read coordinates. Functions are built from these.", science_tag: "retrieval" },
      { name: "The Vending Machine", minutes: 10, body: "Press B4, get one thing. If it gave a different snack each time it would be broken. That is the function rule.", science_tag: "elaboration" },
      { name: "Test Tables", minutes: 12, body: "Look for a repeated input with different outputs. Only that breaks it. Students check several tables.", science_tag: "interleaving" },
      { name: "Repeated Outputs Are Fine", minutes: 10, body: "Two inputs sharing an output is allowed. Students often think it is not. Show a valid example.", science_tag: "elaboration" },
      { name: "The Vertical Line Test", minutes: 12, body: "Derive it: a vertical line is one input, two crossings means two outputs. The test explains itself.", science_tag: "dual-coding" },
      { name: "Mixed Representations", minutes: 8, body: "Tables, graphs and pair sets shuffled. Students decide and justify each.", science_tag: "interleaving" },
      { name: "Justify a Verdict", minutes: 3, body: "One student explains why a graph fails the test in terms of inputs and outputs.", science_tag: "spaced" },
    ],
    ef_supports: ["Vending machine analogy anchor", "Repeated input highlighting", "Vertical line strip to slide across graphs", "Mixed representation card set"],
    tech: "Graph cards and a transparent vertical strip",
    tech_purpose: "Sliding a physical line makes the test tangible",
    ai_prompts: ["Generate tables and graphs that are and are not functions", "Create examples with repeated outputs but valid function status"],
    assessment: ["Check students look for repeated inputs, not outputs", "Confirm justification references the one-output rule", "Individual verdict with reasoning"],
    why_it_works: ["The vending machine gives an intuitive anchor for a formal rule", "The repeated-output misconception needs explicit contradiction", "Deriving the vertical line test stops it being a magic trick", "Mixed representations prove the rule transfers across forms"],
  },
];

await seedStandardsBatch({
  label: "Batch 3",
  standardsData,
  unpacksData,
  blueprintsData,
});
