// @ts-nocheck
/**
 * Batch 15: grade 4 reading — literature, informational and foundational.
 *
 * From the "Unpacking standards 4th" deck. Grade 4 is where the deck starts
 * asking students to judge rather than locate: whether the evidence is strong
 * enough, what a firsthand account cannot see, what a film version loses. The
 * misconceptions follow — assertion accepted as evidence, firsthand assumed
 * accurate, differences between book and film listed without effect.
 *
 * American spellings throughout.
 *
 *   bun run scripts/seed-standards-batch-15.ts
 */
import { seedStandardsBatch } from "./lib/seed-standards-batch";

const standardsData = [
  {
    code: "RL.4.4",
    name: "Words that point at a myth",
    plain_reading:
      "Determine the meaning of words and phrases as they are used in a text, including those that allude to significant characters found in mythology.",
    learning_target: "I can notice a reference to a story I might not know and find out what it means.",
    skills: ["Allusion", "Figurative Meaning", "Context"],
    science_tags: ["elaboration", "interleaving"],
    match_keys: ["allusion", "mythology", "figurative meaning", "context", "fourth grade vocabulary"],
  },
  {
    code: "RL.4.5",
    name: "Poems, plays and prose are built differently",
    plain_reading:
      "Explain major differences between poems, drama, and prose, and refer to the structural elements of each when writing or speaking about a text.",
    learning_target: "I can use the right structural words for each form.",
    skills: ["Genre Structure", "Structural Elements", "Genre Vocabulary"],
    science_tags: ["dual-coding", "retrieval"],
    match_keys: ["poems drama prose", "verse rhythm meter", "cast of characters", "stage directions", "structural elements"],
  },
  {
    code: "RL.4.6",
    name: "What the narrator can and cannot know",
    plain_reading:
      "Compare and contrast the point of view from which different stories are narrated, including the difference between first- and third-person narrations.",
    learning_target: "I can explain what the choice of narrator does to what I get to know.",
    skills: ["First and Third Person", "Narrative Effect", "Comparing Point of View"],
    science_tags: ["elaboration", "metacognition"],
    match_keys: ["first person third person", "point of view", "narration", "perspective", "compare and contrast"],
  },
  {
    code: "RL.4.7",
    name: "The book against the film",
    plain_reading:
      "Make connections between the text of a story or drama and a visual or oral presentation of the text.",
    learning_target: "I can say what a film version gained and what it lost, and why it matters.",
    skills: ["Text and Presentation", "Comparing Versions", "Analyzing Choices"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["visual or oral presentation", "connections between text and film", "version", "reflect descriptions"],
  },
  {
    code: "RL.4.9",
    name: "The same theme in two traditions",
    plain_reading:
      "Compare and contrast the treatment of similar themes and topics and patterns of events in stories, myths, and traditional literature from different cultures.",
    learning_target: "I can compare the underlying pattern rather than the surface details.",
    skills: ["Theme Across Cultures", "Patterns of Events", "Traditional Literature"],
    science_tags: ["dual-coding", "interleaving"],
    match_keys: ["similar themes and topics", "patterns of events", "myths traditional literature", "different cultures", "motif"],
  },
  {
    code: "RL.4.10",
    name: "Finishing is not understanding",
    plain_reading:
      "By the end of the year, read and comprehend literature in the grades 4-5 text complexity band proficiently, with scaffolding as needed at the high end.",
    learning_target: "I can check I understood rather than just reaching the last page.",
    skills: ["Comprehension", "Stamina", "Self-Checking"],
    science_tags: ["metacognition", "spaced"],
    match_keys: ["grades 4-5 complexity band", "proficiently", "scaffolding", "stamina", "retelling check"],
  },
  {
    code: "RI.4.1",
    name: "The sentence, not the paragraph",
    plain_reading:
      "Refer to details and examples in a text when explaining what the text says explicitly and when drawing inferences from the text.",
    learning_target: "I can point to the exact sentence that supports my point.",
    skills: ["Citing Evidence", "Inference", "Precision"],
    science_tags: ["metacognition", "elaboration"],
    match_keys: ["refer to details and examples", "explicitly", "inferences", "cite evidence", "fourth grade"],
  },
  {
    code: "RI.4.4",
    name: "Current, solution, contract",
    plain_reading:
      "Determine the meaning of general academic and domain-specific words or phrases in a text relevant to a grade 4 topic or subject area.",
    learning_target: "I can spot when a word I know is being used technically.",
    skills: ["Domain Vocabulary", "Academic Language", "Reference Materials"],
    science_tags: ["elaboration", "interleaving"],
    match_keys: ["general academic and domain-specific", "technical term", "context and text features", "reference materials"],
  },
  {
    code: "RI.4.6",
    name: "Firsthand is not automatically right",
    plain_reading:
      "Compare and contrast a firsthand and secondhand account of the same event or topic; describe the differences in focus and information provided.",
    learning_target: "I can say what each kind of account is good at and what it misses.",
    skills: ["Firsthand and Secondhand", "Focus", "Source Limits"],
    science_tags: ["elaboration", "metacognition"],
    match_keys: ["firsthand secondhand account", "differences in focus", "information provided", "perspective", "same event"],
  },
  {
    code: "RI.4.7",
    name: "What the graph does for the argument",
    plain_reading:
      "Interpret information presented visually, orally, or quantitatively and explain how the information contributes to an understanding of the text.",
    learning_target: "I can say what a chart means for the point the author is making.",
    skills: ["Interpreting Data", "Charts and Timelines", "Contribution to Meaning"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["visually orally quantitatively", "chart graph timeline diagram", "contributes to understanding", "interpret"],
  },
  {
    code: "RI.4.8",
    name: "Saying it is not proving it",
    plain_reading:
      "Explain how an author uses reasons and evidence to support particular points in a text.",
    learning_target: "I can tell the difference between a claim and the evidence for it.",
    skills: ["Claim and Evidence", "Evaluating Support", "Author's Reasoning"],
    science_tags: ["elaboration", "metacognition"],
    match_keys: ["reasons and evidence", "support particular points", "claim", "evaluate evidence", "assertion"],
  },
  {
    code: "RI.4.9",
    name: "Weave the sources, do not stack them",
    plain_reading:
      "Integrate information from two texts on the same topic in order to write or speak about the subject knowledgeably.",
    learning_target: "I can write one account from two sources rather than two summaries.",
    skills: ["Integration", "Synthesis", "Handling Conflict"],
    science_tags: ["dual-coding", "interleaving"],
    match_keys: ["integrate information from two texts", "knowledgeably", "synthesize", "sources conflict", "same topic"],
  },
  {
    code: "RI.4.10",
    name: "Chunk it rather than skim it",
    plain_reading:
      "By the end of year, read and comprehend informational texts in the grades 4-5 text complexity band proficiently, with scaffolding as needed at the high end.",
    learning_target: "I can break a dense text into sections and summarize as I go.",
    skills: ["Nonfiction Comprehension", "Chunking", "Sustained Attention"],
    science_tags: ["metacognition", "spaced"],
    match_keys: ["informational text", "grades 4-5 band", "dense paragraphs", "chunking", "summarize each section"],
  },
  {
    code: "RF.4.3.A",
    name: "Decode it and know what it means",
    plain_reading:
      "Use combined knowledge of all letter-sound correspondences, syllabication patterns, and morphology to read accurately unfamiliar multisyllabic words.",
    learning_target: "I can read a long word and then say what it means.",
    skills: ["Syllabication", "Morphology", "Meaning from Parts"],
    science_tags: ["elaboration", "interleaving"],
    match_keys: ["letter-sound correspondences", "syllabication patterns", "morphology", "multisyllabic words", "in and out of context"],
  },
  {
    code: "RF.4.4.A",
    name: "Purpose changes the reading",
    plain_reading: "Read grade-level text with purpose and understanding.",
    learning_target: "I can read the same page differently depending on why.",
    skills: ["Purpose", "Adjusting Approach", "Monitoring"],
    science_tags: ["metacognition", "interleaving"],
    match_keys: ["purpose and understanding", "adjust reading approach", "monitor comprehension", "fluency"],
  },
  {
    code: "RF.4.4.B",
    name: "Phrases, not words one at a time",
    plain_reading:
      "Read grade-level prose and poetry orally with accuracy, appropriate rate, and expression on successive readings.",
    learning_target: "I can group words into phrases so long sentences hold together.",
    skills: ["Phrasing", "Prosody", "Successive Readings"],
    science_tags: ["spaced", "collaborative"],
    match_keys: ["prose and poetry orally", "accuracy rate expression", "phrasing", "word-by-word reading", "prosody"],
  },
  {
    code: "RF.4.4.C",
    name: "Did the whole passage make sense",
    plain_reading:
      "Use context to confirm or self-correct word recognition and understanding, rereading as necessary.",
    learning_target: "I can check the paragraph made sense, not just the words in it.",
    skills: ["Self-Correction", "Passage-Level Monitoring", "Rereading"],
    science_tags: ["metacognition", "collaborative"],
    match_keys: ["use context to confirm", "self-correct", "reread as necessary", "monitor comprehension", "passage level"],
  },
];

const unpacksData = [
  {
    standard_code: "RL.4.4",
    verbs: [
      { word: "Determine", gloss: "work out the meaning here" },
      { word: "Interpret", gloss: "unpack what the allusion points at" },
    ],
    concepts: ["Allusion", "Mythological reference", "Figurative meaning"],
    vocabulary: [
      { term: "allusion", definition: "a reference to a story or person outside this text" },
      { term: "mythology", definition: "the old stories a culture tells" },
      { term: "figurative", definition: "not meant literally" },
      { term: "connotation", definition: "the feeling a word carries beyond its meaning" },
    ],
    prior_skills: ["Distinguish literal from nonliteral", "Use context clues", "Know some myths"],
    prior_standards: [{ code: "RL.3.4", text: "Determine the meaning of words and phrases, distinguishing literal from nonliteral" }],
    future_standards: [{ code: "RL.5.4", text: "Determine the meaning of words and phrases including figurative language" }],
    challenges: [
      { problem: "Allusions are missed entirely because the referenced story is unknown, and read straight past", fix: "Teach the signal, not the story. A capitalized name doing odd work in a sentence is a flag to look up" },
      { problem: "The allusion is identified but its meaning is not applied", fix: "Say what the reference brings — an Achilles heel means one fatal weakness, so what is theirs?" },
    ],
    mastery_statement: "Student can recognize an allusion and use it to determine what the phrase means.",
    ladder: [
      { name: "I can use context", descriptor: "Determines word meaning" },
      { name: "I can spot a reference", descriptor: "Notices an allusion" },
      { name: "I can find out what it means", descriptor: "Looks up the source" },
      { name: "I can apply it here", descriptor: "Uses the allusion to read the sentence" },
    ],
  },
  {
    standard_code: "RL.4.5",
    verbs: [
      { word: "Explain", gloss: "the differences between forms" },
      { word: "Refer", gloss: "to the right structural elements" },
    ],
    concepts: ["Genre structure", "Structural elements", "Genre vocabulary"],
    vocabulary: [
      { term: "prose", definition: "ordinary writing in sentences and paragraphs" },
      { term: "drama", definition: "a play, written to be performed" },
      { term: "verse", definition: "a line or group of lines in a poem" },
      { term: "stage directions", definition: "instructions for what happens on stage" },
      { term: "meter", definition: "the rhythm pattern of a poem" },
    ],
    prior_skills: ["Use chapter, scene and stanza", "Read all three forms", "Describe structure"],
    prior_standards: [{ code: "RL.3.5", text: "Refer to parts of stories, dramas and poems using terms such as chapter, scene and stanza" }],
    future_standards: [{ code: "RL.5.5", text: "Explain how a series of chapters, scenes or stanzas fits together" }],
    challenges: [
      { problem: "Story vocabulary is applied to poetry — stanzas described as paragraphs", fix: "The three forms open together, with their own vocabulary lists. The word belongs to the form" },
      { problem: "Differences are listed without explaining what they do", fix: "Ask what the form makes possible. Stage directions can show what a narrator would have to tell you" },
    ],
    mastery_statement: "Student can explain how poems, drama and prose differ and use each form's own terms.",
    ladder: [
      { name: "I can name the forms", descriptor: "Recognizes genre" },
      { name: "I can name their parts", descriptor: "Uses structural vocabulary" },
      { name: "I can use the right words", descriptor: "Matches term to form" },
      { name: "I can explain the difference", descriptor: "Says what each form does" },
    ],
  },
  {
    standard_code: "RL.4.6",
    verbs: [
      { word: "Compare", gloss: "points of view across stories" },
      { word: "Distinguish", gloss: "first from third person" },
      { word: "Analyze", gloss: "the effect on the reader" },
    ],
    concepts: ["First and third person", "What the narrator can know", "Effect of the choice"],
    vocabulary: [
      { term: "first person", definition: "told by a character, using I" },
      { term: "third person", definition: "told from outside, using he, she or they" },
      { term: "narration", definition: "the telling of the story" },
      { term: "perspective", definition: "the position the story is told from" },
    ],
    prior_skills: ["Identify the narrator", "Distinguish own view from the narrator's", "Read both forms"],
    prior_standards: [{ code: "RL.3.6", text: "Distinguish their own point of view from that of the narrator or characters" }],
    future_standards: [{ code: "RL.5.6", text: "Describe how a narrator's point of view influences how events are described" }],
    challenges: [
      { problem: "The person of the narration is identified but its effect on what the reader knows is not explained", fix: "Rewrite one paragraph in the other person. What can you no longer tell the reader?" },
      { problem: "First person is assumed to be more truthful", fix: "A narrator who is wrong about something. Closeness is not accuracy" },
    ],
    mastery_statement: "Student can compare narrative points of view and explain what each lets the reader know.",
    ladder: [
      { name: "I can find the narrator", descriptor: "Identifies the voice" },
      { name: "I can say first or third", descriptor: "Distinguishes person" },
      { name: "I can compare two stories", descriptor: "Contrasts points of view" },
      { name: "I can say what it does", descriptor: "Analyzes the effect" },
    ],
  },
  {
    standard_code: "RL.4.7",
    verbs: [
      { word: "Connect", gloss: "the text to the presentation" },
      { word: "Identify", gloss: "where each reflects the other" },
      { word: "Analyze", gloss: "what is gained and lost" },
    ],
    concepts: ["Adaptation", "Reflecting descriptions", "Effect of a choice"],
    vocabulary: [
      { term: "visual presentation", definition: "a film or staged version" },
      { term: "oral presentation", definition: "a spoken or recorded version" },
      { term: "reflect", definition: "show what the text described" },
      { term: "version", definition: "one telling of the same story" },
    ],
    prior_skills: ["Explain what illustrations add", "Compare versions", "Describe setting and character"],
    prior_standards: [{ code: "RL.3.7", text: "Explain how aspects of a text's illustrations contribute to what the words convey" }],
    future_standards: [{ code: "RL.5.7", text: "Analyze how visual and multimedia elements contribute to a text" }],
    challenges: [
      { problem: "Differences between book and film are listed with no analysis of what the choices do", fix: "Every difference gets a so-what. A cut character changes something, and naming what is the work" },
      { problem: "The film is judged as better or worse rather than analyzed", fix: "Ask what each version can do that the other cannot" },
    ],
    mastery_statement: "Student can connect a text to a presentation of it and analyze what the choices change.",
    ladder: [
      { name: "I can watch and read", descriptor: "Knows both versions" },
      { name: "I can spot a difference", descriptor: "Identifies changes" },
      { name: "I can find where they match", descriptor: "Connects specific descriptions" },
      { name: "I can say what it changes", descriptor: "Analyzes the effect" },
    ],
  },
  {
    standard_code: "RL.4.9",
    verbs: [
      { word: "Compare", gloss: "the treatment of a theme" },
      { word: "Contrast", gloss: "patterns of events" },
    ],
    concepts: ["Theme across cultures", "Pattern of events", "Surface versus structure"],
    vocabulary: [
      { term: "theme", definition: "what a story says about life" },
      { term: "motif", definition: "an image or idea that recurs" },
      { term: "traditional literature", definition: "stories handed down within a culture" },
      { term: "pattern", definition: "a shape of events that repeats" },
    ],
    prior_skills: ["Compare stories by one author", "Identify theme", "Read myths and folktales"],
    prior_standards: [{ code: "RL.3.9", text: "Compare and contrast themes, settings and plots of stories by the same author" }],
    future_standards: [{ code: "RL.5.9", text: "Compare and contrast stories in the same genre on their approaches to similar themes" }],
    challenges: [
      { problem: "Plots are compared on surface details rather than on the underlying theme or pattern", fix: "Strip both to a five-step skeleton before comparing. The surface differs; the skeleton often does not" },
      { problem: "Cultural difference is treated as merely decorative", fix: "Ask what the difference tells you about what that culture valued" },
    ],
    mastery_statement: "Student can compare how two cultures treat a shared theme or pattern of events.",
    ladder: [
      { name: "I can retell both", descriptor: "Knows the stories" },
      { name: "I can find the theme", descriptor: "Identifies the claim about life" },
      { name: "I can strip to the pattern", descriptor: "Sees the underlying structure" },
      { name: "I can compare the treatment", descriptor: "Contrasts across cultures" },
    ],
  },
  {
    standard_code: "RL.4.10",
    verbs: [
      { word: "Read", gloss: "in the grades 4-5 band" },
      { word: "Comprehend", gloss: "not merely finish" },
    ],
    concepts: ["Text complexity", "Comprehension versus completion", "Stamina"],
    vocabulary: [
      { term: "complexity band", definition: "the range of difficulty for a grade" },
      { term: "proficiently", definition: "well enough to be reliable" },
      { term: "scaffolding", definition: "support that is gradually removed" },
      { term: "stamina", definition: "the ability to keep reading" },
    ],
    prior_skills: ["Read at the top of the 2-3 band", "Use fix-up strategies", "Read independently"],
    prior_standards: [{ code: "RL.3.10", text: "Read and comprehend literature at the high end of the grades 2-3 band" }],
    future_standards: [{ code: "RL.5.10", text: "Read and comprehend literature at the high end of the grades 4-5 band" }],
    challenges: [
      { problem: "Finishing a book is confused with comprehending it", fix: "Periodic retelling checks. Pages turned is not evidence, and a retell at chapter five catches the gap early" },
      { problem: "Difficulty is met by reading faster", fix: "Slowing down is a strategy, and it needs saying" },
    ],
    mastery_statement: "Student can read grades 4-5 literature and demonstrate they understood it, not only finished it.",
    ladder: [
      { name: "I can finish a book", descriptor: "Sustains reading" },
      { name: "I can retell it", descriptor: "Demonstrates comprehension" },
      { name: "I can handle the high end", descriptor: "Reads complex text with support" },
      { name: "I can check myself", descriptor: "Monitors comprehension" },
    ],
  },
  {
    standard_code: "RI.4.1",
    verbs: [
      { word: "Refer", gloss: "to specific details and examples" },
      { word: "Explain", gloss: "what the text says explicitly" },
      { word: "Infer", gloss: "what it supports without stating" },
    ],
    concepts: ["Precision of citation", "Explicit and inferred", "Examples"],
    vocabulary: [
      { term: "explicit", definition: "stated outright" },
      { term: "inference", definition: "a conclusion the text supports" },
      { term: "evidence", definition: "the specific words that prove it" },
      { term: "cite", definition: "name exactly where it came from" },
    ],
    prior_skills: ["Refer explicitly to the text", "Separate text from prior knowledge", "Quote accurately"],
    prior_standards: [{ code: "RI.3.1", text: "Ask and answer questions referring explicitly to the text as the basis for the answers" }],
    future_standards: [{ code: "RI.5.1", text: "Quote accurately from a text when explaining and when drawing inferences" }],
    challenges: [
      { problem: "A whole paragraph is cited rather than the sentence that actually supports the point", fix: "One sentence maximum. If the point needs a paragraph, the point is not sharp enough" },
      { problem: "Inference is offered as if stated", fix: "Two columns — what it says, what I conclude" },
    ],
    mastery_statement: "Student can cite the specific sentence supporting a point and label inference as inference.",
    ladder: [
      { name: "I can answer", descriptor: "Responds accurately" },
      { name: "I can find support", descriptor: "Locates in the text" },
      { name: "I can narrow to one sentence", descriptor: "Cites precisely" },
      { name: "I can label my inference", descriptor: "Distinguishes explicit from inferred" },
    ],
  },
  {
    standard_code: "RI.4.4",
    verbs: [
      { word: "Determine", gloss: "the technical meaning" },
      { word: "Use", gloss: "context and text features" },
      { word: "Consult", gloss: "reference materials" },
    ],
    concepts: ["Technical meaning", "Words with two lives", "References"],
    vocabulary: [
      { term: "domain-specific", definition: "belonging to one subject" },
      { term: "academic vocabulary", definition: "words used across subjects" },
      { term: "technical term", definition: "a word with a precise subject meaning" },
      { term: "context", definition: "the surrounding words" },
    ],
    prior_skills: ["Determine domain vocabulary", "Use a glossary", "Substitute to check"],
    prior_standards: [{ code: "RI.3.4", text: "Determine the meaning of general academic and domain-specific words in a grade 3 topic" }],
    future_standards: [{ code: "RI.5.4", text: "Determine the meaning of general academic and domain-specific words in a grade 5 topic" }],
    challenges: [
      { problem: "An everyday meaning is applied to a technical term — current, solution, contract", fix: "Collect them. A familiar word in a science text is a warning rather than a relief" },
      { problem: "The first dictionary sense is taken", fix: "Substitute back into the sentence and read it aloud" },
    ],
    mastery_statement: "Student can determine a technical meaning and verify it fits the sentence.",
    ladder: [
      { name: "I can spot the word", descriptor: "Notices the term" },
      { name: "I can use context", descriptor: "Infers from surroundings" },
      { name: "I can use references", descriptor: "Consults appropriately" },
      { name: "I can check it fits", descriptor: "Verifies by substitution" },
    ],
  },
  {
    standard_code: "RI.4.6",
    verbs: [
      { word: "Compare", gloss: "the two accounts" },
      { word: "Describe", gloss: "differences in focus" },
    ],
    concepts: ["Firsthand and secondhand", "Focus", "Limits of each"],
    vocabulary: [
      { term: "firsthand", definition: "from someone who was there" },
      { term: "secondhand", definition: "from someone who found out about it" },
      { term: "account", definition: "one telling of what happened" },
      { term: "focus", definition: "what the account pays attention to" },
    ],
    prior_skills: ["Distinguish author's view from own", "Compare two texts", "Identify perspective"],
    prior_standards: [{ code: "RI.3.6", text: "Distinguish their own point of view from that of the author of a text" }],
    future_standards: [{ code: "RI.5.6", text: "Analyze multiple accounts of the same event, noting similarities and differences in point of view" }],
    challenges: [
      { problem: "A firsthand account is assumed automatically more accurate, without considering its limits", fix: "Someone at the scene sees one corner of it. Being there is a strength and a limit at once" },
      { problem: "Differences in focus are missed because only facts are compared", fix: "Ask what each account bothered to include" },
    ],
    mastery_statement: "Student can compare firsthand and secondhand accounts and describe what each is good for.",
    ladder: [
      { name: "I can tell which is which", descriptor: "Identifies account type" },
      { name: "I can list what each says", descriptor: "Summarizes both" },
      { name: "I can describe the focus", descriptor: "Notices what each attends to" },
      { name: "I can name the limits", descriptor: "Evaluates each source" },
    ],
  },
  {
    standard_code: "RI.4.7",
    verbs: [
      { word: "Interpret", gloss: "what the data shows" },
      { word: "Explain", gloss: "how it contributes to the text" },
    ],
    concepts: ["Quantitative information", "Contribution to the argument", "Charts and timelines"],
    vocabulary: [
      { term: "quantitatively", definition: "in numbers" },
      { term: "chart", definition: "a diagram showing information" },
      { term: "timeline", definition: "a line showing when things happened" },
      { term: "interpret", definition: "say what it means" },
    ],
    prior_skills: ["Read graphs", "Use diagrams as sources", "Combine visual and text"],
    prior_standards: [{ code: "RI.3.7", text: "Use information from illustrations and words to demonstrate understanding" }],
    future_standards: [{ code: "RI.5.7", text: "Draw on information from multiple print or digital sources to answer a question" }],
    challenges: [
      { problem: "The number is read off the graph without interpreting what it means for the argument", fix: "Reading is step one. So what does that number do for the author's point?" },
      { problem: "The visual is treated as separate from the text", fix: "One sentence connecting them, every time" },
    ],
    mastery_statement: "Student can interpret a visual or quantitative display and say what it does for the text.",
    ladder: [
      { name: "I can read the values", descriptor: "Extracts data" },
      { name: "I can say what it shows", descriptor: "Interprets the display" },
      { name: "I can link it to the text", descriptor: "Connects to the content" },
      { name: "I can say what it proves", descriptor: "Explains the contribution" },
    ],
  },
  {
    standard_code: "RI.4.8",
    verbs: [
      { word: "Explain", gloss: "how reasons support points" },
      { word: "Distinguish", gloss: "claim from evidence" },
      { word: "Evaluate", gloss: "whether the support holds" },
    ],
    concepts: ["Claim and support", "Assertion versus evidence", "Strength"],
    vocabulary: [
      { term: "claim", definition: "something the author wants you to accept" },
      { term: "reason", definition: "why they say you should" },
      { term: "evidence", definition: "the facts behind the reason" },
      { term: "evaluate", definition: "judge how good it is" },
    ],
    prior_skills: ["Find points and reasons", "Describe logical connections", "Distinguish fact from opinion"],
    prior_standards: [{ code: "RI.3.8", text: "Describe the logical connection between particular sentences and paragraphs" }],
    future_standards: [{ code: "RI.5.8", text: "Explain how an author uses reasons and evidence, identifying which support which points" }],
    challenges: [
      { problem: "Any statement in print is accepted as proven — assertion treated as evidence", fix: "A confident paragraph with no evidence in it at all. Hunt for the support and fail" },
      { problem: "Evidence is counted rather than weighed", fix: "Three weak reasons do not equal one strong one. Rank them" },
    ],
    mastery_statement: "Student can separate an author's claim from its support and judge whether the support holds.",
    ladder: [
      { name: "I can find the claim", descriptor: "Identifies the point" },
      { name: "I can find the reasons", descriptor: "Locates support" },
      { name: "I can tell them apart", descriptor: "Distinguishes assertion from evidence" },
      { name: "I can judge the strength", descriptor: "Evaluates the support" },
    ],
  },
  {
    standard_code: "RI.4.9",
    verbs: [
      { word: "Integrate", gloss: "weave the sources together" },
      { word: "Write", gloss: "knowledgeably about the subject" },
    ],
    concepts: ["Integration versus summary", "Agreement and conflict", "Synthesis"],
    vocabulary: [
      { term: "integrate", definition: "combine into one account" },
      { term: "source", definition: "one of the texts" },
      { term: "synthesize", definition: "make something new from several parts" },
      { term: "knowledgeably", definition: "as someone who actually knows" },
    ],
    prior_skills: ["Compare two texts", "Take notes from sources", "Identify important points"],
    prior_standards: [{ code: "RI.3.9", text: "Compare and contrast the most important points and key details in two texts" }],
    future_standards: [{ code: "RI.5.9", text: "Integrate information from several texts on the same topic in order to write or speak knowledgeably" }],
    challenges: [
      { problem: "Each source is summarized in turn rather than woven into a single account", fix: "Ban the words the first text and the second text. Write about the topic, not about the reading" },
      { problem: "Conflicts between sources are ignored", fix: "Name the disagreement explicitly rather than picking one" },
    ],
    mastery_statement: "Student can write one integrated account from two sources, naming where they conflict.",
    ladder: [
      { name: "I can read both", descriptor: "Comprehends each" },
      { name: "I can summarize each", descriptor: "Reports separately" },
      { name: "I can combine them", descriptor: "Integrates into one account" },
      { name: "I can handle disagreement", descriptor: "Names conflicts" },
    ],
  },
  {
    standard_code: "RI.4.10",
    verbs: [
      { word: "Read", gloss: "in the grades 4-5 band" },
      { word: "Comprehend", gloss: "dense informational text" },
      { word: "Chunk", gloss: "rather than skim" },
    ],
    concepts: ["Chunking", "Section summaries", "Sustained attention"],
    vocabulary: [
      { term: "complexity band", definition: "the difficulty range for the grade" },
      { term: "proficiently", definition: "reliably well" },
      { term: "scaffolding", definition: "support gradually withdrawn" },
    ],
    prior_skills: ["Read nonfiction independently", "Use text features", "Monitor comprehension"],
    prior_standards: [{ code: "RI.3.10", text: "Read and comprehend informational texts at the high end of the grades 2-3 band" }],
    future_standards: [{ code: "RI.5.10", text: "Read and comprehend informational texts at the high end of the grades 4-5 band" }],
    challenges: [
      { problem: "Dense paragraphs get skimmed", fix: "Chunk the text and summarize after each section. It restores comprehension where skimming loses it" },
      { problem: "Long texts are abandoned rather than sectioned", fix: "Mark the chunks before starting, so the end is visible" },
    ],
    mastery_statement: "Student can work through dense informational text by chunking and summarizing as they go.",
    ladder: [
      { name: "I can read a section", descriptor: "Handles short pieces" },
      { name: "I can mark the chunks", descriptor: "Sections the text" },
      { name: "I can summarize each", descriptor: "Checks as they go" },
      { name: "I can sustain a long text", descriptor: "Reads across the whole" },
    ],
  },
  {
    standard_code: "RF.4.3.A",
    verbs: [
      { word: "Use", gloss: "sounds, syllables and morphology together" },
      { word: "Read", gloss: "unfamiliar long words accurately" },
      { word: "Apply", gloss: "morphology to the meaning" },
    ],
    concepts: ["Combined knowledge", "In and out of context", "Decoding into meaning"],
    vocabulary: [
      { term: "syllabication", definition: "splitting a word into syllables" },
      { term: "morphology", definition: "the study of word parts and their meanings" },
      { term: "root", definition: "the part carrying the core meaning" },
      { term: "affix", definition: "a prefix or suffix" },
    ],
    prior_skills: ["Decode multisyllable words", "Know common affixes", "Read Latin suffixes"],
    prior_standards: [{ code: "RF.3.3.C", text: "Decode multisyllable words" }],
    future_standards: [{ code: "RF.5.3", text: "Use combined knowledge of morphology to read unfamiliar multisyllabic words" }],
    challenges: [
      { problem: "A long word is decoded correctly but its meaning is skipped, so comprehension does not improve", fix: "Reading it is half. Say what it means, using the parts, before moving on" },
      { problem: "Only sound is used, ignoring the morphology available", fix: "Find the root first, then the affixes, then the sounds" },
    ],
    mastery_statement: "Student can decode an unfamiliar multisyllabic word and use its parts to say what it means.",
    ladder: [
      { name: "I can split it", descriptor: "Applies syllabication" },
      { name: "I can read it", descriptor: "Decodes accurately" },
      { name: "I can find the root", descriptor: "Uses morphology" },
      { name: "I can say what it means", descriptor: "Connects decoding to meaning" },
    ],
  },
  {
    standard_code: "RF.4.4.A",
    verbs: [
      { word: "Read", gloss: "with a purpose" },
      { word: "Adjust", gloss: "the approach to match" },
      { word: "Monitor", gloss: "whether it worked" },
    ],
    concepts: ["Purpose", "Speed and depth", "Monitoring"],
    vocabulary: [
      { term: "purpose", definition: "why you are reading this" },
      { term: "comprehension", definition: "understanding what you read" },
      { term: "monitor", definition: "keep checking" },
    ],
    prior_skills: ["Set a purpose", "Skim and read closely", "Check against the purpose"],
    prior_standards: [{ code: "RF.3.4.A", text: "Read grade-level text with purpose and understanding" }],
    future_standards: [{ code: "RF.5.4", text: "Read with sufficient accuracy and fluency to support comprehension" }],
    challenges: [
      { problem: "Every text is read at the same speed and depth regardless of why", fix: "Name the purpose, then name the approach. Two decisions, not one" },
      { problem: "The purpose is set and then forgotten", fix: "Answer it with the text closed" },
    ],
    mastery_statement: "Student can set a purpose and match their reading approach to it.",
    ladder: [
      { name: "I can read it", descriptor: "Comprehends" },
      { name: "I can set a purpose", descriptor: "Names it first" },
      { name: "I can choose an approach", descriptor: "Adjusts speed and depth" },
      { name: "I can check it worked", descriptor: "Monitors against the purpose" },
    ],
  },
  {
    standard_code: "RF.4.4.B",
    verbs: [
      { word: "Read", gloss: "prose and poetry aloud" },
      { word: "Phrase", gloss: "so the meaning carries" },
      { word: "Improve", gloss: "across readings" },
    ],
    concepts: ["Phrasing", "Prosody", "Long sentences"],
    vocabulary: [
      { term: "fluency", definition: "reading that carries meaning" },
      { term: "prosody", definition: "the music of reading aloud" },
      { term: "phrasing", definition: "grouping words that belong together" },
      { term: "rate", definition: "how fast you read" },
    ],
    prior_skills: ["Read aloud with expression", "Use punctuation", "Reread for improvement"],
    prior_standards: [{ code: "RF.3.4.B", text: "Read grade-level prose and poetry orally with accuracy, rate and expression" }],
    future_standards: [{ code: "RF.5.4", text: "Read grade-level prose and poetry orally with accuracy, rate and expression" }],
    challenges: [
      { problem: "Word-by-word reading persists in longer sentences even when every word is known", fix: "Mark the phrase groups with slashes before reading. The sentence is too long to hold without them" },
      { problem: "Expression is added as performance rather than meaning", fix: "The expression should follow the sense, so ask what the sentence means first" },
    ],
    mastery_statement: "Student can read long sentences in meaningful phrases rather than word by word.",
    ladder: [
      { name: "I can read the words", descriptor: "Decodes accurately" },
      { name: "I can stop at punctuation", descriptor: "Uses basic phrasing" },
      { name: "I can group into phrases", descriptor: "Phrases within sentences" },
      { name: "I can carry the meaning", descriptor: "Uses prosody for sense" },
    ],
  },
  {
    standard_code: "RF.4.4.C",
    verbs: [
      { word: "Use", gloss: "context to confirm" },
      { word: "Self-correct", gloss: "at the meaning level" },
      { word: "Monitor", gloss: "the whole passage" },
    ],
    concepts: ["Passage-level monitoring", "Repair", "Beyond the word"],
    vocabulary: [
      { term: "self-correct", definition: "fix your own error" },
      { term: "context", definition: "the surrounding meaning" },
      { term: "monitor", definition: "keep checking it makes sense" },
    ],
    prior_skills: ["Self-correct at word level", "Reread", "Notice a meaning breakdown"],
    prior_standards: [{ code: "RF.3.4.C", text: "Use context to confirm or self-correct word recognition, rereading as necessary" }],
    future_standards: [{ code: "RF.5.4", text: "Use context to confirm or self-correct word recognition and understanding" }],
    challenges: [
      { problem: "Monitoring happens only at word level, never at whether the passage as a whole made sense", fix: "A check at the end of each paragraph, not each sentence. Some breakdowns are only visible from further back" },
      { problem: "Rereading means rereading the word", fix: "Go back to the start of the paragraph, since that is where the sense went" },
    ],
    mastery_statement: "Student can notice a passage-level breakdown and reread far enough back to repair it.",
    ladder: [
      { name: "I can fix a word", descriptor: "Corrects at word level" },
      { name: "I can fix a sentence", descriptor: "Repairs locally" },
      { name: "I can check a paragraph", descriptor: "Monitors at passage level" },
      { name: "I can reread far enough", descriptor: "Repairs from the right point" },
    ],
  },
];

const blueprintsData = [
  {
    standard_code: "RL.4.4",
    title: "A Name Doing Odd Work",
    badge: "Grade 4",
    route_name: "Strategy Instruction",
    route_line: "Spot the signal → Find the source → Apply it here",
    success_criteria: ["Notices an allusion", "Finds what it refers to", "Uses it to read the sentence"],
    steps: [
      { name: "Retrieve Context Clues", minutes: 5, body: "The tools already held.", science_tag: "retrieval" },
      { name: "Read Straight Past", minutes: 10, body: "A sentence with an allusion nobody notices. The meaning is available and nobody collected it.", science_tag: "metacognition" },
      { name: "The Signal", minutes: 12, body: "A capitalized name doing odd work in an ordinary sentence. Teach the flag, not the myth — you cannot pre-teach every story.", science_tag: "elaboration" },
      { name: "Look It Up", minutes: 12, body: "The reference found, the story read in two lines.", science_tag: "interleaving" },
      { name: "Bring It Back", minutes: 12, body: "An Achilles heel means one fatal weakness. So what is theirs, in this text?", science_tag: "elaboration" },
      { name: "Collect Them", minutes: 8, body: "Allusions logged as they are met across the year.", science_tag: "spaced" },
      { name: "Write One", minutes: 3, body: "Use an allusion in their own sentence.", science_tag: "elaboration" },
    ],
    ef_supports: ["Allusion signal card", "Two-line myth summaries", "Bring-it-back frame", "Allusion log"],
    tech: "A myth reference and texts containing allusions",
    tech_purpose: "Looking it up is the skill, so the reference has to be reachable",
    ai_prompts: ["Write passages containing mythological allusions", "Generate two-line summaries of common myths"],
    assessment: ["Check the allusion was noticed", "Confirm the meaning is applied", "Read the allusion log"],
    why_it_works: ["Teaching the signal scales, where pre-teaching every myth does not", "Reading straight past shows the cost before the fix", "Bringing the meaning back is what makes it a reading skill rather than trivia", "Writing one proves the reference was understood"],
  },
  {
    standard_code: "RL.4.5",
    title: "Three Forms, Three Vocabularies",
    badge: "Grade 4",
    route_name: "Explicit Instruction",
    route_line: "Open all three → Name each form's parts → Say what the form allows",
    success_criteria: ["Explains major differences", "Uses genre-specific terms", "Says what each form does"],
    steps: [
      { name: "Retrieve Structural Terms", minutes: 5, body: "Chapter, scene, stanza, from grade 3.", science_tag: "retrieval" },
      { name: "Stanzas Are Not Paragraphs", minutes: 10, body: "The exact slip the deck names, corrected by putting the forms side by side.", science_tag: "elaboration" },
      { name: "Three Texts, Three Lists", minutes: 14, body: "Prose, drama, poetry open together, each with its own vocabulary.", science_tag: "dual-coding" },
      { name: "What Can This Form Do", minutes: 12, body: "Stage directions show what a narrator would have to tell you. Meter does what prose cannot.", science_tag: "elaboration" },
      { name: "Same Scene, Three Forms", minutes: 12, body: "One moment written as prose, as a script, as a poem.", science_tag: "interleaving" },
      { name: "Write About One", minutes: 8, body: "Using its own terms accurately.", science_tag: "interleaving" },
      { name: "Yesterday's Terms", minutes: 4, body: "Recalled cold across all three.", science_tag: "spaced" },
    ],
    ef_supports: ["Three-form desk set", "Per-form vocabulary lists", "Same-scene comparison", "Term accuracy check"],
    tech: "A novel, a script and a poetry collection",
    tech_purpose: "The distinction cannot be taught from one form",
    ai_prompts: ["Write one scene as prose, drama and poetry", "Generate genre vocabulary sets"],
    assessment: ["Check terms match the form", "Confirm what-the-form-does is answered", "Read for term accuracy"],
    why_it_works: ["Three forms together makes the vocabulary belong to something", "Writing one scene three ways shows what each form gains and gives up", "Asking what a form allows moves past labeling into explanation", "Cold recall across forms catches the paragraph-for-stanza slip"],
  },
  {
    standard_code: "RL.4.6",
    title: "Rewrite It in the Other Person",
    badge: "Grade 4",
    route_name: "Analytical Reading",
    route_line: "Name the person → Rewrite a paragraph → Say what was lost",
    success_criteria: ["Distinguishes first and third person", "Compares points of view", "Explains the effect"],
    steps: [
      { name: "Retrieve Narrator", minutes: 5, body: "Who is telling it, from grade 3.", science_tag: "retrieval" },
      { name: "I Know Which It Is", minutes: 8, body: "Naming the person is easy and is not the standard. The effect is.", science_tag: "metacognition" },
      { name: "Rewrite in the Other", minutes: 16, body: "One paragraph, switched. What can you no longer tell the reader? That loss is the effect.", science_tag: "elaboration" },
      { name: "What the Narrator Cannot See", minutes: 12, body: "First person is stuck behind one pair of eyes. That is a limit and a strength.", science_tag: "elaboration" },
      { name: "A Narrator Who Is Wrong", minutes: 10, body: "Closeness is not accuracy.", science_tag: "elaboration" },
      { name: "Compare Two Stories", minutes: 10, body: "One of each, set against each other.", science_tag: "dual-coding" },
      { name: "Which Would You Choose", minutes: 4, body: "For a story of their own, with a reason.", science_tag: "metacognition" },
    ],
    ef_supports: ["Rewrite frame", "What-was-lost prompt", "Unreliable narrator passage", "Two-story comparison"],
    tech: "Paired texts in first and third person",
    tech_purpose: "Comparing points of view needs both present",
    ai_prompts: ["Write one passage in both first and third person", "Generate passages with a mistaken narrator"],
    assessment: ["Check the effect is explained, not just the person named", "Read the rewrite for what was lost", "Ask about limits"],
    why_it_works: ["Rewriting makes the effect something they discover rather than are told", "Naming what cannot be said is the clearest measure of a narrator's limits", "A mistaken narrator separates proximity from reliability", "Choosing for their own story requires understanding the trade-off"],
  },
  {
    standard_code: "RL.4.7",
    title: "Every Difference Gets a So-What",
    badge: "Grade 4",
    route_name: "Analytical Reading",
    route_line: "Find the differences → Ask what each changes → Say what each form can do",
    success_criteria: ["Connects text to presentation", "Analyzes the effect of choices", "Names what each version can do"],
    steps: [
      { name: "Retrieve the Text", minutes: 6, body: "What the book actually said, before watching.", science_tag: "retrieval" },
      { name: "The List of Differences", minutes: 10, body: "Easy, and not the standard. Listing is where most comparisons stop.", science_tag: "metacognition" },
      { name: "So What", minutes: 16, body: "Every difference gets one. A cut character changes something — naming what is the work.", science_tag: "elaboration" },
      { name: "Where They Match", minutes: 10, body: "A specific description reflected in a specific shot. Connection, not only contrast.", science_tag: "dual-coding" },
      { name: "What Film Can Do", minutes: 12, body: "And what it cannot. A face shows in a frame what a page needs a paragraph for.", science_tag: "elaboration" },
      { name: "Write the Analysis", minutes: 10, body: "One difference, and what it changes.", science_tag: "interleaving" },
      { name: "Not Better, Different", minutes: 3, body: "Judgment set aside in favor of analysis.", science_tag: "metacognition" },
    ],
    ef_supports: ["So-what requirement", "Matching-moment log", "What-each-form-can-do chart", "Judgment ban"],
    tech: "A text and a filmed or staged version",
    tech_purpose: "Both versions have to be known to be compared",
    ai_prompts: ["Generate adaptation comparison prompts", "Write analysis frames for what a change accomplishes"],
    assessment: ["Check every difference has a so-what", "Confirm matches are found too", "Watch for better-or-worse judgments"],
    why_it_works: ["Requiring a so-what on every difference is what turns a list into analysis", "Finding matches stops the comparison being only about what was cut", "Asking what each form can do explains the choices rather than cataloging them", "Setting judgment aside keeps attention on effect"],
  },
  {
    standard_code: "RL.4.9",
    title: "Strip Both to the Skeleton",
    badge: "Grade 4",
    route_name: "Analytical Reading",
    route_line: "Reduce each to five steps → Lay them side by side → Compare the treatment",
    success_criteria: ["Compares themes across cultures", "Compares patterns of events", "Looks past surface detail"],
    steps: [
      { name: "Retrieve Theme", minutes: 5, body: "A claim about life, not a topic.", science_tag: "retrieval" },
      { name: "Different Animals, Same Story", minutes: 10, body: "Two tales that look nothing alike and share a shape.", science_tag: "elaboration" },
      { name: "Five Steps Each", minutes: 14, body: "Both stories stripped to a skeleton. The surface differs; the skeleton often does not.", science_tag: "dual-coding" },
      { name: "Line Them Up", minutes: 12, body: "Step against step. Where they match, and where one culture went elsewhere.", science_tag: "dual-coding" },
      { name: "Why the Difference", minutes: 12, body: "What does the change tell you about what that culture valued?", science_tag: "elaboration" },
      { name: "Write the Comparison", minutes: 10, body: "On theme or pattern, not on setting details.", science_tag: "interleaving" },
      { name: "A Third Tale", minutes: 3, body: "Tested against the same skeleton.", science_tag: "spaced" },
    ],
    ef_supports: ["Five-step skeleton template", "Side-by-side grid", "Why-the-difference prompt", "Surface detail ban"],
    tech: "Myths and folktales from several cultures",
    tech_purpose: "The standard names traditional literature from different cultures",
    ai_prompts: ["Write culturally distinct tales sharing a pattern", "Generate five-step story skeletons"],
    assessment: ["Check comparison is on theme or pattern", "Confirm skeletons were made first", "Read the why-the-difference answers"],
    why_it_works: ["A five-step skeleton removes the surface detail that comparisons get stuck on", "Lining up step against step makes the shared pattern visible", "Asking why a culture changed something treats difference as meaningful", "A third tale tests whether the skeleton was real"],
  },
  {
    standard_code: "RL.4.10",
    title: "Turning Pages Is Not Proof",
    badge: "Grade 4",
    route_name: "Strategy Instruction",
    route_line: "Read a stretch → Retell at checkpoints → Repair before the end",
    success_criteria: ["Reads in the 4-5 band", "Demonstrates comprehension", "Uses scaffolds at the high end"],
    steps: [
      { name: "Retrieve the Story So Far", minutes: 6, body: "Before reading on. Recall, not recap.", science_tag: "retrieval" },
      { name: "Finished but Lost", minutes: 8, body: "Named honestly. Reaching the last page is not evidence of anything.", science_tag: "metacognition" },
      { name: "Retell at Chapter Five", minutes: 14, body: "A checkpoint early enough to repair. Waiting until the end finds the gap too late.", science_tag: "retrieval" },
      { name: "Where Did I Lose It", minutes: 10, body: "Located, not just felt. Go back to there rather than to the start.", science_tag: "metacognition" },
      { name: "Slow Down Is a Strategy", minutes: 10, body: "Difficulty is usually met by speeding up. Naming the alternative matters.", science_tag: "elaboration" },
      { name: "Read On", minutes: 14, body: "Independent, with checkpoints marked in advance.", science_tag: "spaced" },
      { name: "Book Talk", minutes: 4, body: "Which requires having understood it.", science_tag: "collaborative" },
    ],
    ef_supports: ["Checkpoint markers", "Retell prompts", "Where-I-lost-it log", "Book talk frame"],
    tech: "Classroom library spanning the 4-5 band",
    tech_purpose: "The high end has to be available",
    ai_prompts: ["Generate checkpoint retelling prompts", "Write comprehension traps for longer texts"],
    assessment: ["Test retelling at checkpoints, not only at the end", "Read the lost-it log", "Listen to book talks"],
    why_it_works: ["A checkpoint at chapter five catches the gap while it can still be repaired", "Naming finished-but-lost separates completion from comprehension", "Locating where it went wrong beats rereading from the beginning", "A book talk cannot be given about a book that was not understood"],
  },
  {
    standard_code: "RI.4.1",
    title: "One Sentence, Not the Paragraph",
    badge: "Grade 4",
    route_name: "Strategy Instruction",
    route_line: "Make the point → Cite one sentence → Label any inference",
    success_criteria: ["Cites precisely", "Separates explicit from inferred", "Uses examples"],
    steps: [
      { name: "Retrieve Evidence", minutes: 5, body: "What counts, and what does not.", science_tag: "retrieval" },
      { name: "The Whole Paragraph", minutes: 10, body: "Cited as support. Which sentence actually does the work? Usually one.", science_tag: "metacognition" },
      { name: "One Sentence Maximum", minutes: 14, body: "If the point needs a paragraph, the point is not sharp enough. The limit sharpens the claim.", science_tag: "elaboration" },
      { name: "Says and I Conclude", minutes: 12, body: "Two columns. Inference labeled as inference.", science_tag: "dual-coding" },
      { name: "Examples Count Too", minutes: 10, body: "The standard says details and examples. An example is evidence.", science_tag: "elaboration" },
      { name: "Write With Citations", minutes: 10, body: "Every claim carrying its sentence.", science_tag: "interleaving" },
      { name: "Partner Audit", minutes: 3, body: "Is that the sentence that proves it?", science_tag: "collaborative" },
    ],
    ef_supports: ["One-sentence limit", "Two-column says-and-conclude", "Line-numbered texts", "Partner audit"],
    tech: "Printed informational text with line numbers",
    tech_purpose: "Precise citation needs stable references",
    ai_prompts: ["Write paragraphs where one sentence carries the support", "Generate explicit and inferable questions"],
    assessment: ["Check citations are single sentences", "Confirm inference is labeled", "Run the partner audit"],
    why_it_works: ["A one-sentence limit forces the claim to be sharp enough to prove", "Two columns keep inference honest without discouraging it", "Naming examples as evidence matches what the standard asks for", "A partner asking whether that sentence proves it tests precision"],
  },
  {
    standard_code: "RI.4.4",
    title: "A Familiar Word Is a Warning",
    badge: "Grade 4",
    route_name: "Strategy Instruction",
    route_line: "Spot the two-lives word → Take the subject meaning → Substitute to check",
    success_criteria: ["Determines technical meanings", "Uses context and references", "Verifies the fit"],
    steps: [
      { name: "Retrieve Vocabulary Tools", minutes: 5, body: "Context, features, references.", science_tag: "retrieval" },
      { name: "Current, Solution, Contract", minutes: 12, body: "The deck's own examples. Each has an everyday life and a technical one, and both are real.", science_tag: "elaboration" },
      { name: "Familiar Means Careful", minutes: 10, body: "A known word in a science text is a warning rather than a relief.", science_tag: "metacognition" },
      { name: "Which Meaning Here", minutes: 12, body: "Asked of every candidate before reading on.", science_tag: "metacognition" },
      { name: "Substitute and Read", minutes: 10, body: "Put the meaning in. If the sentence breaks, the meaning was wrong.", science_tag: "metacognition" },
      { name: "Use the References", minutes: 10, body: "Glossary, footnote, dictionary — chosen deliberately.", science_tag: "interleaving" },
      { name: "Two-Lives Log", minutes: 4, body: "Collected across subjects.", science_tag: "spaced" },
    ],
    ef_supports: ["Two-lives word log", "Substitution frame", "Reference menu", "Which-meaning prompt"],
    tech: "Science and social studies texts with glossaries",
    tech_purpose: "Technical vocabulary needs a technical subject",
    ai_prompts: ["Generate words with distinct everyday and technical senses", "Write passages using the technical meaning"],
    assessment: ["Check the subject meaning was taken", "Confirm substitution", "Review the log"],
    why_it_works: ["Words with two real meanings show that familiarity misleads", "Treating a known word as a warning inverts the usual instinct", "Substitution catches the everyday meaning being imported", "A log across subjects builds the habit beyond one lesson"],
  },
  {
    standard_code: "RI.4.6",
    title: "There, But Only in One Corner",
    badge: "Grade 4",
    route_name: "Analytical Reading",
    route_line: "Read both accounts → Compare the focus → Name what each misses",
    success_criteria: ["Compares firsthand and secondhand", "Describes differences in focus", "Names the limits of each"],
    steps: [
      { name: "Retrieve Point of View", minutes: 5, body: "From grade 3 — the author has a position.", science_tag: "retrieval" },
      { name: "Firsthand Must Be Right", minutes: 12, body: "Tested rather than assumed. Someone at the scene sees one corner of it, and being there is a limit as well as a strength.", science_tag: "elaboration" },
      { name: "Two Accounts, One Event", minutes: 14, body: "Read together. What does each pay attention to?", science_tag: "dual-coding" },
      { name: "What Only One Says", minutes: 12, body: "Coverage as well as content. A secondhand account can see the whole field.", science_tag: "elaboration" },
      { name: "Name the Limits", minutes: 10, body: "For both. Neither is complete, and saying why is the standard.", science_tag: "metacognition" },
      { name: "Write the Comparison", minutes: 10, body: "Focus and information, both addressed.", science_tag: "interleaving" },
      { name: "Which Would You Trust", minutes: 3, body: "For what question? The answer depends on the question.", science_tag: "metacognition" },
    ],
    ef_supports: ["Paired account sets", "Focus comparison grid", "Limits column", "Trust-for-what prompt"],
    tech: "Firsthand and secondhand accounts of one event",
    tech_purpose: "Both kinds have to be present to compare",
    ai_prompts: ["Write firsthand and secondhand accounts of one event", "Generate questions where each source is better suited"],
    assessment: ["Check limits are named for both", "Confirm focus is compared, not only facts", "Read the trust reasoning"],
    why_it_works: ["Testing the firsthand assumption rather than stating it lets students find the limit", "One corner of the field is a picture that makes the limit concrete", "Comparing focus catches what comparing facts alone misses", "Asking trust-for-what-question makes evaluation situational rather than absolute"],
  },
  {
    standard_code: "RI.4.7",
    title: "What That Number Does for the Argument",
    badge: "Grade 4",
    route_name: "Strategy Instruction",
    route_line: "Read the display → Say what it shows → Say what it proves",
    success_criteria: ["Interprets visual and quantitative information", "Connects it to the text", "Explains the contribution"],
    steps: [
      { name: "Retrieve Display Types", minutes: 5, body: "Chart, graph, timeline, diagram.", science_tag: "retrieval" },
      { name: "Reading Is Not Interpreting", minutes: 10, body: "The number is step one. What does it mean for the point being made?", science_tag: "metacognition" },
      { name: "Say What It Shows", minutes: 12, body: "In a sentence, using the axes and the units.", science_tag: "dual-coding" },
      { name: "Say What It Proves", minutes: 14, body: "For the author's argument. This is the contributes-to-understanding half.", science_tag: "elaboration" },
      { name: "Remove the Display", minutes: 10, body: "What can the text no longer show? The gap names the contribution.", science_tag: "elaboration" },
      { name: "A Timeline Instead", minutes: 8, body: "Same routine, different display type.", science_tag: "interleaving" },
      { name: "Write the Connection", minutes: 3, body: "The chart shows ___, which supports ___.", science_tag: "interleaving" },
    ],
    ef_supports: ["Shows-and-proves two-step", "Display type set", "Remove-the-display test", "Connection frame"],
    tech: "Texts with charts, graphs and timelines",
    tech_purpose: "The standard names visual, oral and quantitative alike",
    ai_prompts: ["Write texts where a chart carries an argumentative load", "Generate displays of varying relevance"],
    assessment: ["Check both shows and proves are answered", "Confirm the connection to the text", "Test the removal reasoning"],
    why_it_works: ["Separating shows from proves names the step that gets skipped", "Removing the display makes its contribution measurable", "Using axes and units keeps the reading precise", "Covering several display types matches what the standard asks"],
  },
  {
    standard_code: "RI.4.8",
    title: "Confident Is Not Proven",
    badge: "Grade 4",
    route_name: "Analytical Reading",
    route_line: "Find the claim → Hunt the evidence → Judge whether it holds",
    success_criteria: ["Distinguishes claim from evidence", "Explains how reasons support", "Evaluates strength"],
    steps: [
      { name: "Retrieve Claim and Reason", minutes: 5, body: "From grade 3.", science_tag: "retrieval" },
      { name: "All Assertion, No Evidence", minutes: 12, body: "A confident paragraph with nothing behind it. Hunt for the support and fail. Print is not proof.", science_tag: "elaboration" },
      { name: "Two Columns", minutes: 12, body: "Claim, and what supports it. Assertions land in neither.", science_tag: "dual-coding" },
      { name: "Rank the Reasons", minutes: 12, body: "Three weak ones do not equal one strong one. Weighing, not counting.", science_tag: "elaboration" },
      { name: "What Would Convince Me", minutes: 10, body: "Name the evidence that is missing.", science_tag: "metacognition" },
      { name: "Write the Evaluation", minutes: 10, body: "The claim, the support, and whether it holds.", science_tag: "interleaving" },
      { name: "Argue the Other Side", minutes: 3, body: "What would the strongest objection be?", science_tag: "collaborative" },
    ],
    ef_supports: ["Claim and support columns", "Assertion-only passage", "Ranking ladder", "Missing evidence prompt"],
    tech: "Persuasive nonfiction at grade level",
    tech_purpose: "Evaluating support needs a text that argues",
    ai_prompts: ["Write confident paragraphs with no evidence", "Generate reason sets of varying strength"],
    assessment: ["Check assertions are not counted as evidence", "Read the rankings", "Confirm missing evidence is named"],
    why_it_works: ["Failing to find evidence in a confident paragraph is more persuasive than a definition", "Two columns force each statement to be classified", "Ranking replaces counting, which is where evaluation actually happens", "Naming missing evidence shows what would have made the case"],
  },
  {
    standard_code: "RI.4.9",
    title: "Write About the Topic, Not the Reading",
    badge: "Grade 4",
    route_name: "Analytical Reading",
    route_line: "Read both → Merge the notes → Write one account",
    success_criteria: ["Integrates two sources", "Writes knowledgeably", "Names conflicts"],
    steps: [
      { name: "Retrieve Note-Taking", minutes: 5, body: "Brief notes, sorted into categories.", science_tag: "retrieval" },
      { name: "Two Summaries in a Row", minutes: 10, body: "Named as the failure it is. That is reporting on the reading, not writing about the topic.", science_tag: "metacognition" },
      { name: "Ban the Phrases", minutes: 12, body: "The first text and the second text, both forbidden. The ban forces integration.", science_tag: "elaboration" },
      { name: "Merge the Notes", minutes: 14, body: "One set of categories, notes from both sources in each.", science_tag: "dual-coding" },
      { name: "Where They Disagree", minutes: 12, body: "Named in the writing rather than resolved by picking one.", science_tag: "elaboration" },
      { name: "Write the Account", minutes: 12, body: "As someone who knows the subject.", science_tag: "interleaving" },
      { name: "Could a Reader Tell", minutes: 3, body: "Which fact came from which source? They should not need to.", science_tag: "metacognition" },
    ],
    ef_supports: ["Banned-phrase list", "Merged category sheet", "Disagreement box", "Knowledgeable-voice check"],
    tech: "Paired sources on one topic",
    tech_purpose: "Integration needs two sources that overlap and diverge",
    ai_prompts: ["Write two sources that agree partly and conflict once", "Generate merged category schemes"],
    assessment: ["Check for source-by-source structure", "Confirm conflicts are named", "Read for a knowledgeable voice"],
    why_it_works: ["Banning the phrases removes the structure that produces stacked summaries", "Merging notes into shared categories does the integration before the writing", "Naming a disagreement is more honest than silently picking a side", "Writing as someone who knows is the standard's own word, knowledgeably"],
  },
  {
    standard_code: "RI.4.10",
    title: "Mark the Chunks Before You Start",
    badge: "Grade 4",
    route_name: "Strategy Instruction",
    route_line: "Section the text → Read one chunk → Summarize before moving on",
    success_criteria: ["Reads dense nonfiction", "Chunks the text", "Summarizes each section"],
    steps: [
      { name: "Retrieve Text Features", minutes: 5, body: "Headings, subheadings, bold terms.", science_tag: "retrieval" },
      { name: "The Skim", minutes: 8, body: "What happens to dense paragraphs, named honestly. Eyes move, nothing lands.", science_tag: "metacognition" },
      { name: "Mark the Chunks First", minutes: 12, body: "Before reading. The end becomes visible, and a long text becomes several short ones.", science_tag: "dual-coding" },
      { name: "One Chunk, Then Stop", minutes: 14, body: "Summarize before moving on. This is what restores comprehension where skimming loses it.", science_tag: "retrieval" },
      { name: "Where It Got Dense", minutes: 10, body: "Marked, and reread deliberately rather than skimmed past.", science_tag: "metacognition" },
      { name: "Read a Long One", minutes: 14, body: "Independently, with chunks marked in advance.", science_tag: "spaced" },
      { name: "Say It Back", minutes: 4, body: "The whole text, from the section summaries.", science_tag: "retrieval" },
    ],
    ef_supports: ["Chunk marking routine", "Section summary lines", "Density marks", "Say-it-back from summaries"],
    tech: "Dense informational text in the 4-5 band",
    tech_purpose: "Chunking is only needed where the text is genuinely long",
    ai_prompts: ["Write dense multi-section informational texts", "Generate section summary prompts"],
    assessment: ["Check chunks are marked before reading", "Confirm a summary per section", "Test the whole-text retell"],
    why_it_works: ["Marking chunks first turns one long text into several short ones", "Summarizing before moving on is what stops the skim", "Naming where it got dense makes rereading targeted", "Retelling from summaries proves the sections connected"],
  },
  {
    standard_code: "RF.4.3.A",
    title: "Read It, Then Say What It Means",
    badge: "Grade 4",
    route_name: "Explicit Instruction",
    route_line: "Find the root → Read the whole → State the meaning",
    success_criteria: ["Decodes multisyllabic words", "Uses morphology", "Connects decoding to meaning"],
    steps: [
      { name: "Retrieve Roots and Affixes", minutes: 5, body: "The parts already known.", science_tag: "retrieval" },
      { name: "Decoded and Not Understood", minutes: 10, body: "A word read perfectly and skipped past. Comprehension did not improve, which is the whole problem.", science_tag: "metacognition" },
      { name: "Root First", minutes: 12, body: "Before the sounds. Morphology gives a way in that phonics alone does not.", science_tag: "elaboration" },
      { name: "Then Syllables", minutes: 12, body: "Split what is left, read through, blend.", science_tag: "dual-coding" },
      { name: "Say What It Means", minutes: 12, body: "Using the parts. Reading it is half the job.", science_tag: "elaboration" },
      { name: "In and Out of Context", minutes: 10, body: "The standard names both. A word list and a sentence.", science_tag: "interleaving" },
      { name: "Yesterday's Words", minutes: 4, body: "Read and defined again, cold.", science_tag: "spaced" },
    ],
    ef_supports: ["Root-first routine", "Meaning statement requirement", "In-and-out-of-context sets", "Word log"],
    tech: "Word lists and connected text",
    tech_purpose: "The standard names both contexts explicitly",
    ai_prompts: ["Generate multisyllabic words with recognizable roots", "Write sentences containing target words"],
    assessment: ["Require the meaning, not just the reading", "Test in isolation and in text", "Check the root is found first"],
    why_it_works: ["Naming the decoded-but-not-understood gap makes meaning part of the task", "Finding the root first uses knowledge phonics alone cannot reach", "Requiring the meaning every time closes the gap the deck names", "Testing both in and out of context matches the standard"],
  },
  {
    standard_code: "RF.4.4.A",
    title: "Two Decisions, Not One",
    badge: "Grade 4",
    route_name: "Strategy Instruction",
    route_line: "Name the purpose → Name the approach → Check it worked",
    success_criteria: ["Sets a purpose", "Adjusts speed and depth", "Monitors the outcome"],
    steps: [
      { name: "Retrieve Purpose Types", minutes: 4, body: "Locate, follow, understand, enjoy.", science_tag: "retrieval" },
      { name: "Same Speed Every Time", minutes: 10, body: "Named as the default it is. One speed cannot serve four purposes.", science_tag: "metacognition" },
      { name: "Purpose, Then Approach", minutes: 14, body: "Two decisions written down before reading. The second is the one usually skipped.", science_tag: "metacognition" },
      { name: "One Text, Four Purposes", minutes: 14, body: "The same page read four ways. If it looked the same each time, something is wrong.", science_tag: "interleaving" },
      { name: "Close and Answer", minutes: 10, body: "Against the purpose, text shut.", science_tag: "retrieval" },
      { name: "The Wrong Approach", minutes: 8, body: "Deliberately mismatched, so the mismatch is felt.", science_tag: "elaboration" },
      { name: "Choose Both Yourself", minutes: 4, body: "Unprompted, for a new text.", science_tag: "metacognition" },
    ],
    ef_supports: ["Two-decision card", "Four-purpose set", "Close-and-answer check", "Mismatch exercise"],
    tech: "One text reused across purposes",
    tech_purpose: "Holding the text constant isolates the approach",
    ai_prompts: ["Generate four purposes for one text", "Write purpose-matched question sets"],
    assessment: ["Check both decisions are recorded", "Watch whether reading behavior changes", "Confirm the check happens"],
    why_it_works: ["Naming the approach as a second decision surfaces the step usually skipped", "One text and four purposes isolates approach as the only variable", "A deliberate mismatch makes the cost felt rather than described", "Answering with the text closed tests reading, not searching"],
  },
  {
    standard_code: "RF.4.4.B",
    title: "Slashes Before You Read It Aloud",
    badge: "Grade 4",
    route_name: "Routine and Practice",
    route_line: "Mark the phrases → Read in groups → Improve on the next pass",
    success_criteria: ["Reads in meaningful phrases", "Uses accuracy, rate and expression", "Improves across readings"],
    steps: [
      { name: "Retrieve Punctuation Jobs", minutes: 4, body: "What each mark does to the voice.", science_tag: "retrieval" },
      { name: "Word By Word in Long Sentences", minutes: 10, body: "Every word known, and the sentence still falls apart. Length is the problem, not vocabulary.", science_tag: "metacognition" },
      { name: "Mark the Phrase Groups", minutes: 14, body: "Slashes before reading aloud. A long sentence cannot be held without them.", science_tag: "dual-coding" },
      { name: "Read the Groups", minutes: 12, body: "Not the words. The voice carries the grouping.", science_tag: "collaborative" },
      { name: "What Does It Mean", minutes: 10, body: "Before adding expression, so the expression follows the sense rather than performing.", science_tag: "elaboration" },
      { name: "Three Reads", minutes: 12, body: "Successive, as the standard says.", science_tag: "spaced" },
      { name: "Poetry Too", minutes: 4, body: "Where line breaks are not stops.", science_tag: "interleaving" },
    ],
    ef_supports: ["Phrase-marking slashes", "Meaning-before-expression rule", "Three-read tracker", "Poetry set"],
    tech: "Long-sentence passages and poetry",
    tech_purpose: "Phrasing only matters where sentences are long",
    ai_prompts: ["Write passages with demanding sentence length", "Generate poetry with enjambment"],
    assessment: ["Listen for phrase groups rather than words", "Compare first and third reads", "Check meaning precedes expression"],
    why_it_works: ["Marking phrases makes an invisible grouping decision visible", "Naming length rather than vocabulary as the problem targets the real cause", "Establishing meaning first keeps expression from becoming performance", "Enjambment forces reading for sense over line"],
  },
  {
    standard_code: "RF.4.4.C",
    title: "Go Back Further Than the Word",
    badge: "Grade 4",
    route_name: "Strategy Instruction",
    route_line: "Check the paragraph → Find where it went → Reread from there",
    success_criteria: ["Monitors at passage level", "Locates the breakdown", "Rereads from the right point"],
    steps: [
      { name: "Retrieve the Check Question", minutes: 4, body: "Did that make sense — now applied to a paragraph, not a word.", science_tag: "retrieval" },
      { name: "Every Word Right, No Meaning", minutes: 12, body: "A passage read faultlessly that nobody can retell. Word-level monitoring missed it entirely.", science_tag: "metacognition" },
      { name: "Check at the Paragraph", minutes: 12, body: "Not the sentence. Some breakdowns are only visible from further back.", science_tag: "metacognition" },
      { name: "Where Did It Go", minutes: 12, body: "Located rather than felt. Often earlier than expected.", science_tag: "elaboration" },
      { name: "Reread From There", minutes: 12, body: "Not the word, not the start. From where the sense went.", science_tag: "elaboration" },
      { name: "Partner Listening", minutes: 10, body: "One reads, one listens for meaning rather than errors.", science_tag: "collaborative" },
      { name: "Yesterday's Passage", minutes: 3, body: "Reread with the paragraph check running.", science_tag: "spaced" },
    ],
    ef_supports: ["Paragraph check routine", "Where-did-it-go marking", "Reread-from-there prompt", "Meaning-focused listening"],
    tech: "Passages with built-in comprehension traps",
    tech_purpose: "A passage-level breakdown has to be constructed to be practiced",
    ai_prompts: ["Write passages that decode easily but confuse", "Generate paragraph-level monitoring prompts"],
    assessment: ["Check monitoring at paragraph level", "Confirm rereading starts at the right point", "Ask for a retell"],
    why_it_works: ["A faultlessly read passage nobody can retell shows word-level monitoring is not enough", "Checking at the paragraph catches breakdowns a sentence check misses", "Locating where the sense went makes rereading targeted rather than wholesale", "Listening for meaning rather than errors trains the right attention"],
  },
];

seedStandardsBatch({
  label: "Batch 15 — grade 4 reading",
  standardsData,
  unpacksData,
  blueprintsData,
});
