// @ts-nocheck
/**
 * Batch 5: 20 more drafted standards.
 *
 * Continues filling depth — grade 1 phonics, story structure, multistep
 * problems, multiplying fractions, area by decomposition, and two topics the
 * library had nothing on: irrational numbers and scatter plots.
 *
 *   bun run scripts/seed-standards-batch-5.ts
 */
import { seedStandardsBatch } from "./lib/seed-standards-batch";

const standardsData = [
  // ─── ELA ────────────────────────────────────────────────────────────────
  {
    code: "RI.K.1",
    name: "Ask and answer questions about a true book",
    plain_reading:
      "With prompting and support, ask and answer questions about key details in a text.",
    learning_target: "I can ask and answer questions about a book that tells me real things.",
    skills: ["Comprehension", "Questioning", "Nonfiction"],
    science_tags: ["retrieval", "collaborative"],
    match_keys: ["informational text kindergarten", "ask and answer", "key details", "with prompting"],
  },
  {
    code: "RF.1.3",
    name: "Use grade 1 phonics to read words",
    plain_reading:
      "Know and apply grade-level phonics and word analysis skills in decoding words, including consonant digraphs, final -e and common vowel teams, and counting syllables to decode longer words.",
    learning_target: "I can use letter patterns to read longer words on my own.",
    skills: ["Phonics", "Decoding", "Syllables"],
    science_tags: ["retrieval", "interleaving"],
    match_keys: ["digraphs", "silent e", "vowel teams", "syllables", "grade 1 phonics", "decoding"],
  },
  {
    code: "RL.2.5",
    name: "Describe how a story is put together",
    plain_reading:
      "Describe the overall structure of a story, including describing how the beginning introduces the story and the ending concludes the action.",
    learning_target: "I can explain what the beginning sets up and how the ending finishes it.",
    skills: ["Story Structure", "Beginning and Ending", "Narrative Analysis"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["story structure", "beginning middle end", "introduces", "concludes", "narrative shape"],
  },
  {
    code: "W.3.1",
    name: "Write an opinion piece with organized reasons",
    plain_reading:
      "Write opinion pieces on topics or texts, supporting a point of view with reasons, introducing the topic, stating an opinion, and creating an organizational structure that lists reasons.",
    learning_target: "I can state what I think and organize my reasons so they build.",
    skills: ["Opinion Writing", "Organization", "Reasons"],
    science_tags: ["elaboration", "spaced"],
    match_keys: ["opinion writing", "point of view", "reasons", "organizational structure", "linking words"],
  },
  {
    code: "RI.4.3",
    name: "Explain what happened and why",
    plain_reading:
      "Explain events, procedures, ideas, or concepts in a historical, scientific, or technical text, including what happened and why, based on specific information in the text.",
    learning_target: "I can explain not just what happened but why, using the text.",
    skills: ["Causation", "Nonfiction Analysis", "Textual Evidence"],
    science_tags: ["elaboration", "dual-coding"],
    match_keys: ["cause and effect", "explain events", "historical text", "scientific text", "procedures", "why"],
  },
  {
    code: "L.4.1",
    name: "Use grade 4 grammar correctly",
    plain_reading:
      "Demonstrate command of the conventions of standard English grammar and usage when writing or speaking, including relative pronouns, progressive verb tenses, modal auxiliaries, and prepositional phrases.",
    learning_target: "I can use tenses, pronouns and phrases correctly in my own writing.",
    skills: ["Grammar", "Verb Tense", "Sentence Structure"],
    science_tags: ["retrieval", "interleaving"],
    match_keys: ["grammar", "relative pronouns", "progressive tense", "modal auxiliaries", "prepositional phrases"],
  },
  {
    code: "SL.5.4",
    name: "Present a topic clearly and in order",
    plain_reading:
      "Report on a topic or text or present an opinion, sequencing ideas logically and using appropriate facts and relevant, descriptive details to support main ideas or themes, speaking clearly at an understandable pace.",
    learning_target: "I can present ideas in an order that makes sense, with details that back them up.",
    skills: ["Presenting", "Sequencing", "Supporting Detail"],
    science_tags: ["elaboration", "spaced"],
    match_keys: ["present a topic", "report", "sequencing ideas", "speaking clearly", "oral presentation"],
  },
  {
    code: "RL.6.4",
    name: "Analyze word choice and tone",
    plain_reading:
      "Determine the meaning of words and phrases as they are used in a text, including figurative and connotative meanings, and analyze the impact of a specific word choice on meaning and tone.",
    learning_target: "I can explain why a writer chose one word rather than a similar one.",
    skills: ["Word Choice", "Tone", "Connotation"],
    science_tags: ["elaboration", "interleaving"],
    match_keys: ["word choice", "tone", "connotation", "figurative meaning", "diction", "impact"],
  },
  {
    code: "RI.7.6",
    name: "Determine an author's point of view",
    plain_reading:
      "Determine an author's point of view or purpose in a text and analyze how the author distinguishes his or her position from that of others.",
    learning_target: "I can work out what the author thinks and how they set it apart from other views.",
    skills: ["Author's Purpose", "Point of View", "Critical Reading"],
    science_tags: ["elaboration", "dual-coding"],
    match_keys: ["author's purpose", "point of view", "position", "bias", "distinguishes", "perspective"],
  },
  {
    code: "W.7.1",
    name: "Write an argument that answers the other side",
    plain_reading:
      "Write arguments to support claims with clear reasons and relevant evidence, acknowledging alternate or opposing claims and organising the reasons and evidence logically.",
    learning_target: "I can argue a claim with evidence and deal with the opposing view.",
    skills: ["Argument Writing", "Counterclaim", "Logical Organization"],
    science_tags: ["elaboration", "interleaving"],
    match_keys: ["argument writing", "claim", "opposing claims", "evidence", "logical organization"],
  },

  // ─── Mathematics ────────────────────────────────────────────────────────
  {
    code: "K.NBT.A.1",
    name: "See teen numbers as ten and some more",
    plain_reading:
      "Compose and decompose numbers from 11 to 19 into ten ones and some further ones, and record each composition or decomposition by a drawing or equation.",
    learning_target: "I know 14 is one ten and four more.",
    skills: ["Place Value", "Composing Numbers", "Teen Numbers"],
    science_tags: ["dual-coding", "retrieval"],
    match_keys: ["teen numbers", "ten and some more", "compose decompose", "11 to 19", "place value"],
  },
  {
    code: "1.OA.B.3",
    name: "Use properties of operations to add",
    plain_reading:
      "Apply properties of operations as strategies to add and subtract, including that addition can be done in any order and that three numbers can be grouped in any way.",
    learning_target: "I can add numbers in whatever order makes it easiest.",
    skills: ["Commutative Property", "Associative Property", "Mental Strategies"],
    science_tags: ["elaboration", "dual-coding"],
    match_keys: ["commutative property", "associative property", "any order", "make a ten", "grouping"],
  },
  {
    code: "2.NBT.B.5",
    name: "Add and subtract fluently within 100",
    plain_reading:
      "Fluently add and subtract within 100 using strategies based on place value, properties of operations, and the relationship between addition and subtraction.",
    learning_target: "I can add and subtract two-digit numbers using a strategy that fits.",
    skills: ["Two-Digit Computation", "Place Value Strategies", "Fluency"],
    science_tags: ["retrieval", "interleaving"],
    match_keys: ["add within 100", "subtract within 100", "regrouping", "place value strategies", "two digit"],
  },
  {
    code: "3.G.A.1",
    name: "Sort shapes by what they have in common",
    plain_reading:
      "Understand that shapes in different categories may share attributes, that shared attributes can define a larger category, and recognize rhombuses, rectangles and squares as examples of quadrilaterals.",
    learning_target: "I can group shapes by what they share, not just what they look like.",
    skills: ["Classification", "Attributes", "Quadrilaterals"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["quadrilaterals", "attributes", "categories", "rhombus", "classify shapes"],
  },
  {
    code: "4.OA.A.3",
    name: "Solve multistep problems and read the remainder",
    plain_reading:
      "Solve multistep word problems posed with whole numbers using the four operations, including problems in which remainders must be interpreted, and assess the reasonableness of answers.",
    learning_target: "I can solve a several-step problem and know what to do with a remainder.",
    skills: ["Multistep Problems", "Remainders", "Reasonableness"],
    science_tags: ["interleaving", "elaboration"],
    match_keys: ["multistep word problems", "remainders", "four operations", "reasonableness", "estimation"],
  },
  {
    code: "5.NF.B.4",
    name: "Multiply a fraction by a fraction",
    plain_reading:
      "Apply and extend previous understandings of multiplication to multiply a fraction or whole number by a fraction, including finding the area of a rectangle with fractional side lengths.",
    learning_target: "I can multiply fractions and explain why the answer gets smaller.",
    skills: ["Fraction Multiplication", "Area Model", "Scaling"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["multiply fractions", "fraction of a fraction", "area model", "fractional side lengths"],
  },
  {
    code: "6.G.A.1",
    name: "Find area by composing and decomposing",
    plain_reading:
      "Find the area of right triangles, other triangles, special quadrilaterals, and polygons by composing into rectangles or decomposing into triangles, and apply these techniques to real-world problems.",
    learning_target: "I can find the area of an awkward shape by cutting it into easy ones.",
    skills: ["Area", "Decomposition", "Polygons"],
    science_tags: ["dual-coding", "interleaving"],
    match_keys: ["area of triangles", "trapezoid", "composite shapes", "decompose", "polygons"],
  },
  {
    code: "7.EE.A.1",
    name: "Add, factor and expand linear expressions",
    plain_reading:
      "Apply properties of operations as strategies to add, subtract, factor, and expand linear expressions with rational coefficients.",
    learning_target: "I can rewrite an expression in a different but equal form.",
    skills: ["Expressions", "Distributive Property", "Factoring"],
    science_tags: ["interleaving", "elaboration"],
    match_keys: ["expand", "factor", "linear expressions", "distributive property", "like terms", "equivalent"],
  },
  {
    code: "8.NS.A.1",
    name: "Tell rational numbers from irrational ones",
    plain_reading:
      "Know that numbers that are not rational are called irrational, and understand informally that every number has a decimal expansion — repeating or terminating for rational numbers.",
    learning_target: "I can tell whether a number can be written as a fraction, and say how I know.",
    skills: ["Rational Numbers", "Irrational Numbers", "Decimal Expansion"],
    science_tags: ["elaboration", "dual-coding"],
    match_keys: ["irrational numbers", "rational numbers", "repeating decimal", "terminating", "square roots", "pi"],
  },
  {
    code: "8.SP.A.1",
    name: "Read a scatter plot for association",
    plain_reading:
      "Construct and interpret scatter plots for bivariate measurement data to investigate patterns of association between two quantities, describing clustering, outliers, and the form and direction of any association.",
    learning_target: "I can plot two measurements together and describe how they relate.",
    skills: ["Scatter Plots", "Bivariate Data", "Association"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["scatter plot", "association", "correlation", "bivariate data", "outliers", "clustering"],
  },
];

const unpacksData = [
  {
    standard_code: "RI.K.1",
    verbs: [
      { word: "Ask", gloss: "wonder something about the book" },
      { word: "Answer", gloss: "say what the book told you" },
    ],
    concepts: ["Key details", "Real information", "Questioning"],
    vocabulary: [
      { term: "real", definition: "something that actually happens or exists" },
      { term: "fact", definition: "something true the book tells you" },
      { term: "question", definition: "something you ask to find out more" },
      { term: "photograph", definition: "a picture of something real" },
    ],
    prior_skills: ["Listen to a read-aloud", "Talk about pictures", "Ask questions aloud"],
    prior_standards: [{ code: "PK.RI.1", text: "Respond to questions about an informational read-aloud" }],
    future_standards: [{ code: "RI.1.1", text: "Ask and answer questions about key details in a text" }],
    challenges: [
      { problem: "Answers come from what they already knew", fix: "Ask 'did the book say that?'" },
      { problem: "Story and information books are treated the same", fix: "Sort books by whether they show photographs or drawings" },
    ],
    mastery_statement: "Student can ask and answer questions about key details in an informational read-aloud with support.",
    ladder: [
      { name: "I can listen to a true book", descriptor: "Attends to informational text" },
      { name: "I can tell one thing I learned", descriptor: "Recalls a fact" },
      { name: "I can answer a question about it", descriptor: "Responds from the text" },
      { name: "I can ask my own question", descriptor: "Poses a relevant question" },
    ],
  },
  {
    standard_code: "RF.1.3",
    verbs: [
      { word: "Know", gloss: "hold the letter patterns in memory" },
      { word: "Apply", gloss: "use them on a word you have not seen" },
      { word: "Decode", gloss: "read a word from its letters" },
    ],
    concepts: ["Digraphs", "Silent e", "Syllables"],
    vocabulary: [
      { term: "digraph", definition: "two letters making one sound, like sh" },
      { term: "silent e", definition: "an e at the end that changes the vowel and says nothing" },
      { term: "vowel team", definition: "two vowels working together for one sound" },
      { term: "syllable", definition: "a chunk of a word with one vowel sound" },
    ],
    prior_skills: ["Blend and segment sounds", "Know consonant and short vowel sounds", "Read CVC words"],
    prior_standards: [{ code: "RF.K.3", text: "Know and apply kindergarten phonics skills" }],
    future_standards: [{ code: "RF.2.3", text: "Know and apply grade 2 phonics and word analysis skills" }],
    challenges: [
      { problem: "Digraph letters are sounded separately — s-h for sh", fix: "Underline digraphs as one unit before reading" },
      { problem: "Silent e is sounded out", fix: "Contrast pairs like cap and cape side by side" },
    ],
    mastery_statement: "Student can decode grade 1 words using digraphs, silent e, vowel teams and syllable counting.",
    ladder: [
      { name: "I can read short vowel words", descriptor: "Decodes CVC reliably" },
      { name: "I can read digraphs as one sound", descriptor: "Treats sh, ch, th as units" },
      { name: "I can use silent e", descriptor: "Reads cape, bike, note" },
      { name: "I can split a longer word into chunks", descriptor: "Counts syllables to decode" },
    ],
  },
  {
    standard_code: "RL.2.5",
    verbs: [
      { word: "Describe", gloss: "explain how the story is built" },
      { word: "Introduce", gloss: "set up who and where at the start" },
      { word: "Conclude", gloss: "finish off the action at the end" },
    ],
    concepts: ["Story shape", "Openings", "Endings"],
    vocabulary: [
      { term: "beginning", definition: "the part that sets the story up" },
      { term: "ending", definition: "the part that finishes the action" },
      { term: "introduce", definition: "tell the reader about something for the first time" },
      { term: "structure", definition: "the way something is put together" },
    ],
    prior_skills: ["Retell a story in order", "Identify characters and setting", "Name the problem in a story"],
    prior_standards: [{ code: "RL.1.3", text: "Describe characters, settings, and major events" }],
    future_standards: [{ code: "RL.3.5", text: "Refer to parts of stories using terms like chapter and scene" }],
    challenges: [
      { problem: "The 'beginning' is retold rather than described", fix: "Ask what job it does, not what happens in it" },
      { problem: "Any last event counts as the ending", fix: "Ask whether the problem is actually resolved" },
    ],
    mastery_statement: "Student can describe what a story's beginning sets up and how its ending resolves the action.",
    ladder: [
      { name: "I can retell the story", descriptor: "Recounts events in order" },
      { name: "I can find the beginning and ending", descriptor: "Locates the parts" },
      { name: "I can say what the beginning sets up", descriptor: "Describes its function" },
      { name: "I can say how the ending finishes it", descriptor: "Links ending to problem" },
    ],
  },
  {
    standard_code: "W.3.1",
    verbs: [
      { word: "Support", gloss: "back your view with reasons" },
      { word: "Introduce", gloss: "tell the reader what this is about" },
      { word: "Organize", gloss: "put reasons in a sensible order" },
    ],
    concepts: ["Point of view", "Organizational structure", "Linking words"],
    vocabulary: [
      { term: "opinion", definition: "what you think about something" },
      { term: "reason", definition: "why you think it" },
      { term: "linking word", definition: "a word like because or also that joins ideas" },
      { term: "conclusion", definition: "the ending that sums up your view" },
    ],
    prior_skills: ["State an opinion with two reasons", "Use linking words", "Write a closing sentence"],
    prior_standards: [{ code: "W.2.1", text: "Write opinion pieces with reasons and a conclusion" }],
    future_standards: [{ code: "W.4.1", text: "Write opinion pieces with grouped, supported reasons" }],
    challenges: [
      { problem: "Reasons arrive in whatever order they were thought of", fix: "Cut them up and physically rearrange before drafting" },
      { problem: "The opinion is restated instead of concluded", fix: "Teach a conclusion that answers 'so what?'" },
    ],
    mastery_statement: "Student can write an opinion piece with an introduction, ordered reasons, linking words and a conclusion.",
    ladder: [
      { name: "I can state an opinion", descriptor: "Writes a clear position" },
      { name: "I can give reasons", descriptor: "Supplies two or more" },
      { name: "I can order them deliberately", descriptor: "Sequences for effect" },
      { name: "I can link and conclude", descriptor: "Uses linking words and a real ending" },
    ],
  },
  {
    standard_code: "RI.4.3",
    verbs: [
      { word: "Explain", gloss: "say what happened and why" },
      { word: "Base", gloss: "ground it in specific text information" },
    ],
    concepts: ["Causation", "Procedures", "Specific information"],
    vocabulary: [
      { term: "procedure", definition: "the steps for doing something" },
      { term: "cause", definition: "the reason something happened" },
      { term: "effect", definition: "what happened as a result" },
      { term: "specific", definition: "exact rather than general" },
    ],
    prior_skills: ["Identify cause and effect", "Locate details in nonfiction", "Sequence steps"],
    prior_standards: [{ code: "RI.3.3", text: "Describe the relationship between events or steps in a text" }],
    future_standards: [{ code: "RI.5.3", text: "Explain relationships between individuals, events and ideas" }],
    challenges: [
      { problem: "What happened is given without why", fix: "Require every answer to contain the word because" },
      { problem: "The why comes from prior knowledge", fix: "Require the sentence in the text that supplies it" },
    ],
    mastery_statement: "Student can explain events or procedures including their causes, grounded in specific text information.",
    ladder: [
      { name: "I can say what happened", descriptor: "Recounts the event" },
      { name: "I can put steps in order", descriptor: "Sequences a procedure" },
      { name: "I can say why it happened", descriptor: "Identifies the cause" },
      { name: "I can point to the text that says so", descriptor: "Cites specific information" },
    ],
  },
  {
    standard_code: "L.4.1",
    verbs: [
      { word: "Demonstrate", gloss: "show it in your own writing" },
      { word: "Use", gloss: "apply the convention correctly" },
    ],
    concepts: ["Verb tense", "Pronouns", "Prepositional phrases"],
    vocabulary: [
      { term: "relative pronoun", definition: "a word like who or which that starts a describing clause" },
      { term: "progressive tense", definition: "a verb form for something ongoing, like was walking" },
      { term: "modal", definition: "a helper verb like can, may or must" },
      { term: "prepositional phrase", definition: "a phrase starting with a word like in, on or under" },
    ],
    prior_skills: ["Write complete sentences", "Use past and present tense", "Identify nouns and verbs"],
    prior_standards: [{ code: "L.3.1", text: "Explain the function of parts of speech in sentences" }],
    future_standards: [{ code: "L.5.1", text: "Demonstrate command of grade 5 grammar conventions" }],
    challenges: [
      { problem: "Tense shifts mid-paragraph", fix: "Highlight every verb in a draft and check they agree" },
      { problem: "Grammar is correct in exercises but not in writing", fix: "Edit their own drafts rather than worksheet sentences" },
    ],
    mastery_statement: "Student can use grade 4 grammar conventions accurately in their own writing and speech.",
    ladder: [
      { name: "I can write complete sentences", descriptor: "Subject and verb agree" },
      { name: "I can keep tense consistent", descriptor: "No unintended shifts" },
      { name: "I can use describing clauses", descriptor: "Applies relative pronouns" },
      { name: "I can fix my own grammar", descriptor: "Self-edits a draft" },
    ],
  },
  {
    standard_code: "SL.5.4",
    verbs: [
      { word: "Report", gloss: "present what you found out" },
      { word: "Sequence", gloss: "order ideas so they build" },
      { word: "Support", gloss: "back main ideas with detail" },
    ],
    concepts: ["Logical sequence", "Supporting detail", "Delivery"],
    vocabulary: [
      { term: "sequence", definition: "the order ideas come in" },
      { term: "main idea", definition: "the most important point" },
      { term: "pace", definition: "how fast you speak" },
      { term: "relevant", definition: "actually connected to the point" },
    ],
    prior_skills: ["Speak audibly to a group", "Organize ideas in writing", "Select supporting details"],
    prior_standards: [{ code: "SL.4.4", text: "Report on a topic with appropriate facts and details" }],
    future_standards: [{ code: "SL.6.4", text: "Present claims and findings with pertinent descriptions and examples" }],
    challenges: [
      { problem: "Everything found gets said, in the order it was found", fix: "Plan three points and cut the rest" },
      { problem: "Delivery rushes when nervous", fix: "Mark pause points in the notes" },
    ],
    mastery_statement: "Student can present a topic in a logical sequence with relevant supporting details, spoken clearly.",
    ladder: [
      { name: "I can say what I found out", descriptor: "Reports content" },
      { name: "I can choose my main points", descriptor: "Selects rather than dumps" },
      { name: "I can order them logically", descriptor: "Sequences deliberately" },
      { name: "I can speak at a good pace", descriptor: "Controls delivery" },
    ],
  },
  {
    standard_code: "RL.6.4",
    verbs: [
      { word: "Determine", gloss: "work out what a word means here" },
      { word: "Analyze", gloss: "examine the effect of the choice" },
    ],
    concepts: ["Connotation", "Tone", "Word choice"],
    vocabulary: [
      { term: "connotation", definition: "the feeling a word carries beyond its plain meaning" },
      { term: "denotation", definition: "a word's plain dictionary meaning" },
      { term: "tone", definition: "the writer's attitude, heard in the words" },
      { term: "diction", definition: "the particular words a writer chooses" },
    ],
    prior_skills: ["Use context clues", "Identify figurative language", "Distinguish shades of meaning"],
    prior_standards: [{ code: "RL.5.4", text: "Determine the meaning of words and phrases, including figurative language" }],
    future_standards: [{ code: "RL.7.4", text: "Analyze the impact of rhymes and repetitions of sound" }],
    challenges: [
      { problem: "Word choice is described as 'good' with no reason", fix: "Swap in a synonym and name what changes" },
      { problem: "Tone is confused with mood", fix: "Ask whose feeling it is — writer's or reader's" },
    ],
    mastery_statement: "Student can explain a word's meaning in context and analyze how the choice shapes tone.",
    ladder: [
      { name: "I can work out the meaning in context", descriptor: "Uses surrounding text" },
      { name: "I can spot figurative use", descriptor: "Identifies non-literal meaning" },
      { name: "I can describe the tone", descriptor: "Names the writer's attitude" },
      { name: "I can explain why that word", descriptor: "Compares against alternatives" },
    ],
  },
  {
    standard_code: "RI.7.6",
    verbs: [
      { word: "Determine", gloss: "work out the author's position" },
      { word: "Analyze", gloss: "examine how they set it apart" },
      { word: "Distinguish", gloss: "separate their view from others" },
    ],
    concepts: ["Author's purpose", "Position", "Acknowledging other views"],
    vocabulary: [
      { term: "point of view", definition: "what the author thinks about the subject" },
      { term: "purpose", definition: "why the author wrote it" },
      { term: "position", definition: "the stance the author takes" },
      { term: "distinguish", definition: "show how one thing differs from another" },
    ],
    prior_skills: ["Identify author's purpose", "Trace an argument", "Distinguish fact from opinion"],
    prior_standards: [{ code: "RI.6.6", text: "Determine an author's point of view and explain how it is conveyed" }],
    future_standards: [{ code: "RI.8.6", text: "Analyze how an author responds to conflicting evidence" }],
    challenges: [
      { problem: "Author's view is assumed to be the reader's", fix: "Analyze a text the class disagrees with" },
      { problem: "Purpose is given as 'to inform' regardless", fix: "Require a purpose specific enough to be arguable" },
    ],
    mastery_statement: "Student can identify an author's position and explain how the text distinguishes it from other views.",
    ladder: [
      { name: "I can say what the text is about", descriptor: "Identifies subject" },
      { name: "I can say what the author thinks", descriptor: "Identifies position" },
      { name: "I can find where other views appear", descriptor: "Locates opposing positions" },
      { name: "I can explain how they are set apart", descriptor: "Analyzes the distinction" },
    ],
  },
  {
    standard_code: "W.7.1",
    verbs: [
      { word: "Support", gloss: "back the claim with evidence" },
      { word: "Acknowledge", gloss: "admit other claims exist" },
      { word: "Organize", gloss: "order reasons so they build" },
    ],
    concepts: ["Claim", "Alternate claims", "Logical order"],
    vocabulary: [
      { term: "claim", definition: "the position you are arguing" },
      { term: "alternate claim", definition: "a different position someone might hold" },
      { term: "relevant", definition: "actually supporting the claim made" },
      { term: "logical order", definition: "an arrangement where each point sets up the next" },
    ],
    prior_skills: ["State a claim", "Support with evidence", "Group related reasons"],
    prior_standards: [{ code: "W.6.1", text: "Write arguments to support claims with clear reasons and evidence" }],
    future_standards: [{ code: "W.8.1", text: "Write arguments distinguishing claims from opposing claims" }],
    challenges: [
      { problem: "The other side is mentioned and ignored", fix: "Require a response, not just an acknowledgement" },
      { problem: "Reasons are listed rather than ordered", fix: "Test whether swapping two changes anything — if not, they are not ordered" },
    ],
    mastery_statement: "Student can argue a claim with relevant evidence, acknowledge alternate claims, and organize reasons logically.",
    ladder: [
      { name: "I can state a claim", descriptor: "Writes an arguable position" },
      { name: "I can support it with evidence", descriptor: "Supplies relevant support" },
      { name: "I can acknowledge another view", descriptor: "States an alternate claim" },
      { name: "I can order my reasons deliberately", descriptor: "Sequences for cumulative effect" },
    ],
  },
  {
    standard_code: "K.NBT.A.1",
    verbs: [
      { word: "Compose", gloss: "put ten and some more together" },
      { word: "Decompose", gloss: "break a teen number into ten and some more" },
    ],
    concepts: ["Teen numbers", "Ten as a unit", "Recording with equations"],
    vocabulary: [
      { term: "ten", definition: "a group of ten ones" },
      { term: "teen number", definition: "a number from 11 to 19" },
      { term: "some more", definition: "the extra ones after the ten" },
      { term: "equation", definition: "a number sentence with an equals sign" },
    ],
    prior_skills: ["Count to 20", "Count objects accurately", "Recognize numerals to 19"],
    prior_standards: [{ code: "K.CC.B.4", text: "Connect counting to cardinality" }],
    future_standards: [{ code: "1.NBT.B.2", text: "Understand two-digit place value" }],
    challenges: [
      { problem: "Teen numbers are said backwards — fourteen written as 41", fix: "Build with a ten-frame and count the ten first" },
      { problem: "Teens are counted one by one every time", fix: "Show the full ten-frame and count on from ten" },
    ],
    mastery_statement: "Student can show a teen number as one ten and some further ones, with objects and an equation.",
    ladder: [
      { name: "I can count to 19", descriptor: "Accurate sequence" },
      { name: "I can fill a ten-frame", descriptor: "Makes a ten" },
      { name: "I can say ten and four more", descriptor: "Decomposes a teen number" },
      { name: "I can write 14 = 10 + 4", descriptor: "Records with an equation" },
    ],
  },
  {
    standard_code: "1.OA.B.3",
    verbs: [
      { word: "Apply", gloss: "use a property to make adding easier" },
      { word: "Reorder", gloss: "change the order to suit yourself" },
    ],
    concepts: ["Commutativity", "Associativity", "Strategic grouping"],
    vocabulary: [
      { term: "order", definition: "which number comes first" },
      { term: "group", definition: "which two you add first" },
      { term: "strategy", definition: "a smart way of working something out" },
      { term: "sum", definition: "the answer to an addition" },
    ],
    prior_skills: ["Add within 10", "Know pairs making ten", "Count on from a number"],
    prior_standards: [{ code: "K.OA.A.1", text: "Represent addition and subtraction" }],
    future_standards: [{ code: "2.OA.B.2", text: "Fluently add and subtract within 20" }],
    challenges: [
      { problem: "Numbers are always added left to right", fix: "Show 2 + 9 solved as 9 + 2 and time both" },
      { problem: "Regrouping three addends is not attempted", fix: "Highlight pairs making ten before adding" },
    ],
    mastery_statement: "Student can reorder and regroup addends to make an addition easier, and explain why it is allowed.",
    ladder: [
      { name: "I can add two numbers", descriptor: "Computes a sum" },
      { name: "I know order does not matter", descriptor: "Applies commutativity" },
      { name: "I can start with the bigger number", descriptor: "Counts on efficiently" },
      { name: "I can find a ten first", descriptor: "Regroups three addends" },
    ],
  },
  {
    standard_code: "2.NBT.B.5",
    verbs: [
      { word: "Add", gloss: "combine two-digit numbers" },
      { word: "Subtract", gloss: "find the difference" },
      { word: "Choose", gloss: "pick a strategy that suits the numbers" },
    ],
    concepts: ["Place value strategies", "Regrouping", "Addition and subtraction as inverses"],
    vocabulary: [
      { term: "regroup", definition: "trade ten ones for a ten, or the other way" },
      { term: "strategy", definition: "a method that suits these particular numbers" },
      { term: "difference", definition: "the answer to a subtraction" },
      { term: "inverse", definition: "the operation that undoes another" },
    ],
    prior_skills: ["Understand two-digit place value", "Add within 20 fluently", "Count on and back by tens"],
    prior_standards: [{ code: "2.NBT.A.1", text: "Understand three-digit place value" }],
    future_standards: [{ code: "3.NBT.A.2", text: "Fluently add and subtract within 1000" }],
    challenges: [
      { problem: "Regrouping is skipped and digits subtracted the easy way round", fix: "Model with base ten blocks so the trade is physical" },
      { problem: "One algorithm is used regardless of the numbers", fix: "Ask which strategy fits before solving" },
    ],
    mastery_statement: "Student can add and subtract within 100 fluently, choosing a strategy suited to the numbers.",
    ladder: [
      { name: "I can add tens to tens", descriptor: "Handles multiples of ten" },
      { name: "I can add without regrouping", descriptor: "Two-digit sums under ten ones" },
      { name: "I can regroup when I need to", descriptor: "Trades correctly" },
      { name: "I can pick the best strategy", descriptor: "Chooses to suit the numbers" },
    ],
  },
  {
    standard_code: "3.G.A.1",
    verbs: [
      { word: "Understand", gloss: "see how categories overlap" },
      { word: "Recognize", gloss: "identify examples of a category" },
      { word: "Classify", gloss: "sort by shared attributes" },
    ],
    concepts: ["Attributes", "Nested categories", "Quadrilaterals"],
    vocabulary: [
      { term: "attribute", definition: "something a shape has, like four sides" },
      { term: "quadrilateral", definition: "any shape with four straight sides" },
      { term: "rhombus", definition: "a quadrilateral with four equal sides" },
      { term: "category", definition: "a group of things sharing something" },
    ],
    prior_skills: ["Name common shapes", "Count sides and corners", "Sort shapes by one attribute"],
    prior_standards: [{ code: "2.G.A.1", text: "Recognize and draw shapes with specified attributes" }],
    future_standards: [{ code: "4.G.A.2", text: "Classify two-dimensional figures by properties of their lines and angles" }],
    challenges: [
      { problem: "A square is not accepted as a rectangle", fix: "Check the definition attribute by attribute rather than by look" },
      { problem: "Shapes are sorted by appearance, not attributes", fix: "Sort with the shapes face down, using written attributes only" },
    ],
    mastery_statement: "Student can classify shapes by shared attributes and recognize that categories can contain one another.",
    ladder: [
      { name: "I can name shapes", descriptor: "Uses correct vocabulary" },
      { name: "I can list a shape's attributes", descriptor: "Counts sides and angles" },
      { name: "I can sort by a shared attribute", descriptor: "Groups by property" },
      { name: "I know a square is also a rectangle", descriptor: "Understands nested categories" },
    ],
  },
  {
    standard_code: "4.OA.A.3",
    verbs: [
      { word: "Solve", gloss: "work through several steps" },
      { word: "Interpret", gloss: "decide what the remainder means" },
      { word: "Assess", gloss: "judge whether the answer is sensible" },
    ],
    concepts: ["Multistep problems", "Remainder interpretation", "Estimation"],
    vocabulary: [
      { term: "remainder", definition: "what is left over after dividing" },
      { term: "multistep", definition: "needing more than one calculation" },
      { term: "interpret", definition: "decide what it means for this situation" },
      { term: "estimate", definition: "a close-enough answer to check against" },
    ],
    prior_skills: ["Solve two-step problems", "Divide with remainders", "Round to estimate"],
    prior_standards: [{ code: "3.OA.D.8", text: "Solve two-step word problems using the four operations" }],
    future_standards: [{ code: "5.NF.B.6", text: "Solve real-world problems involving multiplication of fractions" }],
    challenges: [
      { problem: "The remainder is reported without thought — 4 remainder 2 buses", fix: "Ask what the remainder is, in the story's own terms" },
      { problem: "One step is dropped in longer problems", fix: "Number the steps before calculating anything" },
    ],
    mastery_statement: "Student can solve multistep problems and interpret a remainder correctly for the situation.",
    ladder: [
      { name: "I can solve a two-step problem", descriptor: "Handles two operations" },
      { name: "I can plan several steps", descriptor: "Numbers the steps first" },
      { name: "I can divide with a remainder", descriptor: "Computes correctly" },
      { name: "I can say what the remainder means here", descriptor: "Interprets in context" },
    ],
  },
  {
    standard_code: "5.NF.B.4",
    verbs: [
      { word: "Multiply", gloss: "find a fraction of an amount" },
      { word: "Interpret", gloss: "say what the multiplication means" },
    ],
    concepts: ["Fraction of a fraction", "Area model", "Scaling"],
    vocabulary: [
      { term: "of", definition: "in fraction problems, this means multiply" },
      { term: "area model", definition: "a rectangle split to show multiplication" },
      { term: "scaling", definition: "making something larger or smaller by a factor" },
      { term: "product", definition: "the answer to a multiplication" },
    ],
    prior_skills: ["Multiply whole numbers", "Understand fractions as parts", "Find area of a rectangle"],
    prior_standards: [{ code: "4.NF.B.4", text: "Multiply a fraction by a whole number" }],
    future_standards: [{ code: "6.NS.A.1", text: "Divide fractions by fractions" }],
    challenges: [
      { problem: "The answer is expected to be bigger, because multiplying", fix: "Fold paper to show a half of a half is a quarter" },
      { problem: "Numerators and denominators are cross-multiplied", fix: "Use the area model until the straight-across rule is obvious" },
    ],
    mastery_statement: "Student can multiply fractions, model the product as an area, and explain why it can be smaller than either factor.",
    ladder: [
      { name: "I can multiply a fraction by a whole number", descriptor: "Repeated addition" },
      { name: "I can find a fraction of a fraction", descriptor: "Uses a model" },
      { name: "I can multiply two fractions", descriptor: "Applies the procedure" },
      { name: "I can explain why it gets smaller", descriptor: "Reasons about scaling" },
    ],
  },
  {
    standard_code: "6.G.A.1",
    verbs: [
      { word: "Compose", gloss: "build a shape into a rectangle" },
      { word: "Decompose", gloss: "cut a shape into triangles" },
      { word: "Apply", gloss: "use it on a real problem" },
    ],
    concepts: ["Area of triangles", "Composite shapes", "Decomposition"],
    vocabulary: [
      { term: "decompose", definition: "cut a shape into simpler ones" },
      { term: "trapezoid", definition: "a quadrilateral with one pair of parallel sides" },
      { term: "base", definition: "the side a height is measured from" },
      { term: "height", definition: "the perpendicular distance to the base" },
    ],
    prior_skills: ["Find area of rectangles", "Identify polygons", "Multiply and divide fluently"],
    prior_standards: [{ code: "3.MD.C.7", text: "Relate area to multiplication and addition" }],
    future_standards: [{ code: "7.G.B.6", text: "Solve problems involving area, volume and surface area" }],
    challenges: [
      { problem: "A slanted side is used as the height", fix: "Draw the perpendicular explicitly before computing" },
      { problem: "Composite shapes are attacked whole", fix: "Draw the dividing line first, always" },
    ],
    mastery_statement: "Student can find the area of triangles and composite polygons by composing or decomposing them.",
    ladder: [
      { name: "I can find the area of a rectangle", descriptor: "Applies the formula" },
      { name: "I can find the area of a triangle", descriptor: "Halves the rectangle" },
      { name: "I can identify the height correctly", descriptor: "Uses the perpendicular" },
      { name: "I can break a polygon apart", descriptor: "Decomposes and sums" },
    ],
  },
  {
    standard_code: "7.EE.A.1",
    verbs: [
      { word: "Expand", gloss: "multiply out the brackets" },
      { word: "Factor", gloss: "pull a common factor out" },
      { word: "Combine", gloss: "collect like terms" },
    ],
    concepts: ["Equivalent expressions", "Distributive property", "Like terms"],
    vocabulary: [
      { term: "expand", definition: "multiply out to remove brackets" },
      { term: "factor", definition: "pull out what the terms have in common" },
      { term: "like terms", definition: "terms with the same variable part" },
      { term: "equivalent", definition: "different-looking but always equal" },
    ],
    prior_skills: ["Evaluate expressions", "Apply the distributive property", "Operate with rational numbers"],
    prior_standards: [{ code: "6.EE.A.3", text: "Apply properties of operations to generate equivalent expressions" }],
    future_standards: [{ code: "8.EE.C.7", text: "Solve linear equations in one variable" }],
    challenges: [
      { problem: "The negative outside a bracket is not distributed", fix: "Rewrite subtraction as adding a negative first" },
      { problem: "Unlike terms are combined — 3x + 2 becomes 5x", fix: "Say the terms aloud with units: three x's plus two ones" },
    ],
    mastery_statement: "Student can expand, factor and simplify linear expressions and show the result is equivalent.",
    ladder: [
      { name: "I can combine like terms", descriptor: "Simplifies correctly" },
      { name: "I can expand a bracket", descriptor: "Distributes across terms" },
      { name: "I can handle a negative outside", descriptor: "Distributes the sign" },
      { name: "I can factor an expression", descriptor: "Pulls out a common factor" },
    ],
  },
  {
    standard_code: "8.NS.A.1",
    verbs: [
      { word: "Know", gloss: "recognize which numbers are irrational" },
      { word: "Convert", gloss: "turn a repeating decimal into a fraction" },
    ],
    concepts: ["Rational numbers", "Irrational numbers", "Decimal expansion"],
    vocabulary: [
      { term: "rational", definition: "able to be written as a fraction" },
      { term: "irrational", definition: "impossible to write as a fraction" },
      { term: "terminating", definition: "a decimal that stops" },
      { term: "repeating", definition: "a decimal with a pattern going on forever" },
    ],
    prior_skills: ["Convert fractions to decimals", "Work with square roots", "Order rational numbers"],
    prior_standards: [{ code: "7.NS.A.2", text: "Multiply and divide rational numbers" }],
    future_standards: [{ code: "N-RN.3", text: "Explain why sums and products of rational and irrational numbers behave as they do" }],
    challenges: [
      { problem: "Any long decimal is called irrational", fix: "Test for a repeating pattern before deciding" },
      { problem: "3.14 is treated as equal to pi", fix: "Show more digits and note the pattern never settles" },
    ],
    mastery_statement: "Student can classify a number as rational or irrational and justify it from its decimal expansion.",
    ladder: [
      { name: "I can convert a fraction to a decimal", descriptor: "Divides accurately" },
      { name: "I can spot a repeating pattern", descriptor: "Identifies recurrence" },
      { name: "I can classify a number", descriptor: "Rational or irrational" },
      { name: "I can explain how I know", descriptor: "Justifies from the expansion" },
    ],
  },
  {
    standard_code: "8.SP.A.1",
    verbs: [
      { word: "Construct", gloss: "plot the two measurements together" },
      { word: "Interpret", gloss: "describe the pattern you see" },
    ],
    concepts: ["Bivariate data", "Association", "Outliers and clustering"],
    vocabulary: [
      { term: "scatter plot", definition: "a graph plotting two measurements for each thing" },
      { term: "association", definition: "a pattern linking two quantities" },
      { term: "outlier", definition: "a point far from the rest" },
      { term: "cluster", definition: "a group of points bunched together" },
    ],
    prior_skills: ["Plot on a coordinate plane", "Summarize a data set", "Interpret a line graph"],
    prior_standards: [{ code: "6.SP.B.5", text: "Summarize numerical data sets in relation to their context" }],
    future_standards: [{ code: "8.SP.A.2", text: "Fit a straight line to a scatter plot and assess the fit" }],
    challenges: [
      { problem: "Points are joined up like a line graph", fix: "Say aloud that each point is a separate thing measured twice" },
      { problem: "Association is read as cause", fix: "Find a pair that clearly correlates without causing" },
    ],
    mastery_statement: "Student can construct a scatter plot and describe the form, direction, clustering and outliers.",
    ladder: [
      { name: "I can plot paired measurements", descriptor: "Constructs the plot" },
      { name: "I can describe the direction", descriptor: "Positive or negative" },
      { name: "I can spot outliers and clusters", descriptor: "Identifies features" },
      { name: "I know association is not cause", descriptor: "Reasons carefully" },
    ],
  },
];

const blueprintsData = [
  {
    standard_code: "RI.K.1",
    title: "Books That Tell Us Real Things",
    badge: "Kindergarten",
    route_name: "Interactive Read-Aloud",
    route_line: "Sort real from story → Wonder aloud → Answer from the book",
    success_criteria: ["Tells a true book from a story", "Asks a question about the topic", "Answers using what the book said"],
    steps: [
      { name: "Retrieve Yesterday's Facts", minutes: 5, body: "What did we learn from yesterday's book? Oral recall builds the habit of holding information.", science_tag: "retrieval" },
      { name: "Real or Made Up", minutes: 8, body: "Sort six books. Photographs usually mean real. The sort defines the genre without defining it.", science_tag: "dual-coding" },
      { name: "Model Wondering", minutes: 8, body: "Read a page, stop, say 'I wonder how they do that'. Wondering about facts sounds different from wondering about stories.", science_tag: "elaboration" },
      { name: "Turn and Wonder", minutes: 10, body: "Stop three times. Partners share a question each time. Everybody talks, every time.", science_tag: "collaborative" },
      { name: "Did the Book Say It?", minutes: 10, body: "Take answers and check them against the page. Some will be things they already knew — name that difference gently.", science_tag: "elaboration" },
      { name: "Draw What You Learned", minutes: 10, body: "Students draw one fact from the book. Drawing lets them record what they cannot yet write.", science_tag: "dual-coding" },
      { name: "Share Three Facts", minutes: 4, body: "Three children share, each pointing at the page it came from.", science_tag: "spaced" },
    ],
    ef_supports: ["Book sorting set", "Stop points marked in the book", "Turn-and-talk before whole group", "Draw instead of write"],
    tech: "Informational big book with photographs",
    tech_purpose: "Photographs signal real, and everyone can see the page",
    ai_prompts: ["Write a kindergarten informational read-aloud on a familiar topic", "Generate questions answerable from a given page"],
    assessment: ["Check the genre sort", "Listen for prior knowledge given as text content", "Drawings must show a fact from the book"],
    why_it_works: ["Photographs are a concrete signal children can use themselves", "Checking against the page builds text-based answering early", "Drawing removes writing as a barrier", "Wondering about facts is a different move from wondering about stories"],
  },
  {
    standard_code: "RF.1.3",
    title: "Patterns That Unlock Longer Words",
    badge: "Grade 1",
    route_name: "Explicit Instruction",
    route_line: "Teach the pattern → Sort and read → Meet it in a book",
    success_criteria: ["Reads digraphs as one sound", "Applies silent e correctly", "Splits a longer word into syllables to read it"],
    steps: [
      { name: "Sound Drill", minutes: 5, body: "Flash taught patterns. Students say sounds. Daily, fast, no reteaching.", science_tag: "retrieval" },
      { name: "Two Letters, One Sound", minutes: 10, body: "Introduce a digraph. Underline it as a single unit before reading any word containing it.", science_tag: "dual-coding" },
      { name: "Silent E Changes Everything", minutes: 12, body: "Cap and cape, side by side. Add the e and watch the vowel change. The pair does the teaching.", science_tag: "elaboration" },
      { name: "Word Sort", minutes: 10, body: "Sort words by pattern before reading any of them. Sorting forces attention to spelling.", science_tag: "interleaving" },
      { name: "Chunk the Long Ones", minutes: 10, body: "Clap syllables, then read chunk by chunk. Longer words stop being frightening when they come apart.", science_tag: "dual-coding" },
      { name: "Read a Real Book", minutes: 10, body: "Decodable text loaded with today's pattern. Cover the pictures. Prompt with 'what pattern do you see?'", science_tag: "interleaving" },
      { name: "Exit Words", minutes: 3, body: "Five words including two never taught but built from the pattern.", science_tag: "spaced" },
    ],
    ef_supports: ["Underline digraphs before reading", "Minimal pairs for silent e", "Word sort mats", "Syllable clapping"],
    tech: "Word cards and a decodable book",
    tech_purpose: "Physical sorting before reading",
    ai_prompts: ["Generate minimal pairs for silent e", "Write a decodable grade 1 passage using target digraphs"],
    assessment: ["Check digraphs are read as one sound", "Confirm silent e is applied", "Exit words include untaught transfer words"],
    why_it_works: ["Underlining the digraph prevents sounding both letters", "Minimal pairs make silent e's effect impossible to miss", "Syllable chunking makes long words tractable", "Untaught transfer words test the pattern rather than memory"],
  },
  {
    standard_code: "RL.2.5",
    title: "How Stories Start and Finish",
    badge: "Grade 2",
    route_name: "Explicit Instruction",
    route_line: "Name the parts → Say what each does → Test the ending",
    success_criteria: ["Identifies the beginning and ending", "Says what the beginning sets up", "Explains how the ending resolves the problem"],
    steps: [
      { name: "Retrieve Story Elements", minutes: 5, body: "Character, setting, problem for a known story. The parts before the shape.", science_tag: "retrieval" },
      { name: "Beginnings Do a Job", minutes: 10, body: "Read three openings. What does each set up? Job, not content — the distinction is the lesson.", science_tag: "elaboration" },
      { name: "Endings Finish Something", minutes: 10, body: "Read three endings. What problem does each resolve? Match endings to the problems they close.", science_tag: "elaboration" },
      { name: "The Wrong Ending", minutes: 12, body: "Give a story an ending that resolves nothing. Students say what is missing. The failure teaches faster than the rule.", science_tag: "dual-coding" },
      { name: "Map a Whole Story", minutes: 10, body: "Three boxes: what the beginning sets up, what happens, how it is resolved.", science_tag: "collaborative" },
      { name: "Write a Better Ending", minutes: 8, body: "Students rewrite the broken ending so it actually closes the problem.", science_tag: "interleaving" },
      { name: "Share Two Endings", minutes: 5, body: "Two students read theirs. Class checks the problem is genuinely resolved.", science_tag: "spaced" },
    ],
    ef_supports: ["Three-box story map", "Openings and endings on separate cards", "Deliberately broken ending", "Sentence frames for describing function"],
    tech: "Printed story openings and endings",
    tech_purpose: "Cards let students match beginnings to endings",
    ai_prompts: ["Write three story openings that set up different things", "Write an ending that resolves nothing, for critique"],
    assessment: ["Check descriptions name the job not the content", "Confirm the rewritten ending resolves the problem", "Review story maps"],
    why_it_works: ["A broken ending makes the function of endings obvious", "Separating job from content is the shift this standard needs", "Matching openings to endings makes structure a relationship", "Rewriting proves understanding better than describing"],
  },
  {
    standard_code: "W.3.1",
    title: "Reasons in an Order That Builds",
    badge: "Grade 3",
    route_name: "Writing Workshop",
    route_line: "State it → Gather reasons → Order them on purpose",
    success_criteria: ["Introduces the topic and states an opinion", "Supplies reasons that add new information", "Orders reasons deliberately and concludes"],
    steps: [
      { name: "Retrieve the Because Test", minutes: 5, body: "Opinion plus because plus reason. Does the reason add anything new? Quick recall of the check.", science_tag: "retrieval" },
      { name: "Introduce Before Arguing", minutes: 8, body: "The reader needs to know what this is about first. Model an opening that sets up rather than argues.", science_tag: "dual-coding" },
      { name: "Gather More Than You Need", minutes: 10, body: "Five candidate reasons on separate slips. More than will survive, deliberately.", science_tag: "elaboration" },
      { name: "Cut the Weak Ones", minutes: 10, body: "Apply the because test. Cross out any that restate the opinion. Cutting is part of writing.", science_tag: "elaboration" },
      { name: "Order on Purpose", minutes: 12, body: "Physically rearrange the slips. Strongest last usually lands best. Try two orders and read both aloud.", science_tag: "interleaving" },
      { name: "Link and Close", minutes: 10, body: "Add linking words between reasons and a conclusion that answers 'so what?'", science_tag: "collaborative" },
      { name: "Read the Opening and Close", minutes: 5, body: "Two students read just those two parts. Does the piece feel finished?", science_tag: "spaced" },
    ],
    ef_supports: ["Reason slips that can be rearranged", "Because test anchor chart", "Linking word bank", "Try two orderings before choosing"],
    tech: "Paper slips for reasons",
    tech_purpose: "Ordering is physical before it is written",
    ai_prompts: ["Generate grade 3 opinion prompts with two defensible sides", "Write reasons that restate the opinion, for cutting practice"],
    assessment: ["Check reasons pass the because test", "Confirm the order was chosen not accidental", "Read conclusions for 'so what?'"],
    why_it_works: ["Gathering more than needed makes cutting normal", "Physical slips make ordering a decision rather than a sequence", "Reading two orders aloud shows order matters", "The because test is a self-check students can run alone"],
  },
  {
    standard_code: "RI.4.3",
    title: "What Happened, and Why",
    badge: "Grade 4",
    route_name: "Explicit Instruction",
    route_line: "Track what happened → Find the why → Cite the sentence",
    success_criteria: ["Recounts events or steps accurately", "Explains the cause from the text", "Cites the specific sentence supplying the reason"],
    steps: [
      { name: "Retrieve Cause and Effect", minutes: 5, body: "Signal words: because, so, as a result. Fast recall before applying them.", science_tag: "retrieval" },
      { name: "What Versus Why", minutes: 10, body: "Two answers to the same question — one recounts, one explains. Students name the difference.", science_tag: "elaboration" },
      { name: "Track the Sequence", minutes: 10, body: "Map events or steps in order. What happened has to be secure before why can be added.", science_tag: "dual-coding" },
      { name: "Hunt the Because", minutes: 12, body: "Find the sentence supplying the reason. Sometimes it is nowhere near the event, which is the difficulty.", science_tag: "elaboration" },
      { name: "Prior Knowledge Is Not Evidence", minutes: 10, body: "A why that sounds right but is not in the text. Students spot it. This is the habit being built.", science_tag: "interleaving" },
      { name: "Write the Explanation", minutes: 10, body: "What happened, why, and the sentence proving it. All three, every time.", science_tag: "collaborative" },
      { name: "Share a Hard One", minutes: 3, body: "One student explains an event whose cause was far from it in the text.", science_tag: "spaced" },
    ],
    ef_supports: ["Cause and effect signal word chart", "Sequence map", "Three-part answer frame", "Numbered paragraphs"],
    tech: "Printed historical or scientific text",
    tech_purpose: "Markable copy for locating causes",
    ai_prompts: ["Write a grade 4 science text where causes sit apart from effects", "Generate plausible but unsupported explanations for critique"],
    assessment: ["Check answers contain a why", "Confirm the citing sentence exists", "Watch for prior knowledge presented as text"],
    why_it_works: ["The what-versus-why contrast names the gap directly", "Causes placed far from effects is what makes this hard", "Requiring the sentence blocks plausible invention", "Sequence first frees attention for causation"],
  },
  {
    standard_code: "L.4.1",
    title: "Grammar in Your Own Writing",
    badge: "Grade 4",
    route_name: "Explicit Instruction",
    route_line: "Notice it → Practice it → Fix your own draft",
    success_criteria: ["Keeps verb tense consistent", "Uses relative pronouns to add detail", "Finds and fixes errors in their own writing"],
    steps: [
      { name: "Retrieve Parts of Speech", minutes: 5, body: "Sort words into nouns, verbs, adjectives. The categories before the conventions.", science_tag: "retrieval" },
      { name: "Tense Shifts Are Jarring", minutes: 10, body: "Read a paragraph that shifts tense. Students hear the wrongness before naming it.", science_tag: "elaboration" },
      { name: "Highlight Every Verb", minutes: 10, body: "In a short passage, highlight verbs and check they agree. A mechanical check that catches most shifts.", science_tag: "dual-coding" },
      { name: "Relative Pronouns Add Detail", minutes: 12, body: "Combine two short sentences with who or which. Grammar as a tool for better writing, not a rule.", science_tag: "elaboration" },
      { name: "Mixed Practice", minutes: 10, body: "Sentences needing different fixes, shuffled. Mixing forces diagnosis rather than rule application.", science_tag: "interleaving" },
      { name: "Edit Your Own Draft", minutes: 10, body: "Students highlight verbs in their own writing and check for shifts. This is where it transfers.", science_tag: "collaborative" },
      { name: "Share a Combined Sentence", minutes: 3, body: "Two students share a sentence improved with a relative pronoun.", science_tag: "spaced" },
    ],
    ef_supports: ["Highlight-every-verb routine", "Sentence combining pairs", "Mixed error practice", "Edit own draft rather than worksheets"],
    tech: "Printed drafts and highlighters",
    tech_purpose: "Highlighting verbs makes tense visible",
    ai_prompts: ["Write paragraphs with deliberate tense shifts", "Generate sentence pairs for combining with relative pronouns"],
    assessment: ["Check verb highlighting catches shifts", "Review combined sentences", "Confirm self-edits on real drafts"],
    why_it_works: ["Hearing a tense shift precedes naming it", "Highlighting verbs is a mechanical check students can always run", "Sentence combining shows grammar improving writing rather than policing it", "Editing real drafts is where conventions actually transfer"],
  },
  {
    standard_code: "SL.5.4",
    title: "Saying It So People Follow",
    badge: "Grade 5",
    route_name: "Structured Presentation",
    route_line: "Pick three points → Order them → Deliver clearly",
    success_criteria: ["Selects a small number of main points", "Sequences them logically", "Supports each with a relevant detail"],
    steps: [
      { name: "Retrieve Main Idea", minutes: 5, body: "Given a paragraph, name the main point. Selection starts here.", science_tag: "retrieval" },
      { name: "Three Points, Not Thirty", minutes: 10, body: "Model cutting a pile of research down to three. What gets cut is the lesson.", science_tag: "elaboration" },
      { name: "Order Them", minutes: 10, body: "Which point has to come first for the others to make sense? Sequence as dependency, not preference.", science_tag: "dual-coding" },
      { name: "One Detail Each", minutes: 10, body: "Each point gets one supporting fact. No point without support, no support without a point.", science_tag: "elaboration" },
      { name: "Mark the Pauses", minutes: 10, body: "Annotate notes with pause points. Nervous speakers rush; marked pauses give permission to breathe.", science_tag: "dual-coding" },
      { name: "Present to a Partner", minutes: 12, body: "Full run-through with a listener checking the three points landed. Low stakes before high.", science_tag: "collaborative" },
      { name: "Two Present to the Class", minutes: 3, body: "Two volunteers. Class names the three points they heard.", science_tag: "spaced" },
    ],
    ef_supports: ["Three-point planner", "Pause marks in the notes", "Partner rehearsal before class", "Listener checklist of three points"],
    tech: "Printed note cards",
    tech_purpose: "Notes that can be annotated for delivery",
    ai_prompts: ["Generate research topics suited to three main points", "Create listener checklists for peer feedback"],
    assessment: ["Check the cut down to three", "Confirm each point has support", "Listener names the three points"],
    why_it_works: ["Cutting to three forces the selection the standard asks for", "Ordering by dependency gives a reason rather than a preference", "Marked pauses address the real delivery problem", "A listener checking comprehension tests the sequencing honestly"],
  },
  {
    standard_code: "RL.6.4",
    title: "Why That Word and Not Another",
    badge: "Grade 6",
    route_name: "Analytical Reading",
    route_line: "Find the meaning → Swap in a synonym → Name what changed",
    success_criteria: ["Determines a word's meaning in context", "Describes the tone a word creates", "Explains what a synonym would have lost"],
    steps: [
      { name: "Retrieve Context Strategies", minutes: 5, body: "One unfamiliar word solved from context. The base skill before analysis.", science_tag: "retrieval" },
      { name: "Same Meaning, Different Feeling", minutes: 10, body: "Thin, slender, skinny, gaunt. Same denotation, different connotation. Rank them by feeling.", science_tag: "elaboration" },
      { name: "The Swap Test", minutes: 12, body: "Replace the author's word with a synonym. Read both. Name precisely what changed. This is the whole method.", science_tag: "elaboration" },
      { name: "Tone Is the Writer's Attitude", minutes: 10, body: "Distinguish tone from mood. Whose feeling is it? Sort descriptions into the two.", science_tag: "dual-coding" },
      { name: "Track Tone Across a Passage", minutes: 12, body: "Highlight words carrying tone. A pattern emerges that single words do not show.", science_tag: "dual-coding" },
      { name: "Write the Analysis", minutes: 8, body: "One word: its meaning here, the tone it creates, what a synonym would have lost.", science_tag: "interleaving" },
      { name: "Defend a Word Choice", minutes: 3, body: "One student argues why the author's word beats the alternative.", science_tag: "spaced" },
    ],
    ef_supports: ["Connotation ranking lines", "Swap test as a routine", "Tone versus mood sorting", "Highlighters for tone words"],
    tech: "Printed passage with wide margins",
    tech_purpose: "Room to write synonyms above the author's words",
    ai_prompts: ["Generate synonym sets varying in connotation", "Write passages with a consistent identifiable tone"],
    assessment: ["Check the swap test is actually performed", "Confirm tone is described as the writer's attitude", "Read analyzes for what was lost"],
    why_it_works: ["The swap test turns a vague question into a concrete comparison", "Ranking synonyms makes connotation measurable", "Tone versus mood is the confusion that muddles this standard", "Tracking across a passage shows tone as cumulative"],
  },
  {
    standard_code: "RI.7.6",
    title: "What Does This Author Actually Think?",
    badge: "Grade 7",
    route_name: "Analytical Reading",
    route_line: "Find the position → Find the others → See how they are separated",
    success_criteria: ["States the author's position specifically", "Locates other views in the text", "Explains how the author distinguishes their own"],
    steps: [
      { name: "Retrieve Fact and Opinion", minutes: 5, body: "Sort statements. The base distinction before analysing position.", science_tag: "retrieval" },
      { name: "Purpose Specific Enough to Argue With", minutes: 10, body: "'To inform' says nothing. Push for a purpose someone could disagree with.", science_tag: "elaboration" },
      { name: "Whose Voice Is This?", minutes: 12, body: "Highlight the author's own claims one color, reported views of others another. The page shows the structure.", science_tag: "dual-coding" },
      { name: "How the Separation Works", minutes: 12, body: "Words like 'some argue' and 'however' mark the boundary. Collect the signals.", science_tag: "elaboration" },
      { name: "Agree But Analyze", minutes: 10, body: "A text students agree with. Identifying position is separate from sharing it — the harder discipline.", science_tag: "interleaving" },
      { name: "Write the Analysis", minutes: 8, body: "The author's position, one other view in the text, and how the author sets them apart.", science_tag: "collaborative" },
      { name: "Compare Two Readings", minutes: 3, body: "Two students state the author's position. Discuss any difference.", science_tag: "spaced" },
    ],
    ef_supports: ["Two-color highlighting for voices", "Signal phrase collection", "Purpose specificity test", "Numbered paragraphs"],
    tech: "Printed opinion text with numbered paragraphs",
    tech_purpose: "Two-color highlighting needs a markable copy",
    ai_prompts: ["Write a grade 7 opinion piece that reports and rebuts other views", "Generate vague and specific purpose statements for comparison"],
    assessment: ["Check purposes are specific enough to dispute", "Confirm voices are distinguished in highlighting", "Read analyzes for the separation mechanism"],
    why_it_works: ["Demanding an arguable purpose kills the 'to inform' default", "Color-coding voices makes an invisible structure visible", "Signal phrases are concrete evidence of the separation", "Analysing an agreeable text separates identifying from endorsing"],
  },
  {
    standard_code: "W.7.1",
    title: "Arguing With the Other Side in the Room",
    badge: "Grade 7",
    route_name: "Writing Workshop",
    route_line: "Claim and evidence → Name the opposition → Order it all",
    success_criteria: ["States an arguable claim", "Supports it with relevant evidence", "Acknowledges an alternate claim and responds"],
    steps: [
      { name: "Retrieve Claim and Evidence", minutes: 5, body: "Given a claim, supply evidence. The base before the counterclaim work.", science_tag: "retrieval" },
      { name: "Arguable or Not", minutes: 8, body: "Sort statements into arguable and merely true. A claim nobody disputes is not a claim.", science_tag: "elaboration" },
      { name: "Relevant to the Claim", minutes: 10, body: "Evidence relevant to the topic but not the claim. Students spot the gap.", science_tag: "elaboration" },
      { name: "Write the Other Side", minutes: 12, body: "State the opposing view as its holders would. Not a caricature — a version they would recognize.", science_tag: "elaboration" },
      { name: "Acknowledge Then Respond", minutes: 12, body: "Mentioning the other side is not enough. Model concede-then-counter with a sentence frame.", science_tag: "dual-coding" },
      { name: "Order the Reasons", minutes: 10, body: "Rearrange so each sets up the next. Test by swapping two — if nothing changes, they were not ordered.", science_tag: "interleaving" },
      { name: "Swap and Attack", minutes: 3, body: "Partners try to break each other's argument. Note which parts held.", science_tag: "spaced" },
    ],
    ef_supports: ["Claim/evidence/counterclaim organizer", "Concede-then-counter frames", "Arguable-or-not sorting", "Reason slips for reordering"],
    tech: "Printed organizers",
    tech_purpose: "Keeping the four moves distinct while drafting",
    ai_prompts: ["Generate arguable and non-arguable statements for sorting", "Write strong opposing arguments for common grade 7 claims"],
    assessment: ["Check claims are genuinely arguable", "Confirm the counterclaim is fair not caricatured", "Verify a response follows the acknowledgement"],
    why_it_works: ["Sorting arguable from true prevents claims nobody disputes", "Writing the opposition fairly is what separates argument from persuasion", "Acknowledge-then-respond is a concrete reusable move", "The swap test makes ordering a real decision"],
  },
  {
    standard_code: "K.NBT.A.1",
    title: "Ten and Some More",
    badge: "Kindergarten",
    route_name: "Concrete-Representational-Abstract",
    route_line: "Fill a ten-frame → Count on → Write the equation",
    success_criteria: ["Fills a ten-frame completely", "Says a teen number as ten and some more", "Writes 14 = 10 + 4"],
    steps: [
      { name: "Count to 19", minutes: 5, body: "Rote sequence. The teens are where it wobbles, so drill them.", science_tag: "retrieval" },
      { name: "Fill the Frame", minutes: 12, body: "Ten counters, ten spaces, full. That full frame is one ten — a single thing now.", science_tag: "dual-coding" },
      { name: "And Some More", minutes: 12, body: "Add loose counters beside the full frame. Fourteen is the full frame and four. Say it that way every time.", science_tag: "dual-coding" },
      { name: "Count On From Ten", minutes: 10, body: "Do not recount the frame. Eleven, twelve, thirteen. Counting on treats ten as a unit.", science_tag: "elaboration" },
      { name: "The Backwards Teen", minutes: 10, body: "Fourteen sounds like four-then-ten but is written 14. Build it to settle the confusion.", science_tag: "elaboration" },
      { name: "Write the Equation", minutes: 8, body: "14 = 10 + 4, matching what is built. Symbols attached to something physical.", science_tag: "dual-coding" },
      { name: "Build and Say", minutes: 3, body: "One teen number built and described as ten and some more.", science_tag: "spaced" },
    ],
    ef_supports: ["Ten-frames", "Counters in two colors", "Count-on routine", "Equation frame matching the build"],
    tech: "Ten-frames and counters",
    tech_purpose: "A full frame makes ten a single unit",
    ai_prompts: ["Generate teen number building tasks", "Create equation frames for 11 to 19"],
    assessment: ["Watch for recounting the full frame", "Check the spoken description uses ten and some more", "Individual build and say"],
    why_it_works: ["A full ten-frame makes ten one thing rather than ten things", "Counting on from ten is the behavior that shows unitising", "Teen number naming genuinely misleads, so address it directly", "Equations recorded against a build stay meaningful"],
  },
  {
    standard_code: "1.OA.B.3",
    title: "Add Them in Whatever Order Helps",
    badge: "Grade 1",
    route_name: "Explicit Instruction",
    route_line: "Prove order does not matter → Start with the bigger → Find a ten",
    success_criteria: ["Shows that order does not change the sum", "Counts on from the larger number", "Regroups three addends to make a ten"],
    steps: [
      { name: "Retrieve Pairs to Ten", minutes: 5, body: "What goes with 7 to make 10? Fast recall — this powers the regrouping later.", science_tag: "retrieval" },
      { name: "Same Cubes, Both Orders", minutes: 10, body: "Build 2 + 9 and 9 + 2 with cubes. Same total. Proved, not asserted.", science_tag: "dual-coding" },
      { name: "Race the Two", minutes: 10, body: "Count on from 2, then from 9. Time both. Starting bigger is faster, and now they know why.", science_tag: "elaboration" },
      { name: "Three Numbers", minutes: 12, body: "4 + 6 + 7. Find the pair making ten first. Grouping is a choice, and some choices are easier.", science_tag: "elaboration" },
      { name: "Spot the Ten", minutes: 10, body: "Sets of three addends. Students circle the pair making ten before adding anything.", science_tag: "interleaving" },
      { name: "Explain the Shortcut", minutes: 8, body: "Why is it allowed to move them around? Students articulate it in their own words.", science_tag: "collaborative" },
      { name: "One Each", minutes: 3, body: "One three-addend sum, solved with the ten found first.", science_tag: "spaced" },
    ],
    ef_supports: ["Cubes for building both orders", "Timer for the counting race", "Circle-the-ten routine", "Pairs-to-ten reference"],
    tech: "Linking cubes",
    tech_purpose: "Building both orders proves commutativity physically",
    ai_prompts: ["Generate three-addend sums containing a pair making ten", "Create commutative pairs with a large gap between addends"],
    assessment: ["Watch for counting on from the smaller number", "Check the ten-pair is found first", "Listen to the explanations"],
    why_it_works: ["Timing the two orders gives a reason beyond permission", "Building both proves it rather than asserting it", "Finding a ten first is the strategy the property enables", "Articulating why cements the property as a tool"],
  },
  {
    standard_code: "2.NBT.B.5",
    title: "Choosing How to Add Two-Digit Numbers",
    badge: "Grade 2",
    route_name: "Strategy Instruction",
    route_line: "Build the trade → Learn several strategies → Pick the one that fits",
    success_criteria: ["Regroups correctly when needed", "Uses more than one strategy", "Chooses a strategy suited to the numbers"],
    steps: [
      { name: "Retrieve Facts Within 20", minutes: 5, body: "Quick sums. Two-digit work collapses without these.", science_tag: "retrieval" },
      { name: "Trade Ten Ones for a Ten", minutes: 12, body: "Base ten blocks. When ten ones gather, trade them. The trade is physical before it is notational.", science_tag: "dual-coding" },
      { name: "Add the Tens First", minutes: 10, body: "47 + 25 as 40 + 20, then 7 + 5. Place value strategy, written out fully.", science_tag: "elaboration" },
      { name: "Or Count On by Tens", minutes: 10, body: "47, 57, 67, then five more. A different route to the same place.", science_tag: "elaboration" },
      { name: "Which Fits These Numbers?", minutes: 12, body: "Some pairs suit counting on, some the tens-first split. Choosing is the skill.", science_tag: "interleaving" },
      { name: "Subtraction Is Addition Backwards", minutes: 8, body: "72 - 47 as 'what do I add to 47 to reach 72?'. The inverse relationship made useful.", science_tag: "elaboration" },
      { name: "Two Problems, Two Strategies", minutes: 3, body: "Solve two, using a different strategy for each and saying why.", science_tag: "spaced" },
    ],
    ef_supports: ["Base ten blocks", "Strategy anchor chart", "Choose-before-solving routine", "Number line for counting on"],
    tech: "Base ten blocks",
    tech_purpose: "Regrouping as a physical trade",
    ai_prompts: ["Generate two-digit pairs suiting different strategies", "Create missing-addend subtraction problems"],
    assessment: ["Check regrouping is done, not avoided", "Confirm more than one strategy is used", "Listen to strategy justifications"],
    why_it_works: ["A physical trade explains regrouping that notation only records", "Several strategies prevent one brittle procedure", "Choosing before solving is where number sense shows", "Subtraction as missing addend reuses addition fluency"],
  },
  {
    standard_code: "3.G.A.1",
    title: "A Square Is Also a Rectangle",
    badge: "Grade 3",
    route_name: "Explicit Instruction",
    route_line: "List attributes → Sort by them → Discover nesting",
    success_criteria: ["Lists a shape's attributes", "Sorts shapes by shared attributes", "Explains why a square is a rectangle"],
    steps: [
      { name: "Retrieve Shape Names", minutes: 5, body: "Name shapes quickly. Vocabulary before classification.", science_tag: "retrieval" },
      { name: "Attributes, Not Looks", minutes: 10, body: "Count sides, angles, parallel pairs. Write attributes down. Classification runs on these, not on appearance.", science_tag: "dual-coding" },
      { name: "Sort Face Down", minutes: 12, body: "Sort shapes using only their written attribute cards. Removing the picture forces the definition to do the work.", science_tag: "elaboration" },
      { name: "The Square Question", minutes: 12, body: "Is a square a rectangle? Check the definition attribute by attribute. Most say no; the definition says yes.", science_tag: "elaboration" },
      { name: "Draw the Nesting", minutes: 10, body: "Quadrilaterals containing rectangles containing squares. A diagram makes the containment visible.", science_tag: "dual-coding" },
      { name: "Odd One Out", minutes: 8, body: "Three shapes, name what two share. Several answers may be defensible.", science_tag: "interleaving" },
      { name: "Explain the Nesting", minutes: 3, body: "One student explains why every square is a rectangle.", science_tag: "spaced" },
    ],
    ef_supports: ["Written attribute cards", "Face-down sorting", "Nesting diagram", "Definitions posted and checked against"],
    tech: "Shape cards with attribute cards",
    tech_purpose: "Separating the picture from the properties",
    ai_prompts: ["Generate attribute cards for common quadrilaterals", "Create odd-one-out sets with multiple defensible answers"],
    assessment: ["Check sorting uses attributes not appearance", "Confirm the square-rectangle relationship is explained", "Review nesting diagrams"],
    why_it_works: ["Sorting face down forces definitions to do the work", "The square question is the misconception at the heart of this standard", "A nesting diagram makes containment spatial", "Multiple defensible answers show classification depends on the attribute chosen"],
  },
  {
    standard_code: "4.OA.A.3",
    title: "What Do You Do With the Leftover?",
    badge: "Grade 4",
    route_name: "Strategy Instruction",
    route_line: "Plan the steps → Solve → Read the remainder in context",
    success_criteria: ["Plans the steps before calculating", "Interprets a remainder for the situation", "Checks the answer against an estimate"],
    steps: [
      { name: "Retrieve Division With Remainders", minutes: 5, body: "Compute three. The arithmetic before the interpretation.", science_tag: "retrieval" },
      { name: "Number the Steps First", minutes: 10, body: "Read the problem, write the steps, calculate nothing yet. Planning is separate from arithmetic.", science_tag: "elaboration" },
      { name: "Estimate Before You Solve", minutes: 8, body: "Roughly what should it be? Estimating first is what makes a wild answer visible.", science_tag: "elaboration" },
      { name: "Four Ways to Read a Remainder", minutes: 14, body: "Round up, drop it, use it as the answer, or express it as a fraction. Buses, boxes, leftovers, sharing.", science_tag: "dual-coding" },
      { name: "Sort by Remainder Type", minutes: 12, body: "Problems sorted by what the remainder means before solving. Sorting is the skill being taught.", science_tag: "interleaving" },
      { name: "Solve and Interpret", minutes: 8, body: "Full problems: plan, estimate, solve, say what the remainder means.", science_tag: "collaborative" },
      { name: "Defend an Interpretation", minutes: 3, body: "One student explains why they rounded up rather than down.", science_tag: "spaced" },
    ],
    ef_supports: ["Number-the-steps routine", "Four remainder types chart", "Estimate-first step", "Sorting mats by remainder meaning"],
    tech: "Printed problem cards",
    tech_purpose: "Sorting problems physically before solving",
    ai_prompts: ["Generate problems requiring each remainder interpretation", "Create multistep problems with estimation checks"],
    assessment: ["Check steps are planned first", "Confirm remainder interpretation matches the context", "Compare answers to estimates"],
    why_it_works: ["Four named interpretations turn a vague judgement into a choice", "Sorting before solving isolates interpretation from arithmetic", "Planning separately from computing prevents dropped steps", "Estimation makes checking a comparison rather than a repeat"],
  },
  {
    standard_code: "5.NF.B.4",
    title: "Why Multiplying Can Make It Smaller",
    badge: "Grade 5",
    route_name: "Concrete-Representational-Abstract",
    route_line: "Fold to find a fraction of a fraction → Model the area → Generalize",
    success_criteria: ["Models a fraction times a fraction", "Computes the product correctly", "Explains why the product can be smaller than both factors"],
    steps: [
      { name: "Retrieve Fraction Meaning", minutes: 5, body: "What does 3/4 mean? Three one-fourths. The foundation for scaling.", science_tag: "retrieval" },
      { name: "Half of a Half", minutes: 12, body: "Fold paper in half, then that half in half. A quarter. Multiplying made it smaller, physically.", science_tag: "dual-coding" },
      { name: "Confront the Expectation", minutes: 10, body: "Multiplying is supposed to make things bigger. Name the expectation, then show why it only holds above one.", science_tag: "elaboration" },
      { name: "The Area Model", minutes: 12, body: "Shade 2/3 across and 3/4 down. The overlap is the product. The rule becomes visible in the grid.", science_tag: "dual-coding" },
      { name: "Straight Across", minutes: 10, body: "Notice the overlap count is numerators multiplied, and the total is denominators multiplied. Discovered, not decreed.", science_tag: "elaboration" },
      { name: "Fractional Side Lengths", minutes: 8, body: "A rectangle 2/3 by 3/4. Area and multiplication as the same operation.", science_tag: "interleaving" },
      { name: "Explain the Shrinking", minutes: 3, body: "One student explains why the answer is smaller than both factors.", science_tag: "spaced" },
    ],
    ef_supports: ["Paper folding", "Area model grids", "Name-the-expectation discussion", "Shade-across-and-down routine"],
    tech: "Paper and printed grids",
    tech_purpose: "Folding makes the shrinking undeniable",
    ai_prompts: ["Generate fraction multiplication problems suited to area models", "Create fractional side length area problems"],
    assessment: ["Check models match the computation", "Confirm the shrinking is explained not just observed", "Watch for cross-multiplication"],
    why_it_works: ["Folding shows the product shrinking before any rule appears", "Naming the bigger-answer expectation lets it be corrected rather than ignored", "The area model makes straight-across multiplication self-evident", "Linking to area connects two topics that usually stay apart"],
  },
  {
    standard_code: "6.G.A.1",
    title: "Cut It Into Shapes You Know",
    badge: "Grade 6",
    route_name: "Strategy Instruction",
    route_line: "Halve a rectangle → Find the height → Decompose anything",
    success_criteria: ["Finds the area of a triangle", "Identifies the perpendicular height", "Decomposes a polygon into simpler shapes"],
    steps: [
      { name: "Retrieve Rectangle Area", minutes: 5, body: "Length times width. The shape everything else gets reduced to.", science_tag: "retrieval" },
      { name: "A Triangle Is Half a Rectangle", minutes: 12, body: "Cut a rectangle corner to corner. Two identical triangles. The formula falls out of the cut.", science_tag: "dual-coding" },
      { name: "Which One Is the Height", minutes: 12, body: "Height is perpendicular to the base, not the slanted side. Draw it in on every triangle before computing.", science_tag: "elaboration" },
      { name: "Obtuse Triangles Are Awkward", minutes: 10, body: "The height falls outside the triangle. Show it rather than avoiding it.", science_tag: "elaboration" },
      { name: "Decompose a Polygon", minutes: 12, body: "Draw the dividing line first, always. Then compute each piece and add.", science_tag: "dual-coding" },
      { name: "Or Compose Instead", minutes: 8, body: "Sometimes it is easier to surround the shape and subtract. Two routes to the same area.", science_tag: "interleaving" },
      { name: "One Composite Shape", minutes: 3, body: "Decompose, compute, sum.", science_tag: "spaced" },
    ],
    ef_supports: ["Cut-and-compare rectangles", "Draw-the-height routine", "Obtuse triangle examples", "Draw-the-dividing-line first"],
    tech: "Grid paper and scissors",
    tech_purpose: "Cutting a rectangle proves the triangle formula",
    ai_prompts: ["Generate triangles including obtuse ones with external heights", "Create composite polygons for decomposition"],
    assessment: ["Check the perpendicular height is used", "Confirm dividing lines are drawn first", "Review composite calculations"],
    why_it_works: ["Cutting the rectangle makes the halving obvious rather than memorised", "Drawing the height in every time prevents the slant-side error", "Obtuse triangles break a rule students infer, so include them", "Compose-or-decompose gives flexibility rather than one procedure"],
  },
  {
    standard_code: "7.EE.A.1",
    title: "Same Expression, Different Clothes",
    badge: "Grade 7",
    route_name: "Explicit Instruction",
    route_line: "Combine like terms → Expand → Factor back",
    success_criteria: ["Combines only genuinely like terms", "Expands including a negative outside", "Factors out a common factor"],
    steps: [
      { name: "Retrieve the Distributive Property", minutes: 5, body: "Numeric examples first. 3(20 + 4). The property before the letters.", science_tag: "retrieval" },
      { name: "Terms With Units", minutes: 10, body: "3x + 2 is three x's and two ones. Saying it with units makes combining them obviously wrong.", science_tag: "elaboration" },
      { name: "Expand a Bracket", minutes: 12, body: "Multiply everything inside. Arrows drawn to every term so none is missed.", science_tag: "dual-coding" },
      { name: "The Negative Outside", minutes: 12, body: "5 - 2(x + 3). Rewrite as adding a negative first. This is the highest-frequency error in the standard.", science_tag: "elaboration" },
      { name: "Factoring Is Expanding Backwards", minutes: 10, body: "What do the terms share? Pull it out. Then expand to check you got back where you started.", science_tag: "elaboration" },
      { name: "Prove They Are Equivalent", minutes: 8, body: "Substitute a value into both forms. Same answer means equivalent. A check students can always run.", science_tag: "interleaving" },
      { name: "Expand and Factor One", minutes: 3, body: "One expression expanded, one factored.", science_tag: "spaced" },
    ],
    ef_supports: ["Arrows from the multiplier to every term", "Rewrite-subtraction routine", "Say-terms-with-units habit", "Substitution check for equivalence"],
    tech: "Printed expression cards",
    tech_purpose: "Matching equivalent forms physically",
    ai_prompts: ["Generate expressions requiring negative distribution", "Create equivalent expression pairs for matching"],
    assessment: ["Check the negative is distributed", "Watch for unlike terms combined", "Confirm substitution checks are used"],
    why_it_works: ["Saying terms with units makes 3x + 2 = 5x visibly wrong", "Rewriting subtraction removes a whole error class", "Factoring as reverse expansion links two operations", "Substitution gives students a way to check themselves"],
  },
  {
    standard_code: "8.NS.A.1",
    title: "Numbers That Are Not Fractions",
    badge: "Grade 8",
    route_name: "Explicit Instruction",
    route_line: "Convert to decimals → Look for the pattern → Classify",
    success_criteria: ["Converts fractions to decimals", "Identifies terminating and repeating decimals", "Classifies numbers as rational or irrational with a reason"],
    steps: [
      { name: "Retrieve Fraction to Decimal", minutes: 5, body: "Divide three fractions out. The tool for everything that follows.", science_tag: "retrieval" },
      { name: "Two Kinds of Ending", minutes: 10, body: "Some stop, some repeat forever. Convert several and sort them. Both kinds are rational.", science_tag: "dual-coding" },
      { name: "Then There Is Root Two", minutes: 12, body: "Compute more and more digits. No pattern appears, ever. Irrationality as a failure to settle.", science_tag: "elaboration" },
      { name: "Pi Is Not 3.14", minutes: 10, body: "Show twenty digits. 3.14 is an approximation we use, not the number itself.", science_tag: "elaboration" },
      { name: "Classify and Justify", minutes: 12, body: "Mixed set. Every classification needs a reason from the decimal expansion, not a vibe.", science_tag: "interleaving" },
      { name: "Repeating to Fraction", minutes: 8, body: "0.333… is 1/3. Repeating decimals really are fractions, which is why they are rational.", science_tag: "elaboration" },
      { name: "Classify Three", minutes: 3, body: "Three numbers classified with reasons.", science_tag: "spaced" },
    ],
    ef_supports: ["Calculators for long expansions", "Sorting mats for the three types", "Twenty digits of pi displayed", "Justification required with every classification"],
    tech: "Calculators",
    tech_purpose: "Long expansions show patterns that short ones hide",
    ai_prompts: ["Generate fractions producing terminating and repeating decimals", "Create classification sets mixing rationals and irrationals"],
    assessment: ["Check classifications carry reasons", "Watch for long decimals called irrational", "Confirm repeating decimals are called rational"],
    why_it_works: ["Sorting terminating from repeating shows both are still rational", "Computing many digits makes irrationality observable rather than asserted", "The pi approximation is a misconception worth naming explicitly", "Requiring justification prevents classification by appearance"],
  },
  {
    standard_code: "8.SP.A.1",
    title: "Two Measurements, One Point",
    badge: "Grade 8",
    route_name: "Explicit Instruction",
    route_line: "Plot the pairs → Describe the pattern → Resist the causal leap",
    success_criteria: ["Constructs a scatter plot from paired data", "Describes direction, form and strength", "Identifies outliers and clusters"],
    steps: [
      { name: "Retrieve Coordinate Plotting", minutes: 5, body: "Plot four ordered pairs. The mechanics before the interpretation.", science_tag: "retrieval" },
      { name: "Each Point Is One Thing", minutes: 10, body: "One person, two measurements. Emphasise this before plotting — it is why points are not joined.", science_tag: "elaboration" },
      { name: "Collect and Plot", minutes: 12, body: "Class data — height and arm span, say. Their own data makes the pattern worth looking at.", science_tag: "collaborative" },
      { name: "Describe What You See", minutes: 10, body: "Direction, form, strength. Give the vocabulary and let the plot supply the meaning.", science_tag: "dual-coding" },
      { name: "Outliers and Clusters", minutes: 10, body: "What is that point doing over there? Outliers are interesting, not errors to delete.", science_tag: "elaboration" },
      { name: "The Causal Trap", minutes: 12, body: "Ice cream sales and drownings. Strong association, no causation. The habit worth building most.", science_tag: "interleaving" },
      { name: "Describe One Plot", minutes: 3, body: "Given a scatter plot, describe direction, strength and any outliers.", science_tag: "spaced" },
    ],
    ef_supports: ["Graph paper with labelled axes", "Description vocabulary chart", "Class-collected data", "Correlation-not-causation examples"],
    tech: "Graph paper and class data",
    tech_purpose: "Their own data makes the pattern worth reading",
    ai_prompts: ["Generate paired data sets with varied association strength", "Create correlated pairs with no causal link"],
    assessment: ["Check points are not joined up", "Confirm descriptions cover direction and strength", "Watch for causal claims"],
    why_it_works: ["Their own data makes the pattern something they want to read", "Stating that each point is one thing prevents line-graph habits", "Outliers treated as interesting builds statistical curiosity", "The causation trap is the most transferable idea in the standard"],
  },
];

await seedStandardsBatch({
  label: "Batch 5",
  standardsData,
  unpacksData,
  blueprintsData,
});
