// @ts-nocheck
/**
 * Batch 17: grade 4 mathematics — the last of the three decks.
 *
 * Completes grades 2, 3 and 4. Every standard in all three "Unpacking
 * Standards" documents now has an unpack and a lesson blueprint.
 *
 * The grade 4 maths misconceptions are almost all whole-number thinking
 * surviving into places it does not belong: 0.45 judged greater than 0.5,
 * 3/8 greater than 1/2, multiplying a fraction top and bottom, adding
 * 3/10 and 4/100 to get 7/110. Each blueprint is built to make the
 * whole-number instinct fail visibly rather than quietly.
 *
 * American spellings throughout.
 *
 *   bun run scripts/seed-standards-batch-17.ts
 */
import { seedStandardsBatch } from "./lib/seed-standards-batch";

const standardsData = [
  {
    code: "4.OA.A.1",
    name: "Times as many is not more than",
    plain_reading:
      "Interpret a multiplication equation as a comparison; represent verbal statements of multiplicative comparisons as multiplication equations.",
    learning_target: "I can tell four times as many from four more than.",
    skills: ["Multiplicative Comparison", "Writing Equations", "Comparison Language"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["multiplicative comparison", "times as many", "more than", "multiplication equation", "fourth grade"],
  },
  {
    code: "4.OA.A.2",
    name: "Is it adding or multiplying",
    plain_reading:
      "Multiply or divide to solve word problems involving multiplicative comparison, distinguishing multiplicative from additive comparison.",
    learning_target: "I can work out the relationship before picking an operation.",
    skills: ["Comparison Problems", "Additive Versus Multiplicative", "Unknowns"],
    science_tags: ["metacognition", "dual-coding"],
    match_keys: ["multiplicative comparison word problems", "additive comparison", "symbol for the unknown", "multiply or divide"],
  },
  {
    code: "4.OA.B.4",
    name: "Every factor pair, and prime or not",
    plain_reading:
      "Find all factor pairs for a whole number in the range 1-100; determine whether a given whole number is prime or composite.",
    learning_target: "I can know when I have found every factor, and I know one is neither.",
    skills: ["Factor Pairs", "Multiples", "Prime and Composite"],
    science_tags: ["dual-coding", "retrieval"],
    match_keys: ["factor pairs", "multiples", "prime composite", "1 to 100", "factors and multiples"],
  },
  {
    code: "4.OA.C.5",
    name: "Say the rule, not just the next term",
    plain_reading:
      "Generate a number or shape pattern that follows a given rule; identify apparent features of the pattern that were not explicit in the rule.",
    learning_target: "I can state the rule so I could run the pattern backwards.",
    skills: ["Generating Patterns", "Stating Rules", "Emergent Features"],
    science_tags: ["elaboration", "metacognition"],
    match_keys: ["generate a pattern from a rule", "features not explicit in the rule", "term", "sequence", "extend and describe"],
  },
  {
    code: "4.NBT.A.1",
    name: "Ten times the place to its right",
    plain_reading:
      "Recognize that in a multi-digit whole number, a digit in one place represents ten times what it represents in the place to its right.",
    learning_target: "I can explain why 700 is ten times 70, not just say the rule.",
    skills: ["Place Value Relationships", "Explanation", "Multi-Digit Numbers"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["ten times what it represents", "place value", "digit", "multi-digit whole number", "period"],
  },
  {
    code: "4.NBT.A.2",
    name: "Large numbers, three ways, no and",
    plain_reading:
      "Read and write multi-digit whole numbers using base-ten numerals, number names, and expanded form; compare two numbers using >, =, and <.",
    learning_target: "I can write a big number in words without putting and in it.",
    skills: ["Expanded Form", "Number Names", "Comparing"],
    science_tags: ["dual-coding", "interleaving"],
    match_keys: ["base-ten numerals number names expanded form", "compare multi-digit", "period", "and indicates a decimal"],
  },
  {
    code: "4.NBT.A.3",
    name: "Round the target place only",
    plain_reading: "Use place value understanding to round multi-digit whole numbers to any place.",
    learning_target: "I can round once, to the place asked for, and stop.",
    skills: ["Rounding to Any Place", "Place Value", "Estimation"],
    science_tags: ["metacognition", "dual-coding"],
    match_keys: ["round multi-digit to any place", "place value", "benchmark", "estimate", "compounding error"],
  },
  {
    code: "4.NBT.B.4",
    name: "Estimate first, then subtract across zeros",
    plain_reading:
      "Fluently add and subtract multi-digit whole numbers using the standard algorithm.",
    learning_target: "I can estimate first so I notice when my answer is wrong.",
    skills: ["Standard Algorithm", "Regrouping Across Zeros", "Reasonableness"],
    science_tags: ["metacognition", "spaced"],
    match_keys: ["standard algorithm", "add and subtract multi-digit", "regroup", "across zeros", "estimate to check"],
  },
  {
    code: "4.NF.A.1",
    name: "More pieces, same amount",
    plain_reading:
      "Explain why a fraction a/b is equivalent to a fraction (n x a)/(n x b) using visual fraction models.",
    learning_target: "I can show why cutting into more pieces does not make more.",
    skills: ["Equivalent Fractions", "Visual Models", "Justification"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["equivalent fractions", "visual fraction models", "numerator denominator", "scaling", "explain why"],
  },
  {
    code: "4.NF.A.2",
    name: "Compare fractions, not their digits",
    plain_reading:
      "Compare two fractions with different numerators and different denominators; record the results with the symbols >, =, or <.",
    learning_target: "I can use a half as a benchmark instead of comparing the numbers separately.",
    skills: ["Comparing Fractions", "Common Denominators", "Benchmarks"],
    science_tags: ["dual-coding", "metacognition"],
    match_keys: ["compare fractions different denominators", "common denominator", "benchmark 1/2", "justify with a model"],
  },
  {
    code: "4.NF.B.4",
    name: "A fraction times a whole number",
    plain_reading:
      "Apply and extend previous understandings of multiplication to multiply a fraction by a whole number.",
    learning_target: "I can see three lots of one quarter as three quarters.",
    skills: ["Multiples of Unit Fractions", "Multiplying by a Whole Number", "Word Problems"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["multiply a fraction by a whole number", "multiple of a unit fraction", "repeated addition", "word problems"],
  },
  {
    code: "4.NF.C.5",
    name: "Tenths into hundredths first",
    plain_reading:
      "Express a fraction with denominator 10 as an equivalent fraction with denominator 100, and use this to add two fractions with these denominators.",
    learning_target: "I can rewrite tenths as hundredths before adding.",
    skills: ["Tenths and Hundredths", "Equivalence", "Adding Fractions"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["denominator 10 as 100", "add tenths and hundredths", "equivalent fraction", "common denominator"],
  },
  {
    code: "4.NF.C.7",
    name: "0.5 is bigger than 0.45",
    plain_reading:
      "Compare two decimals to hundredths by reasoning about their size; record the results with the symbols >, =, or <.",
    learning_target: "I can compare decimals by place value, not by how many digits there are.",
    skills: ["Comparing Decimals", "Place Value Reasoning", "Justification"],
    science_tags: ["dual-coding", "metacognition"],
    match_keys: ["compare decimals to hundredths", "tenths hundredths", "more digits", "justify with a model", "whole-number thinking"],
  },
  {
    code: "4.MD.A.1",
    name: "Smaller unit, more of them",
    plain_reading:
      "Know relative sizes of measurement units within one system of units; express measurements in a larger unit in terms of a smaller unit.",
    learning_target: "I can work out whether to multiply or divide by thinking about the unit.",
    skills: ["Unit Conversion", "Relative Sizes", "Two-Column Tables"],
    science_tags: ["dual-coding", "metacognition"],
    match_keys: ["relative sizes of units", "larger unit in terms of smaller", "convert", "metric customary", "two-column table"],
  },
  {
    code: "4.MD.A.2",
    name: "Convert before you combine",
    plain_reading:
      "Use the four operations to solve word problems involving distances, intervals of time, liquid volumes, masses of objects, and money.",
    learning_target: "I can put everything in one unit before I add it.",
    skills: ["Measurement Problems", "Mixed Units", "Diagrams with Scale"],
    science_tags: ["metacognition", "dual-coding"],
    match_keys: ["distances intervals of time liquid volumes masses money", "four operations", "diagram with a scale", "mixed units"],
  },
  {
    code: "4.MD.B.4",
    name: "Line plots in halves, quarters and eighths",
    plain_reading:
      "Make a line plot to display a data set of measurements in fractions of a unit; solve problems involving addition and subtraction of fractions.",
    learning_target: "I can space fractional intervals evenly so the data tells the truth.",
    skills: ["Fractional Line Plots", "Even Intervals", "Adding and Subtracting Fractions"],
    science_tags: ["dual-coding", "metacognition"],
    match_keys: ["line plot fractions of a unit", "halves fourths eighths", "addition and subtraction of fractions", "spread"],
  },
  {
    code: "4.MD.C.5",
    name: "The opening, not the arms",
    plain_reading:
      "Recognize angles as geometric shapes formed wherever two rays share a common endpoint, and understand concepts of angle measurement.",
    learning_target: "I know a longer ray does not make a bigger angle.",
    skills: ["Concept of Angle", "Degrees as Circle Fractions", "Rays and Vertex"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["angles formed by two rays", "vertex", "one-degree angle", "1/360 of a circle", "circular arc"],
  },
  {
    code: "4.MD.C.6",
    name: "Which scale on the protractor",
    plain_reading:
      "Measure angles in whole-number degrees using a protractor; sketch angles of specified measure.",
    learning_target: "I can estimate acute or obtuse first so I pick the right scale.",
    skills: ["Using a Protractor", "Sketching Angles", "Estimating First"],
    science_tags: ["metacognition", "dual-coding"],
    match_keys: ["measure angles protractor", "whole-number degrees", "sketch angles", "acute obtuse", "wrong scale"],
  },
  {
    code: "4.MD.C.7",
    name: "Angles add, when they are adjacent",
    plain_reading:
      "Recognize angle measure as additive; solve addition and subtraction problems to find unknown angles on a diagram.",
    learning_target: "I can find a missing angle and check the parts actually touch.",
    skills: ["Additive Angle Measure", "Decomposing Angles", "Unknown Angles"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["angle measure is additive", "decompose", "unknown angle", "adjacent", "addition and subtraction problems"],
  },
  {
    code: "4.G.A.2",
    name: "Check the attributes one at a time",
    plain_reading:
      "Classify two-dimensional figures based on the presence or absence of parallel or perpendicular lines, or the presence or absence of angles of a specified size.",
    learning_target: "I can classify by testing attributes rather than by how it looks.",
    skills: ["Classification", "Parallel and Perpendicular", "Angle Size"],
    science_tags: ["dual-coding", "interleaving"],
    match_keys: ["classify two-dimensional figures", "parallel perpendicular", "angles of a specified size", "right triangle", "trapezoid"],
  },
  {
    code: "4.G.A.3",
    name: "Fold it to test the symmetry",
    plain_reading:
      "Recognize a line of symmetry for a two-dimensional figure; identify line-symmetric figures and draw lines of symmetry.",
    learning_target: "I can test a line of symmetry by folding instead of guessing.",
    skills: ["Lines of Symmetry", "Testing by Folding", "Multiple Lines"],
    science_tags: ["dual-coding", "metacognition"],
    match_keys: ["line of symmetry", "line-symmetric figures", "draw lines of symmetry", "fold", "reflect"],
  },
];

const unpacksData = [
  {
    standard_code: "4.OA.A.1",
    verbs: [
      { word: "Interpret", gloss: "read the equation as a comparison" },
      { word: "Represent", gloss: "write the statement as an equation" },
    ],
    concepts: ["Multiplicative comparison", "Times as many", "Additive versus multiplicative"],
    vocabulary: [
      { term: "multiplicative comparison", definition: "comparing by how many times bigger" },
      { term: "times as many", definition: "multiplied by that number" },
      { term: "factor", definition: "a number being multiplied" },
      { term: "product", definition: "the result of multiplying" },
    ],
    prior_skills: ["Multiply within 100", "Write equations", "Compare quantities"],
    prior_standards: [{ code: "3.OA.A.3", text: "Use multiplication and division to solve word problems within 100" }],
    future_standards: [{ code: "4.OA.A.2", text: "Multiply or divide to solve word problems involving multiplicative comparison" }],
    challenges: [
      { problem: "Four times as many is read as four more than, which needs a different operation entirely", fix: "Build both with cubes side by side. Four more than five is nine; four times as many is twenty. The gap is the lesson" },
      { problem: "The comparison is written as addition", fix: "Say it aloud as multiplication before writing anything" },
    ],
    mastery_statement: "Student can write a times-as-many statement as a multiplication equation.",
    ladder: [
      { name: "I can multiply", descriptor: "Computes products" },
      { name: "I can read the equation", descriptor: "Interprets as comparison" },
      { name: "I can spot the difference", descriptor: "Distinguishes from more than" },
      { name: "I can write the equation", descriptor: "Represents verbal comparisons" },
    ],
  },
  {
    standard_code: "4.OA.A.2",
    verbs: [
      { word: "Multiply", gloss: "or divide, as the relationship requires" },
      { word: "Distinguish", gloss: "multiplicative from additive" },
    ],
    concepts: ["Relationship before operation", "Comparison problems", "Unknown position"],
    vocabulary: [
      { term: "comparison", definition: "setting two quantities against each other" },
      { term: "additive", definition: "comparing by how much more" },
      { term: "multiplicative", definition: "comparing by how many times" },
      { term: "unknown", definition: "the quantity being found" },
    ],
    prior_skills: ["Interpret multiplicative comparison", "Solve word problems", "Use a symbol for the unknown"],
    prior_standards: [{ code: "4.OA.A.1", text: "Interpret a multiplication equation as a comparison" }],
    future_standards: [{ code: "5.NF.B.5", text: "Interpret multiplication as scaling" }],
    challenges: [
      { problem: "The operation most recently taught is defaulted to rather than the relationship being analyzed", fix: "Sort a mixed pile into additive or multiplicative before solving anything. Deciding is a separate step" },
      { problem: "Division is not recognized as a comparison operation", fix: "How many times bigger is a division question" },
    ],
    mastery_statement: "Student can decide whether a comparison is additive or multiplicative and solve accordingly.",
    ladder: [
      { name: "I can solve when told", descriptor: "Computes given the operation" },
      { name: "I can draw the comparison", descriptor: "Models the relationship" },
      { name: "I can decide which kind", descriptor: "Distinguishes the comparison type" },
      { name: "I can use division too", descriptor: "Handles both directions" },
    ],
  },
  {
    standard_code: "4.OA.B.4",
    verbs: [
      { word: "Find", gloss: "all factor pairs" },
      { word: "Recognize", gloss: "multiples" },
      { word: "Determine", gloss: "prime or composite" },
    ],
    concepts: ["Factor pairs", "Factors versus multiples", "Prime, composite and one"],
    vocabulary: [
      { term: "factor", definition: "a number that divides into it exactly" },
      { term: "multiple", definition: "a number it divides into" },
      { term: "prime", definition: "exactly two factors, one and itself" },
      { term: "composite", definition: "more than two factors" },
    ],
    prior_skills: ["Know multiplication facts", "Divide within 100", "Understand fact families"],
    prior_standards: [{ code: "3.OA.C.7", text: "Fluently multiply and divide within 100" }],
    future_standards: [{ code: "5.NF.A.1", text: "Add and subtract fractions with unlike denominators" }],
    challenges: [
      { problem: "Factors and multiples are constantly reversed", fix: "Factors are smaller and there are few; multiples are bigger and go on forever. Say which direction before answering" },
      { problem: "One is classified as prime, though it is neither prime nor composite", fix: "Prime means exactly two factors. One has one factor, so it fails the definition" },
    ],
    mastery_statement: "Student can list every factor pair of a number and classify it as prime or composite.",
    ladder: [
      { name: "I can find some factors", descriptor: "Identifies divisors" },
      { name: "I can find them in pairs", descriptor: "Works systematically" },
      { name: "I know when to stop", descriptor: "Recognizes completeness" },
      { name: "I can classify it", descriptor: "Determines prime or composite" },
    ],
  },
  {
    standard_code: "4.OA.C.5",
    verbs: [
      { word: "Generate", gloss: "the pattern from the rule" },
      { word: "Identify", gloss: "features the rule did not state" },
    ],
    concepts: ["Rule articulation", "Emergent features", "Reversibility"],
    vocabulary: [
      { term: "pattern", definition: "a sequence following a rule" },
      { term: "rule", definition: "what happens each step" },
      { term: "term", definition: "one number or shape in the sequence" },
      { term: "sequence", definition: "the ordered list" },
    ],
    prior_skills: ["Identify arithmetic patterns", "Explain patterns using properties", "Skip count"],
    prior_standards: [{ code: "3.OA.D.9", text: "Identify arithmetic patterns and explain them using properties of operations" }],
    future_standards: [{ code: "5.OA.B.3", text: "Generate two numerical patterns using two given rules" }],
    challenges: [
      { problem: "The pattern is continued correctly but the rule cannot be stated, which blocks them when it is reversed", fix: "Write the rule as a sentence, then run the pattern backwards using it. A rule you cannot state you cannot reverse" },
      { problem: "Emergent features go unnoticed", fix: "Ask what you notice that the rule never mentioned — every other one is even, say" },
    ],
    mastery_statement: "Student can generate a pattern, state its rule, and name a feature the rule did not specify.",
    ladder: [
      { name: "I can continue a pattern", descriptor: "Extends forwards" },
      { name: "I can state the rule", descriptor: "Articulates it" },
      { name: "I can run it backwards", descriptor: "Reverses using the rule" },
      { name: "I can spot extra features", descriptor: "Identifies emergent properties" },
    ],
  },
  {
    standard_code: "4.NBT.A.1",
    verbs: [
      { word: "Recognize", gloss: "the ten-times relationship" },
      { word: "Explain", gloss: "why it holds" },
    ],
    concepts: ["Ten times relationship", "Place value structure", "Explanation over recitation"],
    vocabulary: [
      { term: "place value", definition: "what a digit is worth where it sits" },
      { term: "ten times", definition: "multiplied by ten" },
      { term: "digit", definition: "a single number symbol" },
      { term: "period", definition: "a group of three places" },
    ],
    prior_skills: ["Understand hundreds, tens and ones", "Multiply by ten", "Read multi-digit numbers"],
    prior_standards: [{ code: "3.NBT.A.3", text: "Multiply one-digit whole numbers by multiples of 10" }],
    future_standards: [{ code: "5.NBT.A.1", text: "Recognize that a digit represents ten times what it represents to its right" }],
    challenges: [
      { problem: "The rule is recited but cannot be applied to explain why 700 is ten times 70", fix: "Blocks. Seven hundreds against seven tens, side by side. Reciting is not explaining, and the blocks force the second" },
      { problem: "The relationship is not seen as running both ways", fix: "Ten times to the left, a tenth to the right" },
    ],
    mastery_statement: "Student can explain why each place is ten times the place to its right, with a model.",
    ladder: [
      { name: "I know the place names", descriptor: "Identifies places" },
      { name: "I can say the rule", descriptor: "Recites the relationship" },
      { name: "I can show it", descriptor: "Models with blocks" },
      { name: "I can explain a case", descriptor: "Justifies why 700 is ten times 70" },
    ],
  },
  {
    standard_code: "4.NBT.A.2",
    verbs: [
      { word: "Read", gloss: "and write multi-digit numbers" },
      { word: "Compare", gloss: "using place value" },
    ],
    concepts: ["Three representations", "Periods", "The and rule"],
    vocabulary: [
      { term: "expanded form", definition: "the number split into place values and added" },
      { term: "standard form", definition: "the ordinary written number" },
      { term: "number name", definition: "the number in words" },
      { term: "period", definition: "thousands, millions, each a group of three" },
    ],
    prior_skills: ["Write numbers to 1000 three ways", "Compare three-digit numbers", "Know place value"],
    prior_standards: [{ code: "2.NBT.A.3", text: "Read and write numbers to 1000 using numerals, names and expanded form" }],
    future_standards: [{ code: "5.NBT.A.3", text: "Read, write and compare decimals to thousandths" }],
    challenges: [
      { problem: "And is inserted when writing whole number names, though it indicates a decimal point", fix: "Three thousand four hundred, not three thousand and four hundred. And is reserved, and saying why makes the rule stick" },
      { problem: "Comparison is attempted without aligning places", fix: "Count the digits first, then align" },
    ],
    mastery_statement: "Student can write a multi-digit number three ways and compare two by place value.",
    ladder: [
      { name: "I can read it", descriptor: "Reads multi-digit numerals" },
      { name: "I can write the words", descriptor: "Uses number names correctly" },
      { name: "I can expand it", descriptor: "Writes expanded form" },
      { name: "I can compare two", descriptor: "Justifies with place value" },
    ],
  },
  {
    standard_code: "4.NBT.A.3",
    verbs: [
      { word: "Round", gloss: "to the named place" },
      { word: "Use", gloss: "place value understanding" },
    ],
    concepts: ["Target place", "One rounding, not several", "Estimation"],
    vocabulary: [
      { term: "round", definition: "replace with the nearest convenient number" },
      { term: "place value", definition: "what each digit is worth" },
      { term: "benchmark", definition: "the nearest round number" },
      { term: "estimate", definition: "an approximate answer" },
    ],
    prior_skills: ["Round to 10 and 100", "Use a number line", "Know place value"],
    prior_standards: [{ code: "3.NBT.A.1", text: "Use place value understanding to round whole numbers to the nearest 10 or 100" }],
    future_standards: [{ code: "5.NBT.A.4", text: "Use place value understanding to round decimals to any place" }],
    challenges: [
      { problem: "Every digit is rounded, or rounding is applied repeatedly left to right, compounding the error", fix: "Underline the target place first. One rounding, then stop" },
      { problem: "The place is misidentified", fix: "Name the place aloud before looking at any digit" },
    ],
    mastery_statement: "Student can round a multi-digit number once, to the place specified.",
    ladder: [
      { name: "I can round to ten", descriptor: "Rounds to a familiar place" },
      { name: "I can find the target place", descriptor: "Identifies where to round" },
      { name: "I can round to any place", descriptor: "Applies generally" },
      { name: "I round once and stop", descriptor: "Avoids compounding" },
    ],
  },
  {
    standard_code: "4.NBT.B.4",
    verbs: [
      { word: "Add", gloss: "multi-digit numbers fluently" },
      { word: "Subtract", gloss: "including across zeros" },
      { word: "Estimate", gloss: "to check it is reasonable" },
    ],
    concepts: ["Standard algorithm", "Across zeros", "Reasonableness"],
    vocabulary: [
      { term: "standard algorithm", definition: "the usual written method" },
      { term: "regroup", definition: "trade between places" },
      { term: "fluently", definition: "accurately and efficiently" },
    ],
    prior_skills: ["Add and subtract within 1000", "Regroup", "Estimate"],
    prior_standards: [{ code: "3.NBT.A.2", text: "Fluently add and subtract within 1000" }],
    future_standards: [{ code: "5.NBT.B.5", text: "Fluently multiply multi-digit whole numbers using the standard algorithm" }],
    challenges: [
      { problem: "Subtraction across multiple zeros remains the highest-error case", fix: "Estimating first catches most of these. If the estimate says 3000 and the answer says 300, something is wrong" },
      { problem: "The algorithm runs with no sense of magnitude", fix: "Round both numbers and estimate before starting, every time" },
    ],
    mastery_statement: "Student can add and subtract multi-digit numbers fluently and check against an estimate.",
    ladder: [
      { name: "I can add with regrouping", descriptor: "Uses the algorithm" },
      { name: "I can subtract with regrouping", descriptor: "Trades correctly" },
      { name: "I can go across zeros", descriptor: "Handles the hard case" },
      { name: "I can check it is sensible", descriptor: "Estimates first" },
    ],
  },
  {
    standard_code: "4.NF.A.1",
    verbs: [
      { word: "Explain", gloss: "why the fractions are equal" },
      { word: "Use", gloss: "a visual model to justify" },
    ],
    concepts: ["Equivalence", "More pieces, same amount", "Scaling"],
    vocabulary: [
      { term: "equivalent", definition: "the same amount, written differently" },
      { term: "numerator", definition: "the top number" },
      { term: "denominator", definition: "the bottom number" },
      { term: "scaling", definition: "multiplying both parts by the same number" },
    ],
    prior_skills: ["Understand unit fractions", "Place fractions on a number line", "Partition equally"],
    prior_standards: [{ code: "3.NF.A.3", text: "Explain equivalence of fractions and compare fractions by reasoning about their size" }],
    future_standards: [{ code: "4.NF.A.2", text: "Compare two fractions with different numerators and different denominators" }],
    challenges: [
      { problem: "Multiplying by n over n is believed to make the fraction larger, since both numbers get bigger", fix: "The model shows the same amount cut into more pieces. Nothing was added — the cuts multiplied" },
      { problem: "Equivalence is a procedure with no picture behind it", fix: "Fold the same strip twice and see the pieces double while the shaded part does not move" },
    ],
    mastery_statement: "Student can explain with a model why a/b equals (n×a)/(n×b).",
    ladder: [
      { name: "I can name a fraction", descriptor: "Reads fractions" },
      { name: "I can find an equivalent", descriptor: "Generates equivalents" },
      { name: "I can show it with a model", descriptor: "Represents equivalence" },
      { name: "I can explain why", descriptor: "Justifies the equality" },
    ],
  },
  {
    standard_code: "4.NF.A.2",
    verbs: [
      { word: "Compare", gloss: "two fractions" },
      { word: "Create", gloss: "a common denominator or numerator" },
      { word: "Justify", gloss: "with a model" },
    ],
    concepts: ["Benchmarks", "Common denominators", "Comparing as wholes"],
    vocabulary: [
      { term: "common denominator", definition: "the same bottom number for both" },
      { term: "benchmark", definition: "a fraction you know well, like a half" },
      { term: "compare", definition: "decide which is greater" },
      { term: "justify", definition: "show why you are right" },
    ],
    prior_skills: ["Generate equivalent fractions", "Place fractions on a line", "Understand unit fractions"],
    prior_standards: [{ code: "4.NF.A.1", text: "Explain why a fraction is equivalent to another using visual models" }],
    future_standards: [{ code: "5.NF.A.1", text: "Add and subtract fractions with unlike denominators" }],
    challenges: [
      { problem: "Numerators and denominators are compared separately, so 3/8 is judged greater than 1/2 because 3 is more than 1", fix: "Benchmark against a half first. Three eighths is under, a half is exactly it — the question is answered before any common denominator" },
      { problem: "Common denominators are found procedurally with no sense of size", fix: "Estimate which is bigger before computing, then check" },
    ],
    mastery_statement: "Student can compare unlike fractions using benchmarks or common denominators and justify it.",
    ladder: [
      { name: "I can compare same denominators", descriptor: "Compares like fractions" },
      { name: "I can use a benchmark", descriptor: "Reasons against a half" },
      { name: "I can find a common denominator", descriptor: "Creates equivalents" },
      { name: "I can justify with a model", descriptor: "Explains the comparison" },
    ],
  },
  {
    standard_code: "4.NF.B.4",
    verbs: [
      { word: "Understand", gloss: "a/b as a multiple of 1/b" },
      { word: "Multiply", gloss: "a fraction by a whole number" },
    ],
    concepts: ["Multiples of unit fractions", "Repeated addition", "Word problems"],
    vocabulary: [
      { term: "multiple", definition: "the result of repeated addition" },
      { term: "unit fraction", definition: "one part, like a quarter" },
      { term: "product", definition: "the result of multiplying" },
    ],
    prior_skills: ["Understand unit fractions", "Multiply whole numbers", "Add fractions with like denominators"],
    prior_standards: [{ code: "4.NF.A.1", text: "Explain fraction equivalence using visual models" }],
    future_standards: [{ code: "5.NF.B.4", text: "Multiply a fraction by a fraction" }],
    challenges: [
      { problem: "Both numerator and denominator are multiplied by the whole number, shrinking the result instead of growing it", fix: "Three lots of one quarter, laid out. Three quarters, not three twelfths — the pieces did not change size" },
      { problem: "The connection to repeated addition is lost", fix: "Write it both ways every time, as a sum and as a product" },
    ],
    mastery_statement: "Student can multiply a fraction by a whole number and explain it as repeated addition.",
    ladder: [
      { name: "I can add like fractions", descriptor: "Adds within a denominator" },
      { name: "I can see a/b as multiples of 1/b", descriptor: "Understands the structure" },
      { name: "I can multiply", descriptor: "Computes the product" },
      { name: "I can solve word problems", descriptor: "Applies in context" },
    ],
  },
  {
    standard_code: "4.NF.C.5",
    verbs: [
      { word: "Express", gloss: "tenths as hundredths" },
      { word: "Add", gloss: "once the denominators match" },
    ],
    concepts: ["Tenths and hundredths", "Common denominator", "Equivalence in base ten"],
    vocabulary: [
      { term: "tenths", definition: "one whole split into ten" },
      { term: "hundredths", definition: "one whole split into a hundred" },
      { term: "equivalent", definition: "the same amount written differently" },
      { term: "denominator", definition: "the bottom number" },
    ],
    prior_skills: ["Generate equivalent fractions", "Add like fractions", "Understand place value"],
    prior_standards: [{ code: "4.NF.A.1", text: "Explain why a fraction is equivalent to another" }],
    future_standards: [{ code: "5.NBT.B.7", text: "Add, subtract, multiply and divide decimals to hundredths" }],
    challenges: [
      { problem: "3/10 and 4/100 are added directly to get 7/110, with no common denominator", fix: "Denominators are not added. A grid of a hundred squares shows why — thirty of them and four of them" },
      { problem: "The equivalence is done procedurally", fix: "Show three tenths as thirty hundredths on the grid, so it is seen not asserted" },
    ],
    mastery_statement: "Student can rewrite tenths as hundredths and add fractions with those denominators.",
    ladder: [
      { name: "I know tenths and hundredths", descriptor: "Reads both" },
      { name: "I can rewrite tenths", descriptor: "Finds the equivalent" },
      { name: "I can add them", descriptor: "Uses a common denominator" },
      { name: "I can explain why", descriptor: "Justifies with a model" },
    ],
  },
  {
    standard_code: "4.NF.C.7",
    verbs: [
      { word: "Compare", gloss: "two decimals" },
      { word: "Reason", gloss: "about the size of each place" },
      { word: "Justify", gloss: "with a model" },
    ],
    concepts: ["Decimal place value", "More digits is not more", "Justification"],
    vocabulary: [
      { term: "tenths", definition: "the first place after the point" },
      { term: "hundredths", definition: "the second place after the point" },
      { term: "compare", definition: "decide which is greater" },
      { term: "justify", definition: "explain how you know" },
    ],
    prior_skills: ["Compare fractions", "Understand tenths and hundredths", "Use place value"],
    prior_standards: [{ code: "4.NF.C.5", text: "Express a fraction with denominator 10 as an equivalent fraction with denominator 100" }],
    future_standards: [{ code: "5.NBT.A.3", text: "Read, write and compare decimals to thousandths" }],
    challenges: [
      { problem: "Whole-number thinking is applied, so 0.45 is judged greater than 0.5 because 45 is greater than 5", fix: "Shade both on hundredths grids. Forty-five squares against fifty. The picture settles it where the digits mislead" },
      { problem: "More digits is taken to mean a larger number", fix: "Write 0.5 as 0.50 and compare like with like" },
    ],
    mastery_statement: "Student can compare decimals to hundredths by reasoning about place value, not digit count.",
    ladder: [
      { name: "I can read a decimal", descriptor: "Names the places" },
      { name: "I can shade it on a grid", descriptor: "Models the value" },
      { name: "I can compare two", descriptor: "Reasons about size" },
      { name: "I can justify it", descriptor: "Explains with a model" },
    ],
  },
  {
    standard_code: "4.MD.A.1",
    verbs: [
      { word: "Know", gloss: "the relative sizes of units" },
      { word: "Express", gloss: "a larger unit as a smaller one" },
    ],
    concepts: ["Relative unit size", "Direction of conversion", "Equivalence tables"],
    vocabulary: [
      { term: "convert", definition: "change from one unit to another" },
      { term: "unit", definition: "what you are measuring in" },
      { term: "metric", definition: "the system using meters and grams" },
      { term: "customary", definition: "the system using feet and pounds" },
    ],
    prior_skills: ["Measure in standard units", "Multiply and divide", "Understand unit size"],
    prior_standards: [{ code: "3.MD.A.2", text: "Measure and estimate liquid volumes and masses using standard units" }],
    future_standards: [{ code: "5.MD.A.1", text: "Convert among different-sized standard measurement units" }],
    challenges: [
      { problem: "Division is used where multiplication is needed, because converting down feels like getting smaller", fix: "The unit got smaller, so there are more of them. Reasoning about the unit fixes the direction every time" },
      { problem: "Conversion factors are memorized without the relationship", fix: "A two-column table built by counting, not recited" },
    ],
    mastery_statement: "Student can convert to a smaller unit and explain why the number gets larger.",
    ladder: [
      { name: "I know the units", descriptor: "Names units in a system" },
      { name: "I know the relationships", descriptor: "Recalls conversion facts" },
      { name: "I can decide the direction", descriptor: "Reasons about unit size" },
      { name: "I can build a table", descriptor: "Records equivalent measures" },
    ],
  },
  {
    standard_code: "4.MD.A.2",
    verbs: [
      { word: "Solve", gloss: "measurement word problems" },
      { word: "Convert", gloss: "before combining" },
      { word: "Represent", gloss: "with a scaled diagram" },
    ],
    concepts: ["Mixed units", "Diagrams with scale", "Four operations"],
    vocabulary: [
      { term: "interval of time", definition: "how long between two moments" },
      { term: "liquid volume", definition: "how much liquid" },
      { term: "mass", definition: "how much matter" },
      { term: "scale", definition: "what a unit on the diagram represents" },
    ],
    prior_skills: ["Convert units", "Solve multi-step problems", "Draw diagrams"],
    prior_standards: [{ code: "4.MD.A.1", text: "Know relative sizes of measurement units and convert" }],
    future_standards: [{ code: "5.MD.A.1", text: "Use conversions in solving multi-step real world problems" }],
    challenges: [
      { problem: "Quantities are combined without converting first, so 3 feet and 8 inches becomes 11", fix: "Units checked before any arithmetic. Same unit, then add — in that order, always" },
      { problem: "The structure of the problem is not represented", fix: "A diagram with a stated scale before calculating" },
    ],
    mastery_statement: "Student can convert to a common unit and solve measurement problems across the four operations.",
    ladder: [
      { name: "I can solve one-step problems", descriptor: "Applies an operation" },
      { name: "I can check the units", descriptor: "Notices mismatches" },
      { name: "I can convert first", descriptor: "Makes units common" },
      { name: "I can draw the structure", descriptor: "Uses a scaled diagram" },
    ],
  },
  {
    standard_code: "4.MD.B.4",
    verbs: [
      { word: "Make", gloss: "a line plot in fractions" },
      { word: "Solve", gloss: "problems using the data" },
    ],
    concepts: ["Fractional scale", "Even intervals", "Adding and subtracting from data"],
    vocabulary: [
      { term: "line plot", definition: "a display where each mark is one measurement" },
      { term: "fraction of a unit", definition: "halves, quarters or eighths" },
      { term: "data", definition: "the measurements collected" },
      { term: "range", definition: "the spread from smallest to largest" },
    ],
    prior_skills: ["Measure to the quarter inch", "Make a line plot", "Add and subtract fractions"],
    prior_standards: [{ code: "3.MD.B.4", text: "Generate measurement data and show it on a line plot with halves and fourths" }],
    future_standards: [{ code: "5.MD.B.2", text: "Make a line plot to display a data set of measurements in fractions of a unit" }],
    challenges: [
      { problem: "Fractional intervals are spaced unevenly, which misrepresents the data", fix: "Squared paper with the fractions marked in advance. Even spacing is a property of the paper, not of care" },
      { problem: "The plot is made and never used", fix: "Every plot answers a question — the difference between longest and shortest, say" },
    ],
    mastery_statement: "Student can make an evenly scaled fractional line plot and solve problems from it.",
    ladder: [
      { name: "I can measure in fractions", descriptor: "Measures precisely" },
      { name: "I can mark the scale", descriptor: "Includes all fractional points" },
      { name: "I can plot evenly", descriptor: "Spaces intervals correctly" },
      { name: "I can solve from the data", descriptor: "Adds and subtracts fractions" },
    ],
  },
  {
    standard_code: "4.MD.C.5",
    verbs: [
      { word: "Recognize", gloss: "angles as figures made by two rays" },
      { word: "Understand", gloss: "a degree as 1/360 of a circle" },
    ],
    concepts: ["Angle as opening", "Degrees as circle fractions", "Ray length is irrelevant"],
    vocabulary: [
      { term: "angle", definition: "the opening between two rays" },
      { term: "ray", definition: "a line going on forever in one direction" },
      { term: "vertex", definition: "where the two rays meet" },
      { term: "degree", definition: "one three-hundred-and-sixtieth of a circle" },
    ],
    prior_skills: ["Recognize shapes by attributes", "Identify right angles", "Understand fractions"],
    prior_standards: [{ code: "4.G.A.1", text: "Draw points, lines, line segments, rays and angles" }],
    future_standards: [{ code: "4.MD.C.6", text: "Measure angles in whole-number degrees using a protractor" }],
    challenges: [
      { problem: "An angle with longer rays is believed to be larger", fix: "Two angles, same opening, different arm lengths, cut from card. Lay one over the other. The measure did not change" },
      { problem: "The degree is an arbitrary unit with no referent", fix: "A circle cut into 360. One of those is a degree, and now it means something" },
    ],
    mastery_statement: "Student can explain that an angle measures the opening, and a degree is 1/360 of a circle.",
    ladder: [
      { name: "I can find an angle", descriptor: "Identifies the figure" },
      { name: "I can name the parts", descriptor: "Uses ray and vertex" },
      { name: "I know length does not matter", descriptor: "Measures the opening" },
      { name: "I know what a degree is", descriptor: "Relates it to a circle" },
    ],
  },
  {
    standard_code: "4.MD.C.6",
    verbs: [
      { word: "Measure", gloss: "angles with a protractor" },
      { word: "Sketch", gloss: "an angle of a given size" },
      { word: "Align", gloss: "the vertex and baseline" },
    ],
    concepts: ["Protractor use", "Two scales", "Estimating first"],
    vocabulary: [
      { term: "protractor", definition: "the tool for measuring angles" },
      { term: "acute", definition: "less than ninety degrees" },
      { term: "obtuse", definition: "more than ninety degrees" },
      { term: "straight", definition: "exactly one hundred and eighty degrees" },
    ],
    prior_skills: ["Understand angle measure", "Recognize right angles", "Read a scale"],
    prior_standards: [{ code: "4.MD.C.5", text: "Recognize angles and understand concepts of angle measurement" }],
    future_standards: [{ code: "4.MD.C.7", text: "Recognize angle measure as additive and find unknown angles" }],
    challenges: [
      { problem: "The wrong scale is read, so a 50-degree angle is reported as 130", fix: "Estimate acute or obtuse first. If you said acute and read 130, you read the wrong scale — the estimate catches it" },
      { problem: "The vertex or baseline is misaligned", fix: "Two checks before reading — vertex on the cross, baseline on the zero" },
    ],
    mastery_statement: "Student can measure and sketch angles accurately, using an estimate to check the scale.",
    ladder: [
      { name: "I can place the protractor", descriptor: "Aligns vertex and baseline" },
      { name: "I can estimate first", descriptor: "Judges acute or obtuse" },
      { name: "I can read the right scale", descriptor: "Selects correctly" },
      { name: "I can sketch to a measure", descriptor: "Draws a specified angle" },
    ],
  },
  {
    standard_code: "4.MD.C.7",
    verbs: [
      { word: "Recognize", gloss: "angle measure as additive" },
      { word: "Decompose", gloss: "into non-overlapping parts" },
      { word: "Solve", gloss: "for an unknown angle" },
    ],
    concepts: ["Additivity", "Adjacency", "Unknown angles"],
    vocabulary: [
      { term: "additive", definition: "the parts add to the whole" },
      { term: "decompose", definition: "split into parts" },
      { term: "adjacent", definition: "next to, sharing a side" },
      { term: "unknown angle", definition: "the one being found" },
    ],
    prior_skills: ["Measure angles", "Add and subtract", "Recognize right and straight angles"],
    prior_standards: [{ code: "4.MD.C.6", text: "Measure angles in whole-number degrees using a protractor" }],
    future_standards: [{ code: "7.G.B.5", text: "Use facts about supplementary and complementary angles to solve for unknowns" }],
    challenges: [
      { problem: "Angles that are not adjacent are added, or any two angles are assumed to sum to 90 or 180", fix: "Do they share a side? If not, they do not combine. Check adjacency before adding anything" },
      { problem: "The unknown is guessed from the diagram's appearance", fix: "Diagrams are not to scale. Work from the numbers" },
    ],
    mastery_statement: "Student can add and subtract adjacent angle measures to find an unknown angle.",
    ladder: [
      { name: "I can measure two angles", descriptor: "Uses a protractor" },
      { name: "I can add them", descriptor: "Combines measures" },
      { name: "I can check they are adjacent", descriptor: "Tests before adding" },
      { name: "I can find the unknown", descriptor: "Subtracts to solve" },
    ],
  },
  {
    standard_code: "4.G.A.2",
    verbs: [
      { word: "Classify", gloss: "by attributes" },
      { word: "Recognize", gloss: "parallel and perpendicular lines" },
    ],
    concepts: ["Attribute testing", "Parallel and perpendicular", "Multiple categories"],
    vocabulary: [
      { term: "classify", definition: "sort into categories by a rule" },
      { term: "parallel", definition: "always the same distance apart" },
      { term: "perpendicular", definition: "meeting at a right angle" },
      { term: "trapezoid", definition: "a quadrilateral with at least one pair of parallel sides" },
    ],
    prior_skills: ["Identify shapes by attributes", "Recognize right angles", "Name quadrilaterals"],
    prior_standards: [{ code: "3.G.A.1", text: "Understand that shapes in different categories may share attributes" }],
    future_standards: [{ code: "5.G.B.3", text: "Understand that attributes of a category belong to all subcategories" }],
    challenges: [
      { problem: "Shapes are classified by overall appearance rather than by checking attributes one at a time", fix: "A checklist per shape — parallel sides, right angles, equal sides. Tick them off rather than looking" },
      { problem: "A shape is assumed to belong to only one category", fix: "A square is a rectangle and a rhombus. Categories overlap" },
    ],
    mastery_statement: "Student can classify a figure by systematically testing its attributes.",
    ladder: [
      { name: "I can name shapes", descriptor: "Recognizes common figures" },
      { name: "I can find parallel sides", descriptor: "Identifies attributes" },
      { name: "I can use a checklist", descriptor: "Tests systematically" },
      { name: "I can use several categories", descriptor: "Recognizes overlap" },
    ],
  },
  {
    standard_code: "4.G.A.3",
    verbs: [
      { word: "Recognize", gloss: "a line of symmetry" },
      { word: "Draw", gloss: "all the lines a figure has" },
    ],
    concepts: ["Line of symmetry", "Testing by folding", "More than one line"],
    vocabulary: [
      { term: "line of symmetry", definition: "a fold line where both halves match exactly" },
      { term: "symmetric", definition: "matching on both sides of a line" },
      { term: "fold", definition: "the test for symmetry" },
      { term: "reflect", definition: "flip across a line" },
    ],
    prior_skills: ["Recognize shapes", "Partition figures", "Compare halves"],
    prior_standards: [{ code: "3.G.A.2", text: "Partition shapes into parts with equal areas" }],
    future_standards: [{ code: "8.G.A.1", text: "Verify experimentally the properties of rotations, reflections and translations" }],
    challenges: [
      { problem: "A diagonal is drawn as a line of symmetry on a non-square rectangle", fix: "Fold it. The corners do not meet, and the fold settles the claim in a second" },
      { problem: "Only one line is found where several exist", fix: "Ask how many, not whether. A square has four" },
    ],
    mastery_statement: "Student can test a line of symmetry by folding and find all the lines a figure has.",
    ladder: [
      { name: "I can see symmetry", descriptor: "Recognizes symmetric figures" },
      { name: "I can fold to test", descriptor: "Verifies physically" },
      { name: "I can draw a line", descriptor: "Marks a line of symmetry" },
      { name: "I can find all of them", descriptor: "Identifies every line" },
    ],
  },
];

const blueprintsData = [
  {
    standard_code: "4.OA.A.1",
    title: "Four More Than, or Four Times",
    badge: "Grade 4",
    route_name: "Concrete-Representational-Abstract",
    route_line: "Build both → See the gap → Write the equation",
    success_criteria: ["Distinguishes times as many from more than", "Writes comparison equations", "Interprets equations as comparisons"],
    steps: [
      { name: "Retrieve Multiplication", minutes: 5, body: "Facts, briefly.", science_tag: "retrieval" },
      { name: "Build Both", minutes: 14, body: "Five cubes. Four more than is nine. Four times as many is twenty. Side by side, the gap is the lesson.", science_tag: "dual-coding" },
      { name: "Which Words Signal Which", minutes: 12, body: "Times as many, as many as, more than. Sorted before any problem.", science_tag: "elaboration" },
      { name: "Write the Equation", minutes: 12, body: "The verbal statement turned into multiplication.", science_tag: "elaboration" },
      { name: "Read One Backwards", minutes: 10, body: "Given the equation, say the comparison it makes.", science_tag: "metacognition" },
      { name: "Mixed Statements", minutes: 10, body: "Both kinds, unlabelled.", science_tag: "interleaving" },
      { name: "Write Your Own", minutes: 4, body: "One of each, with the same numbers.", science_tag: "elaboration" },
    ],
    ef_supports: ["Cubes", "Signal word sorting", "Equation frame", "Mixed statement set"],
    tech: "Linking cubes",
    tech_purpose: "The gap between nine and twenty has to be seen",
    ai_prompts: ["Generate additive and multiplicative comparison statements", "Write equations for backwards reading"],
    assessment: ["Check both kinds are distinguished", "Confirm equations use multiplication", "Test backwards reading"],
    why_it_works: ["Building both with the same starting number makes the difference unmissable", "Sorting the signal words separates the language from the arithmetic", "Reading an equation backwards tests interpretation rather than production", "Writing both from one pair of numbers proves the distinction held"],
  },
  {
    standard_code: "4.OA.A.2",
    title: "Decide the Relationship First",
    badge: "Grade 4",
    route_name: "Strategy Instruction",
    route_line: "Read the problem → Sort the comparison type → Then choose the operation",
    success_criteria: ["Distinguishes comparison types", "Multiplies or divides appropriately", "Uses a symbol for the unknown"],
    steps: [
      { name: "Retrieve Comparison Types", minutes: 5, body: "Additive and multiplicative.", science_tag: "retrieval" },
      { name: "The Most Recent Operation", minutes: 10, body: "Named as the default it is. Whatever was taught last week gets used, and the problem never gets read.", science_tag: "metacognition" },
      { name: "Sort Before Solving", minutes: 14, body: "A mixed pile, sorted into additive or multiplicative. No arithmetic yet.", science_tag: "metacognition" },
      { name: "Draw the Relationship", minutes: 12, body: "Bars, one against the other. The picture shows which kind it is.", science_tag: "dual-coding" },
      { name: "Now Choose", minutes: 12, body: "The operation follows from the relationship, not from the wording.", science_tag: "elaboration" },
      { name: "Division Compares Too", minutes: 10, body: "How many times bigger is a division question.", science_tag: "interleaving" },
      { name: "Move the Unknown", minutes: 4, body: "The same story, a different quantity missing.", science_tag: "interleaving" },
    ],
    ef_supports: ["Sorting mat", "Bar diagrams", "Operation-after-relationship rule", "Varied unknown position"],
    tech: "Bar model strips",
    tech_purpose: "The relationship is visible in a bar model before it is in an equation",
    ai_prompts: ["Generate mixed additive and multiplicative problems", "Write problems with the unknown in each position"],
    assessment: ["Check sorting precedes solving", "Confirm the diagram matches the type", "Vary the unknown"],
    why_it_works: ["Sorting with no arithmetic makes the relationship the only thing being decided", "Bar models show additive and multiplicative comparison as different shapes", "Naming the recent-operation default makes it recognizable", "Including division stops multiplication being the only comparison operation"],
  },
  {
    standard_code: "4.OA.B.4",
    title: "Work Up Until They Meet",
    badge: "Grade 4",
    route_name: "Explicit Instruction",
    route_line: "Start at one → Work up in pairs → Stop when they cross",
    success_criteria: ["Finds all factor pairs", "Knows when the list is complete", "Classifies prime or composite"],
    steps: [
      { name: "Retrieve Division Facts", minutes: 5, body: "The tool for testing factors.", science_tag: "retrieval" },
      { name: "Factors or Multiples", minutes: 12, body: "Reversed constantly. Factors are few and small; multiples are many and large. Say the direction before answering.", science_tag: "metacognition" },
      { name: "Work Up in Pairs", minutes: 14, body: "One and the number, two and its partner, three and its partner. When the pair crosses over, you are done.", science_tag: "dual-coding" },
      { name: "How Do I Know I Am Finished", minutes: 10, body: "The crossing point. That is the answer to the question the standard asks.", science_tag: "metacognition" },
      { name: "One Is Neither", minutes: 10, body: "Prime means exactly two factors. One has one. It fails the definition rather than being an exception.", science_tag: "elaboration" },
      { name: "Sort a Pile", minutes: 10, body: "Prime or composite, with the factor list as evidence.", science_tag: "interleaving" },
      { name: "Yesterday's Numbers", minutes: 4, body: "Factored again, cold.", science_tag: "spaced" },
    ],
    ef_supports: ["Pair-working template", "Factors-or-multiples direction check", "Crossing-point rule", "Sorting set"],
    tech: "Squared paper for arrays",
    tech_purpose: "A factor pair is an array, which makes completeness visible",
    ai_prompts: ["Generate numbers 1-100 for factoring", "Write factor and multiple sorting sets"],
    assessment: ["Check lists are complete", "Ask how they know they finished", "Test the classification of one"],
    why_it_works: ["Working up in pairs makes completeness a stopping rule rather than a hope", "The crossing point answers the standard's own question about knowing you are done", "Explaining why one fails the definition beats calling it an exception", "Naming the direction fixes the factor-multiple reversal"],
  },
  {
    standard_code: "4.OA.C.5",
    title: "Run It Backwards",
    badge: "Grade 4",
    route_name: "Strategy Instruction",
    route_line: "Generate from the rule → State the rule → Reverse it",
    success_criteria: ["Generates a pattern from a rule", "States the rule", "Identifies emergent features"],
    steps: [
      { name: "Retrieve Pattern Language", minutes: 5, body: "Rule, term, sequence.", science_tag: "retrieval" },
      { name: "Continue Without Knowing", minutes: 10, body: "The pattern extends correctly and the rule cannot be said. Then it is shown in reverse, and it stops.", science_tag: "metacognition" },
      { name: "Write the Rule as a Sentence", minutes: 12, body: "Add three each time. Not a demonstration — a sentence.", science_tag: "elaboration" },
      { name: "Run It Backwards", minutes: 14, body: "Using the stated rule. A rule you cannot state you cannot reverse, which is the test.", science_tag: "metacognition" },
      { name: "What Did the Rule Not Say", minutes: 12, body: "Every other term is even. The rule never mentioned that, and noticing it is the standard's second half.", science_tag: "elaboration" },
      { name: "Shape Patterns Too", minutes: 8, body: "The standard names both number and shape.", science_tag: "interleaving" },
      { name: "Give a Partner a Rule", minutes: 4, body: "They generate, you check.", science_tag: "collaborative" },
    ],
    ef_supports: ["Rule sentence frame", "Reversal task", "What-the-rule-did-not-say prompt", "Shape pattern set"],
    tech: "Pattern strips and shape tiles",
    tech_purpose: "The standard names shape patterns as well as number",
    ai_prompts: ["Generate rules producing emergent features", "Write patterns for reverse extension"],
    assessment: ["Ask for the rule as a sentence", "Test reversal", "Check an emergent feature is named"],
    why_it_works: ["Reversal is the test a stated rule passes and a copied pattern fails", "Writing the rule as a sentence forces articulation", "Asking what the rule did not say is the standard's own second demand", "Giving a partner a rule tests whether it was stated clearly enough to use"],
  },
  {
    standard_code: "4.NBT.A.1",
    title: "Seven Hundreds Against Seven Tens",
    badge: "Grade 4",
    route_name: "Concrete-Representational-Abstract",
    route_line: "Build both → Compare them → Explain the relationship",
    success_criteria: ["Recognizes the ten-times relationship", "Explains a specific case", "Applies to multi-digit numbers"],
    steps: [
      { name: "Retrieve Place Names", minutes: 5, body: "Ones, tens, hundreds, thousands.", science_tag: "retrieval" },
      { name: "Reciting Is Not Explaining", minutes: 8, body: "The rule said perfectly, and 700 against 70 unexplained. Naming the gap is the start.", science_tag: "metacognition" },
      { name: "Build Seven Hundreds", minutes: 14, body: "And seven tens beside it. Ten of these make one of those, physically.", science_tag: "dual-coding" },
      { name: "Explain This Case", minutes: 12, body: "Why is 700 ten times 70? In a sentence, using the blocks.", science_tag: "elaboration" },
      { name: "Both Directions", minutes: 10, body: "Ten times going left, a tenth going right.", science_tag: "elaboration" },
      { name: "Any Two Neighbors", minutes: 10, body: "The relationship holds everywhere, not just in the example.", science_tag: "interleaving" },
      { name: "Explain Without Blocks", minutes: 4, body: "Once the picture is internal.", science_tag: "spaced" },
    ],
    ef_supports: ["Base-ten blocks", "Explanation sentence frame", "Both-directions prompt", "Neighbor pairs"],
    tech: "Base-ten blocks including thousands",
    tech_purpose: "The relationship has to be built before it can be explained",
    ai_prompts: ["Generate place value explanation prompts", "Write neighbor-place comparison items"],
    assessment: ["Require an explanation of a specific case", "Check both directions", "Test without blocks last"],
    why_it_works: ["Building both quantities makes the relationship a thing rather than a rule", "Asking for a specific case defeats recitation", "Both directions shows the structure rather than one fact", "Removing the blocks last confirms the picture was internalized"],
  },
  {
    standard_code: "4.NBT.A.2",
    title: "No And in a Whole Number",
    badge: "Grade 4",
    route_name: "Explicit Instruction",
    route_line: "Read by periods → Write three ways → Compare by place",
    success_criteria: ["Writes numbers three ways", "Omits and in whole numbers", "Compares by place value"],
    steps: [
      { name: "Retrieve Place Value", minutes: 5, body: "Through the thousands.", science_tag: "retrieval" },
      { name: "Read by Periods", minutes: 12, body: "Three digits, then the period name. The commas are there to help.", science_tag: "dual-coding" },
      { name: "And Means a Point", minutes: 12, body: "It is reserved for the decimal. Three thousand four hundred, never three thousand and four hundred. The rule has a reason", science_tag: "elaboration" },
      { name: "Three Ways", minutes: 12, body: "Numeral, words, expanded. Same number, one row.", science_tag: "dual-coding" },
      { name: "Align and Compare", minutes: 12, body: "Count the digits, align the places, compare from the left.", science_tag: "metacognition" },
      { name: "Justify the Comparison", minutes: 8, body: "Because the ten-thousands digit is bigger. Place value in the reason.", science_tag: "elaboration" },
      { name: "Yesterday's Numbers", minutes: 4, body: "Written three ways again.", science_tag: "spaced" },
    ],
    ef_supports: ["Period reading routine", "No-and rule with its reason", "Three-column recording", "Alignment grid"],
    tech: "Place value charts with periods marked",
    tech_purpose: "Reading by periods needs the groups visible",
    ai_prompts: ["Generate multi-digit numbers for three-way writing", "Write comparison pairs with differing digit counts"],
    assessment: ["Check number names omit and", "Confirm expanded form", "Look for place value justification"],
    why_it_works: ["Reading by periods makes long numbers manageable in threes", "Giving the and rule a reason makes it memorable rather than arbitrary", "Aligning before comparing removes the visual cause of errors", "Requiring a justification keeps comparison tied to place value"],
  },
  {
    standard_code: "4.NBT.A.3",
    title: "Underline the Place, Round Once",
    badge: "Grade 4",
    route_name: "Explicit Instruction",
    route_line: "Name the place → Find the neighbors → Round once and stop",
    success_criteria: ["Rounds to any named place", "Rounds once", "Uses place value reasoning"],
    steps: [
      { name: "Retrieve Rounding to Ten", minutes: 5, body: "The familiar case.", science_tag: "retrieval" },
      { name: "Rounding Twice", minutes: 12, body: "Left to right, repeatedly. The error compounds and the answer drifts a long way.", science_tag: "metacognition" },
      { name: "Underline the Target", minutes: 12, body: "Before looking at any digit. One place, named first.", science_tag: "dual-coding" },
      { name: "The Two Neighbors", minutes: 12, body: "Which two round numbers does it sit between? Both written down.", science_tag: "dual-coding" },
      { name: "Round Once and Stop", minutes: 12, body: "The rule with a boundary attached.", science_tag: "metacognition" },
      { name: "Any Place at All", minutes: 10, body: "Thousands, ten-thousands. The routine does not change.", science_tag: "interleaving" },
      { name: "Round to Estimate", minutes: 4, body: "Applied in a problem, which is what rounding is for.", science_tag: "interleaving" },
    ],
    ef_supports: ["Underline-the-target routine", "Two-neighbors box", "Round-once rule", "Estimation application"],
    tech: "Blank number lines",
    tech_purpose: "Proximity reasoning still helps at larger magnitudes",
    ai_prompts: ["Generate rounding items across several places", "Write estimation problems requiring rounding"],
    assessment: ["Check only the target place changed", "Watch for repeated rounding", "Test several places"],
    why_it_works: ["Underlining first makes the target place a decision rather than an assumption", "Demonstrating compounded rounding shows why once is the rule", "Writing both neighbors keeps it a comparison", "Applying it to estimation gives rounding a purpose"],
  },
  {
    standard_code: "4.NBT.B.4",
    title: "Estimate, Then Subtract Across the Zeros",
    badge: "Grade 4",
    route_name: "Explicit Instruction",
    route_line: "Estimate first → Work the algorithm → Check against the estimate",
    success_criteria: ["Adds and subtracts fluently", "Handles zeros", "Checks reasonableness"],
    steps: [
      { name: "Retrieve Regrouping", minutes: 5, body: "The trade, from grade 3.", science_tag: "retrieval" },
      { name: "Estimate First, Always", minutes: 12, body: "Round both, estimate, write it down. This is what catches the errors, and it comes before the algorithm.", science_tag: "metacognition" },
      { name: "Across the Zeros", minutes: 16, body: "The highest-error case, taught directly rather than met by accident. Blocks first, then notation.", science_tag: "dual-coding" },
      { name: "Why the Trade Works", minutes: 12, body: "A thousand becomes ten hundreds. The zeros are not obstacles, they are empty places waiting.", science_tag: "elaboration" },
      { name: "Check Against the Estimate", minutes: 10, body: "If the estimate said three thousand and the answer says three hundred, something went wrong.", science_tag: "metacognition" },
      { name: "Mixed Practice", minutes: 10, body: "With and without zeros, addition and subtraction.", science_tag: "interleaving" },
      { name: "Yesterday's Problems", minutes: 4, body: "Revisited cold.", science_tag: "spaced" },
    ],
    ef_supports: ["Estimate-first box", "Across-zeros practice set", "Base-ten blocks", "Reasonableness check"],
    tech: "Base-ten blocks and squared paper",
    tech_purpose: "The trade across zeros has to be seen once to make sense",
    ai_prompts: ["Generate subtraction problems across multiple zeros", "Write estimation prompts"],
    assessment: ["Check an estimate was made first", "Test across zeros specifically", "Confirm the check happened"],
    why_it_works: ["Estimating first catches the errors the algorithm produces, which is the deck's own point", "Teaching the zeros case directly beats meeting it by accident", "Explaining the trade makes the zeros comprehensible rather than obstructive", "Comparing to the estimate is a self-check that needs no adult"],
  },
  {
    standard_code: "4.NF.A.1",
    title: "Same Strip, More Cuts",
    badge: "Grade 4",
    route_name: "Concrete-Representational-Abstract",
    route_line: "Shade the strip → Cut it again → See the shading has not moved",
    success_criteria: ["Generates equivalent fractions", "Justifies with a model", "Explains why the value holds"],
    steps: [
      { name: "Retrieve Unit Fractions", minutes: 5, body: "One part of an equally split whole.", science_tag: "retrieval" },
      { name: "Bigger Numbers, Bigger Fraction", minutes: 12, body: "The belief stated plainly. Both numbers got bigger, so surely it grew. Then tested.", science_tag: "metacognition" },
      { name: "Shade, Then Cut Again", minutes: 16, body: "One half shaded. Fold once more — two quarters, and the shading has not moved. Nothing was added; the cuts multiplied.", science_tag: "dual-coding" },
      { name: "What Changed, What Did Not", minutes: 12, body: "The number of pieces changed. The amount did not. Two columns.", science_tag: "elaboration" },
      { name: "Generate Equivalents", minutes: 12, body: "Times two, times three, times four. The same strip each time.", science_tag: "elaboration" },
      { name: "Explain It in Writing", minutes: 8, body: "Why does multiplying both keep it equal?", science_tag: "metacognition" },
      { name: "Yesterday's Fractions", minutes: 4, body: "Equivalents generated cold.", science_tag: "spaced" },
    ],
    ef_supports: ["Paper strips for folding", "What-changed columns", "Equivalence generation sheet", "Written explanation"],
    tech: "Paper strips and fraction bars",
    tech_purpose: "The shading not moving is the whole argument, and it has to be seen",
    ai_prompts: ["Generate equivalent fraction families", "Write explanation prompts for equivalence"],
    assessment: ["Ask why, not just for equivalents", "Check the model supports the claim", "Read the written explanations"],
    why_it_works: ["Folding again while the shading stays put disproves the bigger-numbers belief physically", "Separating what changed from what did not names the confusion precisely", "Using one strip throughout keeps the whole constant", "A written explanation is where understanding separates from procedure"],
  },
  {
    standard_code: "4.NF.A.2",
    title: "Benchmark It Against a Half",
    badge: "Grade 4",
    route_name: "Strategy Instruction",
    route_line: "Try the benchmark → If that settles it, stop → Otherwise find a common denominator",
    success_criteria: ["Compares unlike fractions", "Uses benchmarks", "Justifies with a model"],
    steps: [
      { name: "Retrieve Equivalence", minutes: 5, body: "From the previous standard.", science_tag: "retrieval" },
      { name: "Three Eighths Beats a Half", minutes: 12, body: "Because three beats one. The claim tested on a fraction wall, and it fails visibly.", science_tag: "metacognition" },
      { name: "Compare to a Half First", minutes: 14, body: "Under, over, or exactly. Often that settles it with no arithmetic at all.", science_tag: "elaboration" },
      { name: "When the Benchmark Fails", minutes: 12, body: "Both over a half. Now a common denominator is needed, and it is needed for a reason.", science_tag: "elaboration" },
      { name: "Find the Common Denominator", minutes: 12, body: "Using the equivalence work already done.", science_tag: "dual-coding" },
      { name: "Justify With a Model", minutes: 10, body: "The standard asks for it. A drawing beside the symbols.", science_tag: "dual-coding" },
      { name: "Estimate Before Computing", minutes: 4, body: "Which do you think is bigger? Then check.", science_tag: "metacognition" },
    ],
    ef_supports: ["Fraction wall", "Benchmark-first routine", "Common denominator method", "Model requirement"],
    tech: "Fraction walls and strips",
    tech_purpose: "Comparing needs a visual that shows relative size",
    ai_prompts: ["Generate comparison pairs settled by benchmarks", "Write pairs requiring common denominators"],
    assessment: ["Check the benchmark was tried first", "Confirm a model accompanies the answer", "Watch for separate numerator comparison"],
    why_it_works: ["Benchmarking answers many comparisons with no computation, which builds number sense", "Testing the three-beats-one claim on a wall makes the error visible", "Introducing common denominators only when benchmarks fail gives them a purpose", "Requiring a model is what the standard asks and it keeps size in view"],
  },
  {
    standard_code: "4.NF.B.4",
    title: "Three Lots of One Quarter",
    badge: "Grade 4",
    route_name: "Concrete-Representational-Abstract",
    route_line: "Lay out the copies → Count the pieces → Write it as a product",
    success_criteria: ["Sees a/b as multiples of 1/b", "Multiplies a fraction by a whole number", "Solves word problems"],
    steps: [
      { name: "Retrieve Unit Fractions", minutes: 5, body: "One quarter, one fifth, one eighth.", science_tag: "retrieval" },
      { name: "Both Numbers Multiplied", minutes: 12, body: "Three times one quarter given as three twelfths. Lay out three quarters and count. The pieces did not change size.", science_tag: "metacognition" },
      { name: "Lay Out the Copies", minutes: 14, body: "Three quarter-pieces, physically. Three quarters, and nothing else it could be.", science_tag: "dual-coding" },
      { name: "Sum and Product", minutes: 12, body: "A quarter plus a quarter plus a quarter, and three times a quarter. Written both ways, every time.", science_tag: "elaboration" },
      { name: "Beyond One Whole", minutes: 12, body: "Five quarters. The pieces keep their size and the total passes one.", science_tag: "elaboration" },
      { name: "Word Problems", minutes: 10, body: "Where the multiplication comes from a situation.", science_tag: "interleaving" },
      { name: "Yesterday's Products", minutes: 4, body: "Recomputed cold.", science_tag: "spaced" },
    ],
    ef_supports: ["Fraction pieces", "Sum-and-product recording", "Beyond-one examples", "Word problem set"],
    tech: "Fraction circles or bars",
    tech_purpose: "Laying out copies shows the piece size is unchanged",
    ai_prompts: ["Generate fraction times whole number problems", "Write word problems in context"],
    assessment: ["Watch for multiplying the denominator", "Check both notations", "Test beyond one whole"],
    why_it_works: ["Laying out three quarter-pieces makes three twelfths impossible to believe", "Writing sum and product together keeps the connection to repeated addition", "Going beyond one whole stops fractions being read as parts of a single object", "The physical pieces keep the unit size constant, which is what the error violates"],
  },
  {
    standard_code: "4.NF.C.5",
    title: "Thirty Hundredths, Not Three",
    badge: "Grade 4",
    route_name: "Multiple Representations",
    route_line: "Shade the tenths → Count them in hundredths → Then add",
    success_criteria: ["Rewrites tenths as hundredths", "Adds with a common denominator", "Justifies with a grid"],
    steps: [
      { name: "Retrieve Equivalence", minutes: 5, body: "Times ten on both parts.", science_tag: "retrieval" },
      { name: "Seven Over One Hundred and Ten", minutes: 12, body: "Denominators added. Shown, then tested on a grid. Denominators are not addends.", science_tag: "metacognition" },
      { name: "Shade Three Tenths", minutes: 14, body: "On a hundred grid. Count the small squares — thirty. Seen, not asserted.", science_tag: "dual-coding" },
      { name: "Now Add", minutes: 12, body: "Thirty hundredths and four hundredths. Thirty-four.", science_tag: "elaboration" },
      { name: "Why Ten Times", minutes: 10, body: "Each tenth is ten hundredths, so the count multiplies by ten.", science_tag: "elaboration" },
      { name: "Practice Both Directions", minutes: 10, body: "Tenths to hundredths, and recognizing hundredths that are whole tenths.", science_tag: "interleaving" },
      { name: "Yesterday's Sums", minutes: 4, body: "Recomputed cold.", science_tag: "spaced" },
    ],
    ef_supports: ["Hundred grids", "Shading routine", "Both-directions practice", "Denominator rule"],
    tech: "Printed hundred grids",
    tech_purpose: "Thirty small squares is the argument",
    ai_prompts: ["Generate tenths and hundredths addition problems", "Write grid shading tasks"],
    assessment: ["Watch for added denominators", "Check the conversion is understood not memorized", "Confirm grid justification"],
    why_it_works: ["Counting thirty small squares makes the equivalence visible rather than procedural", "Testing the added-denominators error on a grid shows it fails", "Explaining why ten times connects it to place value", "Working both directions prevents a one-way procedure"],
  },
  {
    standard_code: "4.NF.C.7",
    title: "Forty-Five Squares Against Fifty",
    badge: "Grade 4",
    route_name: "Multiple Representations",
    route_line: "Shade both → Compare the shading → Then compare the digits",
    success_criteria: ["Compares decimals correctly", "Reasons about place value", "Justifies with a model"],
    steps: [
      { name: "Retrieve Tenths and Hundredths", minutes: 5, body: "What each place is worth.", science_tag: "retrieval" },
      { name: "Nought Point Four Five Is Bigger", minutes: 12, body: "Because forty-five beats five. The claim stated, then shaded on grids. Forty-five squares against fifty.", science_tag: "metacognition" },
      { name: "Shade Both", minutes: 14, body: "Two hundred grids. The picture settles what the digits confuse.", science_tag: "dual-coding" },
      { name: "Write It as 0.50", minutes: 12, body: "Same value, now comparable digit by digit. The trailing zero is a translator.", science_tag: "elaboration" },
      { name: "Compare From the Left", minutes: 12, body: "Tenths first. Five tenths against four tenths, and it is decided.", science_tag: "metacognition" },
      { name: "More Digits Is Not More", minutes: 8, body: "Stated as a rule, once the evidence is in.", science_tag: "elaboration" },
      { name: "Mixed Comparisons", minutes: 4, body: "Including equal values written differently.", science_tag: "interleaving" },
    ],
    ef_supports: ["Hundred grids", "Trailing zero technique", "Compare-from-the-left routine", "Mixed comparison set"],
    tech: "Printed hundred grids and decimal cards",
    tech_purpose: "The shading decides what digit-counting gets wrong",
    ai_prompts: ["Generate decimal pairs where digit count misleads", "Write equal-value pairs written differently"],
    assessment: ["Test pairs like 0.45 and 0.5", "Check the model is used", "Confirm comparison starts at tenths"],
    why_it_works: ["Shading both makes the comparison a matter of area rather than digits", "Writing 0.50 aligns the places so digit comparison becomes valid", "Comparing from the left mirrors whole-number place value correctly", "Stating the more-digits rule after the evidence makes it a conclusion"],
  },
  {
    standard_code: "4.MD.A.1",
    title: "Smaller Unit, So More of Them",
    badge: "Grade 4",
    route_name: "Concrete Practice",
    route_line: "Hold both units → Decide the direction → Then compute",
    success_criteria: ["Knows relative unit sizes", "Converts in the right direction", "Records in a table"],
    steps: [
      { name: "Retrieve the Units", minutes: 5, body: "Within one system, largest to smallest.", science_tag: "retrieval" },
      { name: "Converting Down Feels Smaller", minutes: 12, body: "So division gets used. The instinct named, then tested.", science_tag: "metacognition" },
      { name: "Hold Both", minutes: 12, body: "A meter stick and a centimeter. Smaller unit, so more of them. The hands settle the direction.", science_tag: "dual-coding" },
      { name: "Predict Bigger or Smaller", minutes: 12, body: "Will the number grow or shrink? Answered before any arithmetic.", science_tag: "metacognition" },
      { name: "Then Compute", minutes: 12, body: "The operation follows the prediction.", science_tag: "elaboration" },
      { name: "Two-Column Table", minutes: 10, body: "Equivalent measures recorded, as the standard asks.", science_tag: "dual-coding" },
      { name: "Both Systems", minutes: 4, body: "Metric and customary, same reasoning.", science_tag: "interleaving" },
    ],
    ef_supports: ["Physical unit comparison", "Predict-first routine", "Two-column tables", "Both-system practice"],
    tech: "Meter sticks, rulers, measuring jugs",
    tech_purpose: "Holding both units decides the direction faster than any rule",
    ai_prompts: ["Generate conversion items in both systems", "Write predict-the-direction prompts"],
    assessment: ["Check the prediction precedes the calculation", "Watch for wrong-direction errors", "Review tables"],
    why_it_works: ["Holding both units makes the relationship physical rather than remembered", "Predicting bigger or smaller separates direction from computation", "Naming the converting-down instinct makes it correctable", "A two-column table is the standard's own recording form"],
  },
  {
    standard_code: "4.MD.A.2",
    title: "Same Unit, Then Add",
    badge: "Grade 4",
    route_name: "Strategy Instruction",
    route_line: "Check the units → Convert → Draw it → Solve",
    success_criteria: ["Converts before combining", "Uses a scaled diagram", "Solves across the four operations"],
    steps: [
      { name: "Retrieve Conversion", minutes: 5, body: "From the previous standard.", science_tag: "retrieval" },
      { name: "Three Feet Plus Eight Inches", minutes: 12, body: "Eleven. The error shown, then measured out. Eleven of what?", science_tag: "metacognition" },
      { name: "Units First, Always", minutes: 12, body: "Circle every unit in the problem before touching the numbers.", science_tag: "metacognition" },
      { name: "Convert to One", minutes: 12, body: "Everything in the same unit, then the arithmetic is ordinary.", science_tag: "elaboration" },
      { name: "Draw With a Scale", minutes: 14, body: "A diagram with a stated scale, which the standard names.", science_tag: "dual-coding" },
      { name: "Time, Money, Volume, Mass", minutes: 10, body: "All four named in the standard, all four practiced.", science_tag: "interleaving" },
      { name: "Label the Answer", minutes: 4, body: "With its unit. An unlabelled measurement answer is incomplete.", science_tag: "elaboration" },
    ],
    ef_supports: ["Circle-the-units routine", "Convert-first rule", "Scaled diagram template", "Unit labelling"],
    tech: "Rulers, clocks, coins, measuring jugs",
    tech_purpose: "The standard names five quantity types, so the tools vary",
    ai_prompts: ["Generate mixed-unit word problems", "Write problems across time, money, volume and mass"],
    assessment: ["Watch for combining without converting", "Check diagrams carry a scale", "Confirm units on answers"],
    why_it_works: ["Measuring out three feet and eight inches shows eleven is meaningless", "Circling units before the numbers makes the check automatic", "A scale on the diagram keeps the representation honest", "Covering all five quantity types matches the standard's breadth"],
  },
  {
    standard_code: "4.MD.B.4",
    title: "Even Spacing Tells the Truth",
    badge: "Grade 4",
    route_name: "Multiple Representations",
    route_line: "Measure in eighths → Mark every interval → Solve from the data",
    success_criteria: ["Plots fractional measurements", "Spaces intervals evenly", "Adds and subtracts from the data"],
    steps: [
      { name: "Retrieve Fractions on a Line", minutes: 5, body: "Equal intervals, from grade 3.", science_tag: "retrieval" },
      { name: "Uneven Spacing Lies", minutes: 12, body: "The same data plotted evenly and unevenly. The shape changes, and the shape is what a plot is for.", science_tag: "metacognition" },
      { name: "Mark Every Interval First", minutes: 12, body: "Halves, quarters, eighths, before any data is placed.", science_tag: "dual-coding" },
      { name: "Measure and Plot", minutes: 14, body: "To the eighth, plotted where it belongs.", science_tag: "dual-coding" },
      { name: "Longest Minus Shortest", minutes: 12, body: "Fraction subtraction from real data.", science_tag: "elaboration" },
      { name: "What Does the Spread Show", minutes: 10, body: "Reading the plot, not just building it.", science_tag: "elaboration" },
      { name: "Add to It Later", minutes: 4, body: "New measurements on the same plot.", science_tag: "spaced" },
    ],
    ef_supports: ["Pre-marked fractional scales", "Squared paper", "Longest-minus-shortest prompt", "Spread questions"],
    tech: "Rulers marked in eighths and squared paper",
    tech_purpose: "Eighths need a ruler that shows them",
    ai_prompts: ["Generate measurement data in eighths", "Write fraction problems from plot data"],
    assessment: ["Check intervals are even", "Confirm all fractional points are marked", "Test the subtraction"],
    why_it_works: ["Comparing even and uneven plots of one data set shows spacing carries meaning", "Marking the scale before plotting makes evenness structural", "Subtracting longest from shortest uses the data rather than decorating it", "Reading the spread is the reason for making the plot"],
  },
  {
    standard_code: "4.MD.C.5",
    title: "Long Arms, Same Angle",
    badge: "Grade 4",
    route_name: "Concrete Practice",
    route_line: "Cut two angles → Lay one on the other → Name what is measured",
    success_criteria: ["Recognizes angles as two rays", "Knows length does not affect measure", "Relates degrees to a circle"],
    steps: [
      { name: "Retrieve Rays and Vertex", minutes: 5, body: "The parts of an angle.", science_tag: "retrieval" },
      { name: "Longer Means Bigger", minutes: 12, body: "The belief stated. Two card angles, same opening, different arm lengths.", science_tag: "metacognition" },
      { name: "Lay One on the Other", minutes: 14, body: "They match. The arms differ and the angle does not. The measure is the opening.", science_tag: "dual-coding" },
      { name: "Cut a Circle Into 360", minutes: 12, body: "Or see one already cut. One of those is a degree, and now the unit means something.", science_tag: "elaboration" },
      { name: "Fractions of a Turn", minutes: 12, body: "A quarter turn is ninety. Half is one hundred and eighty. Degrees as circle fractions.", science_tag: "elaboration" },
      { name: "Estimate in Turns", minutes: 8, body: "About a quarter? More than half?", science_tag: "metacognition" },
      { name: "Find Angles Around You", minutes: 4, body: "In the room, estimated in turns.", science_tag: "interleaving" },
    ],
    ef_supports: ["Card angles with differing arm lengths", "360-part circle", "Turn fraction language", "Estimation prompts"],
    tech: "Card angles and a divided circle",
    tech_purpose: "Overlaying two angles is the demonstration",
    ai_prompts: ["Generate angle sets with varying arm lengths", "Write turn-fraction estimation items"],
    assessment: ["Test the long-arms belief directly", "Ask what a degree is", "Check turn estimates"],
    why_it_works: ["Overlaying two angles with different arms settles the belief in one action", "A circle cut into 360 gives the degree a referent", "Turn fractions connect angle measure to fractions already known", "Estimating in turns builds judgment before the protractor arrives"],
  },
  {
    standard_code: "4.MD.C.6",
    title: "Guess Acute or Obtuse First",
    badge: "Grade 4",
    route_name: "Concrete Practice",
    route_line: "Estimate the type → Align carefully → Read the matching scale",
    success_criteria: ["Aligns the protractor", "Selects the correct scale", "Sketches angles to a measure"],
    steps: [
      { name: "Retrieve Angle Types", minutes: 5, body: "Acute, right, obtuse, straight.", science_tag: "retrieval" },
      { name: "One Hundred and Thirty for Fifty", minutes: 12, body: "The wrong scale read. Common, and entirely preventable.", science_tag: "metacognition" },
      { name: "Estimate First", minutes: 12, body: "Acute or obtuse, before the protractor touches the page. If you said acute and read 130, you read the wrong scale.", science_tag: "metacognition" },
      { name: "Two Alignment Checks", minutes: 12, body: "Vertex on the cross, baseline on the zero. Both, every time.", science_tag: "dual-coding" },
      { name: "Read the Matching Scale", minutes: 12, body: "The one that agrees with your estimate.", science_tag: "elaboration" },
      { name: "Sketch to a Measure", minutes: 12, body: "Given seventy degrees, draw it. The reverse direction.", science_tag: "interleaving" },
      { name: "Yesterday's Angles", minutes: 4, body: "Remeasured cold.", science_tag: "spaced" },
    ],
    ef_supports: ["Estimate-first routine", "Two alignment checks", "Scale matching prompt", "Sketching tasks"],
    tech: "Protractors with both scales visible",
    tech_purpose: "The two scales are the source of the error, so they stay visible",
    ai_prompts: ["Generate angles for measuring across both scales", "Write sketch-to-measure tasks"],
    assessment: ["Check the estimate precedes measuring", "Watch for wrong-scale readings", "Test sketching"],
    why_it_works: ["An estimate makes the wrong scale detectable by the student rather than the teacher", "Two alignment checks address the other main source of error", "Sketching reverses the direction and tests understanding of the scale", "Naming the classic 130-for-50 error makes it recognizable"],
  },
  {
    standard_code: "4.MD.C.7",
    title: "Do They Share a Side",
    badge: "Grade 4",
    route_name: "Strategy Instruction",
    route_line: "Check adjacency → Add or subtract → Find the unknown",
    success_criteria: ["Recognizes angle measure as additive", "Checks adjacency", "Solves for unknown angles"],
    steps: [
      { name: "Retrieve Angle Measurement", minutes: 5, body: "From the protractor work.", science_tag: "retrieval" },
      { name: "Adding Angles That Do Not Touch", minutes: 12, body: "Or assuming any two make ninety. Both errors named, both from skipping the check.", science_tag: "metacognition" },
      { name: "Do They Share a Side", minutes: 14, body: "Asked before adding anything. If not, they do not combine, and the arithmetic never starts.", science_tag: "metacognition" },
      { name: "Decompose a Right Angle", minutes: 12, body: "Into two parts, measured, and added back. Additivity demonstrated.", science_tag: "dual-coding" },
      { name: "Find the Unknown", minutes: 12, body: "The whole minus the known part.", science_tag: "elaboration" },
      { name: "Diagrams Are Not to Scale", minutes: 8, body: "Work from the numbers, not the picture.", science_tag: "metacognition" },
      { name: "Mixed Diagrams", minutes: 4, body: "Some adjacent, some not.", science_tag: "interleaving" },
    ],
    ef_supports: ["Adjacency check", "Decomposition tasks", "Not-to-scale warning", "Mixed diagram set"],
    tech: "Printed angle diagrams",
    tech_purpose: "Adjacency has to be judged from a figure",
    ai_prompts: ["Generate diagrams with adjacent and non-adjacent angles", "Write unknown angle problems"],
    assessment: ["Check adjacency is tested", "Watch for assumed right angles", "Confirm unknowns are computed"],
    why_it_works: ["Asking about a shared side is a check students can run before any arithmetic", "Decomposing and recombining demonstrates additivity rather than asserting it", "Warning that diagrams are not to scale stops measurement by eye", "Mixed diagrams stop adjacency being assumed"],
  },
  {
    standard_code: "4.G.A.2",
    title: "Tick the Attributes Off",
    badge: "Grade 4",
    route_name: "Explicit Instruction",
    route_line: "Test each attribute → Record the results → Classify from the list",
    success_criteria: ["Classifies by attributes", "Identifies parallel and perpendicular", "Recognizes overlapping categories"],
    steps: [
      { name: "Retrieve Attributes", minutes: 5, body: "Sides, angles, parallel, perpendicular.", science_tag: "retrieval" },
      { name: "Classifying by Look", minutes: 12, body: "It looks like a rectangle. Then a rotated one appears and the method fails.", science_tag: "metacognition" },
      { name: "A Checklist per Shape", minutes: 14, body: "Parallel sides? Right angles? Equal sides? Ticked off one at a time, not judged at a glance.", science_tag: "dual-coding" },
      { name: "Find the Parallel Sides", minutes: 12, body: "Tested by extending them, not by eye.", science_tag: "dual-coding" },
      { name: "More Than One Category", minutes: 12, body: "A square is a rectangle and a rhombus. Categories overlap, which the checklist reveals.", science_tag: "elaboration" },
      { name: "Right Triangles", minutes: 8, body: "A category named in the standard specifically.", science_tag: "interleaving" },
      { name: "Rotated Shapes", minutes: 4, body: "The checklist survives rotation; appearance does not.", science_tag: "interleaving" },
    ],
    ef_supports: ["Attribute checklist", "Parallel line test", "Overlapping category examples", "Rotated shape set"],
    tech: "Shape cards and rulers",
    tech_purpose: "Parallel and perpendicular have to be tested, not judged",
    ai_prompts: ["Generate shapes in unusual orientations", "Write classification tasks with overlapping categories"],
    assessment: ["Check the checklist is used", "Present rotated shapes", "Test multiple category membership"],
    why_it_works: ["A checklist replaces the glance that fails under rotation", "Testing parallel lines by extending them is evidence rather than impression", "Overlapping categories emerge naturally from attribute testing", "Rotated shapes are where appearance-based classification breaks"],
  },
  {
    standard_code: "4.G.A.3",
    title: "Fold It and Find Out",
    badge: "Grade 4",
    route_name: "Concrete Practice",
    route_line: "Propose a line → Fold along it → Keep it only if the halves match",
    success_criteria: ["Recognizes lines of symmetry", "Tests by folding", "Finds all lines"],
    steps: [
      { name: "Retrieve Symmetry", minutes: 4, body: "Both halves matching.", science_tag: "retrieval" },
      { name: "The Diagonal of a Rectangle", minutes: 12, body: "Proposed as a line of symmetry. Fold it. The corners miss, and the claim dies in a second.", science_tag: "metacognition" },
      { name: "Fold to Test", minutes: 14, body: "Every proposed line. Folding is the test, and it is faster than arguing.", science_tag: "dual-coding" },
      { name: "How Many, Not Whether", minutes: 12, body: "A square has four. Asking how many finds the ones that get missed.", science_tag: "elaboration" },
      { name: "Draw Them All", minutes: 12, body: "On a figure, every line marked.", science_tag: "dual-coding" },
      { name: "Shapes With None", minutes: 8, body: "Some figures have no line of symmetry, and that is an answer.", science_tag: "interleaving" },
      { name: "Yesterday's Shapes", minutes: 4, body: "Retested cold.", science_tag: "spaced" },
    ],
    ef_supports: ["Cut-out shapes for folding", "How-many prompt", "All-lines marking", "No-symmetry examples"],
    tech: "Paper shapes that can be folded",
    tech_purpose: "Folding is the test, and it needs paper",
    ai_prompts: ["Generate figures with varying numbers of symmetry lines", "Write symmetry claims to test"],
    assessment: ["Check folding is used to test", "Ask how many, not whether", "Include figures with none"],
    why_it_works: ["Folding settles the rectangle diagonal claim in one action", "Asking how many rather than whether surfaces the missed lines", "Testing every proposed line makes symmetry checkable rather than intuited", "Figures with no symmetry make it a real question rather than a hunt"],
  },
];

seedStandardsBatch({
  label: "Batch 17 — grade 4 mathematics",
  standardsData,
  unpacksData,
  blueprintsData,
});
