// @ts-nocheck
/**
 * Batch 16: grade 4 writing, speaking and language.
 *
 * Completes grade 4 ELA. The deck's grade 4 misconceptions are mostly about
 * effort mistaken for quality: longer equated with better, long words reached
 * for to sound advanced, revision that stops at spelling, paraphrase that
 * swaps synonyms and keeps the sentence. Each blueprint separates the two.
 *
 * American spellings throughout.
 *
 *   bun run scripts/seed-standards-batch-16.ts
 */
import { seedStandardsBatch } from "./lib/seed-standards-batch";

const standardsData = [
  {
    code: "W.4.3",
    name: "Give the big moment more room",
    plain_reading:
      "Write narratives to develop real or imagined experiences or events using effective technique, descriptive details, and clear event sequences.",
    learning_target: "I can slow down for the moment that matters and hurry past the walk to school.",
    skills: ["Pacing", "Dialogue and Description", "Sensory Detail"],
    science_tags: ["elaboration", "dual-coding"],
    match_keys: ["narrative", "pacing", "dialogue", "sensory details", "transitional phrases", "orient the reader"],
  },
  {
    code: "W.4.4",
    name: "Longer is not better",
    plain_reading:
      "Produce clear and coherent writing in which the development and organization are appropriate to task, purpose, and audience.",
    learning_target: "I can develop an idea instead of padding it.",
    skills: ["Coherence", "Development", "Task and Audience"],
    science_tags: ["metacognition", "elaboration"],
    match_keys: ["clear and coherent", "development and organization", "task purpose audience", "padding", "style"],
  },
  {
    code: "W.4.5",
    name: "Revision that moves things",
    plain_reading:
      "With guidance and support from peers and adults, develop and strengthen writing by planning, revising, editing, and rewriting.",
    learning_target: "I can cut, add and reorganize, not just fix spelling.",
    skills: ["Revising", "Rewriting", "Using Feedback"],
    science_tags: ["metacognition", "collaborative"],
    match_keys: ["plan revise edit rewrite", "try a new approach", "peer feedback", "reorganize", "strengthen writing"],
  },
  {
    code: "W.4.6",
    name: "Type a page in one sitting",
    plain_reading:
      "With some guidance and support from adults, use technology to produce and publish writing and to interact and collaborate with others.",
    learning_target: "I can type fast enough that it stops getting in the way.",
    skills: ["Keyboarding", "Digital Publishing", "Collaboration"],
    science_tags: ["spaced", "collaborative"],
    match_keys: ["technology to produce and publish", "interact and collaborate", "keyboarding", "type a page in one sitting"],
  },
  {
    code: "W.4.7",
    name: "A question a fact cannot answer",
    plain_reading:
      "Conduct short research projects that build knowledge through investigation of different aspects of a topic.",
    learning_target: "I can ask something big enough to research and small enough to finish.",
    skills: ["Research Questions", "Investigating Aspects", "Narrowing"],
    science_tags: ["metacognition", "interleaving"],
    match_keys: ["short research projects", "different aspects of a topic", "investigation", "narrow a research question"],
  },
  {
    code: "W.4.8",
    name: "Paraphrase means change the sentence",
    plain_reading:
      "Recall relevant information from experiences or gather relevant information from print and digital sources; take notes and provide a list of sources.",
    learning_target: "I can say it my own way, not swap a few words.",
    skills: ["Paraphrasing", "Categorizing Notes", "Citing Sources"],
    science_tags: ["retrieval", "metacognition"],
    match_keys: ["paraphrase", "take notes", "categorize", "list of sources", "plagiarism", "print and digital"],
  },
  {
    code: "W.4.9",
    name: "Introduce the quotation, then explain it",
    plain_reading:
      "Draw evidence from literary or informational texts to support analysis, reflection, and research.",
    learning_target: "I can set a quotation up and say what it shows.",
    skills: ["Drawing Evidence", "Using Quotations", "Analysis"],
    science_tags: ["elaboration", "interleaving"],
    match_keys: ["draw evidence from texts", "support analysis", "reflection", "quotation", "cite"],
  },
  {
    code: "W.4.10",
    name: "Plan in proportion to the clock",
    plain_reading:
      "Write routinely over extended and shorter time frames for a range of discipline-specific tasks, purposes, and audiences.",
    learning_target: "I can plan briefly when the time is short and properly when it is not.",
    skills: ["Writing Routinely", "Time Frames", "Discipline-Specific Tasks"],
    science_tags: ["metacognition", "spaced"],
    match_keys: ["extended and shorter time frames", "write routinely", "on-demand writing", "discipline-specific"],
  },
  {
    code: "SL.4.1",
    name: "Come having actually read it",
    plain_reading:
      "Engage effectively in a range of collaborative discussions on grade 4 topics and texts, building on others' ideas and expressing their own clearly.",
    learning_target: "I can bring something from the reading rather than a general reaction.",
    skills: ["Preparation", "Discussion Roles", "Building on Ideas"],
    science_tags: ["collaborative", "retrieval"],
    match_keys: ["come to discussions prepared", "assigned roles", "pose and respond to questions", "review key ideas", "building on others"],
  },
  {
    code: "SL.4.2",
    name: "Paraphrase, not parrot",
    plain_reading:
      "Paraphrase portions of a text read aloud or information presented in diverse media and formats.",
    learning_target: "I can restate it in my own words without changing what it meant.",
    skills: ["Paraphrasing", "Accurate Restating", "Diverse Media"],
    science_tags: ["retrieval", "metacognition"],
    match_keys: ["paraphrase portions", "text read aloud", "diverse media and formats", "restate accurately"],
  },
  {
    code: "SL.4.3",
    name: "Judge the reasoning, not the confidence",
    plain_reading:
      "Identify the reasons and evidence a speaker provides to support particular points.",
    learning_target: "I can separate how sure someone sounds from how good their reasons are.",
    skills: ["Identifying Reasons", "Evaluating Support", "Critical Listening"],
    science_tags: ["metacognition", "collaborative"],
    match_keys: ["reasons and evidence a speaker provides", "support particular points", "evaluate support", "delivery"],
  },
  {
    code: "SL.4.4",
    name: "Talk to people, not from notes",
    plain_reading:
      "Report on a topic or text, tell a story, or recount an experience in an organized manner, using appropriate facts and relevant, descriptive details.",
    learning_target: "I can present from notes without reading them word for word.",
    skills: ["Organized Presentation", "Supporting Main Ideas", "Pace"],
    science_tags: ["spaced", "collaborative"],
    match_keys: ["report in an organized manner", "appropriate facts", "support main ideas or themes", "understandable pace"],
  },
  {
    code: "SL.4.5",
    name: "Media that develops the idea",
    plain_reading:
      "Add audio recordings and visual displays to presentations when appropriate to enhance the development of main ideas or themes.",
    learning_target: "I can add something that develops my point rather than decorating it.",
    skills: ["Audio and Visual Media", "Enhancing Main Ideas", "Purposeful Selection"],
    science_tags: ["dual-coding", "metacognition"],
    match_keys: ["audio recordings visual displays", "enhance development", "main ideas or themes", "animations distract"],
  },
  {
    code: "SL.4.6",
    name: "Formal without being stilted",
    plain_reading:
      "Differentiate between contexts that call for formal English and situations where informal discourse is appropriate.",
    learning_target: "I can switch register without sounding like a robot.",
    skills: ["Formal and Informal", "Register", "Context"],
    science_tags: ["elaboration", "collaborative"],
    match_keys: ["formal English", "informal discourse", "context", "register", "differentiate contexts"],
  },
  {
    code: "L.4.2",
    name: "The comma before and, when it earns it",
    plain_reading:
      "Demonstrate command of the conventions of standard English capitalization, punctuation, and spelling when writing, including commas in compound sentences and quotations.",
    learning_target: "I can tell when the comma before and is needed and when it is not.",
    skills: ["Compound Sentences", "Quotation Punctuation", "Capitalization"],
    science_tags: ["metacognition", "spaced"],
    match_keys: ["comma before a coordinating conjunction", "compound sentence", "quotation marks", "direct speech", "capitalization"],
  },
  {
    code: "L.4.3",
    name: "Precise beats impressive",
    plain_reading:
      "Use knowledge of language and its conventions when writing, speaking, reading, or listening, choosing words and phrases to convey ideas precisely.",
    learning_target: "I can pick the exact word rather than the longest one.",
    skills: ["Precision", "Concision", "Punctuation for Effect"],
    science_tags: ["elaboration", "metacognition"],
    match_keys: ["convey ideas precisely", "punctuation for effect", "formal English", "concise", "word choice"],
  },
  {
    code: "L.4.4",
    name: "Greek and Latin roots, then verify",
    plain_reading:
      "Determine or clarify the meaning of unknown and multiple-meaning words and phrases based on grade 4 reading and content.",
    learning_target: "I can use roots to get a meaning, then check it fits.",
    skills: ["Greek and Latin Roots", "Context Clues", "Verification"],
    science_tags: ["elaboration", "metacognition"],
    match_keys: ["Greek and Latin affixes and roots", "context as a clue", "reference materials", "verify the meaning", "multiple-meaning"],
  },
  {
    code: "L.4.5",
    name: "Similes, metaphors and idioms",
    plain_reading:
      "Demonstrate understanding of figurative language, word relationships, and nuances in word meanings.",
    learning_target: "I can explain what a figure of speech actually means.",
    skills: ["Figurative Language", "Idioms and Adages", "Antonyms and Synonyms"],
    science_tags: ["elaboration", "dual-coding"],
    match_keys: ["simile metaphor", "idiom adage proverb", "antonym synonym", "figurative language", "nuances"],
  },
  {
    code: "L.4.6",
    name: "Words that survive the test",
    plain_reading:
      "Acquire and use accurately grade-appropriate general academic and domain-specific words and phrases.",
    learning_target: "I can use an academic word in my own writing weeks later.",
    skills: ["Academic Vocabulary", "Domain-Specific Words", "Precise Signalling"],
    science_tags: ["retrieval", "spaced"],
    match_keys: ["general academic and domain-specific", "acquire and use accurately", "precise actions emotions states", "signal words"],
  },
];

const unpacksData = [
  {
    standard_code: "W.4.3",
    verbs: [
      { word: "Orient", gloss: "set the scene for the reader" },
      { word: "Develop", gloss: "build the events with technique" },
      { word: "Pace", gloss: "give moments the room they deserve" },
    ],
    concepts: ["Pacing", "Dialogue as development", "Sensory detail"],
    vocabulary: [
      { term: "orient", definition: "give the reader their bearings at the start" },
      { term: "pacing", definition: "how much room each moment gets" },
      { term: "transitional phrase", definition: "words that move the reader through time" },
      { term: "sensory detail", definition: "what could be seen, heard or felt" },
    ],
    prior_skills: ["Write a narrative in order", "Use temporal words", "Include thoughts and feelings"],
    prior_standards: [{ code: "W.3.3", text: "Write narratives using descriptions of actions, thoughts and feelings" }],
    future_standards: [{ code: "W.5.3", text: "Write narratives using pacing and a variety of transitional words and phrases" }],
    challenges: [
      { problem: "Every event gets equal time, so the important moment gets no more space than the walk to school", fix: "Mark the moment that matters before drafting, then give it three times the words" },
      { problem: "Dialogue is used to report rather than to develop", fix: "A line of dialogue has to reveal something the narration did not" },
    ],
    mastery_statement: "Student can pace a narrative so the significant moment carries the most detail.",
    ladder: [
      { name: "I can write events in order", descriptor: "Sequences correctly" },
      { name: "I can add detail", descriptor: "Uses description" },
      { name: "I can use dialogue", descriptor: "Develops through speech" },
      { name: "I can control the pacing", descriptor: "Weights the important moment" },
    ],
  },
  {
    standard_code: "W.4.4",
    verbs: [
      { word: "Produce", gloss: "clear and coherent writing" },
      { word: "Match", gloss: "development to task and audience" },
      { word: "Develop", gloss: "rather than pad" },
    ],
    concepts: ["Coherence", "Development versus padding", "Style"],
    vocabulary: [
      { term: "coherent", definition: "holding together so a reader can follow" },
      { term: "task", definition: "what you were asked to do" },
      { term: "audience", definition: "who reads it" },
      { term: "style", definition: "how the writing sounds" },
    ],
    prior_skills: ["Write for a named audience", "Organize a piece", "Revise for coherence"],
    prior_standards: [{ code: "W.3.4", text: "Produce writing in which the development and organization are appropriate to task and purpose" }],
    future_standards: [{ code: "W.5.4", text: "Produce clear and coherent writing appropriate to task, purpose and audience" }],
    challenges: [
      { problem: "Longer is equated with better, so pieces get padded rather than developed", fix: "Cut a third and see whether anything was lost. Usually nothing was, and that is the lesson" },
      { problem: "Style is not adjusted at all between tasks", fix: "Name the audience and the register together before drafting" },
    ],
    mastery_statement: "Student can develop writing to suit task and audience without padding it.",
    ladder: [
      { name: "I can write a piece", descriptor: "Produces writing" },
      { name: "I can organize it", descriptor: "Structures coherently" },
      { name: "I can develop an idea", descriptor: "Adds substance not length" },
      { name: "I can match the audience", descriptor: "Adjusts style and development" },
    ],
  },
  {
    standard_code: "W.4.5",
    verbs: [
      { word: "Revise", gloss: "cut, add and reorganize" },
      { word: "Rewrite", gloss: "try a different approach" },
      { word: "Edit", gloss: "fix conventions, last" },
    ],
    concepts: ["Revision beyond spelling", "Trying a new approach", "Feedback"],
    vocabulary: [
      { term: "revise", definition: "change what the writing says or how it is ordered" },
      { term: "rewrite", definition: "start a section again a different way" },
      { term: "edit", definition: "correct spelling and punctuation" },
      { term: "feedback", definition: "what a reader tells you" },
    ],
    prior_skills: ["Distinguish revising from editing", "Use peer feedback", "Plan before drafting"],
    prior_standards: [{ code: "W.3.5", text: "Develop and strengthen writing by planning, revising and editing" }],
    future_standards: [{ code: "W.5.5", text: "Develop and strengthen writing by planning, revising, editing, rewriting or trying a new approach" }],
    challenges: [
      { problem: "Revision stops at fixing spelling", fix: "Three required moves before any editing — one cut, one addition, one reorganization" },
      { problem: "A weak section is patched rather than rewritten", fix: "Rewriting a paragraph from scratch is often faster than repairing it" },
    ],
    mastery_statement: "Student can revise by cutting, adding and reorganizing before editing conventions.",
    ladder: [
      { name: "I can fix spelling", descriptor: "Edits conventions" },
      { name: "I can add detail", descriptor: "Develops content" },
      { name: "I can cut and reorder", descriptor: "Revises structure" },
      { name: "I can rewrite a section", descriptor: "Tries a new approach" },
    ],
  },
  {
    standard_code: "W.4.6",
    verbs: [
      { word: "Produce", gloss: "with technology" },
      { word: "Collaborate", gloss: "with others" },
      { word: "Type", gloss: "a page in one sitting" },
    ],
    concepts: ["Keyboarding fluency", "Publishing", "Collaboration"],
    vocabulary: [
      { term: "publish", definition: "make it available to read" },
      { term: "collaborate", definition: "work on it together" },
      { term: "keyboarding", definition: "typing with enough fluency not to interrupt thought" },
    ],
    prior_skills: ["Use digital tools", "Draft on paper", "Basic keyboarding"],
    prior_standards: [{ code: "W.3.6", text: "Use technology to produce and publish writing and to interact and collaborate" }],
    future_standards: [{ code: "W.5.6", text: "Use technology to produce and publish writing, demonstrating sufficient keyboarding" }],
    challenges: [
      { problem: "Keyboarding speed becomes the bottleneck on composition", fix: "It needs its own practice time. Ten minutes of typing drill is not writing time wasted, it is writing time bought" },
      { problem: "Collaboration means one typist and three spectators", fix: "Named sections with named owners" },
    ],
    mastery_statement: "Student can type a page in one sitting and publish and collaborate using technology.",
    ladder: [
      { name: "I can type slowly", descriptor: "Locates keys" },
      { name: "I can type without looking", descriptor: "Builds fluency" },
      { name: "I can type a page", descriptor: "Sustains composition" },
      { name: "I can collaborate", descriptor: "Works with others digitally" },
    ],
  },
  {
    standard_code: "W.4.7",
    verbs: [
      { word: "Conduct", gloss: "a short research project" },
      { word: "Investigate", gloss: "different aspects" },
      { word: "Narrow", gloss: "to a real question" },
    ],
    concepts: ["Researchable question", "Aspects of a topic", "Investigation"],
    vocabulary: [
      { term: "research", definition: "finding out systematically" },
      { term: "investigate", definition: "look into carefully" },
      { term: "aspect", definition: "one side of a topic" },
      { term: "question", definition: "what you are trying to answer" },
    ],
    prior_skills: ["Narrow a topic", "Use multiple sources", "Take notes"],
    prior_standards: [{ code: "W.3.7", text: "Conduct short research projects that build knowledge about a topic" }],
    future_standards: [{ code: "W.5.7", text: "Conduct short research projects using several sources to investigate different aspects" }],
    challenges: [
      { problem: "Questions are chosen that a single fact answers, which cannot sustain a project", fix: "The test — if one sentence finishes it, it is not a research question. How and why questions survive" },
      { problem: "Only one aspect is investigated", fix: "Three aspects named at the start, so the project has a shape" },
    ],
    mastery_statement: "Student can frame a question that needs investigating and explore several aspects of it.",
    ladder: [
      { name: "I can pick a topic", descriptor: "Chooses an area" },
      { name: "I can ask a question", descriptor: "Frames an enquiry" },
      { name: "I can test the question", descriptor: "Checks it needs more than a fact" },
      { name: "I can cover aspects", descriptor: "Investigates several sides" },
    ],
  },
  {
    standard_code: "W.4.8",
    verbs: [
      { word: "Gather", gloss: "relevant information" },
      { word: "Paraphrase", gloss: "in your own structure" },
      { word: "List", gloss: "the sources used" },
    ],
    concepts: ["Real paraphrase", "Categorizing", "Source lists"],
    vocabulary: [
      { term: "paraphrase", definition: "say it your own way, with your own sentence" },
      { term: "categorize", definition: "sort into groups" },
      { term: "source list", definition: "where each piece came from" },
      { term: "relevant", definition: "actually about your question" },
    ],
    prior_skills: ["Take brief notes", "Sort into categories", "Avoid copying"],
    prior_standards: [{ code: "W.3.8", text: "Take brief notes on sources and sort evidence into categories" }],
    future_standards: [{ code: "W.5.8", text: "Summarize or paraphrase information in notes and provide a list of sources" }],
    challenges: [
      { problem: "Paraphrasing becomes swapping a few synonyms while keeping the original sentence structure", fix: "Cover the source, then write. A paraphrase built from memory has your sentence shape, not theirs" },
      { problem: "Sources are used and never recorded", fix: "The source goes on the note as it is taken, not afterwards" },
    ],
    mastery_statement: "Student can paraphrase in their own sentence structure and list where each fact came from.",
    ladder: [
      { name: "I can find information", descriptor: "Gathers relevant material" },
      { name: "I can take notes", descriptor: "Records in phrases" },
      { name: "I can paraphrase properly", descriptor: "Changes structure, not just words" },
      { name: "I can list my sources", descriptor: "Credits appropriately" },
    ],
  },
  {
    standard_code: "W.4.9",
    verbs: [
      { word: "Draw", gloss: "evidence from texts" },
      { word: "Introduce", gloss: "the quotation" },
      { word: "Explain", gloss: "what it shows" },
    ],
    concepts: ["Evidence for analysis", "Quotation sandwich", "Reflection"],
    vocabulary: [
      { term: "evidence", definition: "the part of the text that supports your point" },
      { term: "analysis", definition: "explaining how or why" },
      { term: "reflection", definition: "your considered response" },
      { term: "quotation", definition: "the author's exact words" },
    ],
    prior_skills: ["Cite evidence", "Distinguish claim from support", "Write about texts"],
    prior_standards: [{ code: "RI.4.1", text: "Refer to details and examples when explaining and when drawing inferences" }],
    future_standards: [{ code: "W.5.9", text: "Draw evidence from literary or informational texts to support analysis and reflection" }],
    challenges: [
      { problem: "Quotations are dropped in with no introduction or explanation, leaving the reader to connect them", fix: "Three parts every time — set it up, quote it, say what it shows. A bare quotation does no work" },
      { problem: "The quotation is explained by being restated", fix: "Explaining says why it matters, not what it said" },
    ],
    mastery_statement: "Student can introduce a quotation, present it, and explain what it demonstrates.",
    ladder: [
      { name: "I can find evidence", descriptor: "Locates support" },
      { name: "I can quote it", descriptor: "Uses exact words" },
      { name: "I can introduce it", descriptor: "Sets up the quotation" },
      { name: "I can explain it", descriptor: "Says what it shows" },
    ],
  },
  {
    standard_code: "W.4.10",
    verbs: [
      { word: "Write", gloss: "routinely" },
      { word: "Adapt", gloss: "to the time available" },
    ],
    concepts: ["Extended and short frames", "Proportionate planning", "Discipline-specific writing"],
    vocabulary: [
      { term: "routinely", definition: "regularly, as a habit" },
      { term: "extended", definition: "over days or weeks" },
      { term: "time frame", definition: "how long you have" },
      { term: "discipline-specific", definition: "belonging to one subject" },
    ],
    prior_skills: ["Adjust process to time", "Write across genres", "Plan proportionately"],
    prior_standards: [{ code: "W.3.10", text: "Write routinely over extended and shorter time frames" }],
    future_standards: [{ code: "W.5.10", text: "Write routinely over extended and shorter time frames for a range of tasks" }],
    challenges: [
      { problem: "On-demand writing gets the same lengthy planning as a research paper, and time runs out", fix: "A planning budget written on the page — five minutes of a forty-minute task" },
      { problem: "Writing in science and history is treated as unrelated to writing in English", fix: "The same standards, different content. Name that" },
    ],
    mastery_statement: "Student can budget planning to the time available and write across subjects.",
    ladder: [
      { name: "I can write regularly", descriptor: "Writes routinely" },
      { name: "I can plan a long piece", descriptor: "Uses extended process" },
      { name: "I can budget my planning", descriptor: "Plans proportionately" },
      { name: "I can write in any subject", descriptor: "Adapts to discipline" },
    ],
  },
  {
    standard_code: "SL.4.1",
    verbs: [
      { word: "Prepare", gloss: "by reading beforehand" },
      { word: "Pose", gloss: "specific questions" },
      { word: "Review", gloss: "key ideas at the end" },
    ],
    concepts: ["Preparation", "Roles", "Explaining ideas in light of discussion"],
    vocabulary: [
      { term: "prepared", definition: "having read and thought about it" },
      { term: "role", definition: "your job in the discussion" },
      { term: "pose", definition: "put a question to the group" },
      { term: "elaborate", definition: "say more about it" },
    ],
    prior_skills: ["Come prepared", "Build on others' ideas", "Ask open questions"],
    prior_standards: [{ code: "SL.3.1", text: "Engage effectively in collaborative discussions, coming to discussions prepared" }],
    future_standards: [{ code: "SL.5.1", text: "Engage effectively in collaborative discussions, drawing on preparation" }],
    challenges: [
      { problem: "Students participate without having read, contributing only general reactions", fix: "Every contribution names a page. A general reaction cannot" },
      { problem: "Roles are assigned and ignored", fix: "The role has a visible artefact — the summarizer produces a summary" },
    ],
    mastery_statement: "Student can arrive prepared, carry a role, and explain their ideas in light of the discussion.",
    ladder: [
      { name: "I can join in", descriptor: "Participates" },
      { name: "I can come prepared", descriptor: "Reads beforehand" },
      { name: "I can carry a role", descriptor: "Fulfils an assigned job" },
      { name: "I can review and revise", descriptor: "Explains ideas in light of discussion" },
    ],
  },
  {
    standard_code: "SL.4.2",
    verbs: [
      { word: "Paraphrase", gloss: "restate accurately in your words" },
    ],
    concepts: ["Paraphrase versus repetition", "Accuracy", "Diverse media"],
    vocabulary: [
      { term: "paraphrase", definition: "say the same thing in different words" },
      { term: "restate", definition: "say it again" },
      { term: "diverse media", definition: "video, audio, images and speech" },
      { term: "format", definition: "the way it was presented" },
    ],
    prior_skills: ["Determine main ideas from listening", "Take listening notes", "Retell"],
    prior_standards: [{ code: "SL.3.2", text: "Determine the main ideas and supporting details of a text read aloud" }],
    future_standards: [{ code: "SL.5.2", text: "Summarize a written text read aloud or information presented in diverse media" }],
    challenges: [
      { problem: "Paraphrase becomes verbatim repetition, or drifts far enough to change the meaning", fix: "Two failure modes, so two checks — different words, same meaning. Both have to hold" },
      { problem: "Paraphrasing is attempted while still listening", fix: "Listen, then paraphrase. Not at once" },
    ],
    mastery_statement: "Student can restate what they heard in different words without changing the meaning.",
    ladder: [
      { name: "I can repeat it", descriptor: "Recalls the content" },
      { name: "I can use different words", descriptor: "Changes the wording" },
      { name: "I can keep the meaning", descriptor: "Stays accurate" },
      { name: "I can do both at once", descriptor: "Paraphrases properly" },
    ],
  },
  {
    standard_code: "SL.4.3",
    verbs: [
      { word: "Identify", gloss: "the reasons and evidence" },
      { word: "Connect", gloss: "reasons to points" },
      { word: "Evaluate", gloss: "whether the support holds" },
    ],
    concepts: ["Speaker's reasoning", "Delivery versus substance", "Evaluation"],
    vocabulary: [
      { term: "reason", definition: "why the speaker says you should agree" },
      { term: "evidence", definition: "the facts behind the reason" },
      { term: "claim", definition: "what they want you to accept" },
      { term: "support", definition: "what backs the claim up" },
    ],
    prior_skills: ["Ask about a speaker's information", "Distinguish claim from evidence", "Listen for structure"],
    prior_standards: [{ code: "SL.3.3", text: "Ask and answer questions about information from a speaker, offering elaboration" }],
    future_standards: [{ code: "SL.5.3", text: "Summarize the points a speaker makes and explain how each is supported" }],
    challenges: [
      { problem: "A speaker is judged by delivery and confidence rather than by the quality of the reasoning", fix: "The same argument delivered confidently and hesitantly. The reasoning did not change, so the judgment should not" },
      { problem: "Reasons are counted rather than weighed", fix: "Rank them, and name the weakest" },
    ],
    mastery_statement: "Student can identify a speaker's reasons and judge them separately from the delivery.",
    ladder: [
      { name: "I can follow the speaker", descriptor: "Listens for content" },
      { name: "I can find the claim", descriptor: "Identifies the point" },
      { name: "I can find the reasons", descriptor: "Locates support" },
      { name: "I can judge the support", descriptor: "Evaluates independently of delivery" },
    ],
  },
  {
    standard_code: "SL.4.4",
    verbs: [
      { word: "Report", gloss: "in an organized manner" },
      { word: "Support", gloss: "main ideas with detail" },
      { word: "Speak", gloss: "clearly and at pace" },
    ],
    concepts: ["Organization", "Notes versus script", "Audience connection"],
    vocabulary: [
      { term: "organized", definition: "in an order the listener can follow" },
      { term: "relevant", definition: "to the point" },
      { term: "theme", definition: "the idea running through it" },
      { term: "pace", definition: "how fast you speak" },
    ],
    prior_skills: ["Report with relevant details", "Rehearse", "Speak at an understandable pace"],
    prior_standards: [{ code: "SL.3.4", text: "Report on a topic or text with appropriate facts and relevant, descriptive details" }],
    future_standards: [{ code: "SL.5.4", text: "Report on a topic or text sequencing ideas logically and using appropriate facts" }],
    challenges: [
      { problem: "Presentations are read word for word from notes, which removes the connection with the audience", fix: "Bullet points only — no sentences on the card. You cannot read a bullet aloud" },
      { problem: "The structure is invisible to the listener", fix: "Signpost it. Three things, and then say which one you are on" },
    ],
    mastery_statement: "Student can present from notes in an organized way while staying connected to the audience.",
    ladder: [
      { name: "I can talk about my topic", descriptor: "Reports content" },
      { name: "I can organize it", descriptor: "Sequences logically" },
      { name: "I can use notes not a script", descriptor: "Speaks rather than reads" },
      { name: "I can support my main idea", descriptor: "Uses relevant detail" },
    ],
  },
  {
    standard_code: "SL.4.5",
    verbs: [
      { word: "Add", gloss: "audio or visual media" },
      { word: "Enhance", gloss: "the development of the idea" },
      { word: "Select", gloss: "purposefully" },
    ],
    concepts: ["Enhancement versus distraction", "Purposeful selection", "Developing an idea"],
    vocabulary: [
      { term: "audio recording", definition: "sound added to a presentation" },
      { term: "visual display", definition: "something shown to support the talk" },
      { term: "enhance", definition: "make stronger" },
      { term: "develop", definition: "build the idea out" },
    ],
    prior_skills: ["Add clarifying visuals", "Record audio", "Match medium to message"],
    prior_standards: [{ code: "SL.3.5", text: "Create engaging audio recordings and add visual displays to emphasize facts" }],
    future_standards: [{ code: "SL.5.5", text: "Include multimedia components and visual displays to enhance the development of main ideas" }],
    challenges: [
      { problem: "Animations and effects distract from the content instead of supporting it", fix: "Every element has to answer what it develops. If the answer is that it looks good, it goes" },
      { problem: "Media is chosen first and the point fitted around it", fix: "Main idea first, media second" },
    ],
    mastery_statement: "Student can select media that develops a main idea rather than decorating the presentation.",
    ladder: [
      { name: "I can add a visual", descriptor: "Includes media" },
      { name: "I can match it to my point", descriptor: "Connects to content" },
      { name: "I can say what it develops", descriptor: "Justifies inclusion" },
      { name: "I can cut what distracts", descriptor: "Selects purposefully" },
    ],
  },
  {
    standard_code: "SL.4.6",
    verbs: [
      { word: "Differentiate", gloss: "the contexts" },
      { word: "Use", gloss: "formal English when it is called for" },
    ],
    concepts: ["Formal and informal contexts", "Register switching", "Natural formality"],
    vocabulary: [
      { term: "formal English", definition: "the careful register for public or academic speech" },
      { term: "informal discourse", definition: "everyday talk" },
      { term: "context", definition: "the situation you are speaking in" },
      { term: "register", definition: "the level of formality" },
    ],
    prior_skills: ["Recognize register", "Speak in complete sentences", "Judge a setting"],
    prior_standards: [{ code: "SL.3.6", text: "Speak in complete sentences when appropriate to task and situation" }],
    future_standards: [{ code: "SL.5.6", text: "Adapt speech to a variety of contexts and tasks, using formal English when appropriate" }],
    challenges: [
      { problem: "Formal English is heard as unnatural and resisted, or over-formalized into stilted phrasing", fix: "Both failures modeled. Formal is not archaic, and there is a middle that sounds like a person" },
      { problem: "The context is never named, so the register is never chosen", fix: "Say the setting before speaking" },
    ],
    mastery_statement: "Student can recognize when formal English is called for and use it without stiltedness.",
    ladder: [
      { name: "I can speak informally", descriptor: "Uses everyday register" },
      { name: "I can hear the difference", descriptor: "Recognizes formal English" },
      { name: "I can tell which fits", descriptor: "Differentiates contexts" },
      { name: "I can switch naturally", descriptor: "Uses formal English well" },
    ],
  },
  {
    standard_code: "L.4.2",
    verbs: [
      { word: "Use", gloss: "commas and quotation marks" },
      { word: "Punctuate", gloss: "compound sentences" },
      { word: "Spell", gloss: "consulting references" },
    ],
    concepts: ["Compound sentence comma", "Direct speech", "Reference use"],
    vocabulary: [
      { term: "coordinating conjunction", definition: "and, but, or, so joining two clauses" },
      { term: "compound sentence", definition: "two complete sentences joined" },
      { term: "direct speech", definition: "the exact words someone said" },
      { term: "quotation marks", definition: "the marks around spoken or quoted words" },
    ],
    prior_skills: ["Punctuate dialogue", "Use commas in a series", "Form possessives"],
    prior_standards: [{ code: "L.3.2", text: "Use commas in addresses and dialogue and form possessives" }],
    future_standards: [{ code: "L.5.2", text: "Use punctuation to separate items in a series and a comma to set off elements" }],
    challenges: [
      { problem: "The comma before and in a compound sentence is either always omitted or inserted before every and", fix: "The test — cover the and. If both halves are complete sentences, the comma earns its place" },
      { problem: "Quotation punctuation is inconsistent", fix: "The four-part check from grade 3, still applied" },
    ],
    mastery_statement: "Student can use the compound-sentence comma correctly and punctuate direct speech.",
    ladder: [
      { name: "I can use end punctuation", descriptor: "Basic conventions" },
      { name: "I can punctuate speech", descriptor: "Uses quotation marks" },
      { name: "I can spot a compound sentence", descriptor: "Recognizes two clauses" },
      { name: "I can place the comma", descriptor: "Applies the test" },
    ],
  },
  {
    standard_code: "L.4.3",
    verbs: [
      { word: "Choose", gloss: "words that convey precisely" },
      { word: "Punctuate", gloss: "for effect" },
      { word: "Differentiate", gloss: "formal contexts" },
    ],
    concepts: ["Precision", "Concision", "Punctuation as a choice"],
    vocabulary: [
      { term: "precise", definition: "exactly right, not approximately" },
      { term: "convey", definition: "get across to the reader" },
      { term: "concise", definition: "saying it in no more words than needed" },
      { term: "effect", definition: "what it does to the reader" },
    ],
    prior_skills: ["Choose words for effect", "Adjust register", "Revise for clarity"],
    prior_standards: [{ code: "L.3.3", text: "Use knowledge of language and its conventions, choosing words for effect" }],
    future_standards: [{ code: "L.5.3", text: "Expand, combine and reduce sentences for meaning, interest and style" }],
    challenges: [
      { problem: "Long words are reached for to sound advanced, at the cost of precision and clarity", fix: "Which word is exactly right, not which is longest. Often the short one is more precise" },
      { problem: "Concision is confused with brevity", fix: "Cut words, not content" },
    ],
    mastery_statement: "Student can choose the precise word rather than the impressive one and cut what is unneeded.",
    ladder: [
      { name: "I can choose a word", descriptor: "Makes a choice" },
      { name: "I can pick the precise one", descriptor: "Prioritizes accuracy" },
      { name: "I can cut the extra", descriptor: "Writes concisely" },
      { name: "I can punctuate for effect", descriptor: "Uses punctuation deliberately" },
    ],
  },
  {
    standard_code: "L.4.4",
    verbs: [
      { word: "Determine", gloss: "the meaning" },
      { word: "Use", gloss: "roots and affixes as clues" },
      { word: "Verify", gloss: "the preliminary meaning" },
    ],
    concepts: ["Greek and Latin roots", "Preliminary meaning", "Verification"],
    vocabulary: [
      { term: "Greek root", definition: "a word part from Greek, such as tele" },
      { term: "Latin root", definition: "a word part from Latin, such as port" },
      { term: "affix", definition: "a prefix or suffix" },
      { term: "verify", definition: "check that you were right" },
    ],
    prior_skills: ["Use context clues", "Know common affixes", "Substitute to check"],
    prior_standards: [{ code: "L.3.4", text: "Determine or clarify the meaning of unknown and multiple-meaning words" }],
    future_standards: [{ code: "L.5.4", text: "Use Greek and Latin affixes and roots as clues to the meaning of a word" }],
    challenges: [
      { problem: "The first dictionary definition is accepted without checking it fits the sentence", fix: "Verify is in the standard. Substitute the meaning back and read the sentence aloud" },
      { problem: "Roots are learned as a list rather than used", fix: "Meet each root in three real words the same day" },
    ],
    mastery_statement: "Student can use roots and context to reach a meaning and then verify it in the sentence.",
    ladder: [
      { name: "I can use context", descriptor: "Infers from surroundings" },
      { name: "I can use roots", descriptor: "Applies morphology" },
      { name: "I can use references", descriptor: "Consults appropriately" },
      { name: "I can verify", descriptor: "Checks the meaning fits" },
    ],
  },
  {
    standard_code: "L.4.5",
    verbs: [
      { word: "Explain", gloss: "similes and metaphors" },
      { word: "Recognize", gloss: "idioms, adages and proverbs" },
      { word: "Relate", gloss: "words to opposites and near-synonyms" },
    ],
    concepts: ["Figurative language", "Idiom and adage", "Word relationships"],
    vocabulary: [
      { term: "simile", definition: "a comparison using like or as" },
      { term: "metaphor", definition: "a comparison that says one thing is another" },
      { term: "idiom", definition: "a phrase meaning something other than its words" },
      { term: "adage", definition: "an old saying that carries advice" },
    ],
    prior_skills: ["Distinguish literal from nonliteral", "Order words by degree", "Use synonyms and antonyms"],
    prior_standards: [{ code: "L.3.5", text: "Demonstrate understanding of word relationships and nuances in word meanings" }],
    future_standards: [{ code: "L.5.5", text: "Interpret figurative language, including similes and metaphors, in context" }],
    challenges: [
      { problem: "Idioms are read literally, producing confusion students rarely flag out loud", fix: "Make flagging normal. A weekly idiom that nobody understood, discussed openly" },
      { problem: "Simile and metaphor are identified but not explained", fix: "Say what the comparison claims. Brave as a lion claims courage, not fur" },
    ],
    mastery_statement: "Student can explain what a figure of speech means and relate words to opposites and near-synonyms.",
    ladder: [
      { name: "I can spot a comparison", descriptor: "Identifies simile or metaphor" },
      { name: "I can explain it", descriptor: "Says what it claims" },
      { name: "I can handle idioms", descriptor: "Interprets non-literal phrases" },
      { name: "I can relate words", descriptor: "Uses opposites and near-synonyms" },
    ],
  },
  {
    standard_code: "L.4.6",
    verbs: [
      { word: "Acquire", gloss: "academic and domain vocabulary" },
      { word: "Use", gloss: "it accurately in your own work" },
    ],
    concepts: ["Transfer", "Precise signalling", "Domain vocabulary"],
    vocabulary: [
      { term: "general academic", definition: "words used across school subjects" },
      { term: "domain-specific", definition: "words belonging to one subject" },
      { term: "precise", definition: "exactly the right word" },
      { term: "signal word", definition: "a word that marks an action, emotion or state" },
    ],
    prior_skills: ["Use academic vocabulary", "Read widely", "Use signal words"],
    prior_standards: [{ code: "L.3.6", text: "Acquire and use grade-appropriate conversational, academic and domain-specific words" }],
    future_standards: [{ code: "L.5.6", text: "Acquire and use grade-appropriate general academic and domain-specific words" }],
    challenges: [
      { problem: "Words are learned in isolation for a test and never transfer into writing", fix: "The assessment is their own writing three weeks later, not a Friday quiz" },
      { problem: "Precise signal words are avoided in favor of said and got", fix: "Bank them by what they signal — actions, emotions, states" },
    ],
    mastery_statement: "Student can use academic and domain-specific vocabulary accurately in their own work.",
    ladder: [
      { name: "I can define the word", descriptor: "Knows the meaning" },
      { name: "I can use it on request", descriptor: "Produces on demand" },
      { name: "I can use it accurately", descriptor: "Applies correctly" },
      { name: "I use it weeks later", descriptor: "Transfers into own writing" },
    ],
  },
];

const blueprintsData = [
  {
    standard_code: "W.4.3",
    title: "Three Times the Words for the Moment That Matters",
    badge: "Grade 4",
    route_name: "Writing Workshop",
    route_line: "Mark the big moment → Rush the rest → Slow down where it counts",
    success_criteria: ["Controls pacing", "Uses dialogue to develop", "Includes sensory detail"],
    steps: [
      { name: "Retrieve Transitional Phrases", minutes: 5, body: "Beyond then — later that morning, by the time, once.", science_tag: "retrieval" },
      { name: "Everything Gets Equal Time", minutes: 10, body: "A narrative where the walk to school takes as long as the accident. The reader cannot tell what mattered.", science_tag: "metacognition" },
      { name: "Mark the Moment", minutes: 10, body: "Before drafting. One moment, circled on the plan.", science_tag: "metacognition" },
      { name: "Three Times the Words", minutes: 14, body: "That moment gets triple. The rest gets a sentence. Pacing made countable.", science_tag: "dual-coding" },
      { name: "Dialogue That Reveals", minutes: 12, body: "A line has to show something the narration did not.", science_tag: "elaboration" },
      { name: "Sensory Detail Where It Counts", minutes: 10, body: "In the slow section, not scattered evenly.", science_tag: "dual-coding" },
      { name: "Read the Pacing Aloud", minutes: 4, body: "A listener says which moment mattered. If they get it wrong, the pacing did.", science_tag: "collaborative" },
    ],
    ef_supports: ["Moment-marking planner", "Three-times-the-words rule", "Dialogue reveal test", "Listener check"],
    tech: "Planning sheets with a marked moment",
    tech_purpose: "Pacing has to be decided before drafting to happen at all",
    ai_prompts: ["Write narratives with flat pacing for revision", "Generate dialogue that reveals versus reports"],
    assessment: ["Count words in the key moment", "Check dialogue reveals something", "Ask a listener which moment mattered"],
    why_it_works: ["Three times the words makes pacing countable rather than a feeling", "Marking the moment before drafting is what makes it possible to weight it", "A listener naming the wrong moment is direct evidence about pacing", "Requiring dialogue to reveal stops it being filler"],
  },
  {
    standard_code: "W.4.4",
    title: "Cut a Third and See What Was Lost",
    badge: "Grade 4",
    route_name: "Writing Workshop",
    route_line: "Draft → Cut a third → Check what actually went",
    success_criteria: ["Develops rather than pads", "Writes coherently", "Matches task and audience"],
    steps: [
      { name: "Retrieve Task and Audience", minutes: 5, body: "Both named before drafting.", science_tag: "retrieval" },
      { name: "Longer Means Better", minutes: 10, body: "Named as the belief it is. Then tested.", science_tag: "metacognition" },
      { name: "Cut a Third", minutes: 14, body: "From their own draft. What was lost? Usually nothing, and finding that out is the lesson.", science_tag: "elaboration" },
      { name: "Padding or Development", minutes: 12, body: "Sorted sentence by sentence. Padding restates; development adds.", science_tag: "elaboration" },
      { name: "Add Something Real", minutes: 12, body: "Put back half the words as actual development.", science_tag: "elaboration" },
      { name: "Does It Hold Together", minutes: 10, body: "Coherence checked by reading only the first sentence of each paragraph.", science_tag: "metacognition" },
      { name: "Would My Reader Follow", minutes: 3, body: "Checked against the named audience.", science_tag: "collaborative" },
    ],
    ef_supports: ["Cut-a-third exercise", "Padding-or-development sorting", "First-sentence coherence check", "Audience check"],
    tech: "Drafts long enough to cut",
    tech_purpose: "The exercise needs something to remove",
    ai_prompts: ["Write padded drafts for revision", "Generate padding and development sentence pairs"],
    assessment: ["Compare before and after cutting", "Check what was added back is development", "Run the first-sentence test"],
    why_it_works: ["Cutting a third and losing nothing disproves longer-is-better with their own writing", "Sorting sentence by sentence makes the distinction operational", "Reading only first sentences exposes incoherence quickly", "Adding back real development shows what the word count should have been doing"],
  },
  {
    standard_code: "W.4.5",
    title: "One Cut, One Addition, One Move",
    badge: "Grade 4",
    route_name: "Writing Workshop",
    route_line: "Revise the content → Then rewrite what will not mend → Then edit",
    success_criteria: ["Cuts, adds and reorganizes", "Rewrites when needed", "Edits last"],
    steps: [
      { name: "Retrieve Revise Versus Edit", minutes: 5, body: "The distinction, still holding.", science_tag: "retrieval" },
      { name: "Revision as Spellcheck", minutes: 8, body: "Named as the ceiling most students stop at.", science_tag: "metacognition" },
      { name: "Three Required Moves", minutes: 16, body: "One cut, one addition, one reorganization. Before any editing. The requirement is the intervention.", science_tag: "elaboration" },
      { name: "Patch or Rewrite", minutes: 12, body: "A weak paragraph. Sometimes starting again is faster than repairing.", science_tag: "metacognition" },
      { name: "Try It the Other Way", minutes: 12, body: "The same section written differently. Two versions, then choose.", science_tag: "elaboration" },
      { name: "Now Edit", minutes: 8, body: "Conventions last, once the content has settled.", science_tag: "dual-coding" },
      { name: "What Changed and Why", minutes: 4, body: "Named specifically.", science_tag: "metacognition" },
    ],
    ef_supports: ["Three-moves requirement", "Patch-or-rewrite decision", "Two-version comparison", "Edit-last rule"],
    tech: "Drafts with wide margins",
    tech_purpose: "Revision needs room to work",
    ai_prompts: ["Generate drafts needing structural revision", "Write paragraph pairs for version comparison"],
    assessment: ["Check all three moves happened", "Look for rewriting, not only patching", "Confirm editing came last"],
    why_it_works: ["Three required moves make revision structural instead of optional", "Naming the spellcheck ceiling identifies where most students stop", "Writing a section twice makes choosing possible", "Editing last protects revision from being crowded out"],
  },
  {
    standard_code: "W.4.6",
    title: "Typing Is Its Own Practice",
    badge: "Grade 4",
    route_name: "Routine and Practice",
    route_line: "Drill the keyboard → Compose freely → Publish and collaborate",
    success_criteria: ["Types a page in one sitting", "Publishes with technology", "Collaborates with others"],
    steps: [
      { name: "Retrieve Home Row", minutes: 5, body: "Finger positions, briefly.", science_tag: "retrieval" },
      { name: "The Bottleneck", minutes: 8, body: "Named plainly. Slow typing shortens the writing, and no amount of good ideas gets past it.", science_tag: "metacognition" },
      { name: "Ten Minutes of Drill", minutes: 10, body: "Its own practice time, not writing time. Bought, not wasted.", science_tag: "spaced" },
      { name: "Compose at the Keyboard", minutes: 16, body: "Once fluency allows it. A page in one sitting is the standard's own bar.", science_tag: "spaced" },
      { name: "Named Sections", minutes: 12, body: "In a shared document, each owned. Nobody spectates.", science_tag: "collaborative" },
      { name: "Comment on a Draft", minutes: 8, body: "Interacting, which the standard names.", science_tag: "collaborative" },
      { name: "Publish It", minutes: 4, body: "Where a reader will find it.", science_tag: "collaborative" },
    ],
    ef_supports: ["Daily typing drill", "Page-in-one-sitting target", "Shared document with owners", "Comment stems"],
    tech: "Laptops and a collaborative document tool",
    tech_purpose: "The standard names keyboarding, publishing and collaborating alike",
    ai_prompts: ["Generate typing practice passages", "Write collaborative writing briefs with distinct sections"],
    assessment: ["Time a page", "Check every section has an owner", "Read the comments"],
    why_it_works: ["Treating typing as its own practice removes the bottleneck rather than working around it", "A page in one sitting is a concrete, checkable target", "Named sections make collaboration real rather than nominal", "Publishing gives the fluency a purpose"],
  },
  {
    standard_code: "W.4.7",
    title: "If One Sentence Answers It, Ask Again",
    badge: "Grade 4",
    route_name: "Strategy Instruction",
    route_line: "Draft a question → Test it → Investigate three aspects",
    success_criteria: ["Frames a researchable question", "Investigates several aspects", "Builds knowledge"],
    steps: [
      { name: "Retrieve Narrowing", minutes: 5, body: "From grade 3 — three narrowings.", science_tag: "retrieval" },
      { name: "How Tall Is Everest", minutes: 10, body: "Answered in one sentence, and the project is over. That is the test.", science_tag: "metacognition" },
      { name: "How and Why Survive", minutes: 12, body: "Questions that cannot be closed by a fact. Rewrite each what into a how or why.", science_tag: "elaboration" },
      { name: "Three Aspects", minutes: 12, body: "Named at the start, so the project has a shape rather than a direction.", science_tag: "dual-coding" },
      { name: "Investigate One Each", minutes: 16, body: "With sources, over more than one session.", science_tag: "interleaving" },
      { name: "Bring Them Together", minutes: 10, body: "Three aspects, one account.", science_tag: "elaboration" },
      { name: "What I Still Do Not Know", minutes: 4, body: "Research raises questions too.", science_tag: "metacognition" },
    ],
    ef_supports: ["One-sentence test", "How-and-why rewriting", "Three-aspect planner", "Still-unknown box"],
    tech: "Text sets and supervised search",
    tech_purpose: "Investigating aspects needs more than one source",
    ai_prompts: ["Generate closed and open research questions", "Write three-aspect breakdowns of topics"],
    assessment: ["Apply the one-sentence test", "Check three aspects were covered", "Read the still-unknown box"],
    why_it_works: ["The one-sentence test is a rule students can apply to their own question", "Rewriting what into how or why fixes the question rather than rejecting it", "Naming three aspects gives the project a shape before it starts", "Bringing the aspects together is what makes it knowledge rather than notes"],
  },
  {
    standard_code: "W.4.8",
    title: "Cover It, Then Write It",
    badge: "Grade 4",
    route_name: "Strategy Instruction",
    route_line: "Read → Cover → Write from memory → Record the source",
    success_criteria: ["Paraphrases in their own structure", "Categorizes notes", "Lists sources"],
    steps: [
      { name: "Retrieve Note-Taking", minutes: 5, body: "Phrases, not sentences.", science_tag: "retrieval" },
      { name: "Synonym Swapping", minutes: 12, body: "The original sentence with three words changed. Still the author's sentence, and still plagiarism.", science_tag: "metacognition" },
      { name: "Cover and Write", minutes: 14, body: "A paraphrase built from memory has your sentence shape, not theirs. The covering does the work.", science_tag: "retrieval" },
      { name: "Compare the Two", minutes: 10, body: "Original and paraphrase side by side. Different structure, same meaning?", science_tag: "elaboration" },
      { name: "Source on the Note", minutes: 10, body: "As it is taken, not afterwards. Afterwards means never.", science_tag: "dual-coding" },
      { name: "Categorize", minutes: 10, body: "Notes sorted into the aspects being investigated.", science_tag: "dual-coding" },
      { name: "Build the Source List", minutes: 4, body: "From the notes, since each carries its origin.", science_tag: "interleaving" },
    ],
    ef_supports: ["Cover-and-write routine", "Side-by-side comparison", "Source-on-the-note rule", "Category headers"],
    tech: "Print and digital sources",
    tech_purpose: "The standard names both",
    ai_prompts: ["Generate passages for paraphrase practice", "Write synonym-swapped examples to critique"],
    assessment: ["Compare structure, not just wording", "Check every note carries a source", "Confirm categorization"],
    why_it_works: ["Covering the source makes a genuine paraphrase the only available option", "Showing synonym swapping names what it actually is", "Recording the source at the moment of the note is the only time it happens", "Categorizing during collection saves the sorting later"],
  },
  {
    standard_code: "W.4.9",
    title: "Set It Up, Quote It, Explain It",
    badge: "Grade 4",
    route_name: "Writing Workshop",
    route_line: "Introduce → Quote → Say what it shows",
    success_criteria: ["Draws evidence from texts", "Introduces quotations", "Explains what they show"],
    steps: [
      { name: "Retrieve Citing", minutes: 5, body: "One sentence, precisely chosen.", science_tag: "retrieval" },
      { name: "The Dropped Quotation", minutes: 12, body: "A quotation with nothing before or after it. The reader has to do the work the writer skipped.", science_tag: "metacognition" },
      { name: "Three Parts, Every Time", minutes: 14, body: "Set up, quote, explain. A bare quotation does no work.", science_tag: "dual-coding" },
      { name: "Explain Is Not Restate", minutes: 12, body: "Saying it again is not explaining. Say why it matters for your point.", science_tag: "elaboration" },
      { name: "From Literature and Nonfiction", minutes: 10, body: "The standard names both.", science_tag: "interleaving" },
      { name: "Write a Paragraph", minutes: 10, body: "Claim, evidence in three parts, and the link back.", science_tag: "interleaving" },
      { name: "Partner Reads It Cold", minutes: 3, body: "Did the quotation land, or did they have to work it out?", science_tag: "collaborative" },
    ],
    ef_supports: ["Three-part quotation frame", "Explain-is-not-restate rule", "Literary and informational sets", "Cold reader check"],
    tech: "Texts with quotable passages",
    tech_purpose: "Evidence has to come from somewhere real",
    ai_prompts: ["Generate dropped-quotation examples for repair", "Write passages with strong quotable evidence"],
    assessment: ["Check all three parts", "Confirm explanation adds rather than repeats", "Use a cold reader"],
    why_it_works: ["A dropped quotation shows the gap the reader is left to fill", "Three parts make the structure checkable", "Naming restatement as insufficient targets the commonest weak explanation", "A cold reader tests whether the setup actually worked"],
  },
  {
    standard_code: "W.4.10",
    title: "A Planning Budget",
    badge: "Grade 4",
    route_name: "Writing Workshop",
    route_line: "Check the clock → Budget the planning → Write to fit",
    success_criteria: ["Writes routinely", "Budgets planning to the time", "Adapts across subjects"],
    steps: [
      { name: "Retrieve the Process", minutes: 5, body: "Plan, draft, revise, edit.", science_tag: "retrieval" },
      { name: "Planning Until Time Runs Out", minutes: 10, body: "Twenty-five minutes of planning in a forty-minute task. The piece is unfinished, and the planning was excellent.", science_tag: "elaboration" },
      { name: "Write the Budget Down", minutes: 12, body: "Five minutes planning, thirty drafting, five checking. On the page, before starting.", science_tag: "metacognition" },
      { name: "Write to It", minutes: 16, body: "With the clock visible.", science_tag: "spaced" },
      { name: "The Long Version", minutes: 12, body: "The same task over a week. A different budget entirely.", science_tag: "interleaving" },
      { name: "In Science and History", minutes: 10, body: "Same standards, different content. Discipline-specific is in the standard.", science_tag: "interleaving" },
      { name: "Did the Budget Hold", minutes: 4, body: "Compared against what actually happened.", science_tag: "metacognition" },
    ],
    ef_supports: ["Written planning budget", "Visible clock", "Cross-subject writing tasks", "Budget review"],
    tech: "A clock the room can see",
    tech_purpose: "Time budgeting needs the time to be visible",
    ai_prompts: ["Generate on-demand prompts across subjects", "Write extended project briefs"],
    assessment: ["Check the budget was written first", "Compare planned against actual", "Confirm the piece was finished"],
    why_it_works: ["A written budget turns time management into a plan rather than an intention", "Watching excellent planning produce an unfinished piece makes the trade-off real", "Reviewing the budget against reality is how the estimate improves", "Writing in other subjects is what discipline-specific means"],
  },
  {
    standard_code: "SL.4.1",
    title: "Every Contribution Names a Page",
    badge: "Grade 4",
    route_name: "Structured Discussion",
    route_line: "Prepare with notes → Carry your role → Review what changed",
    success_criteria: ["Arrives prepared", "Carries an assigned role", "Reviews key ideas"],
    steps: [
      { name: "Retrieve the Reading", minutes: 6, body: "Before discussion opens. Preparation checked, not assumed.", science_tag: "retrieval" },
      { name: "General Reactions", minutes: 8, body: "What contributing without reading sounds like. It is recognizable, and naming it changes behavior.", science_tag: "metacognition" },
      { name: "Name a Page", minutes: 14, body: "Every contribution. A general reaction cannot, so it disappears on its own.", science_tag: "collaborative" },
      { name: "Roles With Artefacts", minutes: 12, body: "The summarizer produces a summary, the questioner a question list. A role with no output is a label.", science_tag: "collaborative" },
      { name: "Pose Specific Questions", minutes: 12, body: "Written beforehand, asked during.", science_tag: "elaboration" },
      { name: "Review the Key Ideas", minutes: 10, body: "At the end, together.", science_tag: "retrieval" },
      { name: "What I Now Think", minutes: 4, body: "Their own idea, revised in light of the discussion. The standard's own phrasing.", science_tag: "metacognition" },
    ],
    ef_supports: ["Preparation notes sheet", "Name-a-page rule", "Role artefact requirement", "What-I-now-think slip"],
    tech: "Printed texts with page numbers",
    tech_purpose: "Naming a page needs pages",
    ai_prompts: ["Generate discussion questions requiring preparation", "Write role descriptions with outputs"],
    assessment: ["Count page-referenced contributions", "Check role artefacts exist", "Read the revision slips"],
    why_it_works: ["Requiring a page reference makes unprepared contribution impossible rather than discouraged", "A role that produces something cannot be quietly dropped", "Writing questions beforehand is preparation that shows", "Revising your own view is what the standard asks and it rarely gets asked"],
  },
  {
    standard_code: "SL.4.2",
    title: "Different Words, Same Meaning",
    badge: "Grade 4",
    route_name: "Structured Discussion",
    route_line: "Listen fully → Then restate → Check both halves",
    success_criteria: ["Paraphrases accurately", "Uses different words", "Preserves the meaning"],
    steps: [
      { name: "Retrieve Main Idea", minutes: 4, body: "What the speaker was actually saying.", science_tag: "retrieval" },
      { name: "Two Ways to Fail", minutes: 12, body: "Word-for-word repetition, and a version that drifted. Both fail, in opposite directions.", science_tag: "elaboration" },
      { name: "Two Checks", minutes: 12, body: "Different words? Same meaning? Both have to hold, and checking one is why paraphrase goes wrong.", science_tag: "metacognition" },
      { name: "Listen, Then Restate", minutes: 12, body: "Not at the same time. Paraphrasing while listening loses both.", science_tag: "collaborative" },
      { name: "Speaker Confirms", minutes: 10, body: "Is that what you meant? The only real check on accuracy.", science_tag: "collaborative" },
      { name: "From Media Too", minutes: 10, body: "A video clip, paraphrased. Diverse formats are in the standard.", science_tag: "interleaving" },
      { name: "Yesterday's Passage", minutes: 4, body: "Paraphrased again, cold.", science_tag: "spaced" },
    ],
    ef_supports: ["Two-check card", "Listen-then-restate routine", "Speaker confirmation", "Media clip set"],
    tech: "Read-alouds and short video",
    tech_purpose: "Diverse media and formats are named in the standard",
    ai_prompts: ["Generate passages for paraphrase with drift examples", "Write media clips with clear points"],
    assessment: ["Apply both checks", "Use speaker confirmation", "Test on media as well as text"],
    why_it_works: ["Naming both failure modes prevents fixing one by causing the other", "Two explicit checks make accuracy and rewording equally required", "Speaker confirmation is the only external test of meaning preservation", "Separating listening from restating protects both"],
  },
  {
    standard_code: "SL.4.3",
    title: "The Same Argument, Twice",
    badge: "Grade 4",
    route_name: "Structured Discussion",
    route_line: "Find the claim → List the reasons → Judge them apart from the delivery",
    success_criteria: ["Identifies reasons and evidence", "Connects reasons to points", "Judges independently of delivery"],
    steps: [
      { name: "Retrieve Claim and Evidence", minutes: 5, body: "The distinction, from reading.", science_tag: "retrieval" },
      { name: "Confident and Hesitant", minutes: 14, body: "The same argument delivered both ways. The reasoning did not change, so the judgment should not. This is the whole lesson.", science_tag: "elaboration" },
      { name: "Write Down the Reasons", minutes: 12, body: "On paper, away from the voice. Text has no delivery.", science_tag: "dual-coding" },
      { name: "Rank Them", minutes: 12, body: "Strongest to weakest. Weighing, not counting.", science_tag: "elaboration" },
      { name: "What Is Missing", minutes: 10, body: "Name the evidence that would have helped.", science_tag: "metacognition" },
      { name: "Listen to a Real Speaker", minutes: 10, body: "With the same routine.", science_tag: "collaborative" },
      { name: "Did the Voice Sway Me", minutes: 3, body: "Asked honestly.", science_tag: "metacognition" },
    ],
    ef_supports: ["Two-delivery recordings", "Written reason list", "Ranking ladder", "Did-the-voice-sway-me check"],
    tech: "Recorded arguments in two deliveries",
    tech_purpose: "Holding content constant while varying delivery is the demonstration",
    ai_prompts: ["Write one argument for confident and hesitant delivery", "Generate reason sets of varying strength"],
    assessment: ["Check reasons are written before judging", "Read the rankings", "Ask about delivery influence"],
    why_it_works: ["One argument in two deliveries isolates delivery as the variable", "Writing the reasons down strips the voice away entirely", "Ranking replaces counting, which is where evaluation happens", "Asking honestly about the voice makes the bias discussable"],
  },
  {
    standard_code: "SL.4.4",
    title: "Bullets You Cannot Read Aloud",
    badge: "Grade 4",
    route_name: "Structured Presentation",
    route_line: "Plan in bullets → Signpost the structure → Talk to the room",
    success_criteria: ["Presents in an organized manner", "Supports main ideas", "Speaks at an understandable pace"],
    steps: [
      { name: "Retrieve Relevant Detail", minutes: 4, body: "To the point, not merely true.", science_tag: "retrieval" },
      { name: "Read Word for Word", minutes: 10, body: "What it does to the connection with the audience. Nobody is listening by the second paragraph.", science_tag: "metacognition" },
      { name: "Bullets Only", minutes: 14, body: "No sentences on the card. You cannot read a bullet aloud, so you have to speak.", science_tag: "dual-coding" },
      { name: "Signpost It", minutes: 12, body: "Three things, and say which one you are on. The structure becomes audible.", science_tag: "elaboration" },
      { name: "Rehearse With a Timer", minutes: 12, body: "Pace, and knowing the length.", science_tag: "spaced" },
      { name: "Present It", minutes: 12, body: "To the room, with the bullets as a prompt only.", science_tag: "collaborative" },
      { name: "Could They Follow", minutes: 4, body: "Audience names the three things.", science_tag: "collaborative" },
    ],
    ef_supports: ["Bullets-only rule", "Signpost frame", "Timer", "Audience structure check"],
    tech: "Index cards, deliberately small",
    tech_purpose: "A small card cannot hold a script",
    ai_prompts: ["Generate presentation topics with three natural parts", "Write signposting frames"],
    assessment: ["Check cards hold bullets not sentences", "Ask the audience for the structure", "Time the delivery"],
    why_it_works: ["A bullet cannot be read aloud, so the script becomes impossible rather than discouraged", "Signposting makes the organization audible to a listener", "A small card physically prevents a script", "Asking the audience for the three things tests whether the structure landed"],
  },
  {
    standard_code: "SL.4.5",
    title: "What Does This Element Develop",
    badge: "Grade 4",
    route_name: "Structured Presentation",
    route_line: "Fix the main idea → Ask what would develop it → Add only that",
    success_criteria: ["Adds media purposefully", "Enhances the main idea", "Cuts what distracts"],
    steps: [
      { name: "Retrieve Enhance", minutes: 4, body: "Make stronger, not make prettier.", science_tag: "retrieval" },
      { name: "The Spinning Transition", minutes: 10, body: "Effects that pull attention away from the point. Everyone has seen it.", science_tag: "metacognition" },
      { name: "Main Idea First", minutes: 10, body: "Fixed before any media is chosen. Media second, always.", science_tag: "metacognition" },
      { name: "What Would Develop It", minutes: 14, body: "Asked before making anything. The answer is what to build.", science_tag: "elaboration" },
      { name: "One Question Per Element", minutes: 12, body: "What does this develop? If the answer is that it looks good, it goes.", science_tag: "metacognition" },
      { name: "Record the Audio", minutes: 10, body: "Where sound genuinely adds something.", science_tag: "dual-coding" },
      { name: "Audience Verdict", minutes: 4, body: "Did it help, or distract?", science_tag: "collaborative" },
    ],
    ef_supports: ["Main-idea-first rule", "One-question-per-element test", "Effects ban", "Audience verdict"],
    tech: "Presentation software and recording tools",
    tech_purpose: "Both audio and visual are named in the standard",
    ai_prompts: ["Generate media options of varying usefulness", "Write main ideas needing visual development"],
    assessment: ["Apply the develops test to every element", "Ask the audience about distraction", "Check the main idea came first"],
    why_it_works: ["Fixing the main idea first stops the media choosing the message", "One question per element is a filter that runs quickly", "Naming the spinning transition makes the failure recognizable", "The audience is the only real judge of distraction"],
  },
  {
    standard_code: "SL.4.6",
    title: "Formal Without Sounding Like a Robot",
    badge: "Grade 4",
    route_name: "Oral Practice",
    route_line: "Hear both failures → Find the middle → Switch on purpose",
    success_criteria: ["Differentiates contexts", "Uses formal English appropriately", "Avoids stilted phrasing"],
    steps: [
      { name: "Retrieve Register", minutes: 4, body: "Formal and informal, from grade 3.", science_tag: "retrieval" },
      { name: "Two Ways to Fail", minutes: 12, body: "Refusing formality, and over-formalizing into stiltedness. Both modeled, because both happen.", science_tag: "elaboration" },
      { name: "The Middle", minutes: 12, body: "Formal English that still sounds like a person. That version is rarely demonstrated, so it gets demonstrated.", science_tag: "elaboration" },
      { name: "Sort the Contexts", minutes: 12, body: "Assembly, playground, interview, group work. Which calls for which?", science_tag: "metacognition" },
      { name: "Switch on Cue", minutes: 12, body: "Mid-conversation, a context change is announced. Register switched live.", science_tag: "collaborative" },
      { name: "Why It Matters", minutes: 8, body: "Not politeness — being taken seriously in a setting that expects it.", science_tag: "elaboration" },
      { name: "In a Real Setting", minutes: 4, body: "Used where it actually counts.", science_tag: "spaced" },
    ],
    ef_supports: ["Two-failure models", "Middle-register example", "Context sorting cards", "Switch-on-cue game"],
    tech: "Recorded examples in three registers",
    tech_purpose: "The middle register has to be heard to be copied",
    ai_prompts: ["Write one message as informal, natural formal and stilted", "Generate contexts for register sorting"],
    assessment: ["Check register matches context", "Listen for stiltedness", "Test live switching"],
    why_it_works: ["Modeling both failures explains why resistance and over-correction both happen", "Demonstrating the middle gives students something to copy", "Switching on cue makes register a live skill rather than a category", "Naming being taken seriously is a more honest reason than politeness"],
  },
  {
    standard_code: "L.4.2",
    title: "Cover the And",
    badge: "Grade 4",
    route_name: "Explicit Instruction",
    route_line: "Find the and → Cover it → Comma only if both halves stand alone",
    success_criteria: ["Uses the compound-sentence comma correctly", "Punctuates quotations", "Capitalizes correctly"],
    steps: [
      { name: "Retrieve Complete Sentences", minutes: 5, body: "What makes a clause independent.", science_tag: "retrieval" },
      { name: "Never or Always", minutes: 10, body: "The two errors the deck names. Both come from having no test.", science_tag: "metacognition" },
      { name: "Cover the And", minutes: 14, body: "If both halves are complete sentences, the comma earns its place. If not, no comma. One test, both errors fixed.", science_tag: "metacognition" },
      { name: "Sort Twenty Sentences", minutes: 12, body: "Comma or no comma, using the test.", science_tag: "interleaving" },
      { name: "Quotation Punctuation", minutes: 12, body: "The four-part check from grade 3, still applied.", science_tag: "dual-coding" },
      { name: "Write Some of Each", minutes: 10, body: "Compound sentences and direct speech in one piece.", science_tag: "interleaving" },
      { name: "Yesterday's Sentences", minutes: 4, body: "Rechecked cold.", science_tag: "spaced" },
    ],
    ef_supports: ["Cover-the-and test", "Sorting sets", "Four-part quotation check", "Reference for spelling"],
    tech: "Whiteboards and printed sentence sets",
    tech_purpose: "The test needs sentences to apply it to",
    ai_prompts: ["Generate compound and simple sentences with and", "Write dialogue punctuation exercises"],
    assessment: ["Check the test is applied", "Look at both error types", "Confirm quotation punctuation"],
    why_it_works: ["One test corrects both the never and the always error at once", "Covering the and isolates the question of whether both halves are complete", "Bulk sorting builds the judgment faster than sentence by sentence", "Carrying the grade 3 quotation check forward keeps it from decaying"],
  },
  {
    standard_code: "L.4.3",
    title: "The Exact Word, Not the Long One",
    badge: "Grade 4",
    route_name: "Explicit Instruction",
    route_line: "Draft it → Find the imprecise word → Replace with the exact one",
    success_criteria: ["Chooses precise words", "Writes concisely", "Uses punctuation for effect"],
    steps: [
      { name: "Retrieve Word Choice", minutes: 5, body: "Choosing for effect, from grade 3.", science_tag: "retrieval" },
      { name: "Long to Sound Clever", minutes: 12, body: "A sentence stuffed with long words that says less than a plain one. Precision lost to impression.", science_tag: "metacognition" },
      { name: "Which Is Exactly Right", minutes: 14, body: "Not which is longest. Often the short word is the precise one.", science_tag: "elaboration" },
      { name: "Cut Words, Not Content", minutes: 12, body: "Concision is removing what does no work, not removing substance.", science_tag: "elaboration" },
      { name: "Punctuation as a Choice", minutes: 10, body: "A dash, a colon, a full stop. Each does something different.", science_tag: "dual-coding" },
      { name: "Revise Your Own", minutes: 10, body: "Three imprecise words replaced, ten unnecessary ones cut.", science_tag: "interleaving" },
      { name: "Read Both Aloud", minutes: 4, body: "Before and after. The difference is audible.", science_tag: "collaborative" },
    ],
    ef_supports: ["Precise-versus-long pairs", "Cut-words-not-content rule", "Punctuation effect menu", "Before-and-after reading"],
    tech: "Drafts and a thesaurus used carefully",
    tech_purpose: "A thesaurus helps precision and harms it, depending on use",
    ai_prompts: ["Generate overwritten sentences for revision", "Write precise and impressive word pairs"],
    assessment: ["Check replacements are more precise, not longer", "Confirm content survived cutting", "Listen to the readings"],
    why_it_works: ["Showing a long-worded sentence saying less separates impression from precision", "Asking which is exactly right reframes the choice entirely", "Distinguishing words from content keeps concision from gutting the piece", "Reading both versions aloud makes the improvement audible"],
  },
  {
    standard_code: "L.4.4",
    title: "Guess From the Root, Then Check",
    badge: "Grade 4",
    route_name: "Strategy Instruction",
    route_line: "Use the root → Reach a preliminary meaning → Verify it fits",
    success_criteria: ["Uses Greek and Latin roots", "Uses context and references", "Verifies the meaning"],
    steps: [
      { name: "Retrieve Known Roots", minutes: 5, body: "Port, tele, struct, aud.", science_tag: "retrieval" },
      { name: "Three Words, One Root", minutes: 12, body: "Port in transport, portable, import. The root has to be met in real words the same day.", science_tag: "elaboration" },
      { name: "Preliminary Meaning", minutes: 12, body: "The standard's own word. A first guess, explicitly provisional.", science_tag: "metacognition" },
      { name: "Verify It", minutes: 14, body: "Substitute back and read the sentence. The step the deck says gets skipped.", science_tag: "metacognition" },
      { name: "The Wrong First Definition", minutes: 12, body: "A multiple-meaning word where sense one does not fit. Verification catches it; accepting does not.", science_tag: "elaboration" },
      { name: "Use the References", minutes: 8, body: "For pronunciation as well as meaning, which the standard names.", science_tag: "interleaving" },
      { name: "Root Log", minutes: 4, body: "Collected and revisited.", science_tag: "spaced" },
    ],
    ef_supports: ["Root wall with three examples each", "Preliminary meaning box", "Substitution check", "Root log"],
    tech: "Dictionaries, print and digital",
    tech_purpose: "The standard names reference materials explicitly",
    ai_prompts: ["Generate word families sharing a root", "Write multiple-meaning words with misleading first entries"],
    assessment: ["Check verification happened", "Confirm roots are used", "Watch for accepting the first definition"],
    why_it_works: ["Meeting a root in three real words makes it usable rather than memorized", "Calling the meaning preliminary makes verification a natural next step", "Substitution is the check the standard asks for and students skip", "The wrong-first-definition trap is the commonest dictionary error"],
  },
  {
    standard_code: "L.4.5",
    title: "What Is the Comparison Claiming",
    badge: "Grade 4",
    route_name: "Explicit Instruction",
    route_line: "Spot the figure → Say what it claims → Check it against the sentence",
    success_criteria: ["Explains similes and metaphors", "Interprets idioms and adages", "Relates words to opposites"],
    steps: [
      { name: "Retrieve Literal and Nonliteral", minutes: 5, body: "From grade 3.", science_tag: "retrieval" },
      { name: "Brave as a Lion", minutes: 12, body: "Claims courage, not fur. Naming what a comparison claims is the explanation.", science_tag: "elaboration" },
      { name: "Flag It Out Loud", minutes: 10, body: "Idioms confuse students who rarely say so. A weekly idiom nobody understood, discussed openly.", science_tag: "collaborative" },
      { name: "Adages and Proverbs", minutes: 12, body: "Old sayings carrying advice. What is the advice, in plain words?", science_tag: "elaboration" },
      { name: "Opposites and Near-Synonyms", minutes: 12, body: "A word understood by what it is not, and by what it is nearly.", science_tag: "dual-coding" },
      { name: "Find One in Your Reading", minutes: 8, body: "Collected from independent reading.", science_tag: "spaced" },
      { name: "Write One", minutes: 4, body: "Their own simile, with the claim named.", science_tag: "elaboration" },
    ],
    ef_supports: ["What-does-it-claim frame", "Weekly idiom slot", "Opposites and near-synonym grids", "Figure collection log"],
    tech: "Texts with natural figurative language",
    tech_purpose: "Figures of speech have to be met in context",
    ai_prompts: ["Generate similes and metaphors with clear claims", "Write idioms and adages with plain meanings"],
    assessment: ["Check the claim is named", "Confirm idioms are explained", "Look at the opposites work"],
    why_it_works: ["Asking what a comparison claims turns identification into explanation", "A weekly slot makes admitting confusion normal rather than exposing", "Relating a word to its opposite defines it from two sides", "Writing their own simile tests whether the mechanism was understood"],
  },
  {
    standard_code: "L.4.6",
    title: "Still There in Three Weeks",
    badge: "Grade 4",
    route_name: "Routine and Practice",
    route_line: "Meet it → Use it → Find it in your own writing later",
    success_criteria: ["Acquires academic vocabulary", "Uses it accurately", "Transfers it into own work"],
    steps: [
      { name: "Retrieve Last Month's Words", minutes: 5, body: "Cold, before anything new.", science_tag: "retrieval" },
      { name: "Learned for the Test", minutes: 8, body: "Named as the pattern. A word defined on Friday and never used again was not acquired.", science_tag: "metacognition" },
      { name: "Words That Signal Precisely", minutes: 12, body: "Actions, emotions, states. Not said and got, but muttered, conceded, dreaded.", science_tag: "elaboration" },
      { name: "Your Own Sentence", minutes: 12, body: "About something real, not about the word.", science_tag: "elaboration" },
      { name: "Domain Words in Domain Work", minutes: 12, body: "Science vocabulary used in science writing, the same week.", science_tag: "interleaving" },
      { name: "Three-Week Check", minutes: 8, body: "Their own writing, searched for the words. This is the assessment.", science_tag: "spaced" },
      { name: "Catch a Classmate", minutes: 4, body: "Noticing one used unprompted.", science_tag: "collaborative" },
    ],
    ef_supports: ["Signal word bank by category", "Own-sentence rule", "Three-week check", "Catch-a-classmate tally"],
    tech: "A word wall drawn from across subjects",
    tech_purpose: "Transfer needs the words visible outside the lesson",
    ai_prompts: ["Generate signal words for actions, emotions and states", "Write domain vocabulary sets by subject"],
    assessment: ["Search their writing three weeks later", "Check sentences are about something real", "Count unprompted uses"],
    why_it_works: ["Searching their own writing weeks later measures acquisition rather than recall", "Signal words give a reason to prefer the precise word over the common one", "Using domain words in that domain the same week is where transfer starts", "Catching a classmate makes vocabulary noticed rather than tested"],
  },
];

seedStandardsBatch({
  label: "Batch 16 — grade 4 writing, speaking and language",
  standardsData,
  unpacksData,
  blueprintsData,
});
