// @ts-nocheck
/**
 * Batch 13: grade 3 writing, speaking and language.
 *
 * Completes grade 3 ELA. The through-line in this half of the deck is
 * audience: writing the same way for every assignment because nobody named
 * the reader, filling slides with text and reading them aloud, answering in
 * fragments where a full response was expected. Most of these blueprints make
 * the audience real before anything is produced.
 *
 * American spellings throughout.
 *
 *   bun run scripts/seed-standards-batch-13.ts
 */
import { seedStandardsBatch } from "./lib/seed-standards-batch";

const standardsData = [
  {
    code: "W.3.2",
    name: "Group the facts into paragraphs",
    plain_reading:
      "Write informative/explanatory texts to examine a topic and convey ideas and information clearly.",
    learning_target: "I can put related facts together instead of listing them as they come to me.",
    skills: ["Informative Writing", "Grouping Information", "Linking Words"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["informative explanatory", "group related information", "linking words", "concluding statement", "third grade writing"],
  },
  {
    code: "W.3.4",
    name: "Write for the reader you actually have",
    plain_reading:
      "With guidance and support, produce writing in which the development and organization are appropriate to task and purpose.",
    learning_target: "I can change how I write depending on who is reading it.",
    skills: ["Task and Purpose", "Audience", "Organization"],
    science_tags: ["metacognition", "elaboration"],
    match_keys: ["task and purpose", "audience", "development and organization", "appropriate", "coherence"],
  },
  {
    code: "W.3.5",
    name: "Judge the feedback, then use it",
    plain_reading:
      "With guidance and support from peers and adults, develop and strengthen writing by planning, revising, and editing.",
    learning_target: "I can decide which suggestions to take and say why I left the others.",
    skills: ["Planning", "Revising", "Using Feedback"],
    science_tags: ["metacognition", "collaborative"],
    match_keys: ["plan revise edit", "peer feedback", "strengthen writing", "guidance and support", "draft"],
  },
  {
    code: "W.3.6",
    name: "Technology for writing and working together",
    plain_reading:
      "With guidance and support from adults, use technology to produce and publish writing and to interact and collaborate with others.",
    learning_target: "I can type up and share my writing without the typing shrinking it.",
    skills: ["Digital Publishing", "Online Collaboration", "Keyboarding"],
    science_tags: ["collaborative", "interleaving"],
    match_keys: ["technology to produce and publish", "interact and collaborate", "keyboarding", "share writing"],
  },
  {
    code: "W.3.7",
    name: "A question small enough to answer",
    plain_reading: "Conduct short research projects that build knowledge about a topic.",
    learning_target: "I can narrow my topic to something I can actually finish.",
    skills: ["Research Projects", "Narrowing a Question", "Multiple Sources"],
    science_tags: ["metacognition", "interleaving"],
    match_keys: ["short research projects", "build knowledge", "narrow the question", "multiple sources", "investigate"],
  },
  {
    code: "W.3.8",
    name: "Notes in key words, sorted",
    plain_reading:
      "Recall information from experiences or gather information from print and digital sources; take brief notes and sort evidence into categories.",
    learning_target: "I can note key words rather than sentences, and group them.",
    skills: ["Note-Taking", "Sorting Evidence", "Print and Digital Sources"],
    science_tags: ["retrieval", "dual-coding"],
    match_keys: ["brief notes", "sort evidence into categories", "print and digital sources", "recall", "plagiarism"],
  },
  {
    code: "W.3.10",
    name: "Long projects and short assignments are different",
    plain_reading:
      "Write routinely over extended and shorter time frames for a range of discipline-specific tasks, purposes, and audiences.",
    learning_target: "I can plan differently when I have forty minutes rather than three weeks.",
    skills: ["Writing Routinely", "Time Frames", "Adjusting Process"],
    science_tags: ["metacognition", "spaced"],
    match_keys: ["extended and shorter time frames", "write routinely", "discipline-specific", "on-demand writing", "audiences"],
  },
  {
    code: "SL.3.2",
    name: "Main ideas from something you heard",
    plain_reading:
      "Determine the main ideas and supporting details of a text read aloud or information presented in diverse media and formats.",
    learning_target: "I can sort what I heard into main ideas and the details under them.",
    skills: ["Listening Comprehension", "Main Idea", "Note-Taking"],
    science_tags: ["dual-coding", "retrieval"],
    match_keys: ["main ideas and supporting details", "read aloud", "diverse media and formats", "listening notes"],
  },
  {
    code: "SL.3.3",
    name: "Questions that open rather than close",
    plain_reading:
      "Ask and answer questions about information from a speaker, offering appropriate elaboration and detail.",
    learning_target: "I can ask something that gets more than a yes.",
    skills: ["Open Questions", "Elaboration", "Clarification"],
    science_tags: ["collaborative", "metacognition"],
    match_keys: ["questions about information from a speaker", "elaboration and detail", "open questions", "clarify"],
  },
  {
    code: "SL.3.4",
    name: "Clearly, and at a pace people can follow",
    plain_reading:
      "Report on a topic or text, tell a story, or recount an experience with appropriate facts and relevant, descriptive details, speaking clearly at an understandable pace.",
    learning_target: "I can slow down enough for people to follow me.",
    skills: ["Reporting", "Pace", "Relevant Detail"],
    science_tags: ["spaced", "collaborative"],
    match_keys: ["report on a topic", "understandable pace", "relevant descriptive details", "speaking clearly", "recount"],
  },
  {
    code: "SL.3.5",
    name: "Visuals that support, not duplicate",
    plain_reading:
      "Create engaging audio recordings of stories or poems; add visual displays when appropriate to emphasize or enhance certain facts or details.",
    learning_target: "I can make a slide that helps rather than one I read aloud.",
    skills: ["Audio Recording", "Visual Displays", "Emphasis"],
    science_tags: ["dual-coding", "metacognition"],
    match_keys: ["engaging audio recordings", "visual displays", "emphasize or enhance", "fluid reading", "slides"],
  },
  {
    code: "SL.3.6",
    name: "Full sentences where they are expected",
    plain_reading:
      "Speak in complete sentences when appropriate to task and situation in order to provide requested detail or clarification.",
    learning_target: "I can give a full answer in an academic conversation.",
    skills: ["Complete Sentences", "Register", "Requested Detail"],
    science_tags: ["spaced", "collaborative"],
    match_keys: ["complete sentences", "task and situation", "requested detail", "clarification", "academic talk"],
  },
  {
    code: "L.3.2",
    name: "Punctuating what someone said",
    plain_reading:
      "Demonstrate command of the conventions of standard English capitalization, punctuation, and spelling when writing, including commas in dialogue and possessives.",
    learning_target: "I can punctuate dialogue with the comma and the marks in the right places.",
    skills: ["Dialogue Punctuation", "Commas", "Possessives"],
    science_tags: ["dual-coding", "spaced"],
    match_keys: ["commas in addresses and dialogue", "quotation marks", "possessives", "capitalize titles", "spelling patterns"],
  },
  {
    code: "L.3.3",
    name: "Choosing words for effect",
    plain_reading:
      "Use knowledge of language and its conventions when writing, speaking, reading, or listening, choosing words and phrases for effect.",
    learning_target: "I can tell when writing needs to sound different from talking.",
    skills: ["Word Choice", "Register", "Spoken Versus Written"],
    science_tags: ["elaboration", "metacognition"],
    match_keys: ["choose words for effect", "spoken and written English", "register", "formal informal", "audience"],
  },
  {
    code: "L.3.5",
    name: "Knew, believed, suspected",
    plain_reading:
      "Demonstrate understanding of word relationships and nuances in word meanings, including shades of meaning among related words.",
    learning_target: "I can order words by how certain they are.",
    skills: ["Shades of Meaning", "Literal and Nonliteral", "Word Relationships"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["shades of meaning", "states of mind", "certainty", "literal nonliteral", "real-life connections"],
  },
  {
    code: "L.3.6",
    name: "Academic words in your own mouth",
    plain_reading:
      "Acquire and use accurately grade-appropriate conversational, general academic, and domain-specific words and phrases.",
    learning_target: "I can use an academic word outside the lesson it came from.",
    skills: ["Academic Vocabulary", "Domain-Specific Words", "Spatial and Temporal Signals"],
    science_tags: ["retrieval", "spaced"],
    match_keys: ["conversational general academic domain-specific", "acquire and use accurately", "spatial and temporal", "signal words"],
  },
];

const unpacksData = [
  {
    standard_code: "W.3.2",
    verbs: [
      { word: "Introduce", gloss: "open with the topic" },
      { word: "Group", gloss: "put related facts together" },
      { word: "Link", gloss: "join ideas with connecting words" },
    ],
    concepts: ["Grouping into paragraphs", "Linking words", "Concluding section"],
    vocabulary: [
      { term: "informative", definition: "writing that teaches" },
      { term: "group", definition: "put things that belong together in one place" },
      { term: "linking word", definition: "a word joining one idea to the next" },
      { term: "illustration", definition: "a picture used to make the writing clearer" },
    ],
    prior_skills: ["Introduce a topic", "Use facts and definitions", "Write a conclusion"],
    prior_standards: [{ code: "W.2.2", text: "Introduce a topic, use facts and definitions, provide a concluding statement" }],
    future_standards: [{ code: "W.4.2", text: "Group related information in paragraphs and sections, using formatting" }],
    challenges: [
      { problem: "Facts are listed in the order they were found rather than grouped", fix: "Cut the draft into strips and physically sort them. The groups become obvious when they can be moved" },
      { problem: "Linking words are limited to and and then", fix: "A bank organized by job — adding, contrasting, causing" },
    ],
    mastery_statement: "Student can group related information into paragraphs and link them for a reader.",
    ladder: [
      { name: "I can give facts", descriptor: "Supplies information" },
      { name: "I can introduce my topic", descriptor: "Opens clearly" },
      { name: "I can group related facts", descriptor: "Organizes into paragraphs" },
      { name: "I can link and conclude", descriptor: "Connects and closes" },
    ],
  },
  {
    standard_code: "W.3.4",
    verbs: [
      { word: "Produce", gloss: "writing that fits the job" },
      { word: "Match", gloss: "organization to purpose" },
    ],
    concepts: ["Task", "Purpose", "Audience"],
    vocabulary: [
      { term: "task", definition: "what you have been asked to write" },
      { term: "purpose", definition: "why you are writing it" },
      { term: "audience", definition: "who will read it" },
      { term: "organization", definition: "the order you put things in" },
    ],
    prior_skills: ["Write informative and narrative texts", "Organize a piece", "Revise with support"],
    prior_standards: [{ code: "W.2.5", text: "Focus on a topic and strengthen writing by revising and editing" }],
    future_standards: [{ code: "W.4.4", text: "Produce clear and coherent writing appropriate to task, purpose and audience" }],
    challenges: [
      { problem: "Every assignment is written the same way because the audience is never specified", fix: "Name the reader on the page before drafting. Not the teacher — the actual reader" },
      { problem: "Organization is copied from the last piece regardless of fit", fix: "Choose a structure and say why it suits this purpose" },
    ],
    mastery_statement: "Student can produce writing whose development and organization suit the task and reader.",
    ladder: [
      { name: "I can write a piece", descriptor: "Produces writing" },
      { name: "I can name my reader", descriptor: "Identifies audience" },
      { name: "I can choose a structure", descriptor: "Matches organization to purpose" },
      { name: "I can adjust for the reader", descriptor: "Develops appropriately" },
    ],
  },
  {
    standard_code: "W.3.5",
    verbs: [
      { word: "Plan", gloss: "before drafting" },
      { word: "Revise", gloss: "change what it says" },
      { word: "Judge", gloss: "which feedback to use" },
    ],
    concepts: ["Planning", "Revising with feedback", "Authorship"],
    vocabulary: [
      { term: "plan", definition: "decide the shape before writing" },
      { term: "revise", definition: "change the content" },
      { term: "edit", definition: "fix the conventions" },
      { term: "feedback", definition: "what a reader tells you" },
    ],
    prior_skills: ["Revise with support", "Edit for conventions", "Receive a suggestion"],
    prior_standards: [{ code: "W.2.5", text: "Focus on a topic and strengthen writing by revising and editing with support" }],
    future_standards: [{ code: "W.4.5", text: "Develop and strengthen writing by planning, revising, editing and rewriting" }],
    challenges: [
      { problem: "Every suggestion is accepted, or all are rejected — both avoid the work of judging", fix: "Take two, decline one, and write the reason for the declined one. Judging is the skill" },
      { problem: "Planning is skipped and revision has to do its work", fix: "A plan on the page before a draft is accepted" },
    ],
    mastery_statement: "Student can plan, revise and edit, judging which feedback to act on and why.",
    ladder: [
      { name: "I can write a draft", descriptor: "Produces writing" },
      { name: "I can plan first", descriptor: "Plans before drafting" },
      { name: "I can use feedback", descriptor: "Acts on suggestions" },
      { name: "I can choose what to take", descriptor: "Judges feedback" },
    ],
  },
  {
    standard_code: "W.3.6",
    verbs: [
      { word: "Produce", gloss: "using technology" },
      { word: "Publish", gloss: "for a reader" },
      { word: "Collaborate", gloss: "with others" },
    ],
    concepts: ["Digital production", "Collaboration", "Keyboarding as a bottleneck"],
    vocabulary: [
      { term: "publish", definition: "make it available to read" },
      { term: "collaborate", definition: "work on it together" },
      { term: "technology", definition: "the tools you write and share with" },
      { term: "keyboarding", definition: "typing with some fluency" },
    ],
    prior_skills: ["Use digital tools with support", "Draft on paper", "Basic keyboarding"],
    prior_standards: [{ code: "W.2.6", text: "Use a variety of digital tools to produce and publish writing" }],
    future_standards: [{ code: "W.4.6", text: "Use technology to produce and publish writing, demonstrating keyboarding skills" }],
    challenges: [
      { problem: "Slow keyboarding shortens the writing itself", fix: "Compose by hand, type to publish. The content should not be limited by typing speed" },
      { problem: "Collaboration means one person types while others watch", fix: "Named sections, each owned by someone" },
    ],
    mastery_statement: "Student can produce, publish and collaborate using technology without the tool shrinking the writing.",
    ladder: [
      { name: "I can type my work", descriptor: "Produces digitally" },
      { name: "I can draft first", descriptor: "Protects content from typing speed" },
      { name: "I can publish it", descriptor: "Shares for a reader" },
      { name: "I can work with someone", descriptor: "Collaborates online" },
    ],
  },
  {
    standard_code: "W.3.7",
    verbs: [
      { word: "Conduct", gloss: "a short research project" },
      { word: "Narrow", gloss: "the question to something answerable" },
      { word: "Build", gloss: "knowledge on a topic" },
    ],
    concepts: ["Narrowing", "Short research", "Multiple sources"],
    vocabulary: [
      { term: "research", definition: "finding out systematically" },
      { term: "source", definition: "where the information came from" },
      { term: "investigate", definition: "look into properly" },
    ],
    prior_skills: ["Participate in shared research", "Gather from sources", "Take notes"],
    prior_standards: [{ code: "W.2.7", text: "Participate in shared research and writing projects" }],
    future_standards: [{ code: "W.4.7", text: "Conduct short research projects that build knowledge through investigation" }],
    challenges: [
      { problem: "The topic chosen is far too broad for the time available", fix: "Narrowing is part of the skill, not a preliminary to it. Space, then planets, then why Mars is red" },
      { problem: "One source is treated as sufficient", fix: "Two minimum, and note where they differ" },
    ],
    mastery_statement: "Student can narrow a topic to a researchable question and build knowledge from sources.",
    ladder: [
      { name: "I can pick a topic", descriptor: "Chooses an area" },
      { name: "I can narrow it", descriptor: "Makes it researchable" },
      { name: "I can use two sources", descriptor: "Gathers broadly" },
      { name: "I can say what I learned", descriptor: "Builds knowledge" },
    ],
  },
  {
    standard_code: "W.3.8",
    verbs: [
      { word: "Gather", gloss: "from print and digital" },
      { word: "Take", gloss: "brief notes" },
      { word: "Sort", gloss: "evidence into categories" },
    ],
    concepts: ["Brief notes", "Categories", "Avoiding copying"],
    vocabulary: [
      { term: "brief notes", definition: "key words, not sentences" },
      { term: "category", definition: "a group notes belong to" },
      { term: "evidence", definition: "information that supports something" },
      { term: "source", definition: "where it came from" },
    ],
    prior_skills: ["Gather from provided sources", "Recall from experience", "Write phrases"],
    prior_standards: [{ code: "W.2.8", text: "Recall information or gather information from provided sources to answer a question" }],
    future_standards: [{ code: "W.4.8", text: "Take notes, categorize information and provide a list of sources" }],
    challenges: [
      { problem: "Full sentences are copied, which leads straight to plagiarism later", fix: "A box too small for a sentence, and the source covered while writing. Copying becomes impossible rather than forbidden" },
      { problem: "Notes are gathered but never sorted", fix: "Categories decided before the last source is read" },
    ],
    mastery_statement: "Student can take brief notes in their own words and sort them into categories.",
    ladder: [
      { name: "I can find information", descriptor: "Gathers from sources" },
      { name: "I can write key words", descriptor: "Takes brief notes" },
      { name: "I can avoid copying", descriptor: "Uses own words" },
      { name: "I can sort into groups", descriptor: "Categorizes evidence" },
    ],
  },
  {
    standard_code: "W.3.10",
    verbs: [
      { word: "Write", gloss: "routinely" },
      { word: "Adjust", gloss: "the process to the time" },
    ],
    concepts: ["Extended and shorter time frames", "On-demand writing", "Discipline-specific tasks"],
    vocabulary: [
      { term: "routinely", definition: "regularly, as a habit" },
      { term: "extended", definition: "over a long period" },
      { term: "time frame", definition: "how long you have" },
      { term: "revision", definition: "changing the content" },
    ],
    prior_skills: ["Write across genres", "Plan a piece", "Draft under time"],
    prior_standards: [{ code: "W.3.4", text: "Produce writing appropriate to task and purpose" }],
    future_standards: [{ code: "W.4.10", text: "Write routinely over extended and shorter time frames" }],
    challenges: [
      { problem: "A forty-minute piece is approached like a three-week project, and the time goes on planning", fix: "A different plan for each — five minutes of planning for a short piece, and a timer that says so" },
      { problem: "Short writing gets no planning at all", fix: "Brief is not none. Two minutes, three bullet points" },
    ],
    mastery_statement: "Student can adjust their writing process to the time frame and task.",
    ladder: [
      { name: "I can write regularly", descriptor: "Writes routinely" },
      { name: "I can plan a long piece", descriptor: "Uses extended process" },
      { name: "I can write to time", descriptor: "Manages short frames" },
      { name: "I can choose my process", descriptor: "Adjusts to the task" },
    ],
  },
  {
    standard_code: "SL.3.2",
    verbs: [
      { word: "Determine", gloss: "the main ideas" },
      { word: "Identify", gloss: "the supporting details" },
      { word: "Interpret", gloss: "information from media" },
    ],
    concepts: ["Hierarchy of ideas", "Listening notes", "Diverse formats"],
    vocabulary: [
      { term: "main idea", definition: "the biggest point being made" },
      { term: "supporting detail", definition: "something that backs it up" },
      { term: "media", definition: "video, audio or images used to inform" },
      { term: "format", definition: "the way information is presented" },
    ],
    prior_skills: ["Recount key ideas from a read-aloud", "Listen actively", "Take pictorial notes"],
    prior_standards: [{ code: "SL.2.2", text: "Recount or describe key ideas from a text read aloud or presented through media" }],
    future_standards: [{ code: "SL.4.2", text: "Paraphrase portions of a text read aloud or information presented in diverse media" }],
    challenges: [
      { problem: "Every detail is recorded with no hierarchy, or nothing is recorded at all", fix: "A frame with two main-idea boxes and three details under each. The shape does the sorting" },
      { problem: "Listening notes are attempted verbatim", fix: "Key words only, and the frame is too small for more" },
    ],
    mastery_statement: "Student can determine main ideas and their supporting details from listening.",
    ladder: [
      { name: "I can listen", descriptor: "Attends" },
      { name: "I can note details", descriptor: "Records information" },
      { name: "I can find the main ideas", descriptor: "Identifies the biggest points" },
      { name: "I can sort them", descriptor: "Places details under ideas" },
    ],
  },
  {
    standard_code: "SL.3.3",
    verbs: [
      { word: "Ask", gloss: "a question that opens" },
      { word: "Offer", gloss: "elaboration and detail" },
    ],
    concepts: ["Open versus closed questions", "Elaboration", "Extending"],
    vocabulary: [
      { term: "elaboration", definition: "saying more about something" },
      { term: "detail", definition: "a specific piece of information" },
      { term: "clarify", definition: "make clearer" },
    ],
    prior_skills: ["Ask clarifying questions", "Listen to a speaker", "Answer in sentences"],
    prior_standards: [{ code: "SL.2.3", text: "Ask and answer questions about what a speaker says to clarify comprehension" }],
    future_standards: [{ code: "SL.4.3", text: "Identify the reasons and evidence a speaker provides" }],
    challenges: [
      { problem: "Yes-or-no questions end the exchange rather than opening it", fix: "Sort questions into ones answerable in a word and ones that are not. Then ban the first kind" },
      { problem: "Answers are given without elaboration", fix: "Every answer carries a because or an example" },
    ],
    mastery_statement: "Student can ask an open question and answer with appropriate elaboration.",
    ladder: [
      { name: "I can ask a question", descriptor: "Participates" },
      { name: "I can tell open from closed", descriptor: "Distinguishes question types" },
      { name: "I can ask an open one", descriptor: "Opens the exchange" },
      { name: "I can elaborate when answering", descriptor: "Offers detail" },
    ],
  },
  {
    standard_code: "SL.3.4",
    verbs: [
      { word: "Report", gloss: "on a topic or text" },
      { word: "Speak", gloss: "clearly, at a followable pace" },
    ],
    concepts: ["Pace", "Relevant detail", "Organization of a talk"],
    vocabulary: [
      { term: "report", definition: "tell an audience about something" },
      { term: "recount", definition: "tell what happened" },
      { term: "relevant", definition: "actually to the point" },
      { term: "pace", definition: "how fast you speak" },
    ],
    prior_skills: ["Tell a story audibly", "Choose relevant details", "Speak in sentences"],
    prior_standards: [{ code: "SL.2.4", text: "Tell a story or recount an experience with facts and descriptive details, speaking audibly" }],
    future_standards: [{ code: "SL.4.4", text: "Report on a topic or text in an organized manner with appropriate facts" }],
    challenges: [
      { problem: "Nervousness produces rushing", fix: "Rehearse with a timer. It is the most reliable fix, and knowing the length reduces the nerves that cause the rush" },
      { problem: "Every detail is included", fix: "Three points, chosen and ordered before speaking" },
    ],
    mastery_statement: "Student can report on a topic with relevant detail at a pace listeners can follow.",
    ladder: [
      { name: "I can talk about it", descriptor: "Reports content" },
      { name: "I can choose my points", descriptor: "Selects relevant detail" },
      { name: "I can organize the order", descriptor: "Structures the talk" },
      { name: "I can pace it", descriptor: "Speaks understandably" },
    ],
  },
  {
    standard_code: "SL.3.5",
    verbs: [
      { word: "Create", gloss: "an engaging recording" },
      { word: "Add", gloss: "a visual that emphasizes" },
    ],
    concepts: ["Fluid reading", "Emphasis", "Support rather than duplication"],
    vocabulary: [
      { term: "audio recording", definition: "your voice, saved" },
      { term: "visual display", definition: "something shown to support what is said" },
      { term: "emphasize", definition: "make one thing stand out" },
      { term: "fluid", definition: "smooth and unhesitating" },
    ],
    prior_skills: ["Create a recording", "Add a clarifying visual", "Read aloud fluently"],
    prior_standards: [{ code: "SL.2.5", text: "Create audio recordings and add drawings to clarify ideas" }],
    future_standards: [{ code: "SL.4.5", text: "Add audio recordings and visual displays to presentations to enhance main ideas" }],
    challenges: [
      { problem: "Slides are filled with text and read aloud verbatim, duplicating the message rather than supporting it", fix: "Six words maximum on a slide. If it can be read aloud, it is doing the speaker's job" },
      { problem: "Recording is redone endlessly", fix: "Three takes, then it is finished" },
    ],
    mastery_statement: "Student can produce a fluid recording and a visual that emphasizes rather than repeats.",
    ladder: [
      { name: "I can record myself", descriptor: "Produces audio" },
      { name: "I can read it fluidly", descriptor: "Reads smoothly" },
      { name: "I can add a visual", descriptor: "Creates a display" },
      { name: "I can make it support, not repeat", descriptor: "Emphasizes appropriately" },
    ],
  },
  {
    standard_code: "SL.3.6",
    verbs: [
      { word: "Speak", gloss: "in complete sentences" },
      { word: "Provide", gloss: "the detail requested" },
      { word: "Adapt", gloss: "to the context" },
    ],
    concepts: ["Academic register", "Complete sentences", "Context"],
    vocabulary: [
      { term: "complete sentence", definition: "a whole thought spoken" },
      { term: "context", definition: "the situation you are speaking in" },
      { term: "clarification", definition: "making it clearer when asked" },
    ],
    prior_skills: ["Produce complete sentences", "Answer questions", "Judge a situation"],
    prior_standards: [{ code: "SL.2.6", text: "Produce complete sentences when appropriate to task and situation" }],
    future_standards: [{ code: "SL.4.6", text: "Differentiate between contexts calling for formal and informal English" }],
    challenges: [
      { problem: "Fragments are used in academic settings where a full response is expected", fix: "Name the settings. Academic talk has a register, and nobody has usually said so" },
      { problem: "Full sentences are used everywhere, sounding stilted", fix: "Sort the situations. Not every exchange needs one" },
    ],
    mastery_statement: "Student can speak in complete sentences where the academic situation calls for it.",
    ladder: [
      { name: "I can answer", descriptor: "Responds" },
      { name: "I can use a full sentence", descriptor: "Produces complete sentences" },
      { name: "I can add the detail asked for", descriptor: "Provides clarification" },
      { name: "I can judge the setting", descriptor: "Adapts to context" },
    ],
  },
  {
    standard_code: "L.3.2",
    verbs: [
      { word: "Capitalize", gloss: "words in titles" },
      { word: "Punctuate", gloss: "dialogue and addresses" },
      { word: "Form", gloss: "possessives correctly" },
    ],
    concepts: ["Dialogue punctuation", "Commas", "Possessives"],
    vocabulary: [
      { term: "quotation marks", definition: "the marks around spoken words" },
      { term: "dialogue", definition: "written speech" },
      { term: "possessive", definition: "showing ownership" },
      { term: "comma", definition: "the mark that separates" },
    ],
    prior_skills: ["Use apostrophes for possessives", "Capitalize proper nouns", "Use commas in letters"],
    prior_standards: [{ code: "L.2.2", text: "Use apostrophes for contractions and possessives and commas in greetings" }],
    future_standards: [{ code: "L.4.2", text: "Use correct capitalization, commas and quotation marks to mark direct speech" }],
    challenges: [
      { problem: "Quotation marks appear with no introducing comma, or the end punctuation sits outside them", fix: "A four-part checklist for every line of dialogue — comma, open, capital, close after punctuation" },
      { problem: "Possessives and plurals blur again under pressure", fix: "The two questions from grade 2, still applied" },
    ],
    mastery_statement: "Student can punctuate dialogue correctly and form possessives accurately.",
    ladder: [
      { name: "I can use end punctuation", descriptor: "Basic conventions" },
      { name: "I can use commas", descriptor: "Addresses and lists" },
      { name: "I can form possessives", descriptor: "Shows ownership" },
      { name: "I can punctuate dialogue", descriptor: "All four parts correct" },
    ],
  },
  {
    standard_code: "L.3.3",
    verbs: [
      { word: "Choose", gloss: "words for effect" },
      { word: "Recognize", gloss: "spoken against written English" },
      { word: "Adjust", gloss: "register for the audience" },
    ],
    concepts: ["Word choice for effect", "Register", "Spoken versus written"],
    vocabulary: [
      { term: "effect", definition: "what a word does to the reader" },
      { term: "formal", definition: "the careful register" },
      { term: "informal", definition: "the everyday register" },
      { term: "register", definition: "the level of formality" },
    ],
    prior_skills: ["Compare formal and informal English", "Name an audience", "Choose describing words"],
    prior_standards: [{ code: "L.2.3", text: "Compare formal and informal uses of English" }],
    future_standards: [{ code: "L.4.3", text: "Choose words and phrases to convey ideas precisely and differentiate contexts" }],
    challenges: [
      { problem: "Academic pieces are written in text-message register because nobody named the difference", fix: "Name it. Show the same sentence in three registers and ask which belongs where" },
      { problem: "Word choice is treated as decoration", fix: "Swap one word and read both aloud. The effect is audible" },
    ],
    mastery_statement: "Student can choose words for effect and match register to the situation.",
    ladder: [
      { name: "I can write a sentence", descriptor: "Produces language" },
      { name: "I can hear the difference", descriptor: "Recognizes register" },
      { name: "I can choose for effect", descriptor: "Selects deliberately" },
      { name: "I can match the audience", descriptor: "Adjusts register" },
    ],
  },
  {
    standard_code: "L.3.5",
    verbs: [
      { word: "Distinguish", gloss: "literal from nonliteral" },
      { word: "Identify", gloss: "real-life connections" },
      { word: "Distinguish", gloss: "shades of meaning" },
    ],
    concepts: ["Degrees of certainty", "Nonliteral meaning", "Word relationships"],
    vocabulary: [
      { term: "literal", definition: "meaning exactly what is said" },
      { term: "nonliteral", definition: "meaning something else" },
      { term: "shades of meaning", definition: "small differences between close words" },
      { term: "certainty", definition: "how sure you are" },
    ],
    prior_skills: ["Order words by intensity", "Recognize idioms", "Use synonyms"],
    prior_standards: [{ code: "L.2.5", text: "Demonstrate understanding of word relationships and nuances in word meanings" }],
    future_standards: [{ code: "L.4.5", text: "Demonstrate understanding of figurative language, word relationships and nuances" }],
    challenges: [
      { problem: "Knew, believed and suspected are treated as identical, missing degrees of certainty", fix: "Order them on a certainty line. Which one would you use in court?" },
      { problem: "Nonliteral phrases are recognized but not explained", fix: "Say the plain meaning and check it fits the sentence" },
    ],
    mastery_statement: "Student can order related words by degree and explain nonliteral meanings.",
    ladder: [
      { name: "I can find a synonym", descriptor: "Identifies related words" },
      { name: "I can spot nonliteral language", descriptor: "Distinguishes literal" },
      { name: "I can order by degree", descriptor: "Distinguishes shades" },
      { name: "I can say when to use each", descriptor: "Connects to real use" },
    ],
  },
  {
    standard_code: "L.3.6",
    verbs: [
      { word: "Acquire", gloss: "the vocabulary" },
      { word: "Use", gloss: "it accurately" },
    ],
    concepts: ["Three vocabulary tiers", "Spatial and temporal signals", "Production"],
    vocabulary: [
      { term: "conversational", definition: "everyday words" },
      { term: "academic", definition: "words used across school subjects" },
      { term: "domain-specific", definition: "words belonging to one subject" },
      { term: "spatial", definition: "showing where" },
      { term: "temporal", definition: "showing when" },
    ],
    prior_skills: ["Use newly acquired words", "Use adjectives and adverbs", "Read widely"],
    prior_standards: [{ code: "L.2.6", text: "Use words and phrases acquired through conversations and reading" }],
    future_standards: [{ code: "L.4.6", text: "Acquire and use grade-appropriate academic and domain-specific words" }],
    challenges: [
      { problem: "Vocabulary is learned for the quiz and never enters speech or writing", fix: "The test is whether it appears unprompted a week later, not whether it was defined on Friday" },
      { problem: "Academic words are avoided as risky", fix: "Reward the attempt, correct the accuracy separately" },
    ],
    mastery_statement: "Student can use academic and domain-specific vocabulary accurately in their own work.",
    ladder: [
      { name: "I can define the word", descriptor: "Knows the meaning" },
      { name: "I can use it when asked", descriptor: "Produces on demand" },
      { name: "I can use it accurately", descriptor: "Applies correctly" },
      { name: "I use it unprompted", descriptor: "Owns the vocabulary" },
    ],
  },
];

const blueprintsData = [
  {
    standard_code: "W.3.2",
    title: "Cut It Up and Sort It",
    badge: "Grade 3",
    route_name: "Writing Workshop",
    route_line: "Gather facts → Sort into groups → Link and conclude",
    success_criteria: ["Groups related information", "Uses linking words", "Concludes deliberately"],
    steps: [
      { name: "Retrieve Linking Words", minutes: 5, body: "Also, however, because, for example. Sorted by the job they do.", science_tag: "retrieval" },
      { name: "Facts in Random Order", minutes: 10, body: "A draft where nothing is grouped. Read it aloud and feel the reader lose the thread.", science_tag: "elaboration" },
      { name: "Cut Into Strips", minutes: 14, body: "The draft cut up and physically sorted. Groups become obvious once the sentences can be moved.", science_tag: "dual-coding" },
      { name: "Name Each Pile", minutes: 10, body: "The pile name becomes the paragraph's job.", science_tag: "elaboration" },
      { name: "Join the Piles", minutes: 10, body: "A linking word between each group, chosen for the relationship.", science_tag: "elaboration" },
      { name: "Rewrite in Order", minutes: 10, body: "The sorted version, with the links written in.", science_tag: "interleaving" },
      { name: "Reader Names the Groups", minutes: 3, body: "A partner says what each paragraph was about. If they cannot, it is not grouped.", science_tag: "collaborative" },
    ],
    ef_supports: ["Scissors and strips", "Linking word bank by function", "Pile naming labels", "Reader check"],
    tech: "Printed drafts that can be cut",
    tech_purpose: "Sorting has to be physical to be tried freely",
    ai_prompts: ["Write ungrouped informative drafts for sorting", "Generate linking words organized by function"],
    assessment: ["Check each paragraph has one job", "Confirm links match the relationship", "Ask a reader to name the groups"],
    why_it_works: ["Cutting the draft makes reordering cost nothing, so grouping gets discovered", "A pile that can be named is a paragraph; one that cannot is not", "Choosing the link by relationship pushes past and and then", "A reader who cannot name the groups is the clearest evidence"],
  },
  {
    standard_code: "W.3.4",
    title: "Name the Reader on the Page",
    badge: "Grade 3",
    route_name: "Writing Workshop",
    route_line: "Name the reader → Choose the shape → Write to fit",
    success_criteria: ["Identifies task and purpose", "Names an audience", "Matches organization to both"],
    steps: [
      { name: "Retrieve Purposes", minutes: 5, body: "To explain, to persuade, to tell a story, to instruct.", science_tag: "retrieval" },
      { name: "One Topic, Three Readers", minutes: 12, body: "The same content for a friend, a head teacher and a five-year-old. It cannot be the same piece.", science_tag: "elaboration" },
      { name: "Write the Reader Down", minutes: 8, body: "At the top of the page, before drafting. Not the teacher — the actual reader.", science_tag: "metacognition" },
      { name: "Choose a Shape", minutes: 12, body: "And say why it suits this purpose. Structure as a decision.", science_tag: "metacognition" },
      { name: "Draft to Fit", minutes: 14, body: "With reader and shape both visible on the page.", science_tag: "interleaving" },
      { name: "Does It Fit", minutes: 8, body: "Reread against the named reader, not against a rubric.", science_tag: "metacognition" },
      { name: "Swap Readers", minutes: 3, body: "What would change if the reader changed?", science_tag: "elaboration" },
    ],
    ef_supports: ["Reader-at-the-top routine", "Structure menu with reasons", "Three-reader comparison", "Fit check"],
    tech: "Drafts with a header line for the reader",
    tech_purpose: "The audience has to be visible while writing",
    ai_prompts: ["Write one message for three different audiences", "Generate purpose and audience pairings"],
    assessment: ["Check a real reader is named", "Confirm the structure was chosen with a reason", "Read the fit check"],
    why_it_works: ["One topic and three readers proves audience changes the writing", "Writing the reader on the page keeps them present during drafting", "Choosing a structure with a reason makes organization deliberate", "Checking against the reader beats checking against a rubric"],
  },
  {
    standard_code: "W.3.5",
    title: "Take Two, Decline One",
    badge: "Grade 3",
    route_name: "Writing Workshop",
    route_line: "Plan → Get feedback → Decide what to use",
    success_criteria: ["Plans before drafting", "Acts on feedback", "Judges which suggestions to take"],
    steps: [
      { name: "Retrieve Revise or Edit", minutes: 5, body: "The distinction from grade 2, still holding.", science_tag: "retrieval" },
      { name: "Plan on the Page", minutes: 10, body: "Before a draft is accepted. Revision cannot rescue an absent plan.", science_tag: "metacognition" },
      { name: "Three Suggestions", minutes: 12, body: "From a partner, written down rather than said.", science_tag: "collaborative" },
      { name: "Take Two, Decline One", minutes: 14, body: "With a written reason for the declined one. Judging is the skill — accepting everything and rejecting everything both avoid it.", science_tag: "metacognition" },
      { name: "Make the Changes", minutes: 12, body: "The two taken, actually implemented.", science_tag: "interleaving" },
      { name: "Then Edit", minutes: 8, body: "Conventions last, once the content has settled.", science_tag: "dual-coding" },
      { name: "What Improved", minutes: 3, body: "Named specifically, not generally.", science_tag: "metacognition" },
    ],
    ef_supports: ["Plan-first requirement", "Written suggestion slips", "Take-two-decline-one rule", "Declined reason frame"],
    tech: "Drafts with margins for suggestions",
    tech_purpose: "Written feedback can be weighed; spoken feedback evaporates",
    ai_prompts: ["Generate mixed-quality feedback on a draft", "Write drafts needing content revision"],
    assessment: ["Read the declined reason", "Check the plan preceded the draft", "Confirm two changes were made"],
    why_it_works: ["Requiring a declined suggestion makes judging unavoidable", "Written feedback can be compared; spoken feedback cannot", "Planning first stops revision doing work it should not have to", "Naming what improved is more useful than naming what changed"],
  },
  {
    standard_code: "W.3.6",
    title: "Compose by Hand, Type to Publish",
    badge: "Grade 3",
    route_name: "Writing Workshop",
    route_line: "Draft on paper → Type it up → Share and collaborate",
    success_criteria: ["Produces and publishes with technology", "Collaborates with others", "Content not limited by typing"],
    steps: [
      { name: "Retrieve Keyboard Basics", minutes: 5, body: "Shift, enter, backspace, and where the letters live.", science_tag: "retrieval" },
      { name: "Typing Shrinks Writing", minutes: 8, body: "Named honestly. A piece composed at the keyboard is usually shorter and thinner.", science_tag: "metacognition" },
      { name: "Draft on Paper", minutes: 14, body: "Content first, unconstrained by typing speed.", science_tag: "dual-coding" },
      { name: "Type It Up", minutes: 14, body: "Transcription, which is a manageable job on its own.", science_tag: "spaced" },
      { name: "Named Sections", minutes: 12, body: "In a shared document, each person owning one. Nobody watches.", science_tag: "collaborative" },
      { name: "Comment on a Partner's", minutes: 8, body: "Interacting, which the standard names.", science_tag: "collaborative" },
      { name: "Publish It", minutes: 4, body: "Somewhere a reader will actually find it.", science_tag: "collaborative" },
    ],
    ef_supports: ["Handwritten draft requirement", "Shared document with named sections", "Comment prompts", "Publishing destination"],
    tech: "Laptops with a collaborative document tool",
    tech_purpose: "Interacting and collaborating are named in the standard",
    ai_prompts: ["Generate collaborative writing prompts with distinct sections", "Write comment stems for peer response"],
    assessment: ["Compare handwritten and typed length", "Check every section has an owner", "Read the comments"],
    why_it_works: ["Composing by hand keeps typing speed from capping the thinking", "Named sections make watching impossible", "Commenting is the interacting half of the standard", "A real publishing destination gives the typing a point"],
  },
  {
    standard_code: "W.3.7",
    title: "Space, Planets, Why Mars Is Red",
    badge: "Grade 3",
    route_name: "Strategy Instruction",
    route_line: "Pick an area → Narrow it three times → Research and build",
    success_criteria: ["Narrows to a researchable question", "Uses multiple sources", "Builds knowledge"],
    steps: [
      { name: "Retrieve Research Steps", minutes: 5, body: "Question, sources, notes, product.", science_tag: "retrieval" },
      { name: "Too Big to Finish", minutes: 10, body: "A topic like animals, attempted honestly. Where would you even start?", science_tag: "elaboration" },
      { name: "Narrow It Three Times", minutes: 14, body: "Space, planets, Mars, why Mars is red. Narrowing is the skill, not a preliminary to it.", science_tag: "metacognition" },
      { name: "Can I Answer This", minutes: 8, body: "In two lessons, with the books available? A feasibility check.", science_tag: "metacognition" },
      { name: "Two Sources Minimum", minutes: 14, body: "And note where they say different things.", science_tag: "interleaving" },
      { name: "Build the Answer", minutes: 12, body: "From the notes, not from memory of the reading.", science_tag: "elaboration" },
      { name: "What I Still Do Not Know", minutes: 3, body: "Research raises questions as well as answering them.", science_tag: "metacognition" },
    ],
    ef_supports: ["Three-times narrowing ladder", "Feasibility check", "Two-source minimum", "Still-unknown box"],
    tech: "A text set plus a supervised search tool",
    tech_purpose: "The standard expects print and digital both",
    ai_prompts: ["Generate topic narrowing ladders", "Write source pairs that partially disagree"],
    assessment: ["Check the question is answerable in the time", "Confirm two sources", "Read the still-unknown box"],
    why_it_works: ["Attempting a too-broad topic shows why narrowing matters better than a rule", "Three explicit narrowings make it a procedure rather than a knack", "The feasibility check is what stops the third narrowing being skipped", "Noting what is still unknown treats research honestly"],
  },
  {
    standard_code: "W.3.8",
    title: "Cover the Book Before You Write",
    badge: "Grade 3",
    route_name: "Strategy Instruction",
    route_line: "Read it → Cover it → Write key words → Sort",
    success_criteria: ["Takes brief notes", "Uses own words", "Sorts into categories"],
    steps: [
      { name: "Retrieve What I Know", minutes: 6, body: "Before any source opens. Recall is half the standard.", science_tag: "retrieval" },
      { name: "Copying Becomes Plagiarism", minutes: 8, body: "Named plainly. The habit starts here and it does not stop on its own.", science_tag: "metacognition" },
      { name: "Cover and Write", minutes: 14, body: "Read the passage, cover it, then note. Copying becomes impossible rather than forbidden.", science_tag: "retrieval" },
      { name: "Boxes Too Small", minutes: 10, body: "Three words per box. The paper enforces brevity.", science_tag: "dual-coding" },
      { name: "Decide the Categories", minutes: 12, body: "Before the last source is read, so notes have somewhere to go.", science_tag: "dual-coding" },
      { name: "Sort the Notes", minutes: 10, body: "Physically, into the categories.", science_tag: "dual-coding" },
      { name: "Which Notes Were Useless", minutes: 3, body: "Crossed out. Relevance judged in hindsight.", science_tag: "metacognition" },
    ],
    ef_supports: ["Cover-and-write routine", "Three-word note boxes", "Category headers", "Cross-out review"],
    tech: "Print and digital sources",
    tech_purpose: "The standard names both",
    ai_prompts: ["Write sources at grade 3 level on one topic", "Generate category schemes for sorting notes"],
    assessment: ["Check notes are phrases", "Watch the cover step", "Confirm sorting happened"],
    why_it_works: ["Covering the source makes copying physically impossible", "A box that fits three words cannot hold a sentence", "Deciding categories before the last source gives notes a destination", "Naming plagiarism early is easier than correcting it in grade 7"],
  },
  {
    standard_code: "W.3.10",
    title: "Forty Minutes Is Not Three Weeks",
    badge: "Grade 3",
    route_name: "Writing Workshop",
    route_line: "Check the clock → Choose the process → Write to fit",
    success_criteria: ["Writes routinely", "Adjusts process to time frame", "Manages on-demand writing"],
    steps: [
      { name: "Retrieve the Writing Process", minutes: 5, body: "Plan, draft, revise, edit. The full version.", science_tag: "retrieval" },
      { name: "Planning Until the Time Runs Out", minutes: 10, body: "Demonstrated. A forty-minute piece with twenty-five minutes of planning fails, and that failure is instructive.", science_tag: "elaboration" },
      { name: "Two Plans, Two Clocks", minutes: 12, body: "Five minutes of planning for a short piece, a full plan for a long one. Both are planning.", science_tag: "metacognition" },
      { name: "Write to the Timer", minutes: 16, body: "On demand, with the clock visible.", science_tag: "spaced" },
      { name: "The Long Project", minutes: 10, body: "The same content over three sessions instead. Different process, same standard.", science_tag: "interleaving" },
      { name: "Which Was Harder", minutes: 6, body: "And why. Different demands, both real.", science_tag: "metacognition" },
      { name: "Write Something Every Day", minutes: 3, body: "Routinely is in the standard, and it means daily.", science_tag: "spaced" },
    ],
    ef_supports: ["Visible timer", "Two planning templates", "Time-frame decision card", "Daily writing routine"],
    tech: "A clock the whole room can see",
    tech_purpose: "Time management needs the time to be visible",
    ai_prompts: ["Generate on-demand writing prompts", "Write extended project briefs on the same topic"],
    assessment: ["Check planning is proportionate", "Confirm the piece was finished", "Compare short and extended work"],
    why_it_works: ["Watching the time run out during planning teaches proportion better than a rule", "Two planning templates make brief planning still count as planning", "A visible clock is what makes time management possible", "Writing daily is what routinely actually means"],
  },
  {
    standard_code: "SL.3.2",
    title: "Two Boxes, Three Details Each",
    badge: "Grade 3",
    route_name: "Structured Discussion",
    route_line: "Know the shape → Fill it while listening → Say it back",
    success_criteria: ["Determines main ideas", "Identifies supporting details", "Takes usable notes"],
    steps: [
      { name: "Retrieve Main Idea", minutes: 5, body: "The biggest point, not the most interesting detail.", science_tag: "retrieval" },
      { name: "Everything or Nothing", minutes: 8, body: "Two failed note pages — one a transcript attempt, one blank. Both come from having no structure.", science_tag: "metacognition" },
      { name: "The Frame Does the Sorting", minutes: 14, body: "Two main-idea boxes, three detail lines under each. The shape decides what goes where.", science_tag: "dual-coding" },
      { name: "Listen and Fill", minutes: 12, body: "During, not after. Key words only — the lines are too short for more.", science_tag: "dual-coding" },
      { name: "Say It Back", minutes: 10, body: "From the frame. Main ideas first, then details.", science_tag: "retrieval" },
      { name: "A Video Instead", minutes: 8, body: "Diverse media is in the standard.", science_tag: "interleaving" },
      { name: "Yesterday's Notes", minutes: 3, body: "Used to retell a day later.", science_tag: "spaced" },
    ],
    ef_supports: ["Two-box frame", "Short detail lines", "Say-it-back routine", "Media listening set"],
    tech: "Read-alouds and short video",
    tech_purpose: "Diverse media and formats are named in the standard",
    ai_prompts: ["Write read-alouds with two clear main ideas", "Generate media clips with identifiable structure"],
    assessment: ["Check the frame is filled during listening", "Confirm details sit under the right idea", "Test say-it-back"],
    why_it_works: ["A frame with fixed slots does the hierarchy work students cannot yet do alone", "Short lines make verbatim transcription impossible", "Showing both failure modes explains why structure is the answer", "Retelling a day later tests whether the notes were usable"],
  },
  {
    standard_code: "SL.3.3",
    title: "A Question You Cannot Answer With Yes",
    badge: "Grade 3",
    route_name: "Structured Discussion",
    route_line: "Sort the question types → Ban the closed ones → Elaborate when answering",
    success_criteria: ["Asks open questions", "Offers elaboration", "Requests clarification"],
    steps: [
      { name: "Retrieve Question Stems", minutes: 5, body: "What, how, why, what if.", science_tag: "retrieval" },
      { name: "One Word or More", minutes: 12, body: "Questions sorted by whether they can be answered in a word. Then the first kind is banned.", science_tag: "elaboration" },
      { name: "Watch One Die", minutes: 8, body: "A closed question in a real conversation. It stops, audibly.", science_tag: "elaboration" },
      { name: "Turn It Open", minutes: 12, body: "Did you like it becomes what changed your mind. The same curiosity, a different question.", science_tag: "metacognition" },
      { name: "Every Answer Elaborates", minutes: 12, body: "A because or an example attached to each. Elaboration is in the standard for the answerer too.", science_tag: "collaborative" },
      { name: "Interview a Partner", minutes: 10, body: "Three open questions, real answers.", science_tag: "collaborative" },
      { name: "Best Question of the Day", minutes: 3, body: "Named, and why it worked.", science_tag: "metacognition" },
    ],
    ef_supports: ["Open and closed sorting cards", "Turn-it-open frame", "Elaboration requirement", "Interview structure"],
    tech: "None — face to face",
    tech_purpose: "Watching a conversation die needs the conversation",
    ai_prompts: ["Generate closed and open question pairs on one topic", "Write elaboration prompts"],
    assessment: ["Count open questions", "Check answers elaborate", "Listen for the conversation continuing"],
    why_it_works: ["Sorting by answerability gives a test rather than a definition", "Watching a closed question kill a conversation is the argument", "Turning a closed question open keeps the curiosity and fixes the form", "Requiring elaboration makes the standard apply to both speakers"],
  },
  {
    standard_code: "SL.3.4",
    title: "Rehearse With a Timer",
    badge: "Grade 3",
    route_name: "Structured Presentation",
    route_line: "Choose three points → Rehearse against the clock → Deliver at pace",
    success_criteria: ["Reports with relevant facts", "Speaks clearly", "Uses an understandable pace"],
    steps: [
      { name: "Retrieve Relevant", minutes: 4, body: "To the point, as against merely true.", science_tag: "retrieval" },
      { name: "Three Points, Ordered", minutes: 10, body: "Chosen and sequenced before any rehearsal.", science_tag: "metacognition" },
      { name: "Rehearse With a Timer", minutes: 14, body: "The most reliable fix for rushing. Knowing the length reduces the nerves that cause it.", science_tag: "spaced" },
      { name: "Too Fast to Follow", minutes: 10, body: "A rushed delivery, then a paced one. The difference is obvious from the listener's side.", science_tag: "elaboration" },
      { name: "Mark Your Pauses", minutes: 10, body: "On the notes. A pause is a decision, not a gap.", science_tag: "dual-coding" },
      { name: "Deliver It", minutes: 12, body: "With a listener signalling if they lose you.", science_tag: "collaborative" },
      { name: "What Could I Follow", minutes: 3, body: "Audience feedback on pace, not content.", science_tag: "collaborative" },
    ],
    ef_supports: ["Timer", "Three-point planner", "Pause marking", "Lost-me signal"],
    tech: "A visible timer",
    tech_purpose: "Rehearsal against a clock is the fix the deck names",
    ai_prompts: ["Generate report topics with three natural points", "Write pace-focused feedback prompts"],
    assessment: ["Time the delivery against the rehearsal", "Check three points were used", "Ask about pace specifically"],
    why_it_works: ["Timed rehearsal addresses the cause of rushing rather than the symptom", "Hearing a rushed and a paced version makes pace audible", "Marked pauses turn silence into a deliberate act", "Feedback on pace alone keeps it separate from content"],
  },
  {
    standard_code: "SL.3.5",
    title: "Six Words on a Slide",
    badge: "Grade 3",
    route_name: "Structured Presentation",
    route_line: "Say it aloud → Ask what a visual could add → Make only that",
    success_criteria: ["Records fluidly", "Adds a visual that emphasizes", "Avoids duplicating the words"],
    steps: [
      { name: "Retrieve Emphasize", minutes: 4, body: "Make one thing stand out, not everything.", science_tag: "retrieval" },
      { name: "The Slide You Read Aloud", minutes: 10, body: "Full of text, read verbatim. It duplicates the speaker rather than supporting them.", science_tag: "metacognition" },
      { name: "Six Words Maximum", minutes: 12, body: "A hard limit. If it can be read aloud, it is doing the speaker's job.", science_tag: "dual-coding" },
      { name: "What Do My Words Miss", minutes: 12, body: "Asked before making anything. The answer is what the visual should be.", science_tag: "metacognition" },
      { name: "Record It Fluidly", minutes: 12, body: "Three takes maximum. Fluid is in the standard.", science_tag: "spaced" },
      { name: "Present With It", minutes: 10, body: "Speaking to the visual, not from it.", science_tag: "collaborative" },
      { name: "Did It Help", minutes: 3, body: "Asked of the audience, not the maker.", science_tag: "collaborative" },
    ],
    ef_supports: ["Six-word limit", "What-my-words-miss prompt", "Three-take rule", "Audience helpfulness check"],
    tech: "Recording device and presentation software",
    tech_purpose: "Audio and visual are both named in the standard",
    ai_prompts: ["Generate slide content within a six-word limit", "Write prompts for identifying visual gaps"],
    assessment: ["Count words on slides", "Check the visual fills a real gap", "Ask the audience whether it helped"],
    why_it_works: ["A six-word limit makes reading the slide aloud impossible", "Asking what the words miss produces the visual instead of decorating", "Three takes stops recording consuming the lesson", "Audience judgment is the only test of whether it helped"],
  },
  {
    standard_code: "SL.3.6",
    title: "Academic Talk Has a Register",
    badge: "Grade 3",
    route_name: "Oral Practice",
    route_line: "Read the setting → Choose the register → Answer in full",
    success_criteria: ["Speaks in complete sentences", "Provides requested detail", "Adapts to context"],
    steps: [
      { name: "Retrieve Complete Sentence", minutes: 4, body: "A whole thought, spoken.", science_tag: "retrieval" },
      { name: "Nobody Said So", minutes: 10, body: "Academic conversation expects full responses, and this is often the first time anyone has named that.", science_tag: "metacognition" },
      { name: "Sort the Settings", minutes: 12, body: "Lining up, discussion, presenting, chatting. Which need a full sentence?", science_tag: "elaboration" },
      { name: "Ask Again, Fuller", minutes: 12, body: "Every fragment prompted for the full version. The asking builds the habit.", science_tag: "collaborative" },
      { name: "The Detail Requested", minutes: 10, body: "Answer the question actually asked, with what it asked for.", science_tag: "elaboration" },
      { name: "Partner Practice", minutes: 8, body: "Academic questions, full answers, swapped.", science_tag: "collaborative" },
      { name: "Across the Day", minutes: 4, body: "The same expectation in maths and science.", science_tag: "spaced" },
    ],
    ef_supports: ["Setting sorting cards", "Ask-again prompt", "Sentence starters", "Cross-subject expectation"],
    tech: "None",
    tech_purpose: "This lives in ordinary classroom talk",
    ai_prompts: ["Generate academic questions requiring full responses", "Write settings for register sorting"],
    assessment: ["Count unprompted full responses", "Check the requested detail is given", "Watch register judgment"],
    why_it_works: ["Naming the academic register is often the missing step entirely", "Sorting settings stops full sentences becoming a blanket rule", "Prompting every fragment is what builds the habit", "Carrying it into other subjects is where it becomes normal"],
  },
  {
    standard_code: "L.3.2",
    title: "Four Things Every Line of Dialogue Needs",
    badge: "Grade 3",
    route_name: "Explicit Instruction",
    route_line: "Comma → Open marks → Capital → Close after the punctuation",
    success_criteria: ["Punctuates dialogue correctly", "Uses commas in addresses", "Forms possessives"],
    steps: [
      { name: "Retrieve Possessives", minutes: 5, body: "The two questions from grade 2, still applied.", science_tag: "retrieval" },
      { name: "The Four-Part Check", minutes: 14, body: "Comma before, marks open, capital inside, closing marks after the punctuation. The two failures the deck names are both in this list.", science_tag: "dual-coding" },
      { name: "Find the Missing Part", minutes: 12, body: "Lines with exactly one thing wrong. Which of the four?", science_tag: "elaboration" },
      { name: "Write Some Dialogue", minutes: 12, body: "Their own, checked against the four.", science_tag: "interleaving" },
      { name: "Commas in Addresses", minutes: 10, body: "A real envelope, actually addressed.", science_tag: "dual-coding" },
      { name: "Titles Get Capitals", minutes: 8, body: "Which words, and which do not.", science_tag: "interleaving" },
      { name: "Yesterday's Dialogue", minutes: 4, body: "Rechecked cold.", science_tag: "spaced" },
    ],
    ef_supports: ["Four-part dialogue checklist", "One-error line sets", "Real envelopes", "Title capitalization rules"],
    tech: "Whiteboards and printed dialogue",
    tech_purpose: "Dialogue has to be written to be punctuated",
    ai_prompts: ["Generate dialogue lines with single punctuation errors", "Write passages requiring possessives and dialogue"],
    assessment: ["Check all four parts", "Look at the closing punctuation position", "Confirm possessives"],
    why_it_works: ["A four-item checklist covers both failures the deck names in one routine", "Lines with exactly one error make diagnosis possible", "A real envelope gives address commas a purpose", "Checking cold the next day is where it becomes automatic"],
  },
  {
    standard_code: "L.3.3",
    title: "The Same Sentence, Three Registers",
    badge: "Grade 3",
    route_name: "Explicit Instruction",
    route_line: "Hear the registers → Name the setting → Choose deliberately",
    success_criteria: ["Chooses words for effect", "Recognizes spoken versus written", "Adjusts register"],
    steps: [
      { name: "Retrieve Formal and Informal", minutes: 5, body: "The distinction from grade 2.", science_tag: "retrieval" },
      { name: "Three Versions", minutes: 12, body: "The same message as a text, a note and a letter. All correct somewhere.", science_tag: "elaboration" },
      { name: "Nobody Named It", minutes: 8, body: "Text-message register in an essay happens because the difference was never stated. So it gets stated.", science_tag: "metacognition" },
      { name: "Swap One Word", minutes: 12, body: "Read both aloud. The effect of word choice is audible.", science_tag: "elaboration" },
      { name: "Which Belongs Where", minutes: 10, body: "Register matched to setting, with a reason.", science_tag: "metacognition" },
      { name: "Rewrite for Effect", minutes: 10, body: "One sentence, made sharper by one choice.", science_tag: "interleaving" },
      { name: "Check Your Own Draft", minutes: 3, body: "Any register that slipped?", science_tag: "metacognition" },
    ],
    ef_supports: ["Three-register examples", "Word swap pairs", "Setting matching cards", "Draft register check"],
    tech: "Written and spoken examples side by side",
    tech_purpose: "Comparing registers needs them present together",
    ai_prompts: ["Write one message in three registers", "Generate word pairs differing in effect"],
    assessment: ["Check register matches the setting", "Listen to word swap comparisons", "Read draft checks"],
    why_it_works: ["Three correct versions show register is context, not quality", "Naming the difference is the step that was actually missing", "Swapping one word makes effect audible rather than theoretical", "Checking their own draft is where it transfers"],
  },
  {
    standard_code: "L.3.5",
    title: "How Sure Are You",
    badge: "Grade 3",
    route_name: "Explicit Instruction",
    route_line: "Gather the close words → Order by certainty → Say when each fits",
    success_criteria: ["Distinguishes shades of meaning", "Explains nonliteral phrases", "Connects words to real use"],
    steps: [
      { name: "Retrieve Synonyms", minutes: 4, body: "Nearly the same, which is the operative word.", science_tag: "retrieval" },
      { name: "Knew, Believed, Suspected", minutes: 12, body: "The deck's own set. Ordered on a certainty line, which forces a decision.", science_tag: "dual-coding" },
      { name: "Which One in Court", minutes: 10, body: "A setting where the difference matters. Certainty is not decoration.", science_tag: "elaboration" },
      { name: "Argue the Order", minutes: 10, body: "Two children disagree. The argument is the understanding.", science_tag: "collaborative" },
      { name: "Nonliteral Too", minutes: 12, body: "Expressions explained in plain words and checked against the sentence.", science_tag: "interleaving" },
      { name: "When Would You Use It", minutes: 8, body: "A real moment for each word.", science_tag: "elaboration" },
      { name: "Yesterday's Line", minutes: 4, body: "A new word placed on an existing line.", science_tag: "spaced" },
    ],
    ef_supports: ["Certainty line strips", "Courtroom scenario", "Nonliteral explanation frame", "Real-use prompt"],
    tech: "Movable word cards",
    tech_purpose: "The line has to be rearrangeable for the argument to happen",
    ai_prompts: ["Generate word sets varying in certainty", "Write scenarios where the degree matters"],
    assessment: ["Check ordering, not just grouping", "Listen to the placement argument", "Confirm real-use examples"],
    why_it_works: ["A certainty line forces a decision that a synonym list never requires", "The courtroom setting shows the difference has consequences", "Disagreement about placement is where nuance gets articulated", "Naming a real moment ties the word to use rather than definition"],
  },
  {
    standard_code: "L.3.6",
    title: "Still Using It Next Week",
    badge: "Grade 3",
    route_name: "Routine and Practice",
    route_line: "Meet it → Use it → Use it again unprompted",
    success_criteria: ["Acquires academic vocabulary", "Uses it accurately", "Uses it beyond the lesson"],
    steps: [
      { name: "Retrieve Last Week's Words", minutes: 5, body: "Cold, before new ones arrive.", science_tag: "retrieval" },
      { name: "Learned for the Quiz", minutes: 8, body: "Named as the pattern it is. A word defined on Friday and never spoken again was not acquired.", science_tag: "metacognition" },
      { name: "Three Tiers", minutes: 10, body: "Conversational, academic, domain-specific. Different words, different homes.", science_tag: "elaboration" },
      { name: "Your Own Sentence", minutes: 12, body: "Not the book's. Production, not recognition.", science_tag: "elaboration" },
      { name: "Spatial and Temporal Signals", minutes: 10, body: "Beneath, afterwards, meanwhile. Named in the standard specifically.", science_tag: "interleaving" },
      { name: "Catch It in the Wild", minutes: 8, body: "Noticing a classmate using one. Tallied.", science_tag: "collaborative" },
      { name: "A Week Later", minutes: 4, body: "The real test — does it still appear unprompted?", science_tag: "spaced" },
    ],
    ef_supports: ["Three-tier word wall", "Own-sentence rule", "Signal word list", "Catch-it tally"],
    tech: "A word wall drawn from daily",
    tech_purpose: "A wall nobody uses is wallpaper",
    ai_prompts: ["Generate grade 3 academic vocabulary by tier", "Write prompts requiring spatial and temporal signals"],
    assessment: ["Test a week later, unprompted", "Check sentences are their own", "Count wild sightings"],
    why_it_works: ["Testing a week later measures acquisition rather than recall", "Naming the learned-for-the-quiz pattern makes the goal explicit", "Their own sentence is the difference between knowing and using", "Catching a classmate makes vocabulary noticed rather than tested"],
  },
];

seedStandardsBatch({
  label: "Batch 13 — grade 3 writing, speaking and language",
  standardsData,
  unpacksData,
  blueprintsData,
});
