// @ts-nocheck
/**
 * Batch 11: grade 2 mathematics.
 *
 * Finishes grade 2. With batches 9 and 10 the whole "Unpacking Standards 2nd"
 * deck is now in the library — 73 standards where there were 14.
 *
 * The maths misconceptions in the deck are the most useful content in it,
 * because they are diagnostic rather than general. A child who writes
 * 300 + 40 + 2 as 30042 is concatenating rather than composing, and that is a
 * different problem from not knowing expanded form. A child who says 89 is
 * greater than 132 is reading digits rather than places. Each blueprint is
 * built to surface its own error rather than to avoid it.
 *
 * American spellings throughout.
 *
 *   bun run scripts/seed-standards-batch-11.ts
 */
import { seedStandardsBatch } from "./lib/seed-standards-batch";

const standardsData = [
  // ─── Operations and algebraic thinking ───────────────────────────────────
  {
    code: "2.OA.C.3",
    name: "Odd and even by pairing",
    plain_reading:
      "Determine whether a group of objects (up to 20) has an odd or even number of members; write an equation to express an even number as a sum of two equal addends.",
    learning_target: "I can pair things up to find out if a group is odd or even, and say why.",
    skills: ["Odd and Even", "Pairing", "Equal Addends"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["odd or even", "pair objects", "equal addends", "count by 2s", "second grade"],
  },
  {
    code: "2.OA.C.4",
    name: "Arrays and repeated addition",
    plain_reading:
      "Use addition to find the total number of objects arranged in rectangular arrays with up to 5 rows and 5 columns; write an equation as a sum of equal addends.",
    learning_target: "I can say three rows of four and write 4 + 4 + 4 instead of counting every square.",
    skills: ["Arrays", "Repeated Addition", "Rows and Columns"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["rectangular arrays", "rows and columns", "repeated addition", "equal addends", "foundations for multiplication"],
  },

  // ─── Number and operations in base ten ───────────────────────────────────
  {
    code: "2.NBT.A.2",
    name: "Skip count from anywhere",
    plain_reading: "Count within 1000; skip-count by 5s, 10s, and 100s.",
    learning_target: "I can skip count by tens starting at 250, not just at zero.",
    skills: ["Skip Counting", "Counting to 1000", "Number Patterns"],
    science_tags: ["retrieval", "spaced"],
    match_keys: ["count within 1000", "skip count by 5s 10s 100s", "start from any number", "number pattern"],
  },
  {
    code: "2.NBT.A.3",
    name: "One number, three ways",
    plain_reading:
      "Read and write numbers to 1000 using base-ten numerals, number names, and expanded form.",
    learning_target: "I can write a number as a numeral, in words, and in expanded form.",
    skills: ["Expanded Form", "Number Names", "Base-Ten Numerals"],
    science_tags: ["dual-coding", "interleaving"],
    match_keys: ["expanded form", "number names", "base-ten numerals", "standard form", "read and write to 1000"],
  },
  {
    code: "2.NBT.A.4",
    name: "Compare by place, not by digit",
    plain_reading:
      "Compare two three-digit numbers based on meanings of the hundreds, tens, and ones digits, using >, =, and < symbols.",
    learning_target: "I can compare the hundreds first and say why that comes first.",
    skills: ["Comparing Numbers", "Place Value", "Greater and Less Than"],
    science_tags: ["dual-coding", "metacognition"],
    match_keys: ["compare three-digit numbers", "greater than less than", "place value", "order numbers"],
  },
  {
    code: "2.NBT.B.6",
    name: "Add four numbers the easy way round",
    plain_reading:
      "Add up to four two-digit numbers using strategies based on place value and properties of operations.",
    learning_target: "I can look for pairs that make ten before I start adding.",
    skills: ["Adding Multiple Addends", "Making Ten", "Properties of Operations"],
    science_tags: ["elaboration", "metacognition"],
    match_keys: ["add four two-digit numbers", "make ten", "commutative", "associative", "mental strategies"],
  },
  {
    code: "2.NBT.B.7",
    name: "Add and subtract within 1000",
    plain_reading:
      "Add and subtract within 1000, using concrete models or drawings and strategies based on place value.",
    learning_target: "I can tell when I need to regroup and when I do not.",
    skills: ["Regrouping", "Models and Drawings", "Place Value Strategies"],
    science_tags: ["dual-coding", "interleaving"],
    match_keys: ["add and subtract within 1000", "regroup", "compose decompose", "concrete models", "drawings"],
  },
  {
    code: "2.NBT.B.8",
    name: "Ten or a hundred more, in your head",
    plain_reading:
      "Mentally add 10 or 100 to, or subtract 10 or 100 from, a given number 100-900.",
    learning_target: "I can say which digit changes and do it without writing anything.",
    skills: ["Mental Math", "Place Value Patterns", "Adding Ten and Hundred"],
    science_tags: ["retrieval", "dual-coding"],
    match_keys: ["mentally add 10 or 100", "subtract 10 or 100", "hundreds chart", "place value pattern"],
  },
  {
    code: "2.NBT.B.9",
    name: "Explain why the strategy works",
    plain_reading:
      "Explain why addition and subtraction strategies work, using place value and the properties of operations.",
    learning_target: "I can say why my way works, not just what I did.",
    skills: ["Mathematical Reasoning", "Justification", "Critiquing Methods"],
    science_tags: ["metacognition", "collaborative"],
    match_keys: ["explain why strategies work", "justify", "place value reasoning", "critique", "properties of operations"],
  },

  // ─── Measurement and data ────────────────────────────────────────────────
  {
    code: "2.MD.A.2",
    name: "Smaller unit, bigger number",
    plain_reading:
      "Measure the length of an object twice, using different length units; describe how the two measurements relate to the size of the unit.",
    learning_target: "I can explain why the same desk is 30 inches and only 2 feet.",
    skills: ["Measuring in Two Units", "Unit Size", "Inverse Relationship"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["measure twice different units", "size of the unit", "inches and feet", "centimeters and meters"],
  },
  {
    code: "2.MD.A.3",
    name: "Estimate against something you know",
    plain_reading:
      "Estimate lengths using units of inches, feet, centimeters, and meters.",
    learning_target: "I can compare to a paper clip or a door instead of guessing.",
    skills: ["Estimation", "Benchmarks", "Checking by Measuring"],
    science_tags: ["retrieval", "metacognition"],
    match_keys: ["estimate lengths", "benchmark", "inches feet centimeters meters", "reasonable estimate"],
  },
  {
    code: "2.MD.A.4",
    name: "How much longer is a difference",
    plain_reading:
      "Measure to determine how much longer one object is than another, expressing the difference in a standard length unit.",
    learning_target: "I can hear that how much longer means subtract.",
    skills: ["Measuring Difference", "Subtraction", "Standard Units"],
    science_tags: ["elaboration", "metacognition"],
    match_keys: ["how much longer", "difference in length", "measure two objects", "standard length unit"],
  },
  {
    code: "2.MD.B.5",
    name: "Length word problems, with the unit",
    plain_reading:
      "Use addition and subtraction within 100 to solve word problems involving lengths given in the same units.",
    learning_target: "I can solve a length problem and label my answer with the unit.",
    skills: ["Length Word Problems", "Equations", "Units in Answers"],
    science_tags: ["interleaving", "metacognition"],
    match_keys: ["length word problems", "within 100", "unknown", "same units", "label the unit"],
  },
  {
    code: "2.MD.B.6",
    name: "Jumps on a number line",
    plain_reading:
      "Represent whole numbers as lengths on a number line diagram and represent whole-number sums and differences within 100.",
    learning_target: "I can count the spaces, not the tick marks.",
    skills: ["Number Line", "Sums and Differences", "Equal Intervals"],
    science_tags: ["dual-coding", "metacognition"],
    match_keys: ["number line diagram", "jumps", "equally spaced", "sums and differences within 100", "interval"],
  },
  {
    code: "2.MD.C.7",
    name: "Time to the nearest five minutes",
    plain_reading:
      "Tell and write time from analog and digital clocks to the nearest five minutes, using a.m. and p.m.",
    learning_target: "I can read the hour hand first, then the minutes.",
    skills: ["Telling Time", "Analog and Digital", "a.m. and p.m."],
    science_tags: ["dual-coding", "spaced"],
    match_keys: ["tell time nearest five minutes", "analog digital clock", "a.m. p.m.", "hour hand", "minute hand"],
  },
  {
    code: "2.MD.D.9",
    name: "Measure, then make a line plot",
    plain_reading:
      "Generate measurement data by measuring lengths of several objects; show the measurements by making a line plot.",
    learning_target: "I can make a line plot where the spacing tells the truth about my data.",
    skills: ["Measurement Data", "Line Plots", "Scale"],
    science_tags: ["dual-coding", "metacognition"],
    match_keys: ["line plot", "measurement data", "horizontal scale", "whole units", "generate data"],
  },
  {
    code: "2.MD.D.10",
    name: "Bar graphs, and reading the scale",
    plain_reading:
      "Draw a picture graph and a bar graph to represent a data set with up to four categories; solve problems using information in the graphs.",
    learning_target: "I can check the scale before I read a bar.",
    skills: ["Bar Graphs", "Picture Graphs", "Interpreting Data"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["bar graph", "picture graph", "key", "scale", "four categories", "compare questions"],
  },

  // ─── Geometry ────────────────────────────────────────────────────────────
  {
    code: "2.G.A.1",
    name: "Shapes by attribute, any way up",
    plain_reading:
      "Recognize and draw shapes having specified attributes, such as a given number of angles or a given number of equal faces.",
    learning_target: "I can still name a triangle when it is balanced on a point.",
    skills: ["Shape Attributes", "Sides and Angles", "Drawing Shapes"],
    science_tags: ["dual-coding", "interleaving"],
    match_keys: ["shape attributes", "angles", "faces", "triangle quadrilateral pentagon hexagon cube", "orientation"],
  },
  {
    code: "2.G.A.2",
    name: "Partition a rectangle into equal squares",
    plain_reading:
      "Partition a rectangle into rows and columns of same-size squares and count to find the total number of them.",
    learning_target: "I can split a rectangle into squares that are all the same size.",
    skills: ["Partitioning", "Rows and Columns", "Same-Size Squares"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["partition a rectangle", "rows and columns", "same-size squares", "count the total", "area foundation"],
  },
];

const unpacksData = [
  {
    standard_code: "2.OA.C.3",
    verbs: [
      { word: "Determine", gloss: "work out odd or even" },
      { word: "Write", gloss: "express it as two equal addends" },
    ],
    concepts: ["Pairing", "Even as two equal groups", "Equation"],
    vocabulary: [
      { term: "odd", definition: "a number that leaves one over when you pair everything up" },
      { term: "even", definition: "a number that pairs up with none left over" },
      { term: "pair", definition: "a group of two" },
      { term: "equal addends", definition: "two numbers the same, added together" },
    ],
    prior_skills: ["Count to 20", "Count by 2s", "Write an addition equation"],
    prior_standards: [{ code: "1.OA.C.6", text: "Add and subtract within 20 using strategies" }],
    future_standards: [{ code: "3.OA.A.1", text: "Interpret products of whole numbers as equal groups" }],
    challenges: [
      { problem: "Ends in 0, 2, 4, 6, 8 is memorized with no idea why, so it cannot be applied to a pile of objects", fix: "Pair actual objects before any numeral appears. The rule is the last step, not the first" },
      { problem: "Odd is described as leftover without an equation", fix: "Even numbers get 8 = 4 + 4 written down; odd numbers cannot, and that is the proof" },
    ],
    mastery_statement: "Student can pair objects to decide odd or even and write an even number as two equal addends.",
    ladder: [
      { name: "I can count by 2s", descriptor: "Skip counts" },
      { name: "I can pair the objects", descriptor: "Uses pairing" },
      { name: "I can say odd or even", descriptor: "Determines from pairing" },
      { name: "I can write the equation", descriptor: "Expresses as equal addends" },
    ],
  },
  {
    standard_code: "2.OA.C.4",
    verbs: [
      { word: "Build", gloss: "make the array" },
      { word: "Count", gloss: "using rows, not one by one" },
      { word: "Write", gloss: "the equation of equal addends" },
    ],
    concepts: ["Array structure", "Row as a unit", "Repeated addition"],
    vocabulary: [
      { term: "array", definition: "objects in equal rows and columns" },
      { term: "row", definition: "objects across" },
      { term: "column", definition: "objects down" },
      { term: "repeated addition", definition: "adding the same number again and again" },
    ],
    prior_skills: ["Count objects", "Add within 20", "Recognize equal groups"],
    prior_standards: [{ code: "2.OA.C.3", text: "Determine odd or even and write even numbers as equal addends" }],
    future_standards: [{ code: "3.OA.A.1", text: "Interpret products as the total number of objects in equal groups" }],
    challenges: [
      { problem: "Every square is counted one at a time, ignoring the structure", fix: "Cover all but one row. What is in a row? Then how many rows? The covering is what makes the structure usable" },
      { problem: "The equation is written as a total rather than as equal addends", fix: "Say 3 rows of 4 aloud, then write 4 + 4 + 4 — the words come before the notation" },
    ],
    mastery_statement: "Student can find an array total using rows and write it as a sum of equal addends.",
    ladder: [
      { name: "I can count the objects", descriptor: "Finds a total" },
      { name: "I can see the rows", descriptor: "Recognizes structure" },
      { name: "I can say rows of", descriptor: "Uses the language of groups" },
      { name: "I can write equal addends", descriptor: "Writes the equation" },
    ],
  },
  {
    standard_code: "2.NBT.A.2",
    verbs: [
      { word: "Count", gloss: "within 1000" },
      { word: "Skip count", gloss: "by 5s, 10s and 100s" },
      { word: "Continue", gloss: "from any starting number" },
    ],
    concepts: ["Counting sequence", "Skip counting patterns", "Starting anywhere"],
    vocabulary: [
      { term: "skip count", definition: "count in jumps of the same size" },
      { term: "pattern", definition: "something that repeats in a predictable way" },
      { term: "sequence", definition: "numbers in order" },
    ],
    prior_skills: ["Count to 120", "Count by 10s from zero", "Read three-digit numbers"],
    prior_standards: [{ code: "1.NBT.A.1", text: "Count to 120 starting at any number less than 120" }],
    future_standards: [{ code: "2.NBT.B.8", text: "Mentally add or subtract 10 or 100" }],
    challenges: [
      { problem: "Skip counting works from zero but collapses from 250", fix: "Practice starting at numbers that are not multiples of the skip. The deck names this precisely" },
      { problem: "The count is recited rather than understood", fix: "Ask what changes each time, and which digit stays put" },
    ],
    mastery_statement: "Student can skip count by 5s, 10s and 100s from any starting number within 1000.",
    ladder: [
      { name: "I can count to 1000", descriptor: "Counts by ones" },
      { name: "I can skip count from zero", descriptor: "Uses the sequence" },
      { name: "I can start anywhere", descriptor: "Continues from any number" },
      { name: "I can say what changes", descriptor: "Explains the pattern" },
    ],
  },
  {
    standard_code: "2.NBT.A.3",
    verbs: [
      { word: "Read", gloss: "say the number" },
      { word: "Write", gloss: "in numerals, words and expanded form" },
    ],
    concepts: ["Expanded form as composition", "Number names", "Three representations"],
    vocabulary: [
      { term: "numeral", definition: "the number written in digits" },
      { term: "number name", definition: "the number written in words" },
      { term: "expanded form", definition: "the number split into its place values and added" },
      { term: "standard form", definition: "the ordinary way of writing it" },
    ],
    prior_skills: ["Read two-digit numbers", "Know hundreds, tens and ones", "Write number words"],
    prior_standards: [{ code: "2.NBT.A.1", text: "Understand that the three digits of a three-digit number represent hundreds, tens and ones" }],
    future_standards: [{ code: "3.NBT.A.1", text: "Use place value understanding to round whole numbers" }],
    challenges: [
      { problem: "300 + 40 + 2 is written as 30042 — concatenating rather than composing", fix: "Blocks alongside the notation, every time. The digits have to be seen combining rather than queueing" },
      { problem: "Expanded form is copied as a pattern without meaning", fix: "Give the expanded form and ask for the numeral, so the direction reverses" },
    ],
    mastery_statement: "Student can write a number to 1000 as a numeral, in words and in expanded form.",
    ladder: [
      { name: "I can read the number", descriptor: "Reads numerals" },
      { name: "I can write the numeral", descriptor: "Writes standard form" },
      { name: "I can write the words", descriptor: "Uses number names" },
      { name: "I can expand it", descriptor: "Writes expanded form correctly" },
    ],
  },
  {
    standard_code: "2.NBT.A.4",
    verbs: [
      { word: "Compare", gloss: "decide which is greater" },
      { word: "Use", gloss: "the symbols correctly" },
      { word: "Order", gloss: "arrange a set" },
    ],
    concepts: ["Place value comparison", "Hundreds first", "Symbols"],
    vocabulary: [
      { term: "compare", definition: "decide which is more" },
      { term: "greater than", definition: "more than, written >" },
      { term: "less than", definition: "fewer than, written <" },
      { term: "equal to", definition: "the same as, written =" },
    ],
    prior_skills: ["Compare two-digit numbers", "Know place value to hundreds", "Read three-digit numbers"],
    prior_standards: [{ code: "2.NBT.A.3", text: "Read and write numbers to 1000 in numerals, names and expanded form" }],
    future_standards: [{ code: "3.NBT.A.1", text: "Use place value understanding to round to the nearest 10 or 100" }],
    challenges: [
      { problem: "Leftmost digits are compared without checking place, so 89 is judged greater than 132", fix: "Write them stacked and aligned, and count the digits first. Alignment does the work" },
      { problem: "The symbols are reversed", fix: "The open end faces the bigger number, and say that aloud every time" },
    ],
    mastery_statement: "Student can compare three-digit numbers by place value and record with >, = or <.",
    ladder: [
      { name: "I can read both numbers", descriptor: "Reads three-digit numbers" },
      { name: "I can count the digits", descriptor: "Checks magnitude first" },
      { name: "I can compare the hundreds", descriptor: "Uses place value" },
      { name: "I can write the symbol", descriptor: "Records correctly" },
    ],
  },
  {
    standard_code: "2.NBT.B.6",
    verbs: [
      { word: "Add", gloss: "up to four two-digit numbers" },
      { word: "Look", gloss: "for pairs that make ten" },
      { word: "Apply", gloss: "the properties to reorder" },
    ],
    concepts: ["Making ten", "Reordering addends", "Efficiency"],
    vocabulary: [
      { term: "addend", definition: "a number being added" },
      { term: "total", definition: "what you get when you add" },
      { term: "commutative", definition: "you can add in any order" },
      { term: "associative", definition: "you can group them any way" },
    ],
    prior_skills: ["Add two two-digit numbers", "Know pairs that make ten", "Add three numbers"],
    prior_standards: [{ code: "2.NBT.B.5", text: "Fluently add and subtract within 100" }],
    future_standards: [{ code: "3.NBT.A.2", text: "Fluently add and subtract within 1000" }],
    challenges: [
      { problem: "Adding strictly left to right, missing friendly pairs", fix: "Ask which two you would add first, and why — before any adding happens" },
      { problem: "Reordering feels like cheating", fix: "Show the same four numbers added in three orders, all giving one total" },
    ],
    mastery_statement: "Student can add up to four two-digit numbers, choosing an order that makes it easier.",
    ladder: [
      { name: "I can add two", descriptor: "Adds two-digit numbers" },
      { name: "I can add them in order", descriptor: "Adds several left to right" },
      { name: "I can spot a ten", descriptor: "Finds friendly pairs" },
      { name: "I can choose my order", descriptor: "Applies properties deliberately" },
    ],
  },
  {
    standard_code: "2.NBT.B.7",
    verbs: [
      { word: "Add", gloss: "within 1000" },
      { word: "Subtract", gloss: "within 1000" },
      { word: "Regroup", gloss: "when, and only when, it is needed" },
    ],
    concepts: ["Regrouping", "Composing and decomposing", "Models"],
    vocabulary: [
      { term: "regroup", definition: "trade ten of one place for one of the next" },
      { term: "compose", definition: "put together into a bigger unit" },
      { term: "decompose", definition: "break a unit into smaller ones" },
      { term: "model", definition: "blocks or a drawing that shows the number" },
    ],
    prior_skills: ["Add and subtract within 100", "Know place value to hundreds", "Use base-ten blocks"],
    prior_standards: [{ code: "2.NBT.B.5", text: "Fluently add and subtract within 100" }],
    future_standards: [{ code: "3.NBT.A.2", text: "Fluently add and subtract within 1000 using strategies and algorithms" }],
    challenges: [
      { problem: "Regrouping happens on every problem whether or not it is needed", fix: "Mix problems that need it with problems that do not, unlabelled. Deciding is the skill" },
      { problem: "The algorithm runs with no idea what the carried digit is", fix: "Blocks beside the numerals until the trade can be narrated" },
    ],
    mastery_statement: "Student can add and subtract within 1000, regrouping only when the numbers require it.",
    ladder: [
      { name: "I can add without regrouping", descriptor: "Adds straightforward cases" },
      { name: "I can show it with blocks", descriptor: "Models the number" },
      { name: "I can regroup when needed", descriptor: "Trades correctly" },
      { name: "I can tell when I need to", descriptor: "Decides rather than defaults" },
    ],
  },
  {
    standard_code: "2.NBT.B.8",
    verbs: [
      { word: "Add", gloss: "10 or 100, mentally" },
      { word: "Subtract", gloss: "10 or 100, mentally" },
      { word: "Notice", gloss: "which digit moves" },
    ],
    concepts: ["Place value pattern", "Mental computation", "Which digit changes"],
    vocabulary: [
      { term: "mentally", definition: "in your head, with nothing written" },
      { term: "more", definition: "added on" },
      { term: "less", definition: "taken away" },
    ],
    prior_skills: ["Skip count by 10s and 100s", "Know place value to hundreds", "Read a hundreds chart"],
    prior_standards: [{ code: "2.NBT.A.2", text: "Count within 1000; skip-count by 5s, 10s and 100s" }],
    future_standards: [{ code: "3.NBT.A.2", text: "Fluently add and subtract within 1000" }],
    challenges: [
      { problem: "Reliance on a written algorithm makes this impossible mentally", fix: "Hundreds chart first to make the pattern visible, then take it away. The chart is a scaffold, not the method" },
      { problem: "All digits are recalculated instead of one changing", fix: "Ask which digits stayed the same before giving the answer" },
    ],
    mastery_statement: "Student can mentally add or subtract 10 or 100 and say which digit changed.",
    ladder: [
      { name: "I can use a chart", descriptor: "Finds it on a hundreds chart" },
      { name: "I can see the pattern", descriptor: "Notices the moving digit" },
      { name: "I can do it in my head", descriptor: "Computes mentally" },
      { name: "I can explain which changed", descriptor: "Articulates the place value" },
    ],
  },
  {
    standard_code: "2.NBT.B.9",
    verbs: [
      { word: "Explain", gloss: "why it works, not what you did" },
      { word: "Justify", gloss: "with place value or a model" },
      { word: "Critique", gloss: "someone else's method" },
    ],
    concepts: ["Justification", "Why versus what", "Critiquing reasoning"],
    vocabulary: [
      { term: "explain", definition: "say why it works" },
      { term: "justify", definition: "give the reason it must be right" },
      { term: "reasoning", definition: "the thinking behind the answer" },
      { term: "strategy", definition: "the way you chose to solve it" },
    ],
    prior_skills: ["Use an addition strategy", "Model with blocks", "Talk about maths"],
    prior_standards: [{ code: "2.NBT.B.7", text: "Add and subtract within 1000 using models and place value strategies" }],
    future_standards: [{ code: "3.NBT.A.2", text: "Fluently add and subtract within 1000 using strategies and algorithms" }],
    challenges: [
      { problem: "The steps taken are described instead of why they work", fix: "Ban first I and then I. The sentence has to begin this works because" },
      { problem: "A wrong method is accepted because the answer was right", fix: "Give a right answer from a broken method and ask whether it will always work" },
    ],
    mastery_statement: "Student can explain why a strategy works using place value, and find the flaw in another.",
    ladder: [
      { name: "I can say what I did", descriptor: "Describes steps" },
      { name: "I can show it with a model", descriptor: "Represents the reasoning" },
      { name: "I can say why it works", descriptor: "Justifies with place value" },
      { name: "I can find a mistake", descriptor: "Critiques another method" },
    ],
  },
  {
    standard_code: "2.MD.A.2",
    verbs: [
      { word: "Measure", gloss: "the same object twice" },
      { word: "Compare", gloss: "the two numbers" },
      { word: "Describe", gloss: "how unit size changes the count" },
    ],
    concepts: ["Unit size", "Inverse relationship", "Same object, two numbers"],
    vocabulary: [
      { term: "unit", definition: "what you are measuring in" },
      { term: "inch", definition: "a small customary length unit" },
      { term: "foot", definition: "twelve inches" },
      { term: "centimeter", definition: "a small metric length unit" },
      { term: "meter", definition: "a hundred centimeters" },
    ],
    prior_skills: ["Measure with a ruler", "Line up at zero", "Read a scale"],
    prior_standards: [{ code: "2.MD.A.1", text: "Measure the length of an object using appropriate tools" }],
    future_standards: [{ code: "3.MD.B.4", text: "Generate measurement data by measuring lengths to the nearest half inch" }],
    challenges: [
      { problem: "The bigger number is taken to mean the longer object, even in different units", fix: "Measure the same desk in inches and in feet. One object, two numbers, and the object never changed" },
      { problem: "The relationship is stated backwards", fix: "Smaller unit, more of them — said while holding both units" },
    ],
    mastery_statement: "Student can measure one object in two units and explain why the smaller unit gives a bigger number.",
    ladder: [
      { name: "I can measure once", descriptor: "Uses a ruler correctly" },
      { name: "I can measure in two units", descriptor: "Repeats with a different unit" },
      { name: "I can compare the numbers", descriptor: "Notices the difference" },
      { name: "I can say why", descriptor: "Relates unit size to count" },
    ],
  },
  {
    standard_code: "2.MD.A.3",
    verbs: [
      { word: "Estimate", gloss: "say about how long" },
      { word: "Use", gloss: "a benchmark you know" },
      { word: "Check", gloss: "by measuring" },
    ],
    concepts: ["Benchmark", "Reasonableness", "Estimate then verify"],
    vocabulary: [
      { term: "estimate", definition: "a sensible guess, not a random one" },
      { term: "benchmark", definition: "something known you compare against" },
      { term: "about", definition: "close to, not exact" },
      { term: "reasonable", definition: "sensible, in the right area" },
    ],
    prior_skills: ["Measure with standard units", "Know an inch and a centimeter", "Compare lengths"],
    prior_standards: [{ code: "2.MD.A.1", text: "Measure the length of an object using appropriate tools" }],
    future_standards: [{ code: "3.MD.B.4", text: "Measure lengths using rulers marked with halves and fourths" }],
    challenges: [
      { problem: "Estimates are random guesses with no referent", fix: "Establish benchmarks first — a paper clip is about an inch, a door about two meters. An estimate without a referent is a guess" },
      { problem: "Estimating is treated as failing to measure", fix: "Score closeness, not correctness" },
    ],
    mastery_statement: "Student can estimate a length using a personal benchmark and check it by measuring.",
    ladder: [
      { name: "I can measure it", descriptor: "Uses a tool" },
      { name: "I know some benchmarks", descriptor: "Holds referents" },
      { name: "I can estimate first", descriptor: "Predicts before measuring" },
      { name: "I can get close", descriptor: "Estimates reasonably" },
    ],
  },
  {
    standard_code: "2.MD.A.4",
    verbs: [
      { word: "Measure", gloss: "both, in the same unit" },
      { word: "Subtract", gloss: "to find the difference" },
      { word: "Express", gloss: "the answer with its unit" },
    ],
    concepts: ["Difference", "Comparison as subtraction", "Same unit"],
    vocabulary: [
      { term: "difference", definition: "how much more one is than the other" },
      { term: "longer", definition: "more length" },
      { term: "shorter", definition: "less length" },
      { term: "compare", definition: "see how two things measure up" },
    ],
    prior_skills: ["Measure accurately", "Subtract within 100", "Compare lengths"],
    prior_standards: [{ code: "2.MD.A.1", text: "Measure the length of an object using appropriate tools" }],
    future_standards: [{ code: "2.MD.B.5", text: "Use addition and subtraction to solve word problems involving length" }],
    challenges: [
      { problem: "The two lengths are added instead of subtracted", fix: "Anchor the phrase — how much longer asks for a difference. Line the objects up so the extra bit is visible" },
      { problem: "The unit is dropped from the answer", fix: "An answer without a unit is not an answer" },
    ],
    mastery_statement: "Student can find how much longer one object is and express the difference with its unit.",
    ladder: [
      { name: "I can measure both", descriptor: "Measures in the same unit" },
      { name: "I can say which is longer", descriptor: "Compares" },
      { name: "I can subtract", descriptor: "Finds the difference" },
      { name: "I can label the unit", descriptor: "Expresses in a standard unit" },
    ],
  },
  {
    standard_code: "2.MD.B.5",
    verbs: [
      { word: "Solve", gloss: "the word problem" },
      { word: "Represent", gloss: "with a drawing or equation" },
      { word: "Label", gloss: "the answer with its unit" },
    ],
    concepts: ["Length word problems", "Unknown", "Consistent units"],
    vocabulary: [
      { term: "length", definition: "how long something is" },
      { term: "unknown", definition: "the part you are trying to find" },
      { term: "equation", definition: "a number sentence with an equals sign" },
      { term: "unit", definition: "what the measurement is in" },
    ],
    prior_skills: ["Add and subtract within 100", "Measure length", "Solve word problems"],
    prior_standards: [{ code: "2.MD.A.4", text: "Measure to determine how much longer one object is than another" }],
    future_standards: [{ code: "3.MD.B.4", text: "Generate and represent measurement data" }],
    challenges: [
      { problem: "The unit is dropped — 18 written instead of 18 cm", fix: "Require the unit in every answer, and mark it as incomplete without one" },
      { problem: "Units are mixed within one problem", fix: "Check the units match before any calculating" },
    ],
    mastery_statement: "Student can solve a length word problem within 100 and label the answer with its unit.",
    ladder: [
      { name: "I can read the problem", descriptor: "Understands the situation" },
      { name: "I can draw it", descriptor: "Represents the lengths" },
      { name: "I can write the equation", descriptor: "Uses a symbol for the unknown" },
      { name: "I can label my answer", descriptor: "Includes the unit" },
    ],
  },
  {
    standard_code: "2.MD.B.6",
    verbs: [
      { word: "Represent", gloss: "numbers as lengths" },
      { word: "Show", gloss: "sums and differences as jumps" },
    ],
    concepts: ["Number line as length", "Equal intervals", "Spaces not marks"],
    vocabulary: [
      { term: "number line", definition: "a line where equal spaces show equal amounts" },
      { term: "jump", definition: "a move along the line" },
      { term: "interval", definition: "the space between two marks" },
      { term: "equally spaced", definition: "the same distance apart every time" },
    ],
    prior_skills: ["Add and subtract within 100", "Use a ruler", "Count on"],
    prior_standards: [{ code: "2.MD.B.5", text: "Use addition and subtraction to solve length word problems" }],
    future_standards: [{ code: "3.NF.A.2", text: "Understand a fraction as a number on the number line" }],
    challenges: [
      { problem: "Tick marks are counted rather than the spaces between, so every jump is out by one", fix: "Draw the jump as an arch over the space. An arch cannot sit on a mark" },
      { problem: "Intervals are drawn unevenly", fix: "Use a ruler — a number line is a length, which is the point of it being in this domain" },
    ],
    mastery_statement: "Student can represent sums and differences within 100 as jumps on a number line.",
    ladder: [
      { name: "I can find a number", descriptor: "Locates on the line" },
      { name: "I can space it evenly", descriptor: "Uses equal intervals" },
      { name: "I can jump forward", descriptor: "Shows addition" },
      { name: "I can jump back", descriptor: "Shows subtraction" },
    ],
  },
  {
    standard_code: "2.MD.C.7",
    verbs: [
      { word: "Tell", gloss: "read the time" },
      { word: "Write", gloss: "record it correctly" },
      { word: "Use", gloss: "a.m. and p.m. appropriately" },
    ],
    concepts: ["Two hands, two jobs", "Five-minute intervals", "a.m. and p.m."],
    vocabulary: [
      { term: "analog", definition: "a clock with hands" },
      { term: "digital", definition: "a clock with numbers" },
      { term: "hour hand", definition: "the short hand" },
      { term: "minute hand", definition: "the long hand" },
      { term: "quarter past", definition: "fifteen minutes after the hour" },
    ],
    prior_skills: ["Tell time to the half hour", "Count by 5s", "Read a clock face"],
    prior_standards: [{ code: "1.MD.B.3", text: "Tell and write time in hours and half-hours" }],
    future_standards: [{ code: "3.MD.A.1", text: "Tell and write time to the nearest minute and solve elapsed time problems" }],
    challenges: [
      { problem: "The minute hand is read as the hour when it points near a number", fix: "Practice with the hour hand alone first — the deck's own fix. Add the minute hand only once the hour is secure" },
      { problem: "a.m. and p.m. are guessed", fix: "Tie each to a real event in their day" },
    ],
    mastery_statement: "Student can tell and write time to five minutes and use a.m. and p.m. correctly.",
    ladder: [
      { name: "I can read the hour", descriptor: "Uses the hour hand" },
      { name: "I can count by 5s round", descriptor: "Reads minutes" },
      { name: "I can read any time", descriptor: "Combines both hands" },
      { name: "I can use a.m. and p.m.", descriptor: "Places it in the day" },
    ],
  },
  {
    standard_code: "2.MD.D.9",
    verbs: [
      { word: "Generate", gloss: "make the data by measuring" },
      { word: "Show", gloss: "it on a line plot" },
    ],
    concepts: ["Measurement data", "Line plot", "Scale including zeros"],
    vocabulary: [
      { term: "line plot", definition: "a graph where each mark is one measurement" },
      { term: "data", definition: "the numbers you collected" },
      { term: "scale", definition: "the numbers along the line" },
      { term: "horizontal", definition: "going across" },
    ],
    prior_skills: ["Measure length", "Record numbers", "Count marks"],
    prior_standards: [{ code: "2.MD.A.1", text: "Measure the length of an object using appropriate tools" }],
    future_standards: [{ code: "3.MD.B.4", text: "Generate measurement data and show it on a line plot with halves and fourths" }],
    challenges: [
      { problem: "Values with no data are omitted, distorting the shape", fix: "The scale is every whole number in the range, gaps included. A missing value is information" },
      { problem: "X marks are stacked unevenly", fix: "Squared paper, one X per square" },
    ],
    mastery_statement: "Student can measure several objects and display the data on a correctly scaled line plot.",
    ladder: [
      { name: "I can measure the objects", descriptor: "Generates data" },
      { name: "I can record the numbers", descriptor: "Organizes data" },
      { name: "I can draw the scale", descriptor: "Marks whole units including zeros" },
      { name: "I can plot evenly", descriptor: "Represents the data honestly" },
    ],
  },
  {
    standard_code: "2.MD.D.10",
    verbs: [
      { word: "Draw", gloss: "the graph" },
      { word: "Solve", gloss: "problems using it" },
    ],
    concepts: ["Bar and picture graphs", "Key and scale", "Comparison questions"],
    vocabulary: [
      { term: "picture graph", definition: "a graph using symbols" },
      { term: "bar graph", definition: "a graph using bars" },
      { term: "key", definition: "what one symbol stands for" },
      { term: "category", definition: "one of the groups being counted" },
      { term: "scale", definition: "what each step up the axis is worth" },
    ],
    prior_skills: ["Count and tally", "Read a simple graph", "Add and subtract within 100"],
    prior_standards: [{ code: "1.MD.C.4", text: "Organize, represent and interpret data with up to three categories" }],
    future_standards: [{ code: "3.MD.B.3", text: "Draw a scaled picture graph and a scaled bar graph" }],
    challenges: [
      { problem: "Bar height is read as the count without checking the scale", fix: "Read the scale aloud before any question is answered. One square is not always one" },
      { problem: "The key is drawn and then ignored", fix: "Ask a question that only works if the key is used" },
    ],
    mastery_statement: "Student can draw a bar or picture graph with a key and answer comparison questions from it.",
    ladder: [
      { name: "I can count categories", descriptor: "Organizes data" },
      { name: "I can draw the graph", descriptor: "Represents up to four categories" },
      { name: "I can use a key or scale", descriptor: "Applies the scale" },
      { name: "I can compare from it", descriptor: "Solves problems using the graph" },
    ],
  },
  {
    standard_code: "2.G.A.1",
    verbs: [
      { word: "Recognize", gloss: "name it whatever way up it is" },
      { word: "Draw", gloss: "a shape with given attributes" },
    ],
    concepts: ["Attribute over appearance", "Orientation", "Sides, angles, faces"],
    vocabulary: [
      { term: "attribute", definition: "something a shape has, like sides or angles" },
      { term: "angle", definition: "the corner where two sides meet" },
      { term: "face", definition: "a flat surface on a solid" },
      { term: "quadrilateral", definition: "any shape with four sides" },
      { term: "hexagon", definition: "a shape with six sides" },
    ],
    prior_skills: ["Name common shapes", "Count sides", "Draw a shape"],
    prior_standards: [{ code: "1.G.A.1", text: "Distinguish between defining and non-defining attributes of shapes" }],
    future_standards: [{ code: "3.G.A.1", text: "Understand that shapes in different categories may share attributes" }],
    challenges: [
      { problem: "Shapes are only recognized in their usual orientation — a triangle on its point is not a triangle", fix: "Rotate every example. Count the sides rather than looking at the outline" },
      { problem: "Quadrilateral is taken to mean square", fix: "Show four-sided shapes that look nothing alike" },
    ],
    mastery_statement: "Student can identify and draw shapes by their attributes, regardless of orientation.",
    ladder: [
      { name: "I can name common shapes", descriptor: "Recognizes typical examples" },
      { name: "I can count sides and angles", descriptor: "Uses attributes" },
      { name: "I can name it any way up", descriptor: "Ignores orientation" },
      { name: "I can draw to a spec", descriptor: "Produces given attributes" },
    ],
  },
  {
    standard_code: "2.G.A.2",
    verbs: [
      { word: "Partition", gloss: "split into equal squares" },
      { word: "Count", gloss: "using rows and columns" },
    ],
    concepts: ["Same-size squares", "Rows and columns", "Foundation for area"],
    vocabulary: [
      { term: "partition", definition: "split into parts" },
      { term: "row", definition: "squares going across" },
      { term: "column", definition: "squares going down" },
      { term: "same-size", definition: "all exactly equal" },
    ],
    prior_skills: ["Build an array", "Draw a rectangle", "Count by rows"],
    prior_standards: [{ code: "2.OA.C.4", text: "Use addition to find the total in rectangular arrays" }],
    future_standards: [{ code: "3.MD.C.6", text: "Measure areas by counting unit squares" }],
    challenges: [
      { problem: "Squares are drawn unequal, which breaks the link to area", fix: "Squared paper or a folded template. Same-size is the load-bearing word in the standard" },
      { problem: "Squares are counted one by one", fix: "Rows of, as with arrays — it is the same structure" },
    ],
    mastery_statement: "Student can partition a rectangle into same-size squares and count them using the rows.",
    ladder: [
      { name: "I can split a rectangle", descriptor: "Partitions" },
      { name: "I can make them equal", descriptor: "Uses same-size squares" },
      { name: "I can count by rows", descriptor: "Uses structure" },
      { name: "I can link it to adding", descriptor: "Connects to repeated addition" },
    ],
  },
];

const blueprintsData = [
  {
    standard_code: "2.OA.C.3",
    title: "Pair Them Up and See What Is Left",
    badge: "Grade 2",
    route_name: "Concrete-Representational-Abstract",
    route_line: "Pair the objects → Notice the leftover → Write the equation",
    success_criteria: ["Pairs objects to test", "Names odd or even with a reason", "Writes an even number as equal addends"],
    steps: [
      { name: "Retrieve Counting by 2s", minutes: 5, body: "Fast, and from different starting points.", science_tag: "retrieval" },
      { name: "Pair Real Objects", minutes: 12, body: "Cubes pushed into twos. No numerals yet. Even means everything found a partner, and that is a thing you can see.", science_tag: "dual-coding" },
      { name: "The Leftover One", minutes: 8, body: "Odd is the one with nobody. Name it from the objects, not from a rule.", science_tag: "elaboration" },
      { name: "Now the Numbers", minutes: 10, body: "Only now does the numeral appear. The rule about last digits is the conclusion, not the starting point.", science_tag: "elaboration" },
      { name: "Write It as Two Equal Parts", minutes: 12, body: "8 = 4 + 4. Try it with 9 and find it cannot be done — that failure is the proof.", science_tag: "elaboration" },
      { name: "Predict, Then Pair", minutes: 8, body: "Say odd or even first, then check by pairing. Prediction before verification.", science_tag: "metacognition" },
      { name: "Yesterday's Piles", minutes: 4, body: "Revisited without the cubes.", science_tag: "spaced" },
    ],
    ef_supports: ["Pairing frames", "Cubes or counters", "Equal-addend equation strip", "Predict-then-check sheet"],
    tech: "Counters and ten frames",
    tech_purpose: "Pairing has to be physical before it becomes a rule",
    ai_prompts: ["Generate object counts up to 20 for pairing", "Write equal-addend equations for even numbers"],
    assessment: ["Ask why, not just which — the rule alone is not the standard", "Check the equation is two equal addends", "Give a pile of objects rather than a numeral"],
    why_it_works: ["Pairing objects is what makes the rule about last digits mean something", "Failing to split 9 into equal parts is stronger evidence than being told", "Delaying the numeral prevents the rule replacing the understanding", "A pile of objects is the assessment the memorized rule cannot pass"],
  },
  {
    standard_code: "2.OA.C.4",
    title: "Three Rows of Four",
    badge: "Grade 2",
    route_name: "Concrete-Representational-Abstract",
    route_line: "Build the array → Say rows of → Write the addition",
    success_criteria: ["Builds arrays up to 5 by 5", "Counts using rows", "Writes a sum of equal addends"],
    steps: [
      { name: "Retrieve Equal Groups", minutes: 5, body: "Groups of the same size, recalled from counting work.", science_tag: "retrieval" },
      { name: "Build It", minutes: 10, body: "Counters in rows and columns. Physical before drawn.", science_tag: "dual-coding" },
      { name: "Cover All But One Row", minutes: 12, body: "What is in a row? Then how many rows? Covering is what makes the structure usable instead of decorative.", science_tag: "dual-coding" },
      { name: "Say Rows Of", minutes: 8, body: "Three rows of four, said aloud before anything is written. The words carry the structure.", science_tag: "elaboration" },
      { name: "Write the Equal Addends", minutes: 10, body: "4 + 4 + 4, not 12. The equation has to show the groups.", science_tag: "elaboration" },
      { name: "Turn It Sideways", minutes: 8, body: "Three rows of four becomes four rows of three. Same total, different equation.", science_tag: "interleaving" },
      { name: "Draw One From an Equation", minutes: 5, body: "Given 5 + 5 + 5, build the array. The direction reverses.", science_tag: "metacognition" },
    ],
    ef_supports: ["Row-covering card", "Array building mats", "Rows-of sentence frame", "Squared paper"],
    tech: "Counters and squared paper",
    tech_purpose: "Rows have to be built before they can be seen in a drawing",
    ai_prompts: ["Generate arrays up to 5 by 5 with matching equations", "Write equations for students to build"],
    assessment: ["Watch for one-by-one counting", "Check equations show equal addends", "Listen for rows of language"],
    why_it_works: ["Covering all but one row makes the structure the only available route", "Saying rows of installs the language multiplication will need", "Turning the array shows the same total two ways", "Building from an equation tests the structure rather than the counting"],
  },
  {
    standard_code: "2.NBT.A.2",
    title: "Start at 250 and Keep Going",
    badge: "Grade 2",
    route_name: "Routine and Practice",
    route_line: "Count from zero → Start somewhere else → Say what changes",
    success_criteria: ["Counts within 1000", "Skip counts by 5s, 10s and 100s", "Starts from any number"],
    steps: [
      { name: "Retrieve the Sequences", minutes: 5, body: "By 5s, 10s and 100s from zero. The easy version first.", science_tag: "retrieval" },
      { name: "Now Start at 250", minutes: 12, body: "The count that collapses. This is the deck's misconception, so it gets the most time.", science_tag: "spaced" },
      { name: "Which Digit Moves", minutes: 10, body: "Counting by tens changes the tens digit — until it does not. The rollover is where it gets interesting.", science_tag: "elaboration" },
      { name: "Chart Then No Chart", minutes: 10, body: "Hundreds chart visible, then covered. The pattern has to survive the chart going away.", science_tag: "dual-coding" },
      { name: "Count Backwards", minutes: 8, body: "By tens, from 830. Harder, and it tests the pattern rather than the recital.", science_tag: "interleaving" },
      { name: "Where Will We Land", minutes: 8, body: "Predict the tenth number before counting there.", science_tag: "metacognition" },
      { name: "Yesterday's Start Number", minutes: 4, body: "Picked up cold.", science_tag: "spaced" },
    ],
    ef_supports: ["Hundreds and thousands charts", "Start-number cards", "Which-digit-moves prompt", "Backwards counting strips"],
    tech: "Hundreds chart, then withdrawn",
    tech_purpose: "The chart is a scaffold to be removed, not the method",
    ai_prompts: ["Generate skip-count starting points that are not multiples", "Write rollover cases across hundreds"],
    assessment: ["Test from non-multiples specifically", "Check backwards counting", "Ask which digit changed"],
    why_it_works: ["Starting at a non-multiple is the exact case that separates reciting from understanding", "The rollover is where the pattern is genuinely interesting", "Removing the chart tests whether the pattern was internalized", "Counting backwards cannot be done by recital"],
  },
  {
    standard_code: "2.NBT.A.3",
    title: "Three Hundred and Forty-Two, Three Ways",
    badge: "Grade 2",
    route_name: "Multiple Representations",
    route_line: "Build it with blocks → Write it three ways → Go backwards",
    success_criteria: ["Writes numerals to 1000", "Writes number names", "Writes expanded form correctly"],
    steps: [
      { name: "Retrieve Place Value", minutes: 5, body: "Hundreds, tens, ones. Named before use.", science_tag: "retrieval" },
      { name: "Blocks Beside the Digits", minutes: 12, body: "Three hundreds, four tens, two ones, laid out next to 342. The digits are seen combining rather than queueing.", science_tag: "dual-coding" },
      { name: "The 30042 Problem", minutes: 12, body: "Shown deliberately. Is that three hundred and forty-two? Count the blocks. Concatenating is a different error from not knowing, and naming it matters.", science_tag: "elaboration" },
      { name: "Write All Three", minutes: 10, body: "Numeral, words, expanded. Same number, one row.", science_tag: "dual-coding" },
      { name: "Backwards", minutes: 10, body: "Given the expanded form, write the numeral. The reverse direction is where copying a pattern fails.", science_tag: "metacognition" },
      { name: "Missing Middle", minutes: 8, body: "305 — the zero that gets left out of expanded form.", science_tag: "interleaving" },
      { name: "Yesterday's Numbers", minutes: 4, body: "Three ways again, cold.", science_tag: "spaced" },
    ],
    ef_supports: ["Base-ten blocks", "Three-column recording sheet", "Reverse-direction cards", "Zero-in-the-middle set"],
    tech: "Base-ten blocks alongside written notation",
    tech_purpose: "The notation only means something next to the quantity",
    ai_prompts: ["Generate three-digit numbers including internal zeros", "Write expanded forms for conversion to numerals"],
    assessment: ["Check for concatenation specifically", "Test the reverse direction", "Include numbers with a zero"],
    why_it_works: ["Blocks beside the notation show composition rather than sequence", "Confronting 30042 names an error that otherwise stays invisible", "Reversing the direction defeats pattern-copying", "Internal zeros are where expanded form quietly breaks"],
  },
  {
    standard_code: "2.NBT.A.4",
    title: "Count the Digits Before You Compare",
    badge: "Grade 2",
    route_name: "Explicit Instruction",
    route_line: "Line them up → Compare the hundreds → Write the symbol",
    success_criteria: ["Compares by place value", "Uses >, = and < correctly", "Orders a set of numbers"],
    steps: [
      { name: "Retrieve Place Names", minutes: 5, body: "Hundreds, tens, ones, recalled fast.", science_tag: "retrieval" },
      { name: "Is 89 Bigger Than 132", minutes: 12, body: "Asked seriously. Some will say yes. Blocks settle it, and the error gets named rather than avoided.", science_tag: "elaboration" },
      { name: "Stack and Align", minutes: 10, body: "Written one above the other, places lined up. Alignment does most of the work.", science_tag: "dual-coding" },
      { name: "Hundreds First, and Why", minutes: 10, body: "The biggest place decides first because it is worth the most. Say the why, not just the order.", science_tag: "elaboration" },
      { name: "Only If They Tie", minutes: 10, body: "Move to tens only when the hundreds match. A rule with a condition.", science_tag: "metacognition" },
      { name: "The Open End", minutes: 8, body: "Faces the bigger number, said aloud every time.", science_tag: "dual-coding" },
      { name: "Order Four Numbers", minutes: 5, body: "Least to greatest, using the same routine.", science_tag: "interleaving" },
    ],
    ef_supports: ["Alignment grid", "Base-ten blocks", "Open-end reminder", "Ordering strips"],
    tech: "Place value grid paper",
    tech_purpose: "Misalignment is the cause, so alignment is the fix",
    ai_prompts: ["Generate comparison pairs with differing digit counts", "Write sets for ordering"],
    assessment: ["Include pairs like 89 and 132", "Check the symbol direction", "Ask why hundreds come first"],
    why_it_works: ["Asking the wrong-answer question directly surfaces who is reading digits not places", "Alignment removes the visual cause of the error", "A stated condition stops the rule being applied blindly", "Saying the open-end rule aloud each time fixes symbol reversal"],
  },
  {
    standard_code: "2.NBT.B.6",
    title: "Which Two Would You Add First",
    badge: "Grade 2",
    route_name: "Strategy Instruction",
    route_line: "Look at all four → Find the friendly pair → Then add",
    success_criteria: ["Adds up to four two-digit numbers", "Finds pairs making ten", "Explains the chosen order"],
    steps: [
      { name: "Retrieve Ten Pairs", minutes: 5, body: "Pairs that make ten, rapid fire. The tool before the task.", science_tag: "retrieval" },
      { name: "Which Two First", minutes: 12, body: "Asked before any adding. The question is the strategy — the deck's own prompt.", science_tag: "metacognition" },
      { name: "Same Numbers, Three Orders", minutes: 12, body: "One total every time. Reordering is legal, and seeing it is what makes it feel legal.", science_tag: "elaboration" },
      { name: "Circle the Friendly Pair", minutes: 10, body: "Marked on the page before computing.", science_tag: "dual-coding" },
      { name: "Race a Left-to-Right Adder", minutes: 8, body: "Same four numbers. Efficiency demonstrated rather than asserted.", science_tag: "collaborative" },
      { name: "Explain Your Order", minutes: 8, body: "Why those two first? The reasoning is the assessment.", science_tag: "metacognition" },
      { name: "Yesterday's Sets", minutes: 4, body: "Revisited cold.", science_tag: "spaced" },
    ],
    ef_supports: ["Ten-pair reference", "Circle-the-pair routine", "Three-order comparison sheet", "Order justification frame"],
    tech: "Number cards that can be rearranged",
    tech_purpose: "Reordering has to be physically easy to be tried",
    ai_prompts: ["Generate four-addend sets containing friendly pairs", "Write sets with no obvious pair"],
    assessment: ["Read the reason for the order", "Check pairs are found before adding", "Watch for strict left to right"],
    why_it_works: ["Asking which two first makes the strategy the first move rather than an afterthought", "Three orders with one total is proof that reordering is allowed", "Circling before computing separates planning from calculating", "Racing makes the efficiency argument better than telling"],
  },
  {
    standard_code: "2.NBT.B.7",
    title: "Do I Actually Need to Regroup",
    badge: "Grade 2",
    route_name: "Concrete-Representational-Abstract",
    route_line: "Look first → Decide → Then compute",
    success_criteria: ["Adds and subtracts within 1000", "Uses models or drawings", "Regroups only when needed"],
    steps: [
      { name: "Retrieve Place Value", minutes: 5, body: "What each digit is worth.", science_tag: "retrieval" },
      { name: "Sort Before Solving", minutes: 12, body: "A mixed pile: needs regrouping, does not. Sorted before anything is solved. Deciding is the skill the deck says is missing.", science_tag: "metacognition" },
      { name: "Trade With Blocks", minutes: 12, body: "Ten ones for a ten, narrated. The carried digit gets a meaning.", science_tag: "dual-coding" },
      { name: "Blocks Beside the Numbers", minutes: 12, body: "The written method next to the trade it describes.", science_tag: "dual-coding" },
      { name: "Mixed Practice", minutes: 12, body: "Unlabelled, both kinds. The default of always regrouping fails here.", science_tag: "interleaving" },
      { name: "Draw Instead of Blocks", minutes: 8, body: "Quick sketches. The standard names drawings as well as models.", science_tag: "dual-coding" },
      { name: "Yesterday's Problems", minutes: 4, body: "Revisited cold.", science_tag: "spaced" },
    ],
    ef_supports: ["Sorting mat: needs regrouping or not", "Base-ten blocks", "Sketch shorthand", "Mixed unlabelled practice"],
    tech: "Base-ten blocks and squared paper",
    tech_purpose: "The trade has to be seen before the notation means anything",
    ai_prompts: ["Generate mixed problems requiring and not requiring regrouping", "Write subtraction across a zero"],
    assessment: ["Check regrouping is not automatic", "Ask what the carried digit means", "Look for models on the page"],
    why_it_works: ["Sorting before solving makes the decision the first step", "Narrating the trade gives the carried digit a referent", "Unlabelled mixed practice is the only thing that defeats a default", "Sketching keeps the model available when blocks are not"],
  },
  {
    standard_code: "2.NBT.B.8",
    title: "Which Digit Moved",
    badge: "Grade 2",
    route_name: "Routine and Practice",
    route_line: "See it on the chart → Say which digit changes → Do it without the chart",
    success_criteria: ["Adds and subtracts 10 or 100 mentally", "Identifies the changing digit", "Works across 100 to 900"],
    steps: [
      { name: "Retrieve Skip Counting", minutes: 4, body: "By tens and hundreds, from anywhere.", science_tag: "retrieval" },
      { name: "Down a Row Is Ten More", minutes: 10, body: "On the hundreds chart, the pattern made visible before it is made mental.", science_tag: "dual-coding" },
      { name: "Which Stayed the Same", minutes: 12, body: "Asked before the answer. Two digits do not move, and noticing that is the whole method.", science_tag: "elaboration" },
      { name: "Cover the Chart", minutes: 12, body: "The scaffold withdrawn. The pattern has to survive it.", science_tag: "metacognition" },
      { name: "Hundred More, Hundred Less", minutes: 10, body: "A different digit, same idea.", science_tag: "interleaving" },
      { name: "Across the Hundred", minutes: 8, body: "290 plus 10. The case where two digits do move.", science_tag: "elaboration" },
      { name: "Ten a Day", minutes: 4, body: "A daily thirty-second round, mixed numbers.", science_tag: "spaced" },
    ],
    ef_supports: ["Hundreds chart, then covered", "Which-stayed-the-same prompt", "Rollover practice set", "Daily quick round"],
    tech: "Hundreds chart",
    tech_purpose: "The pattern is spatial before it is numerical",
    ai_prompts: ["Generate mental addition items across hundreds boundaries", "Write which-digit-changed prompts"],
    assessment: ["Test without the chart", "Include rollover cases", "Ask which digits stayed"],
    why_it_works: ["The chart makes an abstract pattern spatial, which is why it comes first", "Asking what stayed the same is the method stated as a question", "Covering the chart is the moment it becomes mental", "The rollover case stops the rule being applied blindly"],
  },
  {
    standard_code: "2.NBT.B.9",
    title: "Not What You Did, Why It Works",
    badge: "Grade 2",
    route_name: "Strategy Instruction",
    route_line: "Solve it → Say why it works → Test someone else's",
    success_criteria: ["Explains using place value", "Justifies with a model", "Critiques another method"],
    steps: [
      { name: "Retrieve a Strategy", minutes: 5, body: "One way of adding, recalled and stated.", science_tag: "retrieval" },
      { name: "First I, Then I — Banned", minutes: 10, body: "Steps are not reasons. The sentence must start this works because.", science_tag: "metacognition" },
      { name: "Show It With Blocks", minutes: 12, body: "The reason made visible. A justification you can point at.", science_tag: "dual-coding" },
      { name: "Right Answer, Broken Method", minutes: 14, body: "A method that worked this once. Will it always? The best question in the lesson.", science_tag: "elaboration" },
      { name: "Convince a Partner", minutes: 10, body: "They may disagree, and they should.", science_tag: "collaborative" },
      { name: "Find the Mistake", minutes: 10, body: "A worked example with a flaw. Say what and why.", science_tag: "elaboration" },
      { name: "Yesterday's Explanation", minutes: 4, body: "Reread and improved.", science_tag: "spaced" },
    ],
    ef_supports: ["Because sentence stem", "Banned-phrase list", "Blocks for justification", "Flawed worked examples"],
    tech: "Base-ten blocks and whiteboards",
    tech_purpose: "A justification you can point at is easier to say",
    ai_prompts: ["Write methods that give a right answer by luck", "Generate flawed worked examples for critique"],
    assessment: ["Check explanations say why, not what", "Listen for place value language", "Read critiques"],
    why_it_works: ["Banning the step words forces the explanation to change shape", "A right answer from a broken method separates answer from reasoning", "Disagreement is where justification actually gets used", "Finding someone else's mistake is easier than examining your own"],
  },
  {
    standard_code: "2.MD.A.2",
    title: "The Desk Did Not Change",
    badge: "Grade 2",
    route_name: "Concrete Practice",
    route_line: "Measure in inches → Measure in feet → Explain the two numbers",
    success_criteria: ["Measures one object in two units", "Compares the measurements", "Relates unit size to the count"],
    steps: [
      { name: "Retrieve Measuring Rules", minutes: 5, body: "Start at zero, no gaps, no overlaps.", science_tag: "retrieval" },
      { name: "Measure the Desk Twice", minutes: 12, body: "Inches then feet. Two numbers, one desk. The deck's own example, and it works.", science_tag: "dual-coding" },
      { name: "Did the Desk Change", minutes: 10, body: "No. So the number is about the unit, not the object. That sentence is the standard.", science_tag: "elaboration" },
      { name: "Hold Both Units", minutes: 10, body: "An inch and a foot in two hands. Smaller unit, more of them.", science_tag: "dual-coding" },
      { name: "Predict Before Measuring", minutes: 10, body: "More or fewer centimeters than inches? Predict, then check.", science_tag: "metacognition" },
      { name: "Metric Too", minutes: 8, body: "Centimeters and meters, same routine.", science_tag: "interleaving" },
      { name: "Which Unit Would You Use", minutes: 5, body: "For a pencil, for a corridor. Choosing sensibly.", science_tag: "elaboration" },
    ],
    ef_supports: ["Rulers in both systems", "Predict-then-measure sheet", "Two-units-in-two-hands routine", "Unit choice cards"],
    tech: "Rulers, meter sticks, tape measures",
    tech_purpose: "Both units have to be held to be compared",
    ai_prompts: ["Generate objects suitable for dual-unit measuring", "Write unit-choice scenarios"],
    assessment: ["Ask why the numbers differ", "Check predictions precede measuring", "Listen for smaller unit, more of them"],
    why_it_works: ["Measuring one unchanged object twice isolates the unit as the only variable", "Did the desk change is a question that answers itself", "Holding both units makes the inverse relationship physical", "Predicting first surfaces the misconception before measuring hides it"],
  },
  {
    standard_code: "2.MD.A.3",
    title: "About an Inch, About a Meter",
    badge: "Grade 2",
    route_name: "Concrete Practice",
    route_line: "Learn your benchmarks → Estimate against them → Check by measuring",
    success_criteria: ["Uses personal benchmarks", "Estimates in four units", "Checks by measuring"],
    steps: [
      { name: "Retrieve the Units", minutes: 4, body: "Inch, foot, centimeter, meter. Which is which.", science_tag: "retrieval" },
      { name: "Find Your Benchmarks", minutes: 12, body: "A paper clip, a thumb width, a door, a big step. Personal and memorable — a guess without a referent is not an estimate.", science_tag: "dual-coding" },
      { name: "Estimate First", minutes: 12, body: "Written down before any ruler appears. Committing makes it an estimate rather than a comment.", science_tag: "metacognition" },
      { name: "Now Measure", minutes: 10, body: "How close were you? Closeness is the score, not correctness.", science_tag: "retrieval" },
      { name: "Adjust the Benchmark", minutes: 8, body: "Consistently over? Your referent is off. Calibration.", science_tag: "metacognition" },
      { name: "Estimate in Two Units", minutes: 8, body: "The same object, both systems.", science_tag: "interleaving" },
      { name: "Yesterday's Objects", minutes: 4, body: "Re-estimated from memory.", science_tag: "spaced" },
    ],
    ef_supports: ["Personal benchmark card", "Estimate-then-measure recording sheet", "Closeness scoring", "Benchmark adjustment prompt"],
    tech: "Rulers and everyday objects",
    tech_purpose: "Benchmarks have to be things they carry with them",
    ai_prompts: ["Generate estimation objects across four units", "Write benchmark suggestions for grade 2"],
    assessment: ["Check estimates are recorded before measuring", "Look for benchmark use", "Track closeness over time"],
    why_it_works: ["A personal benchmark is the difference between an estimate and a guess", "Writing it down first stops it being adjusted after the fact", "Scoring closeness makes estimating a skill rather than a failed measurement", "Adjusting a benchmark teaches that referents can be calibrated"],
  },
  {
    standard_code: "2.MD.A.4",
    title: "How Much Longer Means Take Away",
    badge: "Grade 2",
    route_name: "Concrete Practice",
    route_line: "Line them up → See the extra bit → Subtract",
    success_criteria: ["Measures both in the same unit", "Subtracts to find the difference", "Labels the unit"],
    steps: [
      { name: "Retrieve Subtraction", minutes: 5, body: "Within 100, quick.", science_tag: "retrieval" },
      { name: "Line Them Up", minutes: 12, body: "Two strips, ends aligned. The extra bit is visible, and that is the difference.", science_tag: "dual-coding" },
      { name: "Point at the Difference", minutes: 10, body: "Not the whole of either — the sticking-out part. Then measure just that.", science_tag: "dual-coding" },
      { name: "Adding Gives Nonsense", minutes: 10, body: "Add them and see what you get. Longer than either object, which cannot be the answer.", science_tag: "elaboration" },
      { name: "How Much Longer Means", minutes: 10, body: "Anchor the phrase. Difference, subtract. The words tell you the operation.", science_tag: "metacognition" },
      { name: "Label the Unit", minutes: 8, body: "An answer without a unit is not an answer.", science_tag: "elaboration" },
      { name: "Yesterday's Pairs", minutes: 4, body: "Revisited cold.", science_tag: "spaced" },
    ],
    ef_supports: ["Alignment mat", "Strip pairs", "Phrase anchor card", "Unit label reminder"],
    tech: "Paper strips and rulers",
    tech_purpose: "The difference has to be seen before it is calculated",
    ai_prompts: ["Generate object pairs with clear length differences", "Write how-much-longer problems"],
    assessment: ["Watch for adding", "Check the unit is on the answer", "Ask which operation and why"],
    why_it_works: ["Lining the strips up makes the difference a visible object rather than a calculation", "Adding and getting nonsense is more persuasive than being told not to", "Anchoring the phrase connects the wording to the operation", "Measuring just the sticking-out part is the difference, physically"],
  },
  {
    standard_code: "2.MD.B.5",
    title: "Length Problems, Units and All",
    badge: "Grade 2",
    route_name: "Strategy Instruction",
    route_line: "Draw the lengths → Write the equation → Label the answer",
    success_criteria: ["Solves length problems within 100", "Uses a symbol for the unknown", "Labels the unit"],
    steps: [
      { name: "Retrieve the Operations", minutes: 5, body: "When do we add, when do we subtract?", science_tag: "retrieval" },
      { name: "Draw It as Strips", minutes: 12, body: "Length problems are about length, so they get drawn as lengths.", science_tag: "dual-coding" },
      { name: "Where Is the Unknown", minutes: 10, body: "Marked on the drawing with a box before any equation.", science_tag: "metacognition" },
      { name: "Write the Equation", minutes: 10, body: "With the box in it, matching the drawing.", science_tag: "elaboration" },
      { name: "Check the Units Match", minutes: 8, body: "Before calculating. Mixed units make the answer meaningless.", science_tag: "metacognition" },
      { name: "Label or It Is Not Finished", minutes: 10, body: "18 is not an answer. 18 cm is. Marked incomplete without it.", science_tag: "elaboration" },
      { name: "Yesterday's Problem", minutes: 5, body: "Revisited, units checked.", science_tag: "spaced" },
    ],
    ef_supports: ["Strip diagram template", "Unknown box", "Unit check step", "Label-or-incomplete rule"],
    tech: "Squared paper for strip diagrams",
    tech_purpose: "Drawing lengths as lengths keeps the model honest",
    ai_prompts: ["Generate length word problems within 100", "Write problems with the unknown in different positions"],
    assessment: ["Check every answer carries a unit", "Confirm the drawing matches the equation", "Vary where the unknown sits"],
    why_it_works: ["Drawing lengths as strips keeps the representation faithful to the quantity", "Marking the unknown before writing the equation makes the equation follow the situation", "Checking units before calculating catches the error early", "Refusing an unlabelled answer is what makes the unit stick"],
  },
  {
    standard_code: "2.MD.B.6",
    title: "Count the Spaces, Not the Marks",
    badge: "Grade 2",
    route_name: "Multiple Representations",
    route_line: "Draw an even line → Arch over the spaces → Read the answer",
    success_criteria: ["Uses equal intervals", "Shows sums and differences as jumps", "Counts spaces not marks"],
    steps: [
      { name: "Retrieve Number Line Basics", minutes: 5, body: "Zero on the left, equal spaces, numbers in order.", science_tag: "retrieval" },
      { name: "A Ruler Is a Number Line", minutes: 10, body: "The connection the standard is making. Both are lengths.", science_tag: "dual-coding" },
      { name: "Spaces, Not Marks", minutes: 14, body: "The off-by-one error, demonstrated. Then jumps drawn as arches — an arch sits over a space and cannot sit on a mark.", science_tag: "metacognition" },
      { name: "Jump Forward", minutes: 10, body: "Addition, drawn as arches from a start point.", science_tag: "dual-coding" },
      { name: "Jump Back", minutes: 10, body: "Subtraction, the same line the other way.", science_tag: "dual-coding" },
      { name: "Draw Your Own Line", minutes: 8, body: "With a ruler, so intervals are actually equal.", science_tag: "elaboration" },
      { name: "Yesterday's Jumps", minutes: 4, body: "Re-drawn from the equation alone.", science_tag: "spaced" },
    ],
    ef_supports: ["Pre-drawn even number lines", "Arch-drawing routine", "Ruler for line construction", "Equation-to-line cards"],
    tech: "Rulers and squared paper",
    tech_purpose: "Equal intervals need a straight edge to be equal",
    ai_prompts: ["Generate sums and differences within 100 for number line work", "Write number lines with deliberate spacing errors"],
    assessment: ["Watch for off-by-one jumps", "Check intervals are even", "Confirm arches span spaces"],
    why_it_works: ["An arch physically cannot sit on a tick mark, which is why it fixes the error", "Connecting to the ruler explains why this standard lives in measurement", "Drawing their own line with a ruler makes equal intervals a construction", "Going both directions on one line shows addition and subtraction as opposites"],
  },
  {
    standard_code: "2.MD.C.7",
    title: "The Short Hand First",
    badge: "Grade 2",
    route_name: "Explicit Instruction",
    route_line: "Read the hour → Count round by fives → Say a.m. or p.m.",
    success_criteria: ["Tells time to five minutes", "Reads analog and digital", "Uses a.m. and p.m."],
    steps: [
      { name: "Retrieve Counting by 5s", minutes: 4, body: "Round the clock face.", science_tag: "retrieval" },
      { name: "Hour Hand Alone", minutes: 12, body: "The minute hand removed entirely. Where is it pointing, roughly? The deck's fix, and it works because the confusion is between the hands.", science_tag: "dual-coding" },
      { name: "It Is Between", minutes: 10, body: "The hour hand moves too, and between four and five means it is still four.", science_tag: "elaboration" },
      { name: "Add the Minute Hand", minutes: 12, body: "Only once the hour is secure. Count by fives from the twelve.", science_tag: "dual-coding" },
      { name: "Analog to Digital", minutes: 10, body: "Both faces, same time, side by side.", science_tag: "interleaving" },
      { name: "a.m. or p.m.", minutes: 8, body: "Tied to real events — breakfast, lunch, bedtime.", science_tag: "elaboration" },
      { name: "Yesterday's Times", minutes: 4, body: "Read cold.", science_tag: "spaced" },
    ],
    ef_supports: ["Clock with a removable minute hand", "Five-minute markings", "Analog and digital pairing cards", "Daily event timeline"],
    tech: "Geared demonstration clocks",
    tech_purpose: "The hands must move together to show the hour hand drifting",
    ai_prompts: ["Generate times to the nearest five minutes", "Write a.m. and p.m. daily-event scenarios"],
    assessment: ["Check the hour is read correctly when the minute hand is near a number", "Confirm five-minute accuracy", "Ask about a.m. and p.m."],
    why_it_works: ["Removing the minute hand eliminates the source of the confusion entirely", "Noticing the hour hand drifts explains why between four and five is still four", "Adding the second hand only when the first is secure keeps the load manageable", "Anchoring a.m. and p.m. to meals makes it memorable rather than arbitrary"],
  },
  {
    standard_code: "2.MD.D.9",
    title: "A Line Plot That Tells the Truth",
    badge: "Grade 2",
    route_name: "Multiple Representations",
    route_line: "Measure everything → Draw the whole scale → Plot one X each",
    success_criteria: ["Generates measurement data", "Draws a complete scale", "Plots evenly"],
    steps: [
      { name: "Retrieve Measuring", minutes: 5, body: "Accurately, to the nearest whole unit.", science_tag: "retrieval" },
      { name: "Measure Ten Things", minutes: 12, body: "Real objects, real data. Generating is in the standard.", science_tag: "dual-coding" },
      { name: "Every Number in Range", minutes: 12, body: "Including ones nothing landed on. A gap is information, and leaving it out distorts the shape.", science_tag: "elaboration" },
      { name: "One X Per Square", minutes: 10, body: "Squared paper. Uneven stacks lie about the data.", science_tag: "dual-coding" },
      { name: "What Does the Shape Say", minutes: 10, body: "Where do most sit? Reading the plot, not just making it.", science_tag: "elaboration" },
      { name: "The Missing Value", minutes: 8, body: "Cover a gap and ask what changed. The gap was doing work.", science_tag: "metacognition" },
      { name: "New Objects, Same Plot", minutes: 5, body: "Added later in the week.", science_tag: "spaced" },
    ],
    ef_supports: ["Squared paper", "Full-scale prompt", "Measurement recording table", "Shape-reading questions"],
    tech: "Rulers and squared paper",
    tech_purpose: "Even stacking needs a grid",
    ai_prompts: ["Generate measurement data sets with internal gaps", "Write shape-reading questions for line plots"],
    assessment: ["Check zero-count values appear on the scale", "Confirm even stacking", "Ask what the shape shows"],
    why_it_works: ["Including empty values is what makes the plot honest about the distribution", "Squared paper makes even stacking automatic rather than careful", "Covering a gap shows the gap was carrying information", "Reading the shape is the point of making it"],
  },
  {
    standard_code: "2.MD.D.10",
    title: "Read the Scale Before the Bar",
    badge: "Grade 2",
    route_name: "Multiple Representations",
    route_line: "Check the key → Read the scale → Then answer",
    success_criteria: ["Draws bar and picture graphs", "Uses a key or scale", "Answers comparison questions"],
    steps: [
      { name: "Retrieve Graph Parts", minutes: 4, body: "Title, categories, scale, key.", science_tag: "retrieval" },
      { name: "The Same Bar, Two Scales", minutes: 12, body: "One graph where a square is one, one where it is five. Identical bars, different answers. The misconception dies here.", science_tag: "elaboration" },
      { name: "Scale Aloud First", minutes: 10, body: "Before any question is answered. Said, not assumed.", science_tag: "metacognition" },
      { name: "Draw Your Own", minutes: 12, body: "Four categories, with a key that is actually needed.", science_tag: "dual-coding" },
      { name: "Questions That Need the Key", minutes: 10, body: "Unanswerable without it, so it cannot be ignored.", science_tag: "elaboration" },
      { name: "How Many More", minutes: 10, body: "Compare questions, which are where the arithmetic lives.", science_tag: "interleaving" },
      { name: "Yesterday's Graph", minutes: 4, body: "New questions on the same data.", science_tag: "spaced" },
    ],
    ef_supports: ["Two-scale comparison pair", "Scale-aloud routine", "Key template", "Compare question stems"],
    tech: "Squared paper and printed graphs",
    tech_purpose: "Drawing and reading are different skills, so both appear",
    ai_prompts: ["Generate identical bar graphs with different scales", "Write comparison questions requiring the key"],
    assessment: ["Check the scale is read first", "Confirm key use", "Test how-many-more questions"],
    why_it_works: ["Identical bars with different scales makes assuming one-per-square visibly wrong", "Saying the scale aloud is a habit that survives past the lesson", "Questions that need the key make it load-bearing rather than decorative", "Compare questions are where graph reading meets arithmetic"],
  },
  {
    standard_code: "2.G.A.1",
    title: "Still a Triangle Upside Down",
    badge: "Grade 2",
    route_name: "Explicit Instruction",
    route_line: "Count the sides → Count the angles → Name it, any way up",
    success_criteria: ["Identifies shapes by attributes", "Recognizes shapes in any orientation", "Draws to a specification"],
    steps: [
      { name: "Retrieve Shape Names", minutes: 5, body: "Triangle, quadrilateral, pentagon, hexagon, cube.", science_tag: "retrieval" },
      { name: "Spin It", minutes: 12, body: "The same triangle, rotated onto a vertex. Still a triangle? Count the sides. Orientation is the deck's misconception, so it gets attacked directly.", science_tag: "dual-coding" },
      { name: "Count, Do Not Look", minutes: 10, body: "The outline lies, the count does not.", science_tag: "metacognition" },
      { name: "Four Sides, Four Ways", minutes: 12, body: "A square, a rhombus, a trapezoid, a long thin one. All quadrilaterals, none alike.", science_tag: "elaboration" },
      { name: "Draw to a Spec", minutes: 10, body: "Five sides, given nothing else. Many right answers, which is the point.", science_tag: "elaboration" },
      { name: "Faces on Solids", minutes: 8, body: "A cube has six equal faces. Attributes work in three dimensions too.", science_tag: "interleaving" },
      { name: "Yesterday's Shapes", minutes: 4, body: "Rotated and renamed.", science_tag: "spaced" },
    ],
    ef_supports: ["Rotatable shape cards", "Count-do-not-look prompt", "Odd-quadrilateral set", "Draw-to-spec cards"],
    tech: "Cut-out shapes and solids",
    tech_purpose: "Shapes have to be turned to defeat the orientation habit",
    ai_prompts: ["Generate shapes in unusual orientations", "Write attribute specifications with multiple valid answers"],
    assessment: ["Present shapes rotated", "Include non-square quadrilaterals", "Check drawings meet the spec"],
    why_it_works: ["Rotating the example attacks the orientation habit directly rather than avoiding it", "Counting sides is a rule that survives rotation; recognizing an outline is not", "Four unlike quadrilaterals breaks the square equals quadrilateral assumption", "An open specification shows a category has many members"],
  },
  {
    standard_code: "2.G.A.2",
    title: "Equal Squares, or It Does Not Work",
    badge: "Grade 2",
    route_name: "Concrete-Representational-Abstract",
    route_line: "Fold or grid it → Check they are equal → Count by rows",
    success_criteria: ["Partitions into same-size squares", "Counts using rows and columns", "Connects to repeated addition"],
    steps: [
      { name: "Retrieve Arrays", minutes: 5, body: "Rows of, from the earlier work. Same structure.", science_tag: "retrieval" },
      { name: "Fold It", minutes: 10, body: "Paper folded into equal parts. Folding cannot produce unequal squares, which is why it comes first.", science_tag: "dual-coding" },
      { name: "Unequal Does Not Count", minutes: 12, body: "A rectangle split into squares of different sizes. What goes wrong? Same-size is the load-bearing word.", science_tag: "elaboration" },
      { name: "Count by Rows", minutes: 10, body: "Not one by one. The same move as the array work.", science_tag: "dual-coding" },
      { name: "Write the Addition", minutes: 10, body: "4 + 4 + 4, connecting it back to 2.OA.C.4.", science_tag: "interleaving" },
      { name: "Draw Without a Grid", minutes: 8, body: "Freehand, then checked with a ruler. Harder, and it tests the idea.", science_tag: "metacognition" },
      { name: "Yesterday's Rectangle", minutes: 5, body: "Re-partitioned differently.", science_tag: "spaced" },
    ],
    ef_supports: ["Folding templates", "Squared paper", "Unequal-square counterexample", "Rows-of language"],
    tech: "Paper for folding and squared paper",
    tech_purpose: "Folding guarantees equal parts in a way drawing does not",
    ai_prompts: ["Generate rectangles for partitioning at various dimensions", "Write unequal-partition counterexamples"],
    assessment: ["Check squares are genuinely equal", "Watch for one-by-one counting", "Confirm the addition sentence"],
    why_it_works: ["Folding makes equal parts a physical guarantee rather than an intention", "A counterexample with unequal squares shows why the word same-size is there", "Counting by rows carries the array structure forward", "Writing the addition connects geometry to the multiplication foundation"],
  },
];

seedStandardsBatch({
  label: "Batch 11 — grade 2 mathematics",
  standardsData,
  unpacksData,
  blueprintsData,
});
