// @ts-nocheck
/**
 * Batch 6: 20 more drafted standards, taking the library past 120.
 *
 * Completes several progressions that were only partly covered — opinion
 * writing from grade 1, the central idea strand through grade 8, informative
 * writing at grades 4 and 8 — and opens three more maths corners: money,
 * sampling, and geometric transformations.
 *
 *   bun run scripts/seed-standards-batch-6.ts
 */
import { seedStandardsBatch } from "./lib/seed-standards-batch";

const standardsData = [
  // ─── ELA ────────────────────────────────────────────────────────────────
  {
    code: "RF.K.2",
    name: "Hear the sounds inside spoken words",
    plain_reading:
      "Demonstrate understanding of spoken words, syllables, and sounds, including recognising rhyme, counting syllables, and isolating the initial sound in a word.",
    learning_target: "I can hear rhymes, clap the beats in a word, and say its first sound.",
    skills: ["Phonological Awareness", "Rhyme", "Syllables"],
    science_tags: ["retrieval", "collaborative"],
    match_keys: ["rhyming", "syllables", "initial sound", "phonological awareness", "onset rime"],
  },
  {
    code: "W.1.1",
    name: "Write what you think about a book",
    plain_reading:
      "Write opinion pieces in which they introduce the topic or name the book they are writing about, state an opinion, supply a reason for the opinion, and provide some sense of closure.",
    learning_target: "I can name a book, say what I think of it, and give one reason.",
    skills: ["Opinion Writing", "Reasons", "Closure"],
    science_tags: ["elaboration", "spaced"],
    match_keys: ["opinion writing grade 1", "state an opinion", "reason", "book review", "closure"],
  },
  {
    code: "L.2.4",
    name: "Work out new words in grade 2 texts",
    plain_reading:
      "Determine or clarify the meaning of unknown and multiple-meaning words and phrases based on grade 2 reading and content, using sentence context, known prefixes, compound words and glossaries.",
    learning_target: "I can use clues in the sentence and the parts of a word to work out what it means.",
    skills: ["Vocabulary", "Context Clues", "Compound Words"],
    science_tags: ["elaboration", "interleaving"],
    match_keys: ["context clues", "prefixes", "compound words", "glossary", "multiple meaning words"],
  },
  {
    code: "RL.3.2",
    name: "Find the lesson in a story",
    plain_reading:
      "Recount stories, including fables, folktales and myths from diverse cultures, determine the central message, lesson or moral, and explain how it is conveyed through key details in the text.",
    learning_target: "I can retell a story and say what it teaches, using details that show it.",
    skills: ["Central Message", "Retelling", "Folktales"],
    science_tags: ["elaboration", "dual-coding"],
    match_keys: ["central message", "moral", "lesson", "fable", "folktale", "recount"],
  },
  {
    code: "W.4.2",
    name: "Write to explain a topic clearly",
    plain_reading:
      "Write informative or explanatory texts to examine a topic and convey ideas and information clearly, grouping related information and using facts, definitions and concrete details.",
    learning_target: "I can explain a topic by grouping facts that belong together.",
    skills: ["Informative Writing", "Grouping Information", "Concrete Detail"],
    science_tags: ["elaboration", "dual-coding"],
    match_keys: ["informative writing", "explanatory", "group related information", "facts and definitions"],
  },
  {
    code: "RI.5.5",
    name: "Compare how two texts are organized",
    plain_reading:
      "Compare and contrast the overall structure of events, ideas, concepts or information in two or more texts.",
    learning_target: "I can say how two texts on the same topic are put together differently.",
    skills: ["Text Structure", "Comparison", "Nonfiction Analysis"],
    science_tags: ["dual-coding", "interleaving"],
    match_keys: ["compare structure", "two texts", "chronology", "compare contrast", "problem solution"],
  },
  {
    code: "SL.6.1",
    name: "Come prepared and discuss with evidence",
    plain_reading:
      "Engage effectively in a range of collaborative discussions on grade 6 topics, texts and issues, coming to discussions prepared and drawing on evidence to explore ideas under discussion.",
    learning_target: "I can arrive ready with evidence and use it while we talk.",
    skills: ["Discussion", "Preparation", "Evidence-Based Talk"],
    science_tags: ["collaborative", "elaboration"],
    match_keys: ["collaborative discussion", "come prepared", "evidence", "grade 6 speaking", "norms"],
  },
  {
    code: "RL.7.3",
    name: "Analyze how story elements shape each other",
    plain_reading:
      "Analyze how particular elements of a story or drama interact, including how setting shapes the characters or plot.",
    learning_target: "I can explain how the setting changes who the characters become.",
    skills: ["Story Elements", "Interaction", "Literary Analysis"],
    science_tags: ["elaboration", "dual-coding"],
    match_keys: ["setting shapes character", "story elements interact", "plot", "literary analysis"],
  },
  {
    code: "RI.8.2",
    name: "Trace a central idea and its supporting ideas",
    plain_reading:
      "Determine a central idea of a text and analyze its development over the course of the text, including its relationship to supporting ideas, and provide an objective summary.",
    learning_target: "I can follow a central idea through a text and show what holds it up.",
    skills: ["Central Idea", "Development", "Objective Summary"],
    science_tags: ["elaboration", "dual-coding"],
    match_keys: ["central idea", "development", "supporting ideas", "objective summary", "analyze"],
  },
  {
    code: "W.8.2",
    name: "Write an explanation that analyzes",
    plain_reading:
      "Write informative or explanatory texts to examine a topic and convey ideas, concepts and information through the selection, organization and analysis of relevant content.",
    learning_target: "I can explain a topic by choosing what matters and showing how it connects.",
    skills: ["Informative Writing", "Analysis", "Organization"],
    science_tags: ["elaboration", "interleaving"],
    match_keys: ["informative writing", "explanatory", "analysis", "selection", "organization", "transitions"],
  },

  // ─── Mathematics ────────────────────────────────────────────────────────
  {
    code: "K.MD.A.2",
    name: "Compare two things directly",
    plain_reading:
      "Directly compare two objects with a measurable attribute in common, to see which object has more of or less of the attribute, and describe the difference.",
    learning_target: "I can line two things up and say which is longer or heavier.",
    skills: ["Comparison", "Measurable Attributes", "Measurement Language"],
    science_tags: ["dual-coding", "collaborative"],
    match_keys: ["compare length", "longer shorter", "heavier lighter", "measurable attribute", "direct comparison"],
  },
  {
    code: "1.NBT.C.4",
    name: "Add within 100 using place value",
    plain_reading:
      "Add within 100, including a two-digit number and a one-digit number and a two-digit number and a multiple of ten, using concrete models, drawings and strategies based on place value.",
    learning_target: "I can add a small number or a whole ten to a two-digit number.",
    skills: ["Two-Digit Addition", "Place Value", "Composing a Ten"],
    science_tags: ["dual-coding", "interleaving"],
    match_keys: ["add within 100", "two digit plus one digit", "multiples of ten", "place value", "compose a ten"],
  },
  {
    code: "2.MD.C.8",
    name: "Solve money problems",
    plain_reading:
      "Solve word problems involving dollar bills, quarters, dimes, nickels and pennies, using dollar and cent symbols appropriately.",
    learning_target: "I can work out how much money I have and how much change I get.",
    skills: ["Money", "Coin Values", "Word Problems"],
    science_tags: ["dual-coding", "retrieval"],
    match_keys: ["money", "coins", "quarters dimes nickels", "change", "dollars and cents"],
  },
  {
    code: "3.NBT.A.2",
    name: "Add and subtract within 1000",
    plain_reading:
      "Fluently add and subtract within 1000 using strategies and algorithms based on place value, properties of operations, and the relationship between addition and subtraction.",
    learning_target: "I can add and subtract three-digit numbers and know when to regroup.",
    skills: ["Three-Digit Computation", "Regrouping", "Fluency"],
    science_tags: ["retrieval", "interleaving"],
    match_keys: ["add within 1000", "subtract within 1000", "regrouping", "three digit", "standard algorithm"],
  },
  {
    code: "4.MD.A.3",
    name: "Use area and perimeter formulas",
    plain_reading:
      "Apply the area and perimeter formulas for rectangles in real world and mathematical problems, including finding an unknown side length from a known area or perimeter.",
    learning_target: "I can find area or perimeter, and work backwards to a missing side.",
    skills: ["Area", "Perimeter", "Inverse Reasoning"],
    science_tags: ["dual-coding", "interleaving"],
    match_keys: ["area formula", "perimeter", "unknown side length", "rectangles", "real world problems"],
  },
  {
    code: "5.OA.A.1",
    name: "Use brackets and evaluate in order",
    plain_reading:
      "Use parentheses, brackets or braces in numerical expressions, and evaluate expressions with these symbols.",
    learning_target: "I can work out an expression in the right order, brackets first.",
    skills: ["Order of Operations", "Grouping Symbols", "Numerical Expressions"],
    science_tags: ["retrieval", "interleaving"],
    match_keys: ["order of operations", "parentheses", "brackets", "evaluate expressions", "grouping symbols"],
  },
  {
    code: "6.RP.A.1",
    name: "Understand what a ratio is",
    plain_reading:
      "Understand the concept of a ratio and use ratio language to describe a ratio relationship between two quantities.",
    learning_target: "I can describe a relationship between two amounts using ratio language.",
    skills: ["Ratios", "Ratio Language", "Part-to-Part and Part-to-Whole"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["ratio", "for every", "to", "part to part", "part to whole", "ratio language"],
  },
  {
    code: "7.SP.A.1",
    name: "Use a sample to learn about a population",
    plain_reading:
      "Understand that statistics can be used to gain information about a population by examining a sample, and that generalizations are valid only if the sample is representative.",
    learning_target: "I can tell whether a sample is fair enough to say something about everyone.",
    skills: ["Sampling", "Representativeness", "Statistical Inference"],
    science_tags: ["elaboration", "collaborative"],
    match_keys: ["sample", "population", "representative", "random sampling", "bias", "generalization"],
  },
  {
    code: "8.G.A.1",
    name: "Discover what transformations preserve",
    plain_reading:
      "Verify experimentally the properties of rotations, reflections and translations, including that lines are taken to lines, and that lengths and angle measures are preserved.",
    learning_target: "I can slide, flip and turn a shape and say what stays the same.",
    skills: ["Transformations", "Congruence", "Geometric Properties"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["rotation", "reflection", "translation", "transformations", "congruence", "preserved"],
  },
  {
    code: "8.F.B.4",
    name: "Build a function from a situation",
    plain_reading:
      "Construct a function to model a linear relationship between two quantities, determining the rate of change and initial value from a description, a table, or two points.",
    learning_target: "I can write the rule for a situation and say what the numbers mean.",
    skills: ["Linear Functions", "Rate of Change", "Initial Value"],
    science_tags: ["interleaving", "elaboration"],
    match_keys: ["linear function", "rate of change", "initial value", "y intercept", "slope", "model"],
  },
];

const unpacksData = [
  {
    standard_code: "RF.K.2",
    verbs: [
      { word: "Recognize", gloss: "notice when words rhyme" },
      { word: "Count", gloss: "how many beats in a word" },
      { word: "Isolate", gloss: "pull out one sound on its own" },
    ],
    concepts: ["Rhyme", "Syllables", "Initial sounds"],
    vocabulary: [
      { term: "rhyme", definition: "words that end with the same sound" },
      { term: "syllable", definition: "a beat in a word" },
      { term: "first sound", definition: "the sound a word starts with" },
      { term: "sound", definition: "what you hear, not what you see" },
    ],
    prior_skills: ["Listen to rhyming songs", "Repeat a spoken word", "Join in with chants"],
    prior_standards: [{ code: "PK.RF.2", text: "Engage with rhymes and songs" }],
    future_standards: [{ code: "RF.1.2", text: "Blend and segment the sounds in spoken words" }],
    challenges: [
      { problem: "Rhyme is confused with starting the same", fix: "Sort word pairs into 'starts the same' and 'ends the same'" },
      { problem: "Syllables are counted by letters", fix: "Clap or use a chin drop, eyes closed" },
    ],
    mastery_statement: "Student can recognize rhyme, count syllables, and isolate the first sound in a spoken word.",
    ladder: [
      { name: "I can hear when words rhyme", descriptor: "Recognizes rhyming pairs" },
      { name: "I can make a rhyme", descriptor: "Produces a rhyming word" },
      { name: "I can clap the beats", descriptor: "Counts syllables accurately" },
      { name: "I can say the first sound", descriptor: "Isolates the initial phoneme" },
    ],
  },
  {
    standard_code: "W.1.1",
    verbs: [
      { word: "Introduce", gloss: "name what you are writing about" },
      { word: "State", gloss: "say what you think" },
      { word: "Supply", gloss: "give a reason" },
    ],
    concepts: ["Opinion", "Reason", "Closure"],
    vocabulary: [
      { term: "opinion", definition: "what you think about something" },
      { term: "reason", definition: "why you think it" },
      { term: "because", definition: "the word that joins what you think to why" },
      { term: "closing", definition: "the last sentence that finishes it off" },
    ],
    prior_skills: ["Say what you like and why", "Write a complete sentence", "Use capital letters and full stops"],
    prior_standards: [{ code: "W.K.1", text: "Use drawing and writing to state an opinion about a book" }],
    future_standards: [{ code: "W.2.1", text: "Write opinion pieces with reasons and a conclusion" }],
    challenges: [
      { problem: "The book is never named", fix: "Require the title in the first sentence" },
      { problem: "The reason is 'because I like it'", fix: "Ask what happened in the book that made them like it" },
    ],
    mastery_statement: "Student can name a book, state an opinion about it, give a reason, and close the piece.",
    ladder: [
      { name: "I can name the book", descriptor: "Introduces the topic" },
      { name: "I can say what I think", descriptor: "States an opinion" },
      { name: "I can give a reason", descriptor: "Supplies support" },
      { name: "I can finish it properly", descriptor: "Provides closure" },
    ],
  },
  {
    standard_code: "L.2.4",
    verbs: [
      { word: "Determine", gloss: "work out what a word means" },
      { word: "Use", gloss: "apply a strategy that fits" },
    ],
    concepts: ["Context clues", "Prefixes", "Compound words"],
    vocabulary: [
      { term: "prefix", definition: "a word part at the front that changes the meaning" },
      { term: "compound word", definition: "two words joined to make a new one" },
      { term: "glossary", definition: "a word list at the back of a book" },
      { term: "context", definition: "the words around a word that give hints" },
    ],
    prior_skills: ["Use sentence context", "Recognize common endings", "Read grade 2 text"],
    prior_standards: [{ code: "L.1.4", text: "Determine the meaning of unknown words using grade 1 strategies" }],
    future_standards: [{ code: "L.3.4", text: "Determine the meaning of unknown words using grade 3 strategies" }],
    challenges: [
      { problem: "Compound words are guessed rather than split", fix: "Cover one half at a time and read each part" },
      { problem: "One strategy is used for every word", fix: "Mix words needing different approaches" },
    ],
    mastery_statement: "Student can work out an unfamiliar word using context, prefixes, compound structure or a glossary.",
    ladder: [
      { name: "I can notice a word I do not know", descriptor: "Flags unfamiliar words" },
      { name: "I can use the sentence", descriptor: "Applies context" },
      { name: "I can split a compound word", descriptor: "Reads both parts" },
      { name: "I can pick the strategy that fits", descriptor: "Chooses among approaches" },
    ],
  },
  {
    standard_code: "RL.3.2",
    verbs: [
      { word: "Recount", gloss: "retell the story accurately" },
      { word: "Determine", gloss: "work out the lesson" },
      { word: "Explain", gloss: "show which details convey it" },
    ],
    concepts: ["Central message", "Key details", "Traditional tales"],
    vocabulary: [
      { term: "moral", definition: "the lesson a story teaches" },
      { term: "fable", definition: "a short story with animals that teaches a lesson" },
      { term: "folktale", definition: "an old story passed down by telling" },
      { term: "central message", definition: "the main thing the story wants you to understand" },
    ],
    prior_skills: ["Retell a story in order", "Describe characters and events", "Identify a problem and solution"],
    prior_standards: [{ code: "RL.2.2", text: "Recount stories and determine their central message" }],
    future_standards: [{ code: "RL.4.2", text: "Determine a theme from details in the text" }],
    challenges: [
      { problem: "The plot is given as the lesson", fix: "Ask what it teaches about how to live, not what happened" },
      { problem: "A moral is stated with no supporting detail", fix: "Require the moment in the story that shows it" },
    ],
    mastery_statement: "Student can retell a story, state its central message, and cite the details that convey it.",
    ladder: [
      { name: "I can retell the story", descriptor: "Recounts accurately" },
      { name: "I can find the turning point", descriptor: "Identifies the key moment" },
      { name: "I can say what it teaches", descriptor: "States the message" },
      { name: "I can show the detail that proves it", descriptor: "Links message to text" },
    ],
  },
  {
    standard_code: "W.4.2",
    verbs: [
      { word: "Examine", gloss: "look closely at a topic" },
      { word: "Group", gloss: "put related information together" },
      { word: "Convey", gloss: "get the information across clearly" },
    ],
    concepts: ["Grouping information", "Facts and definitions", "Concrete detail"],
    vocabulary: [
      { term: "informative", definition: "writing that explains rather than argues" },
      { term: "definition", definition: "a sentence saying what something is" },
      { term: "concrete detail", definition: "a specific fact, number or example" },
      { term: "category", definition: "a group of related facts" },
    ],
    prior_skills: ["Write a paragraph with a topic sentence", "Take notes from a text", "Identify related facts"],
    prior_standards: [{ code: "W.3.2", text: "Write informative texts to examine a topic" }],
    future_standards: [{ code: "W.5.2", text: "Write informative texts with logically grouped information" }],
    challenges: [
      { problem: "Facts are listed in the order they were found", fix: "Sort note cards into piles before drafting a word" },
      { problem: "Everything stays general", fix: "Require one number or named example per paragraph" },
    ],
    mastery_statement: "Student can write an informative text that groups related information and supports it with concrete detail.",
    ladder: [
      { name: "I can gather facts", descriptor: "Collects information" },
      { name: "I can group related ones", descriptor: "Sorts into categories" },
      { name: "I can add a definition", descriptor: "Explains key terms" },
      { name: "I can use a concrete detail", descriptor: "Names specifics" },
    ],
  },
  {
    standard_code: "RI.5.5",
    verbs: [
      { word: "Compare", gloss: "find what is the same" },
      { word: "Contrast", gloss: "find what differs" },
    ],
    concepts: ["Text structure", "Cross-text comparison", "Author's choices"],
    vocabulary: [
      { term: "structure", definition: "how a text is organized" },
      { term: "compare", definition: "look for what is the same" },
      { term: "contrast", definition: "look for what is different" },
      { term: "chronology", definition: "told in time order" },
    ],
    prior_skills: ["Identify a text's structure", "Find signal words", "Summarize a text"],
    prior_standards: [{ code: "RI.4.5", text: "Describe the overall structure of a text" }],
    future_standards: [{ code: "RI.6.5", text: "Analyze how a part fits into the overall structure" }],
    challenges: [
      { problem: "Content is compared instead of structure", fix: "Ban topic words from the comparison" },
      { problem: "Both texts are called 'informational' and left there", fix: "Require the specific pattern, with signal words" },
    ],
    mastery_statement: "Student can compare how two texts on a topic are organized and cite the evidence for each structure.",
    ladder: [
      { name: "I can name one text's structure", descriptor: "Identifies a single pattern" },
      { name: "I can name both", descriptor: "Handles two texts" },
      { name: "I can say how they differ", descriptor: "Contrasts the structures" },
      { name: "I can say why an author chose one", descriptor: "Reasons about purpose" },
    ],
  },
  {
    standard_code: "SL.6.1",
    verbs: [
      { word: "Prepare", gloss: "arrive with something to say" },
      { word: "Draw on", gloss: "use evidence while talking" },
      { word: "Engage", gloss: "take an active part" },
    ],
    concepts: ["Preparation", "Evidence in discussion", "Collaborative norms"],
    vocabulary: [
      { term: "prepared", definition: "having read and thought about it beforehand" },
      { term: "evidence", definition: "something from the text that supports your point" },
      { term: "elaborate", definition: "say more about an idea" },
      { term: "norm", definition: "an agreement about how the group talks" },
    ],
    prior_skills: ["Build on others' ideas", "Cite text evidence in writing", "Follow discussion norms"],
    prior_standards: [{ code: "SL.5.1", text: "Engage effectively in collaborative discussions" }],
    future_standards: [{ code: "SL.7.1", text: "Engage in discussions, posing and responding to questions" }],
    challenges: [
      { problem: "Students arrive with opinions but no evidence", fix: "Require two marked passages as a ticket in" },
      { problem: "Evidence is read out with no comment", fix: "Require a sentence saying why it matters" },
    ],
    mastery_statement: "Student can come to a discussion prepared and use text evidence to develop ideas under discussion.",
    ladder: [
      { name: "I can join in", descriptor: "Contributes to discussion" },
      { name: "I can come prepared", descriptor: "Arrives with marked evidence" },
      { name: "I can quote while talking", descriptor: "Draws on the text aloud" },
      { name: "I can say why it matters", descriptor: "Elaborates on evidence" },
    ],
  },
  {
    standard_code: "RL.7.3",
    verbs: [
      { word: "Analyze", gloss: "examine how parts affect each other" },
      { word: "Interact", gloss: "how one element shapes another" },
    ],
    concepts: ["Setting and character", "Plot causation", "Element interaction"],
    vocabulary: [
      { term: "element", definition: "one of the parts of a story, like setting or character" },
      { term: "interact", definition: "affect each other" },
      { term: "shape", definition: "influence what something becomes" },
      { term: "circumstance", definition: "the situation a character is in" },
    ],
    prior_skills: ["Identify setting and character", "Track character change", "Cite evidence"],
    prior_standards: [{ code: "RL.6.3", text: "Describe how characters respond and change" }],
    future_standards: [{ code: "RL.8.3", text: "Analyze how dialogue or incidents propel action and reveal character" }],
    challenges: [
      { problem: "Elements are described separately, never connected", fix: "Require the sentence to contain 'because the setting is…'" },
      { problem: "Setting is treated as scenery", fix: "Ask what would change if the story moved somewhere else" },
    ],
    mastery_statement: "Student can analyze how one story element shapes another, with evidence from the text.",
    ladder: [
      { name: "I can describe the setting", descriptor: "Identifies place and time" },
      { name: "I can describe the characters", descriptor: "Names traits" },
      { name: "I can connect the two", descriptor: "Shows setting shaping character" },
      { name: "I can test it by changing the setting", descriptor: "Reasons about dependence" },
    ],
  },
  {
    standard_code: "RI.8.2",
    verbs: [
      { word: "Determine", gloss: "identify the central idea" },
      { word: "Analyze", gloss: "trace how it is built" },
      { word: "Summarize", gloss: "restate without opinion" },
    ],
    concepts: ["Central idea", "Supporting ideas", "Development"],
    vocabulary: [
      { term: "central idea", definition: "the main point running through the whole text" },
      { term: "supporting idea", definition: "a smaller idea holding up the central one" },
      { term: "development", definition: "how an idea is built across a text" },
      { term: "objective", definition: "sticking to the text without your own view" },
    ],
    prior_skills: ["Determine central ideas", "Trace development", "Write objective summaries"],
    prior_standards: [{ code: "RI.7.2", text: "Determine two or more central ideas and analyze their development" }],
    future_standards: [{ code: "RI.9-10.2", text: "Analyze the development of a central idea over the course of a text" }],
    challenges: [
      { problem: "Supporting ideas are listed as unrelated facts", fix: "Draw arrows from each up to the central idea" },
      { problem: "Development means 'it is mentioned again'", fix: "Require what changes between first and last mention" },
    ],
    mastery_statement: "Student can trace a central idea's development and show how supporting ideas hold it up.",
    ladder: [
      { name: "I can state the central idea", descriptor: "Identifies the main point" },
      { name: "I can list the supporting ideas", descriptor: "Finds the smaller ideas" },
      { name: "I can show how they connect", descriptor: "Links support to center" },
      { name: "I can trace it start to finish", descriptor: "Analyzes development" },
    ],
  },
  {
    standard_code: "W.8.2",
    verbs: [
      { word: "Select", gloss: "choose what is relevant" },
      { word: "Organize", gloss: "arrange it so it builds" },
      { word: "Analyze", gloss: "show how the content connects" },
    ],
    concepts: ["Selection", "Organization", "Analysis versus listing"],
    vocabulary: [
      { term: "relevant", definition: "actually connected to the point being made" },
      { term: "analysis", definition: "explaining how and why, not just what" },
      { term: "transition", definition: "a phrase connecting one idea to the next" },
      { term: "concept", definition: "an idea the topic depends on" },
    ],
    prior_skills: ["Write informative texts", "Group related information", "Use transitions"],
    prior_standards: [{ code: "W.7.2", text: "Write informative texts with relevant, well-organized content" }],
    future_standards: [{ code: "W.9-10.2", text: "Write informative texts examining complex ideas" }],
    challenges: [
      { problem: "Facts are listed without connection", fix: "Require a sentence linking each paragraph to the last" },
      { problem: "Everything researched is included", fix: "Force a cut — half the notes go before drafting" },
    ],
    mastery_statement: "Student can write an informative text that selects relevant content, organizes it, and analyzes how it connects.",
    ladder: [
      { name: "I can gather information", descriptor: "Researches a topic" },
      { name: "I can cut what does not fit", descriptor: "Selects relevant content" },
      { name: "I can organize it", descriptor: "Arranges logically" },
      { name: "I can show how it connects", descriptor: "Analyzes rather than lists" },
    ],
  },
  {
    standard_code: "K.MD.A.2",
    verbs: [
      { word: "Compare", gloss: "put two things side by side" },
      { word: "Describe", gloss: "say which has more" },
    ],
    concepts: ["Measurable attributes", "Direct comparison", "Comparison language"],
    vocabulary: [
      { term: "longer", definition: "more length than the other" },
      { term: "shorter", definition: "less length than the other" },
      { term: "heavier", definition: "weighs more" },
      { term: "compare", definition: "look at two things to see how they differ" },
    ],
    prior_skills: ["Sort objects", "Notice size differences", "Use bigger and smaller"],
    prior_standards: [{ code: "K.MD.A.1", text: "Describe measurable attributes of objects" }],
    future_standards: [{ code: "1.MD.A.1", text: "Order three objects by length" }],
    challenges: [
      { problem: "Objects are compared without lining up the ends", fix: "Always start both at the same line" },
      { problem: "Bigger is used for every attribute", fix: "Name the attribute — longer, heavier, taller" },
    ],
    mastery_statement: "Student can directly compare two objects on a shared attribute and describe the difference.",
    ladder: [
      { name: "I can say which is bigger", descriptor: "Notices a difference" },
      { name: "I can line them up first", descriptor: "Compares from a common start" },
      { name: "I can name the attribute", descriptor: "Says longer, not just bigger" },
      { name: "I can describe the difference", descriptor: "Uses comparison language" },
    ],
  },
  {
    standard_code: "1.NBT.C.4",
    verbs: [
      { word: "Add", gloss: "combine two numbers" },
      { word: "Compose", gloss: "make a new ten when ones fill up" },
    ],
    concepts: ["Adding tens", "Composing a ten", "Place value strategies"],
    vocabulary: [
      { term: "ten", definition: "a bundle of ten ones" },
      { term: "one", definition: "a single unit" },
      { term: "compose", definition: "make a ten from ten ones" },
      { term: "multiple of ten", definition: "10, 20, 30 and so on" },
    ],
    prior_skills: ["Understand two-digit place value", "Add within 20", "Count on by tens"],
    prior_standards: [{ code: "1.NBT.B.2", text: "Understand two-digit place value" }],
    future_standards: [{ code: "2.NBT.B.5", text: "Fluently add and subtract within 100" }],
    challenges: [
      { problem: "Tens are added to ones — 34 + 20 becomes 36", fix: "Build both numbers with blocks before adding" },
      { problem: "Ten ones are left uncomposed", fix: "Trade physically the moment the tenth one appears" },
    ],
    mastery_statement: "Student can add within 100 using place value, composing a ten when the ones fill up.",
    ladder: [
      { name: "I can add a one-digit number", descriptor: "No composing needed" },
      { name: "I can add a multiple of ten", descriptor: "Adds tens to tens" },
      { name: "I can make a new ten", descriptor: "Composes when ones exceed nine" },
      { name: "I can explain what I traded", descriptor: "Articulates the regrouping" },
    ],
  },
  {
    standard_code: "2.MD.C.8",
    verbs: [
      { word: "Solve", gloss: "work out the money problem" },
      { word: "Use", gloss: "write the symbols correctly" },
    ],
    concepts: ["Coin values", "Counting on", "Money notation"],
    vocabulary: [
      { term: "quarter", definition: "a coin worth 25 cents" },
      { term: "dime", definition: "a coin worth 10 cents" },
      { term: "nickel", definition: "a coin worth 5 cents" },
      { term: "change", definition: "the money you get back" },
    ],
    prior_skills: ["Skip count by 5s and 10s", "Add within 100", "Recognize coins"],
    prior_standards: [{ code: "2.NBT.B.5", text: "Fluently add and subtract within 100" }],
    future_standards: [{ code: "4.MD.A.2", text: "Solve word problems involving money and measurement" }],
    challenges: [
      { problem: "Coins are counted by how many, not what they are worth", fix: "Label each coin with its value before counting" },
      { problem: "Cent and dollar symbols are mixed", fix: "Sort amounts into the two notations" },
    ],
    mastery_statement: "Student can solve money problems by counting mixed coins and using dollar and cent symbols correctly.",
    ladder: [
      { name: "I can name the coins", descriptor: "Recognizes each" },
      { name: "I can say what each is worth", descriptor: "Knows values" },
      { name: "I can count a mixed handful", descriptor: "Starts with the largest" },
      { name: "I can work out change", descriptor: "Counts on to the total" },
    ],
  },
  {
    standard_code: "3.NBT.A.2",
    verbs: [
      { word: "Add", gloss: "combine three-digit numbers" },
      { word: "Subtract", gloss: "find the difference" },
      { word: "Regroup", gloss: "trade between places" },
    ],
    concepts: ["Three-digit regrouping", "Place value strategies", "Inverse operations"],
    vocabulary: [
      { term: "regroup", definition: "trade ten of one place for one of the next" },
      { term: "algorithm", definition: "a step-by-step method that always works" },
      { term: "difference", definition: "the answer to a subtraction" },
      { term: "estimate", definition: "a rough answer to check against" },
    ],
    prior_skills: ["Add and subtract within 100", "Understand three-digit place value", "Round to the nearest ten"],
    prior_standards: [{ code: "2.NBT.B.5", text: "Fluently add and subtract within 100" }],
    future_standards: [{ code: "4.NBT.B.4", text: "Fluently add and subtract multi-digit whole numbers" }],
    challenges: [
      { problem: "Subtracting across a zero stalls", fix: "Model the double trade with blocks before the notation" },
      { problem: "Digits are subtracted whichever way is easier", fix: "Estimate first so a wrong answer looks wrong" },
    ],
    mastery_statement: "Student can add and subtract within 1000 fluently, regrouping correctly including across zeros.",
    ladder: [
      { name: "I can add without regrouping", descriptor: "Straightforward sums" },
      { name: "I can regroup once", descriptor: "Single trade" },
      { name: "I can regroup twice", descriptor: "Multiple trades" },
      { name: "I can subtract across a zero", descriptor: "Handles the hardest case" },
    ],
  },
  {
    standard_code: "4.MD.A.3",
    verbs: [
      { word: "Apply", gloss: "use the formula on a real problem" },
      { word: "Find", gloss: "work backwards to a missing side" },
    ],
    concepts: ["Area formula", "Perimeter", "Inverse reasoning"],
    vocabulary: [
      { term: "area", definition: "the space a shape covers, in square units" },
      { term: "perimeter", definition: "the distance all the way round" },
      { term: "formula", definition: "a rule written with symbols" },
      { term: "square unit", definition: "the unit area is measured in" },
    ],
    prior_skills: ["Find area by tiling", "Multiply multi-digit numbers", "Divide within 100"],
    prior_standards: [{ code: "3.MD.C.7", text: "Relate area to multiplication and addition" }],
    future_standards: [{ code: "6.G.A.1", text: "Find area of triangles and polygons" }],
    challenges: [
      { problem: "Area and perimeter formulas are swapped", fix: "Label the units — square for area, plain for perimeter" },
      { problem: "Working backwards is not attempted", fix: "Practice missing-side problems as their own set" },
    ],
    mastery_statement: "Student can apply area and perimeter formulas, including finding a missing side from a known total.",
    ladder: [
      { name: "I can find perimeter", descriptor: "Adds the sides" },
      { name: "I can find area", descriptor: "Multiplies length by width" },
      { name: "I can tell which the question wants", descriptor: "Reads for the measure" },
      { name: "I can find a missing side", descriptor: "Works backwards" },
    ],
  },
  {
    standard_code: "5.OA.A.1",
    verbs: [
      { word: "Use", gloss: "put brackets in an expression" },
      { word: "Evaluate", gloss: "work it out in the right order" },
    ],
    concepts: ["Grouping symbols", "Order of operations", "Expression structure"],
    vocabulary: [
      { term: "parentheses", definition: "round brackets grouping part of an expression" },
      { term: "evaluate", definition: "work out the value" },
      { term: "expression", definition: "a maths phrase with no equals sign" },
      { term: "grouping symbol", definition: "brackets telling you what to do first" },
    ],
    prior_skills: ["Multiply and divide fluently", "Add and subtract multi-digit numbers", "Read expressions"],
    prior_standards: [{ code: "4.OA.A.3", text: "Solve multistep word problems" }],
    future_standards: [{ code: "6.EE.A.2", text: "Write, read and evaluate expressions with variables" }],
    challenges: [
      { problem: "Everything is worked left to right", fix: "Compare 2 + 3 × 4 with (2 + 3) × 4 side by side" },
      { problem: "Nested brackets are worked outside in", fix: "Highlight the innermost pair first" },
    ],
    mastery_statement: "Student can evaluate expressions containing grouping symbols in the correct order.",
    ladder: [
      { name: "I can evaluate a simple expression", descriptor: "One or two operations" },
      { name: "I know multiplication comes first", descriptor: "Applies precedence" },
      { name: "I can use brackets", descriptor: "Evaluates grouped parts first" },
      { name: "I can handle nested brackets", descriptor: "Works innermost outward" },
    ],
  },
  {
    standard_code: "6.RP.A.1",
    verbs: [
      { word: "Understand", gloss: "know what a ratio compares" },
      { word: "Describe", gloss: "use ratio language correctly" },
    ],
    concepts: ["Ratio as comparison", "Part-to-part and part-to-whole", "Ratio language"],
    vocabulary: [
      { term: "ratio", definition: "a comparison of two amounts" },
      { term: "for every", definition: "the phrase describing a ratio relationship" },
      { term: "part to part", definition: "comparing one group with another" },
      { term: "part to whole", definition: "comparing one group with the total" },
    ],
    prior_skills: ["Multiply and divide fluently", "Understand fractions", "Simplify fractions"],
    prior_standards: [{ code: "5.NF.B.4", text: "Multiply fractions" }],
    future_standards: [{ code: "6.RP.A.3", text: "Use ratio reasoning to solve problems" }],
    challenges: [
      { problem: "Part-to-part is read as part-to-whole", fix: "Draw the groups and count the total separately" },
      { problem: "Ratios are written without saying what they compare", fix: "Require a 'for every' sentence with both units" },
    ],
    mastery_statement: "Student can describe a ratio relationship in words and distinguish part-to-part from part-to-whole.",
    ladder: [
      { name: "I can compare two amounts", descriptor: "Notices the relationship" },
      { name: "I can write it as a ratio", descriptor: "Uses ratio notation" },
      { name: "I can say it in words", descriptor: "Uses 'for every' language" },
      { name: "I can tell the two kinds apart", descriptor: "Part-to-part versus part-to-whole" },
    ],
  },
  {
    standard_code: "7.SP.A.1",
    verbs: [
      { word: "Understand", gloss: "know what a sample can tell you" },
      { word: "Generalize", gloss: "say something about the whole population" },
    ],
    concepts: ["Sample and population", "Representativeness", "Bias"],
    vocabulary: [
      { term: "population", definition: "everyone or everything you want to know about" },
      { term: "sample", definition: "the part of the population you actually check" },
      { term: "representative", definition: "reflecting the population fairly" },
      { term: "bias", definition: "a way of choosing that tilts the result" },
    ],
    prior_skills: ["Summarize data sets", "Compute mean and median", "Read data displays"],
    prior_standards: [{ code: "6.SP.B.5", text: "Summarize numerical data sets in relation to their context" }],
    future_standards: [{ code: "7.SP.A.2", text: "Use data from a random sample to draw inferences" }],
    challenges: [
      { problem: "Any sample is treated as good enough", fix: "Survey only the football team about favourite sports" },
      { problem: "Bigger is assumed to mean better", fix: "Compare a large biased sample with a small random one" },
    ],
    mastery_statement: "Student can judge whether a sample is representative and say what can fairly be concluded from it.",
    ladder: [
      { name: "I can tell sample from population", descriptor: "Distinguishes the two" },
      { name: "I can spot an unfair sample", descriptor: "Identifies obvious bias" },
      { name: "I can explain why it is unfair", descriptor: "Names the mechanism" },
      { name: "I can say what it does support", descriptor: "Limits the generalization" },
    ],
  },
  {
    standard_code: "8.G.A.1",
    verbs: [
      { word: "Verify", gloss: "check it by doing it" },
      { word: "Transform", gloss: "slide, flip or turn a shape" },
    ],
    concepts: ["Rigid motions", "Preserved properties", "Congruence"],
    vocabulary: [
      { term: "translation", definition: "sliding a shape without turning it" },
      { term: "reflection", definition: "flipping a shape over a line" },
      { term: "rotation", definition: "turning a shape around a point" },
      { term: "preserved", definition: "unchanged by the transformation" },
    ],
    prior_skills: ["Plot on the coordinate plane", "Measure angles", "Identify congruent shapes"],
    prior_standards: [{ code: "5.G.A.1", text: "Plot points on the coordinate plane" }],
    future_standards: [{ code: "8.G.A.2", text: "Understand congruence through a sequence of transformations" }],
    challenges: [
      { problem: "Reflections are drawn as slides", fix: "Trace and physically flip the paper over the line" },
      { problem: "Rotation direction and center are ignored", fix: "Mark the center and use a pin to turn" },
    ],
    mastery_statement: "Student can perform rotations, reflections and translations and state which properties are preserved.",
    ladder: [
      { name: "I can translate a shape", descriptor: "Slides accurately" },
      { name: "I can reflect a shape", descriptor: "Flips over a line" },
      { name: "I can rotate a shape", descriptor: "Turns about a point" },
      { name: "I can say what stayed the same", descriptor: "Names preserved properties" },
    ],
  },
  {
    standard_code: "8.F.B.4",
    verbs: [
      { word: "Construct", gloss: "build the function" },
      { word: "Determine", gloss: "find the rate and the starting value" },
      { word: "Interpret", gloss: "say what each number means" },
    ],
    concepts: ["Rate of change", "Initial value", "Modelling"],
    vocabulary: [
      { term: "rate of change", definition: "how much y changes for each step in x" },
      { term: "initial value", definition: "the value when x is zero" },
      { term: "model", definition: "a rule describing a real situation" },
      { term: "linear", definition: "changing by the same amount each step" },
    ],
    prior_skills: ["Graph proportional relationships", "Find slope", "Understand functions"],
    prior_standards: [{ code: "8.EE.B.5", text: "Graph proportional relationships and interpret slope" }],
    future_standards: [{ code: "F-LE.2", text: "Construct linear and exponential functions from graphs and tables" }],
    challenges: [
      { problem: "The initial value is taken from the first row rather than x = 0", fix: "Work back to zero explicitly" },
      { problem: "Rate is computed with no units", fix: "Say it aloud as 'dollars per week'" },
    ],
    mastery_statement: "Student can construct a linear function from a situation and interpret its rate and initial value in context.",
    ladder: [
      { name: "I can find the rate from a table", descriptor: "Computes the per-step change" },
      { name: "I can find the initial value", descriptor: "Works back to x = 0" },
      { name: "I can write the function", descriptor: "Produces y = mx + b" },
      { name: "I can say what the numbers mean", descriptor: "Interprets in context" },
    ],
  },
];

const blueprintsData = [
  {
    standard_code: "RF.K.2",
    title: "Listening Closely to Words",
    badge: "Kindergarten",
    route_name: "Oral Practice",
    route_line: "Hear rhyme → Clap the beats → Catch the first sound",
    success_criteria: ["Says whether two words rhyme", "Claps the syllables in a word", "Says the first sound in a spoken word"],
    steps: [
      { name: "Rhyme Warm-Up", minutes: 5, body: "A familiar rhyming song with the last word left off. Students supply it. Joyful and diagnostic at once.", science_tag: "retrieval" },
      { name: "Same End or Same Start", minutes: 10, body: "Sort word pairs into rhyming and starting-the-same. The confusion between these is the commonest one.", science_tag: "elaboration" },
      { name: "Clap the Beats", minutes: 10, body: "Clap syllables in names, starting with their own. Eyes closed so letters cannot interfere.", science_tag: "dual-coding" },
      { name: "Chin Drops", minutes: 8, body: "Hand under the chin — every syllable drops the jaw. A physical check children can run alone.", science_tag: "dual-coding" },
      { name: "What Sound Starts It", minutes: 12, body: "Say a word, students say the first sound. Sound not letter — correct gently and often.", science_tag: "retrieval" },
      { name: "Sound Sorting Game", minutes: 10, body: "Objects sorted by first sound into hoops. Physical, noisy, and everyone participates.", science_tag: "collaborative" },
      { name: "Three Quick Checks", minutes: 5, body: "One rhyme, one clap, one first sound, individually at the door.", science_tag: "spaced" },
    ],
    ef_supports: ["Familiar songs as the entry point", "Chin drop as a self-check", "Sorting hoops for physical grouping", "Eyes closed to remove letters"],
    tech: "Objects and picture cards",
    tech_purpose: "This is oral work — pictures, not print",
    ai_prompts: ["Generate rhyming and same-initial-sound word pairs", "List objects grouped by initial sound"],
    assessment: ["Check the rhyme sort for start/end confusion", "Watch syllable clapping accuracy", "Individual first-sound check"],
    why_it_works: ["Phonological awareness is oral, so letters would split attention", "The rhyme versus alliteration sort targets the standard confusion", "Chin drops give children a check they own", "Songs get every child participating before anyone is singled out"],
  },
  {
    standard_code: "W.1.1",
    title: "What I Think About This Book",
    badge: "Grade 1",
    route_name: "Writing Workshop",
    route_line: "Name the book → Say what you think → Give a reason",
    success_criteria: ["Names the book in the first sentence", "States an opinion", "Gives a reason that mentions something in the book"],
    steps: [
      { name: "Retrieve Opinion Words", minutes: 5, body: "I think, I like, the best. Quick oral recall of how to start.", science_tag: "retrieval" },
      { name: "Say It Out Loud First", minutes: 8, body: "Tell a partner what you thought of the book. Speaking before writing lowers the barrier.", science_tag: "collaborative" },
      { name: "Name the Book", minutes: 8, body: "The reader does not know which book. Model an opening sentence that names it.", science_tag: "dual-coding" },
      { name: "Because Something Happened", minutes: 12, body: "'Because I like it' says nothing. Push for a moment from the book. This is the whole lesson.", science_tag: "elaboration" },
      { name: "Draft Three Sentences", minutes: 12, body: "Book, opinion, reason. Three sentences, no more. A short piece finished beats a long one abandoned.", science_tag: "elaboration" },
      { name: "Add an Ending", minutes: 8, body: "One more sentence to close. Model two options and let students choose.", science_tag: "interleaving" },
      { name: "Read to a Partner", minutes: 5, body: "The partner checks the book is named and a reason is given.", science_tag: "spaced" },
    ],
    ef_supports: ["Say it aloud before writing", "Three-sentence frame", "Because prompt card", "Partner checklist of two items"],
    tech: "Printed sentence frames",
    tech_purpose: "Structure held externally while the ideas come",
    ai_prompts: ["Generate grade 1 opinion sentence frames", "Write weak reasons for students to improve"],
    assessment: ["Check the book is named", "Confirm the reason references the book", "Partner check on both"],
    why_it_works: ["Speaking before writing removes the blank-page barrier", "Pushing past 'because I like it' is the actual work at this grade", "Three sentences is a finishable target", "A two-item partner check is short enough to be used"],
  },
  {
    standard_code: "L.2.4",
    title: "Four Ways Into a Word",
    badge: "Grade 2",
    route_name: "Strategy Instruction",
    route_line: "Learn the strategies → Try each → Choose what fits",
    success_criteria: ["Uses sentence context", "Splits a compound word", "Chooses a strategy suited to the word"],
    steps: [
      { name: "Retrieve Known Prefixes", minutes: 5, body: "un-, re-, pre-. Quick recall before applying them.", science_tag: "retrieval" },
      { name: "Model Getting Stuck", minutes: 8, body: "Read, hit a hard word, stop visibly. Narrate choosing a strategy.", science_tag: "elaboration" },
      { name: "Compound Words Come Apart", minutes: 10, body: "Cover one half at a time. Butterfly, sunshine, rainbow. Two known words make an unknown one.", science_tag: "dual-coding" },
      { name: "Prefixes Change Meaning", minutes: 10, body: "Happy and unhappy. The prefix is a meaning switch, not decoration.", science_tag: "elaboration" },
      { name: "Or Use the Glossary", minutes: 8, body: "When the word matters and the clues run out. Practice finding a word alphabetically.", science_tag: "dual-coding" },
      { name: "Mixed Set", minutes: 12, body: "Words needing different strategies, shuffled. Students record which one they used.", science_tag: "interleaving" },
      { name: "One Word, One Strategy", minutes: 5, body: "One unfamiliar word: meaning plus the strategy used.", science_tag: "spaced" },
    ],
    ef_supports: ["Strategy anchor chart with four options", "Cover-half routine for compounds", "Prefix meaning cards", "Record the strategy used"],
    tech: "Printed word cards and a glossary",
    tech_purpose: "Sorting words by strategy physically",
    ai_prompts: ["Generate compound words from known parts", "Create a mixed set requiring different strategies"],
    assessment: ["Check the recorded strategy matches the word", "Watch for one strategy used regardless", "Exit word with strategy named"],
    why_it_works: ["Four named strategies make an invisible process choosable", "Covering half a compound is a move students can always run", "Recording the strategy makes selection explicit", "Mixed sets prevent drilling one approach"],
  },
  {
    standard_code: "RL.3.2",
    title: "What the Story Is Trying to Teach",
    badge: "Grade 3",
    route_name: "Explicit Instruction",
    route_line: "Retell it → Find the turning point → Name the lesson",
    success_criteria: ["Retells the story accurately", "States the lesson as a sentence about how to live", "Points to the detail that shows it"],
    steps: [
      { name: "Retrieve Story Elements", minutes: 5, body: "Character, problem, solution for a known tale. The scaffolding for message.", science_tag: "retrieval" },
      { name: "Fables Say It Outright", minutes: 10, body: "Read two fables with stated morals. Message with the inference removed — the easiest possible entry.", science_tag: "elaboration" },
      { name: "Now Without the Moral", minutes: 12, body: "A fable with the moral cut off. Students supply it. The gap is where the thinking happens.", science_tag: "elaboration" },
      { name: "Plot Is Not Lesson", minutes: 10, body: "'The tortoise won' is what happened. 'Keeping on beats being fast' is the lesson. Sort statements into the two.", science_tag: "dual-coding" },
      { name: "Find the Moment", minutes: 10, body: "Which detail shows the lesson? Usually one turning point carries it.", science_tag: "collaborative" },
      { name: "A Folktale From Elsewhere", minutes: 10, body: "Same skill on a tale from another culture. Lessons travel; the stories differ.", science_tag: "interleaving" },
      { name: "Share Two Lessons", minutes: 3, body: "Two students state a lesson and the detail proving it.", science_tag: "spaced" },
    ],
    ef_supports: ["Fables with morals as the entry", "Plot versus lesson sorting", "Sentence frame for stating a lesson", "Turning point marker"],
    tech: "Printed fables and folktales",
    tech_purpose: "Short complete stories so the whole arc is visible",
    ai_prompts: ["Write fables with clear morals for grade 3", "Generate plot statements and lesson statements for sorting"],
    assessment: ["Check lessons are about living, not events", "Confirm a supporting detail is cited", "Review the folktale transfer"],
    why_it_works: ["Fables state morals outright, so the concept lands before the inference is required", "Cutting the moral off creates the exact gap students must fill", "The plot-versus-lesson sort names the commonest error", "Folktales from elsewhere show the skill transfers"],
  },
  {
    standard_code: "W.4.2",
    title: "Facts That Belong Together",
    badge: "Grade 4",
    route_name: "Writing Workshop",
    route_line: "Gather → Group → Explain with detail",
    success_criteria: ["Groups related facts into sections", "Includes a definition where needed", "Uses a concrete detail in each section"],
    steps: [
      { name: "Retrieve Topic Sentences", minutes: 5, body: "What does a topic sentence do? Quick recall before scaling to sections.", science_tag: "retrieval" },
      { name: "A Pile Is Not a Text", minutes: 8, body: "Show facts in random order. Students feel the disorder before being told to group.", science_tag: "elaboration" },
      { name: "Sort Into Piles", minutes: 12, body: "Note cards sorted into three groups. Name each pile — those names become the sections.", science_tag: "dual-coding" },
      { name: "Define the Hard Words", minutes: 10, body: "A reader who does not know the topic needs the terms. Practice one-sentence definitions.", science_tag: "elaboration" },
      { name: "Add Something Concrete", minutes: 12, body: "One number, measurement or named example per section. Concrete detail is what makes writing informative.", science_tag: "elaboration" },
      { name: "Draft One Section", minutes: 10, body: "Topic sentence, facts, concrete detail, closing line. One section done well.", science_tag: "collaborative" },
      { name: "Read a Definition Aloud", minutes: 3, body: "Two students read theirs. Would a reader who knew nothing understand?", science_tag: "spaced" },
    ],
    ef_supports: ["Physical note cards for sorting", "Definition sentence frame", "One-concrete-detail rule", "Draft one section, not the whole piece"],
    tech: "Note cards",
    tech_purpose: "Grouping is physical before it is written",
    ai_prompts: ["Generate fact sets that fall into natural groups", "Write vague sentences for students to make concrete"],
    assessment: ["Check piles are coherent and named", "Confirm one concrete detail per section", "Test definitions on a naive reader"],
    why_it_works: ["Feeling the disorder motivates grouping better than being told to", "Pile names become section headings, so the structure emerges from the sort", "Concrete detail is the difference between informative and vague", "Testing definitions on a naive reader is a real audience check"],
  },
  {
    standard_code: "RI.5.5",
    title: "Two Texts, Two Shapes",
    badge: "Grade 5",
    route_name: "Analytical Reading",
    route_line: "Name each structure → Prove it → Say why it differs",
    success_criteria: ["Names each text's structure", "Cites signal words as evidence", "Explains how the two structures differ"],
    steps: [
      { name: "Retrieve Text Structures", minutes: 5, body: "Name the four patterns and a signal word for each.", science_tag: "retrieval" },
      { name: "Same Topic, Two Texts", minutes: 10, body: "Two texts on one subject. Same content, different organization — that contrast is the lesson.", science_tag: "dual-coding" },
      { name: "Name and Prove", minutes: 12, body: "Structure for each, with two signal words as evidence. Two, not one — one can be coincidence.", science_tag: "elaboration" },
      { name: "Ban the Topic Words", minutes: 10, body: "Compare the structures without mentioning the subject. Forces structural rather than content comparison.", science_tag: "elaboration" },
      { name: "Map Both", minutes: 12, body: "The matching graphic organizer for each. The organizer only fits if the structure was named right.", science_tag: "dual-coding" },
      { name: "Why Did They Choose It", minutes: 8, body: "What does chronology do that cause-and-effect does not? Structure as an authorial choice.", science_tag: "interleaving" },
      { name: "State the Difference", minutes: 3, body: "One sentence contrasting the two structures, no topic words allowed.", science_tag: "spaced" },
    ],
    ef_supports: ["Graphic organizer per structure", "Signal word chart", "Topic-word ban", "Two texts on one subject"],
    tech: "Printed paired texts",
    tech_purpose: "Comparison needs both texts side by side",
    ai_prompts: ["Write two texts on one topic using different structures", "Generate signal word sets by pattern"],
    assessment: ["Require two signal words per label", "Check comparison avoids content", "Confirm organizers fit"],
    why_it_works: ["Same topic, different structure isolates the variable", "Banning topic words is what forces structural comparison", "Two signal words prevents guessing from subject matter", "Asking why an author chose it makes structure purposeful"],
  },
  {
    standard_code: "SL.6.1",
    title: "Bring Evidence to the Table",
    badge: "Grade 6",
    route_name: "Structured Discussion",
    route_line: "Prepare with passages → Quote while talking → Say why it matters",
    success_criteria: ["Arrives with marked passages", "Quotes the text during discussion", "Explains why the evidence matters"],
    steps: [
      { name: "Retrieve Discussion Norms", minutes: 5, body: "Recall the agreed norms before the chart appears.", science_tag: "retrieval" },
      { name: "Ticket In", minutes: 8, body: "Two marked passages and a note on each. No ticket, no seat in the circle. Preparation becomes non-negotiable.", science_tag: "elaboration" },
      { name: "Quoting Out Loud", minutes: 10, body: "Reading a quote mid-conversation is awkward until practiced. Model it, then rehearse in pairs.", science_tag: "dual-coding" },
      { name: "So What?", minutes: 12, body: "A quote read out and left there does nothing. Every quote needs a sentence saying why it matters.", science_tag: "elaboration" },
      { name: "Seminar", minutes: 15, body: "Full discussion. Teacher outside the circle, silent. The silences belong to the students.", science_tag: "collaborative" },
      { name: "Tally the Evidence", minutes: 5, body: "Outer circle counts quotes used and 'so what' sentences that followed.", science_tag: "interleaving" },
      { name: "Reflect", minutes: 5, body: "Students note one moment evidence changed the conversation.", science_tag: "spaced" },
    ],
    ef_supports: ["Ticket-in requirement", "Quote-then-explain frame", "Inner and outer circle", "Tally sheets for evidence use"],
    tech: "Marked texts and tally sheets",
    tech_purpose: "Preparation made visible and countable",
    ai_prompts: ["Generate seminar questions requiring textual evidence", "Write quote-then-explain sentence frames"],
    assessment: ["Check tickets before the seminar", "Collect evidence tallies", "Read reflections"],
    why_it_works: ["A ticket-in makes preparation a condition rather than a hope", "Quoting aloud is a skill that needs rehearsal", "The 'so what' requirement stops evidence being decoration", "Counting evidence use makes an abstract expectation concrete"],
  },
  {
    standard_code: "RL.7.3",
    title: "Move the Story Somewhere Else",
    badge: "Grade 7",
    route_name: "Analytical Reading",
    route_line: "Describe the elements → Connect two → Test by changing one",
    success_criteria: ["Describes setting and character separately", "Explains how the setting shapes a character", "Tests the claim by changing the setting"],
    steps: [
      { name: "Retrieve Story Elements", minutes: 5, body: "Setting, character, plot, conflict. The parts before the interactions.", science_tag: "retrieval" },
      { name: "Setting Is Not Scenery", minutes: 10, body: "Setting includes time, place, rules, pressures. Broaden it before connecting it to anything.", science_tag: "elaboration" },
      { name: "Because the Setting Is…", minutes: 12, body: "A required sentence stem forcing the connection. Descriptions of elements in isolation will not satisfy it.", science_tag: "dual-coding" },
      { name: "Move the Story", minutes: 14, body: "Relocate it — different century, different country. What breaks? What survives? The damage reveals dependence.", science_tag: "elaboration" },
      { name: "Gather the Evidence", minutes: 10, body: "Which moments show the setting shaping the character? Two or three, spread across the text.", science_tag: "collaborative" },
      { name: "Write the Analysis", minutes: 8, body: "One paragraph: the connection, the evidence, and what the relocation test showed.", science_tag: "interleaving" },
      { name: "Share a Relocation", minutes: 3, body: "One student explains what broke when they moved the story.", science_tag: "spaced" },
    ],
    ef_supports: ["Broadened setting definition", "Because-the-setting-is stem", "Relocation thought experiment", "Evidence spread across the text"],
    tech: "Printed excerpt with numbered paragraphs",
    tech_purpose: "Citing moments across the text",
    ai_prompts: ["Write excerpts where setting strongly constrains character", "Generate relocation prompts for a given story"],
    assessment: ["Check the connection is made, not just described", "Review relocation reasoning", "Confirm evidence is spread"],
    why_it_works: ["The relocation test makes an abstract interaction concrete", "Broadening setting beyond scenery is what makes it able to shape anything", "A required stem forces connection over description", "What breaks under relocation is exactly what depended on the setting"],
  },
  {
    standard_code: "RI.8.2",
    title: "One Idea, Held Up by Others",
    badge: "Grade 8",
    route_name: "Analytical Reading",
    route_line: "Find the center → Find what holds it → Trace the build",
    success_criteria: ["States the central idea", "Identifies supporting ideas and links them", "Traces development across the text"],
    steps: [
      { name: "Retrieve Central Idea", minutes: 5, body: "One paragraph, one central idea. The base before the architecture.", science_tag: "retrieval" },
      { name: "Central Versus Supporting", minutes: 10, body: "Sort statements into central and supporting. The distinction is structural, not about importance.", science_tag: "dual-coding" },
      { name: "Draw the Arrows", minutes: 12, body: "Each supporting idea gets an arrow to the central one. Any that will not connect is worth discussing.", science_tag: "dual-coding" },
      { name: "Development Is Change", minutes: 12, body: "What is said about the idea at the start versus the end? If nothing changed, that is repetition.", science_tag: "elaboration" },
      { name: "Track on a Timeline", minutes: 10, body: "Plot the central idea's mentions across the text. Development becomes visible as movement.", science_tag: "dual-coding" },
      { name: "Objective Summary", minutes: 8, body: "Central idea, main supports, no opinion. Students circle any evaluative word and replace it.", science_tag: "interleaving" },
      { name: "Compare Two Maps", minutes: 3, body: "Two students compare their arrow diagrams and discuss differences.", science_tag: "spaced" },
    ],
    ef_supports: ["Central and supporting sorting", "Arrow diagram", "Timeline for development", "Evaluative word list"],
    tech: "Printed text with wide margins",
    tech_purpose: "Room to draw arrows between ideas",
    ai_prompts: ["Write a grade 8 text with a clear central idea and three supports", "Generate statements for central versus supporting sorting"],
    assessment: ["Check arrows connect supports to the center", "Confirm development shows change", "Scan summaries for opinion"],
    why_it_works: ["Arrows make an abstract relationship spatial", "An unconnectable support is a useful anomaly to discuss", "Defining development as change rules out repetition", "The timeline turns development into something visible"],
  },
  {
    standard_code: "W.8.2",
    title: "Explaining, Not Listing",
    badge: "Grade 8",
    route_name: "Writing Workshop",
    route_line: "Cut hard → Organize → Connect the pieces",
    success_criteria: ["Cuts irrelevant content", "Organizes sections logically", "Connects each section to the one before"],
    steps: [
      { name: "Retrieve Informative Structure", minutes: 5, body: "Introduction, sections, conclusion. Quick recall before deepening it.", science_tag: "retrieval" },
      { name: "A List Is Not an Explanation", minutes: 10, body: "Two passages: one lists facts, one connects them. Students name the difference precisely.", science_tag: "elaboration" },
      { name: "The Hard Cut", minutes: 12, body: "Half the research goes. Each survivor must answer the focus question. Selection is named in the standard.", science_tag: "elaboration" },
      { name: "Order for Dependency", minutes: 10, body: "Which section has to come first for the next to make sense? Sequence by need, not preference.", science_tag: "dual-coding" },
      { name: "Write the Joins", minutes: 12, body: "One sentence connecting each section to the last. The joins are where explanation lives.", science_tag: "elaboration" },
      { name: "Draft Two Sections", minutes: 10, body: "Two sections plus the join between them. Enough to feel whether it flows.", science_tag: "collaborative" },
      { name: "Read the Join Aloud", minutes: 3, body: "Two students read only their connecting sentence. Does it do real work?", science_tag: "spaced" },
    ],
    ef_supports: ["List versus explanation models", "Forced cut of half the notes", "Dependency ordering test", "Join sentence frame"],
    tech: "Note cards for sorting",
    tech_purpose: "Cutting and ordering physically",
    ai_prompts: ["Write paired passages, one listing and one explaining", "Generate transition sentences connecting sections"],
    assessment: ["Check the cut was genuine", "Confirm ordering has a reason", "Read joins for real connective work"],
    why_it_works: ["The list-versus-explanation contrast names the gap this standard cares about", "Forcing a cut teaches the selection the standard names", "Ordering by dependency gives a defensible reason", "Isolating the join sentence targets where explanation actually happens"],
  },
  {
    standard_code: "K.MD.A.2",
    title: "Which One Is Longer?",
    badge: "Kindergarten",
    route_name: "Concrete Practice",
    route_line: "Line them up → Compare → Say which and why",
    success_criteria: ["Lines objects up from a common start", "Says which has more of the attribute", "Names the attribute rather than saying bigger"],
    steps: [
      { name: "Bigger Is Not Enough", minutes: 5, body: "Show two objects, one longer and one heavier. Which is bigger? The ambiguity does the teaching.", science_tag: "elaboration" },
      { name: "Name the Attributes", minutes: 8, body: "Long, heavy, tall, full. Different things to compare, each with its own word.", science_tag: "dual-coding" },
      { name: "Line Up the Ends", minutes: 12, body: "Both objects start at the same line. Model comparing without lining up so the error is visible first.", science_tag: "dual-coding" },
      { name: "Compare and Say", minutes: 12, body: "Pairs of objects. Students line up and describe: 'the pencil is longer than the crayon'.", science_tag: "collaborative" },
      { name: "Heavier Needs Hands", minutes: 10, body: "Length is seen, weight is felt. One in each hand. Different attributes, different methods.", science_tag: "dual-coding" },
      { name: "Sort by Attribute", minutes: 8, body: "Which pairs would you compare by looking, which by holding?", science_tag: "interleaving" },
      { name: "Compare Two", minutes: 5, body: "One pair each, lined up and described.", science_tag: "spaced" },
    ],
    ef_supports: ["Common start line marked on the table", "Attribute word cards", "Objects with obvious differences first", "Sentence frame for describing"],
    tech: "Everyday classroom objects",
    tech_purpose: "Direct comparison needs things to hold",
    ai_prompts: ["List object pairs differing in one attribute", "Generate comparison sentence frames"],
    assessment: ["Watch for lining up at a common start", "Check the attribute is named", "Individual compare and describe"],
    why_it_works: ["The bigger ambiguity motivates naming attributes", "Modelling the error first makes the common start rule memorable", "Length is seen and weight is felt, so the method must change", "Describing aloud builds the comparison language the standard asks for"],
  },
  {
    standard_code: "1.NBT.C.4",
    title: "Adding On to a Two-Digit Number",
    badge: "Grade 1",
    route_name: "Concrete-Representational-Abstract",
    route_line: "Build it → Add ones or tens → Trade when ten gather",
    success_criteria: ["Adds a one-digit number to a two-digit number", "Adds a multiple of ten", "Composes a new ten when the ones fill up"],
    steps: [
      { name: "Retrieve Pairs to Ten", minutes: 5, body: "What makes ten with seven? This powers the composing later.", science_tag: "retrieval" },
      { name: "Build Both Numbers", minutes: 10, body: "Base ten blocks for each. Seeing them built prevents adding tens to ones.", science_tag: "dual-coding" },
      { name: "Add Tens to Tens", minutes: 10, body: "34 + 20. The tens pile grows, the ones do not move. Simple and worth doing alone first.", science_tag: "elaboration" },
      { name: "Add Ones to Ones", minutes: 10, body: "34 + 3. Only the ones change. Contrast with the previous step deliberately.", science_tag: "interleaving" },
      { name: "When Ten Ones Gather", minutes: 14, body: "34 + 8. Ten ones appear, so trade them for a ten. The trade is physical before notational.", science_tag: "dual-coding" },
      { name: "Mixed Practice", minutes: 8, body: "Tens, ones and composing shuffled. Mixing forces reading the problem.", science_tag: "interleaving" },
      { name: "Build and Explain", minutes: 3, body: "One sum built, with the student saying what they traded.", science_tag: "spaced" },
    ],
    ef_supports: ["Base ten blocks", "Place value mat with two columns", "Trade-the-moment-ten-appears routine", "Tens and ones practiced separately first"],
    tech: "Base ten blocks and place value mats",
    tech_purpose: "The trade has to be physical before it means anything",
    ai_prompts: ["Generate sums separated into tens-only, ones-only and composing", "Create mixed practice sets"],
    assessment: ["Watch for tens added to ones", "Check the trade happens when needed", "Individual build and explain"],
    why_it_works: ["Practicing tens and ones separately before mixing prevents the classic confusion", "Building both numbers keeps place value visible", "Trading physically explains what the notation only records", "Mixed practice stops procedural autopilot"],
  },
  {
    standard_code: "2.MD.C.8",
    title: "Counting Money That Is Not All the Same",
    badge: "Grade 2",
    route_name: "Concrete Practice",
    route_line: "Know the values → Start with the biggest → Count on",
    success_criteria: ["States each coin's value", "Counts a mixed handful starting with the largest", "Uses dollar and cent symbols correctly"],
    steps: [
      { name: "Skip Count Warm-Up", minutes: 5, body: "By fives, tens and twenty-fives. Coin counting is skip counting in disguise.", science_tag: "retrieval" },
      { name: "Not About Size", minutes: 8, body: "A dime is smaller than a nickel and worth more. Confront it early — children reason from size.", science_tag: "elaboration" },
      { name: "Label Every Coin", minutes: 10, body: "Write the value on a sticky note on each coin. Value made visible while it is being learned.", science_tag: "dual-coding" },
      { name: "Biggest First", minutes: 12, body: "Sort the handful largest to smallest, then count on. Order makes counting tractable.", science_tag: "dual-coding" },
      { name: "Two Ways to Write It", minutes: 10, body: "65¢ and $0.65. Sort amounts into the two notations and match the pairs.", science_tag: "interleaving" },
      { name: "Shop and Give Change", minutes: 12, body: "Price cards and coins. Counting on from price to payment is how change actually works.", science_tag: "collaborative" },
      { name: "Count One Handful", minutes: 3, body: "One mixed set counted and written both ways.", science_tag: "spaced" },
    ],
    ef_supports: ["Value labels on coins", "Sort-before-counting routine", "Notation matching cards", "Real or realistic coins"],
    tech: "Coin sets and price cards",
    tech_purpose: "Money is physical, and the size-versus-value confusion needs real coins",
    ai_prompts: ["Generate mixed coin sets with target totals", "Create shopping scenarios requiring change"],
    assessment: ["Check coins are sorted before counting", "Confirm notation is used correctly", "Watch for size-based reasoning"],
    why_it_works: ["The dime-versus-nickel contradiction has to be met head on", "Sorting largest first makes counting on possible", "Labelling values supports the memory while it forms", "Counting on for change is the real-world method, not subtraction"],
  },
  {
    standard_code: "3.NBT.A.2",
    title: "Regrouping Across Three Places",
    badge: "Grade 3",
    route_name: "Strategy Instruction",
    route_line: "Estimate → Regroup with blocks → Record it",
    success_criteria: ["Estimates before calculating", "Regroups correctly, including twice", "Subtracts across a zero"],
    steps: [
      { name: "Retrieve Within 100", minutes: 5, body: "Two-digit sums and differences. The foundation before extending it.", science_tag: "retrieval" },
      { name: "Estimate First", minutes: 8, body: "Round both numbers and add. Now a wrong answer will look wrong.", science_tag: "elaboration" },
      { name: "Trade With Blocks", minutes: 12, body: "Ten ones for a ten, ten tens for a hundred. Both trades done physically before writing anything.", science_tag: "dual-coding" },
      { name: "Record What You Traded", minutes: 10, body: "The little numbers in the algorithm record the trade. Connect the notation to the block move.", science_tag: "dual-coding" },
      { name: "Regrouping Twice", minutes: 12, body: "Problems needing two trades. Slow and careful with blocks alongside.", science_tag: "elaboration" },
      { name: "The Zero Problem", minutes: 12, body: "302 - 147. Nothing to borrow from. Model the double trade with blocks — this is the hardest case.", science_tag: "interleaving" },
      { name: "Estimate, Solve, Check", minutes: 3, body: "One problem through the whole routine.", science_tag: "spaced" },
    ],
    ef_supports: ["Base ten blocks alongside the algorithm", "Estimate-first step", "Place value columns on the page", "Zero-borrowing modelled physically"],
    tech: "Base ten blocks and place value paper",
    tech_purpose: "The double trade across a zero needs to be seen",
    ai_prompts: ["Generate problems requiring one, two and zero-crossing regroupings", "Create estimation practice sets"],
    assessment: ["Check estimates precede answers", "Watch the zero-crossing problems specifically", "Confirm recorded trades match the blocks"],
    why_it_works: ["Estimating first turns checking into comparison", "Blocks alongside the algorithm connect meaning to notation", "Borrowing across a zero is the case that defeats students, so model it physically", "Recording the trade explains the little numbers rather than mystifying them"],
  },
  {
    standard_code: "4.MD.A.3",
    title: "Working Backwards From Area",
    badge: "Grade 4",
    route_name: "Strategy Instruction",
    route_line: "Know both formulas → Tell them apart → Reverse them",
    success_criteria: ["Chooses the right formula for the question", "Uses correct units for each", "Finds a missing side from a known area or perimeter"],
    steps: [
      { name: "Retrieve Both Formulas", minutes: 5, body: "Area and perimeter, stated from memory. The tools before the choosing.", science_tag: "retrieval" },
      { name: "Units Tell Them Apart", minutes: 10, body: "Square units means area. Plain units means perimeter. Read the question for the unit first.", science_tag: "dual-coding" },
      { name: "Same Rectangle, Both Answers", minutes: 10, body: "Compute both for one shape and label them. The contrast prevents the swap.", science_tag: "interleaving" },
      { name: "Fence or Carpet", minutes: 10, body: "Real contexts. Fencing is perimeter, carpeting is area. Context names the measure.", science_tag: "elaboration" },
      { name: "Reverse the Formula", minutes: 14, body: "Area 48, one side 6, find the other. Division rather than multiplication — a genuine shift.", science_tag: "elaboration" },
      { name: "Reverse the Perimeter", minutes: 8, body: "Perimeter 30, one side 7, find the other. Harder, because two sides share what is left.", science_tag: "interleaving" },
      { name: "One Forwards, One Back", minutes: 3, body: "One straightforward problem and one missing-side problem.", science_tag: "spaced" },
    ],
    ef_supports: ["Unit check as the first move", "Fence-or-carpet context test", "Both computed on one shape", "Missing-side problems as their own set"],
    tech: "Grid paper and printed rectangles",
    tech_purpose: "Drawing the rectangle makes the missing side visible",
    ai_prompts: ["Generate real contexts distinguishing area from perimeter", "Create missing-side problems for both formulas"],
    assessment: ["Check the unit is used to choose the formula", "Confirm missing-side problems are attempted", "Watch for swapped formulas"],
    why_it_works: ["Units are a reliable discriminator students can always apply", "Computing both on one shape makes the difference concrete", "Real contexts give the formulas meaning beyond symbols", "Reversing is a genuine step up, so it gets its own practice"],
  },
  {
    standard_code: "5.OA.A.1",
    title: "Brackets Change Everything",
    badge: "Grade 5",
    route_name: "Explicit Instruction",
    route_line: "See the difference → Learn the order → Handle nesting",
    success_criteria: ["Evaluates in the correct order", "Shows how brackets change a result", "Works nested brackets from the inside out"],
    steps: [
      { name: "Retrieve Operations", minutes: 5, body: "Quick multiplication and division facts. Fluency frees attention for order.", science_tag: "retrieval" },
      { name: "Same Numbers, Two Answers", minutes: 10, body: "2 + 3 × 4 and (2 + 3) × 4. Different answers from the same digits. The brackets matter, visibly.", science_tag: "elaboration" },
      { name: "The Order", minutes: 10, body: "Brackets, then multiply and divide, then add and subtract. Stated after the need for it is felt.", science_tag: "dual-coding" },
      { name: "Left to Right Within a Level", minutes: 10, body: "Multiplication and division rank equally — work left to right. A subtlety usually skipped.", science_tag: "elaboration" },
      { name: "Nested Brackets", minutes: 12, body: "Highlight the innermost pair and work outward. Color-code the layers.", science_tag: "dual-coding" },
      { name: "Place the Brackets", minutes: 10, body: "Given numbers and a target answer, insert brackets to make it true. Working backwards proves understanding.", science_tag: "interleaving" },
      { name: "Evaluate Two", minutes: 3, body: "One nested expression evaluated step by step.", science_tag: "spaced" },
    ],
    ef_supports: ["Color-coded bracket layers", "Order chart posted", "Same-digits-different-answer pairs", "Insert-the-brackets puzzles"],
    tech: "Printed expression cards",
    tech_purpose: "Color-coding nesting needs a markable copy",
    ai_prompts: ["Generate expression pairs differing only by brackets", "Create insert-the-brackets puzzles with target answers"],
    assessment: ["Check brackets are evaluated first", "Watch left-to-right within a level", "Review insert-the-brackets solutions"],
    why_it_works: ["Two answers from the same digits motivates the rule before it is stated", "Color-coding nesting prevents outside-in working", "The equal-rank subtlety is where confident students go wrong", "Inserting brackets to hit a target is harder than evaluating, so it proves more"],
  },
  {
    standard_code: "6.RP.A.1",
    title: "For Every One of These, Three of Those",
    badge: "Grade 6",
    route_name: "Explicit Instruction",
    route_line: "Build the groups → Say it in words → Distinguish the two kinds",
    success_criteria: ["Describes a ratio in words", "Writes it in ratio notation", "Tells part-to-part from part-to-whole"],
    steps: [
      { name: "Retrieve Fractions", minutes: 5, body: "Simplify three fractions. Ratios scale the same way, and the link is worth flagging.", science_tag: "retrieval" },
      { name: "Build It With Counters", minutes: 10, body: "Two red for every three blue. Build several groups. The relationship is physical before notational.", science_tag: "dual-coding" },
      { name: "Say It Properly", minutes: 10, body: "'For every two red there are three blue.' Both quantities named, every time.", science_tag: "elaboration" },
      { name: "Part to Part, Part to Whole", minutes: 14, body: "2:3 red to blue, but 2:5 red to total. Same set, different ratios. This is the confusion.", science_tag: "elaboration" },
      { name: "Which Is Being Asked", minutes: 12, body: "Questions requiring one or the other. Reading the question is the skill.", science_tag: "interleaving" },
      { name: "Ratios in the Room", minutes: 8, body: "Find real ratios in the class and describe them properly.", science_tag: "collaborative" },
      { name: "Describe One Ratio", minutes: 3, body: "One relationship described in words and notation, with the kind named.", science_tag: "spaced" },
    ],
    ef_supports: ["Two-color counters", "For-every sentence frame", "Part-to-part and part-to-whole side by side", "Real classroom ratios"],
    tech: "Colored counters",
    tech_purpose: "Building the groups makes the relationship physical",
    ai_prompts: ["Generate ratio scenarios requiring both kinds", "Create questions that hinge on which ratio is asked for"],
    assessment: ["Check both quantities are named in words", "Confirm the two kinds are distinguished", "Watch for part-to-whole given when part-to-part is asked"],
    why_it_works: ["Building the groups makes a ratio a relationship rather than a pair of numbers", "Naming both quantities prevents bare unlabelled ratios", "The part-to-part versus part-to-whole confusion is the core difficulty", "Finding ratios in the room makes the concept immediately usable"],
  },
  {
    standard_code: "7.SP.A.1",
    title: "Who Did You Actually Ask?",
    badge: "Grade 7",
    route_name: "Explicit Instruction",
    route_line: "Ask a biased sample → See the distortion → Design a fair one",
    success_criteria: ["Distinguishes sample from population", "Identifies why a sample is unrepresentative", "Says what a sample does and does not support"],
    steps: [
      { name: "Retrieve Data Summaries", minutes: 5, body: "Mean and median from a small set. The tools before the question of who was measured.", science_tag: "retrieval" },
      { name: "Survey the Wrong People", minutes: 12, body: "Ask only the football team about favourite sports. Report the finding as though it were the school's. Let them object.", science_tag: "elaboration" },
      { name: "Name the Problem", minutes: 10, body: "The sample was not representative. Define the terms once the need for them is obvious.", science_tag: "dual-coding" },
      { name: "Spot the Bias", minutes: 12, body: "Several sampling methods. Which are fair? Bias is usually in who was easiest to ask.", science_tag: "elaboration" },
      { name: "Big and Biased", minutes: 10, body: "A large biased sample versus a small random one. Size does not fix bias — the surprising part.", science_tag: "interleaving" },
      { name: "Design a Fair Sample", minutes: 10, body: "Students design a sampling method for a real school question and defend it.", science_tag: "collaborative" },
      { name: "Judge a Claim", minutes: 3, body: "Given a sample and a claim, say whether the claim is supported.", science_tag: "spaced" },
    ],
    ef_supports: ["Live biased survey", "Sampling method comparison cards", "Design-and-defend task", "Terms defined after the need arises"],
    tech: "Class survey materials",
    tech_purpose: "A real biased survey is more persuasive than a described one",
    ai_prompts: ["Generate sampling scenarios with varied bias", "Create claims that outrun their samples"],
    assessment: ["Check bias is named specifically", "Confirm the size-does-not-fix-bias point landed", "Review sampling designs"],
    why_it_works: ["Running the biased survey live provokes the objection rather than teaching it", "Defining terms after the need makes them meaningful", "Big-and-biased is genuinely surprising and therefore memorable", "Designing a method is harder than criticising one"],
  },
  {
    standard_code: "8.G.A.1",
    title: "Slide, Flip, Turn — What Survives?",
    badge: "Grade 8",
    route_name: "Concrete Practice",
    route_line: "Do the transformation → Measure before and after → Name what held",
    success_criteria: ["Performs each transformation accurately", "Measures lengths and angles before and after", "States which properties are preserved"],
    steps: [
      { name: "Retrieve Coordinate Plotting", minutes: 5, body: "Plot a triangle from three ordered pairs. The shape to transform.", science_tag: "retrieval" },
      { name: "Trace and Slide", minutes: 10, body: "Trace onto tracing paper and translate. Measure sides before and after. Nothing changed.", science_tag: "dual-coding" },
      { name: "Trace and Flip", minutes: 12, body: "Reflect by physically flipping the tracing over the line. Students who slide instead of flip see the difference immediately.", science_tag: "dual-coding" },
      { name: "Pin and Turn", minutes: 12, body: "Rotate about a marked center with a pin. Direction and center both matter, and both get forgotten.", science_tag: "elaboration" },
      { name: "Measure Everything", minutes: 10, body: "Sides and angles before and after each transformation. Build the table of what is preserved.", science_tag: "elaboration" },
      { name: "What Did Change?", minutes: 8, body: "Position changed; size, shape and angles did not. Naming what varied sharpens what did not.", science_tag: "interleaving" },
      { name: "Predict Then Check", minutes: 3, body: "Predict the image of one transformation, then perform it.", science_tag: "spaced" },
    ],
    ef_supports: ["Tracing paper for physical transformation", "Pin for rotation center", "Before-and-after measurement table", "Mark the center and direction every time"],
    tech: "Tracing paper, pins, grid paper",
    tech_purpose: "Verifying experimentally is what the standard actually asks for",
    ai_prompts: ["Generate transformation tasks with specified centers and lines", "Create predict-then-check exercises"],
    assessment: ["Watch for reflections performed as slides", "Check measurements are taken both times", "Confirm preserved properties are named"],
    why_it_works: ["The standard says verify experimentally, so the paper has to move", "Physically flipping distinguishes reflection from translation instantly", "Measuring before and after makes preservation a finding rather than a claim", "Naming what changed sharpens what did not"],
  },
  {
    standard_code: "8.F.B.4",
    title: "Writing the Rule for a Situation",
    badge: "Grade 8",
    route_name: "Mathematical Modelling",
    route_line: "Find the rate → Work back to zero → Write and interpret",
    success_criteria: ["Finds the rate of change from a table or description", "Determines the initial value at x = 0", "Interprets both numbers in context"],
    steps: [
      { name: "Retrieve Slope", minutes: 5, body: "Rise over run from a graph. The rate before the whole function.", science_tag: "retrieval" },
      { name: "Rate From a Table", minutes: 10, body: "How much does y change per step in x? Check it is constant before calling it linear.", science_tag: "elaboration" },
      { name: "Work Back to Zero", minutes: 12, body: "The initial value is at x = 0, not the first row. Step backwards to reach it. This is the commonest error.", science_tag: "elaboration" },
      { name: "Write It as y = mx + b", minutes: 10, body: "Assemble the two numbers into the rule. Structure after meaning.", science_tag: "dual-coding" },
      { name: "Say What They Mean", minutes: 12, body: "Not 'm is 15' but 'fifteen dollars per week', and 'b is 40' but 'forty dollars to start'.", science_tag: "elaboration" },
      { name: "From Two Points", minutes: 10, body: "Given only two points, find both. Harder, and it tests whether the method is understood.", science_tag: "interleaving" },
      { name: "Model One Situation", minutes: 3, body: "One description turned into a function with both numbers interpreted.", science_tag: "spaced" },
    ],
    ef_supports: ["Work-back-to-zero routine", "Units required on both numbers", "Table with an added x = 0 row", "Two-point method as separate practice"],
    tech: "Printed tables and graph paper",
    tech_purpose: "Extending a table back to zero needs room to write",
    ai_prompts: ["Generate tables not starting at x = 0", "Create real situations modelled by linear functions"],
    assessment: ["Check the initial value is at x = 0", "Confirm both numbers are interpreted with units", "Review two-point work"],
    why_it_works: ["Taking the initial value from the first row is the dominant error, so target it", "Interpreting with units turns algebra into modelling", "Checking the rate is constant guards against calling anything linear", "The two-point case tests method rather than pattern-spotting"],
  },
];

await seedStandardsBatch({
  label: "Batch 6",
  standardsData,
  unpacksData,
  blueprintsData,
});
