// @ts-nocheck
/**
 * Batch 2: 20 more drafted standards, extending the pilot pattern.
 *
 * Fills the gaps the pilot left — print concepts and narrative/informative/
 * argument writing on the ELA side, and fraction equivalence, rational numbers
 * and geometry on the math side — so the library covers a usable spread before
 * committing to a full corpus run.
 *
 *   bun run scripts/seed-standards-batch-2.ts
 */
import { seedStandardsBatch } from "./lib/seed-standards-batch";

const standardsData = [
  // ─── ELA ────────────────────────────────────────────────────────────────
  {
    code: "RF.K.1",
    name: "Understand how print works",
    plain_reading:
      "Demonstrate understanding of the organization and basic features of print, including directionality, word boundaries, and letter recognition.",
    learning_target: "I can show which way the words go and where one word stops and the next begins.",
    skills: ["Print Concepts", "Directionality", "Letter Recognition"],
    science_tags: ["dual-coding", "retrieval"],
    match_keys: ["print concepts", "directionality", "word boundaries", "left to right", "return sweep"],
  },
  {
    code: "RL.1.3",
    name: "Describe characters, settings, and major events",
    plain_reading:
      "Describe characters, settings, and major events in a story, using key details.",
    learning_target: "I can tell who is in the story, where it happens, and what happens, using details.",
    skills: ["Story Elements", "Key Details", "Retelling"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["characters", "setting", "major events", "story elements", "key details"],
  },
  {
    code: "RI.2.5",
    name: "Use text features to find information",
    plain_reading:
      "Know and use various text features (captions, bold print, subheadings, glossaries, indexes, electronic menus, icons) to locate key facts or information in a text efficiently.",
    learning_target: "I can use headings, bold words, and captions to find what I need fast.",
    skills: ["Text Features", "Locating Information", "Nonfiction Navigation"],
    science_tags: ["dual-coding", "retrieval"],
    match_keys: ["text features", "headings", "captions", "glossary", "index", "bold print"],
  },
  {
    code: "W.3.3",
    name: "Write a narrative with a clear sequence",
    plain_reading:
      "Write narratives to develop real or imagined experiences or events using effective technique, descriptive details, and clear event sequences.",
    learning_target: "I can tell a story in order with details that put the reader there.",
    skills: ["Narrative Writing", "Sequencing", "Descriptive Detail"],
    science_tags: ["elaboration", "spaced"],
    match_keys: ["narrative writing", "personal narrative", "sequence", "descriptive details", "story writing"],
  },
  {
    code: "RI.4.5",
    name: "Describe the structure of a text",
    plain_reading:
      "Describe the overall structure (chronology, comparison, cause/effect, problem/solution) of events, ideas, concepts, or information in a text or part of a text.",
    learning_target: "I can name how a text is organized and show what gave it away.",
    skills: ["Text Structure", "Organizational Patterns", "Nonfiction Analysis"],
    science_tags: ["dual-coding", "interleaving"],
    match_keys: ["text structure", "cause and effect", "compare contrast", "problem solution", "chronology"],
  },
  {
    code: "L.5.5",
    name: "Understand figurative language and word nuance",
    plain_reading:
      "Demonstrate understanding of figurative language, word relationships, and nuances in word meanings, including similes, metaphors, and idioms.",
    learning_target: "I can tell when words mean something other than exactly what they say.",
    skills: ["Figurative Language", "Word Relationships", "Nuance"],
    science_tags: ["elaboration", "interleaving"],
    match_keys: ["figurative language", "simile", "metaphor", "idiom", "shades of meaning"],
  },
  {
    code: "RI.6.5",
    name: "Analyze how a part fits the whole text",
    plain_reading:
      "Analyze how a particular sentence, paragraph, chapter, or section fits into the overall structure of a text and contributes to the development of the ideas.",
    learning_target: "I can explain what a paragraph is doing for the text as a whole.",
    skills: ["Text Structure", "Analysis", "Authorial Craft"],
    science_tags: ["elaboration", "dual-coding"],
    match_keys: ["text structure", "paragraph function", "contributes to development", "overall structure"],
  },
  {
    code: "W.6.2",
    name: "Write an informative or explanatory text",
    plain_reading:
      "Write informative/explanatory texts to examine a topic and convey ideas, concepts, and information through the selection, organization, and analysis of relevant content.",
    learning_target: "I can explain a topic clearly by choosing and organising the right information.",
    skills: ["Informative Writing", "Organization", "Source Selection"],
    science_tags: ["elaboration", "spaced"],
    match_keys: ["informative writing", "explanatory", "expository", "organize information", "research writing"],
  },
  {
    code: "RL.8.3",
    name: "Analyze how dialogue and incidents drive a story",
    plain_reading:
      "Analyze how particular lines of dialogue or incidents in a story or drama propel the action, reveal aspects of a character, or provoke a decision.",
    learning_target: "I can explain what a single moment does to the story or the character.",
    skills: ["Character Analysis", "Plot Development", "Textual Analysis"],
    science_tags: ["elaboration", "interleaving"],
    match_keys: ["dialogue", "propel the action", "reveal character", "provoke a decision", "turning point"],
  },
  {
    code: "W.8.1",
    name: "Write an argument with claims and evidence",
    plain_reading:
      "Write arguments to support claims with clear reasons and relevant evidence, acknowledging and distinguishing the claim from alternate or opposing claims.",
    learning_target: "I can argue a claim with evidence and deal fairly with the other side.",
    skills: ["Argument Writing", "Counterclaim", "Evidence"],
    science_tags: ["elaboration", "interleaving"],
    match_keys: ["argument writing", "claim", "counterclaim", "evidence", "rebuttal", "persuasive essay"],
  },

  // ─── Mathematics ────────────────────────────────────────────────────────
  {
    code: "K.OA.A.1",
    name: "Represent addition and subtraction",
    plain_reading:
      "Represent addition and subtraction with objects, fingers, mental images, drawings, sounds, acting out situations, verbal explanations, expressions, or equations.",
    learning_target: "I can show adding and taking away with objects, drawings, or numbers.",
    skills: ["Addition", "Subtraction", "Representation"],
    science_tags: ["dual-coding", "collaborative"],
    match_keys: ["represent addition", "subtraction", "act it out", "drawings", "joining and separating"],
  },
  {
    code: "1.NBT.B.2",
    name: "Understand two-digit place value",
    plain_reading:
      "Understand that the two digits of a two-digit number represent amounts of tens and ones, including that 10 can be thought of as a bundle of ten ones called a ten.",
    learning_target: "I can say how many tens and how many ones are in a number.",
    skills: ["Place Value", "Bundling", "Number Sense"],
    science_tags: ["dual-coding", "retrieval"],
    match_keys: ["place value", "tens and ones", "two digit", "bundle of ten", "unitizing"],
  },
  {
    code: "2.OA.B.2",
    name: "Add and subtract fluently within 20",
    plain_reading:
      "Fluently add and subtract within 20 using mental strategies. By end of Grade 2, know from memory all sums of two one-digit numbers.",
    learning_target: "I can add and subtract small numbers quickly using a strategy that fits.",
    skills: ["Fact Fluency", "Mental Strategies", "Number Sense"],
    science_tags: ["retrieval", "spaced"],
    match_keys: ["fact fluency", "within 20", "make a ten", "doubles", "mental math", "math facts"],
  },
  {
    code: "3.NF.A.3",
    name: "Compare fractions and explain equivalence",
    plain_reading:
      "Explain equivalence of fractions in special cases, and compare fractions by reasoning about their size, recognising that comparisons are valid only when the two fractions refer to the same whole.",
    learning_target: "I can tell which fraction is bigger and show why two fractions are the same.",
    skills: ["Equivalent Fractions", "Comparing Fractions", "Fraction Reasoning"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["equivalent fractions", "compare fractions", "same whole", "fraction reasoning", "number line"],
  },
  {
    code: "4.NF.B.3",
    name: "Add and subtract fractions with like denominators",
    plain_reading:
      "Understand a fraction a/b with a > 1 as a sum of fractions 1/b, and add and subtract fractions with like denominators, including mixed numbers.",
    learning_target: "I can add and subtract fractions that share a denominator by counting the parts.",
    skills: ["Fractions", "Decomposing", "Mixed Numbers"],
    science_tags: ["elaboration", "dual-coding"],
    match_keys: ["like denominators", "add fractions", "decompose fractions", "mixed numbers", "unit fractions"],
  },
  {
    code: "5.NBT.A.1",
    name: "Understand place value across the decimal point",
    plain_reading:
      "Recognize that in a multi-digit number, a digit in one place represents 10 times as much as it represents in the place to its right and 1/10 of what it represents in the place to its left.",
    learning_target: "I can explain how each place is ten times the one beside it, both ways.",
    skills: ["Place Value", "Decimals", "Powers of Ten"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["place value", "decimals", "ten times", "one tenth", "powers of ten"],
  },
  {
    code: "6.NS.A.1",
    name: "Divide a fraction by a fraction",
    plain_reading:
      "Interpret and compute quotients of fractions, and solve word problems involving division of fractions by fractions, using visual fraction models and equations.",
    learning_target: "I can work out how many of one fraction fit inside another, and say why.",
    skills: ["Fraction Division", "Modelling", "Reciprocal Reasoning"],
    science_tags: ["dual-coding", "elaboration"],
    match_keys: ["divide fractions", "quotients of fractions", "how many fit", "invert and multiply", "fraction models"],
  },
  {
    code: "7.RP.A.2",
    name: "Recognize and represent proportional relationships",
    plain_reading:
      "Recognize and represent proportional relationships between quantities, identifying the constant of proportionality in tables, graphs, equations, diagrams, and verbal descriptions.",
    learning_target: "I can tell whether a relationship is proportional and find its constant.",
    skills: ["Proportional Reasoning", "Constant of Proportionality", "Graphing"],
    science_tags: ["dual-coding", "interleaving"],
    match_keys: ["proportional relationships", "constant of proportionality", "unit rate", "y=kx", "straight line through origin"],
  },
  {
    code: "7.NS.A.1",
    name: "Add and subtract rational numbers",
    plain_reading:
      "Apply and extend previous understandings of addition and subtraction to add and subtract rational numbers, representing addition and subtraction on a horizontal or vertical number line diagram.",
    learning_target: "I can add and subtract positive and negative numbers and show it on a number line.",
    skills: ["Integers", "Rational Numbers", "Number Line Reasoning"],
    science_tags: ["dual-coding", "interleaving"],
    match_keys: ["integers", "negative numbers", "add and subtract rational", "number line", "additive inverse"],
  },
  {
    code: "8.G.B.7",
    name: "Apply the Pythagorean Theorem",
    plain_reading:
      "Apply the Pythagorean Theorem to determine unknown side lengths in right triangles in real-world and mathematical problems in two and three dimensions.",
    learning_target: "I can find a missing side of a right triangle and know when the theorem applies.",
    skills: ["Pythagorean Theorem", "Right Triangles", "Problem Solving"],
    science_tags: ["retrieval", "interleaving"],
    match_keys: ["pythagorean theorem", "right triangle", "hypotenuse", "missing side", "a squared plus b squared"],
  },
];

const unpacksData = [
  {
    standard_code: "RF.K.1",
    verbs: [
      { word: "Demonstrate", gloss: "show that you know how print works" },
      { word: "Recognize", gloss: "know a letter or word when you see it" },
      { word: "Follow", gloss: "track the words in the right order" },
    ],
    concepts: ["Directionality", "Word boundaries", "Letter vs word"],
    vocabulary: [
      { term: "letter", definition: "one symbol we use to build words" },
      { term: "word", definition: "letters together with a space on each side" },
      { term: "sentence", definition: "a group of words that tells a whole idea" },
      { term: "space", definition: "the gap that shows where a word ends" },
    ],
    prior_skills: ["Hold a book the right way up", "Turn pages one at a time", "Recognize own name in print"],
    prior_standards: [{ code: "PK.RF.1", text: "Show interest in books and handle them correctly" }],
    future_standards: [{ code: "RF.1.1", text: "Recognize the distinguishing features of a sentence" }],
    challenges: [
      { problem: "Letter and word are used interchangeably", fix: "Frame one, then the other, with a finger window" },
      { problem: "Tracking drifts away from the words being read", fix: "Use a pointer and read slowly enough to match" },
    ],
    mastery_statement: "Student can track print left to right with return sweep and point to a letter, a word and a sentence on request.",
    ladder: [
      { name: "I can hold a book and turn the pages", descriptor: "Handles books conventionally" },
      { name: "I can point to where we start reading", descriptor: "Finds the top-left starting point" },
      { name: "I can follow the words with my finger", descriptor: "Tracks with return sweep" },
      { name: "I can show one letter and one word", descriptor: "Distinguishes letter from word" },
    ],
  },
  {
    standard_code: "RL.1.3",
    verbs: [
      { word: "Describe", gloss: "tell about something using details" },
      { word: "Identify", gloss: "pick out who, where and what" },
    ],
    concepts: ["Character", "Setting", "Major events"],
    vocabulary: [
      { term: "character", definition: "a person or animal in the story" },
      { term: "setting", definition: "where and when the story happens" },
      { term: "event", definition: "something that happens in the story" },
      { term: "detail", definition: "a small piece of information from the text" },
    ],
    prior_skills: ["Retell a familiar story", "Name the main character", "Answer who and where questions"],
    prior_standards: [{ code: "RL.K.3", text: "Identify characters, settings, and major events with prompting" }],
    future_standards: [{ code: "RL.2.5", text: "Describe the overall structure of a story" }],
    challenges: [
      { problem: "Every event is treated as major", fix: "Ask whether the story still works if you remove it" },
      { problem: "Descriptions have no supporting detail", fix: "Require 'I know because the book says…'" },
    ],
    mastery_statement: "Student can describe characters, setting and major events using specific details from the text.",
    ladder: [
      { name: "I can name the characters", descriptor: "Identifies who is in the story" },
      { name: "I can tell where the story happens", descriptor: "Names the setting" },
      { name: "I can tell the big things that happen", descriptor: "Selects major over minor events" },
      { name: "I can add details from the book", descriptor: "Supports description with text detail" },
    ],
  },
  {
    standard_code: "RI.2.5",
    verbs: [
      { word: "Know", gloss: "recognize each text feature and its job" },
      { word: "Use", gloss: "actually go to it to find information" },
      { word: "Locate", gloss: "find a fact quickly" },
    ],
    concepts: ["Text features", "Efficient searching", "Nonfiction structure"],
    vocabulary: [
      { term: "heading", definition: "the title of a section that tells you what it is about" },
      { term: "caption", definition: "words under a picture that explain it" },
      { term: "glossary", definition: "a list at the back that tells you what words mean" },
      { term: "index", definition: "a list at the back that tells you what page things are on" },
    ],
    prior_skills: ["Identify a title", "Read a picture", "Recognize bold print"],
    prior_standards: [{ code: "RI.1.5", text: "Know and use text features to locate key facts" }],
    future_standards: [{ code: "RI.3.5", text: "Use text features and search tools to locate information efficiently" }],
    challenges: [
      { problem: "Students read start to finish instead of searching", fix: "Time the task so scanning beats reading" },
      { problem: "Index and glossary get confused", fix: "Sort questions by which tool answers them" },
    ],
    mastery_statement: "Student can choose the right text feature and use it to locate a specific fact quickly.",
    ladder: [
      { name: "I can name the text features", descriptor: "Identifies heading, caption, glossary, index" },
      { name: "I can say what each one is for", descriptor: "Matches feature to purpose" },
      { name: "I can use one to find a fact", descriptor: "Locates information via a feature" },
      { name: "I can pick the fastest one for the job", descriptor: "Selects efficiently under time" },
    ],
  },
  {
    standard_code: "W.3.3",
    verbs: [
      { word: "Write", gloss: "produce a narrative piece" },
      { word: "Develop", gloss: "build the experience out with detail" },
      { word: "Sequence", gloss: "put events in a clear order" },
    ],
    concepts: ["Event sequence", "Descriptive detail", "Narrative technique"],
    vocabulary: [
      { term: "narrative", definition: "a piece of writing that tells a story" },
      { term: "sequence", definition: "the order things happen in" },
      { term: "transition word", definition: "a word like 'next' that moves the story along" },
      { term: "sensory detail", definition: "a detail you can see, hear, smell, taste or feel" },
    ],
    prior_skills: ["Tell a story out loud in order", "Write a complete sentence", "Add one detail to a sentence"],
    prior_standards: [{ code: "W.2.3", text: "Write narratives recounting a well-elaborated event" }],
    future_standards: [{ code: "W.4.3", text: "Write narratives using dialogue and description to develop events" }],
    challenges: [
      { problem: "Stories become 'and then' lists", fix: "Cap the number of events and expand each one" },
      { problem: "No detail beyond plot", fix: "Require one sensory detail per event" },
    ],
    mastery_statement: "Student can write a narrative with a clear ordered sequence and descriptive details that develop the experience.",
    ladder: [
      { name: "I can tell what happened", descriptor: "Records events accurately" },
      { name: "I can put events in order", descriptor: "Uses a clear sequence" },
      { name: "I can add details that show, not tell", descriptor: "Includes sensory detail" },
      { name: "I can use transitions to move the story", descriptor: "Links events smoothly" },
    ],
  },
  {
    standard_code: "RI.4.5",
    verbs: [
      { word: "Describe", gloss: "name the organizational pattern" },
      { word: "Identify", gloss: "spot the signal words that reveal it" },
    ],
    concepts: ["Text structure", "Signal words", "Author's organization"],
    vocabulary: [
      { term: "structure", definition: "the way a text is organized" },
      { term: "signal word", definition: "a word that hints at how the text is organized" },
      { term: "cause and effect", definition: "one thing makes another thing happen" },
      { term: "chronology", definition: "events told in time order" },
    ],
    prior_skills: ["Identify sequence in a text", "Compare two things", "Find a main idea"],
    prior_standards: [{ code: "RI.3.8", text: "Describe the logical connection between sentences and paragraphs" }],
    future_standards: [{ code: "RI.5.5", text: "Compare the overall structure of two or more texts" }],
    challenges: [
      { problem: "Structure is guessed from the topic", fix: "Require two signal words as evidence" },
      { problem: "Texts using two structures cause paralysis", fix: "Analyze by section rather than whole text" },
    ],
    mastery_statement: "Student can name a text's organizational structure and cite the signal words that reveal it.",
    ladder: [
      { name: "I can name the structures", descriptor: "Lists the four common patterns" },
      { name: "I can spot signal words", descriptor: "Identifies because, however, first" },
      { name: "I can name the structure of a text", descriptor: "Matches pattern to passage" },
      { name: "I can prove it with signal words", descriptor: "Cites evidence for the choice" },
    ],
  },
  {
    standard_code: "L.5.5",
    verbs: [
      { word: "Demonstrate", gloss: "show you understand the figurative meaning" },
      { word: "Interpret", gloss: "work out what is really meant" },
      { word: "Distinguish", gloss: "tell close meanings apart" },
    ],
    concepts: ["Figurative vs literal", "Word relationships", "Shades of meaning"],
    vocabulary: [
      { term: "simile", definition: "a comparison using like or as" },
      { term: "metaphor", definition: "saying one thing is another to make a point" },
      { term: "idiom", definition: "a phrase that means something other than its words" },
      { term: "nuance", definition: "a small difference in meaning between similar words" },
    ],
    prior_skills: ["Identify a simile", "Use context clues", "Recognize multiple-meaning words"],
    prior_standards: [{ code: "L.4.5", text: "Demonstrate understanding of figurative language and nuances" }],
    future_standards: [{ code: "L.6.5", text: "Interpret figures of speech and analyze word relationships" }],
    challenges: [
      { problem: "Idioms are read literally", fix: "Collect idioms and draw both meanings side by side" },
      { problem: "Simile and metaphor get swapped", fix: "Sort by whether 'like' or 'as' appears" },
    ],
    mastery_statement: "Student can interpret similes, metaphors and idioms and explain shades of difference between related words.",
    ladder: [
      { name: "I can spot figurative language", descriptor: "Notices non-literal phrasing" },
      { name: "I can tell simile from metaphor", descriptor: "Classifies correctly" },
      { name: "I can explain what an idiom means", descriptor: "Gives the figurative meaning" },
      { name: "I can rank words by strength", descriptor: "Orders related words by intensity" },
    ],
  },
  {
    standard_code: "RI.6.5",
    verbs: [
      { word: "Analyze", gloss: "work out what a part is doing" },
      { word: "Explain", gloss: "say how it develops the ideas" },
    ],
    concepts: ["Part-to-whole structure", "Paragraph function", "Idea development"],
    vocabulary: [
      { term: "structure", definition: "how the parts of a text are arranged" },
      { term: "function", definition: "the job a paragraph does for the text" },
      { term: "development", definition: "how an idea is built up across a text" },
      { term: "transition", definition: "a sentence that moves from one idea to the next" },
    ],
    prior_skills: ["Identify text structure", "Find a main idea", "Summarize a section"],
    prior_standards: [{ code: "RI.5.5", text: "Compare the overall structure of two or more texts" }],
    future_standards: [{ code: "RI.7.5", text: "Analyze the structure an author uses to organize a text" }],
    challenges: [
      { problem: "Students summarize the paragraph instead of naming its job", fix: "Ban content words from the answer — describe the function only" },
      { problem: "Every paragraph is called 'supporting detail'", fix: "Build a menu of functions to choose from" },
    ],
    mastery_statement: "Student can explain the function of a specific paragraph and how it contributes to the text's ideas.",
    ladder: [
      { name: "I can summarize a paragraph", descriptor: "States what it says" },
      { name: "I can name the text's structure", descriptor: "Identifies the overall pattern" },
      { name: "I can say what a paragraph is doing", descriptor: "Names its function" },
      { name: "I can explain how it develops the idea", descriptor: "Links part to whole" },
    ],
  },
  {
    standard_code: "W.6.2",
    verbs: [
      { word: "Examine", gloss: "look closely at a topic" },
      { word: "Select", gloss: "choose the information that matters" },
      { word: "Organize", gloss: "group information so it makes sense" },
    ],
    concepts: ["Information selection", "Organization", "Explanation vs opinion"],
    vocabulary: [
      { term: "informative", definition: "writing that explains rather than argues" },
      { term: "relevant", definition: "actually connected to the point you are making" },
      { term: "transition", definition: "a phrase that connects one idea to the next" },
      { term: "concrete detail", definition: "a specific fact, example or number" },
    ],
    prior_skills: ["Write a paragraph with a topic sentence", "Take notes from a source", "Group related facts"],
    prior_standards: [{ code: "W.5.2", text: "Write informative texts to examine a topic" }],
    future_standards: [{ code: "W.7.2", text: "Write informative texts with well-organized analysis" }],
    challenges: [
      { problem: "Everything found gets included", fix: "Force a cut — half the notes must go before drafting" },
      { problem: "Opinion creeps into explanation", fix: "Highlight evaluative words and remove them" },
    ],
    mastery_statement: "Student can write an informative text that selects relevant information and organizes it coherently.",
    ladder: [
      { name: "I can gather facts on a topic", descriptor: "Collects information" },
      { name: "I can choose which facts matter", descriptor: "Cuts irrelevant material" },
      { name: "I can group facts into sections", descriptor: "Organizes logically" },
      { name: "I can connect sections with transitions", descriptor: "Produces a coherent whole" },
    ],
  },
  {
    standard_code: "RL.8.3",
    verbs: [
      { word: "Analyze", gloss: "examine what a moment does" },
      { word: "Propel", gloss: "push the action forward" },
      { word: "Reveal", gloss: "show something about a character" },
    ],
    concepts: ["Turning points", "Characterisation through action", "Causality"],
    vocabulary: [
      { term: "dialogue", definition: "the words characters say to each other" },
      { term: "incident", definition: "a single event in the story" },
      { term: "propel", definition: "push the story forward" },
      { term: "provoke", definition: "cause someone to act or decide" },
    ],
    prior_skills: ["Track character change", "Identify plot events", "Cite textual evidence"],
    prior_standards: [{ code: "RL.7.3", text: "Analyze how story elements interact" }],
    future_standards: [{ code: "RL.9-10.3", text: "Analyze how complex characters develop and advance the plot" }],
    challenges: [
      { problem: "Students retell the moment rather than analyze it", fix: "Require the answer to start with 'this moment causes…'" },
      { problem: "Any moment is claimed as a turning point", fix: "Test by asking what changes because of it" },
    ],
    mastery_statement: "Student can analyze how a specific line or incident advances the plot, reveals character, or forces a decision.",
    ladder: [
      { name: "I can find an important moment", descriptor: "Selects a significant incident" },
      { name: "I can say what happens because of it", descriptor: "Identifies consequence" },
      { name: "I can say what it shows about a character", descriptor: "Draws characterisation from action" },
      { name: "I can explain its role in the whole story", descriptor: "Connects moment to arc" },
    ],
  },
  {
    standard_code: "W.8.1",
    verbs: [
      { word: "Support", gloss: "back the claim with evidence" },
      { word: "Acknowledge", gloss: "admit the other side exists" },
      { word: "Distinguish", gloss: "keep your claim separate from theirs" },
    ],
    concepts: ["Claim and counterclaim", "Relevant evidence", "Rebuttal"],
    vocabulary: [
      { term: "claim", definition: "the position you are arguing for" },
      { term: "counterclaim", definition: "the strongest argument against your position" },
      { term: "rebuttal", definition: "your response to the counterclaim" },
      { term: "relevant", definition: "actually supporting the claim you made" },
    ],
    prior_skills: ["State a claim", "Support with reasons", "Cite evidence"],
    prior_standards: [{ code: "W.7.1", text: "Write arguments supporting claims with reasons and evidence" }],
    future_standards: [{ code: "W.9-10.1", text: "Write arguments with precise claims and thorough counterclaim development" }],
    challenges: [
      { problem: "The counterclaim is a straw man", fix: "Require the strongest version, sourced from an actual opponent" },
      { problem: "Evidence is relevant to the topic but not the claim", fix: "Test each piece against the claim, not the subject" },
    ],
    mastery_statement: "Student can argue a claim with relevant evidence and fairly acknowledge and answer a counterclaim.",
    ladder: [
      { name: "I can state a clear claim", descriptor: "Writes an arguable position" },
      { name: "I can support it with evidence", descriptor: "Supplies relevant support" },
      { name: "I can name the other side fairly", descriptor: "States a genuine counterclaim" },
      { name: "I can answer the counterclaim", descriptor: "Rebuts without dismissing" },
    ],
  },
  {
    standard_code: "K.OA.A.1",
    verbs: [
      { word: "Represent", gloss: "show the maths in some form" },
      { word: "Act out", gloss: "physically do the situation" },
    ],
    concepts: ["Joining", "Separating", "Multiple representations"],
    vocabulary: [
      { term: "add", definition: "put groups together" },
      { term: "subtract", definition: "take some away" },
      { term: "altogether", definition: "how many when you put them together" },
      { term: "equation", definition: "a number sentence with an equals sign" },
    ],
    prior_skills: ["Count objects accurately", "Compare two groups", "Recognize numerals"],
    prior_standards: [{ code: "PK.OA.1", text: "Explore adding and subtracting with objects" }],
    future_standards: [{ code: "1.OA.A.1", text: "Solve addition and subtraction word problems within 20" }],
    challenges: [
      { problem: "Counting restarts from one every time", fix: "Model counting on from the larger group" },
      { problem: "Drawings do not match the story", fix: "Act it out with objects before drawing" },
    ],
    mastery_statement: "Student can represent an addition or subtraction situation with objects, a drawing, or an equation.",
    ladder: [
      { name: "I can act out the story", descriptor: "Uses objects to model" },
      { name: "I can draw what happened", descriptor: "Produces a matching drawing" },
      { name: "I can say the answer", descriptor: "Counts the result accurately" },
      { name: "I can write it as an equation", descriptor: "Connects situation to symbols" },
    ],
  },
  {
    standard_code: "1.NBT.B.2",
    verbs: [
      { word: "Understand", gloss: "know what each digit is worth" },
      { word: "Bundle", gloss: "group ten ones into one ten" },
    ],
    concepts: ["Unitizing", "Tens and ones", "Bundling"],
    vocabulary: [
      { term: "ten", definition: "a bundle of ten ones treated as one thing" },
      { term: "one", definition: "a single unit" },
      { term: "digit", definition: "one of the symbols 0 to 9" },
      { term: "bundle", definition: "a group put together and counted as one" },
    ],
    prior_skills: ["Count to 100", "Count groups of ten", "Recognize two-digit numerals"],
    prior_standards: [{ code: "K.NBT.A.1", text: "Compose and decompose numbers 11 to 19 into tens and ones" }],
    future_standards: [{ code: "2.NBT.A.1", text: "Understand three-digit place value" }],
    challenges: [
      { problem: "Both digits are read as ones", fix: "Build with bundled straws before writing numerals" },
      { problem: "Teen numbers are reversed", fix: "Say the number while pointing at the tens bundle first" },
    ],
    mastery_statement: "Student can say how many tens and ones make a two-digit number and build it accordingly.",
    ladder: [
      { name: "I can count by tens", descriptor: "Skip counts accurately" },
      { name: "I can make a bundle of ten", descriptor: "Groups ten ones as one ten" },
      { name: "I can say the tens and ones", descriptor: "Decomposes a two-digit number" },
      { name: "I can build any two-digit number", descriptor: "Composes from tens and ones" },
    ],
  },
  {
    standard_code: "2.OA.B.2",
    verbs: [
      { word: "Add", gloss: "combine two numbers" },
      { word: "Subtract", gloss: "find the difference" },
      { word: "Recall", gloss: "know it without working it out" },
    ],
    concepts: ["Fact fluency", "Mental strategies", "Automaticity"],
    vocabulary: [
      { term: "fluent", definition: "quick and accurate without counting every time" },
      { term: "double", definition: "adding a number to itself" },
      { term: "make a ten", definition: "a strategy that builds to ten first" },
      { term: "near double", definition: "a fact one away from a double you know" },
    ],
    prior_skills: ["Add within 10", "Count on from a number", "Know pairs that make ten"],
    prior_standards: [{ code: "1.OA.C.6", text: "Add and subtract within 20 using strategies" }],
    future_standards: [{ code: "3.OA.C.7", text: "Fluently multiply and divide within 100" }],
    challenges: [
      { problem: "Finger counting persists past the point of usefulness", fix: "Time short sets so counting becomes too slow" },
      { problem: "Strategies are known but not chosen", fix: "Ask which strategy fits before solving" },
    ],
    mastery_statement: "Student can add and subtract within 20 fluently, recalling single-digit sums from memory.",
    ladder: [
      { name: "I can add within 10 quickly", descriptor: "Recalls small sums" },
      { name: "I can use doubles", descriptor: "Applies doubles and near doubles" },
      { name: "I can make a ten to add", descriptor: "Uses bridging through ten" },
      { name: "I know my facts from memory", descriptor: "Recalls without strategy" },
    ],
  },
  {
    standard_code: "3.NF.A.3",
    verbs: [
      { word: "Explain", gloss: "say why two fractions are equal" },
      { word: "Compare", gloss: "decide which is larger" },
      { word: "Reason", gloss: "think about size rather than apply a rule" },
    ],
    concepts: ["Equivalence", "Same whole", "Comparison"],
    vocabulary: [
      { term: "equivalent", definition: "the same amount written differently" },
      { term: "the whole", definition: "the thing the fraction is part of" },
      { term: "compare", definition: "decide which is bigger or smaller" },
      { term: "benchmark", definition: "a fraction like 1/2 you compare others against" },
    ],
    prior_skills: ["Name unit fractions", "Partition shapes equally", "Place fractions on a number line"],
    prior_standards: [{ code: "3.NF.A.1", text: "Understand a fraction as parts of a whole" }],
    future_standards: [{ code: "4.NF.A.1", text: "Explain fraction equivalence using visual models" }],
    challenges: [
      { problem: "Bigger denominator is read as bigger fraction", fix: "Compare 1/3 and 1/8 with strips of the same whole" },
      { problem: "Fractions of different wholes are compared", fix: "Show 1/2 of a small and large circle side by side" },
    ],
    mastery_statement: "Student can justify fraction equivalence and compare fractions by reasoning about size within the same whole.",
    ladder: [
      { name: "I can name a fraction", descriptor: "Reads fractions accurately" },
      { name: "I can show two fractions that are equal", descriptor: "Demonstrates equivalence with a model" },
      { name: "I can compare fractions with the same denominator", descriptor: "Compares by numerator" },
      { name: "I can compare any two fractions and say why", descriptor: "Reasons about size" },
    ],
  },
  {
    standard_code: "4.NF.B.3",
    verbs: [
      { word: "Decompose", gloss: "break a fraction into unit fractions" },
      { word: "Add", gloss: "combine fractions of the same size" },
      { word: "Subtract", gloss: "take one fraction from another" },
    ],
    concepts: ["Unit fraction addition", "Decomposition", "Mixed numbers"],
    vocabulary: [
      { term: "unit fraction", definition: "a fraction with 1 on top" },
      { term: "decompose", definition: "break a fraction into smaller fractions" },
      { term: "mixed number", definition: "a whole number and a fraction together" },
      { term: "improper fraction", definition: "a fraction where the top is bigger than the bottom" },
    ],
    prior_skills: ["Understand unit fractions", "Compare fractions", "Find equivalent fractions"],
    prior_standards: [{ code: "3.NF.A.1", text: "Understand a fraction as parts of a whole" }],
    future_standards: [{ code: "5.NF.A.1", text: "Add and subtract fractions with unlike denominators" }],
    challenges: [
      { problem: "Denominators get added along with numerators", fix: "Say the denominator as the piece name — 3 fifths plus 1 fifth is 4 fifths" },
      { problem: "Regrouping mixed numbers stalls", fix: "Convert to improper fractions first" },
    ],
    mastery_statement: "Student can add and subtract like-denominator fractions and mixed numbers by counting unit fractions.",
    ladder: [
      { name: "I can break a fraction into unit fractions", descriptor: "3/4 as 1/4 + 1/4 + 1/4" },
      { name: "I can add fractions with the same denominator", descriptor: "Adds numerators only" },
      { name: "I can subtract them", descriptor: "Subtracts within the same whole" },
      { name: "I can handle mixed numbers", descriptor: "Regroups when needed" },
    ],
  },
  {
    standard_code: "5.NBT.A.1",
    verbs: [
      { word: "Recognize", gloss: "see the ten-times pattern between places" },
      { word: "Explain", gloss: "say why each place relates to its neighbours" },
    ],
    concepts: ["Place value relationships", "Decimals", "Powers of ten"],
    vocabulary: [
      { term: "place value", definition: "what a digit is worth because of where it sits" },
      { term: "tenth", definition: "one of ten equal parts of a whole" },
      { term: "ten times", definition: "multiplied by ten" },
      { term: "decimal point", definition: "the dot separating whole numbers from parts" },
    ],
    prior_skills: ["Understand whole-number place value", "Multiply and divide by 10", "Read decimals to hundredths"],
    prior_standards: [{ code: "4.NBT.A.1", text: "Recognize that a digit represents ten times the place to its right" }],
    future_standards: [{ code: "5.NBT.A.2", text: "Explain patterns when multiplying and dividing by powers of ten" }],
    challenges: [
      { problem: "The pattern is learned only left to right", fix: "Ask the one-tenth question as often as the ten-times one" },
      { problem: "Decimal places are read as whole numbers", fix: "Use a place value chart that crosses the decimal point" },
    ],
    mastery_statement: "Student can explain that each place is ten times the place to its right and one tenth of the place to its left.",
    ladder: [
      { name: "I can name each place", descriptor: "Reads places including decimals" },
      { name: "I can say what a digit is worth", descriptor: "States value in context" },
      { name: "I can explain the ten-times pattern", descriptor: "Relates a place to its right" },
      { name: "I can explain it both directions", descriptor: "Handles one-tenth relationships" },
    ],
  },
  {
    standard_code: "6.NS.A.1",
    verbs: [
      { word: "Interpret", gloss: "say what dividing fractions means" },
      { word: "Compute", gloss: "find the quotient" },
      { word: "Solve", gloss: "answer a real problem" },
    ],
    concepts: ["Measurement division", "Reciprocals", "Fraction models"],
    vocabulary: [
      { term: "quotient", definition: "the answer to a division" },
      { term: "reciprocal", definition: "a fraction flipped upside down" },
      { term: "divisor", definition: "the number you are dividing by" },
      { term: "measurement division", definition: "asking how many of one thing fit in another" },
    ],
    prior_skills: ["Multiply fractions", "Find equivalent fractions", "Model fractions visually"],
    prior_standards: [{ code: "5.NF.B.7", text: "Divide unit fractions by whole numbers and vice versa" }],
    future_standards: [{ code: "7.NS.A.2", text: "Multiply and divide rational numbers" }],
    challenges: [
      { problem: "Invert-and-multiply is applied without meaning", fix: "Model 'how many halves fit in three' before the rule" },
      { problem: "The wrong fraction gets inverted", fix: "Say the question aloud: how many divisors fit in the dividend" },
    ],
    mastery_statement: "Student can compute and interpret quotients of fractions, explaining the result with a model.",
    ladder: [
      { name: "I can multiply fractions", descriptor: "Computes products correctly" },
      { name: "I can model how many fit", descriptor: "Uses a visual fraction model" },
      { name: "I can divide fractions", descriptor: "Computes quotients" },
      { name: "I can explain why it works", descriptor: "Connects the rule to the model" },
    ],
  },
  {
    standard_code: "7.RP.A.2",
    verbs: [
      { word: "Recognize", gloss: "tell whether a relationship is proportional" },
      { word: "Represent", gloss: "show it as a table, graph or equation" },
      { word: "Identify", gloss: "find the constant of proportionality" },
    ],
    concepts: ["Proportionality", "Constant of proportionality", "Multiple representations"],
    vocabulary: [
      { term: "proportional", definition: "two quantities that always change by the same multiple" },
      { term: "constant of proportionality", definition: "the number you always multiply by" },
      { term: "origin", definition: "the point (0, 0) on a graph" },
      { term: "unit rate", definition: "how much for exactly one" },
    ],
    prior_skills: ["Find unit rates", "Build ratio tables", "Plot points on a graph"],
    prior_standards: [{ code: "6.RP.A.3", text: "Use ratio reasoning to solve problems" }],
    future_standards: [{ code: "8.EE.B.5", text: "Graph proportional relationships and interpret slope" }],
    challenges: [
      { problem: "Any straight line is called proportional", fix: "Test whether it passes through the origin" },
      { problem: "The constant is found in a table but not a graph", fix: "Locate the point where x is 1 on both" },
    ],
    mastery_statement: "Student can determine whether a relationship is proportional and identify its constant in any representation.",
    ladder: [
      { name: "I can find a unit rate", descriptor: "Divides to get per-one" },
      { name: "I can test a table for proportionality", descriptor: "Checks a constant multiple" },
      { name: "I can spot it on a graph", descriptor: "Checks straight line through origin" },
      { name: "I can write the equation", descriptor: "Produces y = kx with the right k" },
    ],
  },
  {
    standard_code: "7.NS.A.1",
    verbs: [
      { word: "Add", gloss: "combine rational numbers" },
      { word: "Subtract", gloss: "find the difference" },
      { word: "Represent", gloss: "show the move on a number line" },
    ],
    concepts: ["Additive inverse", "Number line movement", "Absolute value"],
    vocabulary: [
      { term: "rational number", definition: "any number that can be written as a fraction" },
      { term: "additive inverse", definition: "the number that adds with it to make zero" },
      { term: "absolute value", definition: "how far a number is from zero" },
      { term: "opposite", definition: "the same distance from zero on the other side" },
    ],
    prior_skills: ["Order integers", "Plot on a number line", "Understand absolute value"],
    prior_standards: [{ code: "6.NS.C.6", text: "Understand positive and negative numbers on a number line" }],
    future_standards: [{ code: "7.NS.A.2", text: "Multiply and divide rational numbers" }],
    challenges: [
      { problem: "Subtracting a negative is read as subtracting", fix: "Rewrite every subtraction as adding the opposite" },
      { problem: "Signs are decided by rule rather than reasoning", fix: "Model each on a number line before computing" },
    ],
    mastery_statement: "Student can add and subtract rational numbers and justify the result on a number line.",
    ladder: [
      { name: "I can order positive and negative numbers", descriptor: "Places them correctly" },
      { name: "I can add on a number line", descriptor: "Models the movement" },
      { name: "I can rewrite subtraction as adding the opposite", descriptor: "Applies the transformation" },
      { name: "I can add and subtract any rational numbers", descriptor: "Handles fractions and decimals too" },
    ],
  },
  {
    standard_code: "8.G.B.7",
    verbs: [
      { word: "Apply", gloss: "use the theorem to find a side" },
      { word: "Determine", gloss: "work out the unknown length" },
    ],
    concepts: ["Right triangles", "Hypotenuse identification", "Square roots"],
    vocabulary: [
      { term: "hypotenuse", definition: "the longest side, opposite the right angle" },
      { term: "leg", definition: "one of the two shorter sides of a right triangle" },
      { term: "square root", definition: "the number that multiplies by itself to give this" },
      { term: "right angle", definition: "a 90 degree corner" },
    ],
    prior_skills: ["Find squares and square roots", "Identify right angles", "Solve simple equations"],
    prior_standards: [{ code: "8.G.B.6", text: "Explain a proof of the Pythagorean Theorem" }],
    future_standards: [{ code: "G-SRT.8", text: "Use trigonometric ratios to solve right triangles" }],
    challenges: [
      { problem: "A leg is treated as the hypotenuse", fix: "Mark the right angle and its opposite side before substituting" },
      { problem: "The theorem is applied to non-right triangles", fix: "Include non-right triangles in practice sets" },
    ],
    mastery_statement: "Student can find an unknown side of a right triangle and recognize when the theorem does not apply.",
    ladder: [
      { name: "I can find squares and square roots", descriptor: "Computes accurately" },
      { name: "I can identify the hypotenuse", descriptor: "Locates the side opposite the right angle" },
      { name: "I can find the hypotenuse", descriptor: "Applies a² + b² = c²" },
      { name: "I can find a missing leg", descriptor: "Rearranges the theorem" },
    ],
  },
];

const blueprintsData = [
  {
    standard_code: "RF.K.1",
    title: "How Books Work",
    badge: "Kindergarten",
    route_name: "Shared Reading",
    route_line: "Model with a big book → Track together → Point it out yourself",
    success_criteria: ["Tracks print left to right with a return sweep", "Points to one word when asked", "Shows where a sentence starts and ends"],
    steps: [
      { name: "Retrieve Book Handling", minutes: 5, body: "Hand out books upside down and backwards. Students fix them. Fast, physical, and it surfaces who is still unsure.", science_tag: "retrieval" },
      { name: "Model Tracking", minutes: 8, body: "Big book, pointer. Read slowly, touching each word. Exaggerate the return sweep so the move is impossible to miss.", science_tag: "dual-coding" },
      { name: "Letter, Word, Sentence", minutes: 10, body: "Use a finger window to frame one letter, then one word, then a whole sentence. Name each. The framing is what separates them.", science_tag: "dual-coding" },
      { name: "Track Together", minutes: 10, body: "Whole class points along on their own copies while you read. Circulate and watch fingers, not faces.", science_tag: "collaborative" },
      { name: "Find the Spaces", minutes: 8, body: "Students place a counter in each space between words on one line. Counting the gaps makes word boundaries concrete.", science_tag: "elaboration" },
      { name: "Partner Pointing", minutes: 10, body: "Partners take turns pointing while the other reads a familiar line from memory. Both jobs matter.", science_tag: "collaborative" },
      { name: "Show Me Check", minutes: 6, body: "One at a time: show me a letter, a word, where we start. Note who hesitates.", science_tag: "spaced" },
    ],
    ef_supports: ["Pointers for tracking", "Finger windows for framing", "Counters for spaces", "Familiar text so decoding is not competing"],
    tech: "Big book and individual copies",
    tech_purpose: "Shared visual so modelling transfers directly",
    ai_prompts: ["Generate a repetitive kindergarten shared reading text", "List show-me prompts for print concepts assessment"],
    assessment: ["Watch fingers during tracking", "Individual show-me check", "Note return sweep accuracy"],
    why_it_works: ["Print concepts are invisible until someone frames them", "Counting spaces makes word boundaries countable", "Familiar text frees attention for the print itself", "Physical pointing externalises the tracking skill"],
  },
  {
    standard_code: "RL.1.3",
    title: "Who, Where, What Happened",
    badge: "Grade 1",
    route_name: "Explicit Instruction",
    route_line: "Name the elements → Find them in a story → Describe with details",
    success_criteria: ["Names the characters and setting", "Selects major events over minor ones", "Adds a detail from the text to each description"],
    steps: [
      { name: "Retrieve a Known Story", minutes: 5, body: "Yesterday's story: who was in it? Where? Quick oral retrieval before new work.", science_tag: "retrieval" },
      { name: "Name the Three Elements", minutes: 8, body: "Character, setting, events. Anchor chart with an icon for each. Keep it visible all lesson.", science_tag: "dual-coding" },
      { name: "Read and Sort", minutes: 12, body: "Read a short story. Stop three times. Students say which element they just heard about and drop a card in that pile.", science_tag: "collaborative" },
      { name: "Big or Small", minutes: 10, body: "List six events. Which are major? Test each: does the story still work without it? The test is the teaching.", science_tag: "elaboration" },
      { name: "Add the Detail", minutes: 12, body: "Describing is not naming. Model 'the wolf' versus 'the hungry wolf who could not climb'. Students upgrade three descriptions.", science_tag: "elaboration" },
      { name: "Draw and Label", minutes: 8, body: "Students draw the setting and label it with two details from the text. Drawing forces specificity.", science_tag: "dual-coding" },
      { name: "Retell to a Partner", minutes: 5, body: "Retell using all three elements. The listener checks each is present.", science_tag: "spaced" },
    ],
    ef_supports: ["Element anchor chart with icons", "Sorting cards", "Sentence frame for adding detail", "Draw-before-write option"],
    tech: "Printed story and sorting cards",
    tech_purpose: "Let students sort elements physically",
    ai_prompts: ["Write a grade 1 story with a clear setting and three major events", "Generate a mix of major and minor events for sorting"],
    assessment: ["Check sorting accuracy during reading", "Review upgraded descriptions for detail", "Listen to partner retells for all three elements"],
    why_it_works: ["The remove-it test makes 'major' a decidable question", "Upgrading descriptions targets the actual verb in the standard", "Drawing the setting forces detail students would otherwise skip", "Icons let non-readers hold the categories"],
  },
  {
    standard_code: "RI.2.5",
    title: "Finding It Fast: Text Features",
    badge: "Grade 2",
    route_name: "Strategy Instruction",
    route_line: "Name each feature → Match it to its job → Race to find facts",
    success_criteria: ["Names heading, caption, glossary and index", "Says what each one is for", "Uses the right one to find a fact quickly"],
    steps: [
      { name: "Retrieve What We Know", minutes: 5, body: "Flip through a nonfiction book. What do you notice that a storybook does not have? Collect answers.", science_tag: "retrieval" },
      { name: "Feature Tour", minutes: 10, body: "Name each feature and its job, one at a time, pointing at a real example. Job first, name second — the job is what they will remember.", science_tag: "dual-coding" },
      { name: "Match Feature to Job", minutes: 10, body: "Cards: feature names and job descriptions. Students match. Index and glossary will get swapped — that is the useful moment.", science_tag: "elaboration" },
      { name: "Which Tool for Which Question", minutes: 12, body: "Give questions, students name the feature that answers each fastest. No reading yet, just tool selection.", science_tag: "interleaving" },
      { name: "Fact Race", minutes: 12, body: "Timed. Five questions, real book. Speed is the point — it makes scanning beat reading cover to cover.", science_tag: "collaborative" },
      { name: "Explain Your Route", minutes: 6, body: "Students share how they found one fact. Compare routes — some were faster and it is worth naming why.", science_tag: "elaboration" },
      { name: "Exit Question", minutes: 5, body: "One fact to find, one sentence on which feature you used.", science_tag: "spaced" },
    ],
    ef_supports: ["Feature and job matching cards", "Nonfiction books with all features present", "Timer to make scanning worthwhile", "Anchor chart of features"],
    tech: "Nonfiction books plus matching cards",
    tech_purpose: "Real texts, since the features must exist to be used",
    ai_prompts: ["Generate questions answerable by different text features", "Create feature-to-purpose matching cards"],
    assessment: ["Check matching accuracy, especially index vs glossary", "Time the fact race", "Exit ticket names the feature used"],
    why_it_works: ["Timing is what stops cover-to-cover reading", "Teaching the job before the name makes the feature useful, not vocabulary", "Comparing routes surfaces efficiency as a skill", "Index/glossary confusion is predictable, so plan for it"],
  },
  {
    standard_code: "W.3.3",
    title: "Small Moment, Big Detail",
    badge: "Grade 3",
    route_name: "Writing Workshop",
    route_line: "Shrink the moment → Sequence it → Fill it with detail",
    success_criteria: ["Writes about one small moment, not a whole day", "Puts events in clear order with transitions", "Includes sensory detail in each event"],
    steps: [
      { name: "Retrieve Sequence Words", minutes: 5, body: "First, next, then, finally, meanwhile. Quick recall before drafting needs them.", science_tag: "retrieval" },
      { name: "Watermelon and Seed", minutes: 10, body: "Show a whole-day story versus one moment stretched out. Students name which they would rather read. Shrink the topic before writing anything.", science_tag: "elaboration" },
      { name: "Plan the Sequence", minutes: 10, body: "Three or four boxes, one event each. Cap it. The cap is what forces stretching rather than listing.", science_tag: "dual-coding" },
      { name: "Show Not Tell", minutes: 12, body: "'I was scared' becomes 'my hands would not stop shaking'. Students convert three telling sentences to showing ones.", science_tag: "elaboration" },
      { name: "Add a Sense to Each Box", minutes: 10, body: "One sensory detail per event. Students go back through the plan and add before drafting a word of prose.", science_tag: "interleaving" },
      { name: "Draft the Middle", minutes: 12, body: "Draft the two strongest boxes in full. Openings are easier once the middle exists.", science_tag: "collaborative" },
      { name: "Read One Aloud", minutes: 6, body: "Two students read a showing sentence. Class names what they could picture.", science_tag: "spaced" },
    ],
    ef_supports: ["Four-box sequence planner", "Transition word bank", "Show-not-tell conversion examples", "Draft the middle, not the opening"],
    tech: "Printed planners",
    tech_purpose: "Hold the sequence while detail work happens",
    ai_prompts: ["Generate small-moment narrative prompts for grade 3", "Write telling sentences for students to convert to showing"],
    assessment: ["Check the topic is genuinely small", "Confirm one sensory detail per box", "Listen to read-alouds for picturable writing"],
    why_it_works: ["Shrinking the topic is what prevents 'and then' lists", "Capping events forces depth over breadth", "Converting telling to showing is a concrete, teachable move", "Drafting the middle first avoids the blank-opening stall"],
  },
  {
    standard_code: "RI.4.5",
    title: "How the Text Is Built",
    badge: "Grade 4",
    route_name: "Explicit Instruction",
    route_line: "Learn the patterns → Hunt signal words → Name the structure",
    success_criteria: ["Names the four common structures", "Finds signal words in a passage", "Names a text's structure and cites two signals as proof"],
    steps: [
      { name: "Retrieve Text Features", minutes: 5, body: "Quick recall of nonfiction features. Structure is the next layer up, so confirm the layer below.", science_tag: "retrieval" },
      { name: "Four Patterns", minutes: 10, body: "Chronology, compare/contrast, cause/effect, problem/solution. One graphic organizer shape per pattern — the shape is the memory hook.", science_tag: "dual-coding" },
      { name: "Signal Word Hunt", minutes: 10, body: "Sort signal words by pattern. Because, however, first, as a result. Students build the reference they will use next.", science_tag: "elaboration" },
      { name: "Name That Structure", minutes: 12, body: "Four short passages. Students name the structure and underline two signals. Two signals, not one — one can be coincidence.", science_tag: "interleaving" },
      { name: "The Mixed Passage", minutes: 10, body: "A text using two structures. Students analyze by section rather than forcing one label. This is what real texts do.", science_tag: "elaboration" },
      { name: "Map It", minutes: 10, body: "Students fill the matching graphic organizer for one passage. The organizer only fits if the structure was named right.", science_tag: "dual-coding" },
      { name: "Defend a Label", minutes: 5, body: "One student names a structure and cites signals. Class checks the evidence holds.", science_tag: "spaced" },
    ],
    ef_supports: ["Graphic organizer per structure", "Signal word reference chart", "Passages short enough to analyze whole", "Section-by-section option for mixed texts"],
    tech: "Printed passages and organizers",
    tech_purpose: "The organizer shape makes structure visible",
    ai_prompts: ["Write four short passages, one per text structure", "Generate a signal word sort by organizational pattern"],
    assessment: ["Require two signal words per label", "Check organizer fits the named structure", "Listen to the defence for evidence-based reasoning"],
    why_it_works: ["A distinct organizer shape per pattern gives structure a visual identity", "Requiring two signals stops topic-based guessing", "The mixed passage prevents a false one-label-per-text rule", "Filling the organizer self-checks the label"],
  },
  {
    standard_code: "L.5.5",
    title: "When Words Do Not Mean What They Say",
    badge: "Grade 5",
    route_name: "Strategy Instruction",
    route_line: "Spot the non-literal → Name the type → Say what it means",
    success_criteria: ["Notices figurative language in a text", "Distinguishes simile, metaphor and idiom", "States the intended meaning in plain words"],
    steps: [
      { name: "Retrieve Context Clues", minutes: 5, body: "Two quick unknown words solved from context. The same noticing skill drives today's work.", science_tag: "retrieval" },
      { name: "Literal Disaster", minutes: 8, body: "Draw 'it is raining cats and dogs' literally. The absurdity teaches the concept faster than a definition does.", science_tag: "dual-coding" },
      { name: "Three Types", minutes: 10, body: "Simile, metaphor, idiom. Sort by test: does it use like or as? Does it say one thing is another? Is it a fixed phrase?", science_tag: "elaboration" },
      { name: "Sort and Translate", minutes: 12, body: "Students classify twelve examples and write the plain meaning beside each. Classification alone is not the standard — translation is.", science_tag: "interleaving" },
      { name: "Shades of Meaning", minutes: 10, body: "Rank related words by intensity: warm, hot, scorching. Nuance is the second half of this standard and usually gets skipped.", science_tag: "elaboration" },
      { name: "Find It in Real Text", minutes: 10, body: "Students hunt figurative language in a passage and explain what each does for the writing.", science_tag: "collaborative" },
      { name: "Explain One", minutes: 5, body: "Two students explain an idiom's meaning and why it is not literal.", science_tag: "spaced" },
    ],
    ef_supports: ["Type-identification test chart", "Sorting cards with examples", "Intensity ranking lines", "Literal drawings as anchors"],
    tech: "Printed sorting cards",
    tech_purpose: "Classification as a physical, revisable act",
    ai_prompts: ["Generate similes, metaphors and idioms for sorting", "Create word sets to rank by intensity"],
    assessment: ["Check classification accuracy", "Require a plain-language translation for each", "Review intensity rankings"],
    why_it_works: ["Literal drawings make the non-literal nature undeniable", "A test per type gives a decision procedure, not just definitions", "Translation is the actual comprehension demand", "Nuance work covers the half of the standard usually dropped"],
  },
  {
    standard_code: "RI.6.5",
    title: "What Is This Paragraph Doing?",
    badge: "Grade 6",
    route_name: "Analytical Reading",
    route_line: "Map the whole → Name each part's job → Explain the contribution",
    success_criteria: ["Maps the overall structure of a text", "Names a paragraph's function rather than summarising it", "Explains how the part develops the whole"],
    steps: [
      { name: "Retrieve Text Structures", minutes: 5, body: "Name the organizational patterns from memory. This standard sits on top of them.", science_tag: "retrieval" },
      { name: "Summary Is Not Function", minutes: 10, body: "Show a paragraph. Give a summary answer and a function answer side by side. Students name the difference. This distinction is the whole lesson.", science_tag: "elaboration" },
      { name: "Build a Function Menu", minutes: 10, body: "Introduces, gives evidence, counters, transitions, concludes. Chart it. A menu makes 'what is it doing' answerable.", science_tag: "dual-coding" },
      { name: "Map the Text", minutes: 12, body: "One box per paragraph. Students write the function only — content words banned. The ban forces the shift.", science_tag: "dual-coding" },
      { name: "Remove a Paragraph", minutes: 10, body: "What breaks if this paragraph goes? The damage reveals the contribution better than describing it does.", science_tag: "elaboration" },
      { name: "Write the Analysis", minutes: 10, body: "One paragraph: name its function and explain what it contributes to the text's ideas.", science_tag: "interleaving" },
      { name: "Compare Two Maps", minutes: 5, body: "Two students share their function maps. Discuss any paragraph they labelled differently.", science_tag: "spaced" },
    ],
    ef_supports: ["Function menu chart", "One-box-per-paragraph map", "Content-word ban as a forcing device", "Side-by-side summary and function models"],
    tech: "Printed article with numbered paragraphs",
    tech_purpose: "Paragraph-level reference for mapping",
    ai_prompts: ["Write a grade 6 article with clearly distinct paragraph functions", "Generate summary and function answers for the same paragraph"],
    assessment: ["Check maps contain functions, not summaries", "Review the removal reasoning", "Read written analyzes for part-to-whole linking"],
    why_it_works: ["Banning content words is what forces function over summary", "The removal test makes contribution concrete", "A function menu turns an open question into a choice", "Disagreements between maps are where the analysis deepens"],
  },
  {
    standard_code: "W.6.2",
    title: "Explaining Without Arguing",
    badge: "Grade 6",
    route_name: "Writing Workshop",
    route_line: "Gather → Cut hard → Organize and connect",
    success_criteria: ["Selects information relevant to the focus", "Groups related information into sections", "Explains without slipping into opinion"],
    steps: [
      { name: "Retrieve Paragraph Structure", minutes: 5, body: "Topic sentence, supporting detail, closing. Quick recall before scaling up to a whole piece.", science_tag: "retrieval" },
      { name: "Explain vs Argue", minutes: 8, body: "Two paragraphs on one topic, one informative and one persuasive. Students highlight the words that make the difference.", science_tag: "elaboration" },
      { name: "Narrow the Focus", minutes: 10, body: "A broad topic becomes a specific question. Model narrowing three times. Everything downstream depends on this.", science_tag: "dual-coding" },
      { name: "The Hard Cut", minutes: 12, body: "Students have notes. Half must go. Each surviving fact must answer the focus question. Cutting is the selection skill in the standard.", science_tag: "elaboration" },
      { name: "Group into Sections", minutes: 10, body: "Sort surviving facts into three groups and name each. The names become the section headings.", science_tag: "collaborative" },
      { name: "Draft One Section", minutes: 12, body: "Topic sentence, two or three facts, a closing line. One section done properly beats three rushed.", science_tag: "interleaving" },
      { name: "Hunt Opinion Words", minutes: 5, body: "Partners swap and circle any opinion words. Replace them.", science_tag: "spaced" },
    ],
    ef_supports: ["Focus question frame", "Note cards that can be physically sorted", "Opinion word list for the hunt", "Draft one section, not the whole piece"],
    tech: "Note cards",
    tech_purpose: "Make cutting and grouping physical",
    ai_prompts: ["Generate paired informative and persuasive paragraphs on one topic", "List opinion words that creep into informative writing"],
    assessment: ["Check the focus question is narrow enough", "Confirm cut notes were genuinely irrelevant", "Partner hunt catches remaining opinion words"],
    why_it_works: ["Forcing a cut teaches selection, which is named in the standard", "Physical note cards make grouping revisable", "The explain/argue contrast defines the genre boundary", "Narrowing first prevents an unfocused pile of facts"],
  },
  {
    standard_code: "RL.8.3",
    title: "The Moment That Changes Everything",
    badge: "Grade 8",
    route_name: "Analytical Reading",
    route_line: "Find the moment → Test its consequence → Analyze what it reveals",
    success_criteria: ["Selects a genuinely pivotal moment", "Names what changes because of it", "Explains what it reveals about a character"],
    steps: [
      { name: "Retrieve Character Analysis", minutes: 5, body: "How do we learn about characters? Collect: what they say, do, and what others say. Ground the lesson.", science_tag: "retrieval" },
      { name: "Three Jobs", minutes: 8, body: "A moment can propel action, reveal character, or provoke a decision. Often more than one. Chart the three.", science_tag: "dual-coding" },
      { name: "The Consequence Test", minutes: 12, body: "Candidate moments. For each: what changes after it? No change, not pivotal. The test separates important from merely memorable.", science_tag: "elaboration" },
      { name: "Dialogue Under the Microscope", minutes: 12, body: "Take one exchange. What does each line do? Students annotate line by line. Dialogue rewards this scale of attention.", science_tag: "elaboration" },
      { name: "Retell Is Not Analysis", minutes: 8, body: "Show a retell answer and an analysis answer. Students name the difference and rewrite the retell.", science_tag: "interleaving" },
      { name: "Write the Analysis", minutes: 12, body: "One moment, one paragraph: what it does, what changes, what it reveals. Cite the line.", science_tag: "collaborative" },
      { name: "Defend the Choice", minutes: 5, body: "One student argues their moment is the pivotal one. Class tests it with the consequence question.", science_tag: "spaced" },
    ],
    ef_supports: ["Three-jobs anchor chart", "Consequence test frame", "Annotated dialogue example", "Retell vs analysis models"],
    tech: "Printed excerpt with line numbers",
    tech_purpose: "Line-level citation for dialogue analysis",
    ai_prompts: ["Write a dialogue exchange that reveals character and forces a decision", "Generate retell and analysis answers for the same moment"],
    assessment: ["Check moments pass the consequence test", "Confirm writing analyzes rather than retells", "Listen to defences for causal reasoning"],
    why_it_works: ["The consequence test makes 'pivotal' testable rather than felt", "Line-by-line dialogue annotation is where subtext becomes visible", "Retell is the default failure mode, so contrast it explicitly", "Defending a choice forces the causal chain into the open"],
  },
  {
    standard_code: "W.8.1",
    title: "Taking the Other Side Seriously",
    badge: "Grade 8",
    route_name: "Writing Workshop",
    route_line: "Claim and evidence → Steelman the opposition → Rebut fairly",
    success_criteria: ["States an arguable claim", "Supports it with evidence relevant to the claim", "States the opposing view at its strongest, then answers it"],
    steps: [
      { name: "Retrieve Claim and Evidence", minutes: 5, body: "Given a claim, name a piece of evidence that supports it. Confirm the base before adding counterclaim work.", science_tag: "retrieval" },
      { name: "Relevant to What?", minutes: 10, body: "Evidence relevant to the topic but not the claim. Students spot the gap. This distinction is subtle and worth the time.", science_tag: "elaboration" },
      { name: "Steelman the Opposition", minutes: 12, body: "Write the other side's argument at its strongest. Students argue against their own position. Straw men die here.", science_tag: "elaboration" },
      { name: "Rank the Counterclaims", minutes: 10, body: "Which opposing argument is hardest to answer? That is the one worth addressing. Picking the easy one is a tell.", science_tag: "interleaving" },
      { name: "Rebut Without Dismissing", minutes: 12, body: "Model concede-then-counter: 'While it is true that…, the evidence shows…'. Students draft their rebuttal.", science_tag: "dual-coding" },
      { name: "Assemble the Argument", minutes: 10, body: "Claim, evidence, counterclaim, rebuttal in order. One full pass, not a polished draft.", science_tag: "collaborative" },
      { name: "Swap and Challenge", minutes: 6, body: "Partners read and try to break the argument. Note which parts held.", science_tag: "spaced" },
    ],
    ef_supports: ["Claim/evidence/counterclaim/rebuttal organizer", "Concede-then-counter sentence frames", "Counterclaim ranking sheet", "Steelman requirement in writing"],
    tech: "Printed organizers",
    tech_purpose: "Keep the four moves distinct while drafting",
    ai_prompts: ["Generate debatable grade 8 claims with strong opposing arguments", "Write evidence that is topic-relevant but claim-irrelevant"],
    assessment: ["Check counterclaims are genuine, not straw men", "Confirm evidence supports the claim specifically", "Partner challenge finds the weak joints"],
    why_it_works: ["Steelmanning is what separates argument from persuasion", "Ranking counterclaims stops students addressing only the easy one", "Concede-then-counter is a concrete, reusable move", "Peer challenge surfaces weaknesses before grading does"],
  },
  {
    standard_code: "K.OA.A.1",
    title: "Showing Adding and Taking Away",
    badge: "Kindergarten",
    route_name: "Concrete-Representational-Abstract",
    route_line: "Act it out → Draw it → Write it",
    success_criteria: ["Acts out a situation with objects", "Draws a picture matching the story", "Connects the drawing to an equation"],
    steps: [
      { name: "Retrieve Counting", minutes: 5, body: "Count sets of objects. Accurate counting has to be there before anything is combined.", science_tag: "retrieval" },
      { name: "Act Out Adding", minutes: 10, body: "Three children join two children. Students are the manipulatives. Physical before pictorial.", science_tag: "dual-coding" },
      { name: "Act Out Taking Away", minutes: 8, body: "Same setup, children leave. Name the difference between the two situations.", science_tag: "dual-coding" },
      { name: "Draw the Story", minutes: 12, body: "Students draw with counters, then on paper. Check the drawing matches the story, not just the answer.", science_tag: "elaboration" },
      { name: "Count On", minutes: 10, body: "Model counting on from the bigger group rather than restarting at one. Faster, and it builds number sense.", science_tag: "elaboration" },
      { name: "Match Story to Equation", minutes: 10, body: "Story cards and equation cards. Students match. Symbols attach to situations they have already lived.", science_tag: "interleaving" },
      { name: "Show Me", minutes: 5, body: "Give a story. Each student shows it with objects or a drawing.", science_tag: "spaced" },
    ],
    ef_supports: ["Counters and physical acting out", "Drawing templates", "Story and equation matching cards", "Count-on modelling"],
    tech: "Counters and story cards",
    tech_purpose: "Physical modelling before symbols",
    ai_prompts: ["Generate kindergarten addition and subtraction stories within 10", "Create story-to-equation matching cards"],
    assessment: ["Check drawings match the story structure", "Note who still restarts counting at one", "Show-me check with objects"],
    why_it_works: ["Acting out with children makes the situation unmissable", "Drawings reveal whether the structure or just the answer was understood", "Counting on is a strategy upgrade worth teaching explicitly", "Matching attaches symbols to lived situations"],
  },
  {
    standard_code: "1.NBT.B.2",
    title: "Ten Ones Make One Ten",
    badge: "Grade 1",
    route_name: "Concrete-Representational-Abstract",
    route_line: "Bundle it → Draw it → Name the tens and ones",
    success_criteria: ["Bundles ten ones into one ten", "States how many tens and ones in a number", "Builds any two-digit number from tens and ones"],
    steps: [
      { name: "Retrieve Counting by Tens", minutes: 5, body: "Count by tens to 100. The pattern underpins bundling.", science_tag: "retrieval" },
      { name: "Bundle Ten Straws", minutes: 12, body: "Students count ten straws and band them. One bundle, one ten. Making the bundle is what makes unitizing real.", science_tag: "dual-coding" },
      { name: "Build Two-Digit Numbers", minutes: 12, body: "Given a number, build it with bundles and loose straws. Say it: four tens and three ones.", science_tag: "dual-coding" },
      { name: "Draw the Bundles", minutes: 10, body: "Sticks for tens, dots for ones. Move from objects to drawings while the meaning is fresh.", science_tag: "elaboration" },
      { name: "The Reversal Trap", minutes: 10, body: "Show 43 and 34 built side by side. Same digits, different amounts. Confront the confusion directly.", science_tag: "interleaving" },
      { name: "Say How Many Tens", minutes: 8, body: "Rapid: how many tens in 67? How many ones? Fast recall on built understanding.", science_tag: "retrieval" },
      { name: "Build and Check", minutes: 5, body: "One number each, built and named to a partner.", science_tag: "spaced" },
    ],
    ef_supports: ["Straws and rubber bands", "Place value mat", "Stick-and-dot drawing key", "Side-by-side reversal comparison"],
    tech: "Straws and bands",
    tech_purpose: "Students make the ten themselves rather than receive it",
    ai_prompts: ["Generate two-digit numbers including reversal pairs", "Create a tens-and-ones place value mat"],
    assessment: ["Watch bundling for accurate counts of ten", "Check builds match the spoken number", "Partner build-and-name check"],
    why_it_works: ["Physically making a bundle is what teaches unitizing", "Reversal pairs target the dominant misconception", "Stick-and-dot drawings bridge objects and numerals", "Saying tens and ones aloud reinforces the structure"],
  },
  {
    standard_code: "2.OA.B.2",
    title: "Fast Facts, Real Strategies",
    badge: "Grade 2",
    route_name: "Routine and Practice",
    route_line: "Name the strategies → Choose one → Build toward recall",
    success_criteria: ["Names a strategy that fits a given fact", "Adds and subtracts within 20 accurately", "Recalls single-digit sums without counting"],
    steps: [
      { name: "Daily Fact Retrieval", minutes: 5, body: "Timed set of known facts. Short and daily. This routine, not the lesson, is what builds fluency.", science_tag: "retrieval" },
      { name: "Doubles and Near Doubles", minutes: 10, body: "6 + 6 is known, so 6 + 7 is one more. Build the near-double off the double explicitly.", science_tag: "elaboration" },
      { name: "Make a Ten", minutes: 12, body: "8 + 5 becomes 8 + 2 + 3. Model with a ten-frame so the bridging is visible, not verbal.", science_tag: "dual-coding" },
      { name: "Which Strategy Fits", minutes: 12, body: "Facts sorted by strategy before solving. Choosing is the skill; the answer follows.", science_tag: "interleaving" },
      { name: "Subtraction as Missing Addend", minutes: 10, body: "13 - 8 becomes 8 plus what makes 13. Connect subtraction to the addition facts already being built.", science_tag: "elaboration" },
      { name: "Mixed Speed Round", minutes: 8, body: "Addition and subtraction shuffled. Mixing prevents autopilot within one operation.", science_tag: "interleaving" },
      { name: "Track Your Facts", minutes: 3, body: "Students mark facts they now know from memory on a personal chart.", science_tag: "spaced" },
    ],
    ef_supports: ["Ten-frames for bridging", "Strategy sorting mats", "Personal fact-tracking chart", "Short daily sets rather than long sessions"],
    tech: "Ten-frames and fact cards",
    tech_purpose: "Make bridging through ten visible",
    ai_prompts: ["Generate fact sets grouped by best-fit strategy", "Create a personal fact fluency tracking chart"],
    assessment: ["Time the daily retrieval set", "Check strategy choices before answers", "Review personal fact charts over weeks"],
    why_it_works: ["Fluency comes from distributed daily retrieval, not one lesson", "Sorting by strategy before solving teaches selection", "Ten-frames make bridging concrete", "Personal tracking makes progress visible to the student"],
  },
  {
    standard_code: "3.NF.A.3",
    title: "Which Fraction Is Bigger?",
    badge: "Grade 3",
    route_name: "Concrete-Representational-Abstract",
    route_line: "Same whole → Compare by size → Show equivalence",
    success_criteria: ["Compares fractions of the same whole", "Explains why bigger denominator means smaller pieces", "Shows two equivalent fractions with a model"],
    steps: [
      { name: "Retrieve Unit Fractions", minutes: 5, body: "Name and draw 1/2, 1/4, 1/8. The size intuition starts here.", science_tag: "retrieval" },
      { name: "The Same Whole Rule", minutes: 10, body: "Show 1/2 of a small circle and 1/4 of a huge one. Which is bigger? The rule earns itself.", science_tag: "dual-coding" },
      { name: "Bigger Bottom, Smaller Piece", minutes: 12, body: "Fold identical strips into halves, fourths, eighths. Line them up. The inverse relationship becomes obvious.", science_tag: "dual-coding" },
      { name: "Compare with Strips", minutes: 10, body: "Given two fractions, students lay strips to compare. Physical comparison before any rule.", science_tag: "elaboration" },
      { name: "Find Equivalents", minutes: 12, body: "Which strips line up exactly? 1/2 and 2/4 and 4/8. Equivalence discovered, not told.", science_tag: "elaboration" },
      { name: "Benchmark to a Half", minutes: 8, body: "Is it more or less than 1/2? A fast comparison tool that works without common denominators.", science_tag: "interleaving" },
      { name: "Explain a Comparison", minutes: 3, body: "One student explains why 1/3 is bigger than 1/8.", science_tag: "spaced" },
    ],
    ef_supports: ["Identical-length fraction strips", "Same-whole demonstration", "Benchmark half reference line", "Number line for placing fractions"],
    tech: "Paper fraction strips",
    tech_purpose: "Identical wholes so comparisons are valid",
    ai_prompts: ["Generate fraction comparison pairs including same-numerator cases", "Create equivalence discovery tasks with fraction strips"],
    assessment: ["Check comparisons use the same whole", "Listen for bigger-denominator-means-bigger reasoning", "Individual explanation of a comparison"],
    why_it_works: ["The different-wholes demo makes the caveat in the standard concrete", "Identical strips let the inverse relationship be seen, not memorised", "Discovering equivalence beats being shown it", "Benchmarking to a half is a durable estimation tool"],
  },
  {
    standard_code: "4.NF.B.3",
    title: "Counting Fifths and Sevenths",
    badge: "Grade 4",
    route_name: "Concrete-Representational-Abstract",
    route_line: "Decompose into unit fractions → Add by counting → Handle mixed numbers",
    success_criteria: ["Decomposes a fraction into unit fractions", "Adds and subtracts like denominators without changing the denominator", "Regroups mixed numbers when subtracting"],
    steps: [
      { name: "Retrieve Unit Fractions", minutes: 5, body: "What is 3/4 made of? Three one-fourths. This framing carries the whole lesson.", science_tag: "retrieval" },
      { name: "Decompose Everything", minutes: 10, body: "Break fractions into unit fractions on paper. 5/8 as five one-eighths. Repetition builds the habit.", science_tag: "dual-coding" },
      { name: "Adding Is Counting", minutes: 12, body: "3 eighths plus 2 eighths is 5 eighths — the same way 3 apples plus 2 apples is 5 apples. The denominator is the unit name.", science_tag: "elaboration" },
      { name: "Why the Bottom Stays", minutes: 10, body: "Ask why the denominator does not change. Return to the apples. This heads off the classic error before it forms.", science_tag: "elaboration" },
      { name: "Subtract the Same Way", minutes: 10, body: "Counting backwards in the same unit. Model on a number line marked in that unit.", science_tag: "dual-coding" },
      { name: "Mixed Numbers", minutes: 12, body: "Convert to improper fractions, compute, convert back. Include one that needs regrouping.", science_tag: "interleaving" },
      { name: "Explain the Denominator", minutes: 3, body: "One student explains why 1/5 + 2/5 is not 3/10.", science_tag: "spaced" },
    ],
    ef_supports: ["Fraction strips marked in unit fractions", "Number lines in the working denominator", "Apples analogy anchor chart", "Improper fraction conversion reference"],
    tech: "Fraction strips and number lines",
    tech_purpose: "Show that adding fractions is counting units",
    ai_prompts: ["Generate like-denominator problems including mixed numbers", "Create decomposition tasks for fractions greater than one"],
    assessment: ["Check denominators stay unchanged", "Review decompositions for accuracy", "Individual explanation of why the denominator holds"],
    why_it_works: ["Naming the denominator as the unit makes addition obviously counting", "The apples analogy is retrievable under pressure", "Preempting the add-the-denominators error beats correcting it", "Unit-marked number lines keep the model consistent"],
  },
  {
    standard_code: "5.NBT.A.1",
    title: "Ten Times and One Tenth",
    badge: "Grade 5",
    route_name: "Explicit Instruction",
    route_line: "Extend the chart → Move both directions → Explain the pattern",
    success_criteria: ["Names places on both sides of the decimal point", "States a digit's value in context", "Explains the ten-times and one-tenth relationships"],
    steps: [
      { name: "Retrieve Whole Number Places", minutes: 5, body: "Name places to the thousands. The decimal extension only works on a solid base.", science_tag: "retrieval" },
      { name: "Extend Past the Point", minutes: 10, body: "Add tenths and hundredths to the chart. Note the symmetry — and that there is no 'oneths'.", science_tag: "dual-coding" },
      { name: "Ten Times to the Left", minutes: 10, body: "Move a digit left, value multiplies by ten. Do it with the same digit in several positions.", science_tag: "elaboration" },
      { name: "One Tenth to the Right", minutes: 12, body: "The same move backwards. Ask the one-tenth question as often as the ten-times one — students usually only learn one direction.", science_tag: "elaboration" },
      { name: "Same Digit, Different Value", minutes: 10, body: "In 3.33, what is each 3 worth? How do they relate? The comparison makes the pattern explicit.", science_tag: "interleaving" },
      { name: "Multiply and Divide by Ten", minutes: 10, body: "Connect the pattern to computation. Digits shift; the decimal point is a reference, not the thing moving.", science_tag: "dual-coding" },
      { name: "Explain Both Ways", minutes: 3, body: "One student explains the relationship in both directions.", science_tag: "spaced" },
    ],
    ef_supports: ["Place value chart crossing the decimal point", "Same-digit comparison examples", "Digit-shift demonstration cards", "Symmetry annotation on the chart"],
    tech: "Place value charts",
    tech_purpose: "Show both sides of the decimal point at once",
    ai_prompts: ["Generate numbers with repeated digits across decimal places", "Create place value charts extending to thousandths"],
    assessment: ["Check both directions are understood, not just ten-times", "Review same-digit value comparisons", "Individual explanation covering both relationships"],
    why_it_works: ["Teaching only the left-to-right direction leaves the standard half-covered", "Repeated digits make the relationship impossible to miss", "The symmetry of the chart is a memorable structure", "Linking to computation makes the pattern useful, not decorative"],
  },
  {
    standard_code: "6.NS.A.1",
    title: "How Many Fit Inside?",
    badge: "Grade 6",
    route_name: "Concrete-Representational-Abstract",
    route_line: "Model how many fit → Find the pattern → Justify the rule",
    success_criteria: ["Models a fraction division with a visual", "Computes quotients of fractions", "Explains why multiplying by the reciprocal works"],
    steps: [
      { name: "Retrieve Fraction Multiplication", minutes: 5, body: "Quick products. Division will lean on this immediately.", science_tag: "retrieval" },
      { name: "How Many Halves in Three", minutes: 10, body: "Ask before any notation. Students answer six from reasoning. Then write 3 ÷ 1/2 = 6 and let the surprise land.", science_tag: "elaboration" },
      { name: "Model More Divisions", minutes: 12, body: "How many 1/4s in 2? How many 1/3s in 5/6? Strips and number lines. Answers come from the model, not a rule.", science_tag: "dual-coding" },
      { name: "Find the Pattern", minutes: 10, body: "Table the results next to the fractions. Students spot that dividing by 1/2 matches multiplying by 2.", science_tag: "elaboration" },
      { name: "Name the Rule", minutes: 8, body: "Multiply by the reciprocal — now as a discovered summary rather than a given procedure.", science_tag: "dual-coding" },
      { name: "Word Problems", minutes: 12, body: "Real contexts. Students say what the question is asking before computing — that is where the wrong fraction gets inverted.", science_tag: "interleaving" },
      { name: "Justify the Rule", minutes: 3, body: "One student explains why dividing by a fraction gives a bigger answer.", science_tag: "spaced" },
    ],
    ef_supports: ["Fraction strips and number lines", "Pattern table linking division to multiplication", "Question-restating frame for word problems", "Reciprocal reference"],
    tech: "Fraction strips",
    tech_purpose: "Answer division by measuring before any rule exists",
    ai_prompts: ["Generate fraction division word problems in real contexts", "Create a pattern table linking division by a fraction to multiplication"],
    assessment: ["Check models produce correct quotients before the rule", "Confirm students restate the question in word problems", "Individual justification of the reciprocal rule"],
    why_it_works: ["Answering from a model first means the rule explains something already known", "The counterintuitive bigger answer needs confronting head on", "Restating the question prevents inverting the wrong fraction", "Discovering the pattern makes the rule memorable"],
  },
  {
    standard_code: "7.RP.A.2",
    title: "Is It Proportional?",
    badge: "Grade 7",
    route_name: "Multiple Representations",
    route_line: "Test tables → Test graphs → Write the equation",
    success_criteria: ["Tests a table for a constant multiple", "Identifies proportionality on a graph via the origin", "Writes y = kx with the correct constant"],
    steps: [
      { name: "Retrieve Unit Rate", minutes: 5, body: "Find unit rates from two tables. The constant of proportionality is this idea renamed.", science_tag: "retrieval" },
      { name: "Two Tables", minutes: 10, body: "One proportional, one not. Students find what distinguishes them. The constant multiple emerges from the comparison.", science_tag: "elaboration" },
      { name: "Test Tables", minutes: 10, body: "Several tables, proportional or not. Students test each by dividing y by x throughout.", science_tag: "interleaving" },
      { name: "Graph Them", minutes: 12, body: "Plot both kinds. The proportional one is a straight line through the origin. Students name both conditions — straight is not enough.", science_tag: "dual-coding" },
      { name: "The Origin Matters", minutes: 10, body: "Show a straight line missing the origin. Not proportional. This is the most common misidentification.", science_tag: "elaboration" },
      { name: "Write the Equation", minutes: 12, body: "From table or graph to y = kx. Find k in each representation, including reading the point where x is 1.", science_tag: "interleaving" },
      { name: "Identify Across Forms", minutes: 3, body: "Same relationship as table, graph and equation. Students find k in all three.", science_tag: "spaced" },
    ],
    ef_supports: ["Graph paper", "Table testing procedure card", "Non-proportional straight line counterexample", "y = kx frame"],
    tech: "Graph paper and printed tables",
    tech_purpose: "See the origin condition rather than be told it",
    ai_prompts: ["Generate proportional and non-proportional table pairs", "Create straight-line graphs that miss the origin"],
    assessment: ["Check table testing divides throughout, not once", "Confirm both graph conditions are named", "Verify k is found correctly across representations"],
    why_it_works: ["The near-miss counterexample targets the dominant error", "Testing throughout, not once, catches the additive trap", "Multiple representations are named in the standard itself", "Finding k in all three forms proves transfer"],
  },
  {
    standard_code: "7.NS.A.1",
    title: "Moving Both Ways on the Number Line",
    badge: "Grade 7",
    route_name: "Explicit Instruction",
    route_line: "Model on the line → Rewrite subtraction → Compute confidently",
    success_criteria: ["Models addition and subtraction on a number line", "Rewrites subtraction as adding the opposite", "Computes with negative fractions and decimals"],
    steps: [
      { name: "Retrieve Ordering", minutes: 5, body: "Order a set of positive and negative numbers. Position must be secure before movement.", science_tag: "retrieval" },
      { name: "Adding as Movement", minutes: 10, body: "Adding a positive moves right, a negative moves left. Model several on a large number line.", science_tag: "dual-coding" },
      { name: "Zero Pairs", minutes: 10, body: "A number and its opposite make zero. Model with counters. This underpins everything that follows.", science_tag: "dual-coding" },
      { name: "Subtraction Becomes Addition", minutes: 12, body: "Rewrite every subtraction as adding the opposite. Do it mechanically at first — fluency in the rewrite comes before understanding deepens.", science_tag: "elaboration" },
      { name: "The Double Negative", minutes: 10, body: "5 - (-3). Model it. Students see why the answer grows. The most persistent confusion in this standard.", science_tag: "elaboration" },
      { name: "Beyond Integers", minutes: 10, body: "Negative fractions and decimals. Same moves, harder numbers. The standard says rational, not integer.", science_tag: "interleaving" },
      { name: "Explain a Double Negative", minutes: 3, body: "One student explains why subtracting a negative adds.", science_tag: "spaced" },
    ],
    ef_supports: ["Large floor or wall number line", "Two-color counters for zero pairs", "Rewrite-as-addition checklist", "Negative fraction examples"],
    tech: "Number lines and two-color counters",
    tech_purpose: "Make sign changes movements rather than rules",
    ai_prompts: ["Generate rational number problems including negative fractions", "Create double-negative problems with number line models"],
    assessment: ["Check every subtraction is rewritten", "Confirm number line models match the computation", "Individual explanation of subtracting a negative"],
    why_it_works: ["Rewriting subtraction removes an entire category of sign errors", "Zero pairs give a physical basis for the additive inverse", "The double negative needs explicit modelling or it never lands", "Extending past integers covers the standard as written"],
  },
  {
    standard_code: "8.G.B.7",
    title: "Finding the Missing Side",
    badge: "Grade 8",
    route_name: "Strategy Instruction",
    route_line: "Identify the hypotenuse → Substitute carefully → Solve and check",
    success_criteria: ["Identifies the hypotenuse before substituting", "Finds a missing hypotenuse or leg correctly", "Recognizes when the theorem does not apply"],
    steps: [
      { name: "Retrieve Squares and Roots", minutes: 5, body: "Perfect squares and their roots. Weak recall here slows everything downstream.", science_tag: "retrieval" },
      { name: "Mark the Right Angle First", minutes: 10, body: "Before any algebra, mark the right angle and the side opposite it. Make this the non-negotiable first move.", science_tag: "dual-coding" },
      { name: "Find the Hypotenuse", minutes: 12, body: "Straightforward cases where c is unknown. Substitute, compute, take the root. Build the routine.", science_tag: "elaboration" },
      { name: "Find a Leg", minutes: 12, body: "Now c is known and a leg is missing. Students must rearrange rather than pattern-match. This is where the marking pays off.", science_tag: "interleaving" },
      { name: "When It Does Not Apply", minutes: 10, body: "Include non-right triangles. Students must check before computing. Applying it blindly is the failure mode.", science_tag: "elaboration" },
      { name: "Real Contexts", minutes: 10, body: "Ladders, diagonals, screen sizes. Students draw and label the triangle before touching the formula.", science_tag: "collaborative" },
      { name: "Check for Reasonableness", minutes: 3, body: "Is the hypotenuse the longest side? A one-second check that catches most errors.", science_tag: "spaced" },
    ],
    ef_supports: ["Mark-the-right-angle routine", "Formula rearrangement reference", "Non-right triangle distractors", "Draw-and-label step for word problems"],
    tech: "Printed diagrams and grid paper",
    tech_purpose: "Diagrams to mark before substituting",
    ai_prompts: ["Generate right triangle problems mixing missing hypotenuse and missing leg", "Create problems including non-right triangles as distractors"],
    assessment: ["Check the right angle is marked before substitution", "Confirm leg problems are rearranged, not pattern-matched", "Reasonableness check on every answer"],
    why_it_works: ["Marking first prevents the leg-as-hypotenuse error", "Mixing missing-leg and missing-hypotenuse blocks pattern matching", "Non-right distractors force checking applicability", "The longest-side check is a fast, durable self-assessment"],
  },
];

await seedStandardsBatch({
  label: "Batch 2",
  standardsData,
  unpacksData,
  blueprintsData,
});
